### ISSUE TITLE
Intermittent missing files from composer install

### ISSUE THREAD

**Issue by timkelty** [composer/composer#6187] opened 2017-02-20 16:49 UTC
When I run `composer install`, I intermittently end up with an incomplete `vendor` folder. I don't see any errors or anything to indicate it didn't successfully install.

If I remove the `vendor` folder and `composer install` again, all is well.

This is a huge problem because I'm `composer install`ing on deploy, so it results in a broken deploy.

Here is an example of a file `diff` between two identical directories that `composer install` was run in. You'll notice one is missing a ton of files (and therefore broke the site on deploy). https://gist.github.com/timkelty/e1c2b4352730ab16d36f437ba1b3aa42

My only lead is this troubleshooting note: https://getcomposer.org/doc/articles/troubleshooting.md#zip-archives-are-not-unpacked-correctly- However, I don't even see details on where or what to set to change this.

**Comment by alcohol** [comment] 2017-02-21 10:10
First of all, Composer is not a deployment tool and it should not be used as such (you can, but you do so at your own risk). Now that we have that confusion out of the way, lets move on to your issue.

Can you give us anything that is reliably reproducible? If you cannot consistently reproduce it, than it more than likely is an environment issue, and not a Composer issue.

Can you give us more facts about your environment? What OS are you running? Are you always installing on your host system or are you using virtual machines? What OS is your production environment running?

**Comment by timkelty** [comment] 2017-02-21 12:42
@alcohol Thanks for the quick reply.

> Composer is not a deployment tool and it should not be used as such

Agreed - though just to clarify, I might argue I'm not really using it _as a deployment tool_, I just happen to be building dependencies on deploy .

The fact that it is not reliably reproducible is certainly part of the problem. This has happened intermittently across multiple devs/machines in our office (though all MacOS still) for as long as we've been including `composer install` as a step in our deployment.

In this case, we're always running this our local machines.

What I can tell you:

- local env: MacOS (Sierra in this case, but I have seen it this happen for quite a while), using composer and PHP compiled via Homebrew)
- remote env: Ubuntu, though this is isn't really relevant (inconsistent installs are happening on the local machine).
- To fix the issue, the `vendor` folder must be removed and `composer install` run again. Just running install will report `Nothing to install or update`.

**Comment by alcohol** [comment] 2017-02-21 13:06
Without a consistent reproducible scenario there is virtually nothing we can debug :-/

**Comment by timkelty** [comment] 2017-02-21 13:12
@alcohol I understand, I guess I'm looking for any known usual suspects that I might try and see what happens in the meantime.

Is there a way to specify the unzip method? Or will Composer use `unzip` if it is available from the CLI? _[Zip archives are not unpacked correctly.](https://getcomposer.org/doc/articles/troubleshooting.md#zip-archives-are-not-unpacked-correctly-)_ does sound like a likely culprit.

**Comment by alcohol** [comment] 2017-02-21 13:20
It is highly unlikely to be the culprit.
I do not believe there is a way to specify what unarchive method Composer should use.

**Comment by gergnz** [comment] 2017-02-21 21:03
FWIW, we are seeing a similar issue (it's only really started to happen in the last ~ 1 month.). It may not be related, but it sounds very similar.

OS is Ubuntu 14.04 (native php)

**Comment by timkelty** [comment] 2017-03-20 13:25
While I'm not entirely certain _how_ the packages end up partially installed, it appears (from my testing, at least) that when checking if a package is installed, composer seems to just look if the directory exists.

Example: https://github.com/timkelty/composer-test

Running `composer install` or `composer update` there will result in `Nothing to install or update`, even though the target install dirs are empty:
`vendor/composer/illuminate/support`
`craft/plugins/disqus` (via composer-installers)

Is there any way to tell composer to do a more robust check for deps when running install?

**Comment by alcohol** [comment] 2017-03-20 13:50
It also uses https://github.com/timkelty/composer-test/blob/master/vendor/composer/composer/installed.json

There is no reason for directories to suddenly go missing or be empty (no sane reasons at least), so I see no reason to add more robust checks.

**Comment by timkelty** [comment] 2017-03-20 14:14
@alcohol I archived the apps the last couple times this happened. In both cases seemingly all the directories were present, but none of the files.

![screen shot 2017-03-20 at 10 10 12 am](https://cloud.githubusercontent.com/assets/18329/24103514/e7658a0a-0d55-11e7-8322-76bbd832db17.png)

As it seems to be intermittent by definition, I'm not sure how to troubleshoot any further. All I know is that it happens intermittently, and I've seen it on at least 2 other machines (all Macs) in my office.

**Comment by alcohol** [comment] 2017-03-20 15:27
Does not sound like a composer issue in that case. Seems your method of archiving is broken.

**Comment by timkelty** [comment] 2017-03-20 16:01
@alcohol seems like it but, it should just be using OSX's `/usr/bin/unzip`.

I wonder if whole thing is in fact a Github issue with zips being corrupted from time to time. A quick search and there seems to be quite a few "github zip missing files" issues, e.g.: https://github.com/google/material-design-icons/issues/8

Maybe I'll try `--prefer-source`?

**Comment by raiffeisennet** [comment] 2017-11-13 13:35
same problem here... While executing composer install on one machine, it loads the dependency symfony/validator properly, on the other machine, a ValidatorBuilderInterface.php file is missing after a successful composer install.

**Comment by timkelty** [comment] 2017-11-13 13:57
@raiffeisennet @alcohol Still seeing this behavior (infrequently but consistently) across several users/machines in my office.

@alcohol is there anything I can do to help debug this when it happens?

**Comment by alcohol** [comment] 2017-11-13 14:05
Provide a reproducible scenario.

**Comment by Seldaek** [comment] 2018-04-13 09:31
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.

**Closed by Seldaek** 2018-04-13 09:31 UTC
Labels: Support

**Comment by Seldaek** [comment] 2018-04-13 12:35
Have you tried using --prefer-source as a workaround? It kinda sucks but I can't think of anything else here. If you can't reproduce it at all.. Composer essentially runs `unzip -qq path/to/package.zip vendor/composer/tempsomething`, and then after that what we do is list all files in `vendor/composer/tempsomething/*` and move them to `vendor/foo/bar`. I am thinking that perhaps that step is the one failing, if for some reason your filesystem is buggy and doesn't return all files that were just unzipped we might be missing a few. If you have files missing at a deeper level than the top level directory though that sounds unlikely to be the culprit as we only loop through the first level and move those files/dirs.

Where are you storing your project and vendor dirs? Are they on a plain OSX dir or is it a VM or some network share or something funky?

**Comment by timkelty** [comment] 2018-04-13 12:44
> Have you tried using --prefer-source as a workaround?
I'll give it a shot.

> Are they on a plain OSX dir or is it a VM or some network share or something funky?
Nope its a plain macOS/X dir, no VM or network.

The times I've noticed this the most is when we run composer install as part of our deploy process, in this case `composer install` is being initiated by node.js (`childProcess.exec`). There are no errors output to CLI when this occurs.

**Comment by Seldaek** [comment] 2018-04-13 13:02
I've literally never seen this other than in this issue (@gergnz and @raiffeisennet are you still experiencing this?), so I can't imagine it's something we do, but most likely some strange environment thing or a package you install that is messing with stuff sometimes. But if it doesn't even happen that often it is extremely hard to verify what causes it.

**Comment by gergnz** [comment] 2018-04-14 01:56
I've not heard anyone complain about for a while now, so I'm guessing whatever it was is either really intermittent or has been resolved.
