### ISSUE TITLE
Floating point rounding error

### ISSUE THREAD

**Issue by kleiram** [composer/composer#3669] opened 2015-01-23 12:25 UTC
As per [this](https://twitter.com/kleiram/status/558198762862944256) Twitter conversation.

Yesterday I received the following error when running `composer require fguillot/picofeed`:

```
- The requested package league/oauth2-client == 0.4.9999999.9999999-dev could not be found.
```

Below is a copy of my `composer.json`.

``` json
{
    "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.4",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "doctrine/mongodb-odm": "1.0.*@dev",
        "doctrine/mongodb-odm-bundle": "3.0.*@dev",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "knplabs/knp-menu": "~1.1",
        "kriswallsmith/buzz": "~0.10",
        "jms/serializer-bundle": "~0.13",
        "jms/security-extra-bundle": "~1.1",
        "willdurand/hateoas-bundle": "~0.2",
        "willdurand/rest-extra-bundle": "~1.0",
        "friendsofsymfony/rest-bundle": "~1.3",
        "friendsofsymfony/user-bundle": "2.0.*@dev",
        "nelmio/api-doc-bundle": "~2.5",
        "nelmio/cors-bundle": "~1.3",
        "league/oauth1-client": "~1.0",
        "league/oauth2-client": "dev-master",
        "themattharris/tmhoauth": "~0.8",
        "jublonet/codebird-php": "~2.4",
        "fzaninotto/faker": "~1.3",
        "facebook/php-sdk-v4": "4.0.*",
        "ql/uri-template": "~1.0",
        "mantle/mantle": "dev-master",
        "dropbox/dropbox-sdk": "1.1.*",
        "league/flysystem": "0.4.*",
        "snc/redis-bundle": ">=1.1,<2.0",
        "predis/predis": "0.8.*",
        "jeremykendall/php-domain-parser": "1.3.*",
        "linkedinapi/linkedin": "~1.0",
        "widop/google-analytics-bundle": "~1.0",
        "commerceguys/guzzle-oauth2-plugin": "~1.0",
        "raven/raven": "0.*",
        "belt/matter": "dev-master",
        "belt/aggregator": "dev-master",
        "belt/underscore": "dev-master",
        "friendsofsymfony/oauth-server-bundle": "~1.4"
    },
    "require-dev": {
        "willdurand/faker-bundle": "1.2.*",
        "doctrine/doctrine-fixtures-bundle": "2.2.*"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": {
            "dev-master": "2.4-dev"
        }
    }
}
```

Personally, I have a feeling that this is a one-off error (because of floating point rounding errors), since I'm not able to reproduce it but I've created a issue because Twitter is not the best place for this kind of things (in my opinion).

**Comment by danemacmillan** [comment] 2015-01-26 23:20
I'm receiving a similar issue since updating composer today:

```
[145.4MB/49.46s] Updating dependencies (including require-dev)
[482.9MB/58.07s] Your requirements could not be resolved to an installable set of packages.
[482.9MB/58.07s]
  Problem 1
    - The requested package twig/twig == 1.17.9999999.9999999-dev could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

**Comment by Seldaek** [comment] 2015-01-30 20:32
Can't reproduce here unfortunately :/

**Comment by danemacmillan** [comment] 2015-01-30 21:02
If it means anything, I actually rolled back the composer update and the issue was still there, so it was not related to the latest updates.

I had been playing around with the `minimum-stability` and `require` sections of `composer.json` file. I can't say for sure if it was the cause, but I know the error went away shortly after I reverted my changes. Ultimately, these were the steps I had:

**1. Create and install project with requirements such as these:**

```
...
  "minimum-stability": "dev",
  "require": {
    "php": ">=5.3.2",
    "linusshops/web-static": "dev-master@dev",
    "linusshops/web-utilities": "dev-master@dev",
  }
...
```

**2. Modify the `composer.json` file so it looks similar to this:**

```
...
  "minimum-stability": "dev",
  "require": {
    "php": ">=5.3.2",
    "linusshops/web-static": "dev-master",
    "linusshops/web-utilities": "dev-master",
  }
...
```

**3. Run `composer update`**

This is where composer would then start complaining. I had also changed some other version requirements to be specific tagged releases vs `*` or `dev-master@dev`. 

It's not a lot to go on, but this sort of jiggery caused the issue to arise. If I had more concrete steps, I would provide them, but unfortunately the issue arose nearly as randomly as it went away. These were the only changes I can remember that occurred around the time of these errors.

I have since made it go away by reinstalling (deleting and then running `composer install`) the whole project with the updated versions I wanted to use. This did not cause the exceptional floating point error. Maybe a conflict with the cache, or a conflict with the installed dependencies? Perhaps those installed dependencies did not react well to have their `composer.json` versions changed after an install and then `composer update` run.

The reason I had started this whole process of changing versions was because updates were taking an inordinate amount of time. I figured being more explicit with versions would speed up the process. In the end it did, but I had to delete and install the project again, as the version changes then update would not work.

**Comment by kleiram** [comment] 2015-01-30 22:04
@Seldaek I wasn't able to reproduce it either...

**Comment by kleiram** [comment] 2015-03-12 14:02
@Seldaek  I'm having this issue again, today ([this is the output of Composer](https://gist.github.com/kleiram/d6fc1a6d13db36dc4846)). I got it while running the following command:

```shell
$ composer require --dev matthiasnoback/symfony-dependency-injection-test "0.*" --profile -vvv
```

My [`composer.json`](https://gist.github.com/kleiram/c42026574f3faa7335be) (please ignore the mess) and [`composer.lock`](https://gist.github.com/kleiram/39994b8a5266d8278428) files. The version I'm running is `1.0-dev (b296e654eb3e136ca6fa08fa3bcb1d4782c13f8b)`. I've ran this command multiple times and each time I'm getting this error so it is not very rare for me...

I hope this helps!

**Comment by sminnee** [comment] 2015-07-02 11:24
I have a feeling that this is caused by the league/oauth2-client deleting their `0.8.x-dev` version. Specifically, the master branch is aliased to `0.8.x-dev`, and then once 0.8 is released, the master branch is re-aliased to `0.9.x-dev`.

Something is caching the dev-master -> 0.8.x-dev alias and then is unable to find 0.8.x-dev.

**Comment by sminnee** [comment] 2015-07-02 12:06
OK I figured out a replicable case for this:

 * `mkdir tmp && cp tmp && composer init`
 * `composer require league/oauth2-client:dev-master`
 * Edit composer.lock and change the branch alias value for oauth2-client to 0.8.x-dev
 * `composer require league/commonmark` (just a random package)

You'll get the error. Note that you don't get the error if you run composer update instead of composer require at the 4th step.

My high-level diagnosis is that the update execution after `composer require` is failing to refresh the composer.lock file to the same extent that `composer update` does, and that this causes edge-case errors such as this one.

My suggested fix would be to refresh composer.lock more thoroughly as part of the `composer require` execution—to the same extent that `composer update` does. This might slow down `composer require`; is this a problem?

**Comment by sminnee** [comment] 2015-07-02 12:25
So, this fixes the issue, but I'm not sure of the performance implications: https://gist.github.com/e4f1a8952f5824333623

Assuming this fix is appropriate, we would want to deprecate the `--update-with-dependencies` option as well.

The other problem that this introduces is that a user may not wish to have other packages updated. Perhaps this behaviour should only be triggered if an `--update-all` argument is provided, and then we can add a sentence below the error message:

"You could try running composer req

**Comment by Seldaek** [comment] 2015-07-02 12:38
@sminnee basically --update-with-dependencies right now is the equivalent of your --update-all workaround. And no that fix is likely not appropriate as it breaks partial updates :) But thanks for figuring out a repro case. That might allow a closer inspection of what goes wrong.

**Comment by curry684** [comment] 2016-03-08 23:25
This is not a floating point error, just an internal trick to ensure `dev` packages have highest priority when allowed by stability. The real issue is interesting but I'm tempted to say it's highly academical, may even have been a race condition between Packagist and Github pushes causing the mismatch. I'm not sure we should care enough about it as this is to my knowledge the only bug report on it ever.

**Comment by Seldaek** [comment] 2017-12-19 13:04
Closing as it's not clear what to do anyway here.

**Closed by Seldaek** 2017-12-19 13:04 UTC
Labels: Bug
