### ISSUE TITLE
composer.json not writable

### ISSUE THREAD

**Issue by npelov** [composer/composer#8232] opened 2019-07-17 09:12 UTC
My `composer.json`:

```json
{
  "name": "company/package",
  "description": "description",
  "minimum-stability": "dev",
  "license": "proprietary",
  "authors": [
    {
      "name": "Nick",
      "email": "email@example.com"
    }
  ]
}

```

Output of `composer diagnose`:

```
 diagnose --no-interaction --ansi --verbose
 Checking composer.json: OK
 Checking platform settings: OK
 Checking git settings: OK
 Checking http connectivity to packagist: OK
 Checking https connectivity to packagist: OK
 Checking github.com rate limit: OK
 Checking disk free space: OK
 Checking pubkeys: 
 Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
 Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
 OK
 Checking composer version: OK
 Composer version: 1.8.6
 PHP version: 5.6.33
 PHP binary path: D:\php\php.exe
 Composer diagnosed no issues in ./composer.json.
```

When I run this command on a network drive (linux samba share mounted on windows 7):

```
Z:\webroot>D:\php\php D:\php\composer\composer.phar require aldas/modbus-tcp-client:1.1.1 --no-progress --no-interaction --ansi
```

I get the following output:

```
./composer.json is not writable.
```

I don't get the same problem when not on a network drive. The composer.json is writable - I checked.

**Comment by alcohol** [comment] 2019-07-17 11:53
Possibly a duplicate of #8231 in terms of issue (potential bug).

**Comment by alcohol** [comment] 2019-07-17 11:57
Looks related https://bugs.php.net/bug.php?id=68926

**Comment by alcohol** [comment] 2019-07-17 11:59
Closing because the other issue is pretty much identical and was reported earlier.

**Closed by alcohol** 2019-07-17 11:59 UTC
Labels: Support

**Comment by RaviFefar** [comment] 2020-08-10 04:39
Check the owner of composer.json.

`ls -lh ~/.composer/composer.json`

Now run below command:

`sudo chown -R yourusername:yourusername ~/.composer/composer.json`

**Comment by npelov** [comment] 2020-08-10 06:57
As alcohol suggested the problem is in php bug:
https://bugs.php.net/bug.php?id=68926

Owner is ok because the file can be written just fine.
