### ISSUE TITLE
Internal Error [ERR_LOGIC]: An internal script did not run correctly (exit code 1)

### ISSUE THREAD

**Issue by Tatenda** [composer/composer#3526] opened 2014-12-09 14:37 UTC
I have been trying to install composer and all i keep getting is the following error Internal Error [ERR_LOGIC]: An internal script did not run correctly (exit code 1)

**Comment by 4ung** [comment] 2015-09-16 07:28
Below is the full log help me please.

2015-09-16 13:43:17.764   Log opened. (Time zone: UTC+06:30)
2015-09-16 13:43:17.764   Setup version: Inno Setup version 5.5.4 (u)
2015-09-16 13:43:17.764   Original Setup EXE: C:\Users\Aung\Downloads\Programs\Composer-Setup.exe
2015-09-16 13:43:17.764   Setup command line: /SL5="$704B6,220038,119296,C:\Users\Aung\Downloads\Programs\Composer-Setup.exe" /SPAWNWND=$604C6 /NOTIFYWND=$5032A /LOG="C:\Users\Aung\Downloads\log.txt"
2015-09-16 13:43:17.764   Windows version: 6.3.9600  (NT platform: Yes)
2015-09-16 13:43:17.764   64-bit Windows: Yes
2015-09-16 13:43:17.764   Processor architecture: x64
2015-09-16 13:43:17.764   User privileges: Administrative
2015-09-16 13:43:17.764   64-bit install mode: No
2015-09-16 13:43:17.764   Created temporary directory: C:\Users\Aung\AppData\Local\Temp\is-TFP22.tmp
2015-09-16 13:43:17.779   Extracting temporary file: C:\Users\Aung\AppData\Local\Temp\is-TFP22.tmp\composer
2015-09-16 13:43:17.795   Extracting temporary file: C:\Users\Aung\AppData\Local\Temp\is-TFP22.tmp\setup.class.php
2015-09-16 13:43:17.795   Extracting temporary file: C:\Users\Aung\AppData\Local\Temp\is-TFP22.tmp\setup.php
2015-09-16 13:43:17.795   DEBUG:: Getting path info from registry
2015-09-16 13:43:20.025   DEBUG:: User selected Shell Menus: Do not install
2015-09-16 13:43:20.604   DEBUG:: Checking php: C:\xampp\php\php.exe
2015-09-16 13:43:20.729   DEBUG:: Calling cmd.exe with params: /c "C:\xampp\php\php.exe setup.php -- --php --debug > C:\Users\Aung\AppData\Local\Temp\is-TFP22.tmp\result.txt"
2015-09-16 13:43:20.807   DEBUG:: Checking php: error [ERR_INVALID]
2015-09-16 13:43:22.916   Deinitializing Setup.
2015-09-16 13:43:22.916   DEBUG:: Setup cancelled or aborted
2015-09-16 13:43:22.916   Log closed.

**Comment by johnstevenson** [comment] 2015-09-16 08:46
@4ung The error message [ERR_INVALID] means that the installer has not been able to run php.exe  for some reason.

Try running ```C:\xampp\php\php.exe -v``` from a command prompt to see what the problem is.

**Comment by 4ung** [comment] 2015-09-16 12:12
@johnstevenson :'( i just degrade to windows 8 and its ok now

**Comment by Seldaek** [comment] 2016-02-27 17:04
Closing this here, please report again at https://github.com/composer/windows-setup/issues if still relevant

**Closed by Seldaek** 2016-02-27 17:04 UTC
