### ISSUE TITLE
Composer breaks when ran in directory with mercurial repo

### ISSUE THREAD

**Issue by dusan-rd** [composer/composer#6235] opened 2017-03-08 15:07 UTC
My `composer.json`:

```json
{
    "name": "test/test",
    "require": {}
}
```

Output of `composer diagnose`:

```
  [ErrorException]                 
  Illegal string offset 'version'  
```

When I run this command:

```
composer
```

I get the following output:

```        
  [ErrorException]                 
  Illegal string offset 'version'  
```

And I expected this to happen:
At least show help.
Composer version 1.3.3 2017-03-08 11:06:43

Having minimal composer.json and mercurial repo on default branch in the same directory breaks composer.

To recreate the problem run
```
composer install
hg init
composer
```
The error stems from `VersionGuesser::guessHgVersion`, which can return string instead of an array. The fix for Issue  #6178, which was merged in 1.3.3, expects  `guessHgVersion` to return an array.

Adding version to composer.json will stop VersionGuesser and circumvent the problem.

**Comment by hkdobrev** [comment] 2017-03-08 15:16
Failing test in #6236

**Comment by Seldaek** [comment] 2017-03-08 16:13
Alright, pushed fix, can someone please confirm it works with latest snapshot (`composer self-update --snapshot`)? /cc @Slamdunk

**Closed** 2017-03-08 16:12 UTC

**Comment by Slamdunk** [comment] 2017-03-08 16:15
I can confirm `Composer version 1.4-dev (843877cd6d3d8b81a4b176679fc107060dfc28b5) 2017-03-08 16:12:13` resolves the bug.

**Comment by Seldaek** [comment] 2017-03-08 16:22
Alright perfect thanks, will tag 1.4.0 in a bit then

**Comment by Seldaek** [comment] 2017-03-08 16:58
1.4.0 is out if you wanna get back to the stable update channel

**Comment by hkdobrev** [comment] 2017-03-08 16:58
@Seldaek Could you elaborate on why this is in 1.4.0 instead of 1.3.4? Many thanks!

**Comment by Seldaek** [comment] 2017-03-08 17:07
Because the 1.3 branch died with 1.3.3 and I was ready to release 1.4 so might as well fold the fix in there instead of doing yet another release just for one commit.
