### ISSUE TITLE
Something wrong on windows 10

### ISSUE THREAD

**Issue by slince** [composer/composer#5605] opened 2016-08-17 13:07 UTC
![image](https://cloud.githubusercontent.com/assets/3785826/17737056/9e8cebca-64bd-11e6-9e1d-fa37f16c70ce.png)
There are some special characters. So weird!

**Comment by slince** [comment] 2016-08-17 13:28
I seem to know why. But is there a good solution?

**Comment by stof** [comment] 2016-08-17 14:01
Well, Windows 10 is meant to support ANSI chars in the console now. Looks like it does not support them in all cases...

**Comment by stof** [comment] 2016-08-17 14:02
note that you can always force to disable the ANSI colors with the ``--no-ansi`` option

**Comment by slince** [comment] 2016-08-17 14:34
@stof That sounds terrible.

**Comment by alcohol** [comment] 2016-08-18 07:33
Duplicate of #5323

**Closed by alcohol** 2016-08-18 07:33 UTC

**Comment by cirdog** [comment] 2016-08-26 04:27
If this hasn't been mentioned before, the global workaround for Windows is:

```
C:\ProgramData\ComposerSetup\bin\composer.bat
(edit its content)
php "%~dp0composer.phar" %* --no-ansi
```

Adding the "--no-ansi" flag at the launch script of composer eliminates the need to flag it for every command.

**Comment by slince** [comment] 2016-08-26 07:27
@cirdog  good idea!

**Comment by YetiCGN** [comment] 2016-09-05 09:49
Bower and Grunt seem to be able to output colors just fine on Windows 10 Anniversary Update cmd.exe console. Why not Composer?
Oh well ... I will switch to another shell for now.

**Comment by YetiCGN** [comment] 2016-09-05 10:04
Yeah, the default is switched to --no-ansi on Windows apparently, that doesn't bring back the colors, though. :-) I rather continue using the stable version but in PowerShell. Thanks for the info, though.
