### ISSUE TITLE
Multiple issues - SLOW and sometimes zlib_decode(): data error

### ISSUE THREAD

**Issue by sgrover** [composer/composer#4267] opened 2015-07-17 20:34 UTC
I've searched and seen lots of mention of these issues, but can't seem to find the "right" answer for my environment.

I'm running on a Rackspace server and for the past week or so have seen composer running out of memory  (restarting Apache and running composer clears that up).  I'm also seeing incredibly long composer updates the last two days.  These delays sometimes timeout, other times not.  To help with the slow issue I wanted to install Satis and get it involved.  But I can't install Satis via Composer either.  I get the following output:
```
composer create-project composer/satis --stability=dev --keep-vcs -vvv --profile
[4.4MB/0.01s] Downloading https://packagist.org/packages.json
[4.4MB/0.70s] Writing /root/.composer/cache/repo/https---packagist.org/packages.json into cache
[4.5MB/0.70s] Reading /root/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
[4.5MB/0.70s] Reading /root/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
[4.5MB/0.70s] Reading /root/.composer/cache/repo/https---packagist.org/p-provider-2014-10.json from cache
[4.5MB/0.70s] Reading /root/.composer/cache/repo/https---packagist.org/p-provider-2015-01.json from cache
[4.5MB/0.70s] Downloading http://packagist.org/p/provider-2015-04$1a19264843cfeadbcd43f4b600abe85c444dd595a0e868e13a74699d934ced7e.json
[5.2MB/120.62s] Downloading http://packagist.org/p/provider-2015-04$1a19264843cfeadbcd43f4b600abe85c444dd595a0e868e13a74699d934ced7e.json
[6.0MB/335.41s] Downloading http://packagist.org/p/provider-2015-04$1a19264843cfeadbcd43f4b600abe85c444dd595a0e868e13a74699d934ced7e.json


                             
  [ErrorException]           
  zlib_decode(): data error  
                             


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:218
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 zlib_decode() at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:218
 Composer\Util\RemoteFilesystem->get() at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:83
 Composer\Util\RemoteFilesystem->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:596
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:503
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:273
 Composer\Repository\ComposerRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionSelector.php:48
 Composer\Package\Version\VersionSelector->findBestCandidate() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:280
 Composer\Command\CreateProjectCommand->installRootPackage() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:140
 Composer\Command\CreateProjectCommand->installProject() at phar:///usr/local/bin/composer/src/Composer/Command/CreateProjectCommand.php:129
 Composer\Command\CreateProjectCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25


create-project [-s|--stability="..."] [--prefer-source] [--prefer-dist] [--repository-url="..."] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-scripts] [--no-progress] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [package] [directory] [version]
```
You can see the huge delay just before the crash - 120.62 seconds, then 335.41 seconds.

This all points to a problem with Composer within my environment (at least) and is making it un-usable for my situation.  (Composer is called in multiple Jenkins build scripts, so it's really affecting the whole function of the server...)

I am running a Ubuntu server with the latest PHP version available for it (5.5.9)

I'll install Satis via download for now, but I'm still looking for hints.  Thanks bunches!

**Comment by sgrover** [comment] 2015-07-17 20:34
Forgot to mention, I have cleared my cache with no difference...  And I have outright removed the .composer directory as well, same results.

**Comment by slbmeh** [comment] 2015-07-17 21:30
It's a recommended practice to update on your development machine and install from a lock file on the target server/build server.

**Comment by sgrover** [comment] 2015-07-17 21:44
thanks.  The lock file is included in the repo and in place on the target box that is exhibiting the issues.  But this may be a lack of knowledge/understanding on my part as well...  Do you mean checking in the vendor directory?

**Comment by slbmeh** [comment] 2015-07-17 22:02
No. The action that consumes the most memory with composer is resolving the dependencies. It appears the create-project command resolves the dependencies as well. If you were to do a git clone of the project followed by a composer install it should utilize far less memory.

**Comment by sgrover** [comment] 2015-07-17 22:36
makes sense.  The performance issue is also happening for projects like that.  My build jobs sync from git, copies the files to the right location, does a composer update, then changes file permissions.  The LONG delays/failures are happening in those cases as well.  I even tried creating a new simple project last night with a single required project in the composer.json (one of my packages, not a framework), and still saw those delays when I did a composer update.  

Thanks for the responses.  I'm still looking for the cause, but I can work around the issue for now.

**Comment by slbmeh** [comment] 2015-07-17 22:39
The composer update is generally the cause. With loose dependency constraints it could consume a lot of memory evaluating potential candidates for installation as you go through the dependency graph.

**Comment by sgrover** [comment] 2015-07-18 07:29
Initial testing with Satis, and using the { "packagist":false } made a world of difference for one project at least.  Needed to track down the usual top level packages that Laravel uses and set them up in Satis, but otherwise things went quickly then.  It's a bit of a pain to have to do this just to get reasonable performance (sub 20 minute updates), but using Satis opens other opportunities too.  I hope this is a transitory problem that gets resolved quickly though - seems I'm not the only one seeing this sort of issue on an ongoing basis.

**Comment by frederikbosch** [comment] 2015-07-18 12:38
Duplicate of #4121. This one can be closed.

**Comment by frederikbosch** [comment] 2015-07-18 21:16
According to recebt believes in #4121 this is due to IPv6. Please discuss there your own findings.

**Comment by Seldaek** [comment] 2015-07-20 17:13
I pushed an attempt at fixing this which downgrades to http/1.0 and forces ipv4 if any of the connection timeout or the gzip decoding errors are detected, then it should retry the download and subsequent downloads will also be downgraded. That prints a red message because this really should not happen if networks weren't broken, but it seems this is necessary right now if we want to keep IPv6 going (I do, because some people rely on that, and because it's the future no matter how slowly it's coming. If we don't fix routing issues things will never progress).

Please try again using latest composer.phar (or selfupdate in travis builds) to see if it helps at all. I am especially curious to see if a build that soft-fails and prints the red warning can still succeed afterwards or not.

But anyway please refer to #4121 for further comments

**Closed by Seldaek** 2015-07-20 17:13 UTC
