### ISSUE TITLE
Tar Archives Need Parity with Zip Archives

### ISSUE THREAD

**Issue by astorm** [composer/composer#5206] opened 2016-04-16 21:18 UTC
In [this accepted pull request](https://github.com/composer/composer/pull/5144#issuecomment-205021044), the behavior of archiving has been changed such that zip files are now archiving empty folders. This is a welcome change, as it removes some barriers to using Satis with Magento 2's official Composer repository, as well as other repositories of projects that rely on empty directories.

Is a similar change needed for the tar archives as well? i.e. that pull request only changes the behavior of zip files.  This fixes the Magento problem since their repository is using ZIP archives, but it seems like the composer project would want its archiving systems behaving identically -- i.e. if zip files archives and unarchive empty directories, then tar archives should do the same things.  

If the Magento repository ever switched to tar archives, or a user (like me) attempted to create a satis mirror with tar archives instead of zip files, "weird things" might happen.  I did some initial tests and, when I created projects from a satis mirror using tar archives created from Magento's repository, the empty folders were represented as empty, 0 byte regular files.  I can work around this by mirroring with ZIPs -- but the fundamental difference between the archiving methods remain.

Apologies for not having a pull request on this, or a better test description/reproduction steps.  I'm not familiar enough with the composer and satis projects to tackle that without breaking things, and wanted to make sure I'm not making any derpy assumptions before I go to the trouble of creating a reproducible test case.

**Comment by ktomk** [comment] 2016-04-17 21:16
@astorm: I can reproduce what you describe. It's because `PharData::buildFromIterator()` does not differ between a file and a directory, always creating one tempfile per iterator entry.

I've just changed the code to be the same as used for zip files and test it to run right now.

**Comment by ktomk** [comment] 2016-04-17 22:01
As `PharData::buildFromIterator()` seems to be much faster. I opened a feature request upstream:

* [Request #72046 	PharData::buildFromIterator() directory support](https://bugs.php.net/bug.php?id=72046)

**Comment by ktomk** [comment] 2016-04-17 22:27
Update the PR to a variant that uses `buildFromIterator` again and then adds the directories.

**Comment by Seldaek** [comment] 2016-04-18 08:29
Fixed by #5208

**Closed** 2016-04-18 08:29 UTC
