### ISSUE TITLE
Resolver error with specific dependencies on php 7.0

### ISSUE THREAD

**Issue by alexander-schranz** [composer/composer#9018] opened 2020-06-28 00:34 UTC
My `composer.json`:

```json
{
    "name": "handcraftedinthealps/elasticsearch-bundle",
    "description": "Elasticsearch bundle for Symfony.",
    "type": "symfony-bundle",
    "homepage": "http://ongr.io",
    "license": "MIT",
    "authors": [
        {
            "name": "ONGR team",
            "homepage": "http://www.ongr.io"
        },
        {
            "name": "Handcrafted in the Alps Team",
            "homepage": "https://github.com/handcraftedinthealps/ElasticsearchBundle/graphs/contributors"
        }
    ],
    "require": {
        "php": ">=5.5",
        "symfony/symfony": "^2.7",
        "doctrine/annotations": "~1.2",
        "doctrine/inflector": "~1.0",
        "doctrine/cache": "~1.4",
        "monolog/monolog": "~1.10",
        "elasticsearch/elasticsearch": "^2.1.3",
        "handcraftedinthealps/elasticsearch-dsl": "^2.1.2"
    },
    "require-dev": {
        "mikey179/vfsstream": "~1.4",
        "phpunit/phpunit": "~4.8 || ~5.6",
        "squizlabs/php_codesniffer": "~2.0",
        "satooshi/php-coveralls": "~1.0"
    },
    "autoload": {
        "psr-4": { "ONGR\\ElasticsearchBundle\\": "" },
        "exclude-from-classmap": ["/Tests/", "/Test/"]
    },
    "replace": {
        "ongr/elasticsearch-bundle": "self.version"
    },
    "minimum-stability": "dev"
}
```

Output of `composer diagnose`:

```
- # not sure error returned by travis php7.0 composer snapshot bee91155a136659429b4b46f4290ea6aa3c09943
```

When I run this command:

```
php7.0 /usr/local/bin/composer install
```

I get the following output:

```                    
  [Composer\DependencyResolver\SolverBugException]                             

  Reached invalid decision id 0 while looking through (74|75|76|77|78|79|80|8  

  1|82|83|84|85|86|87|88|89|90|91|92|93|94|95|96|97|98|99|100|101|102|103|104  

  |105|106|107|108|109|110|111|112|113|114|115|116|117|118|119|120|121|122|12  

  3|124|125|126|127|128|361) for a literal present in the analyzed rule (-361  

  |437|438|439|440|441|442|443|444|445|446|447|448|449|450|451|452|453|454|45  

  5|456|457|458|459|460|461|462|463|464|2414).                                 

  This exception was most likely caused by a bug in Composer.                  

  Please report the command you ran, the exact error you received, and your

  composer.json on https://github.com/composer/composer/issues - thank you!   
```

See https://travis-ci.org/github/handcraftedinthealps/ElasticsearchBundle/jobs/702410938

Not reproduceable locally or on php7.1: https://travis-ci.org/github/handcraftedinthealps/ElasticsearchBundle/jobs/702775584

And I expected this to happen:

Successfully install dependencies

**Comment by Seldaek** [comment] 2020-06-29 13:53
Could be related to https://github.com/composer/composer/issues/7665 / https://github.com/composer/composer/pull/8733

**Comment by Seldaek** [comment] 2020-10-16 10:00
Closing as duplicate of https://github.com/composer/composer/issues/9294

**Closed by Seldaek** 2020-10-16 10:00 UTC
