### ISSUE TITLE
Problem on load namespaced functions

### ISSUE THREAD

**Issue by IgorDePaula** [composer/composer#11291] opened 2023-02-03 14:44 UTC
Composer don`t load function inside namespaces, like is written in php manual.

https://www.php.net/manual/en/language.namespaces.basics.php

project structure:

---root
 |---src
    |---Hello
       |---echo.php
    |---World
       |---Name.php
  |---vendor
   index.php
   composer.json

```json
//composer.json
{
    "name": "igor/phpnamespacetest",
    "autoload": {
        "psr-4": {
            "App\\": "src/"
        }
    },
    "authors": [
        {
            "name": "Igor de Paula",
            "email": "************@gmail.com"
        }
    ],
    "require": {}
}
```

```php
//index.php
<?php

require('vendor/autoload.php');

$w = new \App\World\Name();

$w->eco('Hi');
```

```php
//echo.php
<?php

namespace App\Hello;

function eco($t){
    echo $t;
}
```

```php
//Name.php

<?php

namespace App\World;

use function App\Hello\eco;

class Name
{
    public function eco($t)
    {
        eco($t);
    }
}
```

**Comment by IgorDePaula** [comment] 2023-02-03 14:45
![image](https://user-images.githubusercontent.com/2833993/216632064-3880a26b-cd5b-4923-9b33-28781243a1d4.png)

**Comment by xabbuh** [comment] 2023-02-03 14:50
You can namespace functions, but you need to take care of loading the files they are contained in yourself. PHP doesn't support autoloading functions.

**Comment by IgorDePaula** [comment] 2023-02-03 14:57
If I write all in one single file, they works. But not in different files, in this case, who load is composer.

**Comment by Seldaek** [comment] 2023-02-03 19:02
You can list all your function files in the autoload config then they will be included every time and they'll be available, but you cannot autoload them on demand like classes https://getcomposer.org/doc/04-schema.md#files - if you have lots of them it may be easier to use static methods on classes as those can be autolaoded.

**Comment by IgorDePaula** [comment] 2023-02-03 19:26
By this reason this is a bug, not follow php pattern.

**Comment by Seldaek** [comment] 2023-02-03 20:10
This is not a bug, there is no way to autoload functions in PHP.

**Comment by IgorDePaula** [comment] 2023-02-03 20:11
And what is right way?

**Comment by Seldaek** [comment] 2023-02-03 20:26
Your options are up there https://github.com/composer/composer/issues/11291#issuecomment-1416277570

**Comment by IgorDePaula** [comment] 2023-02-03 23:18
Yes, admitting that there is a mistake takes courage. 

Composer is not conform to php.

**Comment by Seldaek** [comment] 2023-02-04 13:20
If you can explain me how it is **not conform** exactly then perhaps we can move this forward, but as is I don't see what kind of mistake I should admit here. So either you have the courage to explain what we can improve or we close this..

**Comment by IgorDePaula** [comment] 2023-02-04 13:27
https://www.php.net/manual/en/language.namespaces.basics.php


    Relative file name like foo.txt. This resolves to currentdirectory/foo.txt where currentdirectory is the directory currently occupied. So if the current directory is /home/foo, the name resolves to /home/foo/foo.txt.
    Relative path name like subdirectory/foo.txt. This resolves to currentdirectory/subdirectory/foo.txt.
    Absolute path name like /main/foo.txt. This resolves to /main/foo.txt.


```php
<?php
namespace Foo\Bar\subnamespace;

const FOO = 1;
function foo() {}
class foo
{
    static function staticmethod() {}
}
?>
```


https://www.php.net/manual/en/language.namespaces.importing.php

```php
<?php
namespace foo;
use My\Full\Classname as Another;

// this is the same as use My\Full\NSname as NSname
use My\Full\NSname;

// importing a global class
use ArrayObject;

// importing a function
use function My\Full\functionName;

// aliasing a function
use function My\Full\functionName as func;

// importing a constant
use const My\Full\CONSTANT;

$obj = new namespace\Another; // instantiates object of class foo\Another
$obj = new Another; // instantiates object of class My\Full\Classname
NSname\subns\func(); // calls function My\Full\NSname\subns\func
```

according to the php manual, I can load a namespaced function, but composer does not do.

**Comment by Seldaek** [comment] 2023-02-04 13:32
That page is using filesystem as an example because the resolution of namespace happens the same (relative to your current namespace, or relative to your current path in filesystem), but there is NO autoloading for functions, only using classes trigger the php autoloader (which is then calling Composer's autoloader to locate the class in the right package).

So if you want namespaced functions, you need to include the files yourself, or use Composer `files` autoloading so it always includes these files to make them available. Again and for one last time, there is no other way. You can try doing this without Composer if you think Composer is the problem, you won't be able to without including files explicitly.

**Comment by IgorDePaula** [comment] 2023-02-04 13:36
"....you won't be able to without including files explicitly."

And how to work with classes?

**Comment by IgorDePaula** [comment] 2023-02-04 13:37
PSR-4 is using filesystem too. If I call the class by your name and your namespace like filesystem, I got with functions too. No differences.

**Comment by Seldaek** [comment] 2023-02-04 13:40
See https://getcomposer.org/doc/01-basic-usage.md#autoloading and https://getcomposer.org/doc/04-schema.md#autoload for classes.

Functions do not trigger the autoloader so cannot be autoloaded. I'm unsubscribing from this thread as I feel like you are not willing to listen.

**Closed by Seldaek** 2023-02-04 13:40 UTC
Labels: Support

**Comment by IgorDePaula** [comment] 2023-02-04 14:07
Are I not willing to listen? The manual php shows that is possible, I showed to you technical articles proving my case and  you don't want to admit that is a bug.
I showed courage for anwsuered you, and you not showed me courage for admit that is a bug.

**Comment by IgorDePaula** [comment] 2023-02-04 14:09
You know what happens to that cocky attitude? A competitor is born. Not from me, since to you I'm dumb and ignorant. But someone does.

**Comment by IgorDePaula** [comment] 2023-02-04 14:10
Is bug becasue is not conform php. Read the php manual.

**Comment by IgorDePaula** [comment] 2023-02-04 14:15
Is more easy says this is not a bug.

**Comment by IgorDePaula** [comment] 2023-02-04 14:25
Please @yesdevnull , @PrinsFrank , @eliashaeussler , @digitalgrease , @pankali , @rafaelstz , @greew , @kubawerlos , @staabm , @jeffwidman , @zanbaldwin , @ralflang , @dmitryuk

**Comment by ralflang** [comment] 2023-02-04 14:29
I don't think PSR-4 is about standalone functions. Composer supports other loader instructiins though which would do what you need.

**Comment by staabm** [comment] 2023-02-04 14:36
as others already stated, php cannot autoload functions. unsubscribing.

**Comment by IgorDePaula** [comment] 2023-02-04 14:44
> as others already stated, php cannot autoload functions. unsubscribing.

How not, if the manual said that yes? Composer does not load, but the manual said yes.

PSR-4 not look for the php manual.

**Comment by ralflang** [comment] 2023-02-04 14:47
The manual page on namespaces does not even mention autoloading. By default, PHP does not autoload anything and only provides builtins, extensions and the code in explicitly loaded/required files.

**Comment by zanbaldwin** [comment] 2023-02-04 14:52
Things the documentation does say you can do with namespaced functions: load, import, resolve.
Things the documentation doesn't say you can do with namespaced functions: autoload.

Of the [939 contributors to Composer](https://github.com/composer/composer/graphs/contributors), why was I mentioned? 🤔

**Comment by IgorDePaula** [comment] 2023-02-04 14:55
@ralflang What you are telling me is that the autoload must be done anyway and not as the php manual predicts?

@zanbaldwin You have recent commits, I thought it was part of the core.

**Comment by ralflang** [comment] 2023-02-04 15:02
It might be helpful if you quote the exact phrase you are referring to. PHP makes no assumption how you structure your code and what goes into which file. This is totally  up to you and PHP will by itself not follow any policy. It allows you to register one or many pieces of php code (autoloaders) that look up code from files. PSR-0 and PSR-4 are standards (rules) on what is looked up where. Both deal with classes and class-likes (Interfaces, structures) but not functions. Composer ships with an implementation of PSR-4 and some other schemes. It supports the "files" autoloader that allows to load files with arbitrary code, including functions in namespaces.

But you need to explicitly choose that in your composer.json, regenerate the autoloader (dump-autoload) and tell PHP to use composer's autoloader. That's the require vendor/autoload.php line you see in almost every composer root project.

I hope that helps.

**Comment by IgorDePaula** [comment] 2023-02-04 15:07
@ralflang, sorry, but:

"...PHP makes no assumption how you structure your code and what goes into which file. ...". 

I showed this: https://github.com/composer/composer/issues/11291#issuecomment-1416750883

**Comment by greew** [comment] 2023-02-04 15:29
@IgorDePaula 

You've been told multiple times now, that PHP doesn't support autoloading of namespaced functions.
You've been told multiple times that Composer doesn't support autoloading of namespaced functions because PHP doesn't support it.

You keep on saying, that you think Composer has a bug, because you think the PHP documentation says otherwise.

THEN:
If you actually believe, that PHP does support autoloading of namespaced functions, please show us an example of how you would achieve this without using Composer. If you actually are able to do this, then we might get into a discussion about it, but until then I'm outta here!

**Comment by IgorDePaula** [comment] 2023-02-04 15:48
@greew People said yes, but without PoC, or technical article, I still showed something, something concrete, the php manual, but nobody showed anything but their own words. If php doesn't support namespaced functions, why does it have that in the manual? Clearly there is a fault here, and it's not mine.

**Comment by greew** [comment] 2023-02-04 15:58
@IgorDePaula You clearly chose to ignore what @zanbaldwin said before:

> Things the documentation does say you can do with namespaced functions: load, import, resolve. 
> Things the documentation doesn't say you can do with namespaced functions: autoload.

Of the two links you provided to the PHP core, neither of them tells us anything about autoloading. They only show us how to deal with namespaced classes, function and constants when they have already been loaded, either by already being in the same file as the calling code, by being loaded by `require`/`import` or by using `spl_autoload_register`.

If you take a look at https://www.php.net/manual/en/language.oop5.autoload.php you will see that this is very precisely called "Autoloading Classes". There is no mention of autoloading functions or consts. Actually, the comment https://www.php.net/manual/en/language.oop5.autoload.php#124770 tells us as the first thing, that autoloading functions is not supported in PHP.

You now ask us to provide a PoC or technical article about how this is NOT possible?

You also say, you have showed us something concrete. Good - I have not taken those same two documentation articles and shown you even another one, that what you say can be accomplished, is not supported in PHP.

**Comment by kubawerlos** [comment] 2023-02-04 16:15
@IgorDePaula I see you describe yourself as Technology Lover, so why don't you raise PR with a feature to autoload namespaced functions?

**Comment by zanbaldwin** [comment] 2023-02-04 16:41
> I see you describe yourself as Technology Lover, so why don't you raise PR with a feature to autoload namespaced functions?

Autoloading functions would be a wonderful addition to PHP! @IgorDePaula if they're not working how you think they should, you should make a pull request on https://github.com/php/php-src to add them! A PR for the docs to make those pages more understandable would also be a wonderful contribution :)

**Comment by PrinsFrank** [comment] 2023-02-04 16:41
@IgorDePaula Please don't tag random contributors because you don't get the answer you want. Now a bunch of people got a notification and are automatically subscribed to this thread. Is this thread really what you want other open source developers to remember about you? Please be kind and accepting when some of the smartest people in the PHP community give you an answer and try to help you, even if you don't like that answer.

**Comment by IgorDePaula** [comment] 2023-02-05 00:57
@greew both links php manual sais abaout use filesystem for load namespaced functions.

@kubawerlos according to your friends above, I'm dumb and don't understand php, so I'm unable to do something like that.

@zanbaldwin I sent rfc for another caso to php-list 2 months ago. No response (my first rfc).

@PrinsFrank as you can be random but I think an open source project should have no owner. Latest committers could be part of the project. I didn't tag several people for not liking the answer, but for being treated like an imbecile. No one has read the php manual and seen that there, in text, not in code, talks about how the namespaced functions should be loaded, with the file system. from what they said, composer uses php functions, so why use composer if I can use native loading functions myself? 

https://github.com/composer/composer/issues/11291#issuecomment-1416750883

https://www.php.net/manual/en/language.namespaces.basics.php

Relative file name like foo.txt. This resolves to currentdirectory/foo.txt where currentdirectory is the directory currently occupied. So if the current directory is /home/foo, the name resolves to /home/foo/foo.txt.
Relative path name like subdirectory/foo.txt. This resolves to currentdirectory/subdirectory/foo.txt.
Absolute path name like /main/foo.txt. This resolves to /main/foo.txt.


The loading is using filesystem, Read below.

**Comment by greew** [comment] 2023-02-05 05:33
> @greew both links php manual sais abaout use filesystem for load namespaced functions.

You keep on saying that the PHP documentation says something about loading - it does not!

Number of times the word load or autoload is mentioned in the following links:

- https://www.php.net/manual/en/language.namespaces.basics.php: 1 - used in the menu DownLOAD.
- https://www.php.net/manual/en/language.namespaces.importing.php: 3 - the first one used in the menu DownLOAD, and the second two used in a comment that actually also states, that `The <?php use ?> statement does not load the class file. You have to do this with the <?php require ?> statement or by using an autoload function.` (https://www.php.net/manual/en/language.namespaces.importing.php#114265).

You also keep on saying that the PHP documentation mentions using filesystem for loading namespace functions - it also does not.

https://www.php.net/manual/en/language.namespaces.basics.php:
![image](https://user-images.githubusercontent.com/189321/216802935-32b90a9f-f544-4e7c-99b2-0cf10442cd3b.png)

The filesystem text you keep mentioning does not say anything about that you can load the namespaced stuff. Actually this is the same for for the filesystem itself, that you keep mentioning. By entering the filename in a simple text editor or a command line, the file will not be loaded. You will have to use a program to open the file. 
This is the same in PHP - you have to load the namespaced stuff into the file first. This usually happens with [`include`](https://www.php.net/manual/en/function.include.php) or one of it's friends `require`, `include_once`, `require_once`. 

But instead of having to manually load all files that you have to use, the PHP core have added a function called [`spl_autoload_register()`](https://www.php.net/spl_autoload_register). As the documentation on that page says, it's about autoloading classes - NOT functions.

> @PrinsFrank as you can be random but I think an open source project should have no owner. Latest committers could be part of the project. 

That might be how *you* think it should be, but since the majority of the GitHub community does not see it this way, you're taking a bad approach by just referencing a bunch of random people.

> No one has read the php manual and seen that there, in text, not in code, talks about how the namespaced functions should be loaded, with the file system. 

I hope you will go through this and my previous comments and actually try and read AND understand, what is being written.

**Comment by IgorDePaula** [comment] 2023-03-05 22:34
I found the solution
![namespaced function](https://user-images.githubusercontent.com/2833993/222989670-16c0d813-eeb7-4140-91a5-f904755a659e.png)

**Comment by kubawerlos** [comment] 2023-03-05 22:38
Yes 👍🏼, you did in a month ago, you have even pasted it in this discussion, search for "use function My\Full\functionName;"

**Comment by jean-pasqualini** [comment] 2024-05-07 18:56
@IgorDePaula 

I know this github is closed, but fyi here is how the function queuable is loaded. https://github.com/illuminate/events/blob/master/composer.json#L30

This load the file functions.php that contains the function declaration.
https://github.com/illuminate/events/blob/master/functions.php#L14

To understand how it works.
https://orkhan.dev/2020/02/25/how-to-register-your-global-functions/

when you require vendor/autoload.php, the files defined in the configuration autoload.files will be loaded at the same time.
so in this case, the autoload is not trigger by the first usage of the function.

when you do any composer dump-autoload, the file vendor/composer/autoload_files.php that contains all the files that composer need to load as soon as the file vendor/autoload.php is executed.

<img width="871" alt="image" src="https://github.com/composer/composer/assets/860090/ef1355e8-63f3-455a-a06e-29e107453477">

The first role of the composer package is to manage the dependencies:
- build the tree of dependencies of the constraints on the versions of them, then store this tree in composer.lock
- download these dependencie with the support of
   - http download of the archive then unarchive it
   - git clone of the code
   - symlink to a local folder
   - etc...
- ensure you are always installing the same version of these dependencies where you have tested your code
- make the updating of the dependencies easy

The second role of the composer package, is to help you using the dependencies by handling the autoload part for you.
- To achieve this on classes, the function https://www.php.net/manual/en/function.spl-autoload-register.php allows to execute a callback that receive the FQCN (Full Qualified Class Name) when you try to use a class that is not yet defined in the php memory. if your callback includes the file that contains the definitions so you won't get any error from php saying this class is undefined.
- To achiveve this on function, there is not autoload_register provided by php and so it's not possible to do it on fly. this means at the moment where you use this function for the first time. so the only way is to include yourself the file that contains these functions. composer has just provided a way to included this file at the moment where you are requiring vendor/autoload.php

I didn't see much part about how the autoload files works in composer in the official documentation of composer, maybe i've overlooked. 

I would be glad to add this kinda documentation if it not exists that you could review to ensure i give the nescessary level  of details and that my understanding is corect, plus any improvement, grammar and typos.

**Comment by browsermage** [comment] 2024-05-25 11:25
Thank you all for this thread even it was heated from times, I am new again to PHP and also thought that auto-loading was a thing for functions and const. It is easy to mix up the namespace feature and the spl_autoload_register function as one thing.

Thank you Composer Team ✨

**Comment by frannylac** [comment] 2025-01-12 06:41
I didn't read all comments but until [this reply](https://github.com/composer/composer/issues/11291#issuecomment-1416277570) i thought that i didn't want to add every file manually to .autoload.files array so i wrote a simple php script to do it.

This is a simplification without comments and validations but do the job pretty well. Basically it's recursively search all `fn_*.php` files and load them into .autoload.files array at composer.json file to finally execute `composer dump-autoload` command.

```php
#!/usr/bin/php
<?php

define( "COMPOSER_FILE", "composer.json" );
define( "FILE_PREFIX", "fn_" );
define( "SEARCH_PATH", "src/" );

$iterator = new RecursiveIteratorIterator( new RecursiveDirectoryIterator( SEARCH_PATH ) );
$fn_files = [];

foreach ( $iterator as $file ) {
    if ( $file->isFile() && substr( $file->getFileName(), 0, strlen( FILE_PREFIX ) ) == FILE_PREFIX )
        array_push( $fn_files, $file->getPathName() );
}

$data = json_decode( file_get_contents( COMPOSER_FILE ), TRUE );
$data["autoload"]["files"] = $fn_files;
$data = json_encode( $data, JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE );

file_put_contents( COMPOSER_FILE, $composerJson );

exec( "composer dump-autoload", $cmd_output );
echo implode( "\n", $cmd_output )."\n";

?>
```

Put it into `loadfn.php` next to `composer.json` file and `src` folder and given execution permissions with `chmod +x loadfn.php` and run it every time you need to add elements into .autoload.files.
