### ISSUE TITLE
Composer 2 does not write explicitly required dependency in composer.lock

### ISSUE THREAD

**Issue by samdark** [composer/composer#9490] opened 2020-11-17 11:31 UTC
Composer 2 does not write explicitly required dependency in composer.lock. The dependency is `"psr/http-factory": "^1.0"`. After `composer update` it's not in `composer.lock` and, thus, not in `vendor`. With Composer 1 it works as expected.

My `composer.json`:

```json
{
    "name": "yiisoft/app-api",
    "type": "project",
    "description": "Yii Framework API project template",
    "keywords": [
        "yii3",
        "app",
        "api",
        "rest"
    ],
    "homepage": "https://github.com/yiisoft/app-api/",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/app-api/issues?state=open",
        "forum": "https://www.yiiframework.com/forum/",
        "wiki": "https://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/app-api"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": "^7.4|^8.0",
        "cebe/markdown": "^1.2@dev",
        "cycle/orm": "^1.2",
        "cycle/proxy-factory": "^1.2",
        "myclabs/php-enum": "^1.7",
        "httpsoft/http-message": "^1.0.5",
        "psr/container": "^1.0",
        "psr/http-factory": "^1.0",
        "psr/http-message": "^1.0",
        "psr/http-server-handler": "^1.0",
        "psr/http-server-middleware": "^1.0",
        "psr/log": "^1.1",
        "yiisoft/access": "^1.0",
        "yiisoft/aliases": "^1.0",
        "yiisoft/arrays": "^3.0@dev",
        "yiisoft/auth": "^1.0",
        "yiisoft/cache": "^3.0@dev",
        "yiisoft/cache-file": "^3.0@dev",
        "yiisoft/composer-config-plugin": "^1.0@dev",
        "yiisoft/data": "^3.0@dev",
        "yiisoft/data-response": "^3.0@dev",
        "yiisoft/di": "^3.0@dev",
        "yiisoft/error-handler": "^3.0@dev",
        "yiisoft/factory": "^3.0@dev",
        "yiisoft/http": "^1.0@dev",
        "yiisoft/injector": "^1.0",
        "yiisoft/json": "^1.0",
        "yiisoft/log": "^3.0@dev",
        "yiisoft/log-target-file": "^3.0@dev",
        "yiisoft/request-body-parser": "^3.0@dev",
        "yiisoft/request-model": "^1.0@dev",
        "yiisoft/router": "^3.0@dev",
        "yiisoft/router-fastroute": "^3.0@dev",
        "yiisoft/security": "^1.0",
        "yiisoft/serializer": "^3.0@dev",
        "yiisoft/strings": "^1.0",
        "yiisoft/validator": "^3.0@dev",
        "yiisoft/var-dumper": "^3.0@dev",
        "yiisoft/yii-console": "^3.0@dev",
        "yiisoft/yii-cycle": "^3.0@dev",
        "yiisoft/yii-debug": "^3.0@dev",
        "yiisoft/yii-event": "^3.0@dev",
        "yiisoft/yii-web": "^3.0@dev",
        "yiisoft/yii-debug-api": "^3.0@dev"
    },
    "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Tests\\": "tests/",
            "App\\Tests\\Acceptance\\": "tests/acceptance/"
        }
    },
    "scripts": {
        "post-update-cmd": [
            "App\\Installer::postUpdate"
        ],
        "test": [
            "phpunit --colors --no-interaction"
        ]
    },
    "extra": {
        "branch-alias": {
            "dev-master": "1.0.x-dev"
        },
        "config-plugin-output-dir": "runtime/build/config",
        "config-plugin": {
            "common": "config/common/*.php",
            "params": [
                "config/params.php",
                "?config/params-local.php"
            ],
            "web": [
                "$common",
                "config/web/*.php"
            ],
            "console": [
                "$common",
                "config/console/*.php"
            ],
            "events": "config/events.php",
            "events-web": [
                "$events",
                "config/events-web.php"
            ],
            "events-console": [
                "$events",
                "config/events-console.php"
            ],
            "providers": "config/providers.php",
            "providers-web": [
                "$providers",
                "config/providers-web.php"
            ],
            "providers-console": [
                "$providers",
                "config/providers-console.php"
            ],
            "routes": "config/routes.php"
        },
        "config-plugin-alternatives": {
            "tests": {
                "params": "config/params-test.php"
            }
        }
    },
    "config": {
        "sort-packages": true
    },
    "require-dev": {
        "codeception/codeception": "^4.1",
        "codeception/lib-innerbrowser": "^1.3",
        "codeception/module-asserts": "^1.0.0",
        "codeception/module-db": "^1.0",
        "codeception/module-phpbrowser": "^1.0.0",
        "codeception/module-rest": "^1.2",
        "vimeo/psalm": "^4.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.4.11
PHP binary path: D:\wnmp-dev\php74\php.exe
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.70.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 2 updates, 1 removal
  - Removing psr/http-factory (1.0.1)
  - Downgrading tuupola/cors-middleware (1.2.1 => 1.2.0)
  - Downgrading tuupola/http-factory (1.3.0 => 1.0.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 2 updates, 1 removal
  - Removing psr/http-factory (1.0.1)
  - Downgrading tuupola/http-factory (1.3.0 => 1.0.1): Extracting archive
  - Downgrading tuupola/cors-middleware (1.2.1 => 1.2.0): Extracting archive
Generating autoload files
Assembling config files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
117 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
> App\Installer::postUpdate
```

And I expected this to happen:

`psr/http-factory` makes it to `composer.lock` and is installed.

**Comment by stof** [comment] 2020-11-17 11:41
this is probably a duplicate of #9316 and #9308.
Composer 2 actually fixed a weird behavior of Composer 1, where `provide` rules where not fully respected when a package exists and is also provided by another one. What happens here is that `tuupola/http-factory` version 1.0.1 and older had a wrong `provide` rule (providing `psr/http-factory` instead of `psr/http-factory-implementation`).
The best fix here (considering that `tuupola/http-factory` fixed this issue a long time ago) is to forbid using old broken versions of the package. This can either be done by changing the min version in your constraint (`tuupola/cors-middleware` 1.2.1 already did it for its requirement, so then you would have to check where this package is required, to require at least 1.2.1) or by adding a conflict rule in your composer.json to forbid using `tuupola/http-factory` in versions `<1.0.2`.

**Comment by samdark** [comment] 2020-11-17 15:54
@stof thanks. I'll check it in detail. Is there a FAQ with a list of such changes?

**Comment by samdark** [comment] 2020-11-17 17:21
Related to https://github.com/composer/composer/issues/9308

**Comment by Seldaek** [comment] 2020-11-18 20:51
The only possible fix is for broken packages to release new versions, and for people to update to them. Sorry but it's just not something we can add back in Composer 2 as it is invalid behavior. It's just unfortunate we didn't spot this for so long in v1 so the issue spread silently :/

**Closed by Seldaek** 2020-11-18 20:51 UTC
Labels: Support

**Comment by samdark** [comment] 2020-11-18 21:35
@Seldaek why does `"tuupola/cors-middleware": "^1.2"` install 1.2.0 when 1.2.1 is available?

**Comment by Seldaek** [comment] 2020-11-18 21:36
Probably because it found that first and saw that it satisfied the psr/http-factory requirement.. And picking 1.2.1 would require installing psr/http-factory instead so it's like two valid solutions to the dependencies, which one gets picked is kinda random.

**Comment by samdark** [comment] 2020-11-18 21:37
Could it be made that highest possible version of dependency is picked when there's a case like that? That would potentially solve alike issues.

**Comment by Seldaek** [comment] 2020-11-18 21:38
No that's not possible I'm afraid.. There are cases where you can have A 1 & B 2 or A 2 & B 1 installed for example.. Which is the highest one there? It's not that simple unfortunately.

**Comment by samdark** [comment] 2020-11-18 21:43
Depends on which dependency is less transitive, I guess. Project level having top priority. But yes, I have very vague idea of current SAT solver so I understand that it could be complicated.

**Comment by naderman** [comment] 2020-11-18 22:23
@samdark What you are suggesting is actually an NP complete optimization problem if you do this across more complex dependency structures, this would slow things down a lot, so not a good idea to try and optimize this beyond what we already do. There are also different ways to define what's ideal, e.g. what if your highest level dependency ("less transitive" in your words) can be installed only if 5 more transitive deps are installed in an older version, but they can all be installed in the newst if the less transitive dep is installed in a lower version, wouldn't that be better? 5 up to date rather than just 1? Gets even more complicated because dependencies change over time, so the newer and older versions of these packages may have different dependencies altogether which in turn pose new optimization questions, etc.

Don't think there's anything further to discuss here.

**Comment by stof** [comment] 2020-11-20 16:25
@naderman does this even make sense to allow `provide` to replace an existing package (rather than being for virtual packages only) ? Shouldn't `replace` be the feature used when the name is an actual package (as the code would then be duplicate if you install both) ?
AFAICT, that corresponds to what Composer 1 did: respect `provide` rules only for virtual packages.
