### ISSUE TITLE
Local symlinked package deleted on update

### ISSUE THREAD

**Issue by mabar** [composer/composer#6117] opened 2017-01-31 13:20 UTC
```
"repositories": [
        {
            "type": "path",
            "url": "modex-packages/core",
            "options": {
                "symlink": true
            }
        }
],
"require": {
        "modex/core": "^0.0.7@alpha"
},
```
After changing modex/core version in composer.json is command composer update modex/core deleting source folder.

Console output

```
C:\Web\Modex>composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating modex/core (0.0.6-alpha => 0.0.7-alpha)  - Removing modex/core (0.0.6-alpha)
    Update failed (Source path "modex-packages/core" is not found for package modex/core)
    Would you like to try reinstalling the package instead [yes]? yes
  - Removing modex/core (0.0.6-alpha)


  [RuntimeException]
  Package modex/core cannot install to "C:\Web\Modex\modex-packages\core" inside its source at
   "C:\Web\Modex\modex-packages\core"
```

modex/core is not using VCS, I am just changing version in it's composer.json

Composer should just update autoload file when updating symlinked package

**Comment by alcohol** [comment] 2017-02-01 08:31
Looks like a user error to me.

**Comment by alcohol** [comment] 2017-02-01 09:09
Please provide a reproducible scenario (make a github repo).

**Comment by curry684** [comment] 2017-02-01 12:15
The error seems to indicate you have a `vendor-dir` override from `vendor` to `modex-packages`. If so the error you're seeing is correct and intentional. Also, that error is thrown before actual removal so please elaborate on your issue report: are you actually seeing the folder being deleted or are you saying "Composer is incorrectly *intent* on deleting my source folder"?

**Comment by mabar** [comment] 2017-02-01 13:02
Problematic scenario:
User creates repository with type path and option symlink and do composer require.
Changes version of package and runs composer update. Composer deletes package from vendor directory and because it is a symlink so source folder is deleted too.

**Comment by curry684** [comment] 2017-02-01 14:49
Again: are you *seeing* the folder actually being *deleted*. A reproducible scenario, as alcohol suggests, demonstrating *actual incorrect deletion* would be required to consider this a bug. To my best knowledge (and I'm the one who added it) that exception is thrown before deletion is even attempted. Exactly because it would cause incorrect recursive deletion of source files.

**Comment by Seldaek** [comment] 2017-02-25 18:23
Closing as we don't have enough info to reproduce..

**Closed by Seldaek** 2017-02-25 18:23 UTC
Labels: Support
