### ISSUE TITLE
Autoload dump uses cwd instead configured baseDir

### ISSUE THREAD

**Issue by mikeymike** [composer/composer#5012] opened 2016-03-06 13:28 UTC
hey guys... I'm working on a project for [PHPSchool](http://phpschool.io) (shameless plug) to manage workshops on the users machine (install, uninstall, search etc etc) 

I'm using Composer internals to run a Composer install for the downloaded workshops instead of executing Composer directly which is running fine with the code below (just a snippet)

``` php
$composer = $this->factory->createComposer(
    $this->io,
    sprintf('%s/composer.json', $workshopPath),
    false,
    $workshopPath
);

$installer  = ComposerInstaller::create($this->io, $composer);
$installer->run();
```

The `createComposer` method allows for the `cwd` to be passed in, so in my use case I'm passing in the path to the workshop (`~/.php-school/workshops/workshopname`). The value passed in is then used to create the `Config` object to create paths for `vendor-dir` etc etc in the `get` method.

My problem is that the [AutoloadGenerator uses getcwd](https://github.com/composer/composer/blob/master/src/Composer/Autoload/AutoloadGenerator.php#L102) which after a successful installation leaves the  generated autoload file with the basepath of the workshop manager rather than the workshop itself. 

The quick easy fix for me is to change dir before I install but this doesn't seem right as I'm allowed to set the cwd when I create the Composer obj. 

Unfortunately Config doesn't expose the baseDir property either so there doesn't look like there is currently a way to get that base path when generating the autoload files. 

Should the Config class expose the base dir so the internals can use the defined baseDir throughout ? 

I'm up for creating a PR for this but just wanted to get some thoughts before I do. 

Thanks :smile:

**Comment by Seldaek** [comment] 2016-03-07 00:20
Right now we have a few things depending on the working dir being = to base-dir (typically location of the composer.json). And yes that means doing a chdir() before (and restoring after if needed) is the best way to achieve this. Maybe it'd be nice to fix it yes, but I'm not sure what else needs to be fixed.

**Comment by curry684** [comment] 2016-03-10 23:27
Looking through the code it seems the entire `$cwd` parameter to `Factory::createComposer` is bugged. For example this error message in line 261:

    $message = 'Composer could not find a composer.json file in '.$cwd;

It's formatted like this without ever having tried to load the `composer.json` from the supplied cwd, it just always tries to load it from real cwd. What the intent behind the `$cwd` parameter seems to be there was to be able to [override certain paths in the global project for plugin loading](https://github.com/composer/composer/commit/331bda235c810787be90219f7625cc8a548aa92e), and not actually be a cwd for regular project operations. I agree with @Seldaek that this is hard to fix now and would require a ton of regression testing as it might break an awful lot of stuff.

My advice for now would be not to depend on this part of the internal APIs and just `chdir` in your code indeed.

**Comment by mikeymike** [comment] 2016-03-10 23:37
@Seldaek @curry684 Thanks for the details, I'm looking into this a bit more to see what can be done, hopefully I'll have a PR at some point soon (got a working resolution for my problem)

I'm actually able to install completely fine by using the `$cwd` param which is great. I don't think it has that many issues behind it. I agree there are various areas across the project where `chdir` and `getcwd` are used which is where I'm currently looking into to see what impact a change may have overall.

Any I fully agree, at the moment I've decided to just `chdir` to the package dir before running the install and then moving back. This of course resolves the autoload issues I came across :smile:

**Comment by Seldaek** [comment] 2016-04-19 22:09
I don't think we can fix this. We should instead make it explicit in the Factory that cwd must be set correctly, as it is becoming part of the API guarantees of composer at this point that the cwd is the root package's dir.

**Comment by mikeymike** [comment] 2016-04-21 07:59
@Seldaek that sounds fair to me, just a thought on this though, wouldn't it then be best to just not be able to set the path? Of course this would be a breaking change so is probably not the best approach. 

My initial impression was that we could expose the base dir on the config obj and where required `chdir` to it. But as I looked into it there was a few more places that may need some work and a lot of regression testing that would need to be done.

How would you approach making it explicit that the cwd must be set correctly?

**Comment by curry684** [comment] 2016-04-21 08:14
> Of course this would be a breaking change

No it's not, the internal structure of Composer is not part of its public exposed API, not documented, and rather explicitly not intended to be depended on externally. That was kinda the problem in the first place that you did  :wink: 

In general we would always recommend using the public API via shell scripts or other external tools rather than including the packages directly.

**Comment by mikeymike** [comment] 2016-04-21 09:11
Okay I've always taken the approach that anything public is part of the API, it's usable externally and any changes can cause 1 to hundreds of applications using it to break. Now of course for my application I chose to use the installer directly, 1 because it produces much cleaner and maintainable code and two because I can't rely on shell scripts or external tools (doing that doesn't feel like much of an API to me anyway) 

Also just a side note, if this isn't part of the API then maybe it's worth taking down [the API docs](https://getcomposer.org/apidoc/master/index.html) and [the link to them](https://getcomposer.org/doc/) ?

**Comment by Seldaek** [comment] 2016-04-21 09:27
I think everything is kind of part of the public API because plugins might use it and all.. It's not highly *recommended* to use this stuff because we don't provide strict guarantees but we definitely try and avoid unnecessary breakage (especially now that we have a 1.0, until 2.0..). The createComposer thing though, I doubt it ever worked as you intended it to work so changing that is probably not going to break a lot of usages.

**Comment by curry684** [comment] 2016-04-21 10:49
It could be a good idea to expose some interfaces specifically pertaining to classes that are reasonably stable from outside integrators. That way we could unit test those and if need be provide facades until a major version happens.

> Also just a side note, if this isn't part of the API then maybe it's worth taking down the API docs and the link to them ?

That's still the API. It's just not guaranteed to be publicly infinitely stable (yet)  :smile:

**Comment by RMcLeod79** [comment] 2016-04-27 10:09
> That's still the API. It's just not guaranteed to be publicly infinitely stable (yet)

Then why is composer on release 1.0 then?

**Comment by stof** [comment] 2016-04-27 10:12
@RMcLeod79 composer is a CLI tool, and it is stable as a CLI tool.

**Comment by Seldaek** [comment] 2016-04-27 10:14
@stof @curry684 Composer also has plugins, so the stability has to go beyond CLI IMO, but it should only apply to things that are reasonably useful for plugins, and especially only to working functionality. It's a fine line and common sense will have to prime over strict rules.

**Comment by curry684** [comment] 2016-04-27 11:55
I fully agree, but in general when integrating with a CLI software package like this you should be wary to depend on anything that doesn't end with `Interface`. The CLI frontend is stable, the interfaces are stable. The rest is reasonably stable but should be considered 'implementation details', thus no guarantees. 

Hence my remark about defining interfaces for plugin developers to use, but I think that's to be part of the bigger plans you have with "Plugins 2.0".

**Comment by mikeymike** [comment] 2016-04-27 11:57
Hey guys, I guess it all depends from what perspective your looking at it from. Yes it's a CLI tool and as a CLI tool it's stable. Is it intended to be used outside of that? maybe not (but that's not defined, in fact it says `If you need to work with composer as a library you may also want to check out the API Docs`). Also yes plugins are written for it which means there shouldn't be breaking changes for these __100%__, but at the same time there are going to be projects that depend on the `composer/composer` package as a library and in my eyes you cannot guarantee that making (what would be) a breaking change to an internal class doesn't break a whole bunch of other packages, whether this is a handful of packages or not. _(personal opinion)_ 

Yes, I mentioned internal class... now from my understanding version numbers should be relevant to the declared public API, which again I can only judge to be the whole project at this point as this is what is stated on the website (which is why I suggested that it should be changed)

If we are saying this is a CLI tool and therefore its version is based on a subset of classes then okay but this needs to be explicitly declared as the public API of the project. At least if this is explicitly declared it's easier to just point to a link and say, sorry but that's not the API we can't guarantee it wont change between minor version increments. 

Of course common sense should be applied in a lot of cases but when it comes down to what can and can't be used reliably I think there's is always going to be some problems without something definitive in place. I just believe that there is an approach (such as documentation) that can be taken to help any consumers of this package be aware of what is stable and what is not.

Just a thought, even dropping a little bit of extra text on the site saying that if your using it as a library you should always use concrete versions as it's possible the internal API may have breaking changes that don't impact the public API for plugins etc.

**Comment by Seldaek** [comment] 2020-10-27 16:12
Closing as I don't think this is going to move forward ever.

**Closed by Seldaek** 2020-10-27 16:12 UTC
Labels: Bug
