### ISSUE TITLE
-v should tell, why it is not installing newer version

### ISSUE THREAD

**Issue by indeyets** [composer/composer#1343] opened 2012-11-19 14:35 UTC
In case, when newer version of package has additional requirements, which are not satisfiable (newer php version, for example) composer won't be doing upgrade.

The problem is, that the reason on why upgrade is not done might be non-obvious to the user.

I propose to add the following line to the verbose output of composer:

`there's a newer version of foo/bar, but it can't be installed, as its requirements are not satisfiable`

**Comment by Seldaek** [comment] 2016-04-12 21:39
Closing as duplicate of #1563

**Closed by Seldaek** 2016-04-12 21:39 UTC
