### ISSUE TITLE
Broken autoload in Magento project after upgrade to 2.5.6

### ISSUE THREAD

**Issue by ihor-sviziev** [composer/composer#11480] opened 2023-05-24 11:12 UTC
```
$ composer --version
Composer version 2.5.6 2023-05-24 09:14:18
```
After the upgrade to composer 2.5.6, I started getting an issue - autoloader became broken after  running `composer dump-autoload --optimize`.
Here are steps to reproduce:
```
$ composer create-project --repository-url=https://repo.magento.com/ magento/project-community-edition test
...
$ cd test/
$ composer install --no-dev
...
$ php bin/magento --version
Magento CLI 2.4.6
$ composer dump-autoload --optimize
Generating optimized autoload files
Generated optimized autoload files containing 880 classes
$ php bin/magento --version

Fatal error: Uncaught Error: Class "Magento\Framework\Component\ComponentRegistrar" not found in /var/www/html/test/setup/src/Magento/Setup/registration.php:9
Stack trace:
#0 /var/www/html/test/app/etc/NonComposerComponentRegistration.php(29): require_once()
#1 [internal function]: Magento\NonComposerComponentRegistration\{closure}('/var/www/html/t...')
#2 /var/www/html/test/app/etc/NonComposerComponentRegistration.php(31): array_map(Object(Closure), Array)
#3 /var/www/html/test/app/etc/NonComposerComponentRegistration.php(34): Magento\NonComposerComponentRegistration\{closure}()
#4 /var/www/html/test/vendor/composer/autoload_real.php(41): require('/var/www/html/t...')
#5 /var/www/html/test/vendor/composer/autoload_real.php(45): {closure}('b4cf39431a4b949...', '/var/www/html/t...')
#6 /var/www/html/test/vendor/autoload.php(25): ComposerAutoloaderInitbb42076190ede96daffb0f7e2039b934::getLoader()
#7 /var/www/html/test/app/autoload.php(51): include('/var/www/html/t...')
#8 /var/www/html/test/app/bootstrap.php(44): require_once('/var/www/html/t...')
#9 /var/www/html/test/bin/magento(14): require('/var/www/html/t...')
#10 {main}
  thrown in /var/www/html/test/setup/src/Magento/Setup/registration.php on line 9
```

after rolling back to previous composer version:
```
$ composer dump-autoload --optimize
Generating optimized autoload files
Generated optimized autoload files containing 22510 classes
$ php bin/magento --version
Magento CLI 2.4.6
```

**This issue will affect all (or almost all) Magento2-based projects.**
Pay attention that the new version generated autoload files for 880 classes only, while the older one was 22510.

And I expected this to happen:
No regression issues during composer updates

**Comment by ihor-sviziev** [comment] 2023-05-24 11:18
@adri I don't think it's architecture-dependent. I see this both on Github Actions (where amd64) and on M1 mac in Docker (arm64)

**Comment by ihor-sviziev** [comment] 2023-05-24 11:21
@Seldaek, this is related to the latest release, please check it

**Comment by ihor-sviziev** [comment] 2023-05-24 11:24
Looks like related to https://github.com/composer/composer/pull/11455

**Comment by Seldaek** [comment] 2023-05-24 11:24
Yeahhh well, anyone has a clue what's going on?

My first guess would be that autoloading was misconfigured previously but the metapackage bug we had was hiding that by scanning the whole application folder.

**Comment by Seldaek** [comment] 2023-05-24 11:27
So now autoloading is still misconfigured, but you do see the problem.. 

If anyone has a source install of composer to try a patch, in AutoloadGenerator.php line 488 add a string cast so:

```
$installPath = $installationManager->getInstallPath($package);
```

becomes 

```
$installPath = (string) $installationManager->getInstallPath($package);
```

If that fixes it, at least we have a diagnostic.. but I'm still unsure why it would cause problems unless there is an autoload misconfiguration.

If you have a simple/small package I can try that would be good.

**Comment by fredden** [comment] 2023-05-24 12:04
When including the 'development' packages with Magento, I get the same class count with both Composer 2.5.5 and Composer 2.5.6. When using `--no-dev`, the bug is present.

I can confirm that casting `$installPath` to be a string produces the correct number of classes again.

**Comment by Seldaek** [comment] 2023-05-24 12:20
> I can confirm that casting `$installPath` to be a string produces the correct number of classes again.

What's the correct number? the same as without `--no-dev`? Because that does not sound correct to me, that sounds like it was scanning all classes in `""` (i.e. current working dir, including vendor..), and now it doesn't anymore, correctly excluding dev dependencies. Then probably something which is always required (like `Magento\Framework\Component\ComponentRegistrar`?) but somehow not in require but in require-dev, fails to load if you have a no-dev autoload dump.

**Comment by Seldaek** [comment] 2023-05-24 12:25
Ahh yeah ok I forgot about the filtering that happens after.. That makes a lot of sense, thanks!

I'll take a look if I can fix this without reverting the whole fix though.

**Comment by Seldaek** [comment] 2023-05-24 12:49
OK, if you can check with this if everything is back to normal that'd be good, but I could repro the issue in a test and it's now fixed as far as I can tell

https://github.com/composer/composer/pull/11481

**Comment by fredden** [comment] 2023-05-24 12:55
Thanks for the quick response on this @Seldaek. I have tested with #11481 and confirm that I'm getting the expected auto-loader content in all scenarios listed in https://github.com/composer/composer/issues/11480#issuecomment-1561081728. :+1:

**Comment by Seldaek** [comment] 2023-05-24 12:58
Great, thanks for helping out debugging and testing, that helped a ton!

**Closed** 2023-05-24 13:03 UTC
Labels: Bug

**Comment by Seldaek** [comment] 2023-05-24 13:06
https://github.com/composer/composer/releases/tag/2.5.7 is now available
