### ISSUE TITLE
_tmp1 class for composer plugin generates errors

### ISSUE THREAD

**Issue by exteon** [composer/composer#10101] opened 2021-09-14 13:23 UTC
I have a composer plugin implemented in, let's say, class `InstallerPlugin`.

The plugin itself has a decoupled plugin-like architecture so the `InstallerPlugin` instance also acts as a container for various services and thus it gets sent around to various (strong-typed) constructors.

In certain cases, I get a type error (object should be of type `InstallerPlugin`, `InstallerPlugin_tmp1` provided).
This happens:
- On `composer update` when the plugin itself gets updated
- **Always** on `composer require`

I'm trying to understand the plugin lifecycle, can someone please help shed some light on this, namely:
- It makes _some_ sense that when the plugin gets updated there are two concurrent versions of the plugin. However, I would have expected this would be treated either by process separation (spawn a new process for the new plugin instance), or, if class weaving is deployed (which seems to be the case), I would expect that as you rewrite the class name you also rewrite the types in code
- It makes no sense that this happens in the absence of a plugin update (i.e. `composer require someother/package`). Is this a bug?
- How to avoid the error?

**Comment by Seldaek** [comment] 2021-09-15 09:42
The composer require case seems odd, and may be a bug, or maybe due to you having the plugin installed twice (in global composer install and locally in the project)?

Is the plugin public by any chance so I could try to reproduce?

As for the other type error you get, also having a code sample would be very helpful as I am not entirely sure what you mean.

**Comment by Seldaek** [comment] 2021-09-15 09:44
BTW this is the code doing the replacement, it is very basic indeed, the assumption being that plugin classes can conform to our limitations as they are slightly special classes.. we don't necessarily need/want to support 100% of php code safely. https://github.com/composer/composer/blob/master/src/Composer/Plugin/PluginManager.php#L210-L215

**Comment by exteon** [comment] 2021-09-15 10:04
Haven't thought of it, but the plugin is indeed required in the main project in `require` and in the included library in `require_dev`, because the instaler has two functions: to set up dev/deploy skel for `custom-project` type projects, and to set up dev/testing skel for `custom-project-lib` type included libs. Conceptually, it would make sense to break this into two plugins (or rather, two classes, since the functionality is 99% identical for the project and libs) if needed, could you explain to me how including the plugin in the included lib affects its lifecycle?

ATM the plugin is not public, I could probably produce a minimal TC now that the problem is narrowed down to the double-include...

**Comment by Seldaek** [comment] 2021-09-15 11:10
require-dev from a dependency will have no effect. I meant more if you do `composer global require plugin` then you'll install the plugin in the global composer dir, which gets loaded as well whenever you run composer, so it could maybe load the plugin twice.. but most likely it's something else. I'll dig into the require issue myself I think, probably can repro this with any plugin. Still would be happy to get details about what you mean by `In certain cases, I get a type error (object should be of type InstallerPlugin, InstallerPlugin_tmp1 provided).` though. What kind of code/type annotation triggered this?

**Comment by Seldaek** [comment] 2021-09-15 11:50
Ah ok the composer require loading plugins twice actually makes sense as it needs to initialize a Composer instance (incl plugins) once to get access to packages, figure out what to require in what version etc, then it updates the composer.json and reinitializes it with the new composer.json.

So this isn't really an issue.

For your other issue, I wonder if you can't use `self` or `static` instead of the class name? That'd most likely resolve it.

**Comment by exteon** [comment] 2021-09-15 12:08
So, basically, in `InstallerComposerPlugin` I have this container function that returns a list of enabled VCS "managers" (that will initialize VCS repositories based on the project skel that is an aggregate of the library skels):
```php
        public function getVcsManagers(): array {
            ...
            $managers[] = new MercurialManager($this)
        }
```
Then I have in `MercurialManager`:
```php
        public function __construct(
            InstallerComposerPlugin $installerComposerPlugin
        ) {
            ...
        }
```
Now, obviously, `InstallerComposerPlugin_tmp1` will not be `InstallerComposerPlugin` at this point.

The getVcsManagers() gets called VERY late in the composer process, as a consequence of:
```php
        public static function getSubscribedEvents(): array
        {
            return [
                'post-install-cmd' => 'update',
                'post-update-cmd' => 'update'
            ];
        }
```

**Comment by Seldaek** [comment] 2021-09-15 12:12
OK I see.. Fixing this isn't really possible unless we rewrite/eval ALL classes in the plugin though, which is just way beyond the scope here IMO.

I'd suggest you type-hint against an interface for your plugin class instead as that should remain constant, or remove the type hints altogether.

**Comment by exteon** [comment] 2021-09-15 14:35
Well, there are a few point here:

1. Removing strong typing does not really fix the issue, it just hides it for a while; that's because if there's a `Plugin_v1` and a `Plugin_v2` somewhere then there's definitely a a `Dependency_v1` and `Dependency_v2` somewhere and `Plugin_v1` won't work with `Dependency_v2` and vice-versa
2. If I manage to understand the problem, I have a solution that might be easier or harder to adapt: https://github.com/exteon/chaining-class-resolver is one of my libraries that, among others things, can rewrite classes to translate a full namespace to another namespace (it can also rewrite dependencies)

Even going for the typehint workaround, I'm asking what the purpose of this is and what the lifecycle of the plugin is to realize how to safely attack the problem (for instance, should I make sure to preload all dependencies as soon as possible or should I make sure no dependency is loaded up to a certain point), which methods are called on `Plugin` and which are called on `Plugin_tmp1`, etc

**Comment by exteon** [comment] 2021-09-15 14:55
The worst outcome for me would be that I need to namespace myself every version of the plugin, such as `Exteon\Project\v1_10_4\*` to make sure that class versions don't get tangled... But that also won't solve external dependencies (composer packages).

Another option that pops to mind is spawning myself an outer process `composer do:stuff` command; since I don't need to interact with composer write-wise, I just read from it, so an external transaction would be safe with a single version of the plugin... as long as I know what the right moment is to launch such command when the repository is in a consistent state.

**Comment by exteon** [comment] 2021-09-21 06:59
So as a workaround I implemented the `post-update-cmd`/`post-install` hook as such:

```php
        /**
         * @throws Exception
         */
        public function onUpdate()
        {
            if (!$this->isEnabled()) {
                return;
            }

            /*
             * Composer duplicates installer class after update which generated
             * errors, so use a separate process command to do after update
             * operations
             * https://github.com/composer/composer/issues/10101
             */

            passthru(
                escapeshellarg(PHP_BINARY) .
                ' ' . escapeshellarg(
                    $this->composer->getConfig()->get('bin-dir') . DIRECTORY_SEPARATOR . 'composer'
                ) .
                ' web3:on-update',
                $result
            );
            if ($result !== 0) {
                throw new Exception('Error running update hook');
            }
        }

```

Then implemented the update code in a hidden `web3:on-update` command. Seems to be more stable so far.

**Comment by Seldaek** [comment] 2021-10-01 21:47
I think I'm going to have to close this as won't-fix. I just don't see a way to reasonably handle this use case given the constraints php imposes on us. The current situation isn't perfect for sure, but in practice it's mostly working for everyone else it seems.

**Closed by Seldaek** 2021-10-01 21:47 UTC
Labels: Bug
