### ISSUE TITLE
Suggestion: add configuration for different environment

### ISSUE THREAD

**Issue by emimarz** [composer/composer#5969] opened 2016-12-15 17:14 UTC
I have in require-dev some plugin that needs PHP 5.4 so in my develop machine I have PHP 5.4 but in production I need that all package support PHP 5.3.3
something like this

    {
        "config": {
            "platform": {
                "php": "5.3.3"
            },
        },
        "config-dev": {
            "platform": {
                "php": "5.4"
            },
        },
        "require": {
        ...
        here I need that all package accept PHP 5.3.3
        },
        "require-dev": {
        ...
        some package that have PHP 5.4 as dependencies
        }
    }

**Comment by stof** [comment] 2016-12-15 17:17
The issue is that dependencies are resolved by taking all deps into account (as they are then locked). So we cannot change the target PHP version between ``--dev`` and ``--no-dev``. These flags are only about the installation process, not about the resolution.

**Closed** 2016-12-18 11:19 UTC
Labels: Support
