### ISSUE TITLE
Forward STDIN to sub-processes (was: Composer post-install-cmd php script doesn't wait for input)

### ISSUE THREAD

**Issue by chris-freedom** [composer/composer#2905] opened 2014-04-12 02:26 UTC
So I have a console script i want run after composer has run an install.

    "scripts": {
        "post-install-cmd": [
            "sudo ./bin/phing -f ./phing/builds/nginx/build.xml"
        ]
    }

When I run 
```bash
$ sudo ./bin/phing -f ./phing/builds/nginx/build.xml 
```
manually form the command line - no problems. As expected. However when I run  
```bash
$ composer install 
```
the file executes but STDIN does not wait for a response.

**Comment by fonsecas72** [comment] 2015-12-07 20:44
so, can we close this? @Esysteme , @chris-freedom 
:bee:

**Comment by Esysteme** [comment] 2015-12-08 08:33
Let me try I answer you in the day

**Comment by Esysteme** [comment] 2015-12-09 14:02
still not work for me

**Comment by Seldaek** [comment] 2016-04-15 17:34
Closing as duplicate of #3299 - but it's unlikely to happen as you can see on #4036 it doesn't quite seem to work cross-platform.

**Closed by Seldaek** 2016-04-15 17:34 UTC
Labels: Feature

**Comment by pilot911** [comment] 2016-06-26 19:12
well, why it should work cross-platform ? just do it for linux

**Comment by rquadling** [comment] 2016-06-26 21:08
Windows has a registry setting called InheritConsoleHandles that requires enabling to accept stdin from the command line. Unfortunately, Microsoft seemed to have toggled the meaning of this in a preview version of Windows 10.

http://php.net/manual/en/install.windows.legacy.index.php#install.windows.legacy.commandline

Not sure if this is directly applicable to this issue, but it is related.

**Comment by mbrodala** [comment] 2017-02-22 13:16
@Seldaek I also think that this could be done for non-Windows plattforms only. I see no reason to cripple scripts just because one platform is broken. The check itself can be performed with `Platform::isWindows()` unless I'm missing something.
