### ISSUE TITLE
Your logo is wrong

### ISSUE THREAD

**Issue by yourlogoiswrong** [composer/composer#5511] opened 2016-07-12 01:29 UTC
Your logo is of a conductor, not a composer. While there indeed were conductors who were also composers, one does not automatically equal another.

**Comment by pborreli** [comment] 2016-07-12 01:35
duplicate of #1713 and composer/getcomposer.org#36

**Comment by alcohol** [comment] 2016-07-12 06:50
Thanks @pborreli

**Closed** 2016-07-12 06:49 UTC

**Comment by Seldaek** [comment] 2016-07-12 14:36
Wow, some courageous soul created a new fake account just for the purpose of trolling here. Impressive.

**Comment by yourlogoiswrong** [comment] 2016-07-13 08:40
@Seldaek
Wow, some courageous soul posted in a closed issue thread just for the purpose of being butthurt. Impressive.
