### ISSUE TITLE
Should config platform overrides be stored in lockfile?

### ISSUE THREAD

**Issue by predakanga** [composer/composer#7052] opened 2018-01-29 09:27 UTC
## Summary

I've just discovered that, when using composer's config.json to force detection of certain platform reqs, those reqs are stored in the lockfile and used on later installs.
To me, this is a pretty confusing developer experience.

## Steps to reproduce

1. Configure your local environment as below
2. Run composer update
3. Copy the project (including lockfile) to a different machine
4. Ensure that the second machine does not have the imagick extension installed
5. Run composer install

## Expected behaviour

Composer should warn the user that imagick is not installed

## Actual behaviour

Composer does not warn the user that imagick is not installed

### config.json

```json
{
    "config": {
        "platform": {
            "ext-imagick": "7.1"
        }
    }
}
```

### composer.json

```json
{
    "name": "demo/apptest",
    "require": {
        "php": "^5.6|^7.0",
        "ext-curl": "*",
        "ext-imagick": "*",
        "ext-mysql": "*"
    }
}
```

**Comment by Seldaek** [comment] 2018-01-31 13:53
You can use the new `composer check-platform-reqs` after a `composer install` to make extra sure you have a correct environment in production. 

I am not sure anymore if there was a really good reason to add this to the lock file though to be honest. I can't really think of it having an adverse effect but it's also been working like this since before 1.0.0 came out so I am not so keen on changing it as it might have unexpected effects.

Leaving this open for now though to hopefully gather more opinions.

**Comment by joelpittet** [comment] 2018-07-09 21:57
With a committed lock file it would be nice if updates between developers didn't change this every time.

**Comment by Seldaek** [comment] 2018-07-20 08:08
Yeah that's a hard one though, as global config does affect things in the local project run, ignoring it in some cases is not easy and also would cause more surprising behavior IMO.

**Comment by acoulton** [comment] 2018-08-21 16:03
I just came across this and agree it's not ideal. My usecase is that I want to build a periodic job on CI that runs composer update on our projects and sends pull requests for updates to the composer.lock. 

However I want to do these all in the same container, rather than having to match each individual project's PHP environment. So I need to override the platform to tell `composer update` to only e.g. select updates that support php 5.x.

But then when that composer.lock gets committed back to a project the PR does get built in that project's specific environment. At that point the `composer install` should be strict about checking the php version / extensions meet the requirements of the packages in the composer.lock.

I think that (use a "virtual" environment for update, "real" environment for install) would be a fairly common use of platform package overrides?

**Comment by staabm** [comment] 2018-08-21 16:58
Use  https://getcomposer.org/doc/06-config.md#platform to fake your platform requirements

**Comment by acoulton** [comment] 2018-08-22 09:01
@staabm yes, I know that. The point is that (unexpectedly IMO) the overrides are then committed into composer.lock so they're also applied when running `composer install` in the production etc environment. I want to override for `update` but not `install`.

**Comment by staabm** [comment] 2018-08-22 10:34
Composer install will try to exactly install what is defined in the lockfile. 

It will never try to install a different version.. and thats the only purpose why the command exists

**Comment by alcohol** [comment] 2018-08-22 10:41
@staabm provided of course that a `composer.lock` file exists.

But @staabm is correct. Your worries about `composer install` installing something different in your production environment seem counter intuitive when you consider how `install` functions with a lock file. I do not think your worries are justified.

Though in all honesty, you should build release artifacts and not run Composer in production at all. But that is a topic for a different discussion.

**Comment by acoulton** [comment] 2018-08-22 11:19
I'm not concerned that it will try to install a different version.

My concern is that `composer install` normally verifies the platform requirements even if installing from a composer.lock, so currently when we run it in the project-specific build environment it will fail if e.g. an earlier stage in the build process has configured the wrong php version, missed a required extension etc. This is a useful safety check and fails fast, rather than waiting for and trying to debug individual failing unit/integration tests.

If we use platform overrides to allow us to run the `update` anywhere, and then those overrides are committed to the composer.lock, then `install` will only be verifying the packages against those overrides (which will always succeed) rather than against the actual environment it's running in.

**Comment by staabm** [comment] 2018-08-22 11:37
A shot in the dark: maybe `--ignore-platform-reqs` cli option is what helps you?

**Comment by acoulton** [comment] 2018-08-22 11:48
@staabm no, that would do the opposite.

I need:
* `composer update` to use an emulated set of platform packages so that it can run anywhere but crucially will only select versions that are actually compatible with the target environment. `--ignore-platform-reqs` here would e.g. select php7 packages for a project that runs on php5
* `composer install` to use the actual set of platform packages, to ensure the runtime php environment does actually have the php version / extensions I said it would in the config I passed to `update`. `--ignore-platform-reqs` just skips verification altogether.

The docs for the `platform` option say:
`Lets you fake platform packages (PHP and extensions) so that you can emulate a production env or define your target platform in the config`

The issue is that although it lets you emulate the environment, because those emulated values are then committed into the lockfile that then prevents `composer install` from **verifying** that the actual platform matches the defined target platform.

**Comment by acoulton** [comment] 2018-08-22 11:53
Or to put it another way, if you `emulate a production env` for `update` that results in composer using the same emulated environment for all subsequent `install` commands using that lockfile : I think that's very unexpected. Especially if the emulated environment was defined in a config.json on a specific machine.

**Comment by Seldaek** [comment] 2018-08-22 12:03
@acoulton what's the problem with using `composer check-platform-reqs` before or after an install (+ defining config.platform) to make sure the requirements are actually met in production?

**Comment by predakanga** [comment] 2018-08-22 12:05
@acoulton It sounds like check-platform-reqs is what you would want.

If I'm understanding your case correctly, you would:
1. Include your platform requirements in your project's composer.json
2. Add your expected production platform to the project's composer.json, not the global config
3. Run `composer update` in CI - this should produce the same results anywhere
4. In your production environment/image builder, run `composer check-platform-reqs && composer install` - this will fail if the actual environment doesn't meet your requirements, regardless of the platform setting

**Comment by acoulton** [comment] 2018-08-24 22:49
@Seldaek @predakanga thanks so much for the responses.  I wasn't aware of `check-platform-reqs` but that's perfect and as @predakanga says that will also potentially allow us to re-sequence our build and handle this better anyway.

I still think it's unexpected that the overrides are always committed to the lockfile with no option to override that. But the flow you've suggested works much better anyway and makes that a moot point for my usecase.

**Comment by benbor** [comment] 2018-12-11 20:33
Hi guys. I have a similar problems with platform requirements as @acoulton 
1. I really don't want to run another command (`composer check-platform-reqs`) after the successful running of `composer install`. As for me `install` is a guarantee that everything is fine on any env
2. Now,  I almost don't see reason to add platform requirements under `require` section, because `config.platform` section is more important. At least, `config.platform` section is more respectable than `requre` for almost every command (`install`, `update`; versus `check-platform-reqs`)
3. A documentation says the following:
> Lets you fake platform packages (PHP and extensions) so that you can emulate a production env or define your target platform in the config.

As I understood, it help's me to emulate production env, when I don't need to run my project. For example some code-style, statick analyze checks on my CI\CD pipeline.


Every point is IMHO, and I'm a bit confused with current behaviour like @acoulton  

I propose the following:
1. `config.platform` should NOT be saved in composer.lock. Every environment should care about project requirements, not project's `composer.json`
2. To help an environment care about project requirements `--ignore-platform-reqs` could be used
3. Let `composer install\update` respect global `config.platform` section:
```bash
# setup CI
composer config --global platform.ext-imagick '7'

# run some actions on CI
composer install
```
4. `config.platform` in the local composer.json let's leave as backward compatibility.

As bottom line:
1. The local `composer.json` will provide only information really needed for the successful project run 
2. Each enviroment will care about supporting of `composer.json` with few options:
    - Install real dependencies
    - Emulate dependecies with global config
    - Use `--ignore-platform-reqs` to turn off any checks

If you like this point of view let me know and I prepare PR
Thanks

**Comment by Seldaek** [comment] 2020-10-15 11:30
Closing, composer 2 includes platform check https://getcomposer.org/doc/07-runtime.md#platform-check which should help.

**Closed by Seldaek** 2020-10-15 11:30 UTC
Labels: Question
