### ISSUE TITLE
Receiving Segmentation fault when running Composer Install (windows 10 + cygwin php)

### ISSUE THREAD

**Issue by rreynier** [composer/composer#4433] opened 2015-09-22 02:10 UTC
Whenever I try to generate the autoloader I am receiving a Segmentation fault error, which creates a stackdump.  Here is a gist of this stackdump: https://gist.github.com/rreynier/c89ebace7a8841cb2324  This only happens with a handfull of pacakges.  Currently it is failing on PHPUnit.  I have seen this on multiple machines now. 

Here are steps to reproduce:

- Pull down the latest version of cygwin with php as an addon (currently 5.6.13). 
- Start a clean php project and require just phpunit (4.8) in your composer.json
- Run `composer install`
- Observe error

I debugged some and it turns out that `php_strip_whitespace()` is causing the Segmentation fault. This is found in ClassMapGenerator.php [source](https://github.com/composer/composer/blob/d831c86bcb385d51307e56e4b8667d267e781165/src/Composer/Autoload/ClassMapGenerator.php#L121)

The file it fails on is: https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestFailure.php

Here is the thing that blows my mind, if I open this phpunit file, and just add a new line to the end.. or to top.. (essentially any change) .. all of a sudden everything works!

**Comment by rreynier** [comment] 2015-09-22 02:30
Actually, I debugged some more and it turns out that `php_strip_whitespace()` is causing the Segmentation fault. This is found in ClassMapGenerator.php [source](https://github.com/composer/composer/blob/d831c86bcb385d51307e56e4b8667d267e781165/src/Composer/Autoload/ClassMapGenerator.php#L121)

The file it fails on is: https://github.com/sebastianbergmann/phpunit/blob/master/src/Framework/TestFailure.php

Here is the thing that blows my mind, if I open this phpunit file, and just add a new line to the end.. or to top.. all of a sudden everything works!

**Comment by alcohol** [comment] 2015-09-22 09:18
Can you see if you have apc cli cache turned on?

**Comment by stof** [comment] 2015-09-22 09:24
@rreynier a segfault means there is a bug in PHP itself (or in one of the extension you use). You should open an issue on php.net (and try the same after disabling some of your extensions to see whether you can identify the extension causing this, in which case it should be reported to the extension instead)

**Comment by Seldaek** [comment] 2015-09-22 09:37
Can you reproduce that a simple `php -r 'php_strip_whitespace("TestFailure.php");'` crashes PHP? Because if so then it's an easy way to report it to php core. However if it crashes with the cygwin PHP it might just be a cygwin bug rather than a PHP one.

**Comment by rreynier** [comment] 2015-09-22 15:38
@seldaek I did what you suggested and was able to re-produce:

![image](https://cloud.githubusercontent.com/assets/1953114/10023088/74db5938-610d-11e5-98c4-2b932ec0b8ae.png)

To note, this is the php that is provided by cygwin.  My coworker had the same issue and he just pulled in office windows php into his cygwin and it solved his problem. At this point I am just stubborn and want to know a root cause :)

Sounds like I may be best off reporting this to cygwin somehow.

**Comment by Seldaek** [comment] 2015-09-22 16:36
Yeah TBH using php from cygwin isn't a great idea, cygwin is just too different an environment. Too many hacks that create failures.. In any case closing here as there isn't much we can do I'm afraid :)

**Closed by Seldaek** 2015-09-22 16:36 UTC
Labels: Support

**Comment by rreynier** [comment] 2015-09-22 17:26
Thanks for the help @Seldaek
