### ISSUE TITLE
clearcache command broken on Windows

### ISSUE THREAD

**Issue by SoboLAN** [composer/composer#5833] opened 2016-10-31 15:37 UTC
On Windows 7, when I run the following command:

`composer clearcache -vvv`

I get the following output:

```
Loading config file C:/Users/myuser/AppData/Roaming/Composer/config.json
Loading config file C:/Users/myuser/AppData/Roaming/Composer/auth.json
Failed to initialize global composer: Composer could not find the config file: C:/Users/myuser/AppData/Roaming/Composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.2.1 (2016-09-12 11:27:19) with PHP 5.4.31 on Windows NT / 6.1
Clearing cache (cache-dir): C:\Users\myuser\AppData\Local\Composer
```

And then it just hangs and doesn't do anything, even if I let it run for a few minutes.

I looked at the path mentioned and indeed there is a `config.json` file and a `auth.json` file, but there is no `composer.json` file there.

The behaviour is the same if the current directory contains a `composer.json` file or not.

It seems a bit strange to me that a `composer.json` file is needed just to clear the cache.

I Googled it and searched it here on GitHub but couldn't find anything similar to my problem. Either I'm missing something (most likely) or it's a command almost no one uses.

Any ideas ? Thanks.

**Comment by alcohol** [comment] 2016-10-31 19:41
> `Failed to initialize global composer: Composer could not find the config file: C:/Users/myuser/AppData/Roaming/Composer/composer.json`

This line can be ignored, it has no impact. You are certain that the path given (`C:\Users\myuser\AppData\Local\Composer`) contains nothing other than a `config.json` and a `auth.json`?

**Comment by curry684** [comment] 2016-10-31 22:00
> it's a command almost no one uses.

That's correct as well - most developers don't bother clearing the caches  :smile:

@SoboLAN what output does the command give *without* `-vvv`? The error is technically correct, so it may just be verbosity that's causing the error to escalate to the console. If it shows up without verbosity it's a bug as not having a global composer project is very valid and very common.

**Comment by SoboLAN** [comment] 2016-11-01 08:04
@alcohol The path given contains the following files:

```
.htaccess
2016-07-19_01-28-52-1.2.0-old.phar
auth.json
cacert.pem
config.json
keys.dev.pub
keys.tags.pub
```

So no `composer.json` there. I wouldn't mind, but apparently it's the thing that breaks the `clearcache` command.

@curry684 I initially tried it without `-vvv` and the execution just hanged, like it was in some sort of infinite-loop or something. That's why I added the `-vvv` to better see what's going on. Without the `-vvv` it just prints the last line in the dump I posted above and then... nothing.

**Comment by alcohol** [comment] 2016-11-01 08:21
We already told you, the absence of a `composer.json` in your composer home directory is not what breaks the command. I do not think that we need to repeat this.

As for why it hangs, that is the real puzzle. Since you seem to only have files in said directory, it should finish almost instantly. Normally there would be several directories here as well (`cache/files`, `cache/repos`, `cache/vcs`). It would iterate through these and clean them up. But there is nothing to iterate in your case. Quite a puzzle indeed...

**Comment by SoboLAN** [comment] 2016-11-01 08:34
Maybe it did clear them the first time I executed it and I simply didn't notice.

In any case, it's a low-priority command which I suspect is rarely used. This in turn makes it, imo, a low-priority bug.

If someone does want to solve it and needs more info about my environment, let me know.

**Comment by Seldaek** [comment] 2016-11-03 11:45
The cache dir is in the Local app data, so C:\Users\myuser\AppData\Local\Composer, make sure you check the right dir, because the other files you mentioned, auth.json and config.json, should be in the Roaming app data dir, not Local. So C:\Users\myuser\AppData\Roaming\Composer.

If your Local one is indeed empty and it freezes, you're gonna have to debug it to see where it hangs because I doubt anyone is going to be able to fix this unless we can reproduce or at least understand the problem better.

**Comment by Seldaek** [comment] 2017-06-18 16:20
Closing issue as it has been quiet for a long time and there is no clear next step we can take.

**Closed by Seldaek** 2017-06-18 16:20 UTC
Labels: Support
