### ISSUE TITLE
Oddities with metapackages and plugin events

### ISSUE THREAD

**Issue by weierophinney** [composer/composer#5402] opened 2016-06-02 14:56 UTC
With the following composer.json:

``` json
{
  "require": {
    "zendframework/zend-component-installer": "^0.1",
    "zendframework/zend-mvc-plugins": "^1.0"
  }
}
```

where:
- zendframework/zend-component-installer is a composer-plugin, and subscribes to each of the `post-package-install` and `post-package-uninstall` events
- zendframework/zend-mvc-plugins is a composer metapackage, and adds requirements on four zend-mvc plugin packages

When I run this command:

``` console
$ composer install -vvv
```

or, after installation, any of:

``` console
$ composer remove zendframework/zend-mvc-plugin-identity # one of the packages in the plugins metapackage
$ composer remove zendframework/zend-mvc-plugins # the entire metapackage
```

Installation and uninstallation happen normally, _with one exception_: neither of the subscribers defined in zend-component-installer are triggered for the packages required by the metapackage. They _are_ triggered for the metapackage itself, but none of the packages it requires individually, _even when removing them individually_.

I can work around this to a degree by having zend-mvc-plugins duplicate information from the packages it depends on; since install/remove of the metapackage triggers the zend-component-installer subscribers, this works. However, I do find it problematic that removing any of the individual packages does not trigger the subscribers.

**Comment by Seldaek** [comment] 2020-10-28 14:24
I'm not sure if still actual or not. I can't reproduce on composer 2 as the plugin is not compatible. If this is still an issue please say so and give me a repro case for composer 2 and i'll have a look. In the meantime closing.

**Closed by Seldaek** 2020-10-28 14:24 UTC
Labels: Bug
