### ISSUE TITLE
Extracting the fallback CA file does not clean up afterwards.

### ISSUE THREAD

**Issue by SvenRtbg** [composer/composer#4812] opened 2016-01-21 12:36 UTC
No sure if this should be included in #4804, as it is related:

In case that no CA files are found on the system, the cacert.pem file from the Phar is extracted into a temporary directory on the system. [code](https://github.com/composer/composer/blob/546730dcf3da4d2689664116c0639655aa428b6b/src/Composer/Util/RemoteFilesystem.php#L641-L653) The file is left there without any cleanup. 

I encountered the problem that running Composer from one user account created the file in `/tmp/composer-cacert.pem`, and subsequently running Composer from another user without sufficient write privileges for the already created file instantly killed Composer.

This also prevents the second user to use Composer for anything that might help, i.e. configuring "disable-tls = true" via command line. And I *think* (no evidence collected so far) this is a global problem for any Composer installation with this feature because the created file is global.

This may also be an attack vector for man-in-the-middle: An attacker might be able to influence the temporarily written file (with user privileges) just between creation and usage. The system temp directory probably isn't as secure as any well known central CA directory.

Steps to reproduce:
1. Have a system with no CA files in the well-known locations.
2. Login as user 1. Run `composer update/install/require` (any operation with TLS verification).
3. Verify that `composer-cacert.pem` is created in the system temp location.
4. Login as user 2. Run any other composer command with TLS verification.

Expected:
Second call works as expected.

Experienced:
```
[ErrorException]
  fopen(/tmp/composer-cacert.pem): failed to open stream: Permission denied
```

**Comment by alcohol** [comment] 2016-01-21 14:08
I made a small change to my PR that should resolve this.

**Comment by Seldaek** [comment] 2016-01-22 13:47
Closing as I believe #4805 solves it but feel free to ping us if the problem is still there after self-update.

**Closed by Seldaek** 2016-01-22 13:47 UTC
Labels: Bug

**Comment by rajkumarpudasaini** [comment] 2017-05-07 01:35
[ErrorException]
  hash_file(C:\Users\Raj\AppData\Local\Temp/composer-cacert-300c74d6960d46715ffed607c8e36acfa7cbcad49862bb1b67d3c43dea9bfb40.pem): failed to open stream: Permission
  denied ..this error occur when i start to create  new project..
