### ISSUE TITLE
exec command doesn't works correctly on windows

### ISSUE THREAD

**Issue by EduenSarceno** [composer/composer#6968] opened 2018-01-03 23:53 UTC
I don't know if I'm wrong but I think the command only adds COMPOSER_BIN_PATH to the path and after runs the program

composer.json
```
{
	"name": "vendor/foo",
	"description": "A foo package",
	"scripts": {
		"test" : "phpunit --version"
	},
	"require-dev": {
		"phpunit/phpunit": "^6.5"
	}
}
```

If I try to execute phpunit, I get a error
```
> composer exec phpunit
Script phpunit handling the __exec_command event returned with error code 2
```
But if I run the script its works
```
> composer run-script test
> phpunit --version
PHPUnit 6.5.5 by Sebastian Bergmann and contributors.
```

I don't like do things like  `vendor\bin\phpunit --help` instead of  `composer exec -- phpunit --help`.

**Note**  
The arguments are not passed correctly either

```
>composer exec -- phpunit --help
Usage:
  exec [options] [--] [<binary>] [<args>]...

Arguments:
  binary                         The binary to run, e.g. phpunit
  args                           Arguments to pass to the binary. Use -- to separate from composer arguments

Options:
  -l, --list
  -h, --help                     Display this help message
  -q, --quiet                    Do not output any message
  -V, --version                  Display this application version
      --ansi                     Force ANSI output
      --no-ansi                  Disable ANSI output
  -n, --no-interaction           Do not ask any interactive question
      --profile                  Display timing and memory usage information
      --no-plugins               Whether to disable plugins.
  -d, --working-dir=WORKING-DIR  If specified, use the given directory as working directory.
  -v|vv|vvv, --verbose           Increase the verbosity of messages: 1 for normal output, 2 for more verbose output and 3 for debug

Help:
  Executes a vendored binary/script.
```
Everything that is after -- should be treated as an argument to the program not as a part of the composer command

Environment:
```
>composer --version
Composer version 1.5.6 2017-12-18 12:09:18
```

**Comment by Seldaek** [comment] 2018-01-04 10:22
The `--` thing is a known issue that we can only fix once we drop php 5.3 and 5.4 as it is fixed in symfony/console 3.x.  The rest I am not sure what the problem is here, I think it used to work at least.

**Comment by robbieaverill** [comment] 2018-11-05 20:33
I'm currently not able to run any global composer binaries on a Mac either, with a combination of `Script phpunit handling the __exec_command event returned with error code 127` type errors and no output at all depending on the binary. This seems like a relevant thread to bring that up on.

**Comment by axelitus** [comment] 2021-02-01 17:37
I'm having issues with this too. Trying to setup Github actions to test on both Linux and Windows, but the Windows action always fails. I have set up PHP locally on Windows 10 and ran some commands on it from the CMD:
![image](https://user-images.githubusercontent.com/732441/106495657-9a774a80-6481-11eb-8373-5e04bd6e3df0.png)

I ran the command `composer exec 'echo "%PATH%"'` as instructed in issue #5045 but it fails with `Script 'echo handling the __exec_command event returned with error code 1` as all my defined scripts in composer.json (example: `"test": "./vendor/bin/phpunit --colors=always"`). This also fails in Powershell:
![image](https://user-images.githubusercontent.com/732441/106495885-d8746e80-6481-11eb-8bd0-e31d23d115fd.png)

**Comment by stof** [comment] 2021-02-01 17:48
Well, in the windows shell, you have to use `.\vendor\bin\phpunit` instead of `./vendor/bin/phpunit` due to the directory separator. cmd.exe does not support using Unix paths.

But for composer scripts, you can simplify that as `phpunit --colors=always`. Composer adds the `vendor/bin` folder as the first folder in the PATH when running scripts. That helps a lot writing cross-platform commands.

**Comment by axelitus** [comment] 2021-02-01 18:20
Hey @stof, you are correct: the CMD does not understand `/` as path separator:
![image](https://user-images.githubusercontent.com/732441/106500158-1b851080-6487-11eb-9a61-5c0f3b61992e.png)

Though in this case, it doesn't matter because Composer runs a `realpath()` before using it, so all dir separators get corrected (I ran the commands directly in the shell just for the purpose of shedding some light on my issue).

I did clone the Composer package and followed the command execution to see what was going on. The local vendor path gets indeed prepended to the PATH variable, so I got to the same conclusion as you: remove the `./vendor/bin/` part altogether and just leave the "vendored" command for Composer to execute).

Will do this for the commands and cross-check that everything still works as intended. Thank you for taking the time to answer @stof!

**Closed** 2021-02-23 07:58 UTC
Labels: Bug
