### ISSUE TITLE
Git Downloader Fetches Everything

### ISSUE THREAD

**Issue by timb-pt** [composer/composer#4926] opened 2016-02-16 16:59 UTC
We're attempting to check out a repository without letting Composer autoload the PHP classes in that repository. Our current solution looks something like this:

```json
{
    "name": "my-namespace/my-meta-package",
    "description": "My Meta Package",
    "minimum-stability": "stable",
    "license": "proprietary",
    "type": "metapackage",
    "config": {
        "process-timeout": 999999
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "my-namespace/my-repo",
                "version": "0.1.0",
                "source": {
                    "url": "git@github.com:my-namespace/my-repo.git",
                    "type": "git",
                    "reference": "0.1.0"
                },
                "type": "zend-extra"
            }
        }
    ],
    "require": {
        "composer/installers": "1.0.*",
        "my-namespace/my-repo": "0.1.0"
    },
    "extra": {
        "installer-paths": {
            "my-path/folder": [ "my-namespace/my-repo" ]
        }
    }
}
```

When we ran Composer, the process failed while running `git fetch composer` (obtained via the `pstree` command near the time of failure). The repository it was fetching from was very large and has a very long history w/ multiple branches we currently have to maintain.

We need to include Git in our circumstances because this is a development meta package, but it's alright if we don't fetch every branch and tag.

Is there a good reason why we're fetching every branch in the `composer` remote instead of just the branch we want to checkout? If not, I see room for a significant performance improvement here.

**Comment by hkdobrev** [comment] 2016-02-16 17:11
I asked a similar question about checking just a single branch here: https://github.com/composer/composer/issues/4870#issuecomment-179764588

**Comment by alcohol** [comment] 2016-02-17 13:21
Can you explain your use-case?

**Comment by timb-pt** [comment] 2016-02-17 22:11
@alcohol This is meant as a development meta package, i.e. a developer would use Composer as (high-level) part of the process of deploying their local stack.

We're dealing with an absolutely massive repository of legacy code that has a very long history, and we're only interested in fetching a small portion of that history. It's only one of several repos we're fetching, though.

Due to the meta package nature of our Composer configuration, we're not interested in any kind of top-level autoloading for the development repos.

The problem at hand is specifically pruning the legacy repository's code to only the branch we're interested in while keeping all the other advantages of this configuration.

**Comment by Seldaek** [comment] 2016-02-25 18:13
Closing as duplicate of #3449 - btw please check https://github.com/composer/composer/pull/4961 as it is an attempt at implementing that.

**Closed by Seldaek** 2016-02-25 18:13 UTC
Labels: Support
