### ISSUE TITLE
Weird dependency resolution behaviour

### ISSUE THREAD

**Issue by jyggen** [composer/composer#6188] opened 2017-02-21 15:55 UTC
Let's say I have this `composer.json`:

```json
{
    "require": {
        "zendframework/zend-expressive-fastroute": "^2.0",
        "zendframework/zend-stratigility": "^1.3",
        "sami/sami": "^4.0",
        "phpunit/phpunit": "^5.7"
    }
}
```

I run `composer update` and it installs perfectly fine. But I like to have my dependencies sorted alphabetically, like this:

```json
{
    "require": {
        "phpunit/phpunit": "^5.7",
        "sami/sami": "^4.0",
        "zendframework/zend-expressive-fastroute": "^2.0",
        "zendframework/zend-stratigility": "^1.3"
    }
}
```

Now when I run `composer update` (after removing my lock file and vendor directory) I get the following error:

```shell
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zendframework/zend-stratigility 1.3.0 requires http-interop/http-middleware ^0.2.0 -> satisfiable by http-interop/http-middleware[0.2.0].
    - zendframework/zend-stratigility 1.3.1 requires http-interop/http-middleware ^0.2.0 -> satisfiable by http-interop/http-middleware[0.2.0].
    - zendframework/zend-stratigility 1.3.2 requires http-interop/http-middleware ^0.2.0 -> satisfiable by http-interop/http-middleware[0.2.0].
    - zendframework/zend-stratigility 1.3.3 requires http-interop/http-middleware ^0.2.0 -> satisfiable by http-interop/http-middleware[0.2.0].
    - Conclusion: don't install http-interop/http-middleware 0.2.0
    - Installation request for zendframework/zend-stratigility ^1.3 -> satisfiable by zendframework/zend-stratigility[1.3.0, 1.3.1, 1.3.2, 1.3.3].
```

Not sure why order of dependencies should matter? The dependencies become resolvable again when I, for example, do one of the following:

1. Move `phpunit/phpunit` below `sami/sami`:
```json
{
    "require": {
        "sami/sami": "^4.0",
        "phpunit/phpunit": "^5.7",
        "zendframework/zend-expressive-fastroute": "^2.0",
        "zendframework/zend-stratigility": "^1.3"
    }
}
```

2. Add a strict requirement of `zendframework/zend-expressive-router` (a less strict `^2.0` does not work):
```json
{
    "require": {
        "phpunit/phpunit": "^5.7",
        "sami/sami": "^4.0",
        "zendframework/zend-expressive-fastroute": "^2.0",
        "zendframework/zend-expressive-router": "^2.0 <2.1",
        "zendframework/zend-stratigility": "^1.3"
    }
}
```

3. Move `sami/sami` to the bottom, put on my yolo pants and change the constraint to `*` (I still get 4.0 installed though):
```json
{
    "require": {
        "phpunit/phpunit": "^5.7",
        "zendframework/zend-expressive-fastroute": "^2.0",
        "zendframework/zend-stratigility": "^1.3",
        "sami/sami": "*"
    }
}
```

Any idea what's going on? 😄 

Running the following version (though it's reproducible on earlier tagged version as well):

```shell
$ composer --version
Composer version 1.4-dev (667f1d7815c004b0d50b161fd1582c181435947a) 2017-02-21 12:53:19
```

Output of `composer diagnose`:

```shell
$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

**Comment by stof** [comment] 2017-02-21 15:58
Can you show the output of ``composer why-not http-interop/http-middleware 0.2.0`` in the case where you have the issue ?

**Comment by bolmstedt** [comment] 2017-02-21 16:11
Sadly, it doesn't work to `composer why-not http-interop/http-middleware 0.2.0` since nothing is installed:
```
  [InvalidArgumentException]
  Could not find package "http-interop/http-middleware" in your project
```

**Comment by jyggen** [comment] 2017-02-21 16:55
From what I've gathered while debugging this:
- `zendframework/zend-stratigility ^1.3` requires `http-interop/http-middleware ^0.2.0`.
- `zendframework/zend-expressive-fastroute ^2.0` requires `zendframework/zend-expressive-router ^2.0`.
  - `zendframework/zend-expressive-router 2.0.0` _does not_ require `http-interop/http-middleware`.
  - `zendframework/zend-expressive-router 2.1.0` requires `http-interop/http-middleware ^0.4.1`. 

Obviously `zendframework/zend-stratigility ^1.3` won't resolve with `zendframework/zend-expressive-router 2.1.0`, but should resolve just fine with `zendframework/zend-expressive-router 2.0.0`, which it does with the first JSON but with the second (where only the order of the dependencies differs).

What makes it really peculiar is that fiddling around with `sami/sami` can make it resolvable, which is why the first JSON works and not the second I guess.

I also haven't found a case yet where a JSON is unresolvable despite explicitly telling Composer to install `zendframework/zend-expressive-router ^2.0 <2.1`.

**Comment by JanTvrdik** [comment] 2017-03-02 08:15
@stof The is probably very similar issue https://github.com/composer/composer/issues/6220

**Comment by Seldaek** [comment] 2017-03-06 14:37
Definitely seems like a duplicate of #6220, closing, see [my comment there](https://github.com/composer/composer/issues/6220#issuecomment-284412842)

**Closed by Seldaek** 2017-03-06 14:37 UTC
