### ISSUE TITLE
I can't do anything with composer because  [UnexpectedValueException]

### ISSUE THREAD

**Issue by ttimot24** [composer/composer#4315] opened 2015-07-30 07:58 UTC
[UnexpectedValueException]
  Could not parse version constraint <=2.*: Invalid version string "2.*"

composer update says it's the latest version.

 How can I fix it?

**Comment by alcohol** [comment] 2015-07-30 08:01
Duplicate of #4307

**Closed by alcohol** 2015-07-30 08:01 UTC
