### ISSUE TITLE
Removing package and running update, updates all instead of removing from lock

### ISSUE THREAD

**Issue by dazz** [composer/composer#2946] opened 2014-04-28 14:36 UTC
Steps to reproduce:

1. remove entry from `composer.json`
1. run `./composer.phar update zendframework/zend-permissions-acl`

The package gets removed, but all other packages are also updated which it should not do.

**Comment by roukmoute** [comment] 2016-01-06 16:02
With the version (64b0d721838cdceef679761c5cf69a0d070d14c9), I've used command `remove` but (like it's written on documentation), it only remove in composer.json.

But why do you update composer.lock with an eventually new version of the package we would like to remove ?

Actually use `remove`, is just like:
- remove `my/package` from composer.json
- `composer update my/package`

To remove entirely in composer.lock we must do `composer update`.
But we do not update all packages, just remove a package.

**Comment by Seldaek** [comment] 2016-02-21 14:50
Closing as duplicate of #4895 as it now contains a lot more details/discussion than this one.

**Closed by Seldaek** 2016-02-21 14:50 UTC
Labels: Bug
