### ISSUE TITLE
"require-dev" conflict with "require" even with "composer install --no-dev"

### ISSUE THREAD

**Issue by laszlof** [composer/composer#5727] opened 2016-09-27 15:35 UTC
My `composer.json`:
<details>
<summary>CLICK TO EXPAND</summary>
```json
{
  "name": "projectname/core",
  "description": "The projectname Core Application",
  "license": "proprietary",
  "require": {
    "php": ">=5.6",
    "ext-mcrypt": "*",
    "ext-openssl": "*",
    "itbz/fpdf": "^1.0",
    "guzzlehttp/guzzle": "^6.0",
    "knplabs/github-api": "^1.5",
    "duosecurity/duo_php": "^1.0",
    "zendframework/zendframework1": "^1.0",
    "projectname/lib": "dev-master as 0.0.6",
    "projectname/libvirt": "dev-master as 0.0.1",
    "aws/aws-sdk-php": "^3.18"
  },
  "require-dev": {
    "projectname/tester": "dev-master as 0.0.1",
    "squizlabs/php_codesniffer": "^2.0",
    "projectname/phpcs": "dev-master as 0.0.2"
  },
  "autoload": {
    "psr-4": {
      "ProjectName\\Db\\": "projectname/db",
      "ProjectName\\": "src/ProjectName/",
      "ProjectLib\\": "lib/ProjectLib"
    },
    "psr-0": {
      "Env": "projectname/include/",
      "CLI": "projectname/include/",
      "Ctrl": "projectname/include/",
      "View": "projectname/include/",
      "Plugin": "projectname/include/",
      "ProjectName": "projectname/include/",
      "Plugin_ProjectName_NW": "projectname/include/Plugin",
      "": "projectname/include/ProjectName/Base/"
    },
    "files": [ "vendor/duosecurity/duo_php/duo_web.php" ],
    "classmap": [ "projectname/include/ProjectName/Base/" ]
  },
  "autoload-dev": {
    "psr-4": {
      "ProjectName\\Tests\\Tester\\": "tests/_support/Tester/",
      "ProjectName\\Tests\\": "tests/"
    }
  },
  "repositories": [
    { "type": "vcs", "url": "https://github.com/projectname/lib" },
    { "type": "vcs", "url": "https://github.com/projectname/libvirt" },
    { "type": "vcs", "url": "https://github.com/projectname/tester" },
    { "type": "vcs", "url": "https://github.com/projectname/phpcs" },
    { "type": "package",
      "package": {
        "name": "duosecurity/duo_php",
        "version": "1.0.0",
        "source": {
          "url": "https://github.com/duosecurity/duo_php/",
          "type": "git",
          "reference": "master"
        }
      }
    }
  ],
  "scripts": { },
  "extra": {
    "dependencies": {
      "projectname/blink": "v0.2.0"
    }
  }
}

```
</details>

Output of `composer diagnose`:
<details>
<summary>CLICK TO EXPAND</summary>
```
└──╼ composer diagnose
Checking composer.json: WARNING
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.projectname/lib : unbound version constraints (dev-master as 0.0.6) should be avoided
require.projectname/libvirt : unbound version constraints (dev-master as 0.0.1) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```
</details>

When I run this command:
```
composer install --no-dev
```

I get the following output:
<details>
<summary>CLICK TO EXPAND</summary>vi co
```
Loading composer repositories with package information
Installing dependencies from lock file
Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for projectname/lib dev-master -> satisfiable by projectname/lib[0.0.6].
    - projectname/lib 0.0.6 requires ruflin/elastica ^3.2 -> no matching package found.
  Problem 2
    - projectname/lib dev-master requires ruflin/elastica ^3.2 -> no matching package found.
    - projectname/libvirt 0.0.1 requires projectname/lib dev-master as 0.0.5 -> satisfiable by projectname/lib[dev-master].
    - Installation request for projectname/libvirt dev-master -> satisfiable by projectname/libvirt[0.0.1].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

```
</details>

And I expected this to happen:

The problem here is monolog has a REQUIRE-DEV dependency on elastica that does not include version 3.2.x that I am requesting as a REQUIRE inside `projectname/lib`. By specifying `--no-dev`, it should not be trying to install the require-dev packages within the lockfile. Further more, it certainly shouldn't cause the install to fail due to a version conflict, since the require-dev package will never be installed.

**Comment by alcohol** [comment] 2016-09-27 15:44
`require-dev` is not even taken into account of dependencies. We only look at `require-dev` of the root package. So your issue must be caused by something else.

**Comment by laszlof** [comment] 2016-09-27 15:54
We commit the lock file to our repo, and the require-dev is trickling up to the root package. We do not have a require-dev for elastica in the root package's composer.json

**Comment by stof** [comment] 2016-09-27 15:57
@laszlof commiting the lock file does not change anything to the root package requirements and dev requirements (the composer.json is what defines the root package).

the problem comes form the fact that you have a requirement on ``projectname/lib`` which has a non-dev requirement on ``ruflin/elastica ^3.2`` in the 0.0.6 release. Monolog is not involved at allin your error.

**Comment by laszlof** [comment] 2016-09-27 16:03
Yes. the non-dev requirement for `ruflin/elastica ^3.2` is completely valid. We use this package in our `lib` for non-dev. Running composer install on the `lib` repo itself, works fine. Its only when we run it from the root level package where we run into the problem.

**Comment by laszlof** [comment] 2016-09-27 16:09
I think I see where the issue might lie, and you are correct, it has nothing to do with monolog. Going to do some further troubleshooting to diagnose this. I'll go ahead and close the monolog issue for now.

**Comment by Seldaek** [comment] 2016-09-29 06:55
Closing here because I don't see what we can do, but feel free to keep discussing.

**Closed by Seldaek** 2016-09-29 06:55 UTC
Labels: Support
