### ISSUE TITLE
GitLab Driver

### ISSUE THREAD

**Issue by houstona** [composer/composer#6292] opened 2017-03-23 22:00 UTC
I am running into an issue with using the gitlab driver from within a repo of type composer. It says that there is no such download type. The packages.json contains gitlab as the type. Is this not how you use the GitLab driver?

**Comment by alcohol** [comment] 2017-03-24 10:34
no, the type is either `vcs` or `git` (and I highly recommend using `vcs`).

**Comment by mikl** [comment] 2017-04-10 10:27
Yeah, the GitLab driver is a pain in the ass. You can disable it, so normal Git is used by declaring your repo like this:

```
        {
            "type": "git",
            "url": "git@gitlab.com:docu/drupal-docu_media.git"
        }
```

(type: git being the important part)

**Comment by Seldaek** [comment] 2017-04-13 20:11
@mikl care to share more about why it's a pain in the ass?

**Comment by mikl** [comment] 2017-04-13 20:57
@Seldaek sorry, that was rather harsh. I’ve been unpleasantly surprised by it a few times, and I never managed to get it to work properly.

1. It (presumably) works fine for public repos, I’ve only had problems with private repos.
2. Main frustration is that it works “magically”. I first ran into it when I switched Git hosts. Suddenly, all my builds were breaking, because I had change a repo URL from `"git@private.git.server:something/something.git"` to `"git@gitlab.com:something/something.git"`, and it was giving strange errors about trying to download tarballs via HTTPS. I spent half a day debugging this, before I found out it was because composer was trying to be clever, and thereby breaking the build process. If it’d only used SSH (as a git@something URL normally implies), it would have worked fine.
3. Either the instructions it gives you are wrong, or I’m just full of fail. Whichever is the case, I never managed to figure out how to generate the magic key that composer needs to use Gitlab’s API to install stuff.
4. There’s no obvious way to avoid the “magic”. If you have a repo at Gitlab, composer will use the gitlab driver. I think by the time I finally arrived at this thread, that gave me an important clue (setting type to `git` disables the magic), I’d spent more than a days working time with different failed solutions, hacks and workarounds.

Anyway, sorry for my original, unproductive outburst. Hope this feedback is more useful.

**Comment by houstona** [comment] 2017-04-13 21:49
I still have yet to figure out how to use the GitLab API as well.

**Comment by ohthehugemanatee** [comment] 2017-06-29 08:48
I also can't get a private repo on gitlab.com to work with a personal token with composer 1.4.2 .

First: I tested the token working with
` curl --header "PRIVATE-TOKEN: abcdefghijklmnopqrst" "https://gitlab.com/api/v3/projects/username%2Fprojectname"`

I tried `composer config gitlab-token.gitlab.com abcdefghijklmnopqrst`, without error. But still `composer install` or `composer update` fails on `permission denied (publickey)`. 

So I tried configuring manually with this in composer.json:

```
    "config": {
        "gitlab-token": {
            "gitlab.com": "abcdefghijklmnopqrst"
        }
    },
    "repositories": {
       {
            "type": "vcs",
            "url": "git@gitlab.com:username/projectname.git"
        }
```

Still no luck. I've tried types `vcs`, `git`, and `gitlab`. I've tried with the `gitlab-token` config section in `auth.json` (as `composer config` does it). I can only ever retrieve this repo when my SSH key is available.

**Comment by ohthehugemanatee** [comment] 2017-06-29 08:52
update: gitlab-token works if I explicitly set gitlab-domain!

```
    "config": {
        "gitlab-domains": [
            "gitlab.com"
        ],
        "gitlab-token": {
            "gitlab.com": "abcdefghijklmnopqrst"
        }
    },
```

It only seems to work when using repository type `gitlab`. `vcs` and `git` still fail. 

So the [docs](https://getcomposer.org/doc/06-config.md#gitlab-domains) need to be updated to reflect the fact that gitlab-domains does not default to gitlab.com anymore.

**Comment by renoirb** [comment] 2017-12-06 04:34
I might need to add one more problematic use-case.

When trying to run within a GitLab runner, from `.gitlab-ci.yml`.

What's the appropriate `url` when you are only over `https`, on a different port than 443 (e.g. `5443`, and don't have `ssh` on your GitLab private repositories?

Documentation doesn't cover that use-case.

Here is what I have, that looks close to working.

It's flaky, so far, but I had (sometimes) successful builds and I'm unsure if it's some GitLab cache, or because I ran the command in `before_script`, or anything else. As I said, that's confusing from GitLab.

**My setup**

```yaml
{
    "name": "foo/parent-project",
    "type": "project",
    "require": {
        "Foo/project": "dev-master"
    },
    "repositories": [
      {
        "type": "vcs",
        "url": "https://foo.gitlab.example.org:5443/foo/project.git"
      }
    ]
}
```

To call composer, my `.gitlab-ci.yml` calls a PHP Docker image that already has Composer installed (possibly an older version (1.5.2), that has yet to be looked at).

Here is the shell script that is called:

```
#!/usr/bin/env bash

set -xe

command -v composer >/dev/null 2>&1 || { echo >&2 "Required binary composer not found. This script will not work. Aborting."; exit 1; }

composer --version


composer self-update


if [ ! -z ${CI_REPOSITORY_URL+x} ]; then
# $CI_REPOSITORY_URL variable is set when we are in GitLab

COMPOSER_GITLAB_DOMAIN="foo.gitlab.example.org"
COMPOSER_GITLAB_PORT=":5443"
COMPOSER_DEPENDENCY_URL="https://${COMPOSER_GITLAB_DOMAIN}${COMPOSER_GITLAB_PORT}/Foo/project.git"

# Already available environment variables
# https://docs.gitlab.com/ce/ci/variables/README.html
# $CI_REGISTRY_USER
# $CI_JOB_TOKEN

(cat <<- _EOF_
{
  "gitlab-token": {
    "${COMPOSER_GITLAB_DOMAIN}": "${CI_JOB_TOKEN}"
  }
}
_EOF_
) > ${COMPOSER_HOME}/auth.json
# ${COMPOSER_HOME} is where I keep in cache for GitLab runners.

    # Re-use project repository CI_REPOSITORY_URL with username:password pair to make Compose
    # to be able to clone our dependency.
    # https://getcomposer.org/doc/articles/http-basic-authentication.md
    # https://getcomposer.org/doc/05-repositories.md#git-alternatives
    # https://getcomposer.org/doc/06-config.md#gitlab-oauth

    # An alternate is to use $CI_REPOSITORY_URL and replace "parent-project" to the
    # dependency "project" name and leverage gitlab-ci username:password magic URL pair.
    # But that doesn't work.
    #REWRITTEN_DEPENDENCY_URL=`echo $CI_REPOSITORY_URL | sed "s;parent-project;project;"`

    composer config repositories.0 gitlab "${COMPOSER_DEPENDENCY_URL}"
    composer config gitlab-domains "${COMPOSER_GITLAB_DOMAIN}"

    composer config --list
    composer install --prefer-dist --no-progress --no-suggest -vvv

else
# $CI_REPOSITORY_URL variable is NOT set. Run from local PHP runtime

    composer config --list
    composer install --no-suggest -vvv

fi
```

**Comment by renoirb** [comment] 2017-12-12 03:18
Related to this issue, I've created a PR #6895 that should help my situation with port number.
Maybe I can see what else related to the person who opened the ticket, if I can help there too.

**Comment by Seldaek** [comment] 2020-09-11 15:13
Lots of improvement in GitLabDriver since then so closing, please reopen if still relevant with Composer 2.0-RC1

**Closed by Seldaek** 2020-09-11 15:13 UTC
Labels: Support

**Comment by renoirb** [comment] 2020-09-12 00:26
Oh, I forgot about this and PR #6895 and thought it got merged. Yeah, more work needed to be done. I recall having used this and was fine with some merge. Unsure now. I've stopped using PHP since after that. I hope GitLab on non standard port works now!
Merci de faire suite, et désolé d'avoir laissé ce buillet ouvert, Jordi.

**Comment by Seldaek** [comment] 2020-09-14 18:43
No worries :) https://github.com/composer/composer/pull/6895 was merged and other stuff was fixed, IIRC we support GitLab installs in custom paths (and ports I think) now.

**Comment by renoirb** [comment] 2020-09-14 19:31
Sadly, I can't confirm, I no longer work at a company that uses GitLab with a port number, nor  do I program PHP much anymore. I would've confirmed if I could
