### ISSUE TITLE
Segmentation fault while execute composer install

### ISSUE THREAD

**Issue by RazeSoldier** [composer/composer#7139] opened 2018-02-27 16:27 UTC
My `composer.json`:

https://github.com/wikimedia/mediawiki/blob/master/composer.json

When I run this command:

```
composer install
```

I get the following output (only one line output):

```
Segmentation fault
```

After my test, this error does not appear on another server (fresh PHP installation). I use composer version 1.7-dev (ef46a8afa4f5d845befbc7be832432c4b30d6313) 2018-02-11 10:02:41.

**Comment by stof** [comment] 2018-02-27 17:15
A Segmentation fault indicates a bug in the C layer of PHP (for instance because of trying to access invalid memory).

So this should be reported to PHP or to the impacted PHP extension.

To try to understand where it comes from, compare the PHP runtimes of both servers (version of PHP, list of enabled extensions, versions of these extensions).

This is generally not the kind of errors that can be fixed by a PHP script.

**Comment by johnstevenson** [comment] 2018-02-27 18:02
Are you using the xdebug and opcache extensions by any chance?

**Comment by RazeSoldier** [comment] 2018-02-27 18:10
> Are you using the xdebug and opcache extensions by any chance?
Yes, I am used opcache.
> To try to understand where it comes from, compare the PHP runtimes of both servers
I currently only know one server (without error) is PHP via yum installed , the other server (with error) is PHP via compiler installed.

**Comment by johnstevenson** [comment] 2018-02-27 18:14
And what about xdebug? Run `php -m` to see the loaded extensions.

**Comment by RazeSoldier** [comment] 2018-02-27 18:38
> And what about xdebug? Run php -m to see the loaded extensions.

No.

**Comment by johnstevenson** [comment] 2018-02-27 19:11
Okay thanks. I thought it might be related to this xdebug-opcache bug: https://bugs.php.net/bug.php?id=75932, but that isn't the case. However, if you have `opcache.enable_cli=1` then that can sometimes cause weird problems and might be worth a look.

**Comment by RazeSoldier** [comment] 2018-02-27 19:42
I know there is a big problem with a project because of opcache. But composer should not have this problem, since no matter how I set `opcache.enable_cli`, the problem persists.

**Comment by alcohol** [comment] 2018-02-28 16:48
Composer does not have this problem as long as you do not offer a reproducible scenario.

**Closed** 2018-04-12 17:34 UTC
