### ISSUE TITLE
Require vendor/package:0@dev is broken since 1.10.13

### ISSUE THREAD

**Issue by michaelKaefer** [composer/composer#9524] opened 2020-11-27 18:16 UTC
My `composer.json`:
```json
{
    "name": "michael/reproducer"
}
```

When I run this commands (does not matter which exact version, it is the same for every version since 1.10.13):
```
composer self-update 1.10.13
composer req composer/semver:0@dev
```

I get the following output:
```
  [InvalidArgumentException]                                                
  Could not find package composer/semver in a version matching 0@dev  
```

And I expected this to happen: it should work - it _is_ working when using a version smaller than 1.10.13

When I run:
```
composer self-update 1.10.12
composer req composer/semver:0@dev
```

I get the following output:
```
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing composer/semver (dev-main a02fdf9): Cloning a02fdf930a from cache
Writing lock file
Generating autoload files
55 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Symfony recipes are disabled: "symfony/flex" not found in the root composer.json

Nothing to unpack
```

It looks like a BC break to me. Or was it never allowed/suggested and therefore wrong to use constraints like `0@dev`?

If somebody can give me a hint how then I would love to fix it. I tried on my own but I couldn't.

The diff from `1.10.12` to `1.10.13`: https://github.com/composer/composer/compare/1.10.12...1.10.13

**Comment by Seldaek** [comment] 2020-12-03 21:20
The issue is in https://github.com/composer/semver/compare/1.6.0...1.7.0 I believe. Probably should be fixed but not sure how easy that's gonna be.

**Comment by stof** [comment] 2020-12-04 10:49
I don't see how this could be working actually. composer/semver dev-main has no reason to match a `0` constraint

**Comment by Seldaek** [comment] 2020-12-04 10:51
Not the `0` bit, but passing stability modifiers should be supported imo, like `composer require foo/bar:@dev` should pick the latest dev version.

**Comment by stof** [comment] 2020-12-04 10:55
but that's not what the issue does

**Comment by michaelKaefer** [comment] 2020-12-04 16:03
That's true, `composer req composer/semver:@dev` does work and `composer req composer/semver:0@dev` does not work.

Maybe it is correct to say that it was a bug in `<=1.10.12` that `0@dev` did work. Then this issue can be closed and can be found here for information if others got the same problem. The only solution then is to change `0@dev` to something else like `@dev` or `dev-master`.

**Comment by Seldaek** [comment] 2020-12-04 16:35
Ah well if `@dev` works then yes you should use that, or dev-main or whatever.

**Closed by Seldaek** 2020-12-04 16:35 UTC
Labels: Bug
