### ISSUE TITLE
Composer-update keeps old remotes when git repository URL changes

### ISSUE THREAD

**Issue by DHager** [composer/composer#3874] opened 2015-03-25 22:31 UTC
Composer-update should re-clone the temporary repositories in the `vendor` folder when their original source URL changes, or at least update the git remotes.  

Because it does not, you can end up with a workflow that pushes and pulls your vendor-folder changes against the wrong remote repository.

# Bug repro example

## Initial setup

1. We have two composer packages, `example/bug` and `example/dep`. 
2. Each contains only a minimal `composer.json` file.
3. There's an original git repository for the `example/dep` project in `/tmp/cbug/dep1` and a clone in `/tmp/cbug/dep2`. 

In `/tmp/cbug/mainproj/composer.json` : 

    {
        "name": "example/bug",    
        "require": {            "example/dep": "*@dev"        },    
        "repositories":[
            {"packagist": false},
            {"type" : "vcs", "url" : "/tmp/cbug/dep1" }
        ]
    }

In `/tmp/cbug/dep/composer.json` :

    { "name": "example/dep" }

## First composer update

Running commands:

    user@host:/tmp/cbug/mainproj$ ls
    composer.json
    user@host:/tmp/cbug/mainproj$ composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)         
      - Installing example/dep (dev-master 7b14991)
        Cloning 7b149918414b8954e3d86db52201c22569dfc7a4
    
    Writing lock file
    Generating autoload files

Checking origin of the vendor folder's `example/dep`:

    user@host:/tmp/cbug/mainproj/vendor/example/dep$ git remote -v
    composer	/tmp/cbug/dep1 (fetch)
    composer	/tmp/cbug/dep1 (push)
    origin	/tmp/cbug/dep1 (fetch)
    origin	/tmp/cbug/dep1 (push)

## Changing the repository URL and seeing issues

So far so good, but now my remote repo has moved, perhaps because IT migrated it to a different server or something. Easy enough, all I should need to do is update `composer.json`. This new version points to the `dep2` folder:

    {
        "name": "example/bug",    
        "require": {            "example/dep": "*@dev"        },    
        "repositories":[
            {"packagist": false},
            {"type" : "vcs", "url" : "/tmp/cbug/dep2" }
        ]
    }

Running update with new repo-url:

    user@host:/tmp/cbug/mainproj$ composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)         
    Nothing to install or update
    Writing lock file
    Generating autoload files

Wait, it didn't notice any change? That's worrisome. Let's check our vendor folder: 

    user@host:/tmp/cbug/mainproj/vendor/example/dep$ git remote -v
    composer	/tmp/cbug/dep1 (fetch)
    composer	/tmp/cbug/dep1 (push)
    origin	/tmp/cbug/dep1 (fetch)
    origin	/tmp/cbug/dep1 (push)

**Uh oh!** Our vendor folder (which is a temporary repo) is still pointing to the old `origin` repo. Changes will be pulled/pushed to the wrong place!

# What should have happened

If I delete the `vendor` folder, that functions as a workaround, forcing composer to start from scratch:

    user@host:/tmp/cbug/mainproj$ rm -fr vendor/
    user@host:/tmp/cbug/mainproj$ composer update
    Loading composer repositories with package information
    Updating dependencies (including require-dev)         
      - Installing example/dep (dev-master 7b14991)
        Cloning 7b149918414b8954e3d86db52201c22569dfc7a4
    
    Writing lock file
    Generating autoload files

Let's check:

    user@host:/tmp/cbug/mainproj/vendor/example/dep$ git remote -v
    composer	/tmp/cbug/dep2 (fetch)
    composer	/tmp/cbug/dep2 (push)
    origin	/tmp/cbug/dep2 (fetch)
    origin	/tmp/cbug/dep2 (push)

There we go, **now** it says `dep2`...

**Comment by DHager** [comment] 2015-03-27 21:19
Resembles the very-old issue #2416

**Comment by Seldaek** [comment] 2015-06-11 17:30
Some of this has been fixed by #3985 - the lock file part at least, but indeed the remotes aren't touched. 

I am not sure if it makes sense to go about modifying remotes though, because the composer one will be updated next time composer needs to use it, and the origin one is never touched after initial set up because users might want to change it to push back to some other repo.. So I don't know if updating that is really a good idea.. Maybe we could update it if it matches the composer one and so we assume both are outdated and we update them both in a same manner as was done in #3985, but directly calling into the GitDownloader not dispatching a full UpdateOperation.

**Comment by Brainshack** [comment] 2015-08-11 10:41
```
 Maybe we could update it if it matches the composer one and so we assume both are outdated and we update them both
```
I would really appreciate such a change. We are currently in the process of moving all of our git repositories (about 70, while using our own internal packagist installation) and having to change the origin remote for all those installed packages seems to be a lot of work. So +1 for that.

**Comment by Seldaek** [comment] 2016-04-18 09:10
Fixed in https://github.com/composer/composer/commit/73139a59bfc90ece25c112a27ec6ea7aa2b67451

**Closed by Seldaek** 2016-04-18 09:10 UTC
Labels: Bug

**Comment by mpdude** [comment] 2017-09-28 16:08
If I read this correctly, this updates the remote URL only during `composer update`?

Assume I run `composer install` and get a source installation of some package.

Then, the package URL changes. Somebody updates the `composer.lock` file and I get the new version. 

It seems that then a simple `composer install` will *not*  update the remote URL for the existing clone.

Is that the intended behaviour or a bug?
