### ISSUE TITLE
Trying to get Ratchet but always getting the same error

### ISSUE THREAD

**Issue by Ropy** [composer/composer#3846] opened 2015-03-15 05:05 UTC
I'm trying to get Ratchet (http://socketo.me) with the following command:

`php ~/composer.phar require cboden/ratchet`

But I'm always getting this error, no matter my connection is with or without proxy:

> Loading composer repositories with package information
> The "https://packagist.org/packages.json" file could not be downloaded: SSL: crypto enabling timeout
> Failed to enable crypto
> failed to open stream: operation failed
> https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
> Updating dependencies (including require-dev)
>                                                                                
>   [Composer\Repository\RepositorySecurityException]                            
>   The contents of http://packagist.org/p/guzzle/http$3628f7b092b3f580b2f8e534  
>   26360961fbbf005eba81be459e2aec5894f749b6.json do not match its signature. T  
>   his should indicate a man-in-the-middle attack. Try running composer again   
>   and report this if you think it is a mistake.                                
> 
> update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [packagesN]

Composer version:

> Composer version 1.0-dev (d57187446151ef84b28cb9f6b3ed38cc2cffc597) 2015-03-09 23:06:06

**Comment by jrobeson** [comment] 2015-03-16 03:34
so getting other packages does work as expected?

**Comment by jakoch** [comment] 2015-03-19 17:44
I used `composer require cboden/ratchet`, but couldn't reproduce your problem.
It seems that this is local SSL issue.
Are your SSL certs correctly defined in your php.ini?

**Comment by Seldaek** [comment] 2015-09-20 18:50
This is hopefully fixed by https://github.com/composer/composer/commit/ed954485239ad88f94bcee80a6a648d7943932f8

**Closed by Seldaek** 2015-09-20 18:50 UTC
