### ISSUE TITLE
No valid composer.json was found in any branch or tag of After update to 1.2.0

### ISSUE THREAD

**Issue by Koc** [composer/composer#5541] opened 2016-07-22 12:55 UTC
With the following composer.json:

``` json
{
    "name": "symfony/framework-standard-edition",
    "description": "The \"Symfony Standard Edition\" distribution",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "require": {
        "php": ">=5.5.9",
        "symfony/symfony": "~2.8",
        "doctrine/dbal": "<2.5",
        "doctrine/orm": "^2.4.8",
        "doctrine/doctrine-bundle": "~1.4",
        "twig/twig": "~1.24",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.4",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "^3.0.2",
        "incenteev/composer-parameter-handler": "~2.0",
        "ptachoire/cssembed": "~1.0",
        "doctrine/doctrine-migrations-bundle": "dev-master",
        "pagerfanta/pagerfanta": "dev-lazy-adapters as 1.0.3",
        "white-october/pagerfanta-bundle": "~1.0",
        "knplabs/knp-menu-bundle": "~2.0",
        "gregwar/form-bundle": "~2.7",
        "presta/sitemap-bundle": "1.4.*",
        "sonata-project/doctrine-orm-admin-bundle": "2.3.*",
        "sonata-project/admin-bundle": "2.3.*",
        "ornicar/apc-bundle": "dev-master",
        "juliendidier/buzz-bundle": "dev-master",
        "zapimir/sypexgeo": "dev-master",
        "willdurand/geocoder": "dev-sypex-geo-adapter as 1.7-dev",
        "willdurand/geocoder-bundle": "dev-sypexgeo",
        "stof/doctrine-extensions-bundle": "1.1.*@dev",
        "brouzie/sphinxy": "dev-master",
        "brouzie/sphinxy-bundle": "dev-master",
        "brouzie/brouzie-crossdomain-auth-bundle": "dev-master",
        "snc/redis-bundle": "^2.0",
        "predis/predis": "^1.0",
        "symfony-cmf/routing-bundle": "1.2.*@dev",
        "liuggio/excelbundle": "~2.0",
        "sonata-project/notification-bundle": "~2.3",
        "dompdf/dompdf": "0.6.*",
        "liip/imagine-bundle": "^1.5",
        "webfactory/exceptions-bundle": "@stable",
        "sonata-project/intl-bundle": "2.2.*@dev",
        "asm89/twig-cache-extension": "~1.0",
        "jh9/robokassa-bundle": "dev-copy-of-master",
        "vipx/bot-detect-bundle": "~2.0",
        "ornicar/akismet-bundle": "dev-master",
        "igorw/file-serve-bundle": "~1.0",
        "myclabs/deep-copy": "~1.3",
        "tedivm/fetch": "~0.6",
        "egulias/email-validator": "~1.2",
        "intaro/pinba-bundle": "~0.4",
        "oro/doctrine-extensions": "~1.0",
        "excelwebzone/recaptcha-bundle": "dev-master#2b85953d9ceb5719c878a0a1f6ea51fc86397d6c",
        "cocur/slugify": "dev-patch-2 as 1.4",
        "helios-ag/fm-bbcode-bundle": "^6.8",
        "mgp25/instagram-php": "dev-mirror",
        "gregwar/captcha-bundle": "1.*",
        "hownowstephen/php-foursquare": "1.2.*",
        "alchemy/zippy": "^0.3.5",
        "mxkh/url-finder": "^0.1.8"
    },
    "require-dev": {
        "sensio/generator-bundle": "~3.0",
        "pyrech/composer-changelogs": "^1.3@dev"
    },
    "scripts": {
        "post-install-cmd": [
            "Metal\\ProjectBundle\\Composer\\ScriptHandler::buildParameters",
            "SxGeo\\Composer::installDatabases",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-update-cmd": [
            "Metal\\ProjectBundle\\Composer\\ScriptHandler::buildParameters",
            "SxGeo\\Composer::installDatabases",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ]
    },
    "config": {
        "bin-dir": "bin"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "symfony-assets-install": "relative",
        "branch-alias": {
            "dev-master": "2.8-dev"
        },
        "sxgeo-databases": [
            "SxGeoCity"
        ]
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/Koc/BazingaGeocoderBundle"
        },
        {
            "type": "git",
            "url": "https://github.com/Koc/Pagerfanta"
        },
        {
            "type": "git",
            "url": "https://github.com/Koc/Geocoder"
        },
        {
            "type": "git",
            "url": "https://github.com/Koc/jh9RobokassaBundle"
        },
        {
            "type": "git",
            "url": "https://github.com/Koc/slugify"
        },
        {
            "type": "git",
            "url": "https://github.com/Koc/EWZRecaptchaBundle"
        },
        {
            "type": "git",
            "url": "https://github.com/Koc/Instagram-API"
        }
    ]
}
```

When I run this command:

```
composer update -vvv
```

I get this output:

```
Reading ./composer.json                                                                                                                                                                                           
Loading config file C:/Users/undefined/AppData/Roaming/Composer/auth.json                                                                                                                                         
Loading config file ./composer.json                                                                                                                                                                               
Checked CA file Z:\tmp\composer-cacert-bcf331364fef73d53e4368ba519a6c3fcb21ea7836c3d8efad4ec32731e8152a.pem: valid                                                                                                
Executing command (Z:\home\dev\metalloprokat): git branch --no-color --no-abbrev -v                                                                                                                               
Executing command (Z:\home\dev\metalloprokat): git describe --exact-match --tags                                                                                                                                  
Executing command (Z:\home\dev\metalloprokat): git log --pretty="%H" -n1 HEAD                                                                                                                                     
Reading C:/Users/undefined/AppData/Roaming/Composer/composer.json                                                                                                                                                 
Loading config file C:/Users/undefined/AppData/Roaming/Composer/auth.json                                                                                                                                         
Loading config file C:/Users/undefined/AppData/Roaming/Composer/composer.json                                                                                                                                     
Loading config file C:\Users\undefined\AppData\Roaming\Composer/auth.json                                                                                                                                         
Reading C:\Users\undefined\AppData\Roaming\Composer/auth.json                                                                                                                                                     
Reading Z:\home\dev\metalloprokat/vendor/composer/installed.json                                                                                                                                                  
Loading plugin Pyrech\ComposerChangelogs\ChangelogsPlugin                                                                                                                                                         
Running 1.2.0 (2016-07-19 01:28:52) with PHP 5.5.30 on Windows NT / 6.3                                                                                                                                           
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug                                                                                  
Loading composer repositories with package information                                                                                                                                                            
Executing command (CWD): git clone --mirror "https://github.com/Koc/BazingaGeocoderBundle" "C:/Users/undefined/AppData/Local/Composer/vcs/https---github.com-Koc-BazingaGeocoderBundle/"                          
Executing command (C:/Users/undefined/AppData/Local/Composer/vcs/https---github.com-Koc-BazingaGeocoderBundle/): git show-ref --tags                                                                              
Executing command (C:/Users/undefined/AppData/Local/Composer/vcs/https---github.com-Koc-BazingaGeocoderBundle/): git branch --no-color --no-abbrev -v                                                             
Executing command (C:/Users/undefined/AppData/Local/Composer/vcs/https---github.com-Koc-BazingaGeocoderBundle/): git branch --no-color                                                                            
Executing command (C:/Users/undefined/AppData/Local/Composer/vcs/https---github.com-Koc-BazingaGeocoderBundle/): git show "master":composer.json                                                                  


  [Composer\Repository\InvalidRepositoryException]                                                                                                                                                                
  No valid composer.json was found in any branch or tag of https://github.com/Koc/BazingaGeocoderBundle, could not load a package from it.                                                                        


Exception trace:                                                                                                                                                                                                  
 () at phar://Z:/usr/local/php53/composer.phar/src/Composer/Repository/VcsRepository.php:275                                                                                                                      
 Composer\Repository\VcsRepository->initialize() at phar://Z:/usr/local/php53/composer.phar/src/Composer/Repository/ArrayRepository.php:185                                                                       
 Composer\Repository\ArrayRepository->getPackages() at phar://Z:/usr/local/php53/composer.phar/src/Composer/DependencyResolver/Pool.php:104                                                                       
 Composer\DependencyResolver\Pool->addRepository() at phar://Z:/usr/local/php53/composer.phar/src/Composer/Installer.php:365                                                                                      
 Composer\Installer->doInstall() at phar://Z:/usr/local/php53/composer.phar/src/Composer/Installer.php:216                                                                                                        
 Composer\Installer->run() at phar://Z:/usr/local/php53/composer.phar/src/Composer/Command/UpdateCommand.php:174                                                                                                  
 Composer\Command\UpdateCommand->execute() at phar://Z:/usr/local/php53/composer.phar/vendor/symfony/console/Command/Command.php:259                                                                              
 Symfony\Component\Console\Command\Command->run() at phar://Z:/usr/local/php53/composer.phar/vendor/symfony/console/Application.php:844                                                                           
 Symfony\Component\Console\Application->doRunCommand() at phar://Z:/usr/local/php53/composer.phar/vendor/symfony/console/Application.php:192                                                                      
 Symfony\Component\Console\Application->doRun() at phar://Z:/usr/local/php53/composer.phar/src/Composer/Console/Application.php:231                                                                               
 Composer\Console\Application->doRun() at phar://Z:/usr/local/php53/composer.phar/vendor/symfony/console/Application.php:123                                                                                      
 Symfony\Component\Console\Application->run() at phar://Z:/usr/local/php53/composer.phar/src/Composer/Console/Application.php:104                                                                                 
 Composer\Console\Application->run() at phar://Z:/usr/local/php53/composer.phar/bin/composer:43                                                                                                                   
 require() at Z:\usr\local\php53\composer.phar:24                                                                                                                                       
```

And I expected this to happen: update. When rollback to 1.1.3 it works ok. Looks like problems with caching system of git repos (maybe on windows only)

**Comment by alcohol** [comment] 2016-07-25 06:32
Looks like using a the `--mirror` option (#5384) might present some issues. Though I have been unable to reproduce these locally so far.

**Comment by alcohol** [comment] 2016-07-25 06:32
Any particular reason your user is showing up as "undefined" by the way?

**Comment by Koc** [comment] 2016-07-25 07:02
@alcohol undefined - is name of my user.

**Comment by alcohol** [comment] 2016-07-25 07:05
@Seldaek or @curry684; do you think you might have some time to see if you can reproduce this on a Windows environment? I personally think it is unlikely this would be Windows specific, but would prefer to have someone check before assuming that to be true :-)

**Comment by curry684** [comment] 2016-07-25 09:56
I kinda switched to an Ubuntu VM for most of my development hehe, saves waiting for Bash for Windows to become mainstream and makes Docker all the more usable. However I tried the following minimal sample on both Windows and Ubuntu:
```json
{
    "require": {
        "zapimir/sypexgeo": "dev-master",
        "willdurand/geocoder": "dev-sypex-geo-adapter as 1.7-dev",
        "willdurand/geocoder-bundle": "dev-sypexgeo"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/Koc/BazingaGeocoderBundle"
        },
        {
            "type": "git",
            "url": "https://github.com/Koc/Geocoder"
        }
    ]
}
```
Worked fine on both.

True wtf though - why would you want to use Git repos for this? It looks like you're looking for [path repositories](https://getcomposer.org/doc/05-repositories.md#path) which are much more practical for local fork development.

**Comment by stof** [comment] 2016-07-25 10:08
@curry684 path repositories are not fine when you share things, which is a very valid use case for using VCS repositories pointing to your forks

**Comment by curry684** [comment] 2016-07-25 10:47
Semi-offtopic: I've developed multiple bundles in a concurrent team effort and we've always used local path repos for 'unstable development', syncing them from and to stable upstream git as required. Probably a matter of personal preference.

**Comment by Koc** [comment] 2016-07-26 08:07
My git version is `git version 1.9.5.msysgit.1` if it helps.

Please tell what commands should I run or where add var_dump for help investigate proble,. 1.2.0 is not major version so all previous config that works on 1.1.3 should work on 1.2.0 too.

**Comment by alcohol** [comment] 2016-07-26 08:33
That version of Git should not use the new functionality I mentioned. Would have to see what else changed between 1.1.3 and 1.2.0 I guess.

**Comment by Koc** [comment] 2016-07-26 08:41
Is it possible that composer incorrectly guess my git version and tryed to use this functionality?

**Comment by alcohol** [comment] 2016-07-26 08:42
No I don't think so. It could be a caching issue perhaps. Have you tried removing your entire cache directory (manually, don't use `composer clear-cache`) and then running the command again?

**Comment by Koc** [comment] 2016-07-28 10:28
I've removed files/repo/vsc directories and tryed run `composer update` again after this. Same problem like in 1st message

**Comment by Seldaek** [comment] 2016-07-28 11:49
We upgraded symfony/process from 2.8.6 to 2.8.8 between 1.1.3 and 1.2, I wonder if that's related.. If nobody can reproduce though it's kinda tough, @Koc can you install composer from source and try to debug this further maybe?

**Comment by Koc** [comment] 2016-07-28 14:34
yes, tell how to do it like: clone url, checkout rev, add var dump here and here and execute file

**Comment by alcohol** [comment] 2016-07-28 15:34
Something like this;

``` bash
git clone https://github.com/composer/composer /local/composer
cd composer
# git checkout 1.1.3
# or modify source files where relevant, etc
composer install # this uses global composer, not source install
cd /other/repository/where/issue/occurs
php /local/composer/bin/composer install
```

**Comment by Seldaek** [comment] 2017-01-22 19:09
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.

**Closed by Seldaek** 2017-01-22 19:09 UTC
Labels: Support
