### ISSUE TITLE
Silence deprecation warnings?

### ISSUE THREAD

**Issue by dzuelke** [composer/composer#7963] opened 2019-02-07 23:15 UTC
My `composer.json`:

```json
{
    "require": {
        "php": "*",
        "composer-plugin-api": "*",
```

When I run this command:

```
composer config bin-dir
```

I get the following output:

```
Deprecation warning: require.composer-plugin-api is invalid, it should have a vendor name, a forward slash, and a package name. The vendor and package name can be words separated by -, . or _. The complete name should match "[a-z0-9]([_.-]?[a-z0-9]+)*/[a-z0-9]([_.-]?[a-z0-9]+)*". Make sure you fix this as Composer 2.0 will error.
vendor/bin
```

There is no way to suppress this output; `--quiet` results in the config value not getting returned either (which seems a bit weird).

This is annoying when using Composer for automation; each call to `composer config` or similar now throws the same warnings about package case or missing slashes...

Should `--quiet` really result in `composer config` not returning anything? It's designed to explicitly return a value, after all... might be something worth changing in 2.0 (otherwise it's a BC break).

And should there be a flag for these kind of warnings? And/or should `composer config` even output them? I feel like this should be a `composer install` and `composer update` only thing.

**Comment by Seldaek** [comment] 2019-02-08 16:12
This will be fixed in the next 1.8 patch release (dupe of #7951). The --quiet thing might need attention indeed for the config command, so leaving this issue open.

**Comment by dzuelke** [comment] 2019-02-08 17:58
Sorry, I should have been more specific. That package name was just an example, but it also happens for uppercase characters for instance and I don't think it should for `composer config`

**Closed** 2019-02-10 11:59 UTC
Labels: Bug

**Comment by Seldaek** [comment] 2019-02-10 12:01
Fixed --quiet not outputting things, but also do note that with the existing release you can also do `2>/dev/null` to suppress warnings. The meaningful output is on stdout.

**Comment by Seldaek** [comment] 2019-02-10 12:02
Unfortunately it's very hard to suppress warnings in only a single location on our end, so couldn't fix that part.

**Comment by teamore** [comment] 2022-02-21 09:50
I have been having the same issue with composer v2.0.13, but by running
`sudo composer self-update` and thereby updating the composer version to v2.2.6, i could resolve it > no more deprecation notices.
