### ISSUE TITLE
Don't change semantic versions of Composer w/o version bump.

### ISSUE THREAD

**Issue by NfNitLoop** [composer/composer#3969] opened 2015-04-27 20:10 UTC
We noticed a couple of our builds broke today because the composer available at https://getcomposer.org/download/1.0.0-alpha9/composer.phar was changed.  Its old sha1 was c0917158e84c867ce69753fcbc04eb7c45bb58bb, but it has been updated to f4656e5c7a08213fb53384e45c8c430922b34422.  

I still had an old copy around and compared the two at: http://pastie.org/10116578

~~~
$ diff -r orig/ new/

diff -r orig/vendor/autoload.php new/vendor/autoload.php
7c7
< return ComposerAutoloaderInit6ccd5a50ed5df4dc5993d5b375e26928::getLoader();
---
> return ComposerAutoloaderInitc656bfcd87ec632e8b397a7e40670ee1::getLoader();
diff -r orig/vendor/composer/ClassLoader.php new/vendor/composer/ClassLoader.php
56a57,58
> private $classMapAuthoritative = false;
> 
58a61
> if (!empty($this->prefixesPsr0)) {
61a65,67
> return array();
> }
> 
146a153,154
> 
> 
208c216,219
< public function setPsr4($prefix, $paths) {
---
> 
> 
> public function setPsr4($prefix, $paths)
> {
246a258,278
> 
> public function setClassMapAuthoritative($classMapAuthoritative)
> {
> $this->classMapAuthoritative = $classMapAuthoritative;
> }
> 
> 
> 
> 
> 
> 
> public function isClassMapAuthoritative()
> {
> return $this->classMapAuthoritative;
> }
> 
> 
> 
> 
> 
> 
269c301
< include $file;
---
> includeFile($file);
292a325,342
> if ($this->classMapAuthoritative) {
> return false;
> }
> 
> $file = $this->findFileWithExtension($class, '.php');
> 
> 
>  if ($file === null && defined('HHVM_VERSION')) {
> $file = $this->findFileWithExtension($class, '.hh');
> }
> 
> if ($file === null) {
> 
>  return $this->classMap[$class] = false;
> }
> 
> return $file;
> }
293a344,345
> private function findFileWithExtension($class, $ext)
> {
295c347
<  $logicalPathPsr4 = strtr($class, '\\', DIRECTORY_SEPARATOR) . '.php';
---
>  $logicalPathPsr4 = strtr($class, '\\', DIRECTORY_SEPARATOR) . $ext;
324c376
<  $logicalPathPsr0 = strtr($class, '_', DIRECTORY_SEPARATOR) . '.php';
---
>  $logicalPathPsr0 = strtr($class, '_', DIRECTORY_SEPARATOR) . $ext;
349a402,403
> }
> }
352,353c406,412
<  return $this->classMap[$class] = false;
< }
---
> 
> 
> 
> 
> function includeFile($file)
> {
> include $file;
diff -r orig/vendor/composer/autoload_real.php new/vendor/composer/autoload_real.php
5c5
< class ComposerAutoloaderInit6ccd5a50ed5df4dc5993d5b375e26928
---
> class ComposerAutoloaderInitc656bfcd87ec632e8b397a7e40670ee1
22c22
< spl_autoload_register(array('ComposerAutoloaderInit6ccd5a50ed5df4dc5993d5b375e26928', 'loadClassLoader'), true, true);
---
> spl_autoload_register(array('ComposerAutoloaderInitc656bfcd87ec632e8b397a7e40670ee1', 'loadClassLoader'), true, true);
24,27c24
< spl_autoload_unregister(array('ComposerAutoloaderInit6ccd5a50ed5df4dc5993d5b375e26928', 'loadClassLoader'));
< 
< $vendorDir = dirname(__DIR__);
< $baseDir = dirname($vendorDir);
---
> spl_autoload_unregister(array('ComposerAutoloaderInitc656bfcd87ec632e8b397a7e40670ee1', 'loadClassLoader'));
48a46,50
> 
> function composerRequirec656bfcd87ec632e8b397a7e40670ee1($file)
> {
> require $file;
> }
Only in orig/vendor/composer: include_paths.php
~~~

This breaks anyone who is relying on repeatable builds by verifying the version of Composer that they use. For example, Homebrew:  https://github.com/Homebrew/homebrew-php/blob/master/Formula/composer.rb

Also, it's just a bad idea in general. :p 

Mostly I'm writing to get feedback about why this was changed and whether we should expect these types of changes moving forward.

**Comment by Seldaek** [comment] 2015-04-27 23:53
The old hashes should be back. The issue is just that the last releases aren't in the git repo for the website so when re-deploying the files got recreated using the latest composer available so they have the latest autoloader available as well, causing those minor differences.

I'll keep this open as a reminder though because I should probably change the release process to make sure the new releases get committed to avoid this in the future.

**Closed** 2015-04-29 23:05 UTC
