### ISSUE TITLE
Consider moving VersionParser/Constraint related classes to separate library

### ISSUE THREAD

**Issue by schmittjoh** [composer/composer#2523] opened 2013-12-22 13:05 UTC
Version parsing & comparison seems very useful outside of composer. It would be cool to have the related classes in a small, dedicated library.

**Comment by legoktm** [comment] 2015-05-21 06:29
Dupe of #3545?

**Comment by Seldaek** [comment] 2016-02-16 20:32
It's in composer/semver now

**Closed by Seldaek** 2016-02-16 20:32 UTC
Labels: Feature
