### ISSUE TITLE
Download progress when updating

### ISSUE THREAD

**Issue by maarten00** [composer/composer#3850] opened 2015-03-17 18:43 UTC
Recently the way Composer displays the package download progress seems to have changed. It used to be shown in a single line which would get updated until it reached 100%. Now it shows it's progress on a newline:
https://www.dropbox.com/s/kzw2yi52pwbi4yg/Screenshot%202015-03-17%2019.38.15.png?dl=0

This makes it very hard to see which packages have been updated when updating a project with a large amount of packages. Since we are using the Laravel framework it is not possible for us to limit the amount of packages we are using to resolve this.

**Comment by Seldaek** [comment] 2015-11-19 02:05
Closing as I can't reproduce and it's pretty old at this point, if it is still an issue let me know and please provide more details so we can hopefully reproduce and move this forward.

**Closed by Seldaek** 2015-11-19 02:05 UTC
