### ISSUE TITLE
IDEA - Install PHAR-files as --dev "requirements" instead of sources

### ISSUE THREAD

**Issue by heiglandreas** [composer/composer#6246] opened 2017-03-10 12:10 UTC
Currently common dev-packages like phpunit or phpcodesniffer are installed as dev-dependencies. That will cause them to be donwloaded either as source or as dist. But often they require other packages that then need to be in line with all the other dependencies. 

Wouldn't it be an option to add a ```--prefer-phar```-flag when requiring a dev-dependency so that instead of the sources a PHAR file would be installed? 

The phar -file could be referenced in a new section in the ```composer.json``` or be pulled from the Github-API (for github-based projects only)

The benefit would be to have one place to define my dependencies - along with specific versions. And development-tools are not interfering with my projects source-dependencies.

That - of course - would require the vendors of such tools to add a new section in their composer.json to reference the phar-files but I'm sure when that's possible they would happily do so.

**Comment by stof** [comment] 2017-03-10 12:17
the big drawback of installing PHPUnit as a phar is that it could have dependencies in common with your own project. In such case, running PHPunit will run tests using the PHPUnit version of these deps rather than  the project version, meaning that your tested code will not be the code running in your app for real.

If development tools are never running in the same process that your own code (hint: this excludes all test framework), using a phar is a valid solution to run them. But I would not use composer at all for such cases.
Thus, we would then have to do a very special handling in the solver, because the package definition would have to be different when using the phar or when using the dist/source, as the phar does not have the same dependencies (as many things are embedded in the phar). so this is not a different installation way. This is actually a different package.

**Comment by heiglandreas** [comment] 2017-03-10 12:53
Development-Tools should never depend on run in the same process than your own code. That's why you would include dev-tools like PHPUnit in the ```dev```-section. It's not a requirement of the app but only for development-purposes.

The special handling in the solver is already done, as dev-tools of dependencies are not resolved at all. So I imagine that adding all dependencies to those skipped dependencies when encountering a PHAR-installable requirement should be possible. Though I admit that I have no idea on how complex it might be in the end as I haven't had a look at the code.

From a users POV it's not a different package but a different installation. I want Tool xyz in version a.b.c and I'd like to prefer phars like I'd prefer sources or dists.

Having it all in one place would also allow handling unavailable phars for certain tags. f.e. requiring tool x in version a resolves to a phar while version b might not resolve to a phar and could threfore be installed in the default way using source or dist…

**Comment by shochdoerfer** [comment] 2017-03-10 12:57
For more context: [require-dev gone wrong!](https://blog.bitexpert.de/blog/require-dev-gone-wrong/)

**Comment by naderman** [comment] 2017-03-11 16:10
The key to make any of this viable is really to use something like https://github.com/webmozart/php-scoper to prevent conflicts between the tools and project dependencies. At that point we could even get this working without phar files, although I assume they may be easier option. Although phar files make it a tiny bit harder to debug issues if the problem is actually with the tool itself, which is probably not very common.

**Comment by Seldaek** [comment] 2017-03-17 21:33
Closing as I don't see this happening in the near future.. If the landscape changes (php-scoper or otherwise) we can always revisit.

**Closed by Seldaek** 2017-03-17 21:33 UTC
Labels: Question
