### ISSUE TITLE
Fallback for non existing path repository?

### ISSUE THREAD

**Issue by OvalMedia** [composer/composer#12191] opened 2024-11-09 13:22 UTC
In my local dev setup I am using a local path repository. It houses several projects each having their own repository set to github (and published via packagist). They are symlinked to my vendor folder and this works fine.

When I deploy this setup to the remote production server the local-src folder is omitted, it is not present on the prod server. The idea is that remotely composer should fall back to the public github repository.

I am using composer 2.7.7 which I cannot update (managed server).

When I run `composer install` on the remote machine without a composer.lock file present composer fails with this error message:
`The `url` supplied for the path (./local-src/*) repository does not exist`

How can I tell composer to fall back to github/packagist in those cases? The only way I get this to work is to remove the local-src repository from the composer.json on the remote machine. But this is not really what I want since composer.json is part of the main project's version control.

Thank you

My `composer.json`:

```json
{
    "name": "Magento",
    "description": "",
    "type": "project",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "require": {
        [...]
    },
    "require-dev": {
        [...]
    },
    "autoload": {
        "psr-4": {
            [...]
        },
        "psr-0": {
            "": [
                "app/code/",
                "generated/code/"
            ]
        },
        "files": [
            "app/etc/NonComposerComponentRegistration.php"
        ],
        "exclude-from-classmap": [
            "**/dev/**",
            "**/update/**",
            "**/Test/**"
        ]
    },
    "version": "1.0",
    "minimum-stability": "stable",
    "repositories": {
        "local-src": {
            "type": "path",
            "url": "local-src/*",
            "options": {
                "symlink": true
            }
        },
        "0": {
            "type": "composer",
            "url": "https://repo.magento.com/"
        }
    }
}

```

**Comment by Seldaek** [comment] 2024-11-13 12:35
This is kinda duplicate of #12175  - but as highlighted in https://github.com/composer/composer/pull/12186#issuecomment-2460206889 this will probably fail for the exact case you describe. You'd effectively need to re-run an update on prod to get package info from packagist.org and not rely on the local-src ones. I think that's fairly unlikely we will fix this due to various problems.. But I'd encourage you to try https://github.com/franzliedke/studio to replace your path repos for local development.

**Closed by Seldaek** 2024-11-13 12:35 UTC

**Comment by OvalMedia** [comment] 2024-11-25 08:23
Thank you, [Studio](https://github.com/franzliedke/studio) is exactly what I was lookin for.
