### ISSUE TITLE
Composer 2 removes psr/* virtual packages

### ISSUE THREAD

**Issue by TomasVotruba** [composer/composer#9382] opened 2020-10-30 10:30 UTC
This leads to missing interface issues:

![image](https://user-images.githubusercontent.com/924196/97694626-2a80af00-1aa3-11eb-9d40-6800f05395e5.png)

## Simples Example Reproduce

```bash
composer require symfony/service-contracts
composer self-update --2
composer update
```

Using `ServiceProviderInterface` interface from the  `symfony/service-contracts` will lead to:

```bash
PHP Fatal error:  Uncaught Error: Interface 'Psr\Container\ContainerInterface' not found in /var/www/migrify/vendor/symfony/service-contracts/ServiceProviderInterface.php:22
```

## Full Result

![image](https://user-images.githubusercontent.com/924196/97694594-1d63c000-1aa3-11eb-9596-cf9306f4920f.png)

## Working Result with Composer v1

![image](https://user-images.githubusercontent.com/924196/97694877-7fbcc080-1aa3-11eb-8799-5968c7a2b04c.png)

**Comment by TomasVotruba** [comment] 2020-10-30 10:33
Let me know if you need more details.

**Comment by Seldaek** [comment] 2020-10-30 10:51
I can't reproduce this. I get:

  - Installing psr/container (1.0.0): Extracting archive
  - Installing symfony/service-contracts (v2.2.0): Extracting archive

and with v1 the same..

**Comment by stof** [comment] 2020-10-30 11:34
I'm quite sure that this is the same issue than https://github.com/composer/composer/issues/9316 and https://github.com/composer/composer/issues/9308 which are caused by broken provide rules in some packages.
So check the packages you use to see if one of them has such broken provide rules.

I made a lot of PRs in the ecosystem to fix such mistakes for `psr/*` containers (see the PRs referencing these issues for the ones done on GitHub. the ones done on Gitlab don't appear but there are some too). But not all of them are merged yet, and you might be using older versions of the packages for which a fix was merged.

@TomasVotruba your reproducing steps say to run `composer require symfony/service-contracts`. but are you running that in an empty project, or do you have an existing `composer.json` with lots of other packages ? Your reproducing steps are not complete IMO.

**Comment by stof** [comment] 2020-10-30 11:36
Also, https://gist.github.com/Seldaek/73dfe36bf518eee834cae9bb1810c267 contains a list of package versions identified as being invalid regarding that issue if you want to help fixing other cases.

**Comment by TomasVotruba** [comment] 2020-10-30 11:57
@Seldaek I've narrowed it way too down, I'm sorry.

- This is failing Github Action job: https://github.com/migrify/migrify/pull/203
- This is exact steps to reproduce: https://github.com/migrify/migrify/pull/203/files#diff-99b312f3fa09ea689d0916ca53eb171813cf2813ce7ac51c909e1dd5bf7d489c

@stof It might be the case, thanks for sharing, I'll look into it.

**Comment by TomasVotruba** [comment] 2020-10-30 11:58
@stof It looks like each of those 3rd party packages needs to be fixed.

Is there any hack I can add to my `composer.json`, so it works without waiting for all 3rd party packages to be fixed and tagged?

**Comment by Seldaek** [comment] 2020-10-30 12:15
There is no workaround for this. Broken packages have to be fixed.

**Comment by stof** [comment] 2020-10-30 12:27
@TomasVotruba in your case, the culprit is `phalcon/cphalcon`, which says it provides the psr interfaces because it actually relies on ext-psr to provide it from a C extension. But if you require that package without actually enabling the extension, things indeed don't work fine.

**Comment by TomasVotruba** [comment] 2020-10-30 12:31
@stof Wow, how did you find that out?
I removed the phalcon (it was actually forgotten from old package removal) and it works: [`9292813` (#203)](https://github.com/migrify/migrify/pull/203/commits/9292813e9a15d2f7234fb1c039c220fc03ca6384)
:+1: 

Thank you

**Closed** 2020-10-30 12:35 UTC
Labels: Support

**Comment by stof** [comment] 2020-10-30 13:01
> Wow, how did you find that out?

As part of my cleanup work last week, I reviewed all providers of `psr/*` interface packages registered on Packagist. I identified `phalcon/cphalcon` as a legitimate one (the only one IIRC). And I saw it appearing in your `composer install` output.

**Comment by Seldaek** [comment] 2020-10-30 13:04
Still seems incorrect to me that they expect the ext-psr to be there but don't enforce it. Ideally phalcon/cphalcon would require ext-psr to make sure that the provides are gonna be met.

**Comment by stof** [comment] 2020-10-30 13:05
> Still seems incorrect to me that they expect the ext-psr to be there but don't enforce it. Ideally phalcon/cphalcon would require ext-psr to make sure that the provides are gonna be met.

indeed
