### ISSUE TITLE
composer error when trying to create project in Homestead/code

### ISSUE THREAD

**Issue by knot22** [composer/composer#8294] opened 2019-08-27 19:30 UTC
When I run this command in a VM from the homestead/code directory:

```
composer create-project --prefer-dist laravel/laravel Laravel -vvv
```

I get the following output:
![ErrorException](https://user-images.githubusercontent.com/20587751/63801754-a2b77780-c8d6-11e9-9677-a7523a56f778.png)

And I expected a new project to be created but it wasn't.

Prior to trying to create this project in the homestead/code directory, I had mistakenly created it in the homestead directory.  To remove it, I ran this command from the homestead directory:
```
rm -rf ~/Laravel
```
That caused the Laravel directory within homestead to be removed; however, maybe it didn't clean everything up...?

What would cause this error to occur and how can it be corrected to allow a new project to be installed in homestead/code?

**Comment by alcohol** [comment] 2019-08-28 06:27
The error originates from https://github.com/composer/composer/blob/bfba228b5a232bcb9e4bb7941f0a0aaa37bab117/src/Composer/Installer/ProjectInstaller.php#L67-L69

It would seem to indicate that the "target directory" given to the create-project command already exists in one way or another, but not as a directory. Could it be you have some sort of symbolic link, file or otherwise named `Laravel` in the directory where you attempted to run the create-project command?

**Comment by alcohol** [comment] 2019-08-28 06:29
FYI: the next time you provide us with the output of a command, it would help us very much if you include the working directory (fully qualified path of the directory you are currently in) and literal command you ran. It especially helps us when debugging filesystem issues :-)

**Comment by knot22** [comment] 2019-08-28 23:20
Thanks for the reply.  There was probably something left over from creating it in the wrong directory initially.  However, I didn't see a ```Laravel``` folder in there by running the ```ls``` command.  I'm not sure how, but this problem did self-resolve.  I tried a few different things to fix it but didn't keep good track of the sequence so don't know which thing actually repaired the problem.

Noted the pointer about including the working directory for future posts.

**Comment by alcohol** [comment] 2019-08-29 06:05
Closing the issue then as it seems resolved and unable to reproduce at the moment :-)

**Closed by alcohol** 2019-08-29 06:05 UTC
Labels: Support
