### ISSUE TITLE
Use static package versions

### ISSUE THREAD

**Issue by paladox** [composer/composer#4861] opened 2016-02-01 17:44 UTC
Please use static package version so something like ~ since some packages are upgraded and if they update for example from 2.x to 3.x then that indicates a breaking change.

**Comment by stof** [comment] 2016-02-01 18:52
I don't understand what you mean

**Comment by paladox** [comment] 2016-02-01 18:59
Well if we were to do something like 

        "php": "^5.3.2 || ^7.0",
        "justinrainbow/json-schema": "^1.6",
        "composer/spdx-licenses": "^1.0",
        "composer/semver": "~1.0",
        "seld/jsonlint": "~1.4",
        "symfony/console": "~2.8.2",
        "symfony/finder": "~2.8.2",
        "symfony/process": "~2.8.2",
        "symfony/filesystem": "~2.8.2",
        "seld/phar-utils": "~1.0",
        "seld/cli-prompt": "~1.0"

instead of 

        "php": "^5.3.2 || ^7.0",
        "justinrainbow/json-schema": "^1.6",
        "composer/spdx-licenses": "^1.0",
        "composer/semver": "^1.0",
        "seld/jsonlint": "^1.4",
        "symfony/console": "^2.5 || ^3.0",
        "symfony/finder": "^2.2 || ^3.0",
        "symfony/process": "^2.1 || ^3.0",
        "symfony/filesystem": "^2.5 || ^3.0",
        "seld/phar-utils": "^1.0",
        "seld/cli-prompt": "^1.0"

since even though you added both version composer wont actually be supporting the latest unless you install the latest from master branch meaning any one download using php 5.5 will download a version that supports it but wont actually  be supported in composer.

**Comment by stof** [comment] 2016-02-01 19:12
I still don't understand what is the issue you have.

**Comment by curry684** [comment] 2016-02-02 11:44
@paladox did you ever [read up on the Semantic Versioning system](http://semver.org/) Composer adheres to?

**Comment by 7ochem** [comment] 2016-02-05 13:04
See also this issue https://github.com/composer/composer/issues/4882

Using version constraints that are too broad (`^1.0` means >= 1.0.0 and < 2.0.0) makes that there's no version of your project you can return to to prevent compatibility problems caused by dependencies. This means that if one day some deep dependency down the chain would impulsively add some constraint or library dependency, then you will be forced to update your system all of a sudden (or fork the repo and apply a hard dependency on older versions yourself).

Keeping a bit more strict dependencies would reduce the chance of this to happen.

**Comment by Seldaek** [comment] 2016-02-06 00:49
We allow 2.x and 3.x for symfony packages because our usage is compatible with both AFAIK, and that way people relying on symfony v3 packages can also require composer if they wish to do so (not many people, but still I think we should allow the use case). In composer itself (i.e. our phar files) we won't upgrade to 3.x though because of the platform config that says php 5.3 is in use for composer. Closing this as I don't see what we can do, but if we have indeed some cases where our code doesn't work with symfony 3 packages then let us know and we can surely work on fixing that.

**Closed by Seldaek** 2016-02-06 00:49 UTC
