### ISSUE TITLE
Enhancement proposal: repositories section in composer.json: multiple entries for the same package act as fallback

### ISSUE THREAD

**Issue by shadiakiki1986** [composer/composer#6067] opened 2017-01-13 18:17 UTC
Hello. I just faced a desirable enhancement that I thought I'd propose here.
My composer.json `repositories` section has references to private repositories on bitbucket.
The same repositories are also available on my local path during development.
In production, they're not.
If my `repositories` section looked like this:

```
{
  "repositories": [
      "url": "../private-repo",
      "type": "path"
    }, {
    {
      "url": "https://shadiakiki1986@bitbucket.org/shadiakiki1986/private-repo",
      "type": "git"
    },
}
```
composer would successfully symlink to the local path in development,
but it would fail in production as `../private-repo` does not exist.
It would be nice if upon failure, it could check the next `git` repository and fallback to using it.

What do you think?

**Comment by stof** [comment] 2017-01-13 18:20
the issue is that the production will generally install dependencies locked locally, which would not allow it to fallback to anything.
Your proposal requires resolving dependencies again. and running ``composer update`` in production is highly unsafe (as it means deploying code you never ran)

**Comment by shadiakiki1986** [comment] 2017-01-14 09:24
Ok thank you for your thoughts. I figure it would make a cleaner solution to have two composer.json files, one called `composer.json` and another `composer.override.json` and then just use the `COMPOSER` env var (documented [here](https://getcomposer.org/doc/03-cli.md#composer)) in production to use the `composer.override.json` file in which I would replace the `path` repository with the `git` repository.

This brings me to another idea. Perhaps if the `composer.json` was `extensible` (like [docker-compose.yml](https://docs.docker.com/compose/extends/#/example-use-case)), then my two files wouldn't have much redundancy? I would then just need to include a `repositories` entry instead of the full file

**Comment by Seldaek** [comment] 2017-01-22 18:25
You can use https://github.com/wikimedia/composer-merge-plugin for this

**Closed by Seldaek** 2017-01-22 18:25 UTC

**Comment by shadiakiki1986** [comment] 2017-01-23 07:06
Thank you!
