### ISSUE TITLE
could not find package xxx

### ISSUE THREAD

**Issue by staabm** [composer/composer#7054] opened 2018-01-29 13:43 UTC
https://packagist.org/packages/njoannidi/php-lint-bash

`composer require njoannidi/php-lint-bash`  in a empty folder..
![grafik](https://user-images.githubusercontent.com/120441/35513234-aa7c295a-0502-11e8-95ac-c5e458ee3139.png)

the package which could not be found and the one suggested by composer is the same... ?

```
$ composer --version
Composer version 1.6.2 2018-01-05 15:28:41

$ php --version
PHP 5.4.45-4+deprecated+dontuse+deb.sury.org~precise+1 (cli) (built: Jun 24 2016 08:30:18)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with blackfire v1.17.3~linux-x64-non_zts54, https://blackfire.io, by SensioLabs
```

**Comment by xabbuh** [comment] 2018-01-29 13:47
As far as I have experienced this yet, that's happening when there is no stable release of the required package and the minimum stability settings do not allow the installation.

**Comment by Seldaek** [comment] 2018-01-31 14:26
Duplicate of #7044

**Closed by Seldaek** 2018-01-31 14:26 UTC
