### ISSUE TITLE
Missing key signing of composer

### ISSUE THREAD

**Issue by greencopper** [composer/composer#4739] opened 2015-12-28 15:49 UTC
Hi

Everytime I find some project that has made its installation dependent upon composer I get very frustrated because STILL composer doesn't get ANY kind of key signing.

It is impossible to verify the one-line installer actually is the original and untampered composer.

How hard can it be to key sign composer and get the keys distributed correctly so it's possible to confirm authentication of the program?

Yes, it's possible to download the source code and compile that, but then I would still have to go every single line of code in order to try to verify that the source is clean too.

Since composer is responsible for installation thousand of PHP packages via source WE REALLY FREAKING NEED KEY SIGNING!

If composer is ever compromised think of all the havoc it could cause in changing source code of thousand of files downloaded using composer.

Please get this problem solved once and for all.. Composer is a disaster waiting to happen! Haven't you guys learned anything from the past?!

**Comment by alcohol** [comment] 2015-12-28 17:27
Duplicate of #1074, #4022

**Closed by alcohol** 2015-12-28 17:27 UTC
