### ISSUE TITLE
path repository type does not interpret correctly "./" prefix or even no prefix

### ISSUE THREAD

**Issue by StephaneMangin** [composer/composer#6057] opened 2017-01-10 15:16 UTC
My client project `composer.json`:

```json
...
"repositories" : [
        {
            "type": "git",
            "url":  "../ork-hugeshop-templates"
        }
],
"require" : {
        "module/theme-huge": "*"
},
...
"minimum-stability" : "dev",
"prefer-stable" : true,
```
This project requires the dependency below.

My dependency root `composer.json`:

```json

{
    "name": "module/theme-huge",
    "description": "N/A",
    "require": {
        "magento/theme-frontend-blank": "100.1.*",
        "module/theme-huge-core": "dev-master"
    },
    "type": "magento2-theme",
    "version": "0.0.1",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "autoload": {
		"psr-4" : {
			"Huge\\" : "app/design/Module/Theme_Huge/"
		},
        "files": [
            "registration.php"
        ]
    },
    "repositories": [
        {
            "type": "path",
            "url": "./Core", // or just "Core"
            "options": {
                "symlink": false
            }
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true
}


```
Which requires the internal dependency below.

My internal dependency `composer.json`:

```json
{
    "name": "module/theme-huge-core",
    "description": "N/A",
    "require": {
        "php": "~5.6.5|7.0.2|7.0.4|~7.0.6"
    },
    "version": "0.0.1",
    "license": [
        "OSL-3.0",
        "AFL-3.0"
    ],
    "autoload": {
		"psr-4" : {
			"HugeCore\\" : "app/code/Module/HugeCore/"
		},
        "files": [
            "registration.php"
        ]
    }
}

```
Output of `composer diagnose`:

```
The version field is present, it is recommended to leave it out if the package is published on Packagist.
Defining autoload.psr-0 with an empty namespace prefix is a bad idea for performance
require.magento/product-community-edition : exact version constraints (2.1.2) should be avoided if the package follows semantic versioning
require.composer/composer : unbound version constraints (@alpha) should be avoided
require.imaginaerum/magento2-language-fr-fr : unbound version constraints (*) should be avoided
require.module/theme-huge : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

```

When I run this command:

```
Composer update
```

I get the following output:

```Loading composer repositories with package information
Updating dependencies (including require-dev)         
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for module/theme-huge dev-master -> satisfiable by module/theme-huge[dev-master].
    - module/theme-huge dev-master requires module/theme-huge-core * -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

And I expected this to happen:

Takes count of the "./" relative path to include a local dependency contained in the root path of the composer package. As "../" does when outside of the root. My repo is monolitic and includes its own dependency as follow (magento theme) : 

.
├── composer.json // the root of the dependency repo
├── src/
└── Core // the internal dependency which should be pointed with the "./Core" in the root composer.json
    ├── composer.json
    └── src/

Dependency graph:

```
                                       module/theme-huge
+-------------------+                  +----------------------------+
|                   |                  |                            |
|  Client project   |  depends         |                            |
|                   +------------------>                            |
|  /composer.json   |                  |    /composer.json          |
|                   |                  |                            |
+-------------------+                  |                            |
                                       |   module/theme-huge-core   |
                                       |   +----------------------+ |
                                       |   |                      | |
                                       |   | internal dependency  | |
                                       |   | referenced by ./Core | |
                                       |   | /composer.json       | |
                                       |   |                      | |
                                       |   +----------------------+ |
                                       +----------------------------+

```

Minimum codeless repo created to show or eventually reproduce the issue : https://github.com/StephaneMangin/Composer-Path-Issue
Thanks to comment on missings things if any

**Comment by alcohol** [comment] 2017-01-10 15:17
I am confused. You have 2x "require" in your composer.json. Please fix this first.

**Comment by alcohol** [comment] 2017-01-10 15:22
Also the problem is probably pretty straight forward. One of your dependencies depends on another dependency (dev-master constraint), but this is not allowed since the root composer defaults to stable. So you either have to explicitly add this sub-dependency to your root composer or you have to lower the minimum-stability setting.

**Comment by StephaneMangin** [comment] 2017-01-10 15:23
The problem occurs evene with the fixed version of my package's composer.json

**Comment by alcohol** [comment] 2017-01-10 15:23
Yes and I already explained the problem.

**Comment by StephaneMangin** [comment] 2017-01-10 15:24
Thanks alcohol (you're pretty reactive ;) ) Please let me some time to check between ;)

**Comment by StephaneMangin** [comment] 2017-01-10 15:33
What do you mean by "have to explicitly add this sub-dependency to your root composer". Is it not already the case with the local repository definition ?!

Should i have to indicate it in my non package composer.json ?

**Comment by stof** [comment] 2017-01-10 15:35
no, the repository definition does not whitelist dev stability

**Comment by StephaneMangin** [comment] 2017-01-10 15:42
Thanks stof, you mean that dev is no usable while using local repositories definition, could you please explain enough to well understand. I'm a bit confusing because of my misunderstanding of the internal behavior of composer.

I've just read about recursive repository loading... It sounds like my problem is quite near from this behavioral limit...

**Comment by stof** [comment] 2017-01-10 15:46
no, it means you have 2 things to do:

- telling composer where to find the package definitions
- telling composer that dev versions are acceptable when selecting a package

These are 2 independent things (you might want to specify custom package repository without whitelisting dev versions of everything in it, for instance when using WPPackagist or the drupal repository)

**Comment by stof** [comment] 2017-01-10 15:48
when you have your own internal packages, what you could use is a combination of ``minimum-stability: dev`` and ``prefer-stable: true``, to tell composer that dev versions are allowed for any packages, but only when it does not have a stable version being usable.

**Comment by StephaneMangin** [comment] 2017-01-10 16:02
@stof Thanks a lot.

I've just updated my issue with your comments.

Ok, I see what you mean. But it's not the case right now ? I tell composer where is my sub package by using path type.Then I flag stability to dev and stable preference to true => The same problem remains.

**Comment by stof** [comment] 2017-01-10 16:05
Well, your issue is that it does not find ``module/theme-huge-core``. Where is this package defined ?

**Comment by StephaneMangin** [comment] 2017-01-10 16:06
inside the root in the Core folder

**Comment by alcohol** [comment] 2017-01-11 07:37
* Sorry miss-clicked.

The more I look at your issue, the less it makes sense. I now see 3 composer.json definitions. The first is unclear to me which it belongs to and where it is located. It seems to require your "root" composer.json project. The second references a `huge-core` which I cannot find anywhere. The third json does not seem to appear in your directory tree structure that you presented.

Can you please clean up this incredible mess and present us with a reproducible scenario? Create a new public repository on Github and put the relevant files in there.

**Comment by StephaneMangin** [comment] 2017-01-11 10:08
I've updated the issue.

**Comment by StephaneMangin** [comment] 2017-01-11 10:14
Hi alcohol,

Yes it's a bit difficult to explain this issue. Since my code is not open-sourced, i can't put the code in a public repo.

To be a little bit more precise, here it goes : 

Project : I have a magento project which need to add a theme dependency (the first composer.json)
Theme repo: The dependency  (the second composer.json) includes a local (internal to the repo) dependency which is the core functions of the theme (the last composer.json)

I've updated the issue.

**Comment by alcohol** [comment] 2017-01-11 10:30
> Yes it's a bit difficult to explain this issue. Since my code is not open-sourced, i can't put the code in a public repo.

You don't have to put the actual code in the repository. Just the project structure with composer.json files. The code can just be some dummy classes. We don't care about the code.

**Comment by StephaneMangin** [comment] 2017-01-11 10:38
I've updated the issue with the link to the test repo.

**Comment by sbuzonas** [comment] 2017-01-12 07:49
I believe it's because of the version setting in the composer.json, which tells composer not to guess the version, preventing dev-master from being an available version.

You have two options that will work with the repo you have linked:
* Update the dependency in your root package to use `"module/theme-huge-core": "self.version"` if the version will always be the same, or `"module/theme-huge-core": "0.0.1"` if they will be versioned independently.
* Remove the version configuration from the child package and let composer handle it.

**Comment by sbuzonas** [comment] 2017-01-12 07:54
If `module/theme-huge` is a dependency to another package, the child will not be found automatically.  Repositories are only valid in the root package.  See [`FAQ: Why can't Composer load repositories recursively?`](https://getcomposer.org/doc/faqs/why-can%27t-composer-load-repositories-recursively.md)

**Comment by Seldaek** [comment] 2017-12-19 10:27
Auto-closing this as it's marked as support request and has not received any update in a long time.

**Closed by Seldaek** 2017-12-19 10:27 UTC
Labels: Support
