### ISSUE TITLE
Segmentation fault PHP 5.6.6 - Windows - Composer 1.3.1

### ISSUE THREAD

**Issue by DeyV** [composer/composer#6052] opened 2017-01-09 15:09 UTC
When I run this command:
```
composer -V
```

I get the following output:

```
composer: line 1: 19268 Segmentation fault      $0.phar $*
```
 
Last working composer version 

```
$ composer -V
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug

Composer version 1.2.4 2016-12-06 22:00:51

```

```
$ php -v
PHP 5.6.6 (cli) (built: Feb 18 2015 16:02:19)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.1, Copyright (c) 2002-2015, by Derick Rethans
```

```
ver

Microsoft Windows [Version 10.0.14393]

x 64
```

**Comment by Seldaek** [comment] 2017-01-09 16:56
Can you try if you run `COMPOSER_ALLOW_XDEBUG=1 composer -V` with 1.3.1? That should skip the xdebug-disabling code, which I suspect is the part triggering the segfault.

**Comment by DeyV** [comment] 2017-01-09 17:19
yes, it helped

**Comment by Seldaek** [comment] 2017-01-09 17:26
OK so that means restarting to get rid of xdebug somehow causes the segfault for you.. looping in @johnstevenson who might have more ideas how to debug this.

I guess one thing would be to check what the ini file we generate looks like, and see if starting php with it causes issues, or if it segfaults only when running via `passthru()`.

**Comment by staabm** [comment] 2017-01-09 17:42
@DeyV is updating to a more recent php 5.6.* a option for you?

**Comment by DeyV** [comment] 2017-01-09 17:43
I can check with actual php 5.6 version if You need

**Comment by DeyV** [comment] 2017-01-09 17:58
```
$ php -v
PHP 5.6.29 (cli) (built: Dec  8 2016 12:21:49)
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans
```

```
$  composer -V
/c/php/bat/composer: line 1: 21240 Segmentation fault      $0.phar $*
```

**Comment by staabm** [comment] 2017-01-09 18:39
Could you extract a proper backtrace for the segfault?

**Comment by johnstevenson** [comment] 2017-01-09 19:00
Curious. I cannot reproduce this using the following config:

- Windows 10.0.14393 (x64)
- Php 5.6.29
- Opcache v7.0.6-dev
 - XDebug v2.5.0

 I'm using a 32-bit thread-safe php build.

**Comment by DeyV** [comment] 2017-01-09 19:02
How can I do this?


W dniu pon., 9.01.2017 o 19:40 Markus Staab <notifications@github.com>
napisał(a):

**Comment by staabm** [comment] 2017-01-09 19:23
See http://stackoverflow.com/questions/13079513/how-do-i-diagnose-this-php-segmentation-fault

**Comment by johnstevenson** [comment] 2017-01-09 19:37
Try this composer.phar: https://s3-eu-west-1.amazonaws.com/johnstevenson/composer/composer.phar

It reports the command line used when restarting and does not delete the temporary ini file.

`php path/to/this/composer.phar -V`

**Comment by DeyV** [comment] 2017-01-09 21:02
```
$ composer -V
Restarting without xdebug: C:\php\php\php.exe -c C:\Users\Dawid\AppData\Local\Temp\28D8.tmp C:/php/bat/composer.phar -V
/c/php/bat/composer: line 1: 22836 Segmentation fault      $0.phar $*
```
[28D8.tmp.txt](https://github.com/composer/composer/files/694641/28D8.tmp.txt)

**Comment by DeyV** [comment] 2017-01-09 21:08
Trace on "master" 

```
 php -d xdebug.auto_trace=ON -d xdebug.trace_output_dir=./trace/ bin/composer -V
```
[timestamp.xt.txt](https://github.com/composer/composer/files/694656/timestamp.xt.txt)

**Comment by staabm** [comment] 2017-01-09 21:13
@DeyV would you mind open a bug on http://bugs.php.net with this stacktrace and a repro so the segfault can be fixed in php-src?

**Comment by johnstevenson** [comment] 2017-01-09 23:00
I can replicate this issue now, using the temp ini file supplied, but only if I re-enable xdebug! The problem is something to do with xdebug and opcache being run together in the same (parent) process.

This is the essential bit from the temp php ini created by Composer's XdebugHandler:

```
; OPCACHE

zend_extension=php_opcache.dll 

opcache.memory_consumption=128
opcache.interned_strings_buffer=8
opcache.max_accelerated_files=4000
opcache.revalidate_freq=1
opcache.fast_shutdown=1
opcache.enable_cli=1

; XDEBUG
;zend_extension = php_xdebug.dll 
```
This segfaults when Composer restarts PHP (via `passthru`), with the temp ini passed in the `-c` option.
However, running running Composer in a standalone process with this ini does not. For example:

```
php -c temp.ini composer.phar -V
```

Either disabling the opcache extension entirely, or just disabling `opcache.enable_cli` fixes the issue when the process is restarted. @DeyV Could you please confirm this.

I have only tested on Windows so far.

**Comment by DeyV** [comment] 2017-01-10 08:29
correct. 

```
; opcache.enable_cli=1
```
in original php.ini is inaf

```
C:\php\bat>composer -V
Composer version 1.3.1 2017-01-07 18:08:51
```

**Comment by alcohol** [comment] 2017-01-10 09:35
I always disable opcache for cli, since it never has given me anything but trouble. Still good to report this as a possible bug in the php bug tracker though.

**Comment by staabm** [comment] 2017-01-10 09:53
> I always disable opcache for cli, since it has never given me anything but trouble. Still good to report this as a possible bug in the php bug tracker though.

starting from php 7.1 the cli opache with file-cache enabled seems to boost composer considerably. I will have a look into this in a separate issue when time allows.

**Comment by vlakoff** [comment] 2017-01-15 10:54
Refs the subsequent PR, #6060

**Closed** 2017-01-27 17:02 UTC
Labels: Support
