### ISSUE TITLE
JSON in --repository option no longer works

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#10490] opened 2022-01-28 09:34 UTC
The command

````
composer create-project joachim-n/drupal-core-development-project NEW_PROJECT_DIRECTORY --stability=dev --repository='{"url": "/path/to/git/clone/of/project/template/", "type": "vcs"}'
````

produces this error:

>   [Symfony\Component\Console\Exception\RuntimeException]
>  Too many arguments, expected arguments "command" "package" "directory" "version".

It definitely used to work, because I documented it in the README at https://github.com/joachim-n/drupal-core-development-project

**Comment by stof** [comment] 2022-01-28 09:46
I cannot reproduce this myself. So please provide the *exact* command you are running (and the OS and terminal you use to be complete)

**Comment by stof** [comment] 2022-01-28 09:59
Small note: if you are on windows, the cmd.exe shell does not support `'` as a quoting character, only `"`. So in such case, the quoting of your `--repository` value would not work (and yes, it will be a lot more painful as the JSON value also contains `"`)

**Comment by joachim-n** [comment] 2022-01-28 11:24
That is the exact command. I've just copy-pasted from the issue and tried it in my terminal, which is on MacOS.

I've tried escaping the " in the JSON as well:

```
composer create-project joachim-n/drupal-core-development-project test-dcdp --stability=dev --repository='{\"path\": \"/Users/joachim/Sites/drupal-core-composer\", \"type\": \"vcs\"}'
```

produces the same error.

**Comment by joachim-n** [comment] 2022-01-28 11:33
The problem seems to be the spaces in the quoted JSON.

This works:

```
composer create-project joachim-n/drupal-core-development-project NEW_PROJECT_DIRECTORY --stability=dev --repository='{"url":"/path/to/git/clone/of/project/template/","type":"vcs"}'
```

**Comment by stof** [comment] 2022-01-28 11:49
then check whether the shell you are using allows to use `--repository='...'` as a way to quote the options.

Testing script:

```php
<?php
var_dump($argv);
```

Then call `php test_script.php --repository='{\"path\": \"/Users/joachim/Sites/drupal-core-composer\", \"type\": \"vcs\"}'` and see what you have in the output (if the shell quoting worked, `$argv` should have 2 values, the first one being `test_script.php`)

**Comment by joachim-n** [comment] 2022-01-28 13:14
With escaping the "

```
php test_script.php --repository='{\"path\": \"/Users/joachim/Sites/drupal-core-composer\", \"type\": \"vcs\"}'

array(2) {
  [0] =>
  string(15) "test_script.php"
  [1] =>
  string(89) "--repository={\"path\": \"/Users/joachim/Sites/drupal-core-composer\", \"type\": \"vcs\"}"
}
```

Without escaping the "

```
php test_script.php --repository='{"path": "/Users/joachim/Sites/drupal-core-composer", "type": "vcs"}'

array(2) {
  [0] =>
  string(15) "test_script.php"
  [1] =>
  string(81) "--repository={"path": "/Users/joachim/Sites/drupal-core-composer", "type": "vcs"}"
}
```

Looks like the shell is ok.

**Comment by stof** [comment] 2022-01-28 14:31
is `composer` the actual composer in your case ? Or is it a different script that then delegates to the composer phar separately ? In the second case, it might be an escaping bug in that script.

**Comment by joachim-n** [comment] 2022-01-28 14:34
Yes, possibly:

```
~/Sites/drupal-core-composer joachim$ which composer
/usr/local/bin/composer
~/Sites/drupal-core-composer joachim$ more /usr/local/bin/composer
#!/usr/bin/env bash

/usr/bin/env php -d allow_url_fopen=On -d detect_unicode=Off /usr/local/Cellar/composer/1.0.0-alpha8/libexec/composer.phar $*
```

**Comment by stof** [comment] 2022-01-28 14:37
then try the same kind of test than above, but by having the same kind of wrapper script for the testing_script.php

**Comment by stof** [comment] 2022-01-28 14:40
based on the accepted answer in https://stackoverflow.com/questions/1537673/how-do-i-forward-parameters-to-other-command-in-bash-script and https://stackoverflow.com/questions/4824590/propagate-all-arguments-in-a-bash-shell-script/4824637#4824637, I think you need quotes around the `$*` in your proxy script

**Comment by dzuelke** [comment] 2022-01-28 15:33
Yes; `"$@"` is correct for forwarding arguments and preserving quoting. `$@` or `$*` breaks things.

But your `/usr/local/bin/composer` is very outdated; Homebrew no longer installs a wrapper script, but moves the actual PHAR to the bin location, and has done so for... years.

**Comment by joachim-n** [comment] 2022-01-28 16:06
I've been doing `composer self-update` when it tells me. I didn't know I had to also update it with homebrew!

**Comment by Seldaek** [comment] 2022-02-03 15:20
Closing as I am assuming @joachim-n got this figured out now

**Closed by Seldaek** 2022-02-03 15:20 UTC
Labels: Support
