### ISSUE TITLE
Missing newline during "composer update" when repositories are present?

### ISSUE THREAD

**Issue by arrgson** [composer/composer#6520] opened 2017-07-01 06:53 UTC
If I remove the repository configuration I get expected output (nicely formatted), but with it included there seems to be a missing (?) newline.

![screen shot 2017-07-01 at 08 40 54](https://user-images.githubusercontent.com/15320948/27759836-4ff834de-5e3a-11e7-9aee-16b7b38aaa88.png)

My `composer.json`:

```json
{
  "name": "...",
  "description": "...",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "config": {
    "sort-packages": true
  },
  "require": {
    "roave/security-advisories": "dev-master"
  }, 
  "require-dev": {
    "...": "^1.0"
  },
  "repositories": [
    {
      "type": "git",
      "url": "git@gitlab.com:..."
    }
  ]
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
The version field is present, it is recommended to leave it out if the package is published on Packagist.
require.roave/security-advisories : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update
```

I get the following output:

```
ag-work-laptop:resourcespace andreas$ composer update
Loading composer repositories with package information                                                                                   Updating dependencies (including require-dev)         
Nothing to install or update
Generating autoload files
```

And I expected this to happen:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

**Comment by alcohol** [comment] 2017-07-04 07:59
Quirky, can you submit a small PR to fix this?

**Comment by Seldaek** [comment] 2017-08-07 13:01
I can't reproduce this here with a git repo added.

**Comment by Deamon** [comment] 2017-08-14 07:51
I manage to reproduce the problem. 
```
$ ../composer/bin/composer update
Loading composer repositories with package information                                             Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

Exactly as the example, I added a gitlab repo.

I'm working on a PR to solve it. 

But just to know, 

the expected output is the following one : 
```
$ ../composer/bin/composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

with the updating dependencies on a new line.
Because as submited, the output looks like a composer install and not update.

**Comment by Deamon** [comment] 2017-08-14 12:18
After few tests, on my git bash command prompt (MINGW32) I can reproduce the problem.

```
$ php ../composer/bin/composer update
Loading composer repositories with package information                                                                                  Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

I started to launch the command in PHPStorm in several configurations.
When I says asking for debug, it means launching php using those parameters : `-dxdebug.remote_enable=1 -dxdebug.remote_mode=req -dxdebug.remote_port=9000 -dxdebug.remote_host=127.0.0.1`

and it ends up with unexpected outputs : 

w/o xdebug asking debug
```
Loading composer repositories with package information

Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

w/o xdebug and not asking for debug 
```
Loading composer repositories with package information

Reading composer.json of test/test-composer (v1.0)
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

With x-debug asking for debug : 
```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information

Reading composer.json of test/test-composer (v1.0)
Reading composer.json of test/test-composer (master)
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

with xdebug not asking for debug
```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information

Reading composer.json of test/test-composer (v1.0)
                                                    
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```
shouldn't I have the same output ? 

As you can see I end up with lines showing "Reading composer.json..." only in phpStorm console and this line is replaced (?) with spaces in other cli.

I can continue to look At this but I'll need some hints from someone knowing a better than me the composer source code.

Here is the full composer.json file I used to reproduce the problem : 

```
{
  "name": "a./a.",
  "description": "A.",
  "minimum-stability": "dev",
  "prefer-stable": true,
  "license": "proprietary",
  "config": {
    "sort-packages": true
  },
  "require": {
    "seld/jsonlint": "^1.4"
  },
  "repositories": [
    {
      "type": "git",
      "url" : "git@gitlab.com:bdurand/public-test.git"
    }
  ]
}
```

**Comment by Deamon** [comment] 2017-08-14 13:30
Ok so it looks like it comes from `Repository/VcsRepository.php:149` and/or `Repository/VcsRepository.php:213` when calling the `$this->io->overwriteError`

tried to exec the update commande using -vvv where overwriteError isn't called and it works like a charm.

I think the problem comes from the doOverwrite function (`\Composer\IO\ConsoleIO::doOverwrite`) and all the code to clear line. the code comment refs to https://github.com/composer/composer/pull/5836 it might not be an easy fix finally.

**Comment by Seldaek** [comment] 2017-08-14 13:32
If it only happens in phpstorm it might be a bug in phpstorm's handling of the backspace characters we send to overwrite the line?

**Comment by Deamon** [comment] 2017-08-14 13:46
might be. but it only help me to get hints.
@arrgson what software are you using to do your composer commands ?

**Comment by Seldaek** [comment] 2017-12-19 12:39
Closing as this doesn't really seem to be an issue with Composer or at least not widespread.

**Closed by Seldaek** 2017-12-19 12:39 UTC
Labels: Bug
