### ISSUE TITLE
Retry download on `curl error 55`

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#11611] opened 2023-09-01 09:49 UTC
Composer version: latest

CI output: https://github.com/atk4/data/actions/runs/6047830286/job/16412019358#step:7:20

I belive composer should retry the HTTP request on curl error 55.

**Comment by fredden** [comment] 2023-09-01 09:57
@mvorisek please can you provide a version number for Composer? "Composer version: latest" isn't clear to me which version you're referring to. Version 2.6.0 was released an hour ago. I can't see any Composer version information in the linked GitHub Actions run.

**Comment by mvorisek** [comment] 2023-09-01 10:11
composer version: 2.5.8 [1]

[1] https://github.com/mvorisek/image-php/actions/runs/5862936733/job/15911780538#step:14:94

**Comment by fredden** [comment] 2023-09-01 10:55
Thanks for confirming. Please update to version 2.6.0 or better to receive this feature.

**Comment by Seldaek** [comment] 2023-09-01 11:27
Right, duplicate of https://github.com/composer/composer/pull/11543

**Closed by Seldaek** 2023-09-01 11:27 UTC
