### ISSUE TITLE
forking with feature branch makes composer unable to identify dependency

### ISSUE THREAD

**Issue by modelm** [composer/composer#4984] opened 2016-03-01 19:34 UTC
As [requested](https://github.com/composer/composer/issues/4677#issuecomment-190856235) here is an example demonstrating this bug:

There is a parent repository here: https://github.com/modelm/composer-fork-bug-parent

Its composer.json defines two VCS respositories - an original, `modelm/composer-fork-bug-depend`, and a fork, `lksjdflkjsdf/composer-fork-bug-depend`.

The fork has a feature branch named `feature`.

From the parent, this works as expected:
`composer require modelm/composer-fork-bug-depend:dev-master`

This however fails:
`composer require lksjdflkjsdf/composer-fork-bug-depend:dev-feature`

because in the `feature` branch, the package name in the dependency's composer.json has been updated to reflect the new github username owning the fork. Composer thinks that the `lksjdflkjsdf/composer-fork-bug-depend` package is named according to it's *master* (default) branch composer.json (which still says `"name": "modelm/composer-fork-bug-depend"`) rather than the *feature* branch's (which says `"name": "lksjdflkjsdf/composer-fork-bug-depend"`). The error message says only "Could not find package..." rather than explaining the mismatch.

The only fix I know of is to also update the dependency's master branch to use the new github username, but that's not always practical or possible.

**Comment by alcohol** [comment] 2016-03-01 20:22
Why are you changing the name?

**Comment by modelm** [comment] 2016-03-01 20:33
In the particular case where I learned about this behavior, I wanted to distinguish the forked package from the original by name explicitly since both were actively used in related projects. The documentation recommends that "[you should not rename the package unless you really intend to fork it in the long term, and completely move away from the original package.](https://getcomposer.org/doc/05-repositories.md#vcs)" which is more or less what I'm doing.

**Comment by alcohol** [comment] 2016-03-01 20:37
A feature branch is not a long term solution, so no, that is not more or less what you are doing. Hence in this situation, renaming is not necessary. Thus, I see no need to solve an issue that does not exist.

**Comment by modelm** [comment] 2016-03-01 20:41
The feature branch is a stopgap on the way to a more long term solution, but I'll admit it's probably an unusual scenario. The fact that composer reads from a different branch than the one I require in order to discover the package name still seems like a bug regardless.

**Comment by Seldaek** [comment] 2016-03-02 10:52
The problem is the VCS repository has no clue what you (or your dependencies) are requiring, we just don't know until we solve the dependencies. That's why we need to be aware of all branches etc. So "reading from branch X as I require branch X" is not really fixable.

Either you change the name in master branch if you really intend to fork, or you keep the same name as you are just having a feature branch that'll be merged back eventually.

**Closed by Seldaek** 2016-03-02 10:52 UTC
