### ISSUE TITLE
composer update UnexpectedValueException

### ISSUE THREAD

**Issue by heyanlong** [composer/composer#4307] opened 2015-07-28 04:14 UTC
[UnexpectedValueException]
Could not parse version constraint <=2.*: Invalid version string "2.*"

**Comment by mydesign** [comment] 2015-07-28 04:39
The same error. 4 hours can't to resolve it.

**Comment by alcohol** [comment] 2015-07-28 06:28
Can you share your composer.json, the both of you?

**Comment by mydesign** [comment] 2015-07-28 06:38
```
{
    "name": "yiisoft/yii2-app-advanced",
    "description": "Yii 2 Advanced Project Template",
    "keywords": ["yii2", "framework", "advanced", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "dev",
    "require": {
        "php": "~5.4.0",
        "yiisoft/yii2": "~2.0.6",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "rmrevin/yii2-fontawesome": "2.10.*"
    },
    "require-dev": {
        "yiisoft/yii2-codeception": "*",
        "yiisoft/yii2-debug": "*",
        "yiisoft/yii2-gii": "*",
        "yiisoft/yii2-faker": "*"
    },
    "config": {
        "process-timeout": 1800
    },
    "extra": {
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}
```

**Comment by alcohol** [comment] 2015-07-28 07:04
I cannot verify your issue as I run into another problem when trying to reproduce.. :-(

```
$ composer require yiisoft/yii2-app-advanced

..snipped..

Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - yiisoft/yii2-app-advanced 2.0.4 requires yiisoft/yii2 >=2.0.4 -> satisfiable by yiisoft/yii2[2.0.4, 2.0.5].
    - yiisoft/yii2-app-advanced 2.0.0 requires yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - yiisoft/yii2-app-advanced 2.0.1 requires yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - yiisoft/yii2-app-advanced 2.0.2 requires yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - yiisoft/yii2-app-advanced 2.0.3 requires yiisoft/yii2 * -> satisfiable by yiisoft/yii2[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.0.5].
    - yiisoft/yii2 2.0.5 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.4 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.3 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.2 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.1 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - yiisoft/yii2 2.0.0 requires bower-asset/jquery 2.1.*@stable | 1.11.*@stable -> no matching package found.
    - Installation request for yiisoft/yii2-app-advanced ^2.0 -> satisfiable by yiisoft/yii2-app-advanced[2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4].
```

**Comment by alcohol** [comment] 2015-07-28 07:05
I will try cloning your repo and doing a `composer update` instead there.

**Comment by kasp3r** [comment] 2015-07-28 07:05
Same error for me:
```
 [UnexpectedValueException]                                              
  Could not parse version constraint <=2.*: Invalid version string "2.*"
```

**Comment by alcohol** [comment] 2015-07-28 07:06
I am guessing you are all using either `yii2` or a Composer plugin for assets?

**Comment by kasp3r** [comment] 2015-07-28 07:08
I am using Composer plugin for assets

**Comment by alcohol** [comment] 2015-07-28 07:10
Can you run `composer update -vvv` and give me all the details around the Exception?

**Comment by kasp3r** [comment] 2015-07-28 07:24
```
...
Adding VCS repository bower-asset/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap/contents/bower.json?ref=master
Downloading https://api.github.com/repos/twbs/bootstrap/commits/master
Downloading https://api.github.com/repos/twbs/bootstrap/tags?per_page=100
Downloading https://api.github.com/repos/twbs/bootstrap/git/refs/heads?per_page=100


                                                                          
  [UnexpectedValueException]                                              
  Could not parse version constraint <=2.*: Invalid version string "2.*"  
                                                                          


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionParser.php:461
 Composer\Package\Version\VersionParser->parseConstraint() at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionParser.php:257
 Composer\Package\Version\VersionParser->parseConstraints() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:234
 Composer\Package\Loader\ArrayLoader->parseLinks() at phar:///usr/local/bin/composer/src/Composer/Package/Loader/ArrayLoader.php:124
 Composer\Package\Loader\ArrayLoader->load() at /*****/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:174
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->preInitBranchPackage() at /*****/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:138
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initBranches() at /*****/vendor/fxp/composer-asset-plugin/Repository/AssetVcsRepository.php:45
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:178
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at /*****/vendor/fxp/composer-asset-plugin/Repository/Util.php:60
 Fxp\Composer\AssetPlugin\Repository\Util::addRepositoryInstance() at /*****/vendor/fxp/composer-asset-plugin/Repository/Util.php:39
 Fxp\Composer\AssetPlugin\Repository\Util::addRepository() at /*****/vendor/fxp/composer-asset-plugin/Repository/AbstractAssetsRepository.php:139
 Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/Installer.php:855
 Composer\Installer->processDevPackages() at phar:///usr/local/bin/composer/src/Composer/Installer.php:499
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:230
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:140
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25
```

**Comment by heyanlong** [comment] 2015-07-28 07:29
I am using Composer plugin for assets and yii2 (version 2.0.4)

**Comment by alcohol** [comment] 2015-07-28 07:30
It looks like the Asset Plugin is calling parseConstraints with a value that Composer does not accept/support. I do not know where it is retrieving this value from however, since that information is not in the output. I am guessing one of the bower dependencies has a broken requirement.

**Comment by heyanlong** [comment] 2015-07-28 07:30
om-packages/bootstrap-3c71cc99d2fc1c12a3d3e1b27e448ca612a89a1d-package.json into
 cache
Adding VCS repository bower-asset/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap
Downloading https://api.github.com/repos/twbs/bootstrap/contents/bower.json?ref=
master
Downloading https://api.github.com/repos/twbs/bootstrap/commits/master
Downloading https://api.github.com/repos/twbs/bootstrap/tags?per_page=100
Downloading https://api.github.com/repos/twbs/bootstrap/git/refs/heads?per_page=
100



  [UnexpectedValueException]
  Could not parse version constraint <=2.*: Invalid version string "2.*"



Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Packag
e/Version/VersionParser.php:461
 Composer\Package\Version\VersionParser->parseConstraint() at phar://C:/ProgramD
ata/ComposerSetup/bin/composer.phar/src/Composer/Package/Version/VersionParser.p
hp:257
 Composer\Package\Version\VersionParser->parseConstraints() at phar://C:/Program
Data/ComposerSetup/bin/composer.phar/src/Composer/Package/Loader/ArrayLoader.php
:234
 Composer\Package\Loader\ArrayLoader->parseLinks() at phar://C:/ProgramData/Comp
oserSetup/bin/composer.phar/src/Composer/Package/Loader/ArrayLoader.php:124
 Composer\Package\Loader\ArrayLoader->load() at C:\Users\heyanlong\AppData\Roami
ng\Composer\vendor\fxp\composer-asset-plugin\Repository\AssetVcsRepository.php:1
74
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->preInitBranchPackage()
at C:\Users\heyanlong\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\
Repository\AssetVcsRepository.php:138
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initBranches() at C:\Us
ers\heyanlong\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\Reposito
ry\AssetVcsRepository.php:45
 Fxp\Composer\AssetPlugin\Repository\AssetVcsRepository->initialize() at phar://
C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Repository/ArrayRepo
sitory.php:178
 Composer\Repository\ArrayRepository->getPackages() at phar://C:/ProgramData/Com
poserSetup/bin/composer.phar/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at C:\Users\heyanlong\AppData
\Roaming\Composer\vendor\fxp\composer-asset-plugin\Repository\Util.php:60
 Fxp\Composer\AssetPlugin\Repository\Util::addRepositoryInstance() at C:\Users\h
eyanlong\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\Repository\Ut
il.php:39
 Fxp\Composer\AssetPlugin\Repository\Util::addRepository() at C:\Users\heyanlong
\AppData\Roaming\Composer\vendor\fxp\composer-asset-plugin\Repository\AbstractAs
setsRepository.php:139
 Fxp\Composer\AssetPlugin\Repository\AbstractAssetsRepository->whatProvides() at
 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyRe
solver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar://C:/ProgramDat
a/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at phar://C:/ProgramData/Compo
serSetup/bin/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:
168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar://
C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/R
uleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar://C:/Progra
mData/ComposerSetup/bin/composer.phar/src/Composer/DependencyResolver/Solver.php
:177
 Composer\DependencyResolver\Solver->solve() at phar://C:/ProgramData/ComposerSe
tup/bin/composer.phar/src/Composer/Installer.php:505
 Composer\Installer->doInstall() at phar://C:/ProgramData/ComposerSetup/bin/comp
oser.phar/src/Composer/Installer.php:230
 Composer\Installer->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.p
har/src/Composer/Command/UpdateCommand.php:140
 Composer\Command\UpdateCommand->execute() at phar://C:/ProgramData/ComposerSetu
p/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Command/Com
mand.php:257
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/Compo
serSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console/Appl
ication.php:874
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/
ComposerSetup/bin/composer.phar/vendor/symfony/console/Symfony/Component/Console
/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/Compose
rSetup/bin/composer.phar/src/Composer/Console/Application.php:146
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bi
n/composer.phar/vendor/symfony/console/Symfony/Component/Console/Application.php
:126
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerS
etup/bin/composer.phar/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/
composer.phar/bin/composer:43
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:25


update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock]
 [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-
progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader]
 [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [packages1] ... [p
ackagesN]

**Comment by alcohol** [comment] 2015-07-28 07:31
Please report this issue @ [francoispluchino/composer-asset-plugin](/francoispluchino/composer-asset-plugin)

**Comment by heyanlong** [comment] 2015-07-28 07:47
@alcohol @mydesign @kasp3r I used assert plug-in version 1.0.1. does not have this problem.
you try it

**Comment by dbd5** [comment] 2015-07-28 09:46
@alcohol / @heyanlong
I have done as follows per suggestion from @heyanlong ;

# composer global require "fxp/composer-asset-plugin:~1.0.1"

And I got the following;

Changed current directory to /root/.composer
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files

But when I do composer update, I still get the same error as below

[UnexpectedValueException]                                              
  Could not parse version constraint <=2.*: Invalid version string "2.*"

**Comment by alcohol** [comment] 2015-07-28 09:48
That is because `~1.0.1` still allows installing `1.0.2`...

**Comment by alcohol** [comment] 2015-07-28 09:53
Please keep an eye on francoispluchino/composer-asset-plugin#129 for news / updates.

**Comment by dbd5** [comment] 2015-07-28 10:01
You are absolutely right Sir @alcohol 
It's fixed now
Thanks to you both!

**Comment by ttimot24** [comment] 2015-07-30 11:28
These can't solve the issue for me. It keeps throwing the error message.

**Comment by alcohol** [comment] 2015-07-30 11:40
Then you probably have not updated the plugin properly. See the related issue I linked in a post earlier.

**Closed** 2015-08-09 14:36 UTC
Labels: Support
