### ISSUE TITLE
Prevent composer from checking/downloading when versions in local are good

### ISSUE THREAD

**Issue by bilougit** [composer/composer#7262] opened 2018-04-13 12:12 UTC
My company has its own `packagist`. It has many teams working on shared projects.

Many projects I'm working on depend on internal shared projects, of my company, that are handled by `composer`.

When I edit a **dependency** of one project, I need to push the new version of that **dependency** to the company's `gitlab`. Then I should wait for the synchronization to push it to `packagist`. This usually takes several minutes and often it breaks and then our devops restart some services which can take up to 30 minutes.

As a developer, I need to wait all that time for the new version *I've created* to get to `composer` so that `composer update` downloads it. Which makes me loose precious time.

It'd be much better to move the waiting time problem to our CI, which we don't care if it runs a long time to have the new version.

Since I have this version in local because I created it as I said above, wouldn't it be relevant if I could tell composer to not do downloading/fetching if the version is already there?

For instance, let's say in my `composer.json` I have this dependency:

```
"name": "my_company/nice_world",
"require": {
        "php": ">=5.3.17",
        "my_company/project_smurf": "2.0.3",
```

I have edited `project_smurf` in local inside the project `nice_world` and pushed the new tag `2.1.0`.
Then, I'd like that `composer require my_company/project_smurf:2.10` checks the version `2.1.0` in local.
It exists, so composer just makes `git checkout 2.1.0` and updates `composer.lock`.

Would this be something you guys can plan to do?

**Comment by Seldaek** [comment] 2018-04-13 12:24
I see two ways to go here, one is to use [path repositories](https://getcomposer.org/doc/05-repositories.md#path) to link local projects together, but this can be quite messy to handle together with CI if you have multiple repos (which it sounds like you do).

Other option is to get [Private Packagist](https://packagist.com/) which doesn't have 30min delays in package updates.

Closing this as duplicate of #601

**Closed by Seldaek** 2018-04-13 12:24 UTC

**Comment by bilougit** [comment] 2018-04-17 08:00
@Seldaek That can't work for us. The problem is, as you said, we have multiple repositories, plus `composer.lock` is **git-tracked**, so if it works on my local developer environment, it won't work on our CI/delivery server because `path: "../libs/blabla"` only exists on my local environment.

And having a FAST private packagist is not something we as developers can do (company policy).

**Comment by Seldaek** [comment] 2018-04-17 22:59
@bilougit not sure what in your company policy prevents it, but we do offer on-premise installation if that's the problem, just in case you did not see it. https://packagist.com/enterprise

**Comment by bilougit** [comment] 2018-04-18 07:47
@Seldaek ah I misunderstood you, I didn't know that. However we do not use external services, all services are hosted in our local network for security purpose blablabla :smile:  (local packagist, local gitlab etc).

If only it was possible tell `composer.lock` to lie about where it downloaded the package from, I'd tell it to save packages copied from `repositories.type = path` as if it downloaded them from `repositories.type = composer`. Since `repositories.type = path` is not available on CI/Delivery servers.

Anyway, thank you very much for your time :angel:

**Comment by Seldaek** [comment] 2018-04-18 13:31
@bilougit yeah the enterprise version runs in your local network, it's not an external service. That's what I was trying to say.
