### ISSUE TITLE
Composer install generates composer.json with slashes escaped.

### ISSUE THREAD

**Issue by stefgosselin** [composer/composer#6571] opened 2017-07-27 16:33 UTC
I am not certain if this is expected behavior,  `composer.json` is modified ( escaped json) after running composer install.

My initial `composer.json`:

```json
{
    "name": "digitalstate/platform-application",
    "description": "DigitalState Platform Application",
    "homepage": "https://github.com/DigitalState/Platform-Application.git",
    "keywords": ["DigitalState"],
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "": "src/"
        }
    },
    "repositories": {
        "composer": {
            "type": "composer",
            "url": "https://packagist.orocrm.com"
        },
        "dsplatform": {
            "type": "vcs",
            "url": "git@bitbucket.org:villemontreal/dsplatform.git"
        }
    },
    "require": {
        "oro/platform": "2.0.5",
        "oro/platform-serialised-fields": "2.0.2",
        "knplabs/knp-time-bundle": "dev-master#272b9d6c127db1a648d2729bc821f0ed19a274d4",
        "craue/formflow-bundle": "dev-master#47b2b7af9b4385f97470ecb858f3a9c03e431587",
        "digitalstate/bpm-camunda-sdk": "dev-master",
        "lexik/jwt-authentication-bundle": "^2.2",
        "mandrill/mandrill": "^1.0",
        "aws/aws-sdk-php": "^3.28",
        "dunglas/doctrine-json-odm": " dev-master",
        "ramsey/uuid": "^3.6"
    },
    "require-dev": {
        "sensio/generator-bundle": "3.1.2",
        "behat/behat": "3.2.2",
        "behat/mink-extension": "2.2.*",
        "behat/mink-selenium2-driver": "1.*",
        "behat/symfony2-extension": "2.1.1",
        "nelmio/alice": "2.2.*",
        "phpunit/phpunit": "5.7.*",
        "phpunit/phpunit-selenium": "3.0.*",
        "johnkary/phpunit-speedtrap": "1.0.*",
        "mybuilder/phpunit-accelerator": "1.2.*",
        "squizlabs/php_codesniffer": "2.7.*",
        "phpmd/phpmd": "2.5.*",
        "sebastian/phpcpd": "2.0.*",
        "leaphub/phpcs-symfony2-standard": "~2.0.0",
        "league/factory-muffin": "^3.0",
        "league/factory-muffin-faker": "^2.0",
        "codeception/codeception": "^2.2",
        "phploc/phploc": "^3.0"
    },
    "config": {
        "component-dir": "web/bundles/components",
        "bin-dir": "bin"
    },
    "scripts": {
        "post-install-cmd": [
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::checkComposerPlugin",
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setPermissions",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::installAssets",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setAssetsVersion"
        ],
        "post-update-cmd": [
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::checkComposerPlugin",
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setPermissions",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::installAssets",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setAssetsVersion"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "env-map": {
                "server": "SERVER",
                "database_host": "APP_DB_HOST",
                "database_user": "APP_DB_USER",
                "database_password": "APP_DB_PASSWORD",
                "database_name": "APP_DB_NAME"
            },
            "file": "app/config/parameters.yml"
        },
        "asset-installer-paths": {
            "npm-asset-library": "web/bundles/npmassets",
            "bower-asset-library": "web/bundles/bowerassets"
        }
    }
}
```

Output of `composer.json ` after running composer install:

```json

{
    "name": "digitalstate\/platform-application",
    "description": "DigitalState Platform Application",
    "homepage": "https:\/\/github.com\/DigitalState\/Platform-Application.git",
    "keywords": [
        "DigitalState"
    ],
    "license": "MIT",
    "autoload": {
        "psr-4": {
            "": "src\/"
        }
    },
    "repositories": {
        "composer": {
            "type": "composer",
            "url": "https:\/\/packagist.orocrm.com"
        },
        "dsplatform": {
            "type": "vcs",
            "url": "git@bitbucket.org:villemontreal\/dsplatform.git"
        }
    },
    "require": {
        "oro\/platform": "2.0.5",
        "oro\/platform-serialised-fields": "2.0.2",
        "knplabs\/knp-time-bundle": "dev-master#272b9d6c127db1a648d2729bc821f0ed19a274d4",
        "craue\/formflow-bundle": "dev-master#47b2b7af9b4385f97470ecb858f3a9c03e431587",
        "digitalstate\/bpm-camunda-sdk": "dev-master",
        "lexik\/jwt-authentication-bundle": "^2.2",
        "mandrill\/mandrill": "^1.0",
        "aws\/aws-sdk-php": "^3.28",
        "dunglas\/doctrine-json-odm": " dev-master",
        "ramsey\/uuid": "^3.6"
    },
    "require-dev": {
        "sensio\/generator-bundle": "3.1.2",
        "behat\/behat": "3.2.2",
        "behat\/mink-extension": "2.2.*",
        "behat\/mink-selenium2-driver": "1.*",
        "behat\/symfony2-extension": "2.1.1",
        "nelmio\/alice": "2.2.*",
        "phpunit\/phpunit": "5.7.*",
        "phpunit\/phpunit-selenium": "3.0.*",
        "johnkary\/phpunit-speedtrap": "1.0.*",
        "mybuilder\/phpunit-accelerator": "1.2.*",
        "squizlabs\/php_codesniffer": "2.7.*",
        "phpmd\/phpmd": "2.5.*",
        "sebastian\/phpcpd": "2.0.*",
        "leaphub\/phpcs-symfony2-standard": "~2.0.0",
        "league\/factory-muffin": "^3.0",
        "league\/factory-muffin-faker": "^2.0",
        "codeception\/codeception": "^2.2",
        "phploc\/phploc": "^3.0"
    },
    "config": {
        "component-dir": "web\/bundles\/components",
        "bin-dir": "bin"
    },
    "scripts": {
        "post-install-cmd": [
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::checkComposerPlugin",
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setPermissions",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::installAssets",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setAssetsVersion"
        ],
        "post-update-cmd": [
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::checkComposerPlugin",
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setPermissions",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::installAssets",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setAssetsVersion"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "env-map": {
                "database_driver": "APP_DB_DRIVER",
                "database_host": "APP_DB_HOST",
                "database_port": "APP_DB_PORT",
                "database_name": "APP_DB_NAME",
                "database_user": "APP_DB_USER",
                "database_password": "APP_DB_PASSWORD",
                "mailer_transport": "APP_MAILER_TRANSPORT",
                "mailer_host": "APP_MAILER_HOST",
                "mailer_port": "APP_MAILER_PORT",
                "mailer_encryption": "APP_MAILER_ENCRYPTION",
                "mailer_user": "APP_MAILER_USER",
                "mailer_password": "APP_MAILER_PASSWORD",
                "websocket_bind_port": "APP_WEBSOCKET_BACKEND_PORT",
                "websocket_backend_port": "APP_WEBSOCKET_BACKEND_PORT",
                "websocket_frontend_port": "APP_WEBSOCKET_FRONTEND_PORT",
                "installed": "APP_IS_INSTALLED",
                "secret": "APP_SECRET"
            },
            "file": "app\/config\/parameters.yml"
        },
        "asset-installer-paths": {
            "npm-asset-library": "web\/bundles\/npmassets",
            "bower-asset-library": "web\/bundles\/bowerassets"
        }
    }
}%

```

Is this exepected behavior? 

Also, quite certain the % should not be there at the end, but it is also generated by the composer install .

**Comment by nazar-pc** [comment] 2017-07-31 00:18
This is just a matter of using `JSON_UNESCAPED_SLASHES` in `json_encode()` (which is not used by default) and doesn't really affect anything other than readability. It might be useful to escape slashes when inserting JSON into `<script>` tag, but this is irrelevant here.

**Comment by alcohol** [comment] 2017-07-31 06:21
The `%` is not generated by Composer. I am fairly certain it is generated by your shell when you used `cat` to output this file. Open it in `vim` for example and you will see the `%` is not there.

**Comment by Seldaek** [comment] 2017-08-07 13:22
AFAIK composer does not touch the composer.json during install.. Looks like you have some plugins though so maybe one of the plugins is doing something funky there. If you can reproduce it without plugin please let us know.

**Comment by Seldaek** [comment] 2017-08-07 13:23
Also.. Composer always encodes json nicely without escaping via JsonFile::encode so I am really doubtful this is a bug on our end.

**Comment by Seldaek** [comment] 2018-04-13 09:28
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.

**Closed by Seldaek** 2018-04-13 09:28 UTC
Labels: Support
