### ISSUE TITLE
Composer Archive Zip contains dot files even though excluded

### ISSUE THREAD

**Issue by cliffordp** [composer/composer#8866] opened 2020-05-04 05:31 UTC
My `composer.json`:

```json
...
	"minimum-stability": "stable",
	"archive": {
		"exclude": [
			"*",
			".*",
			"*/",
			"!vendor/*",
			"!dist/*",
			"!languages/*",
			"!*.bmp",
			"!*.gif",
			"!*.jpg",
			"!*.jpeg",
			"!*.pdf",
			"!*.php",
			"!*.png",
			"!*.svg",
			"!*.tiff",
			"!*.txt",
			"!*.webp",
			"node_modules/"
		]
	},
	"config": {
		"archive-format": "zip",
		"optimize-autoloader": true
	},
		...
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.5
PHP version: 7.4.5
PHP binary path: /usr/local/Cellar/php/7.4.5_2/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer archive
```

I get the following output:

The .zip contains these:
* `.externals.js`
* `.gitignore`

And I expected this to happen:

The .zip should NOT contain these dot files, per my `"*"` rule but especially due to my `".*"` rule as well.

**Comment by Seldaek** [comment] 2022-05-24 20:15
Could not reproduce so closing with https://github.com/composer/composer/commit/10d3895f187b0be4346781eac5788e15753b2d7c

**Closed by Seldaek** 2022-05-24 20:15 UTC
Labels: Bug
