### ISSUE TITLE
composer doesn't ask for authentication for private gitlab repository when download from dist

### ISSUE THREAD

**Issue by flachesis** [composer/composer#6384] opened 2017-04-27 07:28 UTC
My `composer.json`:

```json
{
  "name": "flachesis/test",
  "description": "test",
  "type": "library",
  "authors": [
    {
      "name": "flachesis",
      "email": "flachesis@flachesis.com"
    }
  ],
  "repositories": [
    {
      "type": "composer",
      "url": "http://satis.flachesis.com"
    }
  ],
  "require": {
    "flachesis/private-package": "~1.0"
  },
  "require-dev": {
    "phpunit/phpunit": "^4.8"
  },
  "config": {
    "gitlab-domains": [
      "gitlab.flachesis.com"
    ],
    "secure-http": false
  },
  "minimum-stability": "dev",
  "prefer-stable": true
}
```

When I run this command:

```
composer install
```

I get the following output:

```
Downloading (failed)    Failed to download flachesis/private-package from dist: The "https://gitlab.flachesis.com/api/v3/projects/flachesis%2Fprivate-package/repository/archive.zip?sha=f79009b96d27283f54be50e69ce8e48df75abb4b" file could not be downloaded (HTTP/1
.1 404 Not Found)
```

And I expected this to happen:
```
Could not fetch https://gitlab.flachesis.com/api/v3/projects/flachesis%2Fprivate-package/repository/archive.zip?sha=f79009b96d27283f54be50e69ce8e48df75abb4b, enter your gitlab.flachesis.com credentials to access private repos
A token will be created and stored in "/home/flachesis/.config/composer/auth.json", your password will never be stored
To revoke access to this token you can visit gitlab.flachesis.com/profile/applications
Username: flachesis
Password: 
Token successfully created
Downloading (100%)
```

**Comment by flachesis** [comment] 2017-04-27 07:33
```
diff --git a/src/Composer/Util/RemoteFilesystem.php b/src/Composer/Util/RemoteFilesystem.php
index 4074d833..0b7b6629 100644
--- a/src/Composer/Util/RemoteFilesystem.php
+++ b/src/Composer/Util/RemoteFilesystem.php
@@ -348,6 +348,19 @@ protected function get($originUrl, $fileUrl, $additionalOptions = array(), $file
             }
         }
 
+        if (
+            $statusCode
+            && $statusCode == 404
+            && $this->config
+            && in_array($this->originUrl, $this->config->get('gitlab-domains'), true)
+            && !$this->io->hasAuthentication($this->originUrl)
+        ) {
+            $result = false;
+            if ($this->retryAuthFailure) {
+                $this->promptAuthAndRetry(401);
+            }
+        }
+
```
I add those code to handle authentication.

**Comment by Seldaek** [comment] 2017-09-11 13:46
f71baa5e0 attempts to fix that by making it prompt on gitlab 404s. Please try to `self-update --snapshot` and check whether it helps? In the meantime, closing as duplicate of #6669 which is the same problem.

**Closed by Seldaek** 2017-09-11 13:46 UTC
Labels: Bug
