### ISSUE TITLE
Composer update failure.

### ISSUE THREAD

**Issue by AlexanderWright** [composer/composer#8941] opened 2020-06-02 14:30 UTC
My `composer.json`:

```json
{
    "name": "laravel/laravel",
    "description": "Pharmacyspace.",
    "keywords": [
        "pharmacyspace"
    ],
    "license": "proprietary",
    "type": "project",
    "require": {
        "php": "^7.2",
        "laravel/framework": "^6.18",
        "alexanderwright/shoppingcart": "~2.6",
        "laracasts/flash": "^3.0.2",
        "laravelcollective/html": "^6.0",
        "cviebrock/eloquent-sluggable": "^6.0.0",
        "doctrine/dbal": "^2.5",
        "citco/carbon": "^1.0",
        "pusher/pusher-php-server": "^3.0",
        "alexanderwright/laravel6-braintree": "dev-master",
        "laravel/tinker": "^2.0",
        "fideloper/proxy": "^4.0"
    },
    "require-dev": {
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "phpunit/phpunit": "^8.0",
        "laracasts/generators": "^1.1",
        "laravel/browser-kit-testing": "^5.1.3",
        "nunomaduro/collision": "^3.0",
        "facade/ignition": "^1.4"
    },
    "autoload": {
        "classmap": [
            "database/seeds",
            "database/factories"
        ],
        "psr-4": {
            "App\\": "app/"
        }
    },
    "autoload-dev": {
        "classmap": [
            "tests/TestCase.php",
            "tests/BrowserKitTestCase.php"
        ],
        "files": [
            "tests/MailTracking.php"
        ]
    },
    "scripts": {
        "post-install-cmd": [
            "@php artisan clear-compiled",
            "@php artisan optimize"
        ],
        "post-update-cmd": [
            "@php artisan clear-compiled",
            "@php artisan optimize"
        ],
        "post-root-package-install": [
            "@php -r \"copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ]
    },
    "config": {
        "preferred-install": "dist",
        "optimize-autoloader": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: You are not running the latest snapshot version, run `composer self-update` to update (383fbe4a8af6229b6c405e6ade85c6764e00f7dd => 4d75d524f18ba5101fd8ad153b7ce4fd35f79883)
Composer version: 2.0-dev+383fbe4a8af6229b6c405e6ade85c6764e00f7dd
PHP version: 7.4.0
PHP binary path: /usr/local/Cellar/php/7.4.0/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
composer install
```

I get the following output:

```
No lock file found. Updating dependencies instead of installing from lock file. Use composer update over composer install if you do not have a lock file.
Loading composer repositories with package information
Updating dependencies


  [Composer\DependencyResolver\SolverBugException]
  Reached invalid decision id 0 while looking through (-81) for a literal present in the analyzed rule (multi(-6184|-628|-627|-626|-625|-624|-623|-622|-621|-620|-619|-618|-617|-616|-
  615|-614|-613|-612|-611|-610|-609|-608|-607|-606|-605|-604|-603|-602|-601|-600|-599|-598|-597|-596|-595|-594|-593|-592|-591|-590|-589|-588|-587|-586|-585|-584|-583|-582|-581|-580|-
  579|-578|-577|-576|-575|-574|-573|-572|-571|-570|-569|-568|-567|-566|-565|-564|-563|-562|-561|-560|-559|-558|-557|-556|-555|-554|-553|-552|-551|-550|-549|-548|-547|-546|-545|-544|-
  543|-542|-541|-540|-539|-538|-537|-536|-535|-534|-533|-532|-531|-530|-529|-528|-527|-526|-525|-524|-523|-522|-521|-520|-519|-518|-517|-516|-515|-514|-513|-512|-511|-510|-509|-508|-
  507|-506|-505|-504|-503|-502|-501|-500|-499|-498|-497|-496|-495|-494|-493|-492|-491|-490|-489|-488|-487|-486|-485|-484|-483|-482|-481|-480|-479|-478|-477|-476|-475|-474|-473|-472|-
  471|-470|-469)).
  This exception was most likely caused by a bug in Composer.
  Please report the command you ran, the exact error you received, and your composer.json on https://github.com/composer/composer/issues - thank you!


install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-suggest] [--no-dev] [--no-autoloader] [--no-scripts] [--no-progress] [--no-install] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--] [<packages>]...

```

And I expected this to happen:
packages to be installed.

**Comment by Seldaek** [comment] 2020-06-02 15:19
Can confirm, most likely duplicate of the few other issues we have which look like this.. Leaving open though as long as we don't have a resolution.

**Comment by barryvdh** [comment] 2020-06-23 07:45
I encountered the same issue with Github Actions: https://github.com/barryvdh/laravel-ide-helper/pull/968/checks?check_run_id=798364715

See composer.json: https://github.com/barryvdh/laravel-ide-helper/blob/7298d6e9653cc77736d956a02d3f5c0ad2a173d5/composer.json
Action: https://github.com/barryvdh/laravel-ide-helper/blob/d0a23693f306b0e6a3ea31cbaf97bd623dfeaefc/.github/workflows/run-tests.yml#L64
Details: <details>
            Run composer self-update --2
Warning: You forced the install of ae44a5963d18b61e0334295b005de7a4ee28aafc via --2, but 1.10.7 is the latest stable version. Updating to it via composer self-update --stable is recommended.
You are already using composer version ae44a5963d18b61e0334295b005de7a4ee28aafc (2 channel).
./composer.json has been updated
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
  [Composer\DependencyResolver\SolverBugException]                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      
  Reached invalid decision id 0 while looking through (-361) for a literal present in the analyzed rule (-125|1324|1325|1326|1327|1328|1329|1330|1331|1332|1333|1334|1335|1336|1337|1338|1339|1340|1341|1342|1343|1344|1345|1346|1347|1348|1349|1350|1351|1352|1353|1354|1355|1356|1357|1358|1359|1360|1361|1362|1363|1364|1365|1366|1367|1368|1369|1370|1371|1372|1373|1374|1375|1376|1377|1378|1379|1380|1381|1382|1383|1384|1385|1386|1387|1388|1389|1390|1391|1392|1393|1394|1395|1396|1397|1398|1399|1400|1401|1402|1403|1404|1405|1406|1407|1408|1409|1410|1411|1412|1413|1414|1415|1416|1417|1418|1419|1420|1421|1422|1423|1424|1425|1426|1427|1428|1429|1430|1431|1432|1433|1434|1435|1436|1437|1438|1439|1440|1441|1442|1443|1444|1445|1446|1447|1448|1449|1450|1451|1452|1453|1454|1455|1456|1457|1458|1459|1460|1461|1462|1463|1464|1465|1466|1467|1468|1469|1470|1471|1472|1473|1474|1475|1476|1477|1478|1479|1480|1481|1482|1483|1484|1485|1486|1487|1488|1489|1490|1491|1492|1493|1494|1495|1496|1497|1498|1499|1500|1501|1502|1503|1504|1505|1506|1507|1508|1509|1510|1511|1512|1513|1514|1515|1516|1517|1518|1519|1520|1521|1522|1523|1524|1525|1526|1527|1528|1529|1530|1531|1532|1533|1534|1535|1536|1537|1538|1539|1540|1541|1542|1543|1544|1545|1546|1547|1548|1549|1550|1551|1552|1553|1554|1555|1556|1557|1558|1559|1560|1561|1562|1563|1564|1565|1566|1567|1568|1569|1570|1571|1572|1573|1574|1575|1576|1577|1578|1579|1580|1581|1582|1583|1584|1585|1586|1587|1588|1589|1590).  
  This exception was most likely caused by a bug in Composer.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           
  Please report the command you ran, the exact error you received, and your composer.json on https://github.com/composer/composer/issues - thank you!                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        </details>

It's strange (to me) that it runs fine on some matrix builds, but crashes on others. Eg PHP 7.3+Laravel7 and PHP7.2 + Laravel 7 fail, but PHP 7.4+ Laravel 7 and PHP7.3 + Laravel 6 pass.

<img width="809" alt="Screen Shot 2020-06-23 at 09 43 02" src="https://user-images.githubusercontent.com/973269/85375072-0f6ec300-b536-11ea-9def-214c7a54e09f.png">

**Comment by naderman** [comment] 2020-06-23 08:43
Probably duplicate of https://github.com/composer/composer/issues/7051

**Comment by naderman** [comment] 2020-06-23 08:44
@barryvdh Since this is only triggered by rather specific combinations of dependencies a small change like different PHP version can already result in a successful run as it changes the order of resolution / which packages get picked.

**Comment by naderman** [comment] 2020-06-29 08:40
@AlexanderWright @barryvdh I believe this has been fixed in Composer2 master, can you check again that you can still reproduce the problem on Composer2 alpha1/2 and if yes, test again with a current snapshot (composer self-update --snapshot) and tell me if that fixes it? Thanks!

**Comment by barryvdh** [comment] 2020-06-29 11:02
I think it is solved now. Github has some issues but it seemed to work now: https://github.com/barryvdh/laravel-ide-helper/actions/runs/144580351

**Comment by Seldaek** [comment] 2020-06-29 11:22
Ok, marking closed then, please reopen if you still have a use case failing on latest snapshot.

**Comment by barryvdh** [comment] 2020-06-29 11:35
Well not sure if the original issue from @AlexanderWright was fixed, but thanks!

**Comment by barryvdh** [comment] 2020-06-29 17:46
Sorry, I do get the same error after changing the depencies (that work on v1), only with prefer-lowest, the rest works.
https://github.com/barryvdh/laravel-ide-helper/pull/968/checks?check_run_id=819426586
<img width="1239" alt="Screen Shot 2020-06-29 at 19 44 47" src="https://user-images.githubusercontent.com/973269/86038370-1a978680-ba41-11ea-8d70-374096f07b63.png">

Using the latest snapshot. It broke after this commit: https://github.com/barryvdh/laravel-ide-helper/pull/968/commits/84933ea80fd3b23904e7d12a6d7e3c61a8f3ab68

**Comment by Seldaek** [comment] 2020-07-01 07:45
Ok so not quite fixed.

**Comment by Seldaek** [comment] 2020-10-21 18:11
OP case is now confirmed fixed (albeit slow to resolve) with latest snapshot (`composer self-update --snapshot`). @barryvdh please try again and report a new issue with repro details if you still experience issues.

**Closed by Seldaek** 2020-10-21 18:11 UTC
Labels: Bug, Solver
