### ISSUE TITLE
composer config messes up empty autoload/psr-4 object

### ISSUE THREAD

**Issue by pniederlag** [composer/composer#6335] opened 2017-04-07 06:45 UTC
I do have a valid `composer.json`, which is in use for quite some time. In order to add another repository I do use the CLI like so:

```bash
composer config repositories.l10nmgr vcs https://git.typo3.org/TYPO3CMS/Extensions/l10nmgr.git
```

Any subsequent usage of composer cli results in a fatal error:

```bash
[Composer\Json\JsonValidationException]                           
"./composer.json" does not match the expected JSON schema:        
- autoload.psr-4 : Array value found, but an object is required 
```

Here is the relevant diff to composer.json that causes it.

```json
        "autoload": {
-        "psr-4": {
-        }
+        "psr-4": []
     },
```

the (empty, yet valid) object entry was changed into an (empty) invalid array value. Setting this back to an empty object '{}' I can continue work as intented.

Composer version used:

    composer -- version
    Composer version 1.4.1 2017-03-10 09:29:45
Output of `composer config repositories.l10nmgr vcs https://git.typo3.org/TYPO3CMS/Extensions/l10nmgr.git`:

**Comment by Seldaek** [comment] 2017-04-07 08:08
I think this can be fixed by doing the fallback json transformation using json_decode with objects rather than arrays, it shouldn't be too much work I guess, and probably fixes this. In the meantime I'd suggest you avoid having empty declarations in the json file, as this is what triggers the problem, and they are not bringing anything.

**Comment by pniederlag** [comment] 2017-04-07 08:19
hi, 

thx for your quick feedback! I think I got the point. Changing the fallback transformation from array to object sounds like the very same problem could appear elsewhere.

If your suggestion is to avoid having empty declarations why not default to drop empty declarations? Imho it's way better to drop unused stuff than to risk ending up with a broken composer.json. 

FYI: We use empty declarations in terms of "keep in mind, you might have to add autoload entries here", they just feel comfortable for me.

**Comment by Seldaek** [comment] 2017-04-07 08:25
No what I mean is if you `json_decode(..., false)` instead of `(..., true)`  then you get safe types and empty objects don't get converted to arrays accidentally, so this would fix it I'm pretty sure.

**Comment by Seldaek** [comment] 2020-10-28 14:23
I think this was fixed, can't reproduce.

**Closed by Seldaek** 2020-10-28 14:23 UTC
Labels: Bug
