### ISSUE TITLE
composer codification error

### ISSUE THREAD

**Issue by ggfernando94** [composer/composer#5607] opened 2016-08-18 09:03 UTC
When I run this command:

```
composer --version
```

I get this output:

```
[32mComposer[39m version [33m1.2.0[39m 2016-07-19 01:28:52
```

![captura](https://cloud.githubusercontent.com/assets/19630730/17768006/d3042640-64f7-11e6-924e-4b747234282b.PNG)

i have windows 10 home but already test windows pro version and have the same error

![captura2](https://cloud.githubusercontent.com/assets/19630730/17768140/5f243f70-64f8-11e6-9038-3ec0c9f33438.PNG)

please need some help  ( sorry for the bad english :( )

**Comment by stof** [comment] 2016-08-18 10:01
Are you using cmd.exe or powershell to run the command ?

Windows 10 supports ANSI colors, which is why Composer uses them here. But some people already reported that powershell disables this feature by default.

**Comment by stof** [comment] 2016-08-18 10:03
Note that you can use the ``--no-ansi`` option to force composer to avoid using ANSI codes for colors (there is also a ``--ansi`` option to force using them, even when the autodetection told composer to skip them)

**Comment by johnstevenson** [comment] 2016-08-18 10:42
Which version of Windows 10 are you using? Go to _Settings, System, About_

This would be useful to know because on my machine the latest (Anniversary) update removed ANSI color support in cmd.exe but not in powershell.

**Comment by alcohol** [comment] 2016-08-18 11:14
Duplicate of #5323

**Closed by alcohol** 2016-08-18 11:14 UTC

**Comment by ggfernando94** [comment] 2016-08-18 20:59
i "fix" using **power shell** thanks to all <3

**Comment by cirdog** [comment] 2016-08-26 04:26
If it hasn't been mentioned before, the global workaround for Windows is:

```
C:\ProgramData\ComposerSetup\bin\composer.bat
(edit its content)
php "%~dp0composer.phar" %* --no-ansi
```

Adding the "--no-ansi" flag at the launch script of composer, then it eliminates the need to flag it for every command.
