### ISSUE TITLE
End of php52 supporting

### ISSUE THREAD

**Issue by sveneld** [composer/composer#9224] opened 2020-09-17 13:38 UTC
7 years ago such issue was created https://github.com/composer/composer/issues/1730
As a result such code is using now in production
`$vendorPathCode52 = str_replace('__DIR__', 'dirname(__FILE__)', $vendorPathCode);`

Mayby it's time to remove this code and say good bay to php5.2?

Using `dirname(__FILE__)` is also slower 
```
$startTime = microtime(true);
for ($i=1;$i<1000000;$i++){
    $a = dirname(__FILE__);
}
echo microtime(true) - $startTime;

echo PHP_EOL;
$startTime = microtime(true);
for ($i=1;$i<1000000;$i++){
    $a = __DIR__;
}
echo microtime(true) - $startTime;
```

Result
0.95782494544983
0.14195108413696

**Comment by xabbuh** [comment] 2020-09-17 14:05
see #8785

**Comment by sveneld** [comment] 2020-09-17 14:12
@xabbuh thanks, but as i can see in discussion minimum version is 5.3. And minimum version in composer.json for composer is also "php": "^5.3.2

**Comment by stof** [comment] 2020-09-17 14:48
AFAICT, the only places supporting PHP 5.2 are the generated `vendor/autoload_{files,namespaces,classmap}.php` files. As these are not used at all anymore when using the `vendor/autoload.php` file on PHP 5.6+ (it reads `vendor/autoload_static.php` instead), there is no performance impact.

So my suggestion is to keep that legacy feature until Composer 2.1 and to clean this at the same time than other things.

**Comment by Wirone** [comment] 2021-11-24 07:17
Probably duplicate of #9303 @Seldaek

**Closed** 2022-01-04 15:30 UTC
