### ISSUE TITLE
Please document new PHP version requirements

### ISSUE THREAD

**Issue by greg-1-anderson** [composer/composer#10422] opened 2022-01-03 15:05 UTC
The [System Requirements](https://getcomposer.org/doc/00-intro.md#system-requirements) section of the Composer documentation still says that PHP 5.3.2+ is supported. It appears that Composer 2.3.0 will only support PHP 7.2+, per #10343. Please update the documentation so that users still running on EOL versions of PHP know clearly what is supported.

**Comment by Seldaek** [comment] 2022-01-03 15:40
Yup we need to update a bunch of places I am sure. Thanks for the reminder. It's 7.2.5 requirement, otherwise nothing much changed I believe. People packaging with older PHP should use the 2.2.x LTS series.

**Comment by andypost** [comment] 2022-01-22 04:54
Looks like duplicate of https://github.com/composer/composer/issues/10340

**Comment by RdeWilde** [comment] 2022-01-31 08:54
Does composer 2.2.5 support PHP 8.1? Any summary for the constraints per version?

**Comment by GromNaN** [comment] 2022-01-31 10:21
Summary is here: #10340

I assume composer 2.2.x will support all new PHP versions until the end of the LTS.

**Comment by Seldaek** [comment] 2022-01-31 14:10
Composer 2.2 supports PHP 8.1 yes, but it may not support 8.2 depending on the effort required. If you are using 8.2 you anyway should use Composer 2.3+ IMO.

**Comment by Seldaek** [comment] 2022-02-23 13:44
Updated things in https://github.com/composer/composer/pull/10562 and also listing version support for the manual download links on https://getcomposer.org/download/

**Closed by Seldaek** 2022-02-23 13:44 UTC
Labels: Documentation
