### ISSUE TITLE
CTRL+C does not exit Composer install/update in WSL2/Windows Terminal

### ISSUE THREAD

**Issue by mortona42** [composer/composer#11116] opened 2022-10-12 21:44 UTC
My `composer.json`:

```json
{
    "name": "mysite/drupal",
    "description": "My site.",
    "type": "project",
    "license": "GPL-2.0-or-later",
    "authors": [
        {
            "name": "",
            "role": ""
        }
    ],
    "repositories": [
        {
            "type": "composer",
            "url": "https://packages.drupal.org/8"
        },
        {
            "type": "package",
            "package": {
              "name": "ckeditor/resize",
              "installer-name": "resize",
              "version": "4.19.0",
              "type": "drupal-library",
              "dist": {
                "url": "https://download.ckeditor.com/resize/releases/resize_4.19.0.zip",
                "type": "zip"
              }
            }
        },
        {
            "type": "package",
            "package": {
              "name": "ckeditor-plugin/wordcount",
              "version": "1.17.9",
              "type": "drupal-library",
              "dist": {
                "url": "https://download.ckeditor.com/wordcount/releases/wordcount_1.17.9.zip",
                "type": "zip"
              }
            }
        },
        {
            "type": "package",
            "package": {
              "name": "furf/jquery-ui-touch-punch",
              "version": "dev-master",
              "type": "drupal-library",
              "dist": {
                "url": "https://github.com/furf/jquery-ui-touch-punch/archive/master.zip",
                "type": "zip"
              }
            }
        },
        {
            "type": "package",
            "package": {
                "name": "select2/select2",
                "version": "4.0.13",
                "type": "drupal-library",
                "dist": {
                    "type": "zip",
                    "url": "https://github.com/select2/select2/archive/refs/tags/4.0.13.zip"
                }
            }
        }
    ],
    "require": {
        "php": ">=7.3",
        "behat/mink-selenium2-driver": "dev-master as 1.3.x-dev",
        "composer/installers": "1.9.0",
        "cweagans/composer-patches": "1.7.0",
        "drupal/console": "^1.0.2",
        "drupal/core": "9.4.5",
        "drupal/core-composer-scaffold": "9.4.5",
        "drush/drush": "10.3.6",
        "oomphinc/composer-installers-extender": "2.0.0",
        "pantheon-systems/drupal-integrations": "9.0.0",
        "vlucas/phpdotenv": "^2.4",
        "webflo/drupal-finder": "^1.0.0",
        "zaporylie/composer-drupal-optimizations": "^1.0",
        "ckeditor/resize": "4.19.0",
        "ckeditor-plugin/wordcount": "1.17.9",
        "furf/jquery-ui-touch-punch": "dev-master",
        "select2/select2": "4.0.13",
        "drupal/address": "1.11",
        "drupal/admin_toolbar": "3.1.1",
        "drupal/advagg": "5.0",
        "drupal/allowed_formats": "1.5",
        "drupal/auto_entitylabel": "3.0-beta4",
        "drupal/better_exposed_filters": "5.2",
        "drupal/captcha": "1.4",
        "drupal/ckeditor_resize": "1.3",
        "drupal/ckwordcount": "1.5",
        "drupal/cdn": "3.5",
        "drupal/config_filter": "2.4",
        "drupal/config_override_warn": "1.3",
        "drupal/config_rewrite": "1.5",
        "drupal/config_split": "2.0.0-rc3",
        "drupal/content_lock": "2.2",
        "drupal/contextual_range_filter": "1.0",
        "drupal/consumers": "1.13",
        "drupal/csv_serialization": "2.1",
        "drupal/ctools": "3.10",
        "drupal/devel": "4.1.5",
        "drupal/devel_entity_updates": "3.0.1",
        "drupal/diff": "1.0",
        "drupal/dynamic_entity_reference": "2.0-alpha19",
        "drupal/editor_advanced_link": "2.0",
        "drupal/entityqueue": "1.2",
        "drupal/entity_browser": "2.8",
        "drupal/entity_browser_enhanced": "1.0",
        "drupal/entity_reference_revisions": "1.10",
        "drupal/entity_usage": "2.0-beta6",
        "drupal/field_group": "3.2",
        "drupal/file_delete": "1.0",
        "drupal/file_mdm": "2.4",
        "drupal/flag": "4.0-beta3",
        "drupal/google_tag": "1.5",
        "drupal/hook_event_dispatcher": "3.2.0",
        "drupal/image_effects": "3.3",
        "drupal/imagecache_external": "3.0",
        "drupal/imce": "2.4",
        "drupal/instapage": "3.0.1",
        "drupal/jsonapi_extras": "3.21",
        "drupal/jwt": "1.0",
        "drupal/key": "1.15",
        "drupal/language_access": "1.7",
        "drupal/linkchecker": "1.0-beta5",
        "drupal/linkit": "6.0.0-beta3",
        "drupal/login_security": "2.0",
        "drupal/masquerade": "2.0-beta4",
        "drupal/media_library_edit": "2.3",
        "drupal/metatag": "1.21",
        "drupal/migrate_plus": "5.3",
        "drupal/migrate_tools": "5.1",
        "drupal/minifyjs": "2.2",
        "drupal/module_missing_message_fixer": "2.0.2",
        "drupal/mtcaptcha": "6.1",
        "drupal/name": "1.x-dev",
        "drupal/node_edit_protection": "1.0",
        "drupal/node_revision_delete": "1.0-rc5",
        "drupal/notification": "1.1",
        "drupal/page_manager": "4.0-beta6",
        "drupal/panels": "4.6",
        "drupal/pantheon_advanced_page_cache": "2.0",
        "drupal/paragraphs": "1.14",
        "drupal/pathauto": "1.11",
        "drupal/pdb": "1.x-dev@dev",
        "drupal/permissions_filter": "1.3",
        "drupal/queue_ui": "3.1",
        "drupal/quick_node_clone": "1.15",
        "drupal/range": "1.4",
        "drupal/readonlymode": "1.1",
        "drupal/redirect": "1.7",
        "drupal/redis": "1.5",
        "drupal/robotstxt": "1.4",
        "drupal/role_delegation": "1.2",
        "drupal/remote_stream_wrapper": "2.0",
        "drupal/remote_stream_wrapper_widget": "1.x-dev",
        "drupal/reroute_email": "2.1.1",
        "drupal/restui": "1.21",
        "drupal/salesforce": "5.0.0",
        "drupal/schema_metatag": "2.3",
        "drupal/search_api": "1.25",
        "drupal/search_api_autocomplete": "1.6",
        "drupal/search_api_solr": "4.2.8",
        "drupal/seckit": "2.0.0",
        "drupal/select2": "1.13",
        "drupal/scheduler": "1.4",
        "drupal/scheduler_content_moderation_integration": "1.4",
        "drupal/simple_oauth": "5.2.0",
        "drupal/siteimprove": "1.12",
        "drupal/smtp": "1.1",
        "drupal/stripe": "1.0",
        "drupal/subpathauto": "1.2",
        "drupal/term_reference_tree": "1.x-dev",
        "drupal/token": "1.11",
        "drupal/transliterate_filenames": "2.0.1",
        "drupal/typed_data": "1.0-beta1",
        "drupal/ultimate_cron": "2.0-alpha5",
        "drupal/views_bulk_operations": "4.1.4",
        "drupal/views_data_export": "1.1",
        "drupal/votingapi": "3.0-beta3",
        "drupal/xmlsitemap": "1.2"
    },
    "require-dev": {
        "mglaman/drupal-check": "^1.0",
        "sempro/phpunit-pretty-print": "1.0.3",
        "drupal/core-dev": "9.4.5",
        "drupal/drupal-extension": "^4.0.1",
        "drupal/entity_browser": "2.8",
        "phpspec/prophecy-phpunit": "^2"
    },
    "conflict": {
        "drupal/drupal": "*"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "config": {
        "optimize-autoloader": true,
        "sort-packages": true,
        "allow-plugins": {
            "composer/installers": true,
            "cweagans/composer-patches": true,
            "drupal/console-extend-plugin": true,
            "drupal/core-composer-scaffold": true,
            "oomphinc/composer-installers-extender": true,
            "zaporylie/composer-drupal-optimizations": true,
            "dealerdirect/phpcodesniffer-composer-installer": true
        }
    },
    "autoload": {
        "classmap": [
            "scripts/composer/ScriptHandler.php"
        ],
        "psr-4": {
            "Drupal\\twig_component\\": "web/components/src"
        },
        "files": ["load.environment.php"]
    },
    "scripts": {
        "pre-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "pre-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::checkComposerVersion"
        ],
        "npm-install": "npm install --prefix web/themes/custom/mytheme",
        "prepare-git": "DrupalProject\\composer\\ScriptHandler::prepareGit",
        "build-assets-css": [
            "@npm-install",
            "npm run build:css --prefix web/themes/custom/mytheme"
        ],
        "build-theme-css": "npm run build:css --prefix web/themes/custom/mytheme--ansi",
        "build-comp-css": "npm run build:css --prefix web/components --ansi",
        "post-install-cmd": [
            "DrupalProject\\composer\\ScriptHandler::postUpdatePackage"
        ],
        "post-update-cmd": [
            "DrupalProject\\composer\\ScriptHandler::postUpdatePackage"
        ]
    },
    "extra": {
        "composer-exit-on-patch-failure": true,
        "patchLevel": {
            "drupal/core": "-p2"
        },
        "patches-file": "patches/composer.patches.json",
        "installer-types": [
            "drupal-custom-component",
            "drupal-custom-component-components"
        ],
        "installer-paths": {
            "web/core": ["type:drupal-core"],
            "web/libraries/{$name}": [
                "type:drupal-library"
            ],
            "web/modules/contrib/{$name}": ["type:drupal-module"],
            "web/modules/custom/{$name}": ["type:drupal-custom-module"],
            "web/profiles/contrib/{$name}": ["type:drupal-profile"],
            "web/profiles/custom/{$name}": ["type:drupal-custom-profile"],
            "web/themes/contrib/{$name}": ["type:drupal-theme"],
            "web/themes/custom/{$name}": ["type:drupal-custom-theme"],
            "drush/Commands/{$name}": ["type:drupal-drush"],
            "web/components": ["type:drupal-custom-component"],
            "web/components/src/{$name}": ["type:drupal-custom-component-components"]
        },
        "drupal-scaffold": {
            "locations": {
                "web-root": "./web"
            },
            "gitignore": false,
            "allowed-packages": [
                "pantheon-systems/drupal-integrations"
            ],
            "file-mapping": {
                "[project-root]/.csslintrc": "web/core/assets/scaffold/files/csslintrc",
                "[project-root]/.eslintignore": "web/core/assets/scaffold/files/eslintignore",
                "[project-root]/.eslintrc.json": "web/core/assets/scaffold/files/eslintrc.json",
                "[project-root]/example.gitignore": "web/core/assets/scaffold/files/example.gitignore",
                "[web-root]/.csslintrc": false,
                "[web-root]/.eslintignore": false,
                "[web-root]/.eslintrc.json": false,
                "[web-root]/example.gitignore": false,
                "[web-root]/robots.txt": false,
                "[web-root]/sites/development.services.yml": false
            }
        },
        "drush": {
            "services": {
                "drush.services.yml": "^9"
            }
        }
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
drupal/entity_browser is required both in require and require-dev, this can lead to unexpected behavior
require.composer/installers : exact version constraints (1.9.0) should be avoided if the package follows semantic versioning
require.cweagans/composer-patches : exact version constraints (1.7.0) should be avoided if the package follows semantic versioning
require.drupal/core : exact version constraints (9.4.5) should be avoided if the package follows semantic versioning
require.drupal/core-composer-scaffold : exact version constraints (9.4.5) should be avoided if the package follows semantic versioning
require.drush/drush : exact version constraints (10.3.6) should be avoided if the package follows semantic versioning
require.oomphinc/composer-installers-extender : exact version constraints (2.0.0) should be avoided if the package follows semantic versioning
require.pantheon-systems/drupal-integrations : exact version constraints (9.0.0) should be avoided if the package follows semantic versioning
require.ckeditor/resize : exact version constraints (4.19.0) should be avoided if the package follows semantic versioning
require.ckeditor-plugin/wordcount : exact version constraints (1.17.9) should be avoided if the package follows semantic versioning
require.select2/select2 : exact version constraints (4.0.13) should be avoided if the package follows semantic versioning
require.drupal/address : exact version constraints (1.11) should be avoided if the package follows semantic versioning
require.drupal/admin_toolbar : exact version constraints (3.1.1) should be avoided if the package follows semantic versioning
require.drupal/advagg : exact version constraints (5.0) should be avoided if the package follows semantic versioning
require.drupal/allowed_formats : exact version constraints (1.5) should be avoided if the package follows semantic versioning
require.drupal/auto_entitylabel : exact version constraints (3.0-beta4) should be avoided if the package follows semantic versioning
require.drupal/better_exposed_filters : exact version constraints (5.2) should be avoided if the package follows semantic versioning
require.drupal/captcha : exact version constraints (1.4) should be avoided if the package follows semantic versioning
require.drupal/ckeditor_resize : exact version constraints (1.3) should be avoided if the package follows semantic versioning
require.drupal/ckwordcount : exact version constraints (1.5) should be avoided if the package follows semantic versioning
require.drupal/cdn : exact version constraints (3.5) should be avoided if the package follows semantic versioning
require.drupal/config_filter : exact version constraints (2.4) should be avoided if the package follows semantic versioning
require.drupal/config_override_warn : exact version constraints (1.3) should be avoided if the package follows semantic versioning
require.drupal/config_rewrite : exact version constraints (1.5) should be avoided if the package follows semantic versioning
require.drupal/config_split : exact version constraints (2.0.0-rc3) should be avoided if the package follows semantic versioning
require.drupal/content_lock : exact version constraints (2.2) should be avoided if the package follows semantic versioning
require.drupal/contextual_range_filter : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.drupal/consumers : exact version constraints (1.13) should be avoided if the package follows semantic versioningrequire.drupal/csv_serialization : exact version constraints (2.1) should be avoided if the package follows semantic versioning
require.drupal/ctools : exact version constraints (3.10) should be avoided if the package follows semantic versioning
require.drupal/devel : exact version constraints (4.1.5) should be avoided if the package follows semantic versioning
require.drupal/devel_entity_updates : exact version constraints (3.0.1) should be avoided if the package follows semantic versioning
require.drupal/diff : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.drupal/dynamic_entity_reference : exact version constraints (2.0-alpha19) should be avoided if the package follows semantic versioning
require.drupal/editor_advanced_link : exact version constraints (2.0) should be avoided if the package follows semantic versioning
require.drupal/entityqueue : exact version constraints (1.2) should be avoided if the package follows semantic versioning
require.drupal/entity_browser : exact version constraints (2.8) should be avoided if the package follows semantic versioning
require.drupal/entity_browser_enhanced : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.drupal/entity_reference_revisions : exact version constraints (1.10) should be avoided if the package follows semantic versioning
require.drupal/entity_usage : exact version constraints (2.0-beta6) should be avoided if the package follows semantic versioning
require.drupal/field_group : exact version constraints (3.2) should be avoided if the package follows semantic versioning
require.drupal/file_delete : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.drupal/file_mdm : exact version constraints (2.4) should be avoided if the package follows semantic versioning
require.drupal/flag : exact version constraints (4.0-beta3) should be avoided if the package follows semantic versioningrequire.drupal/google_tag : exact version constraints (1.5) should be avoided if the package follows semantic versioningrequire.drupal/hook_event_dispatcher : exact version constraints (3.2.0) should be avoided if the package follows semantic versioning
require.drupal/image_effects : exact version constraints (3.3) should be avoided if the package follows semantic versioning
require.drupal/imagecache_external : exact version constraints (3.0) should be avoided if the package follows semantic versioning
require.drupal/imce : exact version constraints (2.4) should be avoided if the package follows semantic versioning
require.drupal/instapage : exact version constraints (3.0.1) should be avoided if the package follows semantic versioning
require.drupal/jsonapi_extras : exact version constraints (3.21) should be avoided if the package follows semantic versioning
require.drupal/jwt : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.drupal/key : exact version constraints (1.15) should be avoided if the package follows semantic versioning
require.drupal/language_access : exact version constraints (1.7) should be avoided if the package follows semantic versioning
require.drupal/linkchecker : exact version constraints (1.0-beta5) should be avoided if the package follows semantic versioning
require.drupal/linkit : exact version constraints (6.0.0-beta3) should be avoided if the package follows semantic versioning
require.drupal/login_security : exact version constraints (2.0) should be avoided if the package follows semantic versioning
require.drupal/masquerade : exact version constraints (2.0-beta4) should be avoided if the package follows semantic versioning
require.drupal/media_library_edit : exact version constraints (2.3) should be avoided if the package follows semantic versioning
require.drupal/metatag : exact version constraints (1.21) should be avoided if the package follows semantic versioning
require.drupal/migrate_plus : exact version constraints (5.3) should be avoided if the package follows semantic versioning
require.drupal/migrate_tools : exact version constraints (5.1) should be avoided if the package follows semantic versioning
require.drupal/minifyjs : exact version constraints (2.2) should be avoided if the package follows semantic versioning
require.drupal/module_missing_message_fixer : exact version constraints (2.0.2) should be avoided if the package follows semantic versioning
require.drupal/mtcaptcha : exact version constraints (6.1) should be avoided if the package follows semantic versioning
require.drupal/name : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/node_edit_protection : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.drupal/node_revision_delete : exact version constraints (1.0-rc5) should be avoided if the package follows semantic versioning
require.drupal/notification : exact version constraints (1.1) should be avoided if the package follows semantic versioning
require.drupal/page_manager : exact version constraints (4.0-beta6) should be avoided if the package follows semantic versioning
require.drupal/panels : exact version constraints (4.6) should be avoided if the package follows semantic versioning
require.drupal/pantheon_advanced_page_cache : exact version constraints (2.0) should be avoided if the package follows semantic versioning
require.drupal/paragraphs : exact version constraints (1.14) should be avoided if the package follows semantic versioning
require.drupal/pathauto : exact version constraints (1.11) should be avoided if the package follows semantic versioning
require.drupal/pdb : exact version constraints (1.x-dev@dev) should be avoided if the package follows semantic versioning
require.drupal/permissions_filter : exact version constraints (1.3) should be avoided if the package follows semantic versioning
require.drupal/queue_ui : exact version constraints (3.1) should be avoided if the package follows semantic versioning
require.drupal/quick_node_clone : exact version constraints (1.15) should be avoided if the package follows semantic versioning
require.drupal/range : exact version constraints (1.4) should be avoided if the package follows semantic versioning
require.drupal/readonlymode : exact version constraints (1.1) should be avoided if the package follows semantic versioning
require.drupal/redirect : exact version constraints (1.7) should be avoided if the package follows semantic versioning
require.drupal/redis : exact version constraints (1.5) should be avoided if the package follows semantic versioning
require.drupal/robotstxt : exact version constraints (1.4) should be avoided if the package follows semantic versioning
require.drupal/role_delegation : exact version constraints (1.2) should be avoided if the package follows semantic versioning
require.drupal/remote_stream_wrapper : exact version constraints (2.0) should be avoided if the package follows semantic versioning
require.drupal/remote_stream_wrapper_widget : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/reroute_email : exact version constraints (2.1.1) should be avoided if the package follows semantic versioning
require.drupal/restui : exact version constraints (1.21) should be avoided if the package follows semantic versioning
require.drupal/salesforce : exact version constraints (5.0.0) should be avoided if the package follows semantic versioning
require.drupal/schema_metatag : exact version constraints (2.3) should be avoided if the package follows semantic versioning
require.drupal/search_api : exact version constraints (1.25) should be avoided if the package follows semantic versioning
require.drupal/search_api_autocomplete : exact version constraints (1.6) should be avoided if the package follows semantic versioning
require.drupal/search_api_solr : exact version constraints (4.2.8) should be avoided if the package follows semantic versioning
require.drupal/seckit : exact version constraints (2.0.0) should be avoided if the package follows semantic versioning
require.drupal/select2 : exact version constraints (1.13) should be avoided if the package follows semantic versioning
require.drupal/scheduler : exact version constraints (1.4) should be avoided if the package follows semantic versioning
require.drupal/scheduler_content_moderation_integration : exact version constraints (1.4) should be avoided if the package follows semantic versioning
require.drupal/simple_oauth : exact version constraints (5.2.0) should be avoided if the package follows semantic versioning
require.drupal/siteimprove : exact version constraints (1.12) should be avoided if the package follows semantic versioning
require.drupal/smtp : exact version constraints (1.1) should be avoided if the package follows semantic versioning
require.drupal/stripe : exact version constraints (1.0) should be avoided if the package follows semantic versioning
require.drupal/subpathauto : exact version constraints (1.2) should be avoided if the package follows semantic versioning
require.drupal/term_reference_tree : exact version constraints (1.x-dev) should be avoided if the package follows semantic versioning
require.drupal/token : exact version constraints (1.11) should be avoided if the package follows semantic versioning
require.drupal/transliterate_filenames : exact version constraints (2.0.1) should be avoided if the package follows semantic versioning
require.drupal/typed_data : exact version constraints (1.0-beta1) should be avoided if the package follows semantic versioning
require.drupal/ultimate_cron : exact version constraints (2.0-alpha5) should be avoided if the package follows semantic versioning
require.drupal/views_bulk_operations : exact version constraints (4.1.4) should be avoided if the package follows semantic versioning
require.drupal/views_data_export : exact version constraints (1.1) should be avoided if the package follows semantic versioning
require.drupal/votingapi : exact version constraints (3.0-beta3) should be avoided if the package follows semantic versioning
require.drupal/xmlsitemap : exact version constraints (1.2) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK git version 2.30.2
Checking http connectivity to packagist: A connection timeout was encountered. If you intend to run Composer without connecting to the internet, run the command again prefixed with COMPOSER_DISABLE_NETWORK=1 to make Composer run in offline mode.
FAIL
The following exception probably indicates you have misconfigured DNS resolver(s)
[Composer\Downloader\TransportException] curl error 28 while downloading http://repo.packagist.org/packages.json: Resolving timed out after 10000 milliseconds
Checking https connectivity to packagist: FAIL
The following exception probably indicates you have misconfigured DNS resolver(s)
[Composer\Downloader\TransportException] curl error 28 while downloading https://repo.packagist.org/packages.json: Resolving timed out after 10000 milliseconds
Checking github.com oauth access: FAIL
[Composer\Downloader\TransportException] curl error 28 while downloading https://api.github.com/: Resolving timed out after 10000 milliseconds
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
[Composer\Downloader\TransportException] curl error 28 while downloading https://getcomposer.org/versions: Resolving timed out after 10000 milliseconds
Composer version: 2.4.2
PHP version: 7.4.29
PHP binary path: /usr/local/bin/php
OpenSSL version: OpenSSL 1.1.1n  15 Mar 2022
cURL version: 7.74.0 libz 1.2.11 ssl OpenSSL/1.1.1n
zip: extension present, unzip present, 7-Zip not available
```

When I run this command:

```
composer install --no-dev -vvv
```

I get the following output: 

![composer-download-ctrlc-fail](https://user-images.githubusercontent.com/696005/195453720-19d3b471-e736-40fb-8691-3c39c2ae3f0c.PNG)
![composer-login-ctrlc-fail](https://user-images.githubusercontent.com/696005/195453732-6654bec3-08e0-4bd0-af63-9b9ed6c29329.png)

And I expected this to happen:

Composer process to exit.

**Comment by Seldaek** [comment] 2022-10-13 10:02
Well this is odd for sure..

Works for me:

```
  - Downloading behat/mink (v1.10.0)
  - Downloading friends-of-behat/mink-browserkit-driver (v1.6.1)
  - Downloading easyrdf/easyrdf (1.1.1)
  - Downloading phpstan/phpdoc-parser (1.8.0)
  - Downloading slevomat/coding-standard (8.5.2)
  - Downloading sirbrillig/phpcs-variable-analysis (v2.11.9)
  - Syncing drupal/coder (8.3.16) into cache
^C
```

And I run this in WSL2 + windows terminal too.

I do see in your diagnose output that you are getting timeouts, not sure if that is related.

**Comment by Seldaek** [comment] 2022-10-13 10:04
One thing to consider perhaps is how do you run composer? How was it installed? Can you show the output of `which composer && head -30 $(which composer)`

**Comment by Seldaek** [comment] 2024-09-20 11:59
Duplicate of #12106 I believe, as the OP was stuck in a prompt actually.

**Closed by Seldaek** 2024-09-20 11:59 UTC
