### ISSUE TITLE
why composer is no compatible with xdebug module? it not works when xdebug is enabled

### ISSUE THREAD

**Issue by chapgaga** [composer/composer#3965] opened 2015-04-26 14:11 UTC
i am using win7 x64 and my php is extracted from zip file, seems composer failed to launch
the command works after i disable xdebug module,
so why composer cannot work with xdebug enabled?

![]( http://img.itc.cn/photo/jf4uRdiVPVc.jpg)

http://img.itc.cn/photo/jf4uRdiVPVc.jpg

![](http://img.itc.cn/photo/jf4pxYicgtc.jpg)
http://img.itc.cn/photo/jf4pxYicgtc.jpg

**Comment by alcohol** [comment] 2015-04-28 06:41
It works for me with xdebug enabled. It just becomes incredibly slow. It is probably related to configuration that is specific to your environment. In other words, unless you can provide us with a way to reproduce this issue, please close it.

**Comment by stof** [comment] 2015-04-28 09:00
According to what I can see (I may be wrong though because of the language of your system in the screenshot), this looks like a segfault of PHP itself. Such errors are related to issues in PHP or its extensions themselves.

XDebug 2.2.6 and 2.2.7 have fixed several segfaults, so I suggest you to update your XDebug version to a newer one (you could even upgrade to XDebug 2.3.2).

**Closed** 2015-06-02 13:50 UTC
