### ISSUE TITLE
Recognize bin dir configuration changes.

### ISSUE THREAD

**Issue by dmolineus** [composer/composer#3392] opened 2014-11-04 08:40 UTC
When I change my bin dir configuration after installing some dependencies (which provides binaries) their binaries are not moved (unless they get updated).

I'd would be useful if it is always checked during `composer update`. An console command to recreate them (same as `dump-autoload`) would be an alternative.

**Comment by sp-gonzalo-serrano** [comment] 2015-02-23 14:55
I would also like to recreate the bin configuration since i'm trying to cache composer dependencies in travis but caching the vendor/ directory does not work since i don't have the bin directory populated yet.

**Comment by mbrevda** [comment] 2015-10-29 12:22
+1. When building a docker container off of a working directory, the `bin/` symlinks may be off, depending on the file structure of the container. Would be great to have a way to regenerate the `bin/` symlinks

**Comment by Seldaek** [comment] 2016-04-15 17:47
Closing as duplicate of #1209 (which has a fix in #5127 which I hope to merge soon btw).

**Closed by Seldaek** 2016-04-15 17:47 UTC
Labels: Bug, Feature
