### ISSUE TITLE
Scripts output different than it was for an old composer (1.1.1)

### ISSUE THREAD

**Issue by AdrianSkierniewski** [composer/composer#5937] opened 2016-12-03 11:01 UTC
Hi,

I recently updated composer to latest version (1.1.1 => 1.2.3), and I noticed one issue during running scripts. I'm using codeception to run my tests and I've put the command inside scripts to have a handy shortcut and unify it among all repositories.

```json
    "scripts": {
        "test": "./vendor/bin/codecept run"
    },
```

Before upgrading composer everything was displayed properly:

```
composer test
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> ./vendor/bin/codecept run
Codeception PHP Testing Framework v2.2.6
Powered by PHPUnit 5.7.1 by Sebastian Bergmann and contributors.

Unit Tests (127) --------------------------------------------------------------------------------------------------------------------------------
✔ ContentRepositoryTest: Can_filter_content_files_list (0.10s)
✔ OptionRepositoryTest: It_checks_existence_of_category_when_deleting_an_option (0.04s)
✔ FileRepositoryTest: Can_create_file_with_unique_name_if_file_name_is_already_taken (0.07s)
✔ OptionsServiceTest: Can_get_categories (0.05s)
✔ ContentRepositoryTest: It_does_not_allow_to_delete_active_translation (0.04s)
✔ ContentRepositoryTest: It_checks_for_empty_array_of_files_to_remove (0.06s)
✔ BlockFinderTest: It_finds_correct_block_for_static_pages (0.05s)
✔ ContentRepositoryTest: It_checks_existence_of_parent (0.06s)
```

But after upgrade it looks like it ignores \r or something like that in output:

```
composer test
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
> ./vendor/bin/codecept run
Codeception PHP Testing Framework v2.2.6
Powered by PHPUnit 5.7.1 by Sebastian Bergmann and contributors.


Unit Tests (127) -------------------------------------------------------------

- FileRepositoryTest: Can_create_file_without_author

✔ 
FileRepositoryTest: Can_create_file_without_author
 
(0.10s)


- ContentRepositoryTest: Can_update_content_file

✔ ContentRepositoryTest: Can_update_content_file
 
(0.09s)

- BlockRepositoryTest: Can_create_block_without_author

✔ 
BlockRepositoryTest: Can_create_block_without_author
 
(0.06s)

- ContentRepositoryTest: It_checks_if_parent_is_proper_type
```

When I'm running codeception manually I'm getting correct results.

**Comment by AdrianSkierniewski** [comment] 2016-12-03 11:16
It looks like duplicated to #5936

**Comment by alcohol** [comment] 2016-12-03 23:30
Yea duplicate of #5933

**Closed by alcohol** 2016-12-03 23:30 UTC
