### ISSUE TITLE
SHA256 mismatch during installation via brew on Mac

### ISSUE THREAD

**Issue by fds-github** [composer/composer#12012] opened 2024-06-13 08:48 UTC
Like #9764 I get a SHA256 mismatch running "brew install composer":

`==> Downloading https://getcomposer.org/download/2.7.7/composer.phar ############################################################################################################################################################# 100.0%
Error: composer: SHA256 mismatch
Expected: 06e4c4bc6d32b8975174f4f4a0a93476d8907da92a1484c5a8ef138897a760e1
  Actual: aab940cd53d285a54c50465820a2080fcb7182a4ba1e5f795abfb10414a4b4be
    File: /Users/Stephen/Library/Caches/Homebrew/downloads/3b16a80d0e8819859d9ffd927146c8c2206f5968c131606db0c9d74fb08af3f9--composer.phar`

**Comment by pierres** [comment] 2024-06-13 12:26
If the release was intentionally replaced, it would be great if a new one (e.g. 2.7.8) could be created. This would spare us some investigation to verify that there was no malicious code injection.

**Comment by fredden** [comment] 2024-06-13 12:34
This looks like a duplicate of https://github.com/composer/composer/issues/12009

**Comment by fds-github** [comment] 2024-06-13 12:50
#12009 has been closed.  I have no clue of machinations between the issue being closed and "brew install composer" working for me.   Is there something I should do, or do I have to wait for the developers to release something?

**Comment by Seldaek** [comment] 2024-06-14 08:47
Yeah sorry I think by fixing #12009 I actually caused this one. I'm guessing brew hardcodes the hash on their end and they would need to replace it with the new one to fix this. Sorry about that.. But you can verify the new file is signed by me by doing `composer self-update 2.7.7`, as that verifies the signatures before completing the update.

**Closed** 2024-06-24 08:58 UTC

**Comment by vojtech-dobes** [comment] 2024-07-02 06:13
Unfortunately I have to report that I can't even install Composer via `brew`, getting the same error as reported above:

```console
$ brew install composer
==> Fetching composer
Warning: Building composer from source:
  The bottle (and many others) needs to be installed into /opt/homebrew.

==> Downloading https://raw.githubusercontent.com/Homebrew/homebrew-core/189bfaf275e572a59836f5e8030f606501ad851d/Formula/c/composer.rb
Already downloaded: /Users/vojtechdobes/Library/Caches/Homebrew/downloads/c1649faa832601f789c1ffa37de5bf912abc1f14bca9cbbdd9146e8bfba42562--composer.rb
==> Downloading https://getcomposer.org/download/2.7.7/composer.phar
Already downloaded: /Users/vojtechdobes/Library/Caches/Homebrew/downloads/3b16a80d0e8819859d9ffd927146c8c2206f5968c131606db0c9d74fb08af3f9--composer.phar
Error: composer: SHA256 mismatch
Expected: 06e4c4bc6d32b8975174f4f4a0a93476d8907da92a1484c5a8ef138897a760e1
  Actual: aab940cd53d285a54c50465820a2080fcb7182a4ba1e5f795abfb10414a4b4be
    File: /Users/vojtechdobes/Library/Caches/Homebrew/downloads/3b16a80d0e8819859d9ffd927146c8c2206f5968c131606db0c9d74fb08af3f9--composer.phar
To retry an incomplete download, remove the file above.
```

**Comment by Seldaek** [comment] 2024-07-06 20:11
Fixed now https://github.com/Homebrew/homebrew-core/pull/176539/files

**Comment by fds-github** [comment] 2024-07-11 14:58
I can confirm that I was now able to install composer.  Thank you.
