### ISSUE TITLE
`composer update` does not update local repository paths in composer.lock

### ISSUE THREAD

**Issue by imliam** [composer/composer#8473] opened 2019-12-09 23:15 UTC
When using a local path repository in composer.json, running the `install` or `update` command will add the repository path to the composer.lock file as expected.

Example `composer.json`:

```json
{
    "repositories": [
        {
            "type": "path",
            "url": "./example-a/"
        }
    ],
    "require-dev": {
        "test/example-a": "dev-master"
    }
}
```

However, after changing the path in the composer.json file:

```diff
-            "url": "./example-a/"
+            "url": "./example-b/"
```

And running the `composer update` command, the path in the composer.lock file remains `./example-a/`, not updating to match the JSON file.

I'm not sure if this is a bug or just confusing behaviour, but it seems like the former. It's pretty confusing seeing the JSON file look correct, but no commands actually commit that change back to the lockfile without deleting it and running `composer install` again.

**Comment by Seldaek** [comment] 2019-12-13 15:19
Might/should be fixed by existing changes in 2.0 branch, if not we'll have to address it then, but not worth fixing for v1 anymore.

**Comment by adrianosferreira** [comment] 2020-01-10 20:37
@Seldaek sadly I've spent many hours fixing it on v1 and then saw your message :(
https://github.com/composer/composer/pull/8523/

Now, after checking out the v2 the issue is already solved there.
I will remember to read all the comments before start debugging...

**Comment by Seldaek** [comment] 2020-01-10 21:14
👍 sorry your wasted time on this but also thanks for confirming it's fixed there, closing this then.

**Closed by Seldaek** 2020-01-10 21:14 UTC
Labels: Bug

**Comment by adrianosferreira** [comment] 2020-01-10 21:19
@Seldaek since you are here (feel free to delete this commit). I've pushed a couple of PR for Composer / Semver, do I need to do anything else to move it forward?

https://github.com/composer/composer/pull/8520
https://github.com/composer/composer/pull/8517
https://github.com/composer/semver/pull/76

**Comment by Seldaek** [comment] 2020-01-10 21:31
@adrianosferreira I'll get to them eventually, sorry for the delay but holidays & co, busy times, please be patient :)

**Comment by adrianosferreira** [comment] 2020-01-10 21:32
@Seldaek no problem at all! Just wondering if I should have mentioned someone in particular. Thanks!
