### ISSUE TITLE
Composer cannot find some versions of some packages

### ISSUE THREAD

**Issue by emodric** [composer/composer#4480] opened 2015-10-05 13:10 UTC
I'm using the following `composer.json`

```json
{
    "require": {
        "ezsystems/comments-bundle": "v2014.11.0"
    }
}
```
`composer install` returns the following error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package ezsystems/comments-bundle could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

`composer show ezsystems/comments-bundle v2014.11.0` also throws `InvalidArgumentException` with `Package ezsystems/comments-bundle not found` message while `composer show ezsystems/comments-bundle` has the following output:

```
name     : ezsystems/comments-bundle
descrip. : Commenting system for eZ Publish
keywords : 
versions : dev-master, v2014.11.0, v2014.07.0, v2014.05.0, v2014.03.1, v2014.01.1, v2013.09.0, v2013.07.0, 6.0.x-dev, v6.0.0-alpha5, v6.0.0-alpha3, v6.0.0-alpha1, 5.4.x-dev, v5.4.2, v5.4.0, v5.4.0-rc2, v5.4.0-rc1, v5.4.0-beta1, 5.3.x-dev, v5.3.2, v5.3.2-rc1, v5.3.0, v5.2.0, v5.2.0-beta1, dev-ezp24869-viewController_refactoring
type     : library
license  : GNU General Public License v2.0 only (GPL-2.0) (OSI approved) https://spdx.org/licenses/GPL-2.0.html#licenseText
source   : [git] https://github.com/ezsystems/CommentsBundle.git ad72e3c09b42074e2c2ee0fb9ae627eefd553bf4
dist     : [zip] https://api.github.com/repos/ezsystems/CommentsBundle/zipball/ad72e3c09b42074e2c2ee0fb9ae627eefd553bf4 ad72e3c09b42074e2c2ee0fb9ae627eefd553bf4
names    : ezsystems/comments-bundle

autoload
psr-0
EzSystems\CommentsBundle => .

requires
symfony-cmf/routing ~1.1
ezsystems/ezpublish-kernel ~6.0@dev

requires (dev)
phpunit/phpunit ~4.1.3
matthiasnoback/symfony-dependency-injection-test 0.*

suggests
ezsystems/ngsymfonytools-bundle Needed for use with legacy backend tab for administration of comments
```

**Comment by alcohol** [comment] 2015-10-05 14:45
Uh... what kind of a versioning schema is that.

This might be related to the changes in `composer/semver`. I have no idea. Just use one of their newer normal versions.

**Comment by emodric** [comment] 2015-10-05 14:58
@alcohol You should ask eZ Systems :) One of the "normal versions" can technically be used, but they are mostly used for enterprise versions of eZ Publish, which are not publicly available.

Besides, what is really different between 2014.11.0 and 5.4.0 ? They're both versions in major.minor.patch format, are they not?

But what does that have to do with this issue? The point is that the specific existing tag cannot be resolved. This worked fine until couple of weeks ago: for example, it works with `1.0-dev (f1aa655e6113e0efa979b8b09d7951a762eaa04c) 2015-08-20 11:59:54`, but not with latest available.

**Comment by alcohol** [comment] 2015-10-05 14:58
I think it's because it is now just considered classical versioning, whereas before it was considered some sort of date'ish version. Even though 2014.11.0 is not a valid date. So yeah... not sure what to do about that. Don't really see a point in reverting those changes. Might just need a refresh of the composer providers file stuff (which is hosted on packagist, I can't refresh that for you unfortunately).

**Comment by emodric** [comment] 2015-10-05 15:03
Well, this will not affect just me. This will affect eZ Publish community as well, so this should be considered/fixed somehow.

What are the changes exactly in `composer/semver`? Technically, I see no reason why `2014.11.0` wouldn't work with classical versioning? Maybe `2014` number is just too long?

**Comment by alcohol** [comment] 2015-10-05 15:06
The thing is that 2014.11.0 was normalized as a date before, so that becomes 2014-11-0. Now it's just classical versioning which is normalized to 2014.11.0.0. I don't know if this normalized value is actually relevant, but that is the only difference I can think of/spot right now. It is metadata in the package.json that is hosted on packagist, so I imagine there is a fair chance that it is relevant.

**Comment by emodric** [comment] 2015-10-05 15:15
Okay, that makes sense. Who can refresh packagist.org metadata to see if that fixes the problem? I know @seldaek can, but I presume he's too busy :)

**Comment by alcohol** [comment] 2015-10-05 15:17
He's travelling right now. If he has a free night and wifi, he might be able to have a look at it. But I cannot make any promises or guarantees. On the short term, I can't think of what the best solution would be for now. You could use a composer version from before the semver changes. It's not ideal, but it will allow you to get back to work.

**Comment by emodric** [comment] 2015-10-05 15:22
Okay, thanks! I'll revert to version from August above and give it to my client.

If the metadata refresh doesn't help, what then? Besides eZ Systems having to retag their entire codebase? :)

Ping @andrerom @lolautruche @bdunogier

**Comment by alcohol** [comment] 2015-10-05 15:25
If that doesn't help we can revert a specific change in semver that should resolve this. But I want to be sure that that is the root cause, before actually doing so. Also I need to figure out what the impact of reverting that change will be. Cause it might mean that other versions that are now correctly considered 'classical versioning', will then suddenly again be considered 'date versioning', which might result in recently created tags not being recognised **again**.

**Comment by emodric** [comment] 2015-10-05 15:28
Understood. If you need someone to test, I'm available :)

**Comment by pborreli** [comment] 2015-10-05 16:30
had same issue, reverted to alpha10 composer bin https://getcomposer.org/download/1.0.0-alpha10/composer.phar fixed the issue temporarily while waiting for a bug fix.

**Comment by emodric** [comment] 2015-10-14 07:43
Hi!

Any news on this issue?

**Comment by alcohol** [comment] 2015-10-14 08:08
Not as of yet, but @seldaek is back so we might have a chance to look into this this week.

**Comment by emodric** [comment] 2015-10-14 21:27
Alright, thanks!

**Comment by Seldaek** [comment] 2015-10-15 18:17
So yes the problem is indeed that the normalization isn't consistent anymore, and since we ship normalized version from packagist to composer to save some CPU time normalizing things client side, that means exact requirements like this will stop working. I can fix them on packagist's end, but then old composer clients will start failing. 

So either we revert this change in semver and call it a day, or we move forward and clean things up but break old client in this edge case. There are only 394 versions from 50 packages using this versioning scheme so it's  not widespread and as far as I can see it only is a problem if you require a specific version. 

If we decide for the latter, I'll just run an update of those 50 packages to make sure their versions are normalized according to the new rules.

**Comment by emodric** [comment] 2015-10-15 18:28
Thanks @seldaek for detailed explanation.

If it means anything, I vote for normalizing without changes to semver :)

**Comment by alcohol** [comment] 2015-10-16 11:18
Well, bummer. Did not really see that coming, sorry.

@Seldaek let me know how you want to proceed. And just out of curiousity, can you check how many packages still use "valid" date versions? I'm wondering if perhaps it might be more convenient to just normalize everything as classical versioning (that would require 1 more change in `composer/semver` though).

**Comment by Seldaek** [comment] 2015-10-16 15:18
OK so overall yes I'd also vote for updating them all. @alcohol I'm not sure what you mean there though, by valid date versions?

**Comment by alcohol** [comment] 2015-10-16 15:20
@Seldaek there is still this block: https://github.com/composer/semver/blob/master/src/VersionParser.php#L124-L128

Which normalizes the version to 'yyyy-mm-dd' (dashes, not dots, and only 3 identifiers, not 4).

**Comment by emodric** [comment] 2015-10-16 15:22
@alcohol When is that supposed to fire if `2014.11.0` matches the classic versioning?

**Comment by alcohol** [comment] 2015-10-16 15:23
It fires for `v2014-11-0` for example.

**Comment by emodric** [comment] 2015-10-16 15:27
Convenience? With `v2014.11.0` being normalized to date, you can't use `~` operator which may be confusing to newcomers. It was to me two years back :)

**Comment by Seldaek** [comment] 2015-10-16 15:32
Oh those yyyy-mm-dd were including my 50package number above. I just searched for anything matching `\d{4}-` in the normalized form (as it still uses the old normalization, 2014.11.0 becomes 2014-11-00)

**Comment by alcohol** [comment] 2015-10-16 15:33
Convenience? I'm not sure I understand :-(

**Comment by alcohol** [comment] 2015-10-16 15:34
Why wouldn't ~ or ^ work with yyyy-mm-dd? It's not so different from major.minor.patch?

**Comment by emodric** [comment] 2015-10-16 15:39
It didn't before. But I haven't tried it in a long time, so maybe stuff changed :)

You couldn't do `~2014.11.0` for example, to only get patch releases of 2014.11.

**Comment by alcohol** [comment] 2015-10-16 15:41
Sorry I mean, that should be doable if we normalize everything as classical versioning. I was basically suggesting to completely drop normalizing to a date(time) string, ever.

**Comment by emodric** [comment] 2015-10-16 15:45
Ah, so we misunderstood each other then :)

It seems that all three of us agree :)

**Comment by alcohol** [comment] 2015-10-16 15:47
Do we? Cause my suggestion goes a bit beyond what @seldaek suggested. So I'm not sure about that. Either way, I'm also fine with just updating the packages on packagist.

**Comment by emodric** [comment] 2015-10-16 15:53
I know, and I'm fine with that change, considering that only 50 packages are using either `yyyy-mm-dd` or `yyyy.mm.dd`.

**Comment by emodric** [comment] 2015-10-16 15:53
I'm fine going beyond what @seldaek suggested, that is.

**Comment by Seldaek** [comment] 2015-10-24 13:14
Yeah I'd be ok with it too I think, do you wanna do those changes to semver @alcohol? I might as well update packagist all at once.

**Comment by alcohol** [comment] 2015-10-24 16:27
Sure, I'll get it done tomorrow.

**Comment by gggeek** [comment] 2015-11-05 10:09
Not 100% sure I get all the details / usecases / consequences, but I vote for normalizing everything as version number instead of date...

**Comment by emodric** [comment] 2015-11-05 10:16
Now that semver PR is merged, can we know the timeframe when packagist update will be done?

**Comment by alcohol** [comment] 2015-11-05 10:27
I think @seldaek wants to update packagist as soon as we release alpha11.

**Comment by Seldaek** [comment] 2015-11-10 15:40
Should be fixed now (if you have latest composer, older composer versions will start breaking with those exact requires of date versions I'm afraid)

**Closed by Seldaek** 2015-11-10 15:40 UTC
Labels: Bug, Support

**Comment by emodric** [comment] 2015-11-10 15:42
@Seldaek @alcohol Testing now! :)

**Comment by emodric** [comment] 2015-11-10 15:58
It works fine.

I tested with `composer.json` from the issue description as well as with `~2014.11` and `^2014.11`.
