### ISSUE TITLE
Version conflict checks dev-master instead of concrete revision

### ISSUE THREAD

**Issue by Koc** [composer/composer#4614] opened 2015-11-17 10:53 UTC
```json
    "require": {
        "php": ">=5.3.8",
        "symfony/symfony": "2.5.*",
        "excelwebzone/recaptcha-bundle": "dev-master#60303ddc3feec3a7a6f34fa44ed8149d48ab20bc"
    }
```

As you see from https://github.com/excelwebzone/EWZRecaptchaBundle/blob/60303ddc3feec3a7a6f34fa44ed8149d48ab20bc/composer.json this revision require Symfony ~2.4 but I couldn't do update because version solver checks dependencies from master branch, not at specified revision

**Comment by Koc** [comment] 2015-11-17 11:19
workaround: fork original repo, strip it to 60303ddc3feec3a7a6f34fa44ed8149d48ab20bc revision and use own repository

**Comment by stof** [comment] 2015-11-17 12:32
@Koc I suggest you to check all previous issues related to this. This is known and cannot change: the revision hash in the constraint is an **installer** hack to force it to install a different commit than the one referenced on Packagist (and it works only for source installs or github repositories btw).
The solver does not take it into account, because it cannot get metadata for this particular commit: Packagist does not store them for each commit (and it won't, unless you want to run composer with 1 TB RAM for the solver).

This feature was added in composer at a time where partial updates were not available, but it never worked in a satisfying way. My advice is to avoid it entirely. Use releases to keep it to an older version

**Comment by Koc** [comment] 2015-11-17 12:45
I cann't find related issues because don't know what to search. Looks like lack of documentation about limitations of this feature.

**Comment by stof** [comment] 2015-11-17 14:01
@Koc this is explicitly documented in the doc showing this feature: https://getcomposer.org/doc/04-schema.md#package-links (scroll down a bit as there is no direct link to the paragraph showing this constraint)

**Comment by alcohol** [comment] 2015-11-17 14:58
Duplicate of many duplicate issues, closing :)

**Closed by alcohol** 2015-11-17 14:58 UTC
