### ISSUE TITLE
Weird php-version-related composer install issue

### ISSUE THREAD

**Issue by marcomenzel** [composer/composer#5228] opened 2016-04-21 13:45 UTC
We got some weird `composer install` issue. The main problem is, that we cannot provide a reproducible bug description, because it's all about private repositories :(.
I'll try to explain it as exact as possible.

We got no .lock-File, just a composer.json. It contains something like this:

```
"require": {
  "bla/geniuspackage": ">=1.0.5",
  "maglnet/magl-legacy-application": "^1.5",
  "bla/coolpackage": "^1.0",
  "bla/awesomepackage": "1.0.x-dev",
  "ramsey/uuid-doctrine": "^1.2"
}
```

The installation breaks with the following output:

```
composer install                                                                                                                                                     
Loading composer repositories with package information                                                                                                                 
Updating dependencies (including require-dev)                                                                                                                          
Your requirements could not be resolved to an installable set of packages.                                                                                             

  Problem 1                                                                                                                                                            
    - bla/coolpackage 1.0.0 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - bla/coolpackage 1.0.1 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - bla/coolpackage 1.1.0 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - bla/coolpackage 1.1.1 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - bla/coolpackage 1.1.2 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - bla/coolpackage 1.1.3 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - bla/coolpackage 1.1.4 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - bla/coolpackage 1.1.5 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - bla/coolpackage 1.1.6 requires bla/anothercoolpackage ^1.0 -> satisfiable by bla/anothercoolpackage[1.0.0].                                               
    - Conclusion: don't install bla/anothercoolpackage 1.0.0                                                                                                            
    - Installation request for bla/coolpackage ^1.0 -> satisfiable by bla/coolpackage[1.0.0, 1.0.1, 1.1.0, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.5, 1.1.6].
```

It happens with the following setup:
Installing with PHP 5.6, composer 1.0.1 doesn't work
Installing with PHP 5.5, composer 1.0.1 doesn't work
Installing with PHP 5.4, composer 1.0.1 and `config platform.php 5.5` doesn't work
Installing with PHP 5.4, composer 1.0.1 and `config platform.php 5.6` doesn't work

But:
Installing with PHP 5.6, composer 1.0.1 and `config platform.php 5.4` works fine
Installing with PHP 5.4, composer 1.0.1 works fine, too

After installing with a working command, like `composer install` with PHP 5.4, it is possible to do a `composer install` even with PHP 5.5 and PHP 5.6 when we can use the previously generated .lock-File.

The whole installation process works with PHP 5.5 and PHP 5.6 without a .lock-File if we remove ANY dependency.
The whole installation process works with PHP 5.5 and PHP 5.6 if we change the constraint `"bla/coolpackage": "^1.0"` to `"bla/coolpackage": ">1.0"`. It doesn't works with `"bla/coolpackage": "^1.0|>1.0"`.

Another thing, `bla/coolpackage` requires `"zendframework/zendframework": ">2.4,<2.5"`.
If we require `"zendframework/zendframework": ">2.4,<2.5"` in our package too, the whole install process works with PHP 5.4, 5.5, 5.6!

If we `composer install` with PHP 5.4 and then `composer update` with PHP 5.6 it works, too.

Craziest thing so far. If we do an `composer require roave/security-advisories:dev-master` and then `composer install` with PHP 5.6 - It works. WTF? These package has no requirements, just a `conflicts`-Node.

I don't know what is broken in here. 
Is there any way for me to provide useful further information.

//cc @maglnet

**Comment by Seldaek** [comment] 2016-04-21 13:57
Ouch, this sounds like either you missed something silly or we have a really bad edge case bug :) Not so sure what more you can do though.. After installing with 5.4 you could call `composer why-not php:5.5` or 5.6, maybe this hints at something?

**Comment by marcomenzel** [comment] 2016-04-21 14:06
Thanks for yourr quick look, @Seldaek!

Sadly, nothing new:
```
composer why-not php:5.5
There is no installed package depending on "php" in versions not matching 5.5

composer why-not php:5.6
There is no installed package depending on "php" in versions not matching 5.6
```
After looking into it with two other people, I would like to assume that we don't miss something obvious :fire_engine:

**Comment by curry684** [comment] 2016-04-21 14:32
You should be able to work around this with the `--ignore-platform-reqs` flag btw, worth a try.

For further debugging, can you c/p the full output of `composer why php`?

**Comment by marcomenzel** [comment] 2016-04-22 06:54
Executing an `composer install --ignore-platform-reqs` with PHP 5.4 fails with the same output.
I was using `config platform.php` to test if it makes any difference between installing with PHP 5.6 and not using `config platform.php` or installing with PHP 5.4 and using `config platform.php 5.6`. Both cases don't work. I tried that to determine if there's any relevance on the version of the executed PHP.
In my mind this means, we're not talking about some PHP incompatibilities between 5.4/5.5/5.6, but searching for a different handling while solving the dependencies.

btw, I'm now on composer 1.0.2, issue stays the same, just for information.

After `composer install`ing with PHP 5.4 I get the following output on `composer why php` (Not sure about if this is what @curry684 requested).
```
adodb/adodb-php                  v5.20.4  requires  php (>=5.3.2)
doctrine/annotations             v1.2.7   requires  php (>=5.3.2)
doctrine/cache                   v1.5.4   requires  php (>=5.3.2)
doctrine/collections             v1.3.0   requires  php (>=5.3.2)
doctrine/common                  v2.5.3   requires  php (>=5.3.2)
doctrine/dbal                    v2.5.4   requires  php (>=5.3.2)
doctrine/doctrine-module         0.9.0    requires  php (>=5.4)
doctrine/doctrine-orm-module     0.9.2    requires  php (>=5.4)
doctrine/inflector               v1.1.0   requires  php (>=5.3.2)
doctrine/instantiator            1.0.5    requires  php (>=5.3,<8.0-DEV)
doctrine/lexer                   v1.0.1   requires  php (>=5.3.2)
doctrine/orm                     v2.5.4   requires  php (>=5.4)
kriswallsmith/assetic            v1.2.1   requires  php (>=5.3.1)
maglnet/magl-legacy-application  1.5.1    requires  php (>=5.3.0)
paragonie/random_compat          v2.0.2   requires  php (>=5.2.0)
pimple/pimple                    v3.0.2   requires  php (>=5.3.0)
ramsey/uuid                      3.3.0    requires  php (>=5.4)
ramsey/uuid-doctrine             1.2.0    requires  php (>=5.4)
rwoverdijk/assetmanager          1.6.0    requires  php (>=5.3.3)
symfony/console                  v2.5.12  requires  php (>=5.3.3)
symfony/process                  v2.8.4   requires  php (>=5.3.9)
zendframework/zendframework      2.4.9    requires  php (>=5.3.23)
zendframework/zendxml            1.0.2    requires  php (^5.3.3 || ^7.0)
```

**Comment by curry684** [comment] 2016-04-22 09:06
Well nothing wrong there - got me stumped now  :open_mouth:

**Comment by Seldaek** [comment] 2016-04-22 09:09
If there was something obviously wrong it wouldn't fail in such weird ways :)

**Comment by naderman** [comment] 2016-04-22 22:03
This isn't going to help really debug this, but generally speaking don't run composer install without a lock file, while it will automatically create one, it's difficult to now understand if you reran composer install without deleting the lock file in between or not. Run composer update to generate or change a lock file, run composer install to sync your vendor directory with the lock file, that way it's clearer what is going on.

**Comment by naderman** [comment] 2016-04-22 22:06
I can't really see a way to debug this without seeing the details of all the different private packages's composer.jsons to see where the cause of this behaviour is. Maybe you can give me access to it to debug it somehow? Send me an email to naderman at naderman de if that's an option.

**Comment by marcomenzel** [comment] 2016-04-25 06:09
To pick up @naderman's line in https://github.com/composer/composer/issues/5228#issuecomment-213603775:
It doesn't change anything on the result running a `composer update`.

Talking about that, and I guess it's not only my understanding, I assumed that a `composer install` and `composer update` does the same thing, when there's no composer.lock.

Referring to https://github.com/composer/composer/issues/5228#issuecomment-213604678 this will have administrative barriers, bla ... ;-), but I'll try to build a publicly available project with the same construct of releases and tags which hopefully breaks, too.

However - thank you for taking a deeper look into my problem!

**Comment by naderman** [comment] 2016-04-27 12:59
They are mostly the same as of https://github.com/composer/composer/pull/5035 / https://github.com/composer/composer/commit/55b0ed8c8be74af348d9fec6702da3efd50feb46 but that's pretty recent and they're still not necessarily 100% the same.

**Comment by marcomenzel** [comment] 2016-05-04 06:43
As mentioned in https://github.com/composer/composer/issues/5250#issuecomment-216758793 after changing my origin composer.json from
```
"require": {
  "bla/geniuspackage": ">=1.0.5",
  "maglnet/magl-legacy-application": "^1.5",
  "bla/coolpackage": "^1.0",
  "bla/awesomepackage": "1.0.x-dev",
  "ramsey/uuid-doctrine": "^1.2"
}
```
to
```
"require": {
  "ramsey/uuid-doctrine": "^1.2",
  "bla/geniuspackage": ">=1.0.5",
  "maglnet/magl-legacy-application": "^1.5",
  "bla/coolpackage": "^1.0",
  "bla/awesomepackage": "1.0.x-dev"
}
```
everything is fine!

In my mind fixing #5250 will fix this issue, too - because it's just the same.
Propably we should put this issue (5228) on-hold, I didn't move forward about it.

**Comment by Seldaek** [comment] 2017-01-22 19:31
Closing as there isn't a clear action item here.

**Closed by Seldaek** 2017-01-22 19:31 UTC
Labels: Bug, Solver

**Comment by mhmohon** [comment] 2018-02-04 21:07
sddf
