### ISSUE TITLE
Composer update --no-dev attempting to resolve dev dependencies.

### ISSUE THREAD

**Issue by SamMousa** [composer/composer#5547] opened 2016-07-25 10:59 UTC
With the following composer.json:

```json
{
    "name": "root/test",
    "description": "test",
    "type": "library",
    "license": "MIT",
    "authors": [
        {
            "name": "Sam Mousa",
            "email": "sam@mousa.nl"
        }
    ],
    "minimum-stability": "dev",
    "require": {},
    "require-dev": {
        "nonexistent/package": "13.4"
    }
}
```

When I run this command:

```
composer update -vvv --no-dev
```

I get this output:

```
vagrant@vagrant-ubuntu-wily-64:/tmp/test$ composer update --no-dev -vvv
Reading ./composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/tmp/test): git branch --no-color --no-abbrev -v
Executing command (/tmp/test): git describe --exact-match --tags
Executing command (/tmp/test): git log --pretty="%H" -n1 HEAD
Reading /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/config.json
Loading config file /home/vagrant/.composer/auth.json
Loading config file /home/vagrant/.composer/composer.json
Loading config file /home/vagrant/.composer/auth.json
Reading /home/vagrant/.composer/auth.json
Reading /tmp/test/vendor/composer/installed.json
Reading /home/vagrant/.composer/vendor/composer/installed.json
Loading plugin Fxp\Composer\AssetPlugin\FxpAssetPlugin
Running 1.2.0 (2016-07-19 01:28:52) with PHP 5.6.11-1ubuntu3.4 on Linux / 4.2.0-42-generic
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /home/vagrant/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-2015.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-2015-10.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-2016-01.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-2016-04.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-2016-07.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-archived.json from cache
Reading /home/vagrant/.composer/cache/repo/https---packagist.org/p-provider-latest.json from cache
Resolving dependencies through SAT
Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package nonexistent/package could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
```

And I expected this to happen:

Since I specified the `--no-dev` parameter I expected it to not care about dev dependencies and not even attempt to resolve them.

**Comment by stof** [comment] 2016-07-25 11:04
Resolving them is necessary to ensure that resolved dependencies are consistent even if you skip the installation of dev deps during ``composer update``, and that you don't get an error when using ``composer install`` later just because the lock file does not have dev dependencies. This was done to avoid a bunch of WTF from earlier composer versions.

``--no-dev`` is now controlling only the installation part of ``composer update``.

Btw, there are already many closed issues about this topic.

@alcohol @Seldaek it might be worth writing something about it in the doc FAQ to avoid seeing it pop again every week

**Comment by SamMousa** [comment] 2016-07-25 11:06
Okay, thanks. Feel free to close; forgot to search in closed issues for this one, my apologies!

**Comment by alcohol** [comment] 2016-07-25 11:06
Please use the search functionality. This has been reported multiple times, and is expected behaviour.

@stof I documented the commit hash hack for the same reason, yet that question also still pops up from time to time. Sad truth is, documentation simply is not consulted very often.

**Closed by alcohol** 2016-07-25 11:06 UTC

**Comment by stof** [comment] 2016-07-25 11:24
@alcohol but if we don't have the doc, 100% of people will complain in the issue tracker. If we have the doc, we can hope that part of them will read the doc.

**Comment by alcohol** [comment] 2016-07-25 11:30
@stof Yeah I am definitely not arguing against documenting this. Just not very optimistic about it having a significant impact. Regardless, I am unhappy about the current state of our documentation, and until that changes, I am personally not interested in adding more content to it.

**Comment by henno** [comment] 2016-08-15 06:49
I recently ran into this issue, too. I run PHP7 on my dev machine but some of my customers use hosters using older PHP version and when I deploy to their servers, I get this error, because I use Behat and Codeception locally which depend on Phpunit which doesn't work on PHP 5.5.

I was completely stomped by this composer behavior. No-dev should mean "do not install stuff from 'require-dev'" but why is it complaining about stuff in require-dev packages"? I finally thought that there must be a bug in composer. I did try to google but didn't find anything.

I did try to search Github issues here but while I searched the existing issues, I didn't delete the default filter which is to search for only open issues. That's why I didn't find any issues and created a new one. @alcohol kindly referenced me here.

How about a warning message including an explanation why composer tries to resolve dependencies from require-dev even though --no-dev is set? It would have saved me a whole day of work.

**Comment by alcohol** [comment] 2016-08-15 07:12
Running update or installing without a lock file will cause issues in your situation. But it will still install fine from a lock file if you just include `--no-dev`.

**Comment by henno** [comment] 2016-08-15 07:13
AFAIK, I have the lock file included in version control.

**Comment by alcohol** [comment] 2016-08-15 07:16
I would prefer you showed the (very verbose: `-vvv`) output of your attempt to run install, rather than just making statements that I cannot verify.

**Comment by henno** [comment] 2016-08-15 07:29
You are right. I did
```
rm -rf vendor/
composer install --no-dev -vvv
```
and it installed fine.

My deploy script to staging server (which also has older PHP to verify compatibility with the live environment) currently has ```composer update --no-dev```. The script is invoked through Bitbucket webhook when a commit comes in. I could do ```rm -rf vendor``` and ```composer install --no-dev``` in that script but: there is a 10 second window (Bitbucket-side limitation). If the script does not finish within that period, Bitbucket will retry after a few minutes (even though the script does finish in about 15 seconds) and everyone gets duplicate emails about the new commit. What solved this problem in the past was replacing ```rm -rf projectdir && git clone ...``` with ```git pull``` and ```composer install``` with ```composer update --no-dev```.

Could you add another switch --do-not-resolve-require-dev-dependecies, for example? :)

**Comment by alcohol** [comment] 2016-08-15 08:06
Why remove the vendor dir? Just run `install`.

**Comment by henno** [comment] 2016-08-15 11:14
Then I'm getting ```Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.```.

**Comment by alcohol** [comment] 2016-08-15 11:26
Then you did something wrong during development. That has nothing to do with deployment. It means you committed a composer.json and composer.lock that are out of sync.
