### ISSUE TITLE
Composer still tries to update other dependencies when `composer require`

### ISSUE THREAD

**Issue by Axure** [composer/composer#4720] opened 2015-12-19 15:43 UTC
When `composer require` some package, e.g. `composer require barryvdh/laravel-debugbar`, my network monitor gives information like this

>response GET packagist.org:80/p/illuminate/broadcasting%24f707b335967776aa918e75caf6676af0133fdde1a90b90c6c03dde48050a9a82.json 200 OK

, which I think makes my requiring very slow. But according to [Composer: how can I install another dependency without updating old ones?](http://stackoverflow.com/questions/15212381/composer-how-can-i-install-another-dependency-without-updating-old-ones), `composer require` does not update other packages. So what is composer doing?

**Comment by Seldaek** [comment] 2016-02-21 14:59
Duplicate of #3672

**Closed by Seldaek** 2016-02-21 14:59 UTC
Labels: Support
