### ISSUE TITLE
Allow interaction when running custom scripts

### ISSUE THREAD

**Issue by back-2-95** [composer/composer#5311] opened 2016-05-11 09:53 UTC
Consider following in by composer.json:

```
"scripts": {
    "mycustomcmd": "php application.php
  },
```

When e.g. having following, I can use `composer mycustomcmd foobar` which will be same as running `php application.php foobar`

BUT if my application.php asks for input (e.g. asks yes/no questions), it won't give the possibility to do so. Is this possible to add to Composer OR are they some good reasons why not to do it?

**Comment by Seldaek** [comment] 2016-05-11 10:53
Duplicate of https://github.com/composer/composer/pull/4036 & #3299

**Closed by Seldaek** 2016-05-11 10:53 UTC
