### ISSUE TITLE
getting error

### ISSUE THREAD

**Issue by aloksinha3110** [composer/composer#10398] opened 2021-12-27 09:11 UTC
composer update getting

Files with "phar" extensions aren't supported. Only ZIP and TAR/TAR.GZ/TGZ archives are supported.

**Comment by Seldaek** [comment] 2021-12-28 11:51
We'll need a lot more information here if you want someone to help.. At least a composer.json and the output of the command you run (ideally with -vvv flag)

**Comment by aloksinha3110** [comment] 2022-01-03 06:33
[root@xlgarten dev]# composer update -vvv
Running 2.2.1 (2021-12-22 22:21:31) with PHP 7.4.27 on Linux / 3.10.0
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Continue as root/super user [yes]?
Reading ./composer.json (/var/www/html/dev/composer.json)
Loading config file /root/.config/composer/auth.json
Loading config file ./composer.json (/var/www/html/dev/composer.json)
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid
Failed to initialize global composer: Composer could not find the config file: /root/.config/composer/composer.json

Reading /var/www/html/dev/vendor/composer/installed.json
Loading plugin MagentoHackathon\Composer\Magento\Plugin (from magento/magento-composer-installer)
activate magento plugin
Loading plugin Magento\InventoryComposerInstaller\Plugin (from magento/inventory-composer-installer)
Loading plugin Laminas\DependencyPlugin\DependencyRewriterPluginDelegator (from laminas/laminas-dependency-plugin)
Activating Laminas\DependencyPlugin\DependencyRewriterV2
Loading plugin Magento\ComposerRootUpdatePlugin\Plugin\PluginDefinition (from magento/composer-root-update-plugin)
> pre-command-run: Laminas\DependencyPlugin\DependencyRewriterPluginDelegator->onPreCommandRun
In Laminas\DependencyPlugin\DependencyRewriterV2::onPreCommandRun
> command: MagentoHackathon\Composer\Magento\Plugin->onCommandEvent
> pre-update-cmd: Magento\InventoryComposerInstaller\Plugin->initModuleDeployment
Reading ./composer.lock (/var/www/html/dev/composer.lock)
Loading composer repositories with package information
Reading /root/.cache/composer/repo/https---repo.magento.com/packages.json from cache
Using HTTP basic authentication with username "9117b4efa39aa51e4150e3f3c2964b20"
Downloading https://repo.magento.com/packages.json
[200] https://repo.magento.com/packages.json
Writing /root/.cache/composer/repo/https---repo.magento.com/packages.json into cache
Reading /root/.cache/composer/repo/https---repo.magento.com/p-provider-ce.json from cache
Reading /root/.cache/composer/repo/https---repo.magento.com/p-provider-marketplace-extensions.json from cache
Reading /root/.cache/composer/repo/https---repo.magento.com/provider-magento$composer-root-update-plugin.json from cache
Reading /root/.cache/composer/repo/https---repo.magento.com/provider-magento$data-migration-tool.json from cache
Reading /root/.cache/composer/repo/https---repo.magento.com/provider-magento$product-community-edition.json from cache
Reading /root/.cache/composer/repo/https---repo.magento.com/packages.json from cache
Downloading https://repo.magento.com/packages.json
[200] https://repo.magento.com/packages.json
Writing /root/.cache/composer/repo/https---repo.magento.com/packages.json into cache
Reading /root/.cache/composer/repo/https---repo.magento.com/p-provider-ce.json from cache
Reading /root/.cache/composer/repo/https---repo.magento.com/p-provider-marketplace-extensions.json from cache










  [RuntimeException]
  Files with "phar" extensions aren't supported. Only ZIP and TAR/TAR.GZ/TGZ archives are supported.


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Repository/ArtifactRepository.php:115
 Composer\Repository\ArtifactRepository->getComposerInformation() at phar:///usr/local/bin/composer/src/Composer/Repository/ArtifactRepository.php:89
 Composer\Repository\ArtifactRepository->scanDirectory() at phar:///usr/local/bin/composer/src/Composer/Repository/ArtifactRepository.php:68
 Composer\Repository\ArtifactRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:310
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:62
 Composer\Repository\ArrayRepository->loadPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:379
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/PoolBuilder.php:234
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///usr/local/bin/composer/src/Composer/Repository/RepositorySet.php:261
 Composer\Repository\RepositorySet->createPool() at phar:///usr/local/bin/composer/src/Composer/Installer.php:435
 Composer\Installer->doUpdate() at phar:///usr/local/bin/composer/src/Composer/Installer.php:279
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:248
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:335
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:130
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:73
 require() at /usr/local/bin/composer:29

**Comment by aloksinha3110** [comment] 2022-01-03 11:21
my composer.json file https://github.com/magento/magento2/blob/2.4-develop/composer.json

**Comment by Seldaek** [comment] 2022-01-03 12:37
The stack trace shows it's failing in ArtifactRepository, which I don't see present in the magento2 composer.json, so I assume you added it yourself? And then have some phar in that directory.. Anyway looks like a duplicate of https://github.com/composer/composer/issues/10406

**Closed by Seldaek** 2022-01-03 12:37 UTC
Labels: Support
