### ISSUE TITLE
Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 9223372036854775912 bytes) with PHP7

### ISSUE THREAD

**Issue by bupy7** [composer/composer#4940] opened 2016-02-22 09:51 UTC
I have don't work composer with PHP7. My every actions accompanied by fatal error.

PHP:
```
PHP 7.0.4-dev (cli) (built: Jan 27 2016 15:57:53) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0RC4, Copyright (c) 2002-2016, by Derick Rethans
```

Composer log with command `composer status`:
```
$ composer status

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 16140901064495857768 bytes) in phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Util/RemoteFilesystem.php on line 927

Call Stack:
    0.0016     357888   1. {main}() /Volumes/Home/bupy7/.phpbrew/bin/composer:0
    0.0178     560528   2. require('phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/bin/composer') /Volumes/Home/bupy7/.phpbrew/bin/composer:25
    0.0488    2752968   3. Composer\Console\Application->run() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/bin/composer:43
    0.0510    3075320   4. Symfony\Component\Console\Application->run() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Console/Application.php:99
    0.0518    3145040   5. Composer\Console\Application->doRun() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/vendor/symfony/console/Application.php:123
    0.0541    3216528   6. Symfony\Component\Console\Application->doRun() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Console/Application.php:166
    0.0542    3216528   7. Symfony\Component\Console\Application->doRunCommand() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/vendor/symfony/console/Application.php:192
    0.0547    3216528   8. Symfony\Component\Console\Command\Command->run() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/vendor/symfony/console/Application.php:844
    0.0559    3218520   9. Composer\Command\StatusCommand->execute() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/vendor/symfony/console/Command/Command.php:259
    0.0559    3218520  10. Composer\Command\Command->getComposer() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Command/StatusCommand.php:49
    0.0559    3218520  11. Composer\Console\Application->getComposer() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Command/Command.php:53
    0.0559    3218520  12. Composer\Factory::create() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Console/Application.php:244
    0.0559    3218560  13. Composer\Factory->createComposer() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Factory.php:578
    0.0721    3856712  14. Composer\Factory::createRemoteFilesystem() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Factory.php:332
    0.0738    4018608  15. Composer\Util\RemoteFilesystem->__construct() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Factory.php:612
    0.0738    4018608  16. Composer\Util\RemoteFilesystem->getTlsDefaults() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Util/RemoteFilesystem.php:60
    0.0816    4020464  17. Composer\Util\RemoteFilesystem->validateCaFile() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Util/RemoteFilesystem.php:798
    0.0827    4314856  18. openssl_x509_parse() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Util/RemoteFilesystem.php:927


Check https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors for more info on how to handle out of memory errors.
```

But if I uses PHP5.6 then it there is no error.

PHP:
```
PHP 5.6.16 (cli) (built: Dec 13 2015 19:24:38) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.3.3, Copyright (c) 2002-2015, by Derick Rethans
```

Composer log with command `composer status`:
```
﻿﻿﻿$ composer status

No local changes
```

**OS:** OS X 10.9.5
**Composer:** Composer version 1.0-dev (4c0e163977f8289288df7b37e0fd0469d3e8cbc6) 2016-02-20 19:28:03

**Comment by curry684** [comment] 2016-02-22 10:08
```    0.0816    4020464  17. Composer\Util\RemoteFilesystem->validateCaFile() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Util/RemoteFilesystem.php:798
    0.0827    4314856  18. openssl_x509_parse() phar:///Volumes/Home/bupy7/.phpbrew/bin/composer/src/Composer/Util/RemoteFilesystem.php:927
```
Wtf, it's allocating 8192 PETAbyte to validate a CA file?  :D   Can you run the failing command with `-vvv` option and share the output in [a gist](https://gist.github.com/)? You may want to edit out personally identifiable information.

**Comment by bupy7** [comment] 2016-02-22 10:19
@curry684 Log: https://gist.github.com/bupy7/aae6561f844acf8ff2cc

And I not understand phrase 

> You may want to edit out personally identifiable information.

What is? )

**Comment by Seldaek** [comment] 2016-02-22 10:30
So it blows up when loading `/private/var/folders/g7/3_xqmxdj17n8_tpk8jz1cs_w0000gn/T/composer-cacert-39eaf16e26c08cc90d728865f1c60406ee5d864d5963f72ede2a1cbb127f95ca.pem` which sure looks like the CAfile we bundle in composer. That's really odd.

Can you check if running this command crashes too with php7?

```
php -ddisplay_errors=1 -derror_reporting=-1 -r 'openssl_x509_parse(file_get_contents("https://raw.githubusercontent.com/composer/composer/master/res/cacert.pem"));'
```

If it crashes I would report it as a bug on bugs.php.net using that as reproduce code.

**Comment by bupy7** [comment] 2016-02-22 10:33
@Seldaek 
```
$ php -v
PHP 7.0.4-dev (cli) (built: Jan 27 2016 15:57:53) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0RC4, Copyright (c) 2002-2016, by Derick Rethans
~ > bupy7@bupy7-mac [php:-phpbrew]
$ php -ddisplay_errors=1 -derror_reporting=-1 -r 'openssl_x509_parse(file_get_contents("https://raw.githubusercontent.com/composer/composer/master/res/cacert.pem"));'
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 6917529027641081960 bytes) in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. openssl_x509_parse() Command line code:1

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 6917529027641081960 bytes) in Command line code on line 1

Call Stack:
    0.0001     349392   1. {main}() Command line code:0
    1.6906     610288   2. openssl_x509_parse() Command line code:1
```

**Comment by Seldaek** [comment] 2016-02-22 10:36
OK, could you go and report it as a bug to php and put the link to the 
bug report here?

I think relevant information needed is the exact commit you built from 
and the version of openssl you used to build against. You can get that 
using:

     php -i | grep -i openssl

**Comment by curry684** [comment] 2016-02-22 10:41
> `PHP 7.0.4-dev (cli) (built: Jan 27 2016 15:57:53) ( NTS )`

Please do note that you're using a pretty outdated nightly. I have none of these issues with PHP 7.0 stable. In general, when unexpected crashes occur using a PHP nightly, that is a likelier cause than the software it was running  :wink: 

You should consider switching to 7.0.3 stable instead for predictable behaviour, or to the most recent nightly if you want to report a bug - something invasive like this is likely already fixed.

**Comment by bupy7** [comment] 2016-02-22 10:44
Ok, what me do? )) Write to bug report or build stable version PHP7?

**Comment by Seldaek** [comment] 2016-02-22 10:46
Build the latest dev version if you can, and then if that still fails report a bug.

**Comment by bupy7** [comment] 2016-02-22 10:48
@Seldaek ok!

**Comment by bupy7** [comment] 2016-02-22 14:51
```
$ php -v
PHP 7.0.3 (cli) (built: Feb 22 2016 19:34:44) ( NTS )
Copyright (c) 1997-2016 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
    with Xdebug v2.4.0RC4, Copyright (c) 2002-2016, by Derick Rethans
```

```
$ php -ddisplay_errors=1 -derror_reporting=-1 -r 'openssl_x509_parse(file_get_contents("https://raw.githubusercontent.com/composer/composer/master/res/cacert.pem"));'
PHP Fatal error:  Allowed memory size of 2147483648 bytes exhausted (tried to allocate 10376293541461622888 bytes) in Command line code on line 1
PHP Stack trace:
PHP   1. {main}() Command line code:0
PHP   2. openssl_x509_parse() Command line code:1

Fatal error: Allowed memory size of 2147483648 bytes exhausted (tried to allocate 10376293541461622888 bytes) in Command line code on line 1

Call Stack:
    0.0002     349360   1. {main}() Command line code:0
    1.8395     610256   2. openssl_x509_parse() Command line code:1
```

**Comment by bupy7** [comment] 2016-02-22 15:22
https://bugs.php.net/bug.php?id=71645

**Comment by bupy7** [comment] 2016-02-22 22:32
The problem is solved rebuild PHP7 with new version OpenSSL. Thanks!

**Comment by curry684** [comment] 2016-02-22 22:56
Good to hear, feel free to close the issue if you need no further help.

**Closed** 2016-02-22 22:57 UTC
Labels: Bug
