### ISSUE TITLE
Composer's update command not working in window environment

### ISSUE THREAD

**Issue by divineniiquaye** [composer/composer#9978] opened 2021-06-21 08:10 UTC
Composer `update` command works fine when the dev-master version of a project is included, since the composer's version 2.1.3. When the package is syncing, I get an error:

Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type resource, bool given in phar://C:/HomeServer/PHP/composer/composer.phar/vendor/symfony/process/Pipes/WindowsPipes.php:71

With 29 stack traces, suspecting the error might have occurred at this exact stack 9:

`#9` phar://C:/HomeServer/PHP/composer/composer.phar/src/Composer/Util/Git.php(294): Composer\Util\Git->syncMirror()

Please can this be investigated and treated as a **hot-fix**.

**Comment by stof** [comment] 2021-06-21 13:37
please give the full stack trace

**Comment by divineniiquaye** [comment] 2021-06-22 01:59
The Full stack traces:

![image](https://user-images.githubusercontent.com/53147395/122850396-aa8eaa00-d2fc-11eb-9fb1-d44b6d397c04.png)

![image](https://user-images.githubusercontent.com/53147395/122850707-402a3980-d2fd-11eb-9bae-f2b67cc59066.png)

**Comment by Seldaek** [comment] 2021-06-27 12:02
- Can you show the full output of `composer diagnose` too?
- Can you try `composer update --prefer-dist` as a workaround?

**Comment by WOSHIZHAZHA120** [comment] 2021-07-25 02:21
> 
> 
>     * Can you show the full output of `composer diagnose` too?
> 
>     * Can you try `composer update --prefer-dist` as a workaround?

I have same problem too.
```composer update --prefer-dist``` command still not work.
This is diagnostic log.
```
PHP Fatal error:  Uncaught TypeError: fclose(): Argument #1 ($stream) must be of
 type resource, bool given in phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/co
mposer.phar/vendor/symfony/process/Pipes/WindowsPipes.php:71
Stack trace:
#0 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Pipes/WindowsPipes.php(71): fclose()
#1 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Pipes/WindowsPipes.php(194): Symfony\Component\Process\Pipes\WindowsPipe
s->__construct()
#2 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Process.php(1231): Symfony\Component\Process\Pipes\WindowsPipes::create(
)
#3 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Process.php(258): Symfony\Component\Process\Process->getDescriptors()
#4 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Process.php(196): Symfony\Component\Process\Process->start()
#5 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Ut
il/ProcessExecutor.php(131): Symfony\Component\Process\Process->run()
#6 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Ut
il/ProcessExecutor.php(66): Composer\Util\ProcessExecutor->doExecute()
#7 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Pa
ckage/Version/VersionGuesser.php(122): Composer\Util\ProcessExecutor->execute()
#8 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Pa
ckage/Version/VersionGuesser.php(71): Composer\Package\Version\VersionGuesser->g
uessGitVersion()
#9 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Pa
ckage/Loader/RootPackageLoader.php(86): Composer\Package\Version\VersionGuesser-
>guessVersion()
#10 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/F
actory.php(384): Composer\Package\Loader\RootPackageLoader->load()
#11 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/F
actory.php(616): Composer\Factory->createComposer()
#12 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/C
onsole/Application.php(418): Composer\Factory::create()
#13 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/C
onsole/Application.php(540): Composer\Console\Application->getComposer()
#14 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/C
onsole/Application.php(191): Composer\Console\Application->getPluginCommands()
#15 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony
/console/Application.php(117): Composer\Console\Application->doRun()
#16 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/C
onsole/Application.php(125): Symfony\Component\Console\Application->run()
#17 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/bin/composer(6
7): Composer\Console\Application->run()
#18 C:\Users\WOSHI\scoop\apps\composer\2.1.5\composer.phar(24): require('...')
#19 {main}
  thrown in phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor
/symfony/process/Pipes/WindowsPipes.php on line 71

Fatal error: Uncaught TypeError: fclose(): Argument #1 ($stream) must be of type
 resource, bool given in phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/compose
r.phar/vendor/symfony/process/Pipes/WindowsPipes.php:71
Stack trace:
#0 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Pipes/WindowsPipes.php(71): fclose()
#1 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Pipes/WindowsPipes.php(194): Symfony\Component\Process\Pipes\WindowsPipe
s->__construct()
#2 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Process.php(1231): Symfony\Component\Process\Pipes\WindowsPipes::create(
)
#3 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Process.php(258): Symfony\Component\Process\Process->getDescriptors()
#4 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony/
process/Process.php(196): Symfony\Component\Process\Process->start()
#5 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Ut
il/ProcessExecutor.php(131): Symfony\Component\Process\Process->run()
#6 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Ut
il/ProcessExecutor.php(66): Composer\Util\ProcessExecutor->doExecute()
#7 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Pa
ckage/Version/VersionGuesser.php(122): Composer\Util\ProcessExecutor->execute()
#8 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Pa
ckage/Version/VersionGuesser.php(71): Composer\Package\Version\VersionGuesser->g
uessGitVersion()
#9 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/Pa
ckage/Loader/RootPackageLoader.php(86): Composer\Package\Version\VersionGuesser-
>guessVersion()
#10 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/F
actory.php(384): Composer\Package\Loader\RootPackageLoader->load()
#11 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/F
actory.php(616): Composer\Factory->createComposer()
#12 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/C
onsole/Application.php(418): Composer\Factory::create()
#13 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/C
onsole/Application.php(540): Composer\Console\Application->getComposer()
#14 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/C
onsole/Application.php(191): Composer\Console\Application->getPluginCommands()
#15 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor/symfony
/console/Application.php(117): Composer\Console\Application->doRun()
#16 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/src/Composer/C
onsole/Application.php(125): Symfony\Component\Console\Application->run()
#17 phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/bin/composer(6
7): Composer\Console\Application->run()
#18 C:\Users\WOSHI\scoop\apps\composer\2.1.5\composer.phar(24): require('...')
#19 {main}
  thrown in phar://C:/Users/WOSHI/scoop/apps/composer/2.1.5/composer.phar/vendor
/symfony/process/Pipes/WindowsPipes.php on line 71

进程已结束，退出代码为 255。
```

**Comment by WOSHIZHAZHA120** [comment] 2021-07-25 02:24
I found this bug only current in php 8, I used php7 can complete update without exception.

**Comment by divineniiquaye** [comment] 2021-11-15 06:15
I investigated the issue after encountering it several times and realized, the bug in from the Symfony's process component.

Line 79 of the WindowPipe class is where the bug is.

**Comment by Seldaek** [comment] 2021-11-15 08:05
Most likely it is fixed in symfony already, we're just using a super old symfony version due to php 5.3 support. In 2.3 we will drop old versions of PHP and update symfony components to latest, hence why it's in the 2.3 milestone.

**Comment by Seldaek** [comment] 2022-01-04 15:33
Please try again now after a `composer self-update --snapshot` to see if the issue is fixed.

**Comment by divineniiquaye** [comment] 2022-01-04 16:01
Working fine, I debugged and realized, the error is only caused, when some packages repo git objects corrupts.

I fixed my repos which had corrupted git objects and no longer facing an Issue on windows.

Thanks for work on this fix.

**Comment by Seldaek** [comment] 2022-01-04 16:04
OK thanks closing then.

**Closed by Seldaek** 2022-01-04 16:04 UTC
Labels: Bug
