### ISSUE TITLE
Keeping stuff out of packages

### ISSUE THREAD

**Issue by marapper** [composer/composer#3809] opened 2015-03-02 14:25 UTC
`composer install -o` (or just `--prefer-dist`) could install deps and copy files ignore test, docs, examples like `npm install` (with `.npmignore` list) does. When we're just using the package we don't need all the stuff.

**Comment by xabbuh** [comment] 2015-03-02 21:46
Looks like a duplicate of #1750.

**Comment by marapper** [comment] 2015-03-03 12:15
Thanks.

**Closed** 2015-03-03 12:15 UTC
