### ISSUE TITLE
Composer 2: 'composer remove' doesn't remove dependencies

### ISSUE THREAD

**Issue by ocean90** [composer/composer#9207] opened 2020-09-12 12:53 UTC
Output of `composer diagnose`:

<details>
<summary>Details</summary>

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.0-RC1
PHP version: 7.3.22
PHP binary path: /usr/local/Cellar/php@7.3/7.3.22/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```
</details>

I haven't found any related issue but there seems to be a difference between v1 and v2 when running `composer remove  johnpbloch/wordpress`. In v2 it no longer removes the dependencies defined in the [composer.json](https://github.com/johnpbloch/wordpress/blob/0973abd5c01ecce0b60bc1c81a6dd072827de930/composer.json#L25-L28). 

To reproduce create an empty `composer.json` via `composer init` and then run the following commands:

```
❯ composer selfupdate --stable
Upgrading to version 1.10.13 (stable channel).

Use composer self-update --rollback to return to version 2.0.0-RC1

❯ composer require johnpbloch/wordpress --no-plugins
Using version ^5.5 for johnpbloch/wordpress
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing johnpbloch/wordpress-core-installer (2.0.0): Loading from cache
  - Installing johnpbloch/wordpress-core (5.5.1): Loading from cache
  - Installing johnpbloch/wordpress (5.5.1): Loading from cache
Writing lock file
Generating autoload files

❯ composer remove johnpbloch/wordpress --no-plugins
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 3 removals
  - Removing johnpbloch/wordpress-core-installer (2.0.0)
  - Removing johnpbloch/wordpress-core (5.5.1)
  - Removing johnpbloch/wordpress (5.5.1)
Generating autoload files

❯ composer selfupdate --preview
Updating to version 2.0.0-RC1 (preview channel).
   Downloading (100%)
Use composer self-update --rollback to return to version 1.10.13

❯ composer require johnpbloch/wordpress --no-plugins
Using version ^5.5 for johnpbloch/wordpress
./composer.json has been updated
Running composer update johnpbloch/wordpress
Loading composer repositories with package information
Updating dependencies
Lock file operations: 3 installs, 0 updates, 0 removals
  - Locking johnpbloch/wordpress (5.5.1)
  - Locking johnpbloch/wordpress-core (5.5.1)
  - Locking johnpbloch/wordpress-core-installer (2.0.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 0 updates, 0 removals
  - Installing johnpbloch/wordpress-core-installer (2.0.0): Extracting archive
  - Installing johnpbloch/wordpress-core (5.5.1): Extracting archive
  - Installing johnpbloch/wordpress (5.5.1): Extracting archive
Generating autoload files

❯ composer remove johnpbloch/wordpress --no-plugins
./composer.json has been updated
Running composer update johnpbloch/wordpress
Loading composer repositories with package information
Updating dependencies
Lock file operations: 0 installs, 0 updates, 1 removal
  - Removing johnpbloch/wordpress (5.5.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing johnpbloch/wordpress (5.5.1)
Generating autoload files
```

In v1 the composer.lock is removed because all dependencies were removed, in v2 only `johnpbloch/wordpress` is removed, leaving the other two unused dependencies. The result of `composer why` is also odd:

```
❯ composer why johnpbloch/wordpress-core

  [InvalidArgumentException]
  Could not find package "johnpbloch/wordpress-core" in your project


depends [-r|--recursive] [-t|--tree] [--] <package> [<constraint>]

❯ composer why johnpbloch/wordpress-core-installer
There is no installed package depending on "johnpbloch/wordpress-core-installer"
```

Theres no difference when running remove with `--with-all-dependencies` or `--update-with-all-dependencies`.

**Comment by Ayesh** [comment] 2020-09-13 11:09
I can reproduce this as well, even at the current git HEAD `6cf4ba051c8`.

**Comment by Seldaek** [comment] 2020-09-14 19:28
Known issue, and duplicate of #8870 which @naderman is working on already. Please watch the other issue.

**Closed by Seldaek** 2020-09-14 19:28 UTC
