### ISSUE TITLE
Reinstall command to reinstall packages as source|dist

### ISSUE THREAD

**Issue by alexey-baranov** [composer/composer#2901] opened 2014-04-11 07:05 UTC
Hello!
I have my package installed into project. How to update them with source code?

I have tried 
```
C:\wapp54\apache2\htdocs\hd>composer update alexey_baranov/page --prefer-source
```

but nothing was updated
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```

**Comment by Seldaek** [comment] 2016-04-15 16:48
Closing as duplicate of https://github.com/composer/composer/issues/3112

**Closed by Seldaek** 2016-04-15 16:48 UTC
Labels: Feature
