### ISSUE TITLE
Script execution fails with version 1.2.3

### ISSUE THREAD

**Issue by mwjames** [composer/composer#5933] opened 2016-12-03 04:04 UTC
My `composer.json`:

```json
	},
	"config": {
		"process-timeout": 0
	},
	"scripts": {
		"phpunit": "php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist",
		"unit": [
			"composer dump-autoload",
			"php ../../tests/phpunit/phpunit.php -c phpunit.xml.dist --testsuite=semantic-mediawiki-unit"
		],
		"cs-standalone": [
			"composer validate --no-interaction",
			"vendor/bin/phpcs src/* includes/* tests/* --standard=phpcs.xml --extensions=php -sp"
		],
		"cs": [
			"composer cs-standalone",
			"vendor/bin/phpmd src/,includes/,tests/ text phpmd.xml"
		],
		"ci": [
			"composer phpunit",
			"composer cs"
		]
	}
```

Running `composer phpunit -q` with `Composer version 1.2.2 2016-11-03 17:43:15` works as expected [0] but with `Composer version 1.2.3 2016-12-01 14:33:53` [1], the execution fails.

The use of the `-q` is expected to be applied to the Composer component and not to the script output but with `1.2.3` this behvaiour changed where `-q` is applied to the whole output.

For test purpose I removed `-q` from the caller [2] (`composer phpunit`) which returns an output but it is not formatted correctly (different to version 1.2.2 [0]).

[0] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/180316580
[1] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/180894326
[2] https://travis-ci.org/SemanticMediaWiki/SemanticMediaWiki/jobs/180897823

**Comment by alcohol** [comment] 2016-12-03 23:22
Try changing the order. I think some changes were applied in 1.2.3 that allow arguments to be passed to script commands, `composer --quiet phpunit` should still do the trick though.

**Comment by alcohol** [comment] 2016-12-03 23:28
Composer script behaviour was changed in https://github.com/composer/composer/commit/103624d4ed7da1719f8204f11f97147108e1e975

**Comment by alcohol** [comment] 2016-12-03 23:29
@Seldaek any idea if this was intentional? Side effect we did not take into account? Any suggestions or ideas?

**Comment by Seldaek** [comment] 2016-12-04 16:55
I think this was exactly the point that the inner output should not leak and instead go through the composer IO. Maybe @fabpot can confirm, but this seems to me like you just were abusing a bug and treating it as a feature :)

**Comment by mwjames** [comment] 2016-12-04 17:04
>  but this seems to me like you just were abusing a bug and treating it as a feature :)

From a user or consumer point of you I can hardly classify this as bug because it did exactly what it suppose to do til 1.2.2, now with a minor release this just got f....d and all I get is scrambled output which is more or less useless especially given one wants to use/read the script output.

**Comment by mwjames** [comment] 2016-12-04 17:09
The issue is two-fold:

- Different behaviour of `-q` in combination with a script execution [0] -> [1]
- The script output is unreadable [2]

**Comment by Seldaek** [comment] 2016-12-04 17:27
OK sorry I missed the fact that the output is garbage.. That just seems to be due to the fact we use write(x) and it should be write(x, false) I think to avoid inserting newlines. That should fix it.

The rest though, -q leaking output was accidental and IMO a bugfix which is fine a patch release.

**Comment by mwjames** [comment] 2016-12-04 17:35
> The rest though, -q leaking output was accidental and IMO a bugfix which is fine a patch release.

Understood.

What is the recommendation when one wants to see the script output but suppress any Composer specific output (which was accidentally achieved by `-q`)?

**Comment by Seldaek** [comment] 2016-12-04 17:44
Well, all composer outputs really in this case is the "> xxx" line on 
top, right?

I think in non-verbose mode we could skip it at least when using the 
run-script command or the script aliases like "composer test", because 
in this case it's quite obvious what you are running. We added this 
output mostly because during a composer install or update, if scripts 
failed with an exception users would report it here, so the execution 
line more clearly shows what was happening when it failed.

**Comment by hannesvdvreken** [comment] 2016-12-06 14:43
```
$ composer unit-tests
> phpunit
PHPUnit 5.4.8 by Sebastian Bergmann and contributors.

.
.
.
.^C
$
$ composer self-update 1.2.2
Updating to version 1.2.2 (preview channel).
    Downloading: 100%         
Use composer self-update --rollback to return to version 1.2.3
$
$ composer unit-tests
> phpunit
PHPUnit 5.4.8 by Sebastian Bergmann and contributors.

......^C
```

When comparing v [1.2.3 to 1.2.2](https://github.com/composer/composer/compare/1.2.2...1.2.3) you see it's because of this commit: https://github.com/composer/composer/commit/103624d4ed7da1719f8204f11f97147108e1e975

The `$this->io->write` method doesn't do the exact same thing as `echo`.

**Comment by hannesvdvreken** [comment] 2016-12-06 14:43
Will investigate further when I have time, and may send a PR.

**Comment by hannesvdvreken** [comment] 2016-12-06 14:49
It should be called as `$this->io->write($buffer, false)`. Props to @driesvints

**Comment by Seldaek** [comment] 2016-12-06 16:07
Fixed in the next release, use `composer self-update --snapshot` if you want the fix right now.

**Closed by Seldaek** 2016-12-06 16:07 UTC
Labels: Bug

**Comment by hannesvdvreken** [comment] 2016-12-06 16:12
Confirmed!

```
$ composer self-update --snapshot
Updating to version e9d04f2b2d1470e94e276f90a63171c635e4fd61 (snapshot channel).
    Downloading: 100%         
Use composer self-update --rollback to return to version 1.2.2
$
$ composer unit-tests
> phpunit
PHPUnit 5.4.8 by Sebastian Bergmann and contributors.

..............................................^C
$
```
