### ISSUE TITLE
UserAgent used by composer 2, treated as attack signature by WAF

### ISSUE THREAD

**Issue by VadymKovalenko** [composer/composer#9492] opened 2020-11-18 10:25 UTC
Our network infra is protected by Web Application Firewall.  And our private composer repository(which we expose to our clients)  located behind this firewall
After updating composer to v2, it is impossible to download packages from our repository. Investigation shows that requests done by composer are blocked by WAF with next reason: `"curl" execution attempt (Header)`

This is caused by User-Agent header, used by composer  : `Composer/2.0.7 (Linux; 4.15.0-20-generic; PHP 7.2.24; curl 7.58.0)` Combination of `; curl`  is treated like an attack signature. If omit `;` or use `cURL` instead of `curl` - everything is ok

 With Composer 1 it works as expected. As UserAgent of composer 1 looks different : `Composer/1.10.17 (Linux; 4.15.0-20-generic; PHP 7.2.24)`

----------------
My `composer.json`:

```json
{
    "name": "vadym/tst",
    "authors": [
        {
            "name": "Vadym Kovalenko",
            "email": "vadym@xxxxx.com"
        }
    ],
  "repositories": [{
    "type": "composer",
    "url": "https://xxxx"
  }],
    "require": {
        "xxxxx/ourapp" : "^2.0"
    },
  "license" : "XXX"
}

```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.2.24
PHP binary path: /usr/bin/php7.2
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1
zip extension: OK
vadym@vadym-kovalenko-mint-19:~/develop/tst$ composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.2.24
PHP binary path: /usr/bin/php7.2
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
cURL version: 7.58.0 libz 1.2.11 ssl OpenSSL/1.1.1
zip extension: OK

```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
https://xxxxx could not be fully loaded ("https://xxxxxx/packages.json" does not contain valid JSON
Parse error on line 1:
<htOCTYPE html>
^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['), package information was loaded from the local cache and may be out of date

                                                                                            
  [Seld\JsonLint\ParsingException]                                                          
  "https://xxxxx/p2/yyyyy/ourapp.json" does not contain valid JSON  
  Parse error on line 1:                                                                    
<ht                                                                       
  ^                                                                                         
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['                    
                                                                                            

update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

```

And I expected this to happen:

Package is downloaded from our repository.

**Comment by naderman** [comment] 2020-11-18 11:48
Just blocking anything containing "; curl" in the user agent seems entirely unreasonable, and something that should be fixed on the firewall in my opinion. Composer 1 did not use curl so the user agent was different then.

**Comment by johnstevenson** [comment] 2020-11-18 11:59
I think this is a clumsy attempt to block the shellshock bug, which can result in bash being tricked into running code from an environment variable (in this case HTTP_USER_AGENT).

Perhaps we could change the user-agent to:

```
Composer/2.0.7 (Linux; 4.15.0-20-generic) PHP/7.2.24 curl/7.58.0 
```

so that apparently evil tokens like "curl" are formatted as product/version?

**Comment by Seldaek** [comment] 2020-11-18 12:38
If we do anything here I'd rather switch `curl` to `cURL` if that's enough to fix it, as I like to keep consistency across versions as much as possible since we do parse the user-agent for metrics on the packagist end.

I do agree though that if it's this one firewall which needs fixing, it's not really something we should take care of.

**Comment by Danack** [comment] 2020-11-18 12:43
I disagree with customising things like useragents to work around the problems people have with firewalls....but in this case, the suggestion would be sligtly more conformant (as far as I understand it) with the spec for useragent https://tools.ietf.org/html/rfc7231#page-46

> The User-Agent field-value consists of one or more product identifiers, each followed by zero or more comments (Section 3.2 of
   [RFC7230]), which together identify the user agent software and its significant subproducts.

Although it's allowed to chuck all the sub-product info into the comment surrounded by ()'s the example given of `User-Agent: CERN-LineMode/2.15 libwww/2.17b3` does have the underlying library used listed as a separate product, rather than added in a comment field.

**Comment by ssx** [comment] 2020-11-18 13:00
This is not a composer problem.

**Comment by javiereguiluz** [comment] 2020-11-18 14:46
Just a minor comment: Composer 2 user agent seems to include "project names" instead of "the name of the project command". That's why it includes `Composer` instead of `composer` and `PHP` instead of `php`.

So, given that cURL project name is `cURL` and its command name is `curl` ... the user agent could include `cURL` for consistency. But I understand that this kind of changes are very annoying for maintainers 🙏

**Comment by gggeek** [comment] 2020-11-18 17:03
To all commenters saying "not a composer problem": I vehemently disagree with this pov.

We are writing software as means to perform a function, not to achieve ideological purity or satisfy a desire for smugness.
Even if the firewall in question is brain dead, the specific detection rule was put in place for good reason: to paper over the myriad of shell scripts which do unsafe handling of environment vars. Guess what? Safe shell scripting is _hard_ - on a close-to-impossible level. So cry me a river - instead of complaining about firewalls go deprecate bash and rewrite the complete set of shell code out there. Either that or suck it up, be a nice neighbour and do your best to cope with real life needs of customers.

Setting aside any philosophical and ideological dispute, is there any reason _not_ to implement the requested change to the user-agent header?

- if it is true that the problem started happening with Composer 2.0, then it is fair to assume that there are not many tools in the wild that parse the string. Which means that the "BC breakness" of altering it is low (ok, Packagist does the parsing, but I'm sure Jordi can fix that in 30 seconds total)
- there seems to be no standard that mandates usage of semicolons as separator for the components in the UA string
- the fix is probably about 1 line of code

**Comment by ssx** [comment] 2020-11-18 17:05
> To all commenters saying "not a composer problem": I vehemently disagree with this pov.
> 
> 
> 
> We are writing software as means to perform a function, not to achieve ideological purity or satisfy a desire for smugness.
> 
> Even if the firewall in question is brain dead, the specific detection rule was put in place for good reason: to paper over the myriad of shell scripts which do unsafe handling of environment vars. Guess what? Safe shell scripting is _hard_ - on a close-to-impossible level. So cry me a river - instead of complaining about firewalls go deprecate bash and rewrite the complete set of shell code out there. Either that or suck it up, be a nice neighbour and do your best to cope with real life needs of customers.
> 
> 
> 
> Setting aside any philosophical and ideological dispute, is there any reason _not_ to implement the requested change to the user-agent header?
> 
> 
> 
> - if it is true that the problem started happening with Composer 2.0, then it is fair to assume that there are not many tools in the wild that parse the string. Which means that the "BC breakness" of altering it is low (ok, Packagist does the parsing, but I'm sure Jordi can fix that in 30 seconds total)
> 
> - there seems to be no standard that mandates usage of semicolons as separator for the components in the UA string
> 
> - the fix is probably about 1 line of code

So when Bob comes along and his firewall is blocking anything with "poser" in it - they should have to change it again?

**Comment by gggeek** [comment] 2020-11-18 17:09
@ssx don't be disingenuous.
There might be a fine line between bug and feature in many situations, but in this case the blocking of the `; curl`, although unfortunate, has a reasonable explanation. I am not advocating for accepting _any_ request for change.
But no one on this thread has so far posted a good reason for not implementing the requested change, so I stand by what I said: the benefit is bigger than the cost.

**Comment by ssx** [comment] 2020-11-18 17:29
There’s no disingenuous comments on my part and to imply so is ill thought
out.

Changing once sets a precedent. As easy as the code change is - it’s just
as easy to add an exception to most WAFs.

There may be software out in the wild already using the current user agent
as daft as that would be, changing it now would be a breaking change if
folks are expecting it to stay as is (which is not a wild thing to expect).

**Comment by Seldaek** [comment] 2020-11-18 17:53
Everyone chills down please. It's not because Nils tweets a link that the whole community needs to chip in here about something which affects none of you. 

As I said changing above to cURL would be ok, harmless as far as I can tell, and fixes it for OP and others which may be affected but don't know yet cause they still use composer 1. What mostly worries me is that it's likely not  super easy to figure out the root cause of the issue if you're affected, so I'd rather fix it.

**Comment by Seldaek** [comment] 2020-11-18 20:37
@VadymKovalenko please confirm it works for you now after a `composer self-update --snapshot`.

**Closed** 2020-11-18 20:36 UTC
Labels: Bug

**Comment by VadymKovalenko** [comment] 2020-11-19 07:50
@Seldaek . Thanks. Everything works fine

**Comment by ondrejmirtes** [comment] 2020-11-19 09:25
I’ll chime in because doing such changes is dangerous and I usually avoid those - you’re fixing a problem that’s specific to one’s person environment. You might even break someone else’s dumb firewall rules that block the new string. This is why it should be up to the user to fix their environment. This argument doesn’t seem ideological to me at all.
