### ISSUE TITLE
include-path doesn't update for repositories

### ISSUE THREAD

**Issue by pharazon** [composer/composer#6339] opened 2017-04-08 11:04 UTC
My composer.json
```
{
    "name": "my/superproject",
    "require": {
        "my/privateproject": "dev-master",
    },
    "repositories" : [
        {
            "type":"vcs",
            "url":"git@mygit.com:my/privateproject.git"
        }
    ],
}
```
(Note! I get this to work if I move the include-path from sub-project to the main project)
```
    "include-path": [
        "vendor/my/privateproject/test/"
    ]
```

My `my/privateproject/composer.json` of :
```
{
    "name": "my/privateproject",
    "include-path": "test/"
    "autoload-dev": [
         "files": "test/mytest.php
    ]
}
```
Output of `composer diagnose`:
```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:
```
composer dump-autoload or composer update
```
I get the following output:

vendor/composer/autoload_files.php
does not have the test/ folder in the array, and I'd expect it to be there.

vendor/composer/autoload_real.php
to have the include-path but it's not there.

As noted above, I get the include-path and autoload-dev: files to work if I put it to the main project, but not if I use (custom) repository. However, both work ok if you load packages from normal sources (packagist).

**Comment by alcohol** [comment] 2017-04-09 10:05
@Seldaek could it be that `include-path` is root-only, even though the documentation does not explicitly mention this? https://getcomposer.org/doc/04-schema.md#include-path

**Comment by Seldaek** [comment] 2017-04-10 08:10
Seems to use it from the whole packageMap in AutoloaderGenerator::getIncludePathsFile `include-path` should be an array of paths though.. `my/privateproject/composer.json` seems to define a string, I don't know if that'd be the cause of the problem. Probably some other unrelated misuse I'd guess.

@pharazon if you can reproduce this with a dummy package that is open source and you can share, that would be good so we can investigate further.

**Comment by Seldaek** [comment] 2017-12-19 10:32
Auto-closing this as it's marked as support request and has not received any update in a long time.

**Closed by Seldaek** 2017-12-19 10:32 UTC
Labels: Support
