### ISSUE TITLE
Composer 2 solver error

### ISSUE THREAD

**Issue by fabpot** [composer/composer#9290] opened 2020-10-15 06:09 UTC
My `composer.json`:

```json
{
    "require": {
        "php": ">=7.4",
        "mailgun/mailgun-php": "^2.8",
        "symfony/flex": "^1"
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "symfony": {
            "require": "5.2.*"
        }
    }
}
```

When I run this command:

```
composer up
```

I get the following output:

```
  [Composer\DependencyResolver\SolverBugException]                                                                                                                                  
  Reached invalid decision id 0 while looking through (-275) for a literal present in the analyzed rule (-94|274|275|276|277|278|279|280|281|282|283|284|285|286|287|288|289|328).  
  This exception was most likely caused by a bug in Composer.                                                                                                                       
  Please report the command you ran, the exact error you received, and your composer.json on https://github.com/composer/composer/issues - thank you!
```

/cc @nicolas-grekas

**Comment by Seldaek** [comment] 2020-10-15 07:22
This is somehow caused by flex as it works fine with --no-plugins, but I am not sure why.

**Comment by nicolas-grekas** [comment] 2020-10-15 07:37
Note that this happens only with composer 2.
Also, after the first error, if I run `composer i`, I get
`Fixed package symfony/options-resolver 5.1.7.0 was not added to solver pool.`

**Comment by Seldaek** [comment] 2020-10-15 07:40
Yeah that last one is definitely a flex bug.. fixed packages should not be removed from the pool ever, no matter what the extra.symfony.require key says..

**Comment by Seldaek** [comment] 2020-10-15 07:43
I think you can use `$prePoolCreateEvent->getRequest()->getFixedOrLockedPackages()` to get the packages which you can not filter out.

**Comment by nicolas-grekas** [comment] 2020-10-15 15:01
> you can use $prePoolCreateEvent->getRequest()->getFixedOrLockedPackages()

thanks for the hint, it worked, see https://github.com/symfony/flex/pull/704

About the original issue, it happens because of Flex' `PackageFilter::removeLegacyPackages()`, but honestly I don't see anything wrong in the result of this method, it correctly filters unwanted packages.

This looks like a composer issue really.

**Comment by Seldaek** [comment] 2020-10-15 18:33
yeah it might be a composer bug anyway, but it's hard to repro because it's dependent on the filtering that flex does.. Is it correct you only filter on PRE_POOL_CREATE for Composer 2? Or are you filtering on any other event still?

**Comment by nicolas-grekas** [comment] 2020-10-15 18:41
> Is it correct you only filter on PRE_POOL_CREATE for Composer 2?

yep, that's correct, I just double checked.

**Comment by Seldaek** [comment] 2020-10-15 19:50
Ok managed to create a minimal repro case for it (https://gist.github.com/Seldaek/cb330c80c333ea191fd5f256447ffb82), definitely is a bug in v2 - it's tracked in https://github.com/composer/composer/issues/9294 now.

**Comment by naderman** [comment] 2020-10-21 15:46
As far as I can tell it's fixed with https://github.com/composer/composer/pull/9309 if you want to give that a try as well.

**Comment by Seldaek** [comment] 2020-10-21 16:46
Verified, works now with #9309 merged.

**Closed by Seldaek** 2020-10-21 16:46 UTC
Labels: Bug, Solver
