### ISSUE TITLE
Using deprecated "no-custom-installers" option does not work as expected

### ISSUE THREAD

**Issue by Wirone** [composer/composer#6410] opened 2017-05-09 09:10 UTC
Composer v1.4.1

My `composer.json`:

Not related.

Output of `composer diagnose`:

```
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install --no-custom-installers
```

I get the following output:

```
You are using the deprecated option "no-custom-installers". Use "no-plugins" instead.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
PHP CodeSniffer Config installed_paths set to <project>/vendor/frenck/php-compatibility
```

Since `InstallCommand::execute()` has this:

```
if ($input->getOption('no-custom-installers')) {
    $io->writeError('<warning>You are using the deprecated option "no-custom-installers". Use "no-plugins" instead.</warning>');
    $input->setOption('no-plugins', true);
}
```

I expected that no custom installers / plugins will be called, but as you can see in output above, they were executed. When I use new option `composer install --no-plugins` I get:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Dealerdirect\Composer\Plugin\Installers\PHPCodeSniffer\Plugin::run
PHP CodeSniffer Config installed_paths set to <project>/vendor/frenck/php-compatibility
```

It works as expected (plugins were not called, only post-install scripts).

Additionally, when I run `composer install --no-custom-installers --no-scripts` I get:

```
You are using the deprecated option "no-custom-installers". Use "no-plugins" instead.
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
```

Plugins were not called even if the same deprecated option was used, but only with additional `no-scripts` flag (which should not be related?).

**Comment by alcohol** [comment] 2017-05-09 09:36
Your composer.json is relevant. Please do not submit incomplete issues.

**Comment by Wirone** [comment] 2017-05-09 09:44
No, it's not relevant because it works the same for any project (any `composer.json`).

**Comment by Wirone** [comment] 2017-05-09 10:12
Mhm. I didn't put `composer.json` so you're closing the issue? Quite embarrassing.

What would change if I did it, since it works the same for any `composer.json`? I can add it if you make you happy with reading not related data. To be honest, I could put anything there.

**Comment by alcohol** [comment] 2017-05-09 10:13
I simply asked for it since I would like to see it. You told me it was not relevant, so I guess that makes this issue not relevant to me.

**Comment by Wirone** [comment] 2017-05-09 10:21
Jeez, `composer.json` is not relevant because Composer behaves like this with ANY `composer.json`. I don't think it should be handled like you did since issue is real, despite it's rather minor.

**Comment by alcohol** [comment] 2017-05-09 10:24
And yes, I have no way to reproduce this because I do not have your `composer.json`. Starting to see the relevance now?

**Comment by Seldaek** [comment] 2017-05-09 10:28
OK you two thanks for the pissing contest. Welcome to the internet.

I think there's enough info here.. But I don't think it's really worth much time investigating tbh, so if someone comes up with a PR fixing it great, otherwise it'll likely remain unfixed.

**Comment by Seldaek** [comment] 2020-10-27 15:47
Closing as I don't think this is going to be fixed, and has no clear repro case. Open a new issue with details if still relevant in 2.0.

**Closed** 2020-10-27 15:46 UTC
Labels: Bug
