### ISSUE TITLE
Windows bat file does not work correctly

### ISSUE THREAD

**Issue by WouterJ** [composer/composer#4280] opened 2015-07-21 19:14 UTC
The Windows bat file uses the special `%~dp0` thing. This introduces a very strange problem with the installation of Composer:

* When executing composer like `composer`, `%~dp0` in the bat file refers to the location of the batch (`C:\ProgramData\ComposerSetup\bin`).
* When executing composer like `"composer"`, `%~dp0` in the bat file refers to the current directory (e.g. `C:\Users\Wouter\sf-world\symfony-27`).

This introduces a problem when using composer with the Symfony Process component, as it puts double quotes around every passed argument/prefix.

**Comment by alcohol** [comment] 2015-07-21 20:27
Can you elaborate about what you mean with "when executing composer like"? Executing from where? How? Some code to reproduce the issue maybe?

**Comment by WouterJ** [comment] 2015-07-21 21:16
Sorry for being unclear. Let's make it a bit more clear:

When using the Windows installer, a bat file is created in `C:\ProgramData\ComposerSetup\bin\composer.bat` containing:
```bash
@ECHO OFF
php "%~dp0composer.phar" %*
```
The `%~dp0` part in here references the driver name (`d`) and path (`p`) to the current bat file. The windows installer also adds this path to the PATH env variable, so `composer` can be run.

Now, when running `composer` in the terminal, everything works fine (so, just `composer`). `%~dp0` resolves to `C:\ProgramData\ComposerSetup\bin\` and the phar file is executed by PHP.

However, when running `"composer"` (note the double quotes around the command name this time), things suddently change and `%~dp0` resolves to the current path. So imagine executings this command in `C:\`, the bat file now tries to execute `C:\composer.phar` with php. This obviously errors...

**Comment by alcohol** [comment] 2015-07-21 21:24
Yeah I don't understand what you mean with `"composer"`. Why would you quote it? Where do you quote it? How do you run it? You didn't answer my question at all :-/

**Comment by WouterJ** [comment] 2015-07-21 21:28
In the Windows terminal:
```
C:\Users\Wouter\sf-world\symfony-demo> composer update
... everything runs fine

C:\Users\Wouter\sf-world\symfony-demo> "composer" "update"
Could not open input file: C:\Users\Wouter\sf-world\symfony-demo\composer.phar
```

I use the Symfony Process component to automate some tasks, one of them includes updating Composer dependencies. To avoid errors on illegal characters, the Symfony Process component [escapes all](https://github.com/symfony/Process/blob/master/ProcessBuilder.php#L268) process arguments by surrounding them with double quotes at least. Executing that process fails, as of the double quotes.

**Comment by alcohol** [comment] 2015-07-21 21:30
But composer is the process, not an argument. Why would it quote it?

**Comment by WouterJ** [comment] 2015-07-21 21:33
```php
$processBuilder = (new ProcessBuilder())->setPrefix('composer');
$process = $processBuilder->setArguments(['update'])->getProcess();

$process->getCommandLine(); // "composer" "update"
```
That's how the Process component works. I don't know why it was developed as such.

**Comment by alcohol** [comment] 2015-07-21 21:36
Odd. I don't know enough about windows to understand what the difference between `console` and `"console"` is on the command line. I know in Linux quoting a binary name can help you get around aliases.

**Comment by alcohol** [comment] 2015-07-21 22:05
I would recommend just using Process directly, not using the ProcessBuilder.

**Comment by alcohol** [comment] 2015-07-21 22:09
Are you sure you set the cwd in which it should run? (`setWorkingDirectory()`)

**Comment by cs278** [comment] 2015-07-21 23:25
@alcohol The point is you shouldn't need to, it's resolving `composer` using the PATH variable.

I can confirm:

```
C:\>test
%0 = test
%~dp0 = H:\Chris\AppData\Local\Temp\test\
%~z0 = 66

C:\>"test"
%0 = "test"
%~dp0 = C:\
%~z0 =

C:\>H:\Chris\AppData\Local\Temp\test\test
%0 = H:\Chris\AppData\Local\Temp\test\test
%~dp0 = H:\Chris\AppData\Local\Temp\test\
%~z0 = 66

C:\>"H:\Chris\AppData\Local\Temp\test\test"
%0 = "H:\Chris\AppData\Local\Temp\test\test"
%~dp0 = H:\Chris\AppData\Local\Temp\test\
%~z0 =
```

Seems to me like this is a bug in the interpreter at least on 7.

Test script:

```bat
@echo off

echo %%0 = %0
echo %%~dp0 = %~dp0
echo %%~z0 = %~z0
```

**Comment by alcohol** [comment] 2015-07-22 07:07
By "on 7" you mean Windows 7? @WouterJ can you confirm you are also using Windows 7?

/cc @johnstevenson am I correct in assuming you are our Windows guru?

**Comment by WouterJ** [comment] 2015-07-22 07:43
@alcohol I'm on Windows 8.1 (but I don't think cmd changes a lot between Windows releases).

**Comment by johnstevenson** [comment] 2015-07-22 14:30
@alcohol Definately not a guru! (but I did write the installer, for what it's worth).

If you type ```cmd /c "composer"``` into a cmd prompt, then it works fine. However, the Symfony component wraps the command line in double quotes, something like ```cmd /c ""composer""``` which breaks, much like typing ```"composer"``` into a cmd prompt.

@WouterJ The current solution is to not quote the process name. We should probably use the absolute path in the .bat file in future, as you suggest. Thanks.

**Comment by stof** [comment] 2015-07-22 14:54
@WouterJ the issue is that the binary name could still have special chars needing escaping (for instance if you pass the full path to composer rather than using only the short name and relying on the PATH to resolve it). This is why quoting the first element in the ProcessBuilder cannot be skipped.

**Comment by rquadling** [comment] 2015-07-22 16:47
The ```~``` in batch script arguments, variables, etc, removes leading and trailing quotes.

You can see the documentation by running ```CALL /?``` at a Windows command prompt.

```
Calls one batch program from another.

CALL [drive:][path]filename [batch-parameters]

  batch-parameters   Specifies any command-line information required by the
                     batch program.

If Command Extensions are enabled CALL changes as follows:

CALL command now accepts labels as the target of the CALL.  The syntax
is:

    CALL :label arguments

A new batch file context is created with the specified arguments and
control is passed to the statement after the label specified.  You must
"exit" twice by reaching the end of the batch script file twice.  The
first time you read the end, control will return to just after the CALL
statement.  The second time will exit the batch script.  Type GOTO /?
for a description of the GOTO :EOF extension that will allow you to
"return" from a batch script.

In addition, expansion of batch script argument references (%0, %1,
etc.) have been changed as follows:


    %* in a batch script refers to all the arguments (e.g. %1 %2 %3
        %4 %5 ...)

    Substitution of batch parameters (%n) has been enhanced.  You can
    now use the following optional syntax:

        %~1         - expands %1 removing any surrounding quotes (")
        %~f1        - expands %1 to a fully qualified path name
        %~d1        - expands %1 to a drive letter only
        %~p1        - expands %1 to a path only
        %~n1        - expands %1 to a file name only
        %~x1        - expands %1 to a file extension only
        %~s1        - expanded path contains short names only
        %~a1        - expands %1 to file attributes
        %~t1        - expands %1 to date/time of file
        %~z1        - expands %1 to size of file
        %~$PATH:1   - searches the directories listed in the PATH
                       environment variable and expands %1 to the fully
                       qualified name of the first one found.  If the
                       environment variable name is not defined or the
                       file is not found by the search, then this
                       modifier expands to the empty string

    The modifiers can be combined to get compound results:

        %~dp1       - expands %1 to a drive letter and path only
        %~nx1       - expands %1 to a file name and extension only
        %~dp$PATH:1 - searches the directories listed in the PATH
                       environment variable for %1 and expands to the
                       drive letter and path of the first one found.
        %~ftza1     - expands %1 to a DIR like output line

    In the above examples %1 and PATH can be replaced by other
    valid values.  The %~ syntax is terminated by a valid argument
    number.  The %~ modifiers may not be used with %*
```

Not sure if this helps diagnose any issues you are having.

**Comment by rquadling** [comment] 2015-07-22 16:58
https://github.com/php/php-src/blob/0437aa2abf1eb494e4555d7d4dfbdbf566a59bdc/TSRM/tsrm_win32.c#L540 shows the way PHP handles opening a windows command via the shell. It uses ```cmd.exe /c "<command>"```. So, if Symfony is adding another set of quotes, that's not going to work unless the ```/s``` attribute is added, in which case cmd.exe will strip off the leading/trailing ```"``` to the command.

**Comment by stof** [comment] 2015-07-22 17:39
@rquadling Symfony is escaping each part of the command. this does not replace the fact that ``/c`` expects the whole command to be quoted

**Comment by rquadling** [comment] 2015-07-23 08:38
But with ```/s``` the output quotes are removed. I think this is to allow PHP to create scripts that are compliant for both Windows and non-Windows, but you need to incorporate the ```/s``` yourself. Not ideal.

**Comment by Seldaek** [comment] 2016-02-20 16:18
So what do we do here? It doesn't seem like a huge problem but it could be fixed in the installer I think. In the docs we also recommend using this https://getcomposer.org/doc/00-intro.md#manual-installation but there I think it's best to keep it as is for ease-of-copy-pasting's sake.

Ideally there would be a way to achieve this without hardcoding the path and with quoted `"composer"` support. Maybe using `%CD%` and `%~0` but that would require some string manipulation which is quite a pain.

**Comment by rquadling** [comment] 2016-02-22 12:11
Does passing ``['bypass_shell'=>true]`` as the options for the ProcessBuilder (or directly to Process), make any difference?

**Comment by rquadling** [comment] 2016-02-22 12:14
Where is the ``composer.bat`` file on your machine. What happens if you supply the full path (including the ``.bat`` part).

**Comment by curry684** [comment] 2016-02-22 12:26
To answer an age old question:

> Odd. I don't know enough about windows to understand what the difference between console and "console" is on the command line. I know in Linux quoting a binary name can help you get around aliases.

It's to prevent issues with whitespace. In Linux (or at least bash) you would use `change\ dir \to /my\ folder` to run the command `change dir to` with a single argument `my folder`. In Windows the only supported method for that is quote grouping, so `"change dir to" "my folder"`. That's why Symfony's Process inserts them by default, as it wants to be agnostic of these implementation details.

**Comment by curry684** [comment] 2016-04-05 15:07
Done a bit more research on this and I consider it unfixable. If the invocation is quoted all the default expansion methods like `~dp0` won't work, so indeed the only workaround then is doing PATH lookups, which may or may not end up with different paths if you have multiple copies. So imho this is currently as good as it gets.

Given that the issue was originally about interaction with Symfony's Process components - it has [separate facilities for running PHP code](http://symfony.com/doc/current/components/process.html#executing-php-code-in-isolation) that may come in useful.

**Comment by Seldaek** [comment] 2016-04-11 16:47
Agreed, seems to work for most people as is, if you want to programmatically call composer maybe do it at the php level mimicking `bin/composer` with an Console\Input\ArrayInput?

**Closed by Seldaek** 2016-04-11 16:47 UTC
Labels: Bug

**Comment by johnstevenson** [comment] 2016-07-26 10:40
This is fixable using the ` %~dp$PATH:I` syntax mentioned above (and found in the help: `for /?` or `call /?` topics) which:

>  searches the directories listed in the PATH
                   environment variable for %I and expands to the
                   drive letter and path of the first one found.

We can test whether we need to use this method by checking if the `%~x0` expansion results in a file extension (which should of course be `.bat`). If it doesn't, then we can only have got here by a path lookup, so the path expansion will work correctly.

```bat
if [%~x0] == [] (    
    php "%~dp$PATH:0composer.phar" %*
) else (
    php "%~dp0composer.phar" %*
)
```
@Seldaek  @curry684

**Comment by Seldaek** [comment] 2016-07-28 12:01
If that's something you can improve in the Setup.exe, cool, otherwise I am not sure what this is about anymore :)
