### ISSUE TITLE
Composer does not detect new package version

### ISSUE THREAD

**Issue by fabiojaniolima** [composer/composer#6720] opened 2017-10-04 13:47 UTC
In version 1.5.2 the composer does not detect recent and stable versions of new packages.

Example:
```
composer create-project fabiojaniolima / webupload --no-dev
```
Version 1.0.0 has been installed

Days later was released version 1.1.0, I tried to create a new project:
```
composer create-project fabiojaniolima / webupload --no-dev
```
Version 1.0.0 was reinstalled

Played clear composer but did not solve.

Solution:
```
composer clear
composer update
composer create-project fabiojaniolima / webupload --no-dev
```
The "composer update" command caused an error, but allowed us to proceed with the download of the new package

Details:
- PHP v7.1.10
- Composer v1.5.2
- Debian 9.1

**Comment by Jean85** [comment] 2017-10-09 13:51
Maybe your local Composer's cache is interfering?
Try to first issue a `composer clear-cache` to clean it.

**Comment by stof** [comment] 2017-10-09 14:02
The command `composer create-project fabiojaniolima/webupload2 --no-dev` looks weird, as there is no `fabiojaniolima/webupload2` package on Packagist.

and running a `composer update` should fail outside an existing composer-based project, while running `composer create-project` is about creating a new project. So I find your "solution" really weird.

**Comment by fabiojaniolima** [comment] 2017-10-09 16:51
Fixed for webupload. The "composer clear-cache" command does not resolve, I have to run composer update even giving error so I can only install the project in the latest version.

**Comment by Seldaek** [comment] 2018-04-13 09:32
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.

**Closed by Seldaek** 2018-04-13 09:32 UTC
Labels: Support

**Comment by xabbuh** [comment] 2018-11-10 14:16
@Velliz Is this still an issue for you? I can see the expected version on Packagist.

**Comment by Velliz** [comment] 2018-11-10 18:09
@xabbuh Update: After reseting router settings and restarting my wifi all is going well. Still don't know why that hapen. but the problem solved! Thanks :D

**Comment by thirsch** [comment] 2021-08-04 06:25
I know, this issue is a few years old. But if anyone else is also getting here because of composer create-project picking an outdated version (not only packagist, also for a private repo), it might also be caused by your local php version. If for example there is a package 1.0 (php >= 5.6) and a package 2.0 (php >= 8.0) and you have php 7.3, it will always pick the version 1.0. You could easily solve it by using a newer php version or by appending --ignore-platform-reqs to your command.
