### ISSUE TITLE
Allow an esy way to force-reinstall a specific library

### ISSUE THREAD

**Issue by gggeek** [composer/composer#5693] opened 2016-09-19 17:00 UTC
The usecase: the source code for one dependency got messed up. I would **rm -rf vendor/* && composer install**, but one of the packages (not the one I want to 'fix') can not be downloaded any more (it is hosted on a private repo, to which I do not have access keys at this time).

Please excuse me if solving this is already possible, but I could not find an easy solution just by googling around, short of executing **composer update that/package**

**Comment by alcohol** [comment] 2016-09-19 17:35
The workaround you found (solution) is the only one I can think of from the top of my mind. There is no `composer install vendor/package` support.

**Comment by stof** [comment] 2016-09-19 17:43
Instead of deleting the whole vendor folder, you can remove only the package you messed up, and then run composer install.
This way, you would not need to redownload the other packages

**Comment by alcohol** [comment] 2016-09-19 18:12
Ah right. Yes. I misread. I thought he was deleting the package specifically from the `vendor` dir, not the whole directory. What @stof said makes more sense.

**Comment by Seldaek** [comment] 2016-09-29 06:52
In any case, duplicate of #3112

**Closed by Seldaek** 2016-09-29 06:52 UTC
Labels: Support
