### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by kurtgenc** [composer/composer#5201] opened 2016-04-15 18:09 UTC
Trying to install composer on linux.  I tried both downloading a specific version and running the script on your getting started page.  Issue is composer.json is not found on install, and there is no instructions related to json on your web, as displayed from the install message below -- -what am I missing here?

Composer could not find a composer.json file in /home/dev
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section

Notes say basically to download and then "now just run php composer.phar".  Nothing about json in the getting started section is found.
Would be nice to streamline the install, you seem to have instructions all over the place, keep it straight. Hope you update and improve this.

**Comment by kurtgenc** [comment] 2016-04-15 18:17
The instructions are not under "getting started", they're under "basic instructions", talking about the composer.json file.  BTW, If I'm running a 1st time install of a product, it doesn't make sense to fail on a project file requirement.

**Comment by curry684** [comment] 2016-04-15 18:37
Please provide more detailed reproduction steps - copy/paste the exact sequence of commands you're issuing and what they are returning at what point. The instructions and installer haven't changed that much in a while and tons of people are installing Composer on Linux every day, so the challenge is to know what's different on your machine. We cannot determine that just from a generic error.

**Comment by alcohol** [comment] 2016-04-18 06:49
@curry684 he is arguing that the documentation isn't clear enough.

@kurtgenc Please let us know how we can improve the documentation. I know it isn't very cutting edge. In my personal opinion though, I thought it was quite clear that getting started focusses only on "installing" composer. At the very last step (https://getcomposer.org/doc/00-intro.md#using-composer) it directs you to the next part of the guide, which introduces details about composer.json. If any of this could be made more clear though, please let us know how.

Pull requests towards our documentation are always appreciated. :-)

**Comment by Seldaek** [comment] 2016-04-19 09:46
Yeah I don't know if we can really clarify this much. PRs are very much appreciated but I'll close this because it has no clear action points and it seems like most people go through the process without problems?

**Closed by Seldaek** 2016-04-19 09:46 UTC
Labels: Documentation
