### ISSUE TITLE
1.2.0 bug with variation detection on custom VCS repository

### ISSUE THREAD

**Issue by josephmcdermott** [composer/composer#5555] opened 2016-07-27 11:01 UTC
The latest (brilliant) feature might have a slight bug in it:

> Added detection of HEAD changes to the status command. If you git checkout X in a vendor directory for example it will tell you that it is not at the version that was installed

The report from composer status -v is also returning repositories that are NOT changed, so I am getting for example:

```
someVendor/someModule:
    From 1.1.0 to 1.1.0
```

This appears to only happen for modules that I have defined a custom "repositories" entry in order to retrieve my own version of a module from somewhere other than packagist.

When I `cd` in to the the vendor/someVendor/someModule and run `git remote -v` I see different remotes for `composer` and `origin`, so perhaps this has something to do with the comparison giving false positives?

**Comment by SchizoDuckie** [comment] 2016-08-08 08:48
It looks like status -v is a bit confused about tag commit hash vs actual commit hash that has the tag on it.

**Comment by Seldaek** [comment] 2016-09-10 10:13
Can you give details as to how to reproduce that? Step-by-step with a composer.json and the custom repos you have (or at least a public repo that has the same effect). That would help greatly in reproducing and fixing this.

**Comment by Seldaek** [comment] 2016-11-06 16:01
Ping? :)

**Comment by josephmcdermott** [comment] 2016-11-07 11:47
To be honest, no I cannot reproduce it :( I get it from time to time with private projects hosted on BitBucket. Right now for instance for a private project I have:

```
composer status -vvv
/vendor/someVendor/someModule:
    From dev-master (7a1d0bff96788c8ec2153a4cbd2689a7136d25f9) to dev-master (2614ca5f9a13ab3804e1f71cc6da0defbd85cc29)
```

BitBucket lists a commit for the first, but nothing for the second. Although 'git checkout' with either revision results in exactly the same and works just fine. It's like the revision has two different hashes for some reason...

**Comment by Seldaek** [comment] 2016-11-07 12:37
Well if you can build a repro case using a public bitbucket repo maybe we can have a look, but otherwise I'd rather close this..

**Comment by stof** [comment] 2016-11-07 14:37
Having 2 different hashes for a tag might be related to the usage of annotated tags in git (which have a hash on their own)

**Comment by slbmeh** [comment] 2016-11-08 04:56
I don't know what would result in identical states with multiple hashes.  I noticed it a few times before I submitted the PR, but it was always the result of a PR.  The difference between the HEAD commit on my branch and the non-ff merge commit introduced by accepting the PR.

**Comment by oscherler** [comment] 2016-11-11 13:07
I’ve experienced the same thing with private packages hosted on BitBucket and served by Toran Proxy. In my case, I have a `preferred-install` to source for those packages, and Composer points out that the commit is checked out instead of the tag.

However, I can’t reproduce it on a new project, so there must be something else going on. I’ll continue investigating if it happens again.

It’s not really affecting me, though. I’m posting to give the information I have, not because I don’t want you to close it.

**Comment by Seldaek** [comment] 2016-12-06 21:17
Closing as I don't see a clear way forward here sorry.

**Closed by Seldaek** 2016-12-06 21:17 UTC
Labels: Bug

**Comment by dkd-friedrich** [comment] 2016-12-13 12:08
I could reproduce the described issue, using Composer 1.2.4 with private repositories and our EXT:solr GitHub repository (https://github.com/TYPO3-Solr/ext-solr).

It seems that there is a problem with annotated and lightweight tags, `composer status -v` reports version variations if the requested version is an annotated tag. 

```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
You have version variations in the following dependencies:
.../typo3conf/ext/solr:
    From 3.1.1 (b08330d1233701a288cfae623962683e0e85a696) to dev-master (da55382f68a8d9a929a33745a7f1864e6da6d392)
````

Version 3.1.1 is an annotated tag and as far as I can see Composer misses to dereference the tag and compares the hashes of the tag and the referenced commit.

```
$ git show-ref --head -d | grep "tags/3.1.1"
b08330d1233701a288cfae623962683e0e85a696 refs/tags/3.1.1
da55382f68a8d9a929a33745a7f1864e6da6d392 refs/tags/3.1.1^{}
```

You can reproduce this issue by:

```
composer require "typo3/cms:~6.2"
composer config repositories.apache-solr-for-typo3 git https://github.com/TYPO3-Solr/ext-solr.git
composer require "apache-solr-for-typo3/solr:3.1.1" 
composer status -vv
```

I'm not sure if it's relevant here, but I want to mention that our release branch has a non-comparable version name: `release-3.1.x`.

**Comment by timohund** [comment] 2016-12-13 12:34
@Seldaek

Doing the same with a lightweigt tag (5.1.1 is a lightweight tag) works:

```bash
composer require "typo3/cms:~7.6"
composer config repositories.apache-solr-for-typo3 git https://github.com/TYPO3-Solr/ext-solr.git
composer require "apache-solr-for-typo3/solr:5.1.1" 
composer status -vv
```

I think this does not occure that often because tags created on github are lightweight tags by default. But afaik (correct me if i am wrong) annotated tags are the proposed tags for releases.

From my undestading the status result should be the same, independet from the type of tagging.

**Comment by Seldaek** [comment] 2016-12-18 13:52
Thanks for the details guys, https://github.com/composer/composer/commit/1bc8b702ca40ec9f912539cecdb00b61a3109c78 hopefully fixes it, I'd appreciate if you can try again after a `composer self-update --snapshot` - note that it'll require that the package be updated/reinstalled before the changes take effect, as it changes which version of the tag we install (it now prefers annotated) and not the way the status command acts.

**Comment by dkd-friedrich** [comment] 2016-12-19 14:46
Thanks, looks good! I now couldn't reproduce this issue, I tested with GitHub, private repositories and different repository types (git, vcs).
