### ISSUE TITLE
Composer tries/fails to remove PHP extensions when one is listed in "provide"

### ISSUE THREAD

**Issue by paragonie-scott** [composer/composer#7086] opened 2018-02-06 22:04 UTC
My `composer.json`:

https://github.com/paragonie/sodium_compat/blob/a511834959a072000b7c328e8f02b957d4fd8430/composer.json

Output of `composer diagnose`:

```Cannot create cache directory /home/scott/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/scott/.composer/cache/files/, or directory is not writable. Proceeding without cache
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.3
PHP version: 7.2.1-1+ubuntu17.10.1+deb.sury.org+1
PHP binary path: /usr/bin/php7.2
```

When I run this command:

```
composer update -vv
```

I get the following output:

```
Cannot create cache directory /home/scott/.composer/cache/repo/https---packagist.org/, or directory is not writable. Proceeding without cache
Cannot create cache directory /home/scott/.composer/cache/files/, or directory is not writable. Proceeding without cache
Loading composer repositories with package information
Updating dependencies (including require-dev)
Dependency resolution completed in 0.075 seconds
Analyzed 1654 packages to resolve dependencies
Analyzed 83727 rules to resolve dependencies
Dependency resolution completed in 0.000 seconds
Package operations: 0 installs, 0 updates, 1 removal
Removals: ext-sodium

                                                
  [InvalidArgumentException]                    
  Package is not installed: ext-sodium-7.2.1.0  
                                                

Exception trace:
 () at phar:///usr/bin/composer/src/Composer/Installer/LibraryInstaller.php:123
 Composer\Installer\LibraryInstaller->uninstall() at phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php:211
 Composer\Installer\InstallationManager->uninstall() at phar:///usr/bin/composer/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar:///usr/bin/composer/src/Composer/Installer.php:588
 Composer\Installer->doInstall() at phar:///usr/bin/composer/src/Composer/Installer.php:227
 Composer\Installer->run() at phar:///usr/bin/composer/src/Composer/Command/UpdateCommand.php:161
 Composer\Command\UpdateCommand->execute() at phar:///usr/bin/composer/vendor/symfony/console/Command/Command.php:242
 Symfony\Component\Console\Command\Command->run() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:842
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/bin/composer/src/Composer/Console/Application.php:251
 Composer\Console\Application->doRun() at phar:///usr/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/bin/composer/bin/composer:58
 require() at /usr/bin/composer:24

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

And I expected this to happen:

I expected that `ext-sodium`'s presence in the "provide" list, as a PHP extension, wouldn't trigger package removal logic and break the update process.

**Comment by ravage84** [comment] 2018-02-09 19:34
I can confirm this behavior with Composer 1.6.3 and 3c09c0ab2a4b1acc13807fb7ff012a18d67a3a38

As fas as my debugging went it seems Composer finds no reason to install the extension, handles it as "undecided" in the resolver and then decides to remove it.

**Comment by glensc** [comment] 2019-05-27 14:21
just a minor nit, maybe it should be version that you provide, not asterisk?

```json
  "provide": {
    "ext-libsodium": "7.0.0",
    "ext-sodium": "7.2.0"
  }
```

i.e provide version what version API the polyfill is compatible. maybe even makes this bug not relevant.

**Comment by glensc** [comment] 2019-05-27 14:23
looks like there's confirmation to that by @terrafrost:

https://github.com/phpseclib/mcrypt_compat/pull/2#discussion_r260247018

**Comment by mstyles** [comment] 2020-07-07 21:34
Ran into this today, that was a fun issue to debug... Is there any reason why paragonie's fix hasn't been merged? https://github.com/paragonie/composer/commit/47bcdd55b482e2a6dad7097c7f9d6e37a26865f7

**Comment by Seldaek** [comment] 2020-07-08 08:14
The fix you linked is not appropriate IMO. This however appears to be fixed in 2.0 already, if you can try and confirm after a `composer self-update --snapshot`.

**Comment by mstyles** [comment] 2020-07-08 14:59
Confirmed. Using 2.0 I can no longer reproduce the issue. 👍

**Comment by Seldaek** [comment] 2020-07-08 18:24
Alright thanks, closing then.

**Closed by Seldaek** 2020-07-08 18:24 UTC
Labels: Bug, Solver
