### ISSUE TITLE
composer show --tree fails when a package requires a dependency with self.version

### ISSUE THREAD

**Issue by clamburger** [composer/composer#4999] opened 2016-03-04 00:25 UTC
Example:

```
$ composer require zf1/zend-pdf
$ composer show

zf1/zend-cache     1.12.11 Zend Framework 1 Cache package
zf1/zend-exception 1.12.11 Zend Framework 1 Exception package
zf1/zend-log       1.12.11 Zend Framework 1 Log package
zf1/zend-memory    1.12.11 Zend Framework 1 Memory package
zf1/zend-pdf       1.12.11 Zend Framework 1 Pdf package

$ composer show --tree

zf1/zend-pdf 1.12.11 Zend Framework 1 Pdf package
├──php >=5.2.11
├──zf1/zend-exception self.version

                                         
  [ErrorException]                       
  Illegal offset type in isset or empty  
                                         

show [--all] [-i|--installed] [-p|--platform] [-a|--available] [-s|--self] [-N|--name-only] [-P|--path] [-t|--tree] [--] [<package>] [<version>]
```

`composer show` without --tree works fine.

**Comment by curry684** [comment] 2016-03-04 07:24
@barryvdh that fix is invalid - that function requires a string argument already by phpDoc. The error was a level higher where the show command didn't correctly follow up on pre-parsing the constraint if `self.version` was specified (`ShowCommand.php:539`)..

**Comment by barryvdh** [comment] 2016-03-04 07:29
Can't we cast it to string in the ShowCommand instead of checking it's as string, or does that not give the expected result?
I thought about doing that there, but wasn't sure if this could happen from a different place also. But if it's in the phpdocs, I guess we *could* assume it's a string already.

**Comment by curry684** [comment] 2016-03-04 08:01
If it's in the phpDoc we *must* assume it's a string already, it's supposed to be a binding contract. Because now that generic function incurs extra overhead on all invocations that do follow the declaration, and in the future you will get painful regression on this issue when PHP7 arrives and we convert the function signature to `parseConstraints(string $constraints) : ConstraintInterface` per its docs. Also it doesn't really make sense to 'parse' a ContraintInterface into itself.

Casting it in the `ShowCommand` is also an option but rather pointless as it implies casting a `ConstraintInterface` to a string for the sole purpose of resolving it into a `ConstraintInterface` again :wink:

**Comment by barryvdh** [comment] 2016-03-04 08:15
No indeed, if it's already a ConstraintInterface, let's use that :)

**Closed** 2016-03-04 15:39 UTC
