### ISSUE TITLE
A 404 for a required bitbucket repository provides a cryptic error message.

### ISSUE THREAD

**Issue by Everspace** [composer/composer#6763] opened 2017-10-24 16:15 UTC
My `composer.json`:

```json
{
    "name": "example/example",
    "description": "The website",
    "require": {
        "composer/installers": "~1.0",
        "myorg/plugin_myplugin": "dev-master",
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://bitbucket.org/myorg/plugin_plugin_myplugin_typo"
        }
    ]
}
```

Output of `composer diagnose`: irrelevant

When I run this command:

```
composer install
```

I get the following output:

```

  [Composer\Downloader\TransportException]
  The "?pagelen=100&fields=values.name%2Cvalues.target.hash%2Cnext&sort=-target.date" file could not be downloaded: failed to open stream: Resource tempor
  arily unavailable

```

And I expected this to happen:

The error from

```
composer install -vv
``` 

is much more useful to show that I had messed up typing the package name:

```
 [Composer\Downloader\TransportException]
 The "https://api.bitbucket.org/2.0/repositories/myorg/plugin_plugin_myplugin_typo?fields=-project%2C-owner" file could not be downloaded (HTTP/1.1
 404 Not Found)
```

And that I had requested an item that doesn't exist (404).

**Comment by clivewalkden** [comment] 2017-11-08 16:22
I'm getting this a lot when trying to deploy my Magento projects, it is becoming a real pain and slowing down a process which has been great until recently. I don't think it is rate limits causing the issue.

I did think it might be missing author information in the composer file as some of the modules didn't include it by default. I've remedied this but am still getting the issue. 

It is also affecting my Satis repositories as well with the same error being reported. Is there someone that could point us in the right direction, I don't mind testing workarounds, although it is sporadic so isn't something easily testable.

**Comment by brandontamm** [comment] 2017-11-17 22:25
+1 ... getting this all the time when using Bitbucket Pipelines for continuous integration

**Comment by Seldaek** [comment] 2017-11-29 09:52
I'm not quite sure what's happening here.. Is it just temporary failures on the Bitbucket API? Or rather rate limiting because you're hitting it too much? The message would suggest it's an issue on their end more than on ours.

Do you have a way to reproduce it with a public repository?

**Comment by brandontamm** [comment] 2017-11-29 14:36
Honestly, I can't remember the reason I +1'ed this. I remember getting the error, just not the reason. 

I *think* that I may have changed the repo location and name and changed it in the "require" section of my main project and forgot to change it in the composer.json of the actual repo... Are you guys still seeing this issue.

That may not be the case - I may have just resolved the error and kept moving on but I also develop Magento projects so the error and @clivewalkden having the issue made me bump it.

**Comment by brandontamm** [comment] 2017-11-29 14:40
That's what it is @Seldaek - he is looking for a more descriptive error message when we do not match the package names correctly in composer.json...one step further - it would be nice if we somehow knew we screwed up the package name in the depencies actual composer.json...

i.e. (In Main Project composer.json)

{
    "name": "example/example",
    "description": "The website",
    "require": {
        "composer/installers": "~1.0",
        "myorg/plugin": "dev-master",
    },
    "repositories": [
        {
            "type": "vcs",
            "url": "https://bitbucket.org/myorg/plugin"
        }
    ]
}

I.E. - In myorg/plugin" composer.json

{
    "name": "myorg/plugin_typo_oops_i_had_too_much_coffee",
    "license": "OSL-3.0",
....
}

**Comment by Everspace** [comment] 2017-11-30 19:18
brandomtamm has it correct.

I guess it would be more apt to say that when I specify an incorrect package sitting on a bitbucket repository (messing up the package), or specify an incorrect vcs repository (messing up on my workspace) involving bitbucket, the error message is confusing and misleading.

Primarily it is a stranger error eating up a more normal error. In the full stack-trace by increasing the verbosity, you get a clearer 404 as the reason why the there is a "resource temporarily unavailable".

With the verbosity increased you get something like the following instead:

```
Reading ./composer.json
Loading config file %HOME%/Composer/auth.json
Loading config file ./composer.json
Checked CA file C:/tmp/composer-cacert-e78c8ab7b4432bd466e64bb942d988f6c0ac91cd785017e46
5bdc96d42fe9dd0.pem: valid
Executing command (C:/workspace/my_project): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: ~/Composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading C://workspace/my_project/vendor/composer/installed.json
Loading plugin Composer\Installers\Plugin
Running 1.5.2 (2017-09-11 16:59:25) with PHP 7.0.23 on Windows NT / 10.0
Loading composer repositories with package information
Downloading https://wpackagist.org/packages.json
Writing ~/Composer/repo/https---wpackagist.org/packages.json into cache
Downloading https://api.bitbucket.org/2.0/repositories/myorg/my_pluginWITH_A_TYPO?fields=-project%2C-owner
Downloading https://api.bitbucket.org/2.0/repositories/myorg/my_pluginWITH_A_TYPO?fields=-project%2C-owner
Downloading https://api.bitbucket.org/2.0/repositories/myorg/my_pluginWITH_A_TYPO?fields=-project%2C-owner


  [Composer\Downloader\TransportException]
  The "https://api.bitbucket.org/2.0/repositories/myorg/my_pluginWITH_A_TYPO?fields=-project%2C-owner" file could not be downloaded (HTTP/1.1 404 Not Found)


Exception trace:
 () at phar://C:/tools/composer.phar/src/Composer/Util/RemoteFilesystem.php:382
 Composer\Util\RemoteFilesystem->get() at phar://C:/tools/composer.phar/src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar://C:/tools/composer.phar/src/Composer/Repository/Vcs/VcsDriver.php:165
 Composer\Repository\Vcs\VcsDriver->getContents() at phar://C:/tools/composer.phar/src/Composer/Repository/Vcs/BitbucketDriver.php:355
 Composer\Repository\Vcs\BitbucketDriver->getContentsWithOAuthCredentials() at phar://C:/tools/composer.phar/src/Composer/Repository/Vcs/BitbucketDriver.php:95
 Composer\Repository\Vcs\BitbucketDriver->getRepoData() at phar://C:/tools/composer.phar/src/Composer/Repository/Vcs/HgBitbucketDriver.php:33
 Composer\Repository\Vcs\HgBitbucketDriver->getRootIdentifier() at phar://C:/tools/composer.phar/src/Composer/Repository/VcsRepository.php:140
 Composer\Repository\VcsRepository->initialize() at phar://C:/tools/composer.phar/src/Composer/Repository/ArrayRepository.php:185
 Composer\Repository\ArrayRepository->getPackages() at phar://C:/tools/composer.phar/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at phar://C:/tools/composer.phar/src/Composer/Installer.php:376
 Composer\Installer->doInstall() at phar://C:/tools/composer.phar/src/Composer/Installer.php:223
 Composer\Installer->run() at phar://C:/tools/composer.phar/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar://C:/tools/composer.phar/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar://C:/tools/composer.phar/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/tools/composer.phar/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar://C:/tools/composer.phar/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar://C:/tools/composer.phar/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar://C:/tools/composer.phar/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar://C:/tools/composer.phar/bin/composer:54 require()
 at C:\tools\composer.phar:24

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--n
o-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative]
 [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
```

Where it is much more clear that a there is a typeo or something instead of you looking like you have bumped into a rate limitation or something like a .

**Comment by gdevdeiv** [comment] 2020-06-22 14:06
Make sure you have your auth.json updated! (Oauth keys from Bitbucket, more info here https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html)

**Comment by michaelphillpotts** [comment] 2020-11-25 12:25
A solution that worked for me for this exact error was to change the repository type to `git` 

Such as:
```
"repositories": [
    {
      "type": "git",
      "url": "https://bitbucket.org/....."
    }
  ]
```

**Comment by Seldaek** [comment] 2022-05-15 11:50
Closing as we have fixed a few bitbucket issues in the last few months, if you can still reproduce this tho let me know and I can reopen.

**Closed by Seldaek** 2022-05-15 11:50 UTC
Labels: Bug
