### ISSUE TITLE
composer throws exceptions on invalid dependency clauses

### ISSUE THREAD

**Issue by fgm** [composer/composer#9192] opened 2020-09-08 17:16 UTC
My `composer.json`:

```json
{
  "description": "bug demo",
  "license": "GPL-3.0-or-later",
  "name": "fgm/foo",
  "require": {},
  "require-dev": {}
}
```
Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.11
PHP version: 7.3.15
PHP binary path: /usr/local/Cellar/php@7.3/7.3.15/bin/php
OpenSSL version: OpenSSL 1.1.1d  10 Sep 2019
```

When I run this command:

```
composer require -nvvv --prefer-source ankitpokhrel/tus-php
```

I get the following output:

```
Using version ^2.0 for ankitpokhrel/tus-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)

Installation failed, reverting ./composer.json to its original content.


  [RuntimeException]
  Could not load package kylekatarnls/update-helper in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint ^2.0.x-dev: Invalid version string "^2.0.x-dev"



  [UnexpectedValueException]
  Could not parse version constraint ^2.0.x-dev: Invalid version string "^2.0.x-dev"
```

And I expected this to happen: dependency added normally.

In addition, on a larger actual production repo, I did a `composer outdated -vvv` which pinpointed a similar error source error:

```
composer clearcache
composer outdated -vvv
// ...snip...
Downloading http://repo.packagist.org/p/paragonie/random_compat%24c164fec7a284476d3620d9a1dd5bd6601bf177228bce2e07008a592d869334aa.json
Writing /Users/fgm/.composer/cache/repo/https---repo.packagist.org/provider-paragonie$random-compat.json into cache


  [RuntimeException]
  Could not load package ezsystems/ezplatform in http://repo.packagist.org: [UnexpectedValueException] Could not parse version constraint dev-load-varnish-only-when-used as ^2.0@dev: Invalid version st
  ring "^2.0@dev"


Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:668
 Composer\Repository\ComposerRepository->createPackage() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:412
 Composer\Repository\ComposerRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:213
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:202
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/Package/Version/VersionSelector.php:54
 Composer\Package\Version\VersionSelector->findBestCandidate() at phar:///usr/local/bin/composer/src/Composer/Command/ShowCommand.php:1199
 Composer\Command\ShowCommand->findLatestPackage() at phar:///usr/local/bin/composer/src/Composer/Command/ShowCommand.php:368
 Composer\Command\ShowCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:281
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:113
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Command/OutdatedCommand.php:85
 Composer\Command\OutdatedCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:281
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:113
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:61
 require() at /usr/local/bin/composer:24


  [UnexpectedValueException]
  Could not parse version constraint dev-load-varnish-only-when-used as ^2.0@dev: Invalid version string "^2.0@dev"

```
This is similar to the case in this reproduction example in that `ezsystems/ezplatform` contains this specific dependency: `dev-load-varnish-only-when-used as ^2.0@dev`, much like the `kylekatarnls/update-helper` `^2.0.x-dev` branch.

Apparently, the presence of such invalid strings in otherwise unrelated providers in packagist now cause such exceptions, whereas they were ignored until recently.

**Comment by flack** [comment] 2020-09-08 17:26
probably the same problem as #9191

**Comment by Seldaek** [comment] 2020-09-08 21:04
Closing as duplicate of https://github.com/composer/composer/issues/9191

**Closed by Seldaek** 2020-09-08 21:04 UTC
