### ISSUE TITLE
Require --dev without dev version

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#4435] opened 2015-09-22 12:29 UTC
Actually, if I do this to add a package on the `require-dev` section:

```bash
composer require --dev sllh/php-cs-fixer-styleci-bridge
```

This is added to the right section but with `@dev` version annotation.

This package is stable, I don't need and don't want the `@dev` for that.

I think the --dev option should just add the package on `require-dev` without annotation. Another option could be made for that.

What do you think?

**Comment by alcohol** [comment] 2015-09-22 14:02
Cannot reproduce.

```
rob@robbast /tmp $ composer require --dev sllh/php-cs-fixer-styleci-bridge
Using version ^1.0 for sllh/php-cs-fixer-styleci-bridge
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/dependency-injection (v2.7.4)
    Downloading: 100%

  - Installing symfony/yaml (v2.7.4)
    Downloading: 100%

  - Installing sllh/php-cs-fixer-styleci-bridge (v1.0.0)
    Downloading: 100%

symfony/dependency-injection suggests installing symfony/config ()
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
Writing lock file
Generating autoload files
rob@robbast /tmp $ cat composer.json
{
    "require-dev": {
        "sllh/php-cs-fixer-styleci-bridge": "^1.0"
    }
}
```

You probably have `minimum-stability` set to dev in your composer.json.

**Comment by Soullivaneuh** [comment] 2015-09-22 14:05
Indeed, but I have also `prefer-stable` set to `true`. This should be considered by composer, isn't it?

**Comment by alcohol** [comment] 2015-09-22 14:09
Well, not sure what to expect..

Documentation regarding `prefer-stable`:

> When this is enabled, Composer will prefer more stable packages over unstable ones when finding compatible stable packages is possible. If you require a dev version or only alphas are available for a package, those will still be selected granted that the minimum-stability allows for it.

**Comment by alcohol** [comment] 2015-09-22 14:10
What version did it actually end up installing in your case (not asking about the entry it created in composer.json)?

**Comment by alcohol** [comment] 2015-09-22 14:11
Seems to work as expected for me. It simply installed 1.0.0.

```
rob@macbookpro /tmp $ composer require --dev sllh/php-cs-fixer-styleci-bridge
Using version ^1.0@dev for sllh/php-cs-fixer-styleci-bridge
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing symfony/dependency-injection (v2.7.4)
    Downloading: 100%

  - Installing symfony/yaml (v2.7.4)
    Loading from cache

  - Installing sllh/php-cs-fixer-styleci-bridge (v1.0.0)
    Downloading: 100%

symfony/dependency-injection suggests installing symfony/config ()
symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
Writing lock file
Generating autoload files
rob@macbookpro /tmp $ cat composer.json
{
  "minimum-stability": "dev",
  "prefer-stable": true,
  "require-dev": {
    "sllh/php-cs-fixer-styleci-bridge": "^1.0@dev"
  }
}
```

**Comment by Soullivaneuh** [comment] 2015-09-22 14:18
Indeed:

```bash
$ composer require --dev sllh/php-cs-fixer-styleci-bridge
Using version ^1.0@dev for sllh/php-cs-fixer-styleci-bridge                                  
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)                                                
  - Installing sllh/php-cs-fixer-styleci-bridge (v1.0.0)
    Loading from cache
$ composer info -i | grep php-cs-fixer
sllh/php-cs-fixer-styleci-bridge         v1.0.0              Auto configure PHP-CS-Fixer from StyleCI config file
```

But I'm still thinking that the `@dev` should not be here. :-)

**Comment by alcohol** [comment] 2015-09-22 14:19
Well, you should not be using **dev** as a `minimum-stability` either. ;-)

**Comment by Soullivaneuh** [comment] 2015-09-22 14:22
Why not? Some packages are not available on stable.

With this option, I got a clearer `composer.json` file.

If this is not the good way, why this option exists? :-)

**Comment by alcohol** [comment] 2015-09-22 14:25
You can use the '@dev' flag for those packages in particular, rather than allow **dev** for _all_ packages.

Existence doesn't imply good practice. It's actually a common pitfall. Maybe because of bad documentation. But also lots of bad examples on blogs/tutorials, unfortunately.

**Comment by alcohol** [comment] 2015-09-22 14:27
The advantage you get with minimum-stability is that even your dependencies can depend on dev dependencies. This is not a possibility with flags (unless you introduce those dependencies in your root composer.json). But whether or not that is a good reason to use it, is debatable.

**Comment by Seldaek** [comment] 2015-09-23 00:16
IMO `@dev` should only be added if it's needed, not following the minimum stability. There are other improvements I'd like to do to this auto-detection though, like skipping versions that require a PHP version higher than the one you have, to avoid selecting something that won't be installable.

**Comment by Soullivaneuh** [comment] 2015-09-23 07:45
Thanks @Seldaek, waiting for it. :+1:

**Comment by Seldaek** [comment] 2016-04-19 19:16
This isn't happening anymore AFAICT, think it's been fixed by the whole require refactorings.

**Closed by Seldaek** 2016-04-19 19:16 UTC
Labels: Feature
