### ISSUE TITLE
composer remove is not equivalent to manually editing composer.json and running composer update

### ISSUE THREAD

**Issue by ondrejmirtes** [composer/composer#9243] opened 2020-09-24 13:13 UTC
I hope that this description will be sufficient, in other case I'll do an example project.

I just encoutered this: I have `"guzzlehttp/guzzle": "^6.5"` in my `require`. I'd like to remove it along all its dependencies (that I don't otherwise use).

Running `composer remove guzzlehttp/guzzle` only removes Guzzle:

```
- Removing guzzlehttp/guzzle (6.5.5)
```

Running `composer remove guzzlehttp/guzzle --with-all-dependencies` also removes only Guzzle:

```
  - Removing guzzlehttp/guzzle (6.5.5)
```

But if I remove the line ``"guzzlehttp/guzzle": "^6.5"`` from my composer.json and run `composer update`, it removes a lot of other stuff too (which I'd expect to always happen):

```
  - Removing guzzlehttp/guzzle (6.5.5)
  - Removing guzzlehttp/promises (v1.3.1)
  - Removing guzzlehttp/psr7 (1.6.1)
  - Removing paragonie/random_compat (v9.99.99)
  - Removing psr/http-message (1.0.1)
  - Removing ralouphie/getallheaders (3.0.3)
  - Removing symfony/polyfill-intl-idn (v1.18.1)
  - Removing symfony/polyfill-intl-normalizer (v1.18.1)
  - Removing symfony/polyfill-php70 (v1.18.1)
  - Removing symfony/polyfill-php72 (v1.18.1)
```

When only Guzzle is removed, the Composer is in a weird state. For example if I ask why `symfony/polyfill-intl-idn` is still installed, it tells me:

```
$ composer why symfony/polyfill-intl-idn
There is no installed package depending on "symfony/polyfill-intl-idn"
```

```
Composer version 2.0-dev (2.0-dev+5df1797d20c6ab1eb606dc0f0d76a16ba57ddb7f) 2020-09-21 12:46:17
```

**Comment by simonberger** [comment] 2020-09-24 18:15
Well described issue. It is a duplicate of
https://github.com/composer/composer/issues/8870
https://github.com/composer/composer/issues/9218

and there is a pull request to fix it
https://github.com/composer/composer/pull/9223

**Comment by Seldaek** [comment] 2020-10-14 09:53
Fixed by https://github.com/composer/composer/pull/9223 I believe - feel free to try with latest snapshot and confirm :)

**Closed by Seldaek** 2020-10-14 09:53 UTC
Labels: Feature
