### ISSUE TITLE
Composer 2.2 breaks Magento installations with create-project

### ISSUE THREAD

**Issue by cmuench** [composer/composer#10384] opened 2021-12-22 14:12 UTC
After the upgrade to Composer 2.2 our Magerun build pipelines are broken.
Seems to be a related to the new plugin whitelist.

Example:

https://github.com/netz98/n98-magerun2/runs/4607228471?check_suite_focus=true#step:13:598

The installation of the `laminas/laminas-dependency-plugin` is stopped. Maybe stopped by the warning message?
I did some tests. A global `composer global config allow-plugins true` does not help here.
In my case I cannot modify the composer.json of the Magento project. So it's not possible to add a whitelist configuration in the root composer.json.

According to the documentation the new logic is not active so a installation with Composer 2.2 should be possible at the moment.

After a downgrade to 2.1.14 in my Github action the installation works again.

**Comment by fritzmg** [comment] 2021-12-22 14:23
Duplicate of https://github.com/composer/composer/issues/10383

If you have `autoload.files` in your `composer.json` (which Magento's project `composer.json` does) it will currently fail.

**Comment by Seldaek** [comment] 2021-12-22 14:33
Right, closing as duplicate, please follow #10383 I hope to get a fix out for it soon.

**Closed by Seldaek** 2021-12-22 14:33 UTC
