### ISSUE TITLE
Composer ignores version constraint on "minimum-stability": "dev"

### ISSUE THREAD

**Issue by cebe** [composer/composer#7544] opened 2018-08-13 09:16 UTC
While trying to reproduce the issue described in https://github.com/cebe/markdown/issues/154 I found some weird behavior, where in the combination of specifying a version constraint in a dependency and in the root composer.json will result in a version being installed that should be restricted by constraints.

1. I have two packages: `cebe/bug1` and `cebe/bug2`, added as a local repository.
   Both exist in version `1.0.0`. `cebe/bug1` requires `cebe/bug2: ~1.0.0`
2. composer.json has `"minimum-stability": "dev",`, so `composer install` gets me the master branch of both.
3. Then I update `cebe/bug2` and release a version 1.1.0.
4. Despite the constraint in `cebe/bug1` a composer update on the project installs `cebe/bug2:1.1.0`

I created a shell script to reproduce the issue:

```sh
#!/bin/sh

WORKDIR=/tmp/composerbug

test -d $WORKDIR && rm -rf $WORKDIR
mkdir -p $WORKDIR

## Create two packages to depend on

mkdir -p $WORKDIR/package1
cd $WORKDIR/package1
git init .
echo '{"name": "cebe/bug1", "require":{"cebe/bug2": "~1.0.0"}}' > composer.json
git add composer.json 
git commit -m "initial commit"
git tag 1.0.0
composer diagnose

mkdir -p $WORKDIR/package2
cd $WORKDIR/package2
git init .
echo '{"name": "cebe/bug2", "extra": {"branch-alias": {"dev-master": "1.0.x-dev"}}}' > composer.json
git add composer.json 
git commit -m "initial commit"
git tag 1.0.0
touch README.md
git add README.md
git commit -m "added readme"
composer diagnose


## Create new project with dependencies

mkdir -p $WORKDIR/bugproject
cd $WORKDIR/bugproject
tee composer.json <<EOF
{
	"minimum-stability": "dev",
	"require": {
		"cebe/bug1": "*",
		"cebe/bug2": "*"
	},
	"repositories": [
		{
			"type": "vcs",
			"url": "file://$WORKDIR/package1"
		},
		{
			"type": "vcs",
			"url": "file://$WORKDIR/package2"
		}
	]
}
EOF

composer diagnose
composer install
composer why cebe/bug1
composer why cebe/bug2

echo ""
echo "everything is fine until now, let's modify the dependency..."
echo ""

## Update package 2


cd $WORKDIR/package2
touch something.txt
git add something.txt
git commit -m "added something.txt"
git tag 1.1.0
echo '{"name": "cebe/bug2", "extra": {"branch-alias": {"dev-master": "1.1.x-dev"}}}' > composer.json
git add composer.json
git commit -m "updated branch-alias"


## try `composer update` in project

cd $WORKDIR/bugproject
composer update
echo "version of cebe/bug1"
git -C vendor/cebe/bug1 describe --tags
echo "version of cebe/bug2"
git -C vendor/cebe/bug2 describe --tags  # this must not be 1.1.0!?
composer why cebe/bug1
composer why cebe/bug2
```

Relevant output (after `composer update`):

```
version of cebe/bug1
1.0.0
version of cebe/bug2
1.1.0-1-g023a4e3
__root__  -  requires  cebe/bug1 (*)  
__root__   -           requires  cebe/bug2 (*)       
cebe/bug1  dev-master  requires  cebe/bug2 (~1.0.0)  
```

It should not install 1.1.0 of cebe/bug2 as this is restricted by cebe/bug1 constraint.
If I remove the `*` requirement from root composer.json `composer update` runs a downgrade to 1.0.0 as expected.

If I remove `"minimum-stability": "dev",` from composer.json everything resolves as expected as well.

```
$ composer --version
Composer version 1.7.1 2018-08-07 09:39:23
```

**Comment by alcohol** [comment] 2018-08-13 12:10
Cannot reproduce in most minimal setup:


```
rob@galaga /tmp/test $ cat bar/composer.json
{"name": "pkg/bar"}

rob@galaga /tmp/test $ cat foo/composer.json
{"name": "pkg/foo", "require":{"pkg/bar": "~1.0.0"}}

rob@galaga /tmp/test $ cat composer.json
{
    "minimum-stability": "dev",
    "require": {
        "pkg/foo": "*",
        "pkg/bar": "*"
    },
    "repositories": [
        {"type": "git", "url": "./foo" },
        {"type": "git", "url": "./bar"}
    ]
}

rob@galaga /tmp/test $ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 2 installs, 0 updates, 0 removals
  - Installing pkg/bar (1.0.0): Cloning 8f1ac4c6c5 from cache
  - Installing pkg/foo (dev-master 08f1440): Cloning 08f1440d19 from cache
Writing lock file
Generating autoload files

rob@galaga /tmp/test $ composer show
pkg/bar 1.0.0             
pkg/foo dev-master 08f1440

rob@galaga /tmp/test $ cd bar
rob@galaga /tmp/test/bar $ touch readme
rob@galaga /tmp/test/bar $ git add readme
rob@galaga /tmp/test/bar $ git commit
[master b059c1b] add readme
 1 file changed, 0 insertions(+), 0 deletions(-)
 create mode 100644 readme
rob@galaga /tmp/test/bar $ git tag 1.1.0
rob@galaga /tmp/test/bar $ cd ..

rob@galaga /tmp/test $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Nothing to install or update
Generating autoload files
```

I'll try reproducing with branch-alias set next.

**Comment by alcohol** [comment] 2018-08-13 12:17
Immediate failure:

```
rob@galaga /tmp/test $ cat bar/composer.json 
{"name": "pkg/bar", "extra": {"branch-alias": {"dev-master": "1.0.x-dev"}}}

rob@galaga /tmp/test $ cat foo/composer.json 
{"name": "pkg/foo", "require":{"pkg/bar": "~1.0.0"}}

rob@galaga /tmp/test $ cat composer.json 
{
    "minimum-stability": "dev",
    "require": {
        "pkg/foo": "*",
        "pkg/bar": "*"
    },
    "repositories": [
        {"type": "git", "url": "./foo" },
        {"type": "git", "url": "./bar"}
    ]
}

rob@galaga /tmp/test $ composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 2 installs, 0 updates, 0 removals
  - Installing pkg/bar (dev-master d6b57e1): Cloning d6b57e1fde from cache
  - Installing pkg/foo (dev-master c3d1ada): Cloning c3d1adac1b from cache
Writing lock file
Generating autoload files

rob@galaga /tmp/test $ composer show
pkg/bar dev-master d6b57e1
pkg/foo dev-master c3d1ada
```

I think it has to do with how the branch alias gets resolved / taken into account. Not sure what the desired behaviour here is or should be. @Seldaek ?

**Comment by Seldaek** [comment] 2018-08-13 12:29
What happens if you rm -rf vendor before running the last composer update? Does it still break then? I'm thinking it might be due to the installed state making it think it's fine to install master, except master now has a different meaning (1.1.x-dev instead of 1.0.x-dev).

**Comment by alcohol** [comment] 2018-08-13 12:34
```
rob@galaga /tmp/test $ rm -rf vendor

rob@galaga /tmp/test $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 2 installs, 0 updates, 0 removals
  - Installing pkg/bar (dev-master dfbfe3d): Cloning dfbfe3de3f from cache
  - Installing pkg/foo (dev-master c3d1ada): Cloning c3d1adac1b from cache
Generating autoload files

rob@galaga /tmp/test $ git -C vendor/pkg/bar describe --tags
1.1.0
```

I'm fairly confident the branch alias directly impacts the resolving here.

**Comment by cebe** [comment] 2018-08-13 21:56
> What happens if you rm -rf vendor before running the last composer update? Does it still break then?

Adding `rm -rf vendor` before last `composer update` does not break it in my case. I get the expected versions then. Script output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)         
Package operations: 2 installs, 0 updates, 0 removals
  - Installing cebe/bug2 (1.0.0): Cloning 0a3f3b3605
  - Installing cebe/bug1 (dev-master 3b9d7d3): Cloning 3b9d7d3764
Writing lock file
Generating autoload files
version of cebe/bug1
1.0.0
version of cebe/bug2
1.0.0
__root__  -  requires  cebe/bug1 (*)  
__root__   -           requires  cebe/bug2 (*)       
cebe/bug1  dev-master  requires  cebe/bug2 (~1.0.0)  
```

**Comment by cebe** [comment] 2018-08-13 21:59
Just tried on another machine and it's the same behavior on composer 1.6.3 and 1.7.1.

**Comment by andrefigueira** [comment] 2019-08-08 09:28
I'm getting the same issue on a project I have, in composer have:

```
"prefer-stable": true,
"minimum-stability": "dev",
```

Trying to pull in:

```
"eagle-eye-solutions/toolbox": "1.0.1@beta",
"eagle-eye-solutions/core-common": "1.1.0@beta",
```

Then get:

```
  Problem 1
    - The requested package eagle-eye-solutions/toolbox 1.0.1@beta exists as eagle-eye-solutions/toolbox[1.0.0, 1.0.1-beta] but these are rejected by your constraint.
  Problem 2
    - The requested package eagle-eye-solutions/core-common 1.1.0@beta exists as eagle-eye-solutions/core-common[1.0.0, 1.1.0-beta.1] but these are rejected by your constraint.
```

Tried removing prefer-stable, but still results in the same, didn't want to have to do that anyway. Attempting to remove vendor dir and run the composer update now.

**Comment by Seldaek** [comment] 2019-08-08 10:08
@andrefigueira if you can build up a reproduction case with a minimalistic composer.json please do post that in its entirety so we can try to reproduce it.

**Comment by xabbuh** [comment] 2019-08-08 12:13
Do stability flags work with exact version numbers? I would have expected something like `^1.0.1@beta` as the version constraint instead.

**Comment by Seldaek** [comment] 2019-08-08 12:16
Ah yes.. nice catch @xabbuh I didn't notice the lack of operator there. `1.0.1@beta` works as in it allows beta versions, but it requires 1.0.1 explicitly too, which won't allow 1.0.1-beta. Adding `^` or requiring `1.0.1-beta` (i.e. the correct exact version) should fix it.

**Comment by Seldaek** [comment] 2020-10-15 13:43
Most likely fixed by composer 2 so closing

**Closed by Seldaek** 2020-10-15 13:43 UTC
Labels: Bug
