### ISSUE TITLE
Stuck at provider-symfony$cache when installing/updating

### ISSUE THREAD

**Issue by calinpristavu** [composer/composer#5084] opened 2016-03-20 12:53 UTC
The scenario is that I want to deploy an oro/platform to an ec2 instance with 4gb of ram.
The app was previously deployed (not today) locally without any headaches.

Now, both locally and on the ec2, install/update both get stuck at 
`Reading /home/ubuntu/.cache/composer/repo/https---packagist.org/provider-symfony$cache.json from cache`

CPU stays at 100%, RAM ~2200 mb

With the following composer.json:

```json
{
    "name": "oro/platform-application",
    "description": "Oro Platform Empty Application",
    "homepage": "https://github.com/orocrm/platform-application.git",
    "license": "MIT",
    "autoload": {
        "psr-0": {
            "": "src/"
        }
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.orocrm.com"
        }
    ],
    "require": {
        "oro/platform": "1.9.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "2.5.3"
    },
    "config": {
        "component-dir": "web/bundles/components"
    },
    "scripts": {
        "post-install-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setPermissions",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::installAssets",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setAssetsVersion"
        ],
        "post-update-cmd": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setPermissions",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::installAssets",
            "Oro\\Bundle\\InstallerBundle\\Composer\\ScriptHandler::setAssetsVersion"
        ]
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "extra": {
        "symfony-app-dir": "app",
        "symfony-web-dir": "web",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        }
    }
}

```

When I run this command:

```
composer install -vvv --profile
```

I get this output:

```
[4.7MB/0.01s] Reading ./composer.json
[4.8MB/0.01s] Loading config file /home/ubuntu/.composer/config.json
[4.8MB/0.01s] Loading config file /home/ubuntu/.composer/auth.json
[4.8MB/0.01s] Loading config file ./composer.json
[5.0MB/0.01s] Checking CA file /etc/ssl/certs/ca-certificates.crt
[5.7MB/0.02s] Executing command (/var/www/welt): git branch --no-color --no-abbrev -v
[7.6MB/0.03s] Failed to initialize global composer: Composer could not find the config file: /home/ubuntu/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
[8.2MB/0.04s] Loading composer repositories with package information
[8.5MB/0.04s] Downloading https://packagist.orocrm.com/packages.json
[8.5MB/0.12s] Writing /home/ubuntu/.cache/composer/repo/https---packagist.orocrm.com/packages.json into cache
[8.5MB/0.12s] Downloading https://packagist.org/packages.json
[8.5MB/1.01s] Writing /home/ubuntu/.cache/composer/repo/https---packagist.org/packages.json into cache
[8.6MB/1.01s] Updating dependencies (including require-dev)
[8.9MB/1.01s] Reading /home/ubuntu/.cache/composer/repo/https---packagist.orocrm.com/p-provider-2014.json from cache
[8.9MB/1.01s] Reading /home/ubuntu/.cache/composer/repo/https---packagist.orocrm.com/p-provider-2015.json from cache
[8.9MB/1.01s] Reading /home/ubuntu/.cache/composer/repo/https---packagist.orocrm.com/p-provider-2015-04.json from cache
... SOME MORE packages from cache...
[446.9MB/28.37s] Reading /home/ubuntu/.cache/composer/repo/https---packagist.org/provider-symfony$cache.json from cache
(STUCK HEE FOR MORE THAN 1 HOUR in several attempts)
```

No idea why it gets stuck...
Any clues?
Thanks!

**Comment by curry684** [comment] 2016-03-20 15:06
Does clearing the cache with `composer clear-cache` solve the issue?

**Comment by curry684** [comment] 2016-03-20 15:09
Never mind that, something is seriously borked. I've just sort of reproduced the issue with your `composer.json`, only in my case it explodes through the 1GB memory limit.

**Comment by curry684** [comment] 2016-03-20 16:22
Pinging @naderman in on this one.

I've set a conditional breakpoint at `RuleSetGenerator.php:246` for `memory_get_usage() > 250000000` (250MB). What I see there is that it is adding 310 obsoletion rules for `symfony/framework-bundle` onto itself, one for every old version, and that `memory_get_usage()` is going up by 10MB for every iteration. In the end it's just blowing itself up there because you're including so many replaced packages with so many old versions. I haven't a clue where to begin to fix this or find the root cause.

**Comment by calinpristavu** [comment] 2016-03-20 17:42
@curry684 

> Does clearing the cache with composer clear-cache solve the issue?

manually removed the composer cache, just to be sure.

> something is seriously borked

I tried to find some major change both in `symfony/security-guard` and the cache component, but from the deps tree, nothing seems to have changed. Moreover, the same json file worked perfectly fine about 1 week ago, peaking at about 1,4 gb of ram, which is manageable for oro platform imo.

**Comment by curry684** [comment] 2016-03-20 18:37
How much physical RAM is in the test machines and what was the longest time it was stuck?

**Comment by curry684** [comment] 2016-03-20 21:24
I added 24GB RAM to my dev machine and it completed after nearly 6 minutes with 1.5GB RAM usage in the end:
```
[365.1MB/129.57s] Reading C:/Users/Niels Keurentjes/AppData/Local/Composer/repo/https---packagist.org/provider-symfony$cache.json from cache
[1496.1MB/343.96s] Analyzed 11209 packages to resolve dependencies
[1496.1MB/343.96s] Analyzed 1056489 rules to resolve dependencies
```
With Xdebug enabled obviously so relatively slow, but this matches the figures you mention for a week ago. It does strengthen my suspicions that your systems are livelocking.

**Comment by calinpristavu** [comment] 2016-03-21 07:57
I have a 4gb machine with 0 swap (ec2 reasons :D)
while loading other deps from the composer cache or while downloading, mem peaks at 500mb for the composer process, and about 600 total.

While loading symfony$cache.json, mem peaks at 2000 ish for the process, with 2200 for all processes.
I still have about 1600 free.

CPU is indeed stuck at 100%.

I seriously doubt it's a livelock, because I tracked procs in `htop` and didn't find any weird mojo, plus I get the same scenario on two different machines(and you apparently are the third).

> I added 24GB RAM to my dev machine
I don't have this luxury in the ec2 instance, and IMO this is not a permanent solution to the issue.

My best bet is that the composer deps graph got extremely complicated as a result of some update of one of the deps.

By the way, could you please tell me what package follows immediately after symfony$cache? Because I've been looking at this the wrong way. symfony cache works fine, but the next one is causing the issue.

**Comment by curry684** [comment] 2016-03-21 08:10
It's the final one so it goes into resolution there as my log shows, the next output was 4 minutes later so it's evaluating those 1 million rules there.

**Comment by Seldaek** [comment] 2016-03-26 08:53
Confusing logging fixed by #5108, as for the other issue, you **should not run composer update on production** machines (where you often have little RAM). See https://getcomposer.org/doc/01-basic-usage.md#composer-lock-the-lock-file

**Closed by Seldaek** 2016-03-26 08:53 UTC

**Comment by andrewkett** [comment] 2016-05-11 00:12
I had exactly the same issue on a small EC2 with limited RAM. The problem in the end wasn't related to composer but probably worth mentioning in case someone else runs into the same problem. Oro Platform has composer.lock in its .gitignore file. I missed this so although I thought i was installing from a lock file I was actually resolving all the dependancies on the server. My local machine had enough RAM to resolve the initial dependancies, commiting my local lock file and running again resolved the issue.

**Comment by resper** [comment] 2017-11-13 10:44
I have the same problem. But no possibility to raise the RAM on my developer system. Is there no other possibility to resolve the problem?

I try to execute this command:
`composer require doctrine/doctrine-migrations-bundle -vvv`

An it stuck at this line:

> Writing /home/lama/.composer/cache/repo/https---packagist.org/provider-symfony$workflow.json into cache

After a while I get the message killed.

**Comment by curry684** [comment] 2017-11-13 10:52
> But no possibility to raise the RAM on my developer system.

So how much is it right now? Realistically, you should not even consider software development with less than 4GB, and have 8GB if you're doing any serious sized development. In my experience, Composer can handle any situation you throw at it with 2GB max.

Optimizing memory usage is not a realistic option without throwing out the entire codebase and restarting in C++.

**Comment by edcarlos-92** [comment] 2024-07-18 17:20
somehow enabling extension=zip in php.ini got this issue resolved
