### ISSUE TITLE
[ErrorException] Undefined index: 0 when run : hhvm composer.phar install

### ISSUE THREAD

**Issue by bbichero** [composer/composer#5566] opened 2016-08-01 12:35 UTC
Hi everyone,

All is in the title, fews days i have this issue.

With the following composer.json:

``` json
{
    "require":
    {
        "facebook/xhp-lib": "2.2"
    }
}
```

When I run this command:

```
hhvm composer install -vvv
```

I get this output:

```
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl/cert.pem: valid
Executing command (/Users/Bicheron/Desktop/dev/xhp_test): git branch --no-color --no-abbrev -v


  [ErrorException]
  Undefined index: 0

Exception trace:
 () at phar://composer.phar/bin/../src/../vendor/symfony/process/Pipes/AbstractPipes.php:140
 Composer\Util\ErrorHandler::handle() at phar://composer.phar/bin/../src/../vendor/symfony/process/Pipes/AbstractPipes.php:140
 Symfony\Component\Process\Pipes\AbstractPipes->write() at phar://composer.phar/bin/../src/../vendor/symfony/process/Pipes/UnixPipes.php:98
 Symfony\Component\Process\Pipes\UnixPipes->readAndWrite() at phar://composer.phar/bin/../src/../vendor/symfony/process/Process.php:1359
 Symfony\Component\Process\Process->readPipes() at phar://composer.phar/bin/../src/../vendor/symfony/process/Process.php:1279
 Symfony\Component\Process\Process->updateStatus() at phar://composer.phar/bin/../src/../vendor/symfony/process/Process.php:305
 Symfony\Component\Process\Process->start() at phar://composer.phar/bin/../src/../vendor/symfony/process/Process.php:201
 Symfony\Component\Process\Process->run() at phar://composer.phar/bin/../src/../src/Composer/Util/ProcessExecutor.php:68
 Composer\Util\ProcessExecutor->execute() at phar://composer.phar/bin/../src/../src/Composer/Package/Version/VersionGuesser.php:94
 Composer\Package\Version\VersionGuesser->guessGitVersion() at phar://composer.phar/bin/../src/../src/Composer/Package/Version/VersionGuesser.php:67
 Composer\Package\Version\VersionGuesser->guessVersion() at phar://composer.phar/bin/../src/../src/Composer/Package/Loader/RootPackageLoader.php:76
 Composer\Package\Loader\RootPackageLoader->load() at phar://composer.phar/bin/../src/../src/Composer/Factory.php:333
 Composer\Factory->createComposer() at phar://composer.phar/bin/../src/../src/Composer/Factory.php:554
 Composer\Factory::create() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:318
 Composer\Console\Application->getComposer() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:430
 Composer\Console\Application->getPluginCommands() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:135
 Composer\Console\Application->doRun() at phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar://composer.phar/bin/composer:43
 include() at /Users/Bicheron/Desktop/dev/xhp_test/composer.phar:25
```

My hhvm php.ini  :

```
; php options
session.save_handler = files
session.save_path = /usr/local/var/lib/hhvm/sessions
session.gc_maxlifetime = 1440

; hhvm specific
hhvm.log.level = Warning
hhvm.log.always_log_unhandled_exceptions = true
hhvm.log.runtime_error_reporting_level = 8191
hhvm.mysql.typed_results = false
```

Thanks for you help, i read a lot of thread but i can't fix my problem ...

**Comment by alcohol** [comment] 2016-08-01 12:53
The exception occurs in a Symfony component. This is not code we maintain. I personally do not have any machines running hhvm either, so I am not in a position to reproduce this issue.

**Comment by bbichero** [comment] 2016-08-01 13:02
Thanks for your answer.
Can I ignore symfony when i use composer ?

**Comment by alcohol** [comment] 2016-08-01 13:11
No you cannot.

**Comment by alcohol** [comment] 2016-08-01 13:19
It looks to me like that particular piece of code checks whether or not a variable that supposedly holds a string value, is empty or not, by doing an array index `isset()` check. Seems questionable to say the least...

I am guessing that error reporting is tripping over this. Whether this is hhvm specific or php in general, I cannot say for sure.

**Comment by alcohol** [comment] 2016-08-01 13:21
Seems to be a duplicate of #5381 also.

**Comment by alcohol** [comment] 2016-08-01 13:22
See also http://stackoverflow.com/questions/38336034/error-installing-xhp-with-composer

**Comment by bbichero** [comment] 2016-08-01 13:29
Thanks, but a I have already seen those 2 threads ...
Whatever I change in my composer.json or add in my command line, I always get the same message ...

**Comment by alcohol** [comment] 2016-08-01 13:41
This has nothing to do with composer.json or how you run composer on the command line.
It has to do with php error reporting and error handling.

**Comment by bbichero** [comment] 2016-08-01 15:16
A ok I get it ... I home a HHVM user will help me, thanks again for your help alcohol !

**Comment by alcohol** [comment] 2016-08-02 06:50
The simplest suggestions I could give you to try out, are:

* reduce error reporting level
* turn off error reporting completely

Because as far as I know, undefined index is normally a notice or warning. It seems our [error handler](https://github.com/composer/composer/blob/eb77c0b7f580a8def3da5b3d56dac86bbb16f2de/src/Composer/Util/ErrorHandler.php) turns it into an ErrorException though.

/cc @Seldaek @nicolas-grekas @romainneutron you seem to have contributed quite a bit to the Symfony/Process component. Any idea why it does this [particular check](https://github.com/symfony/process/blob/3237dce60a9a5c90ad0f96f3ca783849cd798d57/Pipes/AbstractPipes.php#L138-L141), and more specifically, why in such a manner?

**Comment by nicolas-grekas** [comment] 2016-08-02 07:01
@bbichero what happens when you run this?
```ppp
$a = false;
var_dump( isset($a[0]) );
```

Looks like [this should return false](https://3v4l.org/RBfP0), but it's not in your setup?

**Comment by nicolas-grekas** [comment] 2016-08-02 07:03
@alcohol It will return false if the value is the empty string or `false`, which are both potential return values for fread. Maybe not your coding style, but still perfectly fine in PHP :)

**Comment by alcohol** [comment] 2016-08-02 07:04
@bbichero let us know also which hhvm version you are using.

**Comment by alcohol** [comment] 2016-08-02 07:05
@nicolas-grekas I never said it was not fine. It just looks.. awkward to me yea :d .. also starting to look like hhvm might have an issue with it o_O

**Comment by nicolas-grekas** [comment] 2016-08-02 07:11
I can't reproduce the issue with HipHop VM 3.14.3

**Comment by alcohol** [comment] 2016-08-02 07:12
The only other factor I can think of, but which seems mostly negligible, is that he is an OSX user.

**Comment by nicolas-grekas** [comment] 2016-08-02 07:19
Work around here https://github.com/symfony/symfony/pull/19503

**Comment by alcohol** [comment] 2016-08-02 07:26
@nicolas-grekas appreciate the quick action :+1:. Though I would suggest we wait to hear more from @bbichero first before making changes that might not be necessary perhaps.

**Comment by alcohol** [comment] 2016-08-02 07:43
@bbichero you can download a patched Composer (1.2.0 + PR from @nicolas-grekas) [here](https://dump.robbast.nl/composer-patched.phar) to see if that resolves your issue.

**Comment by bbichero** [comment] 2016-08-02 09:50
I have test to run :
```
hhvm composer-patched.phar install
```
But always the same error message.

My HHVM version is :
```
$ hhvm --version
HipHop VM 3.14.3 (rel)
Compiler: 1469981358_N
Repo schema: c2110d97012861cdb853a7ea905be5901e39af62
```
And my composer version is :
```
$ composer --version
Composer version 1.2.0 2016-07-19 01:28:52
```
A have also test the @nicolas-grekas code :
```
$ php example.php
bool(false)

$ cat example.php
<?php

$a = false;
var_dump( isset($a[0]) );

?>
```
And yes I am an OSX user ...

**Comment by alcohol** [comment] 2016-08-02 10:36
You have to run that example code using hhvm, not php (or did you alias php to hhvm?).

**Comment by alcohol** [comment] 2016-08-02 10:38
Can you show the error by the way when running the `composer-patched.phar`? Cause it should be occurring on a different line now at the very least, not on the same line as before (the code has been modified).

**Comment by bbichero** [comment] 2016-08-02 10:40
I have set to Off error reporting but again the same error !

I have run the code with php and hhvm, sorry i dindn't put the right code.

```
$ hhvm composer.phar -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl/cert.pem: valid
Executing command (/Users/Bicheron/Desktop/dev/xhp_test): git branch --no-color --no-abbrev -v


  [ErrorException]
  Undefined index: 0


Exception trace:
 () at phar://composer.phar/bin/../src/../vendor/symfony/process/Pipes/AbstractPipes.php:140
 Composer\Util\ErrorHandler::handle() at phar://composer.phar/bin/../src/../vendor/symfony/process/Pipes/AbstractPipes.php:140
 Symfony\Component\Process\Pipes\AbstractPipes->write() at phar://composer.phar/bin/../src/../vendor/symfony/process/Pipes/UnixPipes.php:98
 Symfony\Component\Process\Pipes\UnixPipes->readAndWrite() at phar://composer.phar/bin/../src/../vendor/symfony/process/Process.php:1359
 Symfony\Component\Process\Process->readPipes() at phar://composer.phar/bin/../src/../vendor/symfony/process/Process.php:1279
 Symfony\Component\Process\Process->updateStatus() at phar://composer.phar/bin/../src/../vendor/symfony/process/Process.php:305
 Symfony\Component\Process\Process->start() at phar://composer.phar/bin/../src/../vendor/symfony/process/Process.php:201
 Symfony\Component\Process\Process->run() at phar://composer.phar/bin/../src/../src/Composer/Util/ProcessExecutor.php:68
 Composer\Util\ProcessExecutor->execute() at phar://composer.phar/bin/../src/../src/Composer/Package/Version/VersionGuesser.php:94
 Composer\Package\Version\VersionGuesser->guessGitVersion() at phar://composer.phar/bin/../src/../src/Composer/Package/Version/VersionGuesser.php:67
 Composer\Package\Version\VersionGuesser->guessVersion() at phar://composer.phar/bin/../src/../src/Composer/Package/Loader/RootPackageLoader.php:76
 Composer\Package\Loader\RootPackageLoader->load() at phar://composer.phar/bin/../src/../src/Composer/Factory.php:333
 Composer\Factory->createComposer() at phar://composer.phar/bin/../src/../src/Composer/Factory.php:554
 Composer\Factory::create() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:318
 Composer\Console\Application->getComposer() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:430
 Composer\Console\Application->getPluginCommands() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:135
 Composer\Console\Application->doRun() at phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar://composer.phar/bin/composer:43
 include() at /Users/Bicheron/Desktop/dev/xhp_test/composer.phar:25
```

**Comment by nicolas-grekas** [comment] 2016-08-02 10:47
So, this is line 140 since the beginning, and I changed line 114... Let me give it another try...

**Comment by bbichero** [comment] 2016-08-02 10:51
Big thanks to you guys ! I very much appreciate :)

**Comment by alcohol** [comment] 2016-08-02 10:54
@bbichero Yeah I forgot by default that composer sets `error_reporting` to `E_ALL | E_STRICT`.

**Comment by nicolas-grekas** [comment] 2016-08-02 10:56
New try here: https://github.com/symfony/symfony/pull/19508

**Comment by alcohol** [comment] 2016-08-02 10:57
I updated the [composer-patched.phar](https://dump.robbast.nl/composer-patched.phar)

**Comment by alcohol** [comment] 2016-08-02 11:00
Sorry I don't know where I got line 114 from earlier. My bad about that.

**Comment by bbichero** [comment] 2016-08-02 11:11
Ho ! No more Error exception ! Yes.
But a segfault, what kind of composer.json i must put in my ~/.composer/ please ? thanks

```
$ hhvm composer-patched.phar install -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl/cert.pem: valid
Executing command (/Users/Bicheron/Desktop/dev/xhp_test): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /Users/Bicheron/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.2.0 (2016-07-19 01:28:52) with HHVM 3.14.3 on Darwin / 14.5.0
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /Users/Bicheron/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /Users/Bicheron/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Reading /Users/Bicheron/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
Reading /Users/Bicheron/.composer/cache/repo/https---packagist.org/p-provider-2015.json from cache
Core dumped: Segmentation fault: 11
Stack trace in /tmp/stacktrace.48630.log
Segmentation fault: 11
```

**Comment by alcohol** [comment] 2016-08-02 11:14
Uh... well that is not good either :\

**Comment by alcohol** [comment] 2016-08-02 11:14
Also, you don't need a composer.json in `~/.composer/`. You can ignore that message.

**Comment by bbichero** [comment] 2016-08-02 11:18
Ok,
here come the Trace :
```
$ cat /tmp/stacktrace.48630.log

PHP Stacktrace:

#0  json_decode() called at [phar://composer.phar/bin/../src/../src/Composer/Repository/ComposerRepository.php:556]
#1  Composer\Repository\ComposerRepository->loadProviderListings() called at [phar://composer.phar/bin/../src/../src/Composer/Repository/ComposerRepository.php:289]
#2  Composer\Repository\ComposerRepository->whatProvides() called at [phar://composer.phar/bin/../src/../src/Composer/DependencyResolver/Pool.php:204]
#3  Composer\DependencyResolver\Pool->computeWhatProvides() called at [phar://composer.phar/bin/../src/../src/Composer/DependencyResolver/Pool.php:193]
#4  Composer\DependencyResolver\Pool->whatProvides() called at [phar://composer.phar/bin/../src/../src/Composer/DependencyResolver/RuleSetGenerator.php:168]
#5  Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() called at [phar://composer.phar/bin/../src/../src/Composer/DependencyResolver/RuleSetGenerator.php:322]
#6  Composer\DependencyResolver\RuleSetGenerator->getRulesFor() called at [phar://composer.phar/bin/../src/../src/Composer/DependencyResolver/Solver.php:214]
#7  Composer\DependencyResolver\Solver->solve() called at [phar://composer.phar/bin/../src/../src/Composer/Installer.php:461]
#8  Composer\Installer->doInstall() called at [phar://composer.phar/bin/../src/../src/Composer/Installer.php:216]
#9  Composer\Installer->run() called at [phar://composer.phar/bin/../src/../src/Composer/Command/InstallCommand.php:135]
#10 Composer\Command\InstallCommand->execute() called at [phar://composer.phar/bin/../src/../vendor/symfony/console/Command/Command.php:259]
#11 Symfony\Component\Console\Command\Command->run() called at [phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:844]
#12 Symfony\Component\Console\Application->doRunCommand() called at [phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:192]
#13 Symfony\Component\Console\Application->doRun() called at [phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:231]
#14 Composer\Console\Application->doRun() called at [phar://composer.phar/bin/../src/../vendor/symfony/console/Application.php:123]
#15 Symfony\Component\Console\Application->run() called at [phar://composer.phar/bin/../src/../src/Composer/Console/Application.php:104]
#16 Composer\Console\Application->run() called at [phar://composer.phar/bin/composer:43]
#17 include() called at [/Users/Bicheron/Desktop/dev/xhp_test/composer-patched.phar:24]
```

**Comment by alcohol** [comment] 2016-08-02 11:21
Can you run `rm -rf ~/.composer` and then retry?

**Comment by bbichero** [comment] 2016-08-02 11:24
Same ...

**Comment by alcohol** [comment] 2016-08-02 11:31
It cannot be the same, cause it is reading from cache now, which you just removed.

**Comment by bbichero** [comment] 2016-08-02 11:32
It try to read from ~/composer/ again :
```
$ hhvm composer-patched.phar update -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /usr/local/etc/openssl/cert.pem: valid
Executing command (/Users/Bicheron/Desktop/dev/xhp_test): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /Users/Bicheron/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.2.0 (2016-07-19 01:28:52) with HHVM 3.14.3 on Darwin / 14.5.0
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing /Users/Bicheron/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /Users/Bicheron/.composer/cache/repo/https---packagist.org/p-provider-2013.json from cache
Reading /Users/Bicheron/.composer/cache/repo/https---packagist.org/p-provider-2014.json from cache
Reading /Users/Bicheron/.composer/cache/repo/https---packagist.org/p-provider-2015.json from cache
Core dumped: Segmentation fault: 11
Stack trace in /tmp/stacktrace.48700.log
Segmentation fault: 11
```

**Comment by alcohol** [comment] 2016-08-02 11:34
I don't care about that message, I already told you. It is not a problem.

This line is where it goes wrong:

`Reading /Users/Bicheron/.composer/cache/repo/https---packagist.org/p-provider-2015.json from cache`

The `json_decode()` fails to read that file for some reason.

But, it cannot be reading that from cache, cause you just told me that you ran `rm -rf ~/.composer` for me.

So I am confused.

**Comment by alcohol** [comment] 2016-08-02 11:36
I expect to see something like

```
Downloading http://packagist.org/p/provider-2015-10%2435a5270f22a96b6a59167dcbd2a1aaaa9c49945144388dec6237fc3d3f2a518a.json
Writing /home/rob/.cache/composer/repo/https---packagist.org/p-provider-2015-10.json into cache
```

**Comment by bbichero** [comment] 2016-08-02 11:39
I updated the message sorry for my inattention.

**Comment by alcohol** [comment] 2016-08-02 11:44
What happens if you run this?

```
curl -s https://dump.robbast.nl/segfault.json | php -r 'var_dump(json_decode(file_get_contents("php://stdin"), true));'
```

**Comment by alcohol** [comment] 2016-08-02 11:47
I actually don't know if hhvm supports the `-r` switch. So this might be a swing and miss.

**Comment by bbichero** [comment] 2016-08-02 11:48
The command line display a big json file i will upload it

**Comment by alcohol** [comment] 2016-08-02 11:49
That is correct, it should display that. Does hhvm do the same as php?

**Comment by bbichero** [comment] 2016-08-02 11:50
No ... 
```
$ curl -s https://dump.robbast.nl/segfault.json | hhvm 'var_dump(json_decode(file_get_contents("php://stdin"), true));'

Notice: File could not be loaded: var_dump(json_decode(file_get_contents("php://stdin"), true));
```

**Comment by alcohol** [comment] 2016-08-02 11:52
Does hhvm support `-r` ?

If not, just create:

**file.php**
``` php
<?php

var_dump(json_decode(file_get_contents("php://stdin"), true));
```

and then run

```
curl -s https://dump.robbast.nl/segfault.json | hhvm file.php
```

**Comment by bbichero** [comment] 2016-08-02 11:54
No HHVM doesn't support -r

The command line result :
```
$ curl -s https://dump.robbast.nl/segfault.json | hhvm file.php
Core dumped: Segmentation fault: 11
Stack trace in /tmp/stacktrace.48871.log
Segmentation fault: 11
```

**Comment by alcohol** [comment] 2016-08-02 11:58
Can you include the stacktrace in your comment?

**Comment by bbichero** [comment] 2016-08-02 12:04
Done but empty ...

**Comment by alcohol** [comment] 2016-08-02 12:09
What if you change the file to:

```
<?php

var_dump(json_decode(file_get_contents("https://dump.robbast.nl/segfault.json"), true));
```

and then run `hhvm file.php` ?

**Comment by alcohol** [comment] 2016-08-02 12:10
I found a `3.9.1` hhvm docker image, but it parses the the json properly :-(

```
docker run -it --rm --name segfault-test -v "$PWD":/usr/src/myapp -w /usr/src/myapp diegomarangoni/hhvm:cli hhvm script.php
```

**Comment by bbichero** [comment] 2016-08-02 12:12
I change the file.php and re-run comand line :
```
$ hhvm file.php
Core dumped: Segmentation fault: 11
Stack trace in /tmp/stacktrace.48943.log
Segmentation fault: 11
```
With empty stacktrace.

**Comment by alcohol** [comment] 2016-08-02 12:15
Do you have docker? If so, can you try one of the above commands?

**Comment by bbichero** [comment] 2016-08-02 12:17
I have brew docker but the command line return me :
```
$ docker run -it --rm --name segfault-test -v "$PWD":/usr/src/myapp -w /usr/src/myapp diegomarangoni/hhvm:cli hhvm script.php
docker: Cannot connect to the Docker daemon. Is the docker daemon running on this host?.
See 'docker run --help'.
```
I've never run docker, I will look a tutorial

**Comment by alcohol** [comment] 2016-08-02 12:18
Yeah you need to use sudo by default. But I just realised that docker runs a vm on OSX (unless you are participating in their new beta). Might be a pain to setup if you don't have it yet.

**Comment by bbichero** [comment] 2016-08-02 12:23
I'am trying to setup, I come back to you when it's finish

**Comment by alcohol** [comment] 2016-08-02 12:27
The issue is that docker will run hhvm inside the VM, which is Linux based, not Darwin (like OSX). So even if it turns out to work when using docker, that might not help you at all.

**Comment by bbichero** [comment] 2016-08-02 12:33
I've download the beta, so no VM created.
I have run :
```
$ docker run -it --rm --name segfault-test -v "$PWD":/usr/src/myapp -w /usr/src/myapp diegomarangoni/hhvm:cli hhvm file.php
```
And it display the json file !

**Comment by alcohol** [comment] 2016-08-02 12:34
Yeah but the beta still sort of runs in a lightweight VM.

**Comment by alcohol** [comment] 2016-08-02 12:36
Did you use Brew to install HHVM on OSX?

**Comment by alcohol** [comment] 2016-08-02 12:47
I opened a ticket for you: facebook/hhvm#7263 -- that's about the best I can do at this point.

**Comment by bbichero** [comment] 2016-08-02 12:50
Yes I have use brew, but i have test to install from source and a haved some trouble, so Brew was the best option.
Thanks again for all and have a good day :D

**Comment by alcohol** [comment] 2016-08-02 12:51
No problem. I hope someone can figure out what is/was going wrong.

**Comment by sebastienbarre** [comment] 2016-08-15 20:16
@bbichero thanks for documenting this. Any update?

**Comment by bbichero** [comment] 2016-08-15 20:48
No update always the same issue ... 
For install dependencies i rien composer with php with --ignore-platform-reqs

**Comment by Seldaek** [comment] 2017-01-22 19:40
Auto-closing as this hasn't been updated in over 6months. If there is a real bug to consider please let us know.

**Closed by Seldaek** 2017-01-22 19:40 UTC
Labels: Bug
