### ISSUE TITLE
Annoying and inappropriate donation-suggestion

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#6334] opened 2017-04-07 00:43 UTC
Is there a policy on the suggest field, and how not to abuse it for the wrong purposes?
Especially when it is yellow-flash "in your face" all the time?

<img width="521" alt="screenshot" src="https://cloud.githubusercontent.com/assets/39854/24780904/9cb2ed42-1b3b-11e7-8442-c3dff3c6fdad.png">

Imagine everyone would do this in every color, or even CAPITAL LETTERS and RED.
Just wondering - I am fairly certain the intention of this suggest field is to give helpful and incentive suggestions with technical relevance on this specific subject of dependency.

I think people should be keeping donation suggestions to their readme/repo, and shouldn't force it upon people when pulling those things as dependency-dependencies ("3rd party").

**Comment by Seldaek** [comment] 2017-04-07 08:06
Yeah I tend to agree this is kinda over the top.. On the other hand, you're also welcome to voice your opinion by stopping to use that software if they annoy you, so I would say this is not really Composer's problem, and not something we can reasonably police I think.

One thing we could do though is strip any color codes from it to avoid such stylistic abuse at least, but policing the content is not possible nor reasonable I think.

**Comment by dereuromark** [comment] 2017-04-07 08:21
I think the stripping part sounds like a reasonable resolution for the time being. I hope the maintainers are responsible enough to remove that noise on their own.
Thanks!

**Comment by dereuromark** [comment] 2017-04-07 08:39
@Seldaek No I cant stop pulling it in. I dont use it or want to use it but a library i use pulls this in as dependency. So there is only so much one can do. :)

**Comment by ondrejmirtes** [comment] 2017-04-07 11:00
I'm really sorry about this. PHPStan itself doesn't show any message of this kind (although I accept pledges), but the dependency of PHPStan, parts of Nette framework, are the cause of this obtrusive message during installation. I'd wish that I'd be able to get rid of Nette as dependency but it won't be possible, not at least in the near future.

**Comment by dg** [comment] 2017-04-07 16:02
Btw, is it actually helpful to show suggestions of dependency-dependencies?

For example, cakephp/cakephp suggests to install lib-ICU to use Text::slug. When cakephp/cakephp will be dependency of dependency, my project code should not use class Text, so this suggestion is useless.

**Comment by dereuromark** [comment] 2017-04-07 16:13
@dg Yes, it depends on how those things are "optional" - as you can see it is optional use lib-ICU but once you want to use the slug part of the framework you need it. It is then directly used by the framework via dependency code. So at least the dependency of a dependency is needed to be shown to make sense.

**Comment by dg** [comment] 2017-04-07 16:40
@dereuromark I do not know if we understand each other. (And `cakephp/cakephp` was bad example, because it is direct dependency, not dependency of dependency). The point is that suggestions of dependencies of dependencies are IMHO not useful. When dependency itself decides that it is useful, it can "propagate" it via own suggestion with better message. For example dependency of dependency suggests to use lib-ICU for Text::slug (which is too low-level information), whereas dependecy itself can suggest to use lib-ICU to enable slug router.

**Comment by derrabus** [comment] 2017-04-08 12:30
If you want to integrate Monolog into a Symfony application, you usually do this by requiring MonologBundle, not Monolog directly. Nevertheless, suggestions made by Monolog itself are very well relevant in that case and I find it reasonable to display them even though Monolog is not a direct dependency.

**Comment by Seldaek** [comment] 2017-04-19 15:50
Fixed by #6340

**Closed by Seldaek** 2017-04-19 15:50 UTC
Labels: Bug, Easy Pick
