### ISSUE TITLE
Inline alias skipped in favor of Packagist

### ISSUE THREAD

**Issue by ameenross** [composer/composer#8818] opened 2020-04-21 16:52 UTC
My `composer.json`:

```json
{
    "require": {
        "distilleries/form-builder": "dev-laravel-6"
    },
    "repositories": [
        {
            "type": "git",
            "url": "../FormBuilder"
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": false
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.5
PHP version: 7.2.24
PHP binary path: /usr/bin/php7.2
OpenSSL version: OpenSSL 1.1.1  11 Sep 2018
```

When I run this command:

```
composer install -vvv
```

I get the following output:

```
Reading ./composer.json
Loading config file /home/username/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/username/dev/testComposer): git branch --no-color --no-abbrev -v
Executing command (/home/username/dev/testComposer): git describe --exact-match --tags
Executing command (/home/username/dev/testComposer): git log --pretty="%H" -n1 HEAD
Executing command (/home/username/dev/testComposer): hg branch
Executing command (/home/username/dev/testComposer): fossil branch list
Executing command (/home/username/dev/testComposer): fossil tag list
Executing command (/home/username/dev/testComposer): svn info --xml
Reading /home/username/.composer/composer.json
Loading config file /home/username/.composer/auth.json
Loading config file /home/username/.composer/composer.json
Loading config file /home/username/.composer/auth.json
Reading /home/username/.composer/auth.json
Reading /home/username/dev/testComposer/vendor/composer/installed.json
Reading /home/username/.composer/vendor/composer/installed.json
Loading plugin PackageVersions\Installer
Running 1.10.5 (2020-04-10 11:44:22) with PHP 7.2.24-0ubuntu0.18.04.4 on Linux / 4.15.0-96-generic
Loading composer repositories with package information
Executing command (../FormBuilder): git show-ref --tags --dereference
Executing command (../FormBuilder): git branch --no-color --no-abbrev -v
Executing command (../FormBuilder): git branch --no-color
Executing command (../FormBuilder): git show '3.0':'composer.json'
Executing command (../FormBuilder): git -c log.showSignature=false log -1 --format=%at '3.0'
Reading composer.json of distilleries/laravel-form-builder (1.0.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/165f7e01802ccb837874888fc45e09174a8ee050 from cache
Importing tag 1.0.0 (1.0.0.0)
Reading composer.json of distilleries/laravel-form-builder (1.1.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/f3d0324e38a55ac91dde25bfda20c174d76d9db7 from cache
Importing tag 1.1.0 (1.1.0.0)
Reading composer.json of distilleries/laravel-form-builder (1.1.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/539c2004e1649a08b174c4f50aaee0711ce714c7 from cache
Importing tag 1.1.1 (1.1.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.0.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/2abc4e58cb8013930fe563deb6034733f552a640 from cache
Importing tag 2.0.0 (2.0.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.1.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/4a77f64b924babcf9a2a3a157c93d9224a2cf70c from cache
Importing tag 2.1.0 (2.1.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.10.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/a65b2b3d6edfe66e0c1b1b0e806e5cfb617fd9b3 from cache
Importing tag 2.10.0 (2.10.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.11.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/5d71148779605e12c8deee3b5a7019075b6eb2d6 from cache
Importing tag 2.11.0 (2.11.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.11.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/297b6a936904d28344c7312056058637f89db0f3 from cache
Importing tag 2.11.1 (2.11.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.12.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/71b043bb5ed4f5f6b61051847e9338b3aa73f030 from cache
Importing tag 2.12.0 (2.12.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.12.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/7407dd9157232edd8ed075b6178cf9da1115cc0c from cache
Importing tag 2.12.1 (2.12.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.13.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/7af75427d3c5a2c2d71b3e22f951dd8a0fa596d4 from cache
Importing tag 2.13.0 (2.13.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.13.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/dc5ba7cfb315a1bf713d4946f382ed9ab48356d0 from cache
Importing tag 2.13.1 (2.13.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.13.2)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/de7bc1f16067b64746253743d63cdf351c8fe279 from cache
Importing tag 2.13.2 (2.13.2.0)
Reading composer.json of distilleries/laravel-form-builder (2.2.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/c5b562cf8ed604060098b5bea4faf6c231f4a422 from cache
Importing tag 2.2.0 (2.2.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.2.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/3482fec0f22de0b75f4f610726a3bbbeca2a8371 from cache
Importing tag 2.2.1 (2.2.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.2.2)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/84297c80e12f4663952a13b55ff1bcbf939fb2ad from cache
Importing tag 2.2.2 (2.2.2.0)
Reading composer.json of distilleries/laravel-form-builder (2.2.3)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/c0c0a4598feb3a2e6ab6bb042c38bad457853678 from cache
Importing tag 2.2.3 (2.2.3.0)
Reading composer.json of distilleries/laravel-form-builder (2.2.4)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/5756027e56e849a126c85935ec65c69abff18201 from cache
Importing tag 2.2.4 (2.2.4.0)
Reading composer.json of distilleries/laravel-form-builder (2.3.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/ca6765b4e66e550aadd904a10ff78faa2f5e2a54 from cache
Importing tag 2.3.0 (2.3.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.4.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/6b1f480c0ad61cdcd191f76787d354839495ff86 from cache
Importing tag 2.4.0 (2.4.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.4.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/61723efd88c6093ea3e86012feaafdf34ad4a56c from cache
Importing tag 2.4.1 (2.4.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.4.2)
Importing tag 2.4.2 (2.4.2.0)
Reading composer.json of distilleries/laravel-form-builder (2.4.3)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/e975fd7cde5ca41496b22f1c90d130447922d758 from cache
Importing tag 2.4.3 (2.4.3.0)
Reading composer.json of distilleries/laravel-form-builder (2.4.4)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/a13ea2c9302a47f7adaf29bd83b7d013db269607 from cache
Importing tag 2.4.4 (2.4.4.0)
Reading composer.json of distilleries/laravel-form-builder (2.5.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/c5b17ab8b9444676b32344fe97db69dd3f4bdfa9 from cache
Importing tag 2.5.0 (2.5.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.5.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/54621691caae553e8eb698929aa750966ffa5fc2 from cache
Importing tag 2.5.1 (2.5.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.5.2)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/ebe0df0b9db158294d1ef38404345775bbb1c20b from cache
Importing tag 2.5.2 (2.5.2.0)
Reading composer.json of distilleries/laravel-form-builder (2.5.3)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/1b00ccb9401170728e2c91ec24298d33e40afcf0 from cache
Importing tag 2.5.3 (2.5.3.0)
Reading composer.json of distilleries/laravel-form-builder (2.6.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/60d51fe46ccc22d8fbb73bcde53c007248543f81 from cache
Importing tag 2.6.0 (2.6.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.7.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/b1fe18f5598e1ae66875e82eb2967710f812dbb6 from cache
Importing tag 2.7.0 (2.7.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/90cc04f21045ee1e0e23f20baa0d04e7fa271d56 from cache
Importing tag 2.8.0 (2.8.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/822bf4936f5e861520004af7703c5d808b2f1d39 from cache
Importing tag 2.8.1 (2.8.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.2)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/c53791cc0ba5d0feccf718579a7d525f1bf23589 from cache
Importing tag 2.8.2 (2.8.2.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.3)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/0ef8bc95c32996d2d5e719fcaa6841e76034790e from cache
Importing tag 2.8.3 (2.8.3.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.4)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/9c5986c716669c434c69e04724549bb09395061c from cache
Importing tag 2.8.4 (2.8.4.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.5)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/f9ec68b143a53d7f1c80f74093ee4af9f605d13e from cache
Importing tag 2.8.5 (2.8.5.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.6)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/fbdc4b9844ecd329491dd4548e4ed681d41f5538 from cache
Importing tag 2.8.6 (2.8.6.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.7)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/346d15f486e32856263489b099e7e3fd7a9f93fd from cache
Importing tag 2.8.7 (2.8.7.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.8)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/5c79c2b8f6c99ec34c75e138e3a74a71dff2cfaf from cache
Importing tag 2.8.8 (2.8.8.0)
Reading composer.json of distilleries/laravel-form-builder (2.8.9)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/f9347eeeea4d74ae66b967692898e49fe0a6b0dc from cache
Importing tag 2.8.9 (2.8.9.0)
Reading composer.json of distilleries/laravel-form-builder (2.9.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/fb5f28a4ba040bfe7df33ace81403775d4b62fae from cache
Importing tag 2.9.0 (2.9.0.0)
Reading composer.json of distilleries/laravel-form-builder (2.9.1)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/1ac7b883669f42bd348d8f412947b74d08af6c2f from cache
Importing tag 2.9.1 (2.9.1.0)
Reading composer.json of distilleries/laravel-form-builder (2.9.2)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/1e579feaeb4147a696fa7a9fe5aefacf50c6a5e4 from cache
Importing tag 2.9.2 (2.9.2.0)
Reading composer.json of distilleries/laravel-form-builder (3.0.0)
Reading /home/username/.composer/cache/repo/-home-username-dev-FormBuilder/7983ac6464cfa23626121f507a21684bd7eb2d07 from cache
Importing tag 3.0.0 (3.0.0.0)
Reading composer.json of distilleries/laravel-form-builder (3.0)
Importing branch 3.0 (3.0.x-dev)
Reading composer.json of distilleries/laravel-form-builder (laravel-6)
Importing branch laravel-6 (dev-laravel-6)
Reading composer.json of distilleries/laravel-form-builder (master)
Importing branch master (dev-master)
Downloading https://repo.packagist.org/packages.json
Writing /home/username/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2013.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2014.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2015.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2016.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2017.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2018.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2019.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2019-07.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2019-10.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-01.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-2020-04.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-archived.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/p-provider-latest.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/provider-guzzlehttp$guzzle.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/provider-dividebv$phpdivideiq.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/provider-guzzlehttp$ringphp.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/provider-react$promise.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/provider-guzzlehttp$streams.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/provider-distilleries$form-builder.json from cache
Resolving dependencies through SAT
Looking at all rules.

Dependency resolution completed in 0.000 seconds
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/provider-distilleries$form-builder.json from cache
Reading /home/username/.composer/cache/repo/https---repo.packagist.org/provider-distilleries$form-builder.json from cache
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package distilleries/form-builder dev-laravel-6 exists as distilleries/form-builder[1.0.0, 1.1.0, 1.1.1, 2.0.0, 2.1.0, 2.10.0, 2.11.0, 2.11.1, 2.12.0, 2.12.1, 2.13.0, 2.13.1, 2.13.2, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.2.4, 2.3.0, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.4.4, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.7.0, 2.8.0, 2.8.1, 2.8.2, 2.8.3, 2.8.4, 2.8.5, 2.8.6, 2.8.7, 2.8.8, 2.8.9, 2.8.x-dev, 2.9.0, 2.9.1, 2.9.2, dev-dev, dev-master, dev-release/laravel-4] but these are rejected by your constraint.
```

And I expected this to happen:
As I have added a branch (laravel-6), and it actually does show up in the verbose output, I expect dev-laravel-6 to resolve correctly. However, it decides to use Packagist nonetheless.

I've also tried with a version tag `3.0.0`, same result. Is this a regression in Composer 1.10.5?

**Comment by ameenross** [comment] 2020-04-21 17:07
*sigh*

I only just noticed this: `Reading composer.json of distilleries/laravel-form-builder (2.4.1)` ... package name `laravel-form-builder`, but required as `form-builder`, as that is its name on Packagist. 

Apparently my require *does* match the Packagist package, but not the git repository itself.

This is a nasty gotcha though, any previous experience with this? Should this be considered a bug with the package (or how it's advertised on Packagist)?

**Comment by Seldaek** [comment] 2020-04-22 05:58
It's quite confusing on the part of the maintainer of that package, that they have a name in composer.json which does not match the name they used to publish on packagist anymore. /cc @mfrancois probably the name in composer.json should be reverted to distilleries/form-builder? 

As a workaround you can tweak the name in the master branch on your local repo to be able to work. The master branch is where the name is read from, then all other branch's names are ignored so you don't need to edit the name in your laravel-6 branch.

In any case not a bug here so closing.

**Closed by Seldaek** 2020-04-22 05:58 UTC

**Comment by ameenross** [comment] 2020-04-22 06:58
Thanks
