### ISSUE TITLE
Composer Search ignores most results from Packagist

### ISSUE THREAD

**Issue by garyross** [composer/composer#5461] opened 2016-06-23 03:35 UTC
With the following composer.json:

```json
{
  "name": "laravel/laravel",
  "description": "The Laravel Framework.",
  "keywords": [
    "framework",
    "laravel"
  ],
  "license": "MIT",
  "type": "project",
  "require": {
    "php": ">=5.5.9",
    "laravel/framework": "5.1.*",
    "jenssegers/agent": "^2.3",
    "laravelcollective/html": "~5.0",
    "barryvdh/laravel-debugbar": "^2.0",
    "guzzlehttp/guzzle": "~5.3|~6.0"
  },
  "require-dev": {
    "fzaninotto/faker": "~1.4",
    "mockery/mockery": "0.9.*",
    "phpunit/phpunit": "~4.0",
    "phpspec/phpspec": "~2.1"
  },
  "autoload": {
    "classmap": [
      "database"
    ],
    "psr-4": {
      "App\\": "app/"
    },
    "files": [
      "app/Support/helpers.php"
    ]
  },
  "autoload-dev": {
    "classmap": [
      "tests/TestCase.php"
    ]
  },
  "scripts": {
    "post-install-cmd": [
      "php artisan clear-compiled",
      "php artisan optimize"
    ],
    "pre-update-cmd": [
      "php artisan clear-compiled"
    ],
    "post-update-cmd": [
      "php artisan optimize"
    ],
    "post-root-package-install": [
      "php -r \"copy('.env.example', '.env');\""
    ],
    "post-create-project-cmd": [
      "php artisan key:generate"
    ]
  },
  "config": {
    "preferred-install": "dist"
  }
}
```

When I run this command:

```
composer search sentence -vvv
```

I get this output:

```
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /private/var/folders/ks/2kp2z1156hbbhdvwprjjrf6h0000gn/T/composer-cacert-bcf331364fef73d53e4368ba519a6c3fcb21ea7836c3d8efad4ec32731e8152a.pem: valid
Executing command (/Users/gary/Dropbox/vhosts/bloxi_root/bloxi): git branch --no-color --no-abbrev -v
Reading /Users/gary/.composer/composer.json
Loading config file /Users/gary/.composer/composer.json
Reading /Users/gary/recdacted/vendor/composer/installed.json
Reading /Users/gary/.composer/vendor/composer/installed.json
Running 1.1.2 (2016-05-31 19:48:11) with PHP 5.5.33 on Darwin / 15.5.0
Downloading https://packagist.org/packages.json
Writing /Users/gary/.composer/cache/repo/https---packagist.org/packages.json into cache
Downloading https://packagist.org/search.json?q=sentence&type=%type%
bigwhoop/sentence-breaker Sentence boundary disambiguation (SBD) - or sentence breaking - library written in PHP.
```

I expect many more search results as I got a couple of days ago. Most of the results just disappeared, and indeed 
https://packagist.org/search.json?q=sentence 
is a long list rather than just the one that is returned.
```
bigwhoop/sentence-breaker Sentence boundary disambiguation (SBD)
next-sentence/afterbuy-sdk The AfterbuySDK provides... XML API
[many results]
pgodel/nmea Library to parse NMEA sentences
```

**Comment by alcohol** [comment] 2016-06-23 08:06
Related/duplicate of #5456

**Closed by alcohol** 2016-06-23 08:06 UTC
