### ISSUE TITLE
Option for keeping only last cached version of every package

### ISSUE THREAD

**Issue by rogervila** [composer/composer#5959] opened 2016-12-10 17:14 UTC
The cache folder uses a lot of disk space, but I don't like to clear it because, after doing it, new projects take a lot of time.

Is it possible to apply an option that keeps only the last cached version?

Something like `composer clear-cache --old`

**Comment by Seldaek** [comment] 2016-12-11 14:37
What's "a lot"? My cache dir is 1GB which isn't all that much.. One way I see to improve this is to allow passing a --max-size param which we would pass to the `$cache->gc()` call so that the oldest cache entries (least recently used) are cleared, but that would require us to fix the Cache class to make sure it doesn't corrupt git/svn/hg repos in the vcs cache.

**Comment by Seldaek** [comment] 2020-10-26 14:25
Closing as duplicate of https://github.com/composer/composer/issues/7834

**Closed by Seldaek** 2020-10-26 14:25 UTC
Labels: Feature
