### ISSUE TITLE
"The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

### ISSUE THREAD

**Issue by richbradshaw** [composer/composer#4789] opened 2016-01-18 19:56 UTC
This worked an hour or so back, but newest version seems to be broken - it's always saying this on a system where the user has no default HOME set, just COMPOSER_HOME.

I notice that commits in version `96ff17c520b398d2a102d082bf0d4df3bd5c18a8` which I'm using reference this error message - a regression?

**Comment by jschnare** [comment] 2016-01-18 20:41
This is affecting us too, we're explicitly setting COMPOSER_HOME and we're getting the same error.

**Comment by fosberyi** [comment] 2016-01-18 20:55
+1 This is crashing all deploys across our system right now.

**Comment by richbradshaw** [comment] 2016-01-18 20:59
As a heads up, you can simply run `composer self-update 1.0.0-alpha11` to fix the version of composer to a specific tagged release - that version works fine, and to be honest, running the newest version probably isn't the best idea anyway.

I wonder if `composer self-update` should just use tagged releases, and have something like `composer self-update --bleeding-edge` work as the current version does.

**Comment by fosberyi** [comment] 2016-01-18 21:28
@richbradshaw thanks for the heads up. I still can't get this to work on ElasticBeanstalk though. Still getting that same error:

"The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

**Comment by PatrickRyan-** [comment] 2016-01-18 21:32
Removing the composer update in your eb config should get you back up until this is resolved.

**Comment by cs278** [comment] 2016-01-18 21:35
Can confirm. @Seldaek this totally breaks Composer.

```
$ env --ignore-environment COMPOSER_HOME=$(pwd) sh -c '( env; /home/chris/src/composer/bin/composer diagnose )'
COMPOSER_HOME=/tmp/chris/tmp.XBaZJ6vFzW
PWD=/tmp/chris/tmp.XBaZJ6vFzW

                                                                                            
  [RuntimeException]                                                                        
  The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly  
                                                                                            

diagnose
```

**Comment by fosberyi** [comment] 2016-01-18 22:18
@PatrickRyan (and everyone else who's curious), I tried removing the composer update in the eb config, and it still didn't work. I was able to finally get it to work by changing this extension script:
```
commands:
  01_update_composer:
    command: export COMPOSER_HOME=/root && /usr/bin/composer.phar self-update 1.0.0-alpha11

option_settings:
  - namespace: aws:elasticbeanstalk:application:environment
    option_name: COMPOSER_HOME
    value: /root
```
To this:

```
commands:
  01_update_composer:
    command: export HOME=/root && export COMPOSER_HOME=/root && /usr/bin/composer.phar self-update 1.0.0-alpha11

option_settings:
  - namespace: aws:elasticbeanstalk:application:environment
    option_name: COMPOSER_HOME
    value: /root
  - namespace: aws:elasticbeanstalk:application:environment
    option_name: HOME
    value: /root

```

However, this causes ssh / bash_profile issues now because of the "HOME" envvar, so It'd be great if this could get sorted so we can go back to using just COMPOSER_HOME. Nevertheless, things seem to be running again.

Thanks for your help everyone!

**Comment by ArlingtonHouse** [comment] 2016-01-19 00:55
For our business today, the apparent change away from COMPOSER_HOME knocked us offline and wasted serval engineering hours.

**Comment by epfremmer** [comment] 2016-01-19 05:27
+1 This is also impacting vagrant/puphpet environments installing composer. Confirmed switching to HOME envar in elastic beanstalk to resolve failed deployments.

**Comment by alcohol** [comment] 2016-01-19 09:07
Seems there might be some unexpected side effects to the XDG PR that was merged (#1407). We will investigate.

/cc @Seldaek

**Comment by alcohol** [comment] 2016-01-19 09:30
@Seldaek maybe `data-dir` should not be defined by default (in `Factory:: createConfig`), cause I believe that is currently triggering the exception for systems that do not have `HOME` set. Alternatively, catch the exception in `Factory:: getDataDir` and check if `COMPOSER_HOME` is set instead?

**Comment by alcohol** [comment] 2016-01-19 09:34
For anyone that needs a quick win right now, set `HOME` to the same value as `COMPOSER_HOME`.

**Comment by gianebao** [comment] 2016-01-19 10:38
:( What's the resolution of this ticket? Will a fix be pushed?

**Comment by alcohol** [comment] 2016-01-19 10:39
I have some ideas, but not sure which one to move forward with. Waiting on feedback from @Seldaek

**Comment by manuel-huez** [comment] 2016-01-19 10:39
Can't you rollback to some older version? This is basically making any deployment fail right now.

**Comment by alcohol** [comment] 2016-01-19 10:41
Anyone can rollback locally. As for the master branch on Github, I'm not reverting anything. I believe more in the fix and move-forward approach.

**Comment by sylouuu** [comment] 2016-01-19 10:42
Replace all `COMPOSER_HOME` by `HOME` in your `.config` file in case you are using AWS.

**Comment by alcohol** [comment] 2016-01-19 10:48
> Replace all `COMPOSER_HOME` by `HOME` in your `.config` file in case you are using AWS.

That might cause issues if your `COMPOSER_HOME` was previously set to a path that did not end with `.composer`.

**Closed** 2016-01-19 10:54 UTC
Labels: Bug

**Comment by Seldaek** [comment] 2016-01-19 11:00
If someone can please confirm the fix using latest build that'd be great. I tried reproducing and I think it's fine but it's always best to get it from someone experiencing the issue for real.

As a side-note, all those complaining here about your broken builds and how desperate the situation is, I have to say I hope you learned the lesson: **Do not self-update blindly if the build is mission-critical**, or at least have a mechanism in place to easily rollback composer AND stop the next builds from self-updating. We offer a rollback mechanism, and we offer tagged releases that are generally pretty stable, so the waste of engineering hours in on you as far as I am concerned.

To the others that tried to find workarounds in a sane way and didn't try to guilt the maintainers, thank you.

**Comment by ricardokenji** [comment] 2016-01-19 11:00
fixed for me, thanks

**Comment by daniel-iwaniec** [comment] 2016-01-19 11:30
That fix works for me too.

**Comment by richbradshaw** [comment] 2016-01-19 11:51
Just confirming that newest version works now - thanks.

@Seldaek I think the issue that many people have faced is that in the AWS documentation it suggests adding a `composer self-update` to the deploy scripts - it's on this page http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP_symfony2.html under "To configure Composer".

I'm well aware that this isn't official composer documentation, but due to the AWS Linux shipping an old version of composer, composer does need updating, so this command at first glance seems logical.

I'd assumed it just updated through stable versions, and wasn't aware it pulled the newest commits.

I think Amazon may wish to rewrite that section of their docs, but right now there isn't an easy way to always update to a tagged release, afaik - maybe self-update should just use tagged versions?

**Comment by Seldaek** [comment] 2016-01-19 11:54
Yes self-update will only use tagged once we go to a 1.0 stable which should be soonish, so I guess let's leave it on amazon's end.. 

The bottom line is still that self-update can always break stuff or fail for any reason and the whole process shouldn't rely on it and it should be easy to disable it IMO if you do put it in a script.

**Comment by gianebao** [comment] 2016-01-20 04:00
works now! thanks!

**Comment by ArlingtonHouse** [comment] 2016-01-20 11:45
Working here, @Seldaek thanks for your attention to the issue and quick fix!

**Comment by ofriedrich** [comment] 2016-01-23 04:13
To all the users working with Amazon Web Services (AWS), Elastic Beanstalk (EB) ... 

As @richbradshaw wrote in his comment, Amazons "best practice" seems to be using "composer update/install" in your install scripts. We used it too and our applications crashed as many others did.

__So we thought about the installation process:__
Any time an environment is scaled up, nearly the same process used during deployment is triggered to install the application on the new instances. In time of deployment we have tested our applications with the current versions of the packages in the vendor folder.

I think most developers will use this "3.0.*" or that "^2.8" in composer.json, that allows composer to install any revision from 3.0.x up. But ... can you be sure that every part of your application works with maybe newer versions of any package?

In most cases a change in revision number shows you, that bugs has been fixed. And it should work. It should ...

__Anyway, installing an application on AWS as described [here](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/create_deploy_PHP_symfony2.html) will cause different software versions on your instances, if you allow up- and down-scaling.__

__Our solution is:__
Build the application locally using composer install/update (remember using the same php-version as installed in your AWS environment especially for symfony applications) and deploy this "ready for use" application package into AWS without using composer.

**Comment by sylouuu** [comment] 2016-01-23 11:18
Hi @ofriedrich,

What about comitting a `composer.lock` and you will be sure that the same versions will be used?

**Comment by Seldaek** [comment] 2016-01-23 11:50
There is nothing wrong with building fixed packages ahead of time, but indeed reliable deployments is exactly what the composer.lock file is for, and if you run `composer install` you are sure to get the same versions on every instance that pops up.

Regarding "remember using the same php-version as installed in your AWS environment", see https://getcomposer.org/doc/06-config.md#platform and http://seld.be/notes/new-composer-patterns (Defining your target production environment) that can help you achieve that with more certainty than "remembering" :)

**Comment by adulion** [comment] 2016-04-20 14:18
for some reason the latest version of composer was breaking my deploy on elastic beanstalk so i just dropped the following line into my deployment files. The vendor folder/authload.php was not being created. 

`command: export COMPOSER_HOME=/root && /usr/bin/composer.phar self-update 1.0.0-alpha11`

**Comment by mathiasgrimm** [comment] 2017-09-06 14:26
Just came across this thread by accident.

I would like to add that for those who got their websites offline, I would think the packaging should happen at build time and not deployment time. For those running composer install at run time on the production server, at least do it in a separate directory that not the current one and only do a symlink if everything worked, which is the most used approach if you don't have a build.

**Comment by ofriedrich** [comment] 2017-09-06 14:33
Hello @mathiasgrimm 
that's exactly what we do. Build the application locally and deploy this build. Deployment would last a little bit longer, but upscaling EBS instances in AWS is faster. No more dependencies on external resources during deployment or upscaling!

**Comment by ZFYL** [comment] 2017-10-11 09:57
Hello all! My 'dirty' solution was based on this [stackoverflow question](https://stackoverflow.com/questions/33080068/running-composer-in-a-different-directory-than-current)

Basicly this issue poped up when i was trying to install anchor cms (on DigitalOcean stack LAMP), the solution is to install composer like this `composer install -d /home/someuser/myproject`

Solved the issue immadiately!
