### ISSUE TITLE
Composer run with a php script using readline()

### ISSUE THREAD

**Issue by Aven30** [composer/composer#6670] opened 2017-09-08 22:04 UTC
Having an issue trying to run a script that uses `readline()` with composer. Any script that is run by `composer run` ignores the readline(). I do understand from PHP docs that readline() returns false when there is CTRL+D (EOF) which it is doing. It seems that composer somehow keeps clearing the input buffer? 

Also, when I run the script like this `php test.php`, it *does* work, thus for sure it is something with composer.

Here's my test.php file
```php
<?php

$input = readline("Please enter something: ");
echo PHP_EOL." THANKS";
```

My `composer.json`:

```json
{
    "name": "example",
    "require": {},
    "scripts": {
        "test-script": [
            "php test.php"
        ]
    }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK

```
When I run this commanded, it complete ignores my readline in that script.

```
composer run test-script
```

 Output:
```
composer run test-script
> php test.php

 THANKS
```

**Comment by alcohol** [comment] 2017-09-09 07:29
The way scripts are run, you do not really have access to stdin, so this will never work.

**Comment by Seldaek** [comment] 2017-09-11 13:13
Duplicate of https://github.com/composer/composer/issues/5856

**Closed by Seldaek** 2017-09-11 13:13 UTC
Labels: Support
