### ISSUE TITLE
'why' and 'why-not' commands don't work for packages that are being prevented from being installed

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#6452] opened 2017-05-26 08:58 UTC
I am getting this error when I do composer update:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package league/csv could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
```

So I tried both 'why' and 'why-not' to get a better understanding of the problem. In particular, I wanted to understand the chain of requirements that is requesting this package.

But both of these commands fail, apparently because the package isn't yet installed:

```
> composer why -r -t league/csv


  [InvalidArgumentException]
  Could not find package "league/csv" in your project
```

```
> composer why-not -r -t league/csv


  [InvalidArgumentException]
  Could not find package "league/csv" in your project
```

**Comment by curry684** [comment] 2017-05-26 09:22
I can confirm the `why-not` incorrectly failing. For the other half - can you provide a minimal `composer.json` file reproducing the issue? I'm aware that will be hard as it's the exact root issue you're trying to solve, but we will be needing to reproduce that to find the cause.

Does the output of `composer show -t | grep -C10 csv` help you?

**Comment by joachim-n** [comment] 2017-05-26 10:08
It looks like it's a chain of requirements, and the problem is possibly that while the top-level composer.json requests:

```
    "minimum-stability": "dev",
    "prefer-stable": true,
```

there is the actual composer.json that requests the problem package which doesn't specify prefer-stable. I'm not able to reproduce this in a single composer.json -- or at least, it's beyond my minimal knowledge of Composer.

> I can confirm the why-not incorrectly failing, although I think it has never worked like this. 

That may be the case; however the help for this command is then unclear, as it seems to say that it should be able to help in this situation:

>  Displays detailed information about why a package cannot be installed.

**Comment by curry684** [comment] 2017-05-26 10:17
The 2 flags you mention are [root-only](https://getcomposer.org/doc/04-schema.md#minimum-stability), meaning they are completely ignored anywhere but in your own `composer.json`. Your dependencies have no say in what you deem acceptable in your own project.

> the help for this command is then unclear

I agree there's room for improvement, it should just support the use case mentioned. I just don't think it ever did thus far (and I wrote the original code 😉 ).

**Comment by Seldaek** [comment] 2017-06-18 15:25
If you don't have a reproducible case here I doubt we can help much.. If you have a complete composer.json that'd be great.

**Comment by Seldaek** [comment] 2018-04-13 09:26
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.

**Closed by Seldaek** 2018-04-13 09:26 UTC
Labels: Support
