### ISSUE TITLE
laravel installing problem with composer xampp in windows

### ISSUE THREAD

**Issue by NilSagor** [composer/composer#4314] opened 2015-07-30 02:47 UTC
composer is installed successfully. but when I try to install laravel it shows this

Failed to decode response: zlib_decode(): data error Retrying with degraded mode

**Comment by alcohol** [comment] 2015-07-30 07:54
That is ok. Does it show you anything else?

**Comment by stof** [comment] 2015-08-02 02:39
Duplicate of #4121

**Closed** 2016-03-02 18:03 UTC
Labels: Support
