### ISSUE TITLE
outdated --minor-only is not available in 1.3.0 release

### ISSUE THREAD

**Issue by akovalyov** [composer/composer#6046] opened 2017-01-05 14:07 UTC
It is stated in [changelog of 1.3 release](https://github.com/composer/composer/releases) that `--minor-only` is available (according to [CHANGELOG.md](https://github.com/composer/composer/blob/master/CHANGELOG.md), it was added in 1.3.0-RC). It is also documented at https://getcomposer.org/doc/03-cli.md#outdated. But tricky part is that in https://github.com/composer/composer/compare/1.3.0...master#diff-6b4c97d66e0ab474239e5e5daa2a3034 `--minor-only` is in master branch still. 

`composer show -l --minor-only` of course works fine. 

Looks like 1.3.1 for me?

**Comment by alcohol** [comment] 2017-01-05 14:28
Duplicate of #5994

**Closed by alcohol** 2017-01-05 14:28 UTC

**Comment by akovalyov** [comment] 2017-01-05 14:32
@alcohol thank you, I didn't notice that issue. However, I am not sure if it is fixed, I believe that it can be fixed only via releasing 1.3.1.

**Comment by akovalyov** [comment] 2017-01-05 15:12
@stof it is just different points of view - from composer end user POV I see the feature in documentation/changelog but am not able to use that, so for me it is not fixed yet. 
For me I've resolved the trouble via using snapshot release, let's hope that there will be no duplicates until new release.

Thank you for your quick replies!
