### ISSUE TITLE
VersionSelector::findBestCandidate() doesn't take into account already installed packages

### ISSUE THREAD

**Issue by sminnee** [composer/composer#4181] opened 2015-06-26 09:13 UTC
It's great that `composer require` no longer requires that you provide a version, and instead makes an educated guess.

However, the current logic is a bit limited when you're have multiple versions of a package, and only some of those will be compatible with already installed packages.

For example, we might have:

 * silverstripe/translatable 2.1 works with silverstripe/framework 3.2
 * silverstripe/translatable 3.0 works with silverstripe/framework 4.0

If framework 3.2 is included and you try and install silverstripe/translatable, it will detect 3.0 as the most recent version and try and install that.

To fix this, I think the candidates selected in https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionSelector.php#L48 should be filtered to only include candidates that are compatible with the currently installed packages.

**Comment by stof** [comment] 2015-06-26 09:23
The issue is that finding whether candidates are compatible or no is not a simple task. It would require running a logic similar to the solver (but not the same logic if we want to avoid having to run the solver once per version, which would be slow as hell), because it would have to take into account new dependencies added by the new package, not only the new package itself.

**Comment by sminnee** [comment] 2015-06-26 09:30
What's the best way to fix this? Was there a reason that "*" isn't simply selected as the default version string, because that would seem to more reliably install a module.

Or, could you do this?

 * Set the requirement to `*`
 * Run the solver
 * Rewrite the requirement to whatever version got installed

**Comment by stof** [comment] 2015-06-26 09:39
@sminnee because you should **never** use an unbound requirement in your dependencies, and ``*`` is unbound.
Unbound requirements means you are allowing composer to use any future major version of the package, which makes no sense as future versions of the package will break BC (otherwise there would be no need to bump the major version), and so your current code is likely not working with versions of the packages released in the future (you have no way to know which BC breaks will be made as time-travel is not possible today). See https://getcomposer.org/doc/faqs/why-are-unbound-version-constraints-a-bad-idea.md for the doc explaining it.

The goal of omitting the version constraint in the command is to have an easy way to require a package without having to figure the best constraint yourselves. Before this was available, most projects were showing the usage of ``*`` in their readme, which is the worse constraint you can use

**Comment by sminnee** [comment] 2015-06-27 07:42
Fair point.

Perhaps there could be a slower version-identification process that only kicks in after the simple approach currently implemented has failed?

**Comment by Seldaek** [comment] 2015-11-19 18:08
It'd be nice to do it smarter in case of update failure I agree but right now it is what it is and until someone does it it'll stay that way I guess (i.e. I'm not so interested in fixing it myself;). I already spent quite some time recently making sure that the PHP version at least is taken into account when selecting a requirement, and also we now default to stable packages unlike before, but this would be a step even further of course, not sure how really important it is though for most projects I doubt this is an issue, even most silverstripe projects I guess active projects where people use require more are more likely to use the latest version.

**Comment by Seldaek** [comment] 2016-04-18 20:37
Closing as I am not gonna work on this and I doubt it's very important. If someone wants to send a PR to do a smarter resolved approach when the dumb way failed, I agree it would be nice and will happily accept it :)

**Closed by Seldaek** 2016-04-18 20:37 UTC
Labels: Feature

**Comment by sminnee** [comment] 2016-04-18 23:18
All good, thanks anyway.
