### ISSUE TITLE
Multiple credentials for a single repository with private packages

### ISSUE THREAD

**Issue by galanx** [composer/composer#10483] opened 2022-01-25 20:29 UTC
I have a satis repository where I host my own private packages, but some of my packages require specific credentials.
For example, let's say I have 2 packages:
acme/foo
test/bar

They both have different credentials. 

Now when I run "composer update", composer does actually prompt for credential once, but when attempting to load the second package, it uses the same credentials from the previous package, which results in the other package failing to download. I actually expect composer to prompt again for credentials but it doesn't seem to be the case due to the repository url being the same for both packages.

My company doesn't want to have a separate subdomain for each package, therefore I wanted to ask if there is a possible workaround for this?

My `composer.json`:

```
{
    "name": "package/test",
    "license": "MIT",
    "type": "project",
    "keywords": ["packages"],
    "description": "",
    "authors": [
        {
            "name": "Albert Feka"
        }
    ],
    "minimum-stability": "stable",
    "repositories": { 
        "satis": { 
            "type": "composer", 
            "url": "http://satis.localhost.local/"
        }
    },
    "require" : {
        "acme/foo": "^1.0",
        "test/bar": "^1.4"
    },
    "config": {
        "preferred-install": {
            "*": "dist"
        },
        "disable-tls": false,
        "secure-http": false,
        "store-auths": false
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: <obfuscated>
Dev Public Key Fingerprint: <obfuscated>
OK
Checking composer version: OK
Composer version: 2.2.5
PHP version: 7.4.19
PHP binary path: C:\laragon\bin\php\php-7.4.19-Win32-vc15-x64\php.exe
OpenSSL version: OpenSSL 1.1.1k  25 Mar 2021
cURL version: 7.70.0 libz 1.2.11 ssl OpenSSL/1.1.1k
zip: extension present, unzip present, 7-Zip not available
```

I get the following output: 

```
Loading composer repositories with package information
Warning: Accessing satis.localhost.local over http which is an insecure protocol.
Updating dependencies
Lock file operations: 2 installs, 0 updates, 0 removals
  - Locking acme/foo (1.0.5)
  - Locking test/bar (1.4.0)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Downloading acme/foo (1.0.5)
  - Downloading test/bar (1.4.0)
 0/2 [>---------------------------]   0%    Authentication required (satis.localhost.local):
      Username: test
      Password:
    Failed to download test/bar from dist: Invalid credentials for 'http://satis.localhost.local/dist/test/bar/test-bar-1.4.0-e4e642.zip', aborting.
    Now trying to download from source
  - Syncing test/bar (1.4.0) into cache
  - Installing acme/foo (1.0.5): Extracting archive
  - Installing test/bar (1.4.0): Cloning 530fb14bf2 from cache
Generating autoload files
```

I expect composer to prompt for credentials again for the next package, instead of just failing to download. 

Hope my issue has been clear so far.

**Comment by Seldaek** [comment] 2022-02-03 15:27
TBH that's a special use case due to poor repository construction which I am not so keen on supporting in composer. [Private Packagist](https://packagist.com) does support this though, as you can add the same repo as a third party mirror multiple times, configuring each with a different set of credentials, and mirroring a different set of packages from each. So I'd suggest you maybe have a look at using that, or try and get your vendors to use it as a paid package repository, which is also something we offer and we then handle credentials correctly for customers.

Duplicate of https://github.com/composer/composer/issues/8724 BTW if you want to read more about this.

**Closed by Seldaek** 2022-02-03 15:27 UTC
