### ISSUE TITLE
getting error "the program can't start because fbclient.dll is missing

### ISSUE THREAD

**Issue by xpvenom** [composer/composer#5110] opened 2016-03-24 22:54 UTC
When I try to run the executable file on windows 7 I receive the error "the program can't start because fbclient.dll is missing" 

Please help.

**Comment by curry684** [comment] 2016-03-24 23:06
Errr which executable...?

**Comment by xpvenom** [comment] 2016-03-24 23:07
Composer-Setup.exe

**Comment by hkdobrev** [comment] 2016-03-24 23:10
Probably this issue could be submitted with more details to the relevant repository: https://github.com/composer/windows-setup

**Comment by xpvenom** [comment] 2016-03-24 23:14
I'm using PHP 7.0 on windows 7.

**Comment by staabm** [comment] 2016-03-25 04:47
You php seem to load the firebird extension but it is not properly configured to find the client dll resources

**Comment by xpvenom** [comment] 2016-03-25 14:46
@staabm can you translate that to English please? :)

**Comment by curry684** [comment] 2016-03-25 14:47
This is not a Composer or Composer Setup issue. Your local PHP install has a configuration entry in its `php.ini` file to load fbclient.dll, and it can't find it. Your PHP install is broken, not Composer.

**Comment by xpvenom** [comment] 2016-03-25 14:59
![liuxrvj](https://cloud.githubusercontent.com/assets/17750476/14046552/a16ce0be-f278-11e5-9afa-0b7e78ad5f9b.jpg) I have the extension enabled. I don't see how my PHP installation is "broken"

**Comment by curry684** [comment] 2016-03-25 22:12
The problem is that it's enabled. The `php_pdo_firebird.dll` depends on the `fbclient.dll` which it cannot find, thus PHP crashes on startup, thus it cannot install Composer. Disable the firebird extension and it'll either work, or you'll at least get another error.

**Comment by Seldaek** [comment] 2016-03-28 16:25
Closing as nothing we can do here, please continue to discuss if needed :)

**Closed by Seldaek** 2016-03-28 16:25 UTC

**Comment by xpvenom** [comment] 2016-04-01 19:47
@curry684 I did as you said and I disabled the extensions that were giving me .dll errors through PHP manager in IIS and composer installed. On to the next step. Thanks
