### ISSUE TITLE
Regression in Autoload\ClassLoader

### ISSUE THREAD

**Issue by gnat42** [composer/composer#6143] opened 2017-02-08 03:09 UTC
In commit fabpot@2853e82400a113620e05504c52729c61b5a53f77 code was removed that stripped prepended '\\' characters from class names. This caused me an issue. Some of my classes had the following:

```
<?php 

namespace Some\Namespace;

use \Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Table(indexes={
 *          @ORM\Index(name="edblmp_idx",columns={"estimated_date_of_birth_lmp"}),
 *          @ORM\Index(name="edbultra_idx",columns={"estimated_date_of_birth_ultra"})
 * })
 * @ORM\Entity()
 */
class SomeClass
{
}
```
**Note the 'use \Doctrine' vs 'use Doctrine'**

Then on a couple of machines and in a CI instance (both PHP5.6 and 7.0.15) I would get errors such as:

```
[Doctrine\Common\Annotations\AnnotationException]                                                                                                                
  [Semantical Error] The annotation "@\Doctrine\ORM\Mapping\Index" in class Some\Namespace\SomeClass does not exist, or could not be auto-loaded. 
```

It took quite awhile to track this down however, in Autoload\ClassLoader findFile($class). I saw that it was requesting the class with a prepended '\'.

Is it not allowed to have use \F\Q\C\N; ? Or is this still a bug. 

In the mean time I've removed all usage of use \F\Q\C\N; which fixes the issue. However the commit mentioned above would allow it to continue to function regardless of how the use statements are used.

**Comment by alcohol** [comment] 2017-02-08 07:19
What PHP version are you running?

**Comment by alcohol** [comment] 2017-02-08 07:22
This is weird. I have never had issues with leading `\` in use statements or docblocks. The "patch" in the classloader was only there for a very old PHP version (5.3 or 5.2, can't recall). You must have some annotation library version.

**Comment by Seldaek** [comment] 2017-02-08 07:31
This is a duplicate of #6038 and see also https://github.com/doctrine/annotations/issues/115 - workaround is to remove the leading `\` from your `use` statements (only the use statements for annotations are relevant here).

**Closed by Seldaek** 2017-02-08 07:31 UTC
