### ISSUE TITLE
Unable  to do "composer update" because "SSL: Handshake timed out"

### ISSUE THREAD

**Issue by Qclanton** [composer/composer#6549] opened 2017-07-14 14:31 UTC
My `composer.json`:

```json
{
    "name": "yiisoft/yii2-app-basic",
    "description": "Yii 2 Basic Project Template",
    "keywords": ["yii2", "framework", "basic", "project template"],
    "homepage": "http://www.yiiframework.com/",
    "type": "project",
    "license": "BSD-3-Clause",
    "support": {
        "issues": "https://github.com/yiisoft/yii2/issues?state=open",
        "forum": "http://www.yiiframework.com/forum/",
        "wiki": "http://www.yiiframework.com/wiki/",
        "irc": "irc://irc.freenode.net/yii",
        "source": "https://github.com/yiisoft/yii2"
    },
    "minimum-stability": "stable",
    "require": {
        "php": ">=5.6",
        "yiisoft/yii2": "~2.0.11",
        "yiisoft/yii2-bootstrap": "~2.0.0",
        "yiisoft/yii2-swiftmailer": "~2.0.0",
        "yiisoft/yii2-jui": "*",
        "ext-curl": "*",
        "akeneo-labs/spreadsheet-parser": "*",
        "authorizenet/authorizenet": ">=1.9.3",
        "spipu/html2pdf": "*"
    },
    "require-dev": {
        "yiisoft/yii2-debug": "~2.0.0",
        "yiisoft/yii2-gii": "~2.0.0",
        "yiisoft/yii2-faker": "~2.0.0",

        "codeception/base": "^2.2.3",
        "codeception/verify": "~0.3.1",
        "codeception/specify": "~0.4.3"
    },
    "config": {
        "process-timeout": 1800
    },
    "scripts": {
        "post-create-project-cmd": [
            "yii\\composer\\Installer::postCreateProject"
        ]
    },
    "extra": {
        "yii\\composer\\Installer::postCreateProject": {
            "setPermission": [
                {
                    "runtime": "0777",
                    "web/assets": "0777",
                    "yii": "0755"
                }
            ],
            "generateCookieValidationKey": [
                "config/web.php"
            ]
        },
        "asset-installer-paths": {
            "npm-asset-library": "vendor/npm",
            "bower-asset-library": "vendor/bower"
        }
    }
}

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.yiisoft/yii2-jui : unbound version constraints (*) should be avoided
require.akeneo-labs/spreadsheet-parser : unbound version constraints (*) should be avoided
require.authorizenet/authorizenet : unbound version constraints (>=1.9.3) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK

```

When I run this command:

```
composer update
```

I get the following output:

```
The "https://bower.herokuapp.com/packages/bootstrap" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed
https://bower.herokuapp.com/packages could not be fully loaded, package information was loaded from the local cache and may be out of date
Package operations: 2 installs, 13 updates, 0 removals
  - Updating symfony/debug (v3.3.2 => v3.3.4): Downloading (100%)
  - Updating symfony/console (v3.3.2 => v3.3.4): Downloading (failed)
Downloading (100%)
  - Updating symfony/dom-crawler (v3.3.2 => v3.3.4): Loading from cache
  - Updating symfony/css-selector (v3.3.2 => v3.3.4): Loading from cache
  - Updating symfony/browser-kit (v3.3.2 => v3.3.4): Downloading (failed)
Downloading (failed)
Downloading (100%)
  - Updating symfony/yaml (v3.3.2 => v3.3.4): Downloading (failed)
Downloading (failed)
Downloading (failed)    Update failed (The "https://api.github.com/repos/symfony/yaml/zipball/1f93a8d19b8241617f5074a123e282575b821df8" file could not be downloaded: SSL: Handshake timed out
Failed to enable crypto
failed to open stream: operation failed)
    Would you like to try reinstalling the package instead [yes]? no


  [Composer\Downloader\TransportException]
  The "https://api.github.com/repos/symfony/yaml/zipball/1f93a8d19b8241617f5074a123e282575b821df8" file could not be downloaded: SSL: Handshake timed out
  Failed to enable crypto
  failed to open stream: operation failed
```

And I expected this to happen:
Update and installation of necessary packages

**Comment by tomzx** [comment] 2017-12-14 23:36
Duplicate of #6423.

**Closed** 2020-09-11 15:14 UTC
Labels: Support
