### ISSUE TITLE
Composer updates dependencies over and over again

### ISSUE THREAD

**Issue by kocsismate** [composer/composer#6218] opened 2017-03-01 22:44 UTC
My `composer.json`:

```json
{
    ...
    "require": {
        "php": "^7.1",
        ...
        "woohoolabs/zen": "^2.0.0",
        "zendframework/zend-diactoros": "^1.3.8"
    },
    ...
}
```

Output of `composer diagnose`:
All checks are OK.

When I run this command:

```
composer update
```

I get the following output even though nothing has changed since the last update:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating woohoolabs/zen (2.0.0 => 2.0.0) Loading from cache
  - Updating zendframework/zend-diactoros (1.3.10 => 1.3.10) Loading from cache
Generating autoload files
```

And I expected this to happen:
Already up-to-date packages shouldn't be updated again. I even tried to delete the `vendor` folder, along with the `composer.lock` file and the cache dir but it didn't help. Sorry if this issue is a duplicate, I couln't find a similary one after a quick search.

**Comment by curry684** [comment] 2017-03-02 06:44
I cannot reproduce your case with the supplied minimal example:
```
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 7 installs, 0 updates, 0 removals
  - Installing php-di/phpdoc-reader (2.0.1) Downloading: 100%         
  - Installing doctrine/lexer (v1.0.1) Loading from cache
  - Installing doctrine/annotations (v1.4.0) Loading from cache
  - Installing psr/container (1.0.0) Downloading: 100%         
  - Installing woohoolabs/zen (2.0.0) Downloading: 100%         
  - Installing psr/http-message (1.0.1) Loading from cache
  - Installing zendframework/zend-diactoros (1.3.10) Downloading: 100%         
Writing lock file
Generating autoload files
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
$ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
curry@ubuntu:~/test$ 
```
Can you try to provide a minimum setup that reproduces the issue? Also please try with both the stable and snapshot versions of Composer (`composer help self-update`) and provide the version numbers that display the issue if not all of them.

**Comment by kocsismate** [comment] 2017-03-03 07:36
@curry684 I managed to reproduce this issue with all the three channels of composer (I was originally using 1.3.2 stable) but more importantly, I found what causes the problem by removing my deps until my issue gets fixed:

So requiring `psr/container-implementation` and `psr/http-message-implementation` causes the problem. As soon as I removed these virtual packages from the "require" block, those two packages doesn't get updated all the time.

**Comment by kocsismate** [comment] 2017-03-03 08:20
Sorry, there is another thing I noticed: in some of my other libs I use (https://github.com/woohoolabs/harmony and https://github.com/woohoolabs/yin-middleware) I also require virtual packages and I suspect that the issue is related to that these virtual packages are required multiple times in my project.

**Comment by Seldaek** [comment] 2017-12-19 10:29
Auto-closing this as it's marked as support request and has not received any update in a long time.

**Closed by Seldaek** 2017-12-19 10:29 UTC
Labels: Support
