### ISSUE TITLE
PEAR installer doesn't work

### ISSUE THREAD

**Issue by oburk** [composer/composer#6193] opened 2017-02-23 10:46 UTC
My `composer.json`:

```
	"require": {
		"pear-pear.php.net/Calendar": "0.5.5",
		"pear-pear.php.net/Date_Holidays_Germany": "0.1.2",
	}
	
	"repositories": [
		{
			"type": "pear",
			"url": "https://pear.php.net/"
		}
	]

```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
require.zendframework/zenddiagnostics : unbound version constraints (dev-master) should be avoided
require.pear-pear.php.net/XML_Util : exact version constraints (1.4.2) should be avoided if the package follows semantic versioning
require.adodb/adodb-php : exact version constraints (v5.19) should be avoided if the package follows semantic versioning
require.phpoffice/phpexcel : exact version constraints (1.7.9) should be avoided if the package follows semantic versioning
require.apache/log4php : exact version constraints (2.3.0) should be avoided if the package follows semantic versioning
require.ezyang/htmlpurifier : exact version constraints (4.7.0) should be avoided if the package follows semantic versioning
require.fpdf/fpdf : exact version constraints (1.81) should be avoided if the package follows semantic versioning
require.phpseclib/phpseclib : exact version constraints (2.0.3) should be avoided if the package follows semantic versioning
require.muz/mive : unbound version constraints (>=1.0.5) should be avoided
require.elasticsearch/elasticsearch : exact version constraints (1.0.x-dev) should be avoided if the package follows semantic versioning
require.pimple/pimple : unbound version constraints (>=v2.0.0) should be avoided
require.muz/docx-api : unbound version constraints (dev-trunk) should be avoided
require.simplesamlphp/simplesamlphp : exact version constraints (1.14.0) should be avoided if the package follows semantic versioning
require.bower-asset/bootstrap : exact version constraints (3.3.4) should be avoided if the package follows semantic versioning
require.bower-asset/respond-minmax : exact version constraints (1.4.2) should be avoided if the package follows semantic versioning
require.bower-asset/html5shiv : exact version constraints (3.7.2) should be avoided if the package follows semantic versioning
require.bower-asset/retina.js : exact version constraints (1.3.0) should be avoided if the package follows semantic versioning
require.bower-asset/mjolnic-bootstrap-colorpicker : exact version constraints (2.1.2) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
  - Installing pear-pear.php.net/archive_tar (1.4.2)
    Loading from cache
  - Installing pear-pear.php.net/console_getopt (1.4.1)
    Loading from cache
  - Installing pear-pear.php.net/structures_graph (1.1.1)
    Loading from cache
  - Installing pear-pear.php.net/xml_util (1.3.0)
    Loading from cache
  - Installing pear-pear.php.net/pear (1.10.1)
    Loading from cache
  - Installing pear-pear.php.net/xml_parser (1.3.6)
    Loading from cache
  - Installing pear-pear.php.net/versioncontrol_svn (0.4.0)
    Loading from cache
...

PEAR repository from https://pear.php.net could not be loaded. Undefined index: channel
Updating dependencies

...

  Problem 1
    - module requires pear-pear.php.net/calendar 0.5.5 -> no matching package found.
    - module requires pear-pear.php.net/calendar 0.5.5 -> no matching package found.

   
...

```

And I expected this to happen:

Seams that after PEAR update package XML_Util from 2017-02-22 the composer install manager for PEAR is not longer working.

**Comment by alcohol** [comment] 2017-02-23 10:56
Is PEAR not dead yet?

**Comment by alcohol** [comment] 2017-02-23 11:00
Can you try purging your cache. See if anything installs at all then.

**Comment by steffendietz** [comment] 2017-02-23 11:09
I can confirm this issue using the minimal `composer.json` from above. (Minus the definition errors)

Also cleared the cache.

Did PEAR change its `packagesinfo.xml` structure?

```
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
PEAR repository from https://pear.php.net could not be loaded. Undefined index: channel
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package pear-pear.php.net/calendar could not be found in any version, there may be a typo in the package name.
  Problem 2
    - The requested package pear-pear.php.net/date_holidays_germany could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
```

**Comment by alecpl** [comment] 2017-02-27 15:23
@cweiske, maybe you or someone from PEAR could check if that's PEAR's fault? I confirm the issue.

**Comment by alecpl** [comment] 2017-03-02 09:11
@Seldaek @alcohol Could you give this issue more prio, please? The new Roundcube release is on hold because of this issue. I'm not sure who's fault it was (maybe PEAR's), but it looks like you already have a PR with the fix.

**Comment by cweiske** [comment] 2017-03-02 09:17
I did not have time to look into this issue, but XML structures at pear were not changed.

**Comment by alcohol** [comment] 2017-03-02 09:23
Well nothing at Composer changed either in regards to pear, so it stands to reason that something else must have changed then.

**Comment by cweiske** [comment] 2017-03-02 09:25
Maybe the package's `package.xml` file has a different structure now (that is valid but unsupported by composer)

**Comment by alcohol** [comment] 2017-03-02 09:28
Is there any documentation on the package.xml format?

**Comment by cweiske** [comment] 2017-03-02 09:31
- http://pear.php.net/manual/en/guide.developers.package2.intro.php
- http://pear.php.net/manual/en/guide.developers.package2.tags.php
- http://pear.php.net/dtd/

**Comment by Seldaek** [comment] 2017-03-02 09:43
The best way forward really would be to make sure you migrate those packages you rely on to packagist, like a bunch of pear packages have been ported already https://packagist.org/packages/pear/ - that way you can eventually drop the pear repo entirely from your composer.json. @cweiske has been doing some of that too AFAIK, it basically just needs someone willing to do the work.

Anyway I merged #6202, if you can confirm that it works after a `composer self-update --snapshot` that'd be nice. I will try and do a release next week as there are a couple other fixes in the pipeline..

**Closed by Seldaek** 2017-03-02 09:43 UTC
Labels: Bug

**Comment by alecpl** [comment] 2017-03-02 09:54
I confirm the fix is working. Thank you very much.

**Comment by oburk** [comment] 2017-03-02 10:38
I can also confirm that my problem was solved by #6202. Many thanks to all.

**Comment by SunMar** [comment] 2017-03-02 11:35
@Seldaek Unfortunately using the packagist versions of PEAR is not always an option, since they're not always maintained (versions lag behind) and sometimes even the package is incorrect (Mail_mimeDecode for example is an old version and contains additional classes that shouldn't be there and cause conflicts). So I would really recommend against using packagist for PEAR packages unless you're absolutely sure they're properly maintained.

Anyway, I can confirm that using the snapshot also worked for me.

**Comment by Seldaek** [comment] 2017-03-02 12:55
Yeah I can see that being the case if it was a one-shot done by someone who's not the maintainer. Hopefully people migrate slowly including the maintainers.
