### ISSUE TITLE
Allow to download binary dependencies

### ISSUE THREAD

**Issue by oscarotero** [composer/composer#4381] opened 2015-08-27 12:34 UTC
This comes from a specific use case (#4371) but in this issue I try to describe and propose the functionality.

Currently, composer doesn't have any way to deal with non-PHP binary files. And for PHP binary files, it installs the entire package and all its dependencies, creating a symlink into de bin folder. There are some use cases that this can be a problem:

* A package requires a binary file from a non-composer package. For example [a java package](https://github.com/validator/validator/releases/tag/15.6.29) to validate html pages. This binary must be included inside the package or documented in the README where to download it manually. This sounds like old pre-composer days.
* A package requires a binary file from a composer package, for example phpunit. In this case, composer downloads the package + dependencies and creates a symlink. This can have side effects like version incompatibility with any dependency that is common with our project, so finally it's better to download the phpunit.phar file because is faster and less problematic.

My proposition is extend the `bin` key in composer.json to accept also objects. For example:

```json
{
    "bin": [
        {
            "type": "symlink",
            "path": "src/bin/my-app"
        }
    ]
}
```
This is the equivalent as how it works now:

```json
{
    "bin": ["src/bin/my-app"]
}
```

With object, we can create more "types" to deal with other types of binary files that our package needs. Right now, I can see two more types of binary files (in addition to "symlink"):

## File
To download a file directly and place it into bin folder. The typical example is phpunit:

```json
{
    "bin": [
        {
            "type": "file",
            "url": "https://phar.phpunit.de/phpunit.phar"
        }
    ]
}
```
This download the phar file into "vendor/bin/phpunit.phar".

## Zip
To download a zip file.

```json
{
    "bin": [
        {
            "type": "zip",
            "url": "https://github.com/validator/validator/releases/download/15.6.29/vnu.jar_15.6.29.zip",
            "path": "vnu.jar"
        }
    ]
}
```
In this case, the zip file is downloaded, extracted and placed in a **subfolder of bin**. The subfolder name can be created using the url with md5 or any other similar method. So in this case the package is saved in: "vendor/bin/10b73bf827b3bf9f2be934833e47c5fc/". Then it creates a symlink to vnu.jar file in the root of bin folder.

## More options
There are more options that we can add to each bin element:
* os: Some packages have different binary files for each operating system, so this is a way to define the target of each binary to download only the binaries matching with the current os.
* name: This allows to rename the binary file. For example, "phpunit.phar" to "phpunit".

## Full example:
```json
{
    "bin": [
        "src/bin/my-app",
        {
            "type": "symlink",
            "path": "src/bin/my-app2"
        },{
            "type": "file",
            "url": "https://phar.phpunit.de/phpunit.phar",
            "name": "phpunit"
        },{
            "type": "zip",
            "url": "https://github.com/validator/validator/releases/download/15.6.29/vnu.jar_15.6.29.zip",
            "path": "vnu.jar"
        },{
            "type": "file",
            "url": "https://github.com/imagemin/gifsicle-bin/tree/master/vendor/osx/gifsicle",
            "os": "macosx"
        },{
            "type": "file",
            "url": "https://github.com/imagemin/gifsicle-bin/tree/master/vendor/win/x64/gifsicle.exe",
            "os": "win32",
            "name": "gifsicle",
        },{
            "type": "file",
            "url": "https://github.com/imagemin/gifsicle-bin/tree/master/vendor/linux/x64/gifsicle",
            "os": "linux"
        }
    ]
}
```
The latests 3 examples are taken from https://github.com/kevva/bin-wrapper

## Security
Because some users may be afraid of composer downloading binary files, they can configure how composer deal with this. So I propose a new key called "bin-downloads" that can have three values:
* ask (by default): Ask for each case whether to download or not. Something like `The package X is going to download the binary file Y. Are you agree? (Y,n)`
* allow: download all files
* deny: do not download any file. In this case, this message should be displayed: `The package X needs the binary file Y. You can download it in Z`

**Comment by hendrikmaus** [comment] 2015-08-30 08:00
+1

I have two more scenarios to add:

## Is it a dev requirement?
One should be able to tell composer whether a binary is a dev requirement or not.
Maybe the same pattern as with **require** and **require-dev**? just as **bin** and **bin-dev**?

## No pre-compiled binary available
It might be an edge case, but I would extend @oscarotero's proposal with an option to **build from source**.

If there is no pre-compiled binary available, I usually do something like this in my root composer.json to get and make tools from source:

```json
"scripts": {
    "post-package-install": [
        "git clone --recursive https://github.com/apiaryio/drafter.git vendor/drafter",
        "cd vendor/drafter && ./configure && make drafter",
        "mkdir -p vendor/bin && cd vendor/bin && ln -s ../drafter/bin/drafter drafter"
    ]
}
```

This approach is straight forward pragmatic, but has several drawbacks:
* I manually fiddle with the contents of the vendor dir
* I always have to reflect the proper bin-dir config
* I have to copy my binary manually to the correct location or use the one down in the tree all the time
* It might be a dev requirement, but it's always installed

To integrate with @oscarotero's proposal, I would suggest something like:

```json
{
    "type": "vcs",
    "url": "https://github.com/apiaryio/drafter.git",
    "os": "linux macosx freebsd",
    "scripts": {
    	"post-package-clone": "HendrikMaus\\DrafterHelper::build"
    }
}
```

> Note: I also extended the **os** key to be able to contain multiple values separated by a space

The **type** key value is taken from the usual composer.json schema [repositories](https://getcomposer.org/doc/04-schema.md#repositories) key.
The **scripts** key here would work the same as the composer.json [scripts](https://getcomposer.org/doc/articles/scripts.md) in place; with other events available though. E.g. **post-package-clone**

`HendrikMaus\\DrafterHelper::build` would then implement an interface defined by composer.
Really rough draft:

```php
interface Buildable
{
	/**
	 * Implement the build process.
	 * e.g. init submodules, configure, make, etc.
	 */
	public function build();

	/**
     * Allows composer to fetch the path to the binary
     * built, in order to properly symlink it to the 
     * configured bin-dir in composer.json
     *
     * Must be called after Buildable::build
     */
	public function getBinaryPath();
}
```

Cheers,
Hendrik

**Comment by danemacmillan** [comment] 2015-09-22 14:02
+1

**Comment by oscarotero** [comment] 2015-09-22 15:22
@hendrikmaus good addition.
Some thoughts:
* Maybe a `src-bin` folder is better than download the files directly in `bin`. I think `bin` only should contains symlinks to src-bin and vendor.
* +1 to **bin** and **bin-dev**
* +1 to no pre-compiled packages. The event name should be something more generic than "post-package-clone", to be compatible to zip files. There's a [pre-file-download](https://getcomposer.org/doc/articles/scripts.md#plugin-events), so a "post-file-download" may be a good name.

**Comment by hendrikmaus** [comment] 2015-09-23 09:40
@oscarotero cheers :)

* +1 to `src-bin`
* I would still stick with an event name more specific for the "no pre-compiled package" scenario. `pre-file-download` and `post-file-download` would mean to me, on a first glance, that the bin is ready which it is not in the scenario. They are perfect for the pre-built bin download scenario, though.

Maybe we can find an event name that indicates on the first glance, that the files are there, but the build process can be kicked off?

**Comment by oscarotero** [comment] 2015-09-23 10:12
If there's only one event, and it's used to compile, maybe we should discard the event aproach and use a more specific way. For example a `script` key:
```json
{
    "type": "vcs",
    "url": "https://github.com/apiaryio/drafter.git",
    "os": "linux macosx freebsd",
    "script": "./configure && make drafter",
    "path": "drafter"
}
```
We can register events, also, but they should be defined under `scripts` key (like any other event), for consistency and simplicity. For example `pre-binary-build`, `post-binary-build` (or something similar).

**Comment by hendrikmaus** [comment] 2015-09-23 10:58
+1

I like the `script` key for a sequence as easy as that and supporting events in `scripts`, too.
Seems to provide a very easy entry point, but also offers room for more complex stuff.

**Comment by lopezdonaque** [comment] 2015-11-19 09:49
+1

**Comment by webmozart** [comment] 2016-02-02 10:50
I would be very much interested in something like this, but I think this should support versioning. At the moment, all CLI tools that are distributed as Phars need to invent their own installer and update mechanism. With Composer, this could be much simplified:

~~~json
{
    "require-bin-dev": {
        "phpunit/phpunit": "^5.1"
    }
}
~~~

A configuration similar to this one would install the `phpunit.phar` in the `bin-dir`. The same clause could be used for many other projects, such as Box, Puli, the Symfony Installer and others. How to determine the location of the Phar I'll leave to somebody else.

On the long run, this could also be used to install whole modules as Phar. For example, a module could be packaged in a Phar together with all of its dependencies, [moved to a separate namespace to prevent collisions](/webmozart/php-scoper) and then installed as mentioned here, which would make the module usable out of the box (using [Puli](/puli)) and without conflicts.

**Comment by shochdoerfer** [comment] 2016-02-02 14:11
It may or may not be interesting to collaborate with [PHIVE](https://phar.io) - the PHAR Installation and Verification Environment for installing phar packages.

**Comment by Seldaek** [comment] 2016-04-18 21:32
Closing as it's too niche IMO and we need to focus on the main use cases for now.  Might be doable as a plugin or external tool..

**Closed by Seldaek** 2016-04-18 21:32 UTC
Labels: Feature

**Comment by webmozart** [comment] 2016-04-19 15:41
Installing a certain version of PHPUnit in a project is too niche?

**Comment by Seldaek** [comment] 2016-04-19 15:51
Oh please, `composer require phpunit/phpunit` does that and you know it. Downloading binaries is something entirely different that I am not willing to tackle right now. If someone does it as an external tool great, if it then proves to be useful and worth including in composer itself then we can always even consider that, but I won't lead that effort I just don't have the time.

**Comment by webmozart** [comment] 2016-04-19 15:58
@Seldaek of course :) The problem is that those tools have dependencies that potentially (and in practice) collide with the project dependencies. However, if the only requirement for the dependency is to run its binary, we don't actually need the libraries that the binary requires.

I think this issue is important. Every executable tool required in a project in a specific version is affected by this problem.

**Comment by Seldaek** [comment] 2016-04-19 16:17
What's important to some isn't necessarily important to most, or to me. As I said, I am not closing the door forever here, I just don't want this distracting us from the more important things (again, subjective, but that's life) in the issue tracker.

**Comment by stof** [comment] 2016-04-19 16:19
@webmozart the case of phpunit is not a good example though. PHPUnit runs in the same process than your own code, and so needs to have compatible deps (for instance, running PHPUnit 5 from a phar means your testsuite will use Symfony Yaml 3.x, even though your project installed 2.x)

**Comment by bamarni** [comment] 2016-05-02 09:40
I've started a plugin for this (https://github.com/bamarni/composer-bin-plugin), it uses the new capabilities feature (#3377).

It doesn't address everything described here, but should help for dependency hell issues :)
