### ISSUE TITLE
Composer install absolute paths in autoload_static.php

### ISSUE THREAD

**Issue by leventerogct** [composer/composer#6558] opened 2017-07-20 16:57 UTC
I'm working on setting up a build pipeline in VSTS.

When I run **composer install** the following paths will be hardcoded in autoload_static.php:

        'AppCache' => 'c:/agent/_work/1/s/app/AppCache.php',
        'AppKernel' => 'c:/agent/_work/1/s/app/AppKernel.php',

This will obviously crash my application once I deploy it to Azure.
Tried using --no-autoloader and --optimize-autoloader but no luck.

Desired result:

        'AppCache' => __DIR__ . '/../..' . '/app/AppCache.php',
        'AppKernel' => __DIR__ . '/../..' . '/app/AppKernel.php',

**Comment by leventerogct** [comment] 2017-07-21 19:19
Looks like the problem is installing composer on a symbolic link.
I have the symlink c:\agent\_work poiting to d:\vsagent\_work
If I run the installer from the c: drive:
c:\agent\work\1\s> php composer install
I will get those 2 weird hardcoded paths.

If I run it from the actual location:
d:\vsagent\work\1\s> php composer install
I get the desired relaive paths in autoload_static.php and autoload_classmap.php

For now I'll just refrain from using symbolic links.

**Comment by curry684** [comment] 2017-07-21 19:47
Your workflow is flawed, as it implies you're upload `vendor` or at least `vendor/composer` to Azure from another machine. Instead you should never upload `vendor` at all, ensure to upload `composer.lock` and run `composer install` on the target machine.

If you insist on shipping `vendor` along with your own code, a solution would be to run only `composer dump-autoload` on the Azure machine as it will regenerate all autoload files.

For reference see https://getcomposer.org/doc/faqs/should-i-commit-the-dependencies-in-my-vendor-directory.md, specifically the second paragraph.

**Comment by robfrawley** [comment] 2017-07-22 02:01
> Your workflow is flawed,

While I tend to agree with your position regarding `vendor` and `composer.lock` best-practices, there is nothing "flawed" about handling deploys in the manner @leventerogct described, it's just now how I (or you) would do it.

That said, the deploy methodology seems irrelevant. The only pertinent issue is that the autoloader paths shouldn't be conditionally absolute depending on the where `composer` is run from a symbolic link or directly (assuming the assumptions @leventerogct mentions are accurate). Absolute paths in this context break tons of workflows, including many not even remotely related to deploying.

**Comment by alcohol** [comment] 2017-07-31 06:49
I do not agree that the workflow is flawed. I personally would encourage deploying a release artefact to Azure. That would be for example a docker container or an archive file containing everything you need to run the application (including the `vendor` directory). Absolute paths should not end up in the autoloader. This seems like a bug. Or you misconfigured your autoload definitions. Can you share those?

**Comment by leventerogct** [comment] 2017-07-31 12:15
I'm deploying the app to Azure PaaS where I don't have the option to run **composer install** as part of the deployment. Azure Web Apps are also missing Ruby that is needed to compile some of the CSS - hence using a Build agent.

**Comment by curry684** [comment] 2017-07-31 19:42
My apologies for using the word *flawed*, I meant to imply it less resolute than it was interpreted. The situation you mention is one of the cases where it makes sense to prepackage. As stated the workflow is supported, but it should never generate absolute paths, so this is likely a bug on our end. Please share the relevant autoload parts of your `composer.json` file.

**Comment by Seldaek** [comment] 2017-08-08 07:50
@leventerogct do you have details as to how you create the symlink and any other details that could help to reproduce this? I tried with a `mklink /D link target` symlink from F:\.. to C:\.. and no matter where I run the composer dump-autoload I always get relative paths like `       'Barzz' => __DIR__ . '/../..' . '/src/Foo.php',` for a file which is in `./src/Foo.php` so the path makes sense.

Can you try also with the latest snapshot? Maybe it's something that was fixed in the last few days/weeks, as I fixed some classmap generation stuff. `composer self-update --snapshot` then `composer dump-autoload`

**Comment by gargoyle** [comment] 2018-01-03 15:57
I think I have come across a similar issue under linux when using "path" type repos. In a similar way to the OP, I do not put "build tools" onto production servers, but instead build a tar archive of all the files required for the app, and upload the archive.

I have the following defined in composer.json:-
```
"repositories": [
        {
            "type": "path",
            "url": "../../Library/Shared Components"
        }
    ],
```

This works perfectly under development. The shared library is symlinkd and the non-optimised autoloader works. 

However, if you generate the optimised autoloader, then I have the following style of entries:-
```
' Psg\\Moveit\\Core\\ApiClient' => $baseDir . '/../../Library/Shared Components/src/ApiClient.php'
```
This is *not* using the symlink!

I would have expected something more along the lines of:-
```
Psg\\Moveit\\Core\\ApiClient' => $vendorDir . 'moveit-core/src/ApiClient.php'
```
Where the "moveit-core" part of the path would be the symlink.

**Comment by alcohol** [comment] 2018-01-04 12:27
Could be that the optimised autoloader is generated using the resolved symlink path?

**Comment by gargoyle** [comment] 2018-01-04 16:14
NM, Ignore me! :-)

Seems I was testing on a system with a horribly out-dated composer install (1.0_beta). All seems to be working as expected in 1.5+.

Much apologies.

**Comment by Seldaek** [comment] 2022-05-15 11:48
Closing as nobody cared to fix it in these many years, if it is still applicable do tell and I will reopen.

**Closed by Seldaek** 2022-05-15 11:48 UTC
Labels: Bug
