### ISSUE TITLE
Could not open input file - space in the folder name - error

### ISSUE THREAD

**Issue by dghez** [composer/composer#6810] opened 2017-11-14 13:55 UTC
Hi everyone.
I'm currently installing [Sage 9](https://github.com/roots/sage), that use Composer to create the project.
Everytime I try to run the command `composer create-project ......` I get `Could not open input file`.
After some tests I found that the problem comes from the name of the folder. If the folder contains a space into the name composer doesn't work.
For example, `test` is fine but `test 2` will give the error. I tried with different folders name in different directory.
Is there a way to solve that? My folder contains a space and it will be painful to change the name.
Hope someone can help me.
Thanks :)

('m on macOS HighSierra)

**Comment by alcohol** [comment] 2017-11-15 07:04
`composer create-project ......` is not a valid command.

I hate to be pedantic here, but it is kind of obvious that if you want any help, you need to tell us what you are actually doing, not leave us guessing.

**Comment by dghez** [comment] 2017-11-15 09:24
Sorry @alcohol I thought that was not the point because as I told the command works in every folder without any space in the name. It gives problem only if the name of the folder contain a space.
Btw, the command was `composer create-project roots/sage your-theme-name 9.0.0-beta.4`, hope this can help.

**Comment by alcohol** [comment] 2017-11-15 09:50
Cannot reproduce:

```
rob@macbookpro.local /tmp > mkdir some\ directory
mkdir: created directory 'some directory'
rob@macbookpro.local /tmp > cd some\ directory/
rob@macbookpro.local /tmp/some directory > composer create-project roots/sage your-theme-name 9.0.0-beta.4
Installing roots/sage (9.0.0-beta.4)
  - Installing roots/sage (9.0.0-beta.4): Downloading (100%)
Created project in your-theme-name
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 26 installs, 0 updates, 0 removals
  - Installing composer/installers (v1.4.0): Downloading (100%)
  - Installing paragonie/random_compat (v2.0.10): Loading from cache
  - Installing illuminate/contracts (v5.4.27): Downloading (100%)
  - Installing doctrine/inflector (v1.2.0): Loading from cache
  - Installing illuminate/support (v5.4.27): Downloading (100%)
  - Installing illuminate/container (v5.4.27): Downloading (100%)
  - Installing illuminate/events (v5.4.27): Downloading (100%)
  - Installing psr/log (1.0.2): Loading from cache
  - Installing symfony/debug (v3.3.6): Downloading (100%)
  - Installing symfony/finder (v3.3.6): Downloading (100%)
  - Installing illuminate/filesystem (v5.4.27): Downloading (100%)
  - Installing illuminate/view (v5.4.27): Downloading (100%)
  - Installing illuminate/config (v5.4.27): Downloading (100%)
  - Installing roots/sage-lib (9.0.0-beta.4): Downloading (100%)
  - Installing symfony/yaml (v3.3.6): Downloading (100%)
  - Installing hassankhan/config (0.10.0): Downloading (100%)
  - Installing brain/hierarchy (2.3.0): Downloading (100%)
  - Installing soberwp/controller (dev-master 220d88a): Cloning 220d88a8e2 from cache
  - Installing symfony/polyfill-mbstring (v1.4.0): Loading from cache
  - Installing symfony/translation (v3.3.6): Loading from cache
  - Installing nesbot/carbon (1.22.1): Loading from cache
  - Installing symfony/process (v3.3.6): Downloading (100%)
  - Installing symfony/console (v3.3.6): Downloading (100%)
  - Installing illuminate/console (v5.4.27): Downloading (100%)
  - Installing roots/sage-installer (1.3.0): Downloading (100%)
  - Installing squizlabs/php_codesniffer (2.9.1): Loading from cache
paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
illuminate/support suggests installing symfony/var-dumper (Required to use the dd function (~3.2).)
illuminate/filesystem suggests installing league/flysystem (Required to use the Flysystem local and FTP drivers (~1.0).)
illuminate/filesystem suggests installing league/flysystem-aws-s3-v3 (Required to use the Flysystem S3 driver (~1.0).)
illuminate/filesystem suggests installing league/flysystem-rackspace (Required to use the Flysystem Rackspace driver (~1.0).)
symfony/translation suggests installing symfony/config ()
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/filesystem ()
illuminate/console suggests installing guzzlehttp/guzzle (Required to use the ping methods on schedules (~6.0).)
illuminate/console suggests installing mtdowling/cron-expression (Required to use scheduling component (~1.0).)
Generating autoload files
> Roots\Sage\Installer\ComposerScript::postCreateProject
Could not open input file: /private/tmp/some
Could not open input file: /private/tmp/some
Could not open input file: /private/tmp/some
```

FYI: the final error is not a Composer error, please direct your question to the Sage project if that is what you are trying to solve.

**Comment by dghez** [comment] 2017-11-15 10:13
That's the error I got.  I'm sorry, I'm new to composer (I downloaded it just for this theme) so for me it was a composer error. Sorry for the post and thanks for the reply. 😊

**Comment by alcohol** [comment] 2017-11-15 11:37
No problem. I'll close this now, but feel free to reply if you need more help, I can reopen it for you.

**Closed by alcohol** 2017-11-15 11:37 UTC
