### ISSUE TITLE
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: HTTP request failed!

### ISSUE THREAD

**Issue by chrisEspira** [composer/composer#7001] opened 2018-01-11 14:45 UTC
HI,
Somebody can help me solve this problem
i cannot install composer
 when i try to install composer 
I get this error
The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: HTTP request failed!

i need help please..........thx

**Comment by tomzx** [comment] 2018-01-12 20:08
Looks like a duplicate of #6515.

**Closed** 2020-09-11 15:18 UTC
