### ISSUE TITLE
Composer Install in a Network Drive - Shared Folder of VirtualBox (RuntimeException http-foundation)

### ISSUE THREAD

**Issue by Naxan** [composer/composer#3497] opened 2014-12-03 10:13 UTC
Hello !

I'm not sure i'm in the right place, but here is my thing.
I've created a VM in VirtualBox with Windows 7, and composer.
The project (using last version of Laravel) is in a Network Drive (which is a Shared Folder of my Windows host). When i try to use the command "composer install", all files are downloaded, but it fails at the very end, with this message : 

```
laravel/framework suggests installing doctrine/dbal (Allow renaming columns and dropping SQLite columns.)
Writing lock file
Generating autoload files



  [RuntimeException]
  Could not scan for classes inside "C:\dev\webapps\webapps\vendor/symfony/http-foundation/Symfony/Component/HttpFoundation/Symfony/Component/HttpFoundation/Resources/stubs" which does not appear to be a file nor a folder
```

I tried with the project inside the VM and not in a Network Drive (without the vendor folder) and it works, so it is not related to the machine.

I tried a lot of things, like deleted cache, re-install composer, but no one worked.

Just to be clear, my goal is having a VM acting as a server with all software (composer, wamp, ...) and having files of the project in the host and not in the VM. So putting the files of the project inside the VM is not a solution.

Thanks for the help :)

**Comment by Seldaek** [comment] 2015-01-01 16:27
Closing this as I don't quite see what to do.. If you have more info please provide and reopen but I can't reproduce this and can not figure out what is wrong I assume it's a VM issue and not composer bug.

**Closed by Seldaek** 2015-01-01 16:27 UTC
Labels: Support
