### ISSUE TITLE
GitExcludeFilter does not respect files already tracked by git

### ISSUE THREAD

**Issue by aaukt** [composer/composer#2607] opened 2014-01-17 08:32 UTC
Currently the [GitExcludeFilter](https://github.com/composer/composer/blob/master/src/Composer/Package/Archiver/GitExcludeFilter.php) is parsing the .gitignore file and excludes all files that match a pattern. So if you run "composer archive" those files are excluded from the resulting archive.

However, it is a valid case to have a file that would match a pattern but is already tracked by git (and "git archive" does not exclude those files), so i would expect that "composer archive" would do the same.

This issue came up when mirroring some packages with satis, as we had some dist-packages with missing files.
I know composer can't/won't mirror the git-behaviour exactly, so maybe this is an issue  in satis (e.g. make the package generation more configurable) or it should just be clarified in the documenation.

Another solution could be to add an option to the archive command to configure the used exlcude filters.

**Comment by Seldaek** [comment] 2016-04-15 15:12
Closing as duplicate of #3733

**Closed by Seldaek** 2016-04-15 15:12 UTC
Labels: Bug
