### ISSUE TITLE
No valid composer.json was found in any branch or tag of [...]

### ISSUE THREAD

**Issue by strarsis** [composer/composer#6624] opened 2017-08-22 12:39 UTC
My `composer.json`:

```json
{
  "name": "test/test",
  "type": "project",
  "config": {
    "preferred-install": "dist"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://wpackagist.org"
    },{
      "url": "https://github.com/strarsis/blade-svg-sage",
      "type": "vcs"
    }
  ],
  "require": {
    "php": ">=5.6",
    "composer/installers": "~1.0.12",
    "log1x/blade-svg-sage": "dev-fix-path"
  },
  "extra": {
    "installer-paths": {
      "web/app/mu-plugins/{$name}/": ["type:wordpress-muplugin"],
      "web/app/plugins/{$name}/": ["type:wordpress-plugin"],
      "web/app/themes/{$name}/": ["type:wordpress-theme"]
    },
    "wordpress-install-dir": "web/wp"
  }
}
```

Output of `composer diagnose`:

```
composer diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
# or
composer update
```

I get the following output:

```
[Composer\Repository\InvalidRepositoryException]
No valid composer.json was found in any branch or tag of https://github.com/strarsis/blade-svg-sage, could not load a package from it.
```

And I expected this to happen:
That blade-svg-sage fork from github.com/strarsis/blade-svg-sage is found and installed correctly.

**Comment by stof** [comment] 2017-08-22 12:57
When I'm using the composer.json you gave in the description and I'm running `composer update`, everything works fine.

**Comment by strarsis** [comment] 2017-08-22 13:05
@stof: It doesn't work on my system. Maybe this is a caching issue?

**Comment by curry684** [comment] 2017-08-22 21:07
Please run `composer install -vvv` for maximum verbosity on what it's trying to do.

**Comment by strarsis** [comment] 2017-08-24 13:58
I use composer in Bash on Windows/WSL. The issue doesn't happen in a Linux VM.
`
`composer install -vvv` output:
````
Reading ./composer.json
Loading config file /home/build/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/build/src/test): git branch --no-color --no-abbrev -v
Executing command (/home/build/src/test): git describe --exact-match --tags
Executing command (/home/build/src/test): git log --pretty="%H" -n1 HEAD
Executing command (/home/build/src/test): hg branch
Executing command (/home/build/src/test): fossil branch list
Executing command (/home/build/src/test): fossil tag list
Executing command (/home/build/src/test): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /home/build/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.5.1 (2017-08-09 16:07:22) with PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4 on Linux / 4.4.0-43-Microsoft
Loading composer repositories with package information
Downloading https://wpackagist.org/packages.json
Writing /home/build/.composer/cache/repo/https---wpackagist.org/packages.json into cache
Downloading https://api.github.com/repos/strarsis/blade-svg-sage
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/contents/composer.json?ref=master
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/commits/master
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/tags?per_page=100
Reading composer.json of https://github.com/strarsis/blade-svg-sage (v1.0.4)
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/contents/composer.json?ref=a1e77cb1fec224546a8ed3d2bbe9f9b28fcbce06
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/commits/a1e77cb1fec224546a8ed3d2bbe9f9b28fcbce06
Skipped tag v1.0.4, no composer file was found
Reading composer.json of https://github.com/strarsis/blade-svg-sage (v1.0.3)
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/contents/composer.json?ref=69b24c4134ebea24680416fb9b29c45dea9377b9
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/commits/69b24c4134ebea24680416fb9b29c45dea9377b9
Skipped tag v1.0.3, no composer file was found
Reading composer.json of https://github.com/strarsis/blade-svg-sage (v1.0.2)
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/contents/composer.json?ref=3a51a92b5a4247351088ada57304a2a54f3cd792
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/commits/3a51a92b5a4247351088ada57304a2a54f3cd792
Skipped tag v1.0.2, no composer file was found
Reading composer.json of https://github.com/strarsis/blade-svg-sage (v1.0.0)
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/contents/composer.json?ref=6596a7c02d37ae15737cbd557d1631defcc28a16
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/commits/6596a7c02d37ae15737cbd557d1631defcc28a16
Skipped tag v1.0.0, no composer file was found
Reading composer.json of https://github.com/strarsis/blade-svg-sage (1.0.1)
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/contents/composer.json?ref=13233ed6fb6df0cbb3213563c7baa18ee650454e
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/commits/13233ed6fb6df0cbb3213563c7baa18ee650454e
Skipped tag 1.0.1, no composer file was found
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/git/refs/heads?per_page=100
Reading composer.json of https://github.com/strarsis/blade-svg-sage (fix-path)
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/contents/composer.json?ref=b75845a3f52cf15a3c65478fb65226a5400bed1b
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/commits/b75845a3f52cf15a3c65478fb65226a5400bed1b
Skipped branch fix-path, no composer file was found
Reading composer.json of https://github.com/strarsis/blade-svg-sage (master)
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/contents/composer.json?ref=abf0b3e5e4b0170c98e452c36bef8b0e4de17b1f
Downloading https://api.github.com/repos/strarsis/blade-svg-sage/commits/abf0b3e5e4b0170c98e452c36bef8b0e4de17b1f
Skipped branch master, no composer file was found

                                                                                                                               
  [Composer\Repository\InvalidRepositoryException]                                                                             
  No valid composer.json was found in any branch or tag of https://github.com/strarsis/blade-svg-sage, could not load a packa  
  ge from it.                                                                                                                  
                                                                                                                               

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Repository/VcsRepository.php:275
 Composer\Repository\VcsRepository->initialize() at phar:///usr/local/bin/composer/src/Composer/Repository/ArrayRepository.php:185
 Composer\Repository\ArrayRepository->getPackages() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:104
 Composer\DependencyResolver\Pool->addRepository() at phar:///usr/local/bin/composer/src/Composer/Installer.php:376
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:223
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/InstallCommand.php:119
 Composer\Command\InstallCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:266
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:861
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:208
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:245
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:127
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:100
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:54
 require() at /usr/local/bin/composer:24

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...


````

**Comment by curry684** [comment] 2017-08-24 17:47
That's really weird, the logs indicate no `composer.json` exists in *any* of the branches or tags, despite it being in every one of them over at https://github.com/strarsis/blade-svg-sage/blob/fix-path/composer.json. Given that the issue only occurs on Windows it's either related to the directory separator or case sensitivity in the paths, likely the first.

@Seldaek no Windows dev machine here anymore, you still have one?

**Comment by strarsis** [comment] 2017-08-24 18:57
It works in cmd directly. So this seems to be a Bash on Windows/WSL issue.

**Comment by curry684** [comment] 2017-08-24 23:48
Yeah I got triggered by this line:
```
Running 1.5.1 (2017-08-09 16:07:22) with PHP 7.1.8-2+ubuntu16.04.1+deb.sury.org+4 on Linux / 4.4.0-43-Microsoft
```
I really have no clue whatsoever how this affects things like path handling in PHP. It may just be terribly confused about the path separators and things like `realpath` functions.

**Comment by strarsis** [comment] 2017-09-01 23:45
@curry684: Thanks! How can I further help / debug this issue?

**Comment by curry684** [comment] 2017-09-02 16:02
That will be kind of hard, as you won't be able to reproduce this while debugging in an IDE. If you want to help you can of course clone the Composer code (fork it first), and debug it the old way - look for the offending code, and insert `print_r` or `die` statements around them to determine where the discrepancy in paths starts to occur. Based on that you should be able to pinpoint it pretty fast if you're experienced with PHP.

I'd be happy to dive into it myself but stopped using Windows for development a while back, so I'd have a lot of work to do to set up a reproducer.

**Comment by Seldaek** [comment] 2018-04-13 09:30
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.

**Closed by Seldaek** 2018-04-13 09:30 UTC
Labels: Support

**Comment by donquixote** [comment] 2020-12-12 15:13
The same or similar is happening for me, for a github repository with private access, which I access using a token.
It tries to download a composer.json for every branch, each with a separate request. When I run with -vvv, most of these requests are followed by "Skipped branch ***, no composer file was found (404 HTTP status code).

```
Reading composer.json of VENDOR/PACKAGE (BRANCH)
Downloading https://api.github.com/repos/ORG/PROJECT/contents/composer.json?ref=COMMIT_ID
Skipped branch BRANCH, no composer file was found (404 HTTP status code)
```

When I access the url with a browser, I get the response as below. Perhaps because the token is not transmitted:
```
{
  "message": "Not Found",
  "documentation_url": "https://docs.github.com/rest/reference/repos#get-repository-content"
}
```
In the end it seems to work anyway..

Composer version 1.10.17

-------

What I don't get: Why does composer need to download every version of composer.json separately from github? Why not simply clone the repo, and do the rest locally? It seems in the end the repo is being cloned anyway, is it not?

**Comment by Adebayo120** [comment] 2022-10-25 14:16
Hi @strarsis were you able to solve this issue, also experiencing same issue

**Comment by strarsis** [comment] 2022-10-25 15:01
@Adebayo120: Good question. This was in the early days of WSL 1. I switched now to WSL 2 and work on my source code in the Linux file system (e.g. `~/src`) and don't have these issues anymore.
