### ISSUE TITLE
'rejected by your constraint' error message should show where the constraint comes from

### ISSUE THREAD

**Issue by joachim-n** [composer/composer#6407] opened 2017-05-08 10:48 UTC
When I run this command:

```
composer update
```

I get the following output:

```
  Problem 1
    - The requested package foo/bar ... exists as foo/bar[...] but these are rejected by your constraint.
```

The package foo/bar isn't mentioned in my composer.json, therefore it must be getting requested by something else.

However, I don't see how I can discover what is causing the problem. The error message should give an indication of this.

Doing 'composer show --tree foo/bar' says:

```
  [InvalidArgumentException]
  Package foo/bar not found
```

**Comment by alcohol** [comment] 2017-05-08 13:05
Need reproducible scenario.

**Comment by joachim-n** [comment] 2017-05-08 14:42
I'm afraid I can't provide the composer.json file, as it's a client project.

**Comment by alcohol** [comment] 2017-05-09 09:59
Did you try using the `why-not` command?

**Comment by joachim-n** [comment] 2017-05-26 08:56
That command doesn't appear to work when a package hasn't been installed yet.

**Comment by curry684** [comment] 2017-05-26 09:26
> I'm afraid I can't provide the composer.json file, as it's a client project.

Unless the error is caused by internal projects it should not be a problem to remove possibly sensitive bits and reduce the file to an [SSCCE](http://sscce.org/).

**Comment by Seldaek** [comment] 2018-04-13 09:25
Automatically closing as this has not received any updates in a while. Please re-open if it is still relevant.

**Closed by Seldaek** 2018-04-13 09:25 UTC
Labels: Support

**Comment by dungnt081191** [comment] 2018-07-12 09:16
still have this issue 
Problem 1                                                                                                                                          
15:57:39       - The requested package squizlabs/php_codesniffer 3.2.3 exists as squizlabs/php_codesniffer[3.3.0] but these are rejected by your constraint.

**Comment by xabbuh** [comment] 2018-07-12 10:00
@dungnt081191 What's your `composer.json` file and what did you do that led to this error?

**Comment by dungnt081191** [comment] 2018-07-12 10:08
my composer.json about laravel 
and some require file are : 
    "require": {
        "php": ">=7.0.0",
        "aws/aws-sdk-php": "*",
        "doctrine/dbal": "^2.7",
        "fideloper/proxy": "~3.3",
        "laravel/framework": "5.5.*",
        "laravel/tinker": "~1.0",
        "laravelcollective/html": "^5.5",
        "maatwebsite/excel": "~2.1.0",
        "mpdf/mpdf": "^7.0",
        "phpmd/phpmd": "2.6.0",
        "phpoffice/phpexcel": "1.8.1",
        "phpoffice/phpword": "v0.14.0",
        "squizlabs/php_codesniffer": "3.2.3",
        "tecnickcom/tcpdf": "6.2.*",
        "yajra/laravel-datatables-oracle": "^8.4"
    },
    "require-dev": {
        "barryvdh/laravel-debugbar": "^3.1",
        "barryvdh/laravel-ide-helper": "*",
        "filp/whoops": "~2.0",
        "fzaninotto/faker": "~1.4",
        "mockery/mockery": "~1.0",
        "phpmd/phpmd": "@stable",
        "phpunit/phpunit": "~6.0",
        "squizlabs/php_codesniffer": "*",
        "symfony/thanks": "^1.0"

**Comment by vlaidmeR** [comment] 2018-07-12 10:10
my composer.json about laravel
and some require file are :
"require": {
"php": ">=7.0.0",
"aws/aws-sdk-php": "",
"doctrine/dbal": "^2.7",
"fideloper/proxy": "~3.3",
"laravel/framework": "5.5.",
"laravel/tinker": "~1.0",
"laravelcollective/html": "^5.5",
"maatwebsite/excel": "~2.1.0",
"mpdf/mpdf": "^7.0",
"phpmd/phpmd": "2.6.0",
"phpoffice/phpexcel": "1.8.1",
"phpoffice/phpword": "v0.14.0",
"squizlabs/php_codesniffer": "3.2.3",
"tecnickcom/tcpdf": "6.2.",
"yajra/laravel-datatables-oracle": "^8.4"
},
"require-dev": {
"barryvdh/laravel-debugbar": "^3.1",
"barryvdh/laravel-ide-helper": "",
"filp/whoops": "~2.0",
"fzaninotto/faker": "~1.4",
"mockery/mockery": "~1.0",
"phpmd/phpmd": "@stable",
"phpunit/phpunit": "~6.0",
"squizlabs/php_codesniffer": "*",
"symfony/thanks": "^1.0"

**Comment by dungnt081191** [comment] 2018-07-12 10:13
@vlaidmeR  what do you think?

**Comment by xabbuh** [comment] 2018-07-12 10:21
This still does miss the information about what steps you did perform to end up with this error message.

**Comment by dungnt081191** [comment] 2018-07-12 10:23
@xabbuh  this is total error message when i trigger job from Jenkins : 
17:14:12 + composer install
17:14:12 Loading composer repositories with package information
17:14:13 Updating dependencies (including require-dev)
17:15:37 
17:15:37                                                                                                                                                      
17:15:37   [Composer\DependencyResolver\SolverProblemsException]                                                                                              
17:15:37   Problem 1                                                                                                                                          
17:15:37       - The requested package squizlabs/php_codesniffer 3.2.3 exists as squizlabs/php_codesniffer[3.3.0] but these are rejected by your constraint.  
17:15:37                                                                                                                                                      
17:15:37 
17:15:37 install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--] [<packages>]...
17:15:37 
17:15:37 Build step 'Execute shell' marked build as failure
17:15:37 Finished: FAILURE

**Comment by xabbuh** [comment] 2018-07-12 10:50
You have `squizlabs/php_codesniffer` in `require` and `require-dev`. Removing one of the two should resolve your issue.

**Comment by itscaro** [comment] 2018-10-29 23:57
I encountered many times this error. I need to `require` the package first then fire `require --dev` to move it to dev dependencies
