### ISSUE TITLE
Improve Composer output, make language more helpful to novices.

### ISSUE THREAD

**Issue by grasmash** [composer/composer#6691] opened 2017-09-18 19:24 UTC
Composer's output can be very difficult to interpret, even for those who already understand what's happening.

I believe that this is largely responsible for the criticism that composer is overly complex or difficult to use. Improving the clarity of the language used to describe installation and update failures would go a long way towards improving the developer experience.

I've opened this issue to begin a discussion on what we would like the output to be.

Ideally, the output from a failed installation or update should:
1) Clearly and succinctly identify the problem
2) Offer actionable solutions
3) Assume no knowledge of the internal workings of Composer.

It is apparent from the current behavior composer that these principles have been considered before. The problem/conclusion format of the current output is a nice starting point.

I'd like to outline a few example scenarios, show their current output, and offer suggestions for improved output.

##  Scenario 1: Redundant output

```
composer require grasmash/yaml-cli
composer require symfony/console:~2.0.4
``` 

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - grasmash/yaml-cli 1.0.3 requires symfony/console ^2.8.11|^3.2 -> satisfiable by symfony/console[2.8.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9] but these conflict with your requirements or minimum-stability.
    - grasmash/yaml-cli 1.0.3 requires symfony/console ^2.8.11|^3.2 -> satisfiable by symfony/console[2.8.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9] but these conflict with your requirements or minimum-stability.
    - grasmash/yaml-cli 1.0.3 requires symfony/console ^2.8.11|^3.2 -> satisfiable by symfony/console[2.8.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9] but these conflict with your requirements or minimum-stability.
    - Installation request for grasmash/yaml-cli (locked at 1.0.3, required as ^1.0) -> satisfiable by grasmash/yaml-cli[1.0.3].
```

There are a few issues with this output:

1. This output is redundant and overly verbose. The first three points are identical. 
1. The problem is generally but not specifically stated. The specific problem is that the user has executed a command to require symfony/console:~2.0.4, but that is not compatible with the existing grasmash/yaml-cli 1.0.3 requirement. This is not clearly stated.
1. The last bullet point seems only tangentially related, like a bit of metadata tacked on at the end to help the user decipher the true meaning of the problem.

I believe the better output would be:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1: 
    Summary: `symfony/console:~2.0.4` cannot be installed because it conflicts with the root requirement `grasmash/yaml-cli: ^1.0`. 
    Suggestion: Install a version of symfony/console that is compatible with grasmash/yaml-cli 1.0.3 or install a different version of grasmash/yaml-cli.
    Related information:
    - grasmash/yaml-cli 1.0.3 requires symfony/console ^2.8.11|^3.2 -> satisfiable by symfony/console[2.8.x-dev, 3.2.x-dev, 3.3.x-dev, 3.4.x-dev, v2.8.11, v2.8.12, v2.8.13, v2.8.14, v2.8.15, v2.8.16, v2.8.17, v2.8.18, v2.8.19, v2.8.20, v2.8.21, v2.8.22, v2.8.23, v2.8.24, v2.8.25, v2.8.26, v2.8.27, v3.2.0, v3.2.0-BETA1, v3.2.0-RC1, v3.2.0-RC2, v3.2.1, v3.2.10, v3.2.11, v3.2.12, v3.2.13, v3.2.2, v3.2.3, v3.2.4, v3.2.5, v3.2.6, v3.2.7, v3.2.8, v3.2.9, v3.3.0, v3.3.0-BETA1, v3.3.0-RC1, v3.3.1, v3.3.2, v3.3.3, v3.3.4, v3.3.5, v3.3.6, v3.3.7, v3.3.8, v3.3.9] but these conflict with your requirements or minimum-stability.
```

I will post more scenarios after I create easily reproducible steps for example output.

**Comment by grasmash** [comment] 2017-09-18 19:34
## Scenario 2:  "can only install one of"

```
composer create-project acquia/lightning-project MY_PROJECT
cd MY_PROJECT
composer require drupal/core:8.4.0-rc1
```

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - acquia/lightning 2.1.7 requires drupal/core ~8.3.1 -> satisfiable by drupal/core[8.3.x-dev].
    - acquia/lightning 2.1.7 requires drupal/core ~8.3.1 -> satisfiable by drupal/core[8.3.x-dev].
    - acquia/lightning 2.1.7 requires drupal/core ~8.3.1 -> satisfiable by drupal/core[8.3.x-dev].
    - Can only install one of: drupal/core[8.4.0-rc1, 8.3.x-dev].
    - Installation request for drupal/core 8.4.0-rc1 -> satisfiable by drupal/core[8.4.0-rc1].
    - Installation request for acquia/lightning (locked at 2.1.7, required as ~2.1.0) -> satisfiable by acquia/lightning[2.1.7].
```

In this output, I'd like to focus on the "Can only install one of: drupal/core[8.4.0-rc1, 8.3.x-dev]."  part.  The value of this statement is not clear to me. I don't believe that anyone will ever try to install two versions of the same package. Presumably, this is just saying that is unable to install the requested version? 

 Improved output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1: 
    Summary: `drupal/core:8.4.0-rc2` cannot be installed because it conflicts with the root requirement `acquia/lightning 2.1.7`.
    Suggestion: Install a version of drupal/core that is compatible with acquia/lightning 2.1.7 or install a different version of acquia/lightning.
    Related Information:
    - acquia/lightning 2.1.7 requires drupal/core ~8.3.1 -> satisfiable by drupal/core[8.3.x-dev].
    - Installation request for acquia/lightning (locked at 2.1.7, required as ~2.1.0) -> satisfiable by acquia/lightning[2.1.7].
    - Installation request for drupal/core 8.4.0-rc1 -> satisfiable by drupal/core[8.4.0-rc1].
```

**Comment by grasmash** [comment] 2017-09-18 21:58
## Scenario 3: "Conclusion: don't install" && "Conclusion: remove"

Sometimes, requiring a new Composer package results in Composer suggesting that other packages be removed or not installed.  In general, this seems counterproductive. Typically removing a package is not a viable course of action--it's typically there because it's being used. Much more often the answer is to change one or more package versions.

That aside, this advice can be extremely confusing for a novice, particularly if the package suggested for removal is not one that is listed in the root composer.json file or the one being explicitly required by the current command.

```
composer create-project acquia/lightning-project MY_PROJECT
cd MY_PROJECT
composer remove drush/drush
composer require acquia/blt:8.x-dev
```

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for acquia/blt 8.x-dev -> satisfiable by acquia/blt[8.x-dev].
    - Conclusion: remove doctrine/inflector v1.2.0
    - Conclusion: don't install doctrine/inflector v1.2.0
    - acquia/blt 8.x-dev requires doctrine/inflector ~1.1.0 -> satisfiable by doctrine/inflector[1.1.x-dev, v1.1.0].
    - Can only install one of: doctrine/inflector[1.1.x-dev, v1.2.0].
    - Can only install one of: doctrine/inflector[v1.1.0, v1.2.0].
    - Installation request for doctrine/inflector (locked at v1.2.0) -> satisfiable by doctrine/inflector[v1.2.0].
```

Most of this output does not provide any value to the end-user.

Improved output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1: 
    Summary: `acquia/blt 8.x-dev` cannot be installed because requires doctrine/inflector ~1.1.0,  which conflicts with the root requirement drupal/core 8.3.7.
    Suggestion: Install a version of acquia/blt that is compatible with drupal/core 8.3.7, or install a different version of drupal/core.
    Related information:
    - Installation request for acquia/blt 8.x-dev -> satisfiable by acquia/blt[8.x-dev].
    - acquia/blt 8.x-dev requires doctrine/inflector ~1.1.0 -> satisfiable by doctrine/inflector[1.1.x-dev, v1.1.0].
    - drupal/core 8.3.7 requires doctrine/common (^2.5), which requires doctrine/inflector -> satisfiable by doctrine/inflector[1.1.x-dev, v1.1.0].
    - Installation request for doctrine/inflector (locked at v1.2.0) -> satisfiable by doctrine/inflector[v1.2.0].
```

I suspect that this improved output is difficult to generate. The key here is that we need to give users some insight into the dependency chain. In this case, we need to communicate that  a dependency of a dependency is to blame for the conflict, not a root dependency.

As an intermediary, and be worthwhile to simply say "you may use `composer why` to determine why this package is being installed."

**Comment by grasmash** [comment] 2017-09-18 22:11
In summary, the issues to address (as represented by the three scenarios),  include:

1. Structure output for problems as: 
    a. Summary
    b. Suggestion
    c. Related information.
1. Reduce duplicative output.
1. Remove or rephrase output that does not provide value to the end-user.
    a. "can only install one of"
    b. "Conclusion: remove"
    c. "Conclusion: don't install"
1. When there is a version conflict in a "recursive case" dependency, indicate the root dependencies responsible for the conflict.

**Comment by alcohol** [comment] 2017-09-19 10:09
@naderman you know most about the solver and conflict (resolution) rules. Is there anything we can do with the above feedback? I remember that the reason it currently is so "complex" is literally because solving is just a very complex thing and the results that we get from the solver are not that easy to interpret?

**Comment by weitzman** [comment] 2019-04-09 17:08
Great writeup! We could be giving such a better user experience.

Not to quibble about tags, but labelling this issue as _Nice to Have_ and _Feature_ makes it seem less important. In the context of user experience, I hope we can call them bugs. If the maintainers can say a bit more about next steps for fixing some of them, that would be much appreciated.

**Comment by alcohol** [comment] 2019-04-10 06:18
I think #7779 is related to this.

**Comment by naderman** [comment] 2020-03-11 14:29
There have been a lot of improvements to error reporting in 2.0 @Seldaek can you review the suggestions here and see if anything else should be adjusted?

**Comment by Seldaek** [comment] 2020-03-13 16:11
The main problem is all the examples above I can't reproduce anymore as either things changed in 2.0 in resolution or the ecosystem changed and it doesn't break in the same way.. So hard to tell exactly, but for sure the 2.0 branch improves things quite a bit so I'm gonna close this now. 

It's not perfect yet though, and @grasmash I think it'd be great if you can report more of these once 2.0 is getting ready for usage, if we can improve further we'd like to but I think at this point most of the easy ones are tackled and it'll get harder to extract more actionable feedback in a generic way. It's always easy to say "this or that" when looking at a specific case, but building code/rules to identify such cases definitely is another story. 

One way to help for sure is to identify the conditions which cause some problem, and write a test file like https://github.com/composer/composer/pull/8690/files#diff-f7eb2d91175f91f5dc464d891c6f2806 where you can define the lock file state, the remote repos packages, and the command to run. If we get that it gets much easier to iterate on a solution, and especially it's something that doesn't break in a few months after package x and y released new versions.

**Closed by Seldaek** 2020-03-13 16:11 UTC
Labels: Feature, Question, Solver
