### ISSUE TITLE
Prefer source or dist on by-package basis

### ISSUE THREAD

**Issue by mcd-php** [composer/composer#3862] opened 2015-03-23 09:02 UTC
I wish to install most of the dependencies packages as dist (to reduce file tree size and avoid extra load on github) but only the chosen packages as source from VCS, since I want to make and track changes in them.

Any plans on including dist/source preferences in `composer.json` ?

**Comment by barryvdh** [comment] 2015-04-20 08:57
This is a duplicate of #2885 right?

**Comment by mcd-php** [comment] 2015-04-30 06:02
Yes, indeed. Sorry for not searching harder ;(

**Closed** 2015-05-01 09:41 UTC
