### ISSUE TITLE
After update 1.4.2 → 1.5.1 in Symfony some script is broken

### ISSUE THREAD

**Issue by chernomyrdin** [composer/composer#6599] opened 2017-08-09 15:02 UTC
My `composer.json`:

```json
{
    "name": "foo/bar",
    "license": "proprietary",
    "type": "project",
    "autoload": {
        "psr-4": {
            "": "src/"
        },
        "classmap": [
            "app/AppKernel.php",
            "app/AppCache.php"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        },
        "files": [
            "vendor/symfony/symfony/src/Symfony/Component/VarDumper/Resources/functions/dump.php"
        ]
    },
    "require": {
        "php": ">=5.5.9",
        "doctrine/doctrine-bundle": "^1.6",
        "doctrine/doctrine-cache-bundle": "^1.2",
        "doctrine/orm": "^2.5",
        "friendsofsymfony/rest-bundle": "^2.2",
        "incenteev/composer-parameter-handler": "^2.0",
        "jms/serializer-bundle": "^2.0",
        "nelmio/api-doc-bundle": "^2.13",
        "predis/predis": "^1.0",
        "sensio/distribution-bundle": "^5.0",
        "sensio/framework-extra-bundle": "^3.0.2",
        "snc/redis-bundle": "2.x-dev",
        "symfony/monolog-bundle": "^3.0.2",
        "symfony/polyfill-apcu": "^1.0",
        "symfony/symfony": "3.2.*",
        "twig/twig": "^1.0||^2.0"
    },
    "require-dev": {
        "sensio/generator-bundle": "^3.0",
        "symfony/phpunit-bridge": "^3.0"
    },
    "scripts": {
        "symfony-scripts": [
            "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
            "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::prepareDeploymentTarget"
        ],
        "post-install-cmd": [
            "@symfony-scripts"
        ],
        "post-update-cmd": [
            "@symfony-scripts"
        ]
    },
    "config": {
        "sort-packages": true
    },
    "extra": {
        "symfony-app-dir": "app",
        "symfony-bin-dir": "bin",
        "symfony-var-dir": "var",
        "symfony-web-dir": "web",
        "symfony-tests-dir": "tests",
        "symfony-assets-install": "relative",
        "incenteev-parameters": {
            "file": "app/config/parameters.yml"
        },
        "branch-alias": null
    }
}
```

Output of `composer diagnose`:

```
> bin/composer.phar diagnose
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
require.snc/redis-bundle : exact version constraints (2.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.4.2 => 1.5.1)
```

When I run this command:

```
> rm composer.lock 
> bin/composer.phar install
> bin/symfony_requirements
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

                                                                                
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    
                                                                                

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- -------------------- ------------------ 
      Bundle               Method / Error    
 --- -------------------- ------------------ 
  ✔   NelmioApiDocBundle   relative symlink  
 --- -------------------- ------------------ 

                                                                                
 [OK] All assets were successfully installed.                                   
                                                                                

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget

Symfony Requirements Checker
~~~~~~~~~~~~~~~~~~~~~~~~~~~~

> PHP is using the following php.ini file:
  /etc/php/7.0/cli/php.ini

> Checking Symfony requirements:
  ..................................W........

                                              
 [OK]                                         
 Your system is ready to run Symfony projects 
                                              

Optional recommendations to improve your setup
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

 * intl ICU version installed on your system is outdated (57.1) and
   does not match the ICU data bundled with Symfony (59.1)
   > To get the latest internationalization data upgrade the ICU
   > system package and the intl PHP extension.


Note  The command console could use a different php.ini file
~~~~  than the one used with your web server. To be on the
      safe side, please check the requirements from your web
      server using the web/config.php script.

```
All ok.

Try to update composer:

Output of `bin/composer.phar self-update`:
```
Updating to version 1.5.1 (stable channel).
   Downloading (100%)         
Use composer self-update --rollback to return to version 1.4.2
```
Output of `composer diagnose`:
```
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
require.snc/redis-bundle : exact version constraints (2.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

Run `bin/composer.phar install`
```
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Nothing to install or update
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache

 // Clearing the cache for the dev environment with debug                       
 // true                                                                        

                                                                                
 [OK] Cache for the "dev" environment (debug=true) was successfully cleared.    
                                                                                

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets

 Trying to install assets as relative symbolic links.

 --- -------------------- ------------------ 
      Bundle               Method / Error    
 --- -------------------- ------------------ 
  ✔   NelmioApiDocBundle   relative symlink  
 --- -------------------- ------------------ 

 [OK] All assets were successfully installed.                                   

> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::prepareDeploymentTarget
```

Run `bin/symfony_requirements`
```
PHP Warning:  require_once(/path/to/bin/./SymfonyRequirements.php): failed to open stream: No such file or directory in /path/to/bin/symfony_requirements on line 4
PHP Stack trace:
PHP   1. {main}() /path/to/bin/symfony_requirements:0
PHP Fatal error:  require_once(): Failed opening required '/path/to/bin/./SymfonyRequirements.php' (include_path='.:/usr/share/php') in /path/to/symfony_requirements on line 4
PHP Stack trace:
PHP   1. {main}() /path/to/bin/symfony_requirements:0
```

In 1.5.1 /path/to/bin/symfony_requirements on line 4
```
require_once dirname(__FILE__).'/./SymfonyRequirements.php';
```

In 1.4.2/path/to/bin/symfony_requirements on line 4
```
require_once dirname(__FILE__).'/../var/SymfonyRequirements.php';
```

**Comment by goedderz** [comment] 2017-08-10 07:51
I can confirm the problem with multiple different Symfony projects. It also does not only occur within symfony_requirements, but other files like `web/config.php` as well:

```
-require_once dirname(__FILE__).'/../var/SymfonyRequirements.php';
+require_once dirname(__FILE__).'/./SymfonyRequirements.php';
```

**Comment by derrabus** [comment] 2017-08-12 12:40
This is the same bug as sensiolabs/SensioDistributionBundle#324, I guess.

**Comment by alcohol** [comment] 2017-08-14 05:53
@Seldaek I recall there was something you modified/changed for path resolving. Might have broken some things it seems?

**Comment by xelaris** [comment] 2017-08-14 22:58
This happens because composer 1.5.0 changed the bundled version of symfony/filesystem from v2.8.18 to v2.8.26. So this is not a directly related to composer, but probably a BC break in the Filesystem component or a misusage of the `makePathRelative` in `SensioDistributionBundle` (see symfony/symfony#22321)

**Comment by Seldaek** [comment] 2017-08-15 06:01
From reading that issue, it sounds like the makePathRelative call should be made after realpath'ing both paths in SensioDistributionBundle?

**Comment by fabpot** [comment] 2017-08-25 16:48
This one can be closed as the issue is not in Composer. Fix coming for SensioDistributionBundle.

**Closed** 2017-08-25 17:10 UTC
Labels: Bug
