### ISSUE TITLE
Feature request: composer-override.json

### ISSUE THREAD

**Issue by zmitic** [composer/composer#9612] opened 2021-01-14 19:13 UTC
##### Short explanation

If ``composer-override.json`` is present, merge its values into ``composer.json``.

##### Longer

Right now, I am making reusable Symfony bundle for admin. To make things easier, I also set playground project where I require that bundle like

```json
"require": {
    "me/my_budle": "*"
},
"repositories": [
  {
     "type": "github", 
     "url": "https://github.com/me/my-bundle"
  },
]
```

PHPStorm is set to copy files from bundle to ``/vendor`` of playground; that way, I don't have to use symlink dependencies and can safely commit to github. The worst case scenario is someone downloading playground with older version of bundle due to ``composer.lock``.

But setting PHPStorm is not fun at all especially when 2 or more packages become part of playground.

So the request would if ``composer-override.json`` has this:

```json
"repositories": [
  {
     "type": "path", 
     "url": "../../my_packages/directory_of_admin_bundle"
  },
]

``` 

its resolved values would merge to resolved values of ``composer.json``.

---

Everything I googled pointed to composer plugin that would enable this feature but then this plugin would have to be part of package.

Possible solution would be using ENV variables but it is not as user-friendly as this.

**Comment by Seldaek** [comment] 2021-01-14 20:16
I believe this use case is well served by https://github.com/wikimedia/composer-merge-plugin - this is not something we are looking to add. You can also track https://github.com/composer/composer/issues/601 which this is kind of a duplicate of.

**Closed by Seldaek** 2021-01-14 20:16 UTC

**Comment by zmitic** [comment] 2021-01-14 20:32
@Seldaek 

>I believe this use case is well served by https://github.com/wikimedia/composer-merge-plugin - this is not something we are looking to add

I mentioned it; all search results point to that plugin but that also means plugin becomes dependency for everyone. 

The suggested feature is to avoid extra dependency for regular users but helping a lot in developing packages locally. 

---

If final decision is to not implement this merge, I will take a look at some fork; hopefully someone made it :smile:

**Comment by Seldaek** [comment] 2021-01-14 20:46
Yeah sorry actually what you should look at for this use case is rather studio: https://github.com/franzliedke/studio

**Comment by zmitic** [comment] 2021-01-14 20:48
Thanks! And #601 does have lots of ideas, no idea why google didn't point me to it.

Studio looks like good replacement for this problem.
