### ISSUE TITLE
--quiet should output errors

### ISSUE THREAD

**Issue by lastorset** [composer/composer#4017] opened 2015-05-09 13:31 UTC
In my experience (which, admittedly, does not cover a lot of the modern PHP ecosystem), the convention for `--quiet` is that it silences all output when things are going well, but still outputs warnings and errors. Often additional quiet levels are offered, so you could squelch normal messages at level 1, warnings at level 2, and errors (the current Composer behavior) at level 3.

My use case is that I want to include "composer install" in a deployment script, but I don't want a lot of noise when there isn't any problem. Currently 4 lines are output if all packages are OK. With `--quiet`, nothing is output if there is an error. I would like `--quiet` not to squelch errors.

Ideally I would want multiple quiet levels, one of which shows a one-line message before installing each top-level package (i. e. not for each dependency), and nothing else except warnings and errors. That's the one I would use for my script.

**Comment by hkdobrev** [comment] 2015-05-13 06:30
:+1:

**Comment by alcohol** [comment] 2015-06-03 07:35
Proper use of output levels (verbose, very verbose, very very verbose) and the ones you suggested (different quiet levels) is definitely a nice to have. It requires quite a lot of grunt work though, so it probably isn't going to happen any time soon.

**Comment by Seldaek** [comment] 2015-06-03 11:26
The problem is that this is defined by symfony/console itself and --quiet disables all output. I think moving this discussion there would be best, similarly the -v/vv/vvv initially came from here.

**Closed** 2015-06-03 11:26 UTC
