### ISSUE TITLE
Composer keeps remote if you have the correct version in vendor folder.

### ISSUE THREAD

**Issue by fabiocarneiro** [composer/composer#3703] opened 2015-02-03 15:08 UTC
I guess it's a bug. When you update your packages and then you want to use a new remote and you have both remotes in the same version, although it properly connects to the new remote to get the last version. If you have that same version currently installed (in your vendor folder), it considers this package to be up to date and doesn't properly update the composer.lock with the new remote address, instead keeping the old remote address, which you may have access locally but removed this remove permission in a deployment environment (which was exactly what happened to me).

To fix this, once composer connects to a remote to retrieve the last package version, it must update the remote address in composer.lock no matter if the package is updated or not.

**Comment by stof** [comment] 2015-02-21 14:00
Duplicate of #2416

**Closed** 2015-06-02 14:14 UTC
