### ISSUE TITLE
Validation of inline package definition in repositories is broken in latest build

### ISSUE THREAD

**Issue by skors** [composer/composer#6028] opened 2017-01-02 19:47 UTC
My `composer.json`:

```json
{
    "require": {
        "xxxx/yyyyy": "0.0.1"
    },
    "repositories": [
        {
          "type": "package",
          "package": {
            "name": "xxxx/yyyyy",
            "version": "0.0.1",
            "authors": [
              {
                "name": "xxxx xxxx",
                "email": "xxxxx@xxxx.xyz"
              }
            ],
            "dist": {
              "type": "zip",
              "url": "https://xxxxx/xyz.zip",
              "reference": "123abc"
            }
          }
        }
    ]
}
```

Output of `composer diagnose`:

```
not possible, error occurs directly, see output
```

When I run this command:

```
php composer.phar install -o
```
or
```
php composer.phar update -o
```

I get the following output:

```

  [Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - repositories[0] : Must contain no more than 1 properties
   - repositories[0].package : Object value found, but a boolean is required
   - repositories[0].package : Does not have a value in the enumeration [false]
   - repositories[0].package : Object value found, but an array is required
   - repositories[0].package : The property dist is not defined and the definition does not allow additional properties
   - repositories[0].package : Failed to match exactly one schema
   - repositories[0].url : The property url is required
   - repositories[0].type : Does not have a value in the enumeration ["composer"]
   - repositories[0].type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg","hg-bitbucket","fossil","perforce","svn"]
   - repositories[0].type : Does not have a value in the enumeration ["path"]
   - repositories[0].type : Does not have a value in the enumeration ["artifact"]
   - repositories[0].type : Does not have a value in the enumeration ["pear"]
   - repositories[0] : Failed to match exactly one schema

```

And I expected this to happen:

install package from given url

**Comment by bryangruneberg** [comment] 2017-01-02 21:02
Confirmed

**WORKING**: Composer version 1.3.0 2016-12-24 00:47:03 

**FAILS as per issue description**: Composer version 1.3-dev (38e02eda7cb1da22817f11b61ce88852951f892f) 2017-01-02 15:27:28

**Comment by skors** [comment] 2017-01-02 21:15
@bryangruneberg thanks, i missed adding explizit used version numbers.

**Comment by alcohol** [comment] 2017-01-03 08:37
@stof @Seldaek is this the same issue as was reported earlier? Is this fixed in latest dev already or not?

**Comment by stof** [comment] 2017-01-03 08:47
@alcohol I'm not sure.

**Comment by Seldaek** [comment] 2017-01-03 08:49
This looks like maybe it's another issue with dist this time..

   - repositories[0].package : The property dist is not defined and the definition does not allow additional properties

**Comment by Rudloff** [comment] 2017-01-03 09:42
I can reproduce with 550376d649672f65af3c481498b185f46ab94c65 and [this composer.json](https://github.com/Rudloff/alltube/blob/develop/composer.json).

Here is the error:
```
  [Composer\Json\JsonValidationException]                                                                                                                           
  "./composer.json" does not match the expected JSON schema:                                                                                                        
   - repositories[0] : Must contain no more than 1 properties                                                                                                       
   - repositories[0].package : Object value found, but a boolean is required                                                                                        
   - repositories[0].package : Does not have a value in the enumeration [false]                                                                                     
   - repositories[0].package : Object value found, but an array is required                                                                                         
   - repositories[0].package : The property dist is not defined and the definition does not allow additional properties                                             
   - repositories[0].package : Failed to match exactly one schema                                                                                                   
   - repositories[0].url : The property url is required                                                                                                             
   - repositories[0].type : Does not have a value in the enumeration ["composer"]                                                                                   
   - repositories[0].type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg","hg-bitbucket","fossil","perforce","svn"]  
   - repositories[0].type : Does not have a value in the enumeration ["path"]                                                                                       
   - repositories[0].type : Does not have a value in the enumeration ["artifact"]                                                                                   
   - repositories[0].type : Does not have a value in the enumeration ["pear"]                                                                                       
   - repositories[0] : Failed to match exactly one schema                                                                                                           
   - repositories[1] : Must contain no more than 1 properties                                                                                                       
   - repositories[1].package : Object value found, but a boolean is required                                                                                        
   - repositories[1].package : Does not have a value in the enumeration [false]                                                                                     
   - repositories[1].package : Object value found, but an array is required                                                                                         
   - repositories[1].package : The property dist is not defined and the definition does not allow additional properties                                             
   - repositories[1].package : Failed to match exactly one schema                                                                                                   
   - repositories[1].url : The property url is required                                                                                                             
   - repositories[1].type : Does not have a value in the enumeration ["composer"]                                                                                   
   - repositories[1].type : Does not have a value in the enumeration ["vcs","github","git","gitlab","git-bitbucket","hg","hg-bitbucket","fossil","perforce","svn"]  
   - repositories[1].type : Does not have a value in the enumeration ["path"]                                                                                       
   - repositories[1].type : Does not have a value in the enumeration ["artifact"]                                                                                   
   - repositories[1].type : Does not have a value in the enumeration ["pear"]                                                                                       
   - repositories[1] : Failed to match exactly one schema   
```

**Comment by joachimVT** [comment] 2017-01-03 09:42
I'm having the same issues

`[Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - repositories.newance-language-nl : Object value found, but a boolean is required
   - repositories.newance-language-nl : Does not have a value in the enumeration [false]
   - repositories.newance-language-nl.package : The property package is required
   - repositories.newance-language-nl.type : Does not have a value in the enumeration ["package"]
   - repositories.newance-language-nl.type : Does not have a value in the enumeration ["composer"]
   - repositories.newance-language-nl.url : Invalid URL format
   - repositories.newance-language-nl.type : Does not have a value in the enumeration ["path"]
   - repositories.newance-language-nl.type : Does not have a value in the enumeration ["artifact"]
   - repositories.newance-language-nl.type : Does not have a value in the enumeration ["pear"]
   - repositories.newance-language-nl : Failed to match exactly one schema
   - repositories.districompany-language-nl : Object value found, but a boolean is required
   - repositories.districompany-language-nl : Does not have a value in the enumeration [false]
   - repositories.districompany-language-nl.package : The property package is required
   - repositories.districompany-language-nl.type : Does not have a value in the enumeration ["package"]
   - repositories.districompany-language-nl.type : Does not have a value in the enumeration ["composer"]
   - repositories.districompany-language-nl.url : Invalid URL format
   - repositories.districompany-language-nl.type : Does not have a value in the enumeration ["path"]
   - repositories.districompany-language-nl.type : Does not have a value in the enumeration ["artifact"]
   - repositories.districompany-language-nl.type : Does not have a value in the enumeration ["pear"]
   - repositories.districompany-language-nl : Failed to match exactly one schema
`

On version Composer version 1.3-dev (5e8776ae1292b89b20baf03fa969079eeaab6500) 2017-01-02 12:00:18 I got these errors.

On version composer version 1.3.0 2016-12-24 00:47:03 no errors

**Closed** 2017-01-03 12:14 UTC
Labels: Bug

**Comment by sassman** [comment] 2018-12-13 14:59
this issue is still valid with Composer version 1.7.3 2018-11-01 10:05:06

**Comment by jfretin** [comment] 2019-02-20 12:39
Also still valid with composer version 1.8.4 2019-02-11 10:52:10 for me.

**Comment by Seldaek** [comment] 2019-02-20 12:42
Please report a new issue with actual details @jfretin. Commenting here is useless.

**Comment by jfretin** [comment] 2019-02-20 12:56
Ok, I got it working. I followed the doc at https://getcomposer.org/doc/05-repositories.md#package-2, but was missing just the 'reference' property in the package.source... (master for git).

Sorry for disturbing :sob:
