### ISSUE TITLE
Regression in package installation

### ISSUE THREAD

**Issue by Nikerabbit** [composer/composer#4526] opened 2015-10-22 12:46 UTC
```
$ sudo composer self-update
Updating to version f85d965732d9505b69242a070dc0b381c9f6bbab.
    Downloading: 100%         
Use composer self-update --rollback to return to version 15face5432d7b7334db6ac69fac0190971cafa6e

$ composer require mediawiki/cldr
Using version 2015.08 for mediawiki/cldr
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package mediawiki/cldr could not be found in any version, there may be a typo in the package name.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.

$ sudo composer self-update --rollback
Rolling back to version 2015-09-23_17-46-25-15face5.

$ composer require mediawiki/cldr
Using version 2015.08 for mediawiki/cldr
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing composer/installers (v1.0.21)
    Loading from cache

  - Installing mediawiki/cldr (2015.08)
    Loading from cache

Writing lock file
Generating autoload files
```

**Comment by alcohol** [comment] 2015-10-22 20:19
Duplicate of #4480

**Closed by alcohol** 2015-10-22 20:19 UTC
