### ISSUE TITLE
composer global vendor not exists and permission denied

### ISSUE THREAD

**Issue by patrickmaciel** [composer/composer#8143] opened 2019-05-15 17:22 UTC
I'm on Windows 10, build 1809.

I did not change the structure of composer directories.

**The error:** `C:\Users\patri\AppData\Roaming\Composer/vendor exists and is not a directory.`

**When I run this command:**

```
composer global require laravel/installer
```

**I get the following output:**
```
Package operations: 12 installs, 0 updates, 0 removals
Installs: symfony/process:v4.2.8, symfony/polyfill-ctype:v1.11.0, symfony/filesystem:v4.2.8, symfony/polyfill-mbstring:v1.11.0, symfony/contracts:v1.1.0, symfony/console:v4.2.8, guzzlehttp/promises:v1.3.1, ralouphie/getallheaders:2.0.5, psr/http-message:1.0.1, guzzlehttp/psr7:1.5.2, guzzlehttp/guzzle:6.3.3, laravel/installer:v2.1.0

Installation failed, deleting C:\Users\patri\AppData\Roaming\Composer\vendor.


  [RuntimeException]
  C:\Users\patri\AppData\Roaming\Composer/vendor exists and is not a directory.


Exception trace:
 () at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Util/Filesystem.php:181
 Composer\Util\Filesystem->ensureDirectoryExists() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/LibraryInstaller.php:229
 Composer\Installer\LibraryInstaller->initializeVendorDir() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/LibraryInstaller.php:93
 Composer\Installer\LibraryInstaller->install() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:173
 Composer\Installer\InstallationManager->install() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer/InstallationManager.php:160
 Composer\Installer\InstallationManager->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:595
 Composer\Installer->doInstall() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Installer.php:229
 Composer\Installer->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/RequireCommand.php:209
 Composer\Command\RequireCommand->doUpdate() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/RequireCommand.php:166
 Composer\Command\RequireCommand->execute() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:258
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/GlobalCommand.php:101
 Composer\Command\GlobalCommand->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:258
 Composer\Console\Application->doRun() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Console/Application.php:104
 Composer\Console\Application->run() at phar://C:/ProgramData/ComposerSetup/bin/composer.phar/bin/composer:61
 require() at C:\ProgramData\ComposerSetup\bin\composer.phar:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-progress] [--no-suggest] [--no-update] [--no-scripts] [--update-no-dev] [--update-with-dependencies] [--update-with-all-dependencies] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--] [<packages>]...
```

And I expected this to happen: **the package install**

**Comment by alcohol** [comment] 2019-05-16 07:03
I think the error message is rather clear as to what the problem is. Did you try resolving it yourself? Because pasting the error here does not mean we can magically fix the situation for you. We don't have access to your system. I am not sure what you expect from us honestly.

**Comment by patrickmaciel** [comment] 2019-05-17 14:32
@alcohol sir, are you ok? Because, I just post my error and as a developer I know things dont fix "magically". Can you please be gently? Its just an issue.

I tried everything and if the problem is clear for you, clear that for me, because I dont know how to solve otherwise I would not be here.

Other example... the problem persists:

```
PS C:\Users\patri\www\.......................i> composer update -vvv
Reading C:/Users/patri/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/patri/AppData/Roaming/Composer/composer.json
Checked CA file C:\Users\patri\AppData\Local\Temp\ope779B.tmp: valid
Executing command (C:/Users/patri/AppData/Roaming/Composer): git branch --no-color --no-abbrev -v
Executing command (C:/Users/patri/AppData/Roaming/Composer): git describe --exact-match --tags
Executing command (C:/Users/patri/AppData/Roaming/Composer): git log --pretty="%H" -n1 HEAD
Executing command (C:/Users/patri/AppData/Roaming/Composer): hg branch
Executing command (C:/Users/patri/AppData/Roaming/Composer): fossil branch list
Executing command (C:/Users/patri/AppData/Roaming/Composer): fossil tag list
Executing command (C:/Users/patri/AppData/Roaming/Composer): svn info --xml
Reading C:/Users/patri/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/patri/AppData/Roaming/Composer/composer.json
Reading C:/Users/patri/AppData/Roaming/Composer/vendor/composer/installed.json
Reading C:/Users/patri/AppData/Roaming/Composer/vendor/composer/installed.json
Running 1.8.5 (2019-04-09 17:46:47) with PHP 7.2.18 on Windows NT / 10.0
Reading C:/Users/patri/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/patri/AppData/Roaming/Composer/composer.json
Executing command (C:/Users/patri/AppData/Roaming/Composer): git branch --no-color --no-abbrev -v
Executing command (C:/Users/patri/AppData/Roaming/Composer): git describe --exact-match --tags
Executing command (C:/Users/patri/AppData/Roaming/Composer): git log --pretty="%H" -n1 HEAD
Executing command (C:/Users/patri/AppData/Roaming/Composer): hg branch
Executing command (C:/Users/patri/AppData/Roaming/Composer): fossil branch list
Executing command (C:/Users/patri/AppData/Roaming/Composer): fossil tag list
Executing command (C:/Users/patri/AppData/Roaming/Composer): svn info --xml
Reading C:/Users/patri/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/patri/AppData/Roaming/Composer/composer.json
Reading C:/Users/patri/AppData/Roaming/Composer/vendor/composer/installed.json
Reading C:/Users/patri/AppData/Roaming/Composer/vendor/composer/installed.json
Composer could not find the config file: C:\Users\patri\AppData\Roaming\Composer\vendor
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
PS C:\Users\patri\www\.............i>
```

**Comment by alcohol** [comment] 2019-05-19 19:41
For some reason it thinks that `C:\Users\patri\AppData\Roaming\Composer\vendor` is your `composer.json` file. Do you by any chance have an environment variable named `COMPOSER` that points to said directory?

**Closed** 2019-06-07 08:37 UTC
Labels: Support
