### ISSUE TITLE
Dependencies not retrieved in vendor/ without error

### ISSUE THREAD

**Issue by ArthurHoaro** [composer/composer#5592] opened 2016-08-12 08:16 UTC
With the following composer.json:

``` json
{
    "require": {
        "php": ">=5.3.4",
        "shaarli/netscape-bookmark-parser": "1.*"
    }
}
```

When I run this command:

``` sh
$ COMPOSER_CACHE_DIR=/home/shaarlidemo/cache php composer.phar install --no-dev -vvv

Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/home/shaarlidemo/s): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.2.0 (2016-07-19 01:28:52) with PHP 5.6.23-0+deb8u1 on Linux / 3.2.58-grsec
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.004 seconds
Analyzed 71 packages to resolve dependencies
Analyzed 72 rules to resolve dependencies
  - Installing shaarli/netscape-bookmark-parser (v1.0.1)
Downloading https://api.github.com/repos/shaarli/netscape-bookmark-parser/zipball/4e3adcd67c9d203e617cc9baa10bbee8d481ad59
    Downloading: 100%         
Writing /home/shaarlidemo/cache/files/shaarli/netscape-bookmark-parser/e7ec55e98f583822af90c78fba4810f1c4da4b06.zip into cache from /home/shaarlidemo/s/vendor/shaarli/netscape-bookmark-parser/e366ac0e8e46f5a58c7521c27ef618fe
    Extracting archive
Executing command (CWD): unzip '/home/shaarlidemo/s/vendor/shaarli/netscape-bookmark-parser/e366ac0e8e46f5a58c7521c27ef618fe' -d '/home/shaarlidemo/s/vendor/composer/2d123405' && chmod -R u+w '/home/shaarlidemo/s/vendor/composer/2d123405'

    REASON: Required by the root package: Install command rule (install shaarli/netscape-bookmark-parser v1.0.1)

Generating autoload files

$ ls -l vendor/
-rw-r--r-- 1 arthur group  183 Aug 12 07:57 autoload.php
drwxr-sr-x 1 arthur group 4096 Aug 12 07:57 composer

$ ls -l vendor/composer/
-rw-r--r-- 1 arthur group   147 Aug 12 07:57 autoload_classmap.php
-rw-r--r-- 1 arthur group   263 Aug 12 07:57 autoload_files.php
-rw-r--r-- 1 arthur group   149 Aug 12 07:57 autoload_namespaces.php
-rw-r--r-- 1 arthur group   143 Aug 12 07:57 autoload_psr4.php
-rw-r--r-- 1 arthur group  2333 Aug 12 07:57 autoload_real.php
-rw-r--r-- 1 arthur group   488 Aug 12 07:57 autoload_static.php
-rw-r--r-- 1 arthur group 12466 Aug 12 07:57 ClassLoader.php
-rw-r--r-- 1 arthur group  1793 Aug 12 07:57 installed.json
-rw-r--r-- 1 arthur group  1075 Aug 12 07:57 LICENSE


$ ls -lh /home/shaarlidemo/cache/files/shaarli/netscape-bookmark-parser/e7ec55e98f583822af90c78fba4810f1c4da4b06.zip
-rw-r--r-- 1 arthur group 5.1K Aug 12 07:57 /home/shaarlidemo/cache/files/shaarli/netscape-bookmark-parser/e7ec55e98f583822af90c78fba4810f1c4da4b06.zip

```

There isn't any error, the ZIP archive has been downloaded in the cache folder, however, for some reason, it doesn't get extracted in the `vendor/` directory. I tried to unzip it manually from the cache folder, I had no issue.

I also tried without `--no-dev` (PHPUnit, etc.), same issue.

This only happens on a specific shared host environment. The default cache folder is /home/.composer, but the FS doesn't have any space.

Composer version 1.2.0 and PHP 5.6.

EDIT: I can workaround this issue using `--prefer-source`, but this method retrieve a bunch of unwanted files.

**Comment by alcohol** [comment] 2016-08-12 08:30
Unwanted files? Those few bytes won't change a thing.

Cannot reproduce your issue though.

**Comment by Seldaek** [comment] 2016-09-02 16:57
You said the default cache dir has no free space. But the one you run with COMPOSER_CACHE_DIR also fails despite having free space in there? So it's not about cache dir free space I assume? 

Did you try to unzip the archive using the `unzip` on your shared host? That might be broken somehow.

Anyway we need more details to have any chance of helping.

**Comment by ArthurHoaro** [comment] 2016-09-03 09:49
> So it's not about cache dir free space I assume? 

No it's not, you can see that the archive is downloaded in the cache folder properly. Unzipping it also works:

```bash
$ unzip e7ec55e98f583822af90c78fba4810f1c4da4b06.zip 
Archive:  e7ec55e98f583822af90c78fba4810f1c4da4b06.zip
4e3adcd67c9d203e617cc9baa10bbee8d481ad59
   creating: shaarli-netscape-bookmark-parser-4e3adcd/
  inflating: shaarli-netscape-bookmark-parser-4e3adcd/LICENSE  
  inflating: shaarli-netscape-bookmark-parser-4e3adcd/NetscapeBookmarkParser.php  
  inflating: shaarli-netscape-bookmark-parser-4e3adcd/README.md  
```

I don't think it could be an issue, but the real path is a bit odd:
```
/home/shaarlidemo/shaarlidemo.host.tld-web/tmp/cache/files/shaarli/netscape-bookmark-parser
```

I understand that you can't help without reproducing, however, I don't know what details I can add.

**Comment by Seldaek** [comment] 2017-06-18 16:10
Closing issue as it has been quiet for a long time and there is no clear next step we can take.

**Closed by Seldaek** 2017-06-18 16:10 UTC
Labels: Support
