### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array in Autoload/AutoloadGenerator.php:1202

### ISSUE THREAD

**Issue by joshirohit100** [composer/composer#11234] opened 2022-12-21 11:34 UTC
After upgrading to composer 2.5.0, we are seeing issues in build. It is working fine with 2.4 version.

Error, we are getting -
```
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, Closure given in /vendor/composer/composer/src/Composer/Autoload/AutoloadGenerator.php:1202
```

code of that line of AutoLoadGenerator.php is -
```
foreach ($maps as $prop => $value) {
            if (count($value) > 32767) {
                // Static arrays are limited to 32767 values on PHP 5.6
                // See https://bugs.php.net/68057
                $staticPhpVersion = 70000;
            }
```
and failing for `if (count($value) > 32767) {` 

Tried with - cache clear, vendor delete as well

**Comment by joshirohit100** [comment] 2022-12-21 12:00
So we have a script in `scripts` section of composer where we are running a script. In that script we are just `cd` into a different directory/app and doing `composer install` there (as that is a separate app) and its failing.

If I comment that script or `composer install` in script all works fine.

This is working fine with 2.4.4

**Comment by graste** [comment] 2022-12-21 12:39
Is your app's `composer.lock` file matching the requirements from the `composer.json` file at that time? See #11195 and #11232

**Comment by joshirohit100** [comment] 2022-12-21 13:33
Yes! Its upto date. If I don;t use "script" tag for custom script and run manually `composer install` in both apps, it works fine. But if using script to run composer install in other app, it fails

**Comment by Seldaek** [comment] 2022-12-21 13:38
@joshirohit100 it seems you have composer/composer installed in your vendor dir, which I assume is the reason things break here.

Can you try to update your composer in vendors to 2.5 as well, or try to use `@composer install`  in scripts (with the `@`)?

**Comment by nikunjkotecha** [comment] 2022-12-22 05:31
does this mean composer 2.5 isn't backwards compatible?

**Comment by Seldaek** [comment] 2022-12-22 08:47
Well it depends what is going on here, but if you are running Composer with some files included from 2.4.4 and some files included from 2.5.0 then sure it may not be compatible with itself in another version.. that sometimes happen when composer is itself installed in the vendor dir and the vendor/autoload.php is included by some script within the composer process. That's why we discourage requiring composer/composer but many still do unfortunately for various more or less valid reasons.

**Comment by joshirohit100** [comment] 2022-12-22 10:06
[app1.zip](https://github.com/composer/composer/files/10285906/app1.zip)

So I tried a vanilla test

So if we use ^^ zip and then add composer package to app1 for the version 2.5, all works.

But when we use the composer package 2.2.17 in app1 and run install, we get the error

`composer require composer/composer` -> this is for 2.5 version
`composer require composer/composer:"2.2.17"` -> this for the old version which we have fails

Only thing we not sure what change breaking this for 2.5.0 while working for 2.4.4

**Comment by nikunjkotecha** [comment] 2022-12-22 10:24
This looks like duplicate of https://github.com/sebastianbergmann/phpunit/issues/5117 (it is in different repository though so we shouldn't mark this as duplicate but both are talking about same issue) and caused by the change in PR #11015

In release notes it has BC warning https://github.com/composer/composer/releases/tag/2.5.0
> BC Warning: To prevent abuse of our includeFile() function it is now gone, it was not part of the official API but may still cause issues if some code incorrectly relied on it (https://github.com/composer/composer/pull/11015)

**Comment by Seldaek** [comment] 2022-12-22 11:50
It is not a duplicate, tho it is triggered by that change. It seems you have composer/composer 2.2 indeed which causes issues. That should be fixed by https://github.com/composer/composer/commit/a30299b103dff4d311a14e4409569659e55a3103 (you can try to require `composer/composer:2.2.x-dev`), but ideally you should keep the composer in vendor in sync with your composer binary.

**Closed by Seldaek** 2022-12-22 11:50 UTC
Labels: Support

**Comment by brandonkelly** [comment] 2023-02-05 18:43
@Seldaek Looks like the fix for this didn’t make it into Composer 2.2.19, even though a30299b103dff4d311a14e4409569659e55a3103 is on the `2.2` branch. Was it overlooked somehow or is there a reason for that?

**Comment by Seldaek** [comment] 2023-02-05 21:12
@brandonkelly it is in 2.2.19 as far as I can tell. Not sure why github does not show the commit as being in the tag, but gitk shows it in for me.

**Comment by Seldaek** [comment] 2023-02-05 21:13
https://github.com/composer/composer/commits/2.2.19 shows it as well

**Comment by brandonkelly** [comment] 2023-02-07 20:17
Oh weird, thanks!
