### ISSUE TITLE
Content-Length mismatch (again)

### ISSUE THREAD

**Issue by J3Rik0** [composer/composer#7782] opened 2018-11-13 13:48 UTC
My `composer.json`:

```json
{} // nothing, fresh install
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.3
PHP version: 7.2.10
PHP binary path: /usr/bin/php7.2

```

When I run this command:

```
composer global require cpriego/valet-linux
```

I get the following output:

```
 [Composer\Downloader\TransportException]                                    
  Content-Length mismatch, received 111539 bytes out of the expected 1617048 
```

And I expected this to happen:
Install valet linux

**Fix**: #6449
> Finally I fixed it by using a chinese mirror.
> mv composer.phar /usr/local/bin/composer
> composer config -g repo.packagist composer https://packagist.phpcomposer.com

From what I could dig out it appears that there is a problem with the EU mirrors (Eastern Europe to be exact) and #6449 fixed my issue.

I've seen in #6342 that a similar issue was fixed by tweaking the US mirrors, I'm suspecting as I've already mentioned that this is the same problem but for EU.

To note that this was tested with the same symptoms in Fedora 29 and Mint 19

**Comment by scuben** [comment] 2018-11-13 14:48
I can confirm this problem on a fresh composer installation.

**Comment by ViktorPontinen** [comment] 2018-11-13 15:15
Another confirm. Can also confirm that changing mirrors resolved the issue for now.

**Comment by Seldaek** [comment] 2018-11-13 20:31
Seems like network routing issues affecting some people only, the servers are still serving a ton of traffic and everything looks rather normal from our end :/

**Comment by WalterMeier** [comment] 2018-11-14 07:32
Same problem here. The entire php team at our corporation can't work properly now, because our docker CI/CD scripts use `composer install` a lot and are all broken now.

Really hoping for a fix soon.

**Comment by Seldaek** [comment] 2018-11-14 08:53
### If you are affected by this, try running:

`composer config repositories.packagist.org composer https://repo-eu-uk-1.packagist.org`

This should force to use the UK mirror which is hopefully unaffected by those network issues.

Accessing the mirror URL directly is kind of a hack though and **not guaranteed to work in the future**, so I would advise you to remove it in the coming days once this network glitch hopefully passes.. You can do so using:

`config repositories.packagist.org --unset`

**Comment by RomanoschoonheimNL** [comment] 2018-11-14 09:19
Not sure if it is related, since yesterday is the performance of composer awful.  When i run composer update it takes around 15 minutes to pass "Loading composer repositories with package information", normally it will take around 2 minutes to finish a update.

**Comment by peterjaap** [comment] 2018-11-14 09:36
Confirmed, workaround seems to 'fix' it. Were having issues since yesterday.

**Comment by RomanoschoonheimNL** [comment] 2018-11-14 09:38
> Confirmed, workaround seems to 'fix' it. Were having issues since yesterday.

Also working in The Netherlands?

**Comment by RomanoschoonheimNL** [comment] 2018-11-14 09:38
> Confirmed, workaround seems to 'fix' it. Were having issues since yesterday.

@peterjaap also working from The Netherlands?

**Comment by peterjaap** [comment] 2018-11-14 09:41
> > Confirmed, workaround seems to 'fix' it. Were having issues since yesterday.
> 
> @peterjaap also working from The Netherlands?

Yes

**Comment by tanthammar** [comment] 2018-11-14 09:54
@Seldaek solution worked for me.
@peterjaap @RomanoschoonheimNL I'm working from Stockholm

**Comment by JeroenBoersma** [comment] 2018-11-14 10:21
Packagist.com is also affected for mirrored packages to packagist.org

**Comment by twmbx** [comment] 2018-11-14 11:21
Wow, I've actually thought this was a problem with my own setup for days because there were no issues being reported.
To provide more possible information; I first started experiencing issues at the weekend. Working from Zambia.

**Comment by RomanoschoonheimNL** [comment] 2018-11-14 12:32
@Seldaek are there any updates on this? I'm still unable to pull dependencies. The fix you suggested does not work for me at this moment.

**Comment by marcel-burkhard** [comment] 2018-11-14 12:33
Confirm the same issue from Switzerland. It wasn't working yesterday either, the workaround with the UK *does* work for me.

**Comment by Seldaek** [comment] 2018-11-14 12:50
@RomanoschoonheimNL do you have more details? Does it fail with a timeout/content length issue like the others or is it another issue? You can also try `repo-ca-bhs-1.packagist.org` as an alternative to the UK node, see if it helps.

**Comment by jakguru** [comment] 2018-11-14 13:18
Confirmed both the issue and the fix using the UK mirror from the middle East.

**Comment by RomanoschoonheimNL** [comment] 2018-11-14 13:29
@Seldaek sorry for not providing more details. When I use the UK mirror I encounter the same symptoms as when I use the default mirror. The symptoms I encounter so far: high packet loss (28,8%). Awful performance, downloading/resolving dependencies takes forever. 


**ping https://repo.packagist.org results:**
`
--- repo.packagist.org ping statistics ---`
`170 packets transmitted, 121 packets received, 28.8% packet loss`
`round-trip min/avg/max/stddev = 33.466/35.058/48.342/1.836 ms
`

**trace route results**
```
Romanos-iMac:test4 romanoschoonheim$ traceroute repo.packagist.org
 1  10.6.5.1 (10.6.5.1)  3.337 ms  0.767 ms  0.701 ms
 2  172.16.28.1 (172.16.28.1)  0.383 ms  0.322 ms  0.542 ms
 3  185.159.125.89 (185.159.125.89)  10.882 ms  1.196 ms  1.087 ms
 4  185.134.216.29 (185.134.216.29)  13.662 ms  13.931 ms  17.956 ms
 5  core3.nkh.comsave.com (185.52.208.162)  1.646 ms  1.757 ms  1.748 ms
 6  * * *
 7  be100-1166.var-5-a9.pl.eu (91.121.215.191)  34.718 ms  34.338 ms *
 8  vl1068.waw-d2-a75.pl.eu (213.186.32.203)  35.258 ms  34.898 ms  34.570 ms
 9  * * *
 10  * * *
 11  * * *
 12  * * *
 13  * * *
 14  ip-54-38-136.eu (54.38.136.239)  34.443 ms *  34.542 ms
```

**Composer require <package>**
```
Romanos-iMac:test4 romanoschoonheim$ composer require nikic/fast-route -vvv
Failed to initialize global composer: Composer could not find the config file: /Users/romanoschoonheim/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 1.7.2 (2018-08-16 16:57:12) with PHP 7.1.16 on Darwin / 17.7.0
Failed to initialize global composer: Composer could not find the config file: /Users/romanoschoonheim/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /private/etc/ssl/cert.pem: valid
Executing command (/Users/romanoschoonheim/tmp/test4): git branch --no-color --no-abbrev -v
Executing command (/Users/romanoschoonheim/tmp/test4): git describe --exact-match --tags
Executing command (/Users/romanoschoonheim/tmp/test4): git log --pretty="%H" -n1 HEAD
Executing command (/Users/romanoschoonheim/tmp/test4): hg branch
Executing command (/Users/romanoschoonheim/tmp/test4): fossil branch list
Executing command (/Users/romanoschoonheim/tmp/test4): fossil tag list
Executing command (/Users/romanoschoonheim/tmp/test4): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /Users/romanoschoonheim/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Downloading https://repo.packagist.org/packages.json
Writing /Users/romanoschoonheim/.composer/cache/repo/https---repo.packagist.org/packages.json into cache
Reading /Users/romanoschoonheim/.composer/cache/repo/https---repo.packagist.org/p-provider-2013.json from cache
Reading /Users/romanoschoonheim/.composer/cache/repo/https---repo.packagist.org/p-provider-2014.json from cache
Downloading http://repo.packagist.org/p/provider-2015%24869586ae3f412fc2085709f5d060d6e3296fb91c66346210b8812807060ca4ba.json
```

Am I the only person still having issues, if not what is going on?

**Comment by Seldaek** [comment] 2018-11-14 13:31
In this output log it doesn't seem like you are using the UK mirror.

**Comment by RomanoschoonheimNL** [comment] 2018-11-14 13:32
> In this output log it doesn't seem like you are using the UK mirror.

@Seldaek I will provide more logs, give me a sec!

**Comment by golbanstefan** [comment] 2018-11-14 13:52
I have the same problem in Moldova, we have executed:
```
composer config repositories.packagist.org composer https://repo-eu-uk-1.packagist.org

```

composer update takes 1 hour minim

**Comment by zolhorvath** [comment] 2018-11-14 14:01
Workaround at https://github.com/composer/composer/issues/7782#issuecomment-438585301 works from Hungary

**Comment by loevgaard** [comment] 2018-11-14 14:05
@Seldaek's hack didn't work for me. It still took ages, so I changed to a third party mirror: 
`composer config -g repos.packagist composer https://packagist.co.za` which works great. Just to let people know :)

**Comment by mihaikelemen** [comment] 2018-11-14 14:16
same problem here

**Comment by golbanstefan** [comment] 2018-11-14 14:17
Problem persist :
config: 
```
 "repositories": {
        "0": {
            "type": "composer",
            "url": "https://repo-eu-uk-1.packagist.org"
        }
    }
```
Errorr:
```
                                                                             
  [Composer\Downloader\TransportException]                                   
  Content-Length mismatch, received 59849 bytes out of the expected 2264921  
                                                                             

Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:337
 Composer\Util\RemoteFilesystem->get() at phar:///usr/local/bin/composer/src/Composer/Util/RemoteFilesystem.php:101
 Composer\Util\RemoteFilesystem->getContents() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:682
 Composer\Repository\ComposerRepository->fetchFile() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:594
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///usr/local/bin/composer/src/Composer/Repository/ComposerRepository.php:314
 Composer\Repository\ComposerRepository->whatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:204
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///usr/local/bin/composer/src/Composer/DependencyResolver/Pool.php:193
 Composer\DependencyResolver\Pool->whatProvides() at phar:///usr/local/bin/composer/src/Composer/Installer.php:1013
 Composer\Installer->processDevPackages() at phar:///usr/local/bin/composer/src/Composer/Installer.php:468
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:228
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:162
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:241
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:843
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:193
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:254
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:103
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:56
 require() at /usr/local/bin/composer:24

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--no-suggest] [--with-dependencies] [--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...

```

**Comment by mihaikelemen** [comment] 2018-11-14 14:33
changing the mirror as @loevgaard proposed, fixed my issue.

**Comment by B4rb4ross4** [comment] 2018-11-14 17:15
We were in the fortunate Position that we have multiple internet connections from different ISPs. We fixed the problem by routing the composer traffic through SDSL=>Telefonica/German Telekom instead of fibre=>Versatel. Just in case thats an option for you.

**Comment by stof** [comment] 2018-11-14 17:32
@golbanstefan in your case, you are not replacing packagist with the UK mirror. you are adding the UK mirror as a second repository (the key is `0` in your config, not `packagist.org`). So you are trying to access both the UK mirror and the normal domain (which might be the one failing for you)

**Comment by B4rb4ross4** [comment] 2018-11-14 17:54
Just as a different source of inspiration:
Our company has multiple internet connections from different ISPs and routing the composer traffic through Telefonica / German Telekom instead of Versatel seems to fix the Problem for us.

**Comment by RomanoschoonheimNL** [comment] 2018-11-14 18:30
**Addition:**  just arrived home from work, tried to reproduce this issue but everything works from here. @Seldaek if you need more logs, I can generate them for you.

**Comment by webkim** [comment] 2018-11-14 19:07
Same here. It was driving me insane. Resolved by using uk mirros.

**Comment by Jeordy** [comment] 2018-11-14 19:32
Same problem here. UK mirror workaround works.

**Comment by rask** [comment] 2018-11-14 21:42
UK mirror works here as well. Hang/freeze on all `composer` commands that tried to access something from Packagist otherwise.

**Comment by J3Rik0** [comment] 2018-11-14 22:58
Yeah, apparently Eastern Europe still has some issues, I can confirm the default repo works on a fresh install, but it's slow as hell, I mean about 25 minutes to install `laravel/installer` and it's still going.

**Comment by fuzzy76** [comment] 2018-11-15 07:17
Is there really no centralised way to remove broken mirrors to fix this for everyone?

**Comment by Seldaek** [comment] 2018-11-15 10:52
Yes, I now disabled the Warsaw nodes as it seems the problem isn't going away. I'd recommend removing/disabling the workaround if you added it.

**Comment by moux2003** [comment] 2018-11-15 11:10
Don't know if there's a link but I have an error and here is my `composer diagnose` output:
```bash
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: WARNING
[Composer\Downloader\TransportException] The "https://repo.packagist.org/packages.json" file could not be downloaded: Peer certificate CN=`packagist.org' did not match expected CN=`repo.packagist.org'
Failed to enable crypto
failed to open stream: operation failed
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.7.3
PHP version: 7.2.4
```

**Comment by tanthammar** [comment] 2018-11-15 11:56
Still problems from Sweden.
Did: --unset repositories and repos

Unable to install Laravel/Cashier:
The requested package laravel/cashier could not be found in any version, there may be a typo in the package name.

Unable to do composer update:
[Composer\Downloader\TransportException]                                                              
  The "https://repo.packagist.com/packages.json" file could not be downloaded (HTTP/1.1 404 Not Found)

Still have to use: composer config -g repos.packagist.org composer https://repo-eu-uk-1.packagist.org
to make it work.

**Comment by Seldaek** [comment] 2018-11-15 12:14
Sorry I had to rollback the change due to the SSL issue @moux2003 mentioned. I have added new nodes now so I can disable the Warsaw ones without causing problems.

Please try again hitting the regular repo.packagist.org

**Comment by Seldaek** [comment] 2018-11-15 13:11
I'd appreciate if anyone can report back whether things work again (you can just 👍 this post to avoid spamming all in the thread).

As a reminder, `config repositories.packagist.org --unset` should undo the workaround and get you back using the default URL, which I would highly recommend to avoid issues in the future.

**Comment by Seldaek** [comment] 2018-11-16 10:49
OK gonna close this then :)

**Closed by Seldaek** 2018-11-16 10:49 UTC
Labels: Support

**Comment by felix2056** [comment] 2019-04-12 04:23
My project is still fresh so I don't yet have a config.json file. Only the directories and composer.json file was installed. I was able to fix it using laravel new [projectname]  instead of composer create-project --prefer-dist laravel/laravel [projectname]

**Comment by mateusfccp** [comment] 2019-05-14 18:22
I am also having this issue.

**Comment by Mr-Sakr** [comment] 2019-05-21 00:42
On Command, Just change the default repo url to:
composer config -g repo.packagist composer https://packagist.phpcomposer.com

Then It will be solved
