### ISSUE TITLE
Resolve dependencies without applying them makes deployment faster

### ISSUE THREAD

**Issue by sourcerer-mike** [composer/composer#6264] opened 2017-03-15 08:56 UTC
Please add some command that gathers information about dependencies.
Here is the scenario (TL;DR: deployment):

- Start of new release on server
- Maintenance mode for some reason
- `composer update --no-dev`
- Other migrations and stuff
- Maintenance mode off.

It is true that composer.lock could have saved time here but this is no longer true.
Depending on the server a bunch of different package versions need to be installed
as big composer.json files become very fragile from server to server.
Each server wants slighly different versions, don't ask why - I guess due to modules , PHP versions, etc.

So a command that does the following would be great:

- Almost like `composer update`
- But without applying changes to the vendor-dir.
- Just write everything in composer.lock

Afterwards you can deploy "faster" because resolving dependencies is already done. A `composer install` applying the new dependencies is surely faster and you can disable maintenance mode within seconds instead of minutes.

**Comment by alcohol** [comment] 2017-03-15 11:04
I do not understand your use-case unfortunately. But it sounds to me like you want something equivalent to `--dry-run` but with the side effect of still updating the `composer.lock` file. Though I am not sure why...

**Comment by avant1** [comment] 2017-03-15 11:31
You should move towards unifying your servers environment (use same set of available PHP extensions and PHP version) by automation of deployment using tools like `ansible`/`chef` or using `docker`.
And the difference between dev and prod env ideally should be as minimal as possible.
When your dev and prod envs are identical you can use the same `.lock` file during development and on production. 

BTW resolving dependencies during deploy is not a good idea. You may run different versions of packages on different servers, which may lead to strange and hard-to-reproduce bugs on prod.

And if new versions of dependencies will be released then you may deploy to production code that you have never executed. For me that soulds like a horrible idea.

**Comment by sourcerer-mike** [comment] 2017-03-15 14:59
Well yes. This is how professionals do their job. 
But the world is odd ;) And yee @alcohol you got the idea.

How do you want to unify? In a good team is as simple as saying: Use linux, use docker, use PHP7.1, use postgre, use phpStorm. Almost complete list.

And then reality hits you hard.
The project manager says: Deploy now, unify later.
Some dev say: What is docker? What is linux? I can't get away from 5.6 - because I am constantly under pressure. And I only build using PHing or gulp.
The boss says: What? I need to buy everyone the same system? You want to clean things up? Err... No! All budget went on marketing and I brought some new projects with deadline yesterday.

Thank god I live in the perfect unified world and you composer developer do too - I guess from your replies.
Feel free to decide if you want to support different workflows and give them a hand.
If the composer policy is less about popularity but serving the professional workflows then close the issue ;-) Both ways have advantages.

IMHO this issue supports both. Call it prefetching or so. Sometimes useful.

**Comment by avant1** [comment] 2017-03-15 17:33
@sourcerer-mike I feel your pain, and I understand your use case.

You've mentioned a "good team".
Good teams do not pop out of nowhere. They are being created from individual "good" developers, or "not very good team" can evolve to a "good team". It takes time and requires developers motivation and interest from bosses side, but it is possible.

Large part of developers is motivated in professional growth, so usually this is not a problem.
Managers motivation is usually simple: time and money.
Long maintenance downtimes are bad for business, right? Nobody likes waiting, otherwise this issue would not be created.
Mistakes made during manual deploys can be very, very expensive.
Setting up environment for new team member can take hours (imagine if your team is growing rapidly).
Adding new server can take days.

**Automation is your friend**, and your manager can understand that if someone explains it in a proper way.

You don't need to buy the same hardware for everyone, you don't need to use the same OS in your team. You can use whatever your team likes. Nowadays you can spin up virtual machine locally in any OS in minutes (`vagrant` works on Windows/Linux/OSX).
PHP 5.6 is fine if you cannot migrate now, but it should be 5.6 everywhere.
`phing` is good place to start. You don't have to use `docker` or automate server configuration using `ansible` or `chef`. You can start by writing shell script that will install PHP 5.6 with all required extensions. It will take an hour. And it will allow you to use one `composer.lock` everywhere.

One more thing that is required for building a "good team" is a leader. But this is a whole new story.

Anyway it is up to `composer` team to decide if the feature you've requested fits to the `composer` "philosophy".
I'm just a guy who lives in a real world but still thinks that everything is possible if someone has willing to improve current situation. Maybe I'm just too optimistic.
Sorry for this comment that is not related directly to `composer` :smile:

**Comment by curry684** [comment] 2017-03-16 00:28
> The project manager says: Deploy now, unify later.

If the project manager does not care about quality, stability, predictability and maintainability he should not be a project manager.

You can hardly blame Composer for not supporting fundamentally corrupted workflows. As pointed out the lock mechanism works the way it does for dozens of very good reasons rooted in proper software engineering practices.

Don't blame a car for not turning right when you steer left. Fix the process that expects it to.

**Comment by Seldaek** [comment] 2017-03-17 21:21
Just to add 2cents to what has been said here, because I won't repeat it all, one way to get around different environments is to define your production environment in the [config.platform](https://getcomposer.org/doc/06-config.md#platform). That would at least normalize the package resolution across dev/staging/prod machines, although you really should only do composer updates on dev machines IMO, and then have build/staging/prod only install from lock files.

**Closed by Seldaek** 2017-03-17 21:21 UTC
Labels: Question

**Comment by sourcerer-mike** [comment] 2017-03-26 10:27
That wasn't the case. Anyway I am good with closing this as the issue reflects only problems of other people than me.
It was about: "Do something like `git fetch` for composer, only updating composer.lock but not applying."
I have VMs everywhere and maybe no use of this feature. This is where my concern for common people problems stops too. Thanks for discussing this a bit! :)
