### ISSUE TITLE
Composer 2 resolves different dependencies from composer 1 (psr/http-factory)

### ISSUE THREAD

**Issue by jdrieghe** [composer/composer#9316] opened 2020-10-22 07:16 UTC
My `composer.json`:

```json
{
    "name": "composer/test",
    "require": {
        "php": "^7.4 || ^8.0",
        "league/container": "^3.3",
        "league/flysystem": "^1.0",
        "league/flysystem-aws-s3-v3": "^1.0",
        "league/fractal": "^0.19.2",
        "nyholm/psr7": "^1.3",
        "php-http/curl-client": "^2.1",
        "psr/http-factory": "^1.0",
        "ramsey/uuid": "^4.0",
        "respect/validation": "^2.0",
        "sentry/sentry": "^3.0",
        "slim/http": "^1.0.0",
        "slim/psr7": "^1.0.0",
        "slim/slim": "^4.3",
        "vlucas/phpdotenv": "^5.0",
        "zumba/amplitude-php": "^1.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },
    "config": {
        "preferred-install": "dist",
        "sort-packages": true
    },
    "minimum-stability": "dev",
    "prefer-stable": true
}
```

Output of `composer diagnose`:

Composer 1
```
hecking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.15
PHP version: 7.4.10
PHP binary path: /usr/local/Cellar/php/7.4.10/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

Composer 2
```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.0-RC2
PHP version: 7.4.10
PHP binary path: /usr/local/Cellar/php/7.4.10/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.72.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
Installing dependencies from lock file (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing psr/http-factory (1.0.1)
```

And I expected this to happen:

Composer 1 correctly includes `psr/http-factory` in the set of packages to install. However, when I install with Composer 2, it never installs the dependency. When I install it first with Composer 1 and remove the lock file, Composer 2 gives the above output that it will remove the required dependency.

I expect Composer 1 and Composer 2 to install the same set of packages given the same `composer.json` file.

Note that it can possibly be reproduced with a smaller set of dependencies, but it works as expected when I *only* require `prs/http-factory`. There might be something strange going on in the dependency resolution with one of the specific combinations above.

**Comment by Seldaek** [comment] 2020-10-22 08:21
Duplicate of https://github.com/composer/composer/issues/9308 - not a bug. This is fixed by https://github.com/php-http/socket-client/pull/50

**Closed by Seldaek** 2020-10-22 08:21 UTC

**Comment by stof** [comment] 2020-10-22 10:44
@Seldaek that's not the same package and not the same provided package, but the issue is similar.
Could you do a search in the Packagist DB to find packages which have a `provides` and a `require` for the same package ?

**Comment by Seldaek** [comment] 2020-10-22 10:57
Ah sorry, so many of those psr and http something packages it's unreadable. I'll try and query a list of offenders yes.

**Comment by stof** [comment] 2020-10-22 11:08
https://packagist.org/?query=psr%2F shows a bunch of virtual packages for the names of actual PSR interface packages, alongside the corresponding `*-implementation` packages. So I think we have more offenders than the ones I fixed for `psr/http-client` and now `psr/http-factory` (and we might have offenders for other packages than the PSR interfaces too)

**Comment by Seldaek** [comment] 2020-10-22 13:16
https://gist.github.com/Seldaek/73dfe36bf518eee834cae9bb1810c267 if you feel like doing a bunch of PR.. Those packages without dev version on top listed most likely already fixed it in the meantime btw.
