### ISSUE TITLE
Fake requirements conflict when composer.json and composer.lock are out of sync

### ISSUE THREAD

**Issue by tgr** [composer/composer#4310] opened 2015-07-28 20:08 UTC
When `composer.json` and `composer.lock` do not match (user changed the config file but did not run `composer update`), running `composer require` will produce weird errors:

## Steps to reproduce:
1. create composer.json with
    ```
            {
                "name": "test/test",
                "require": {
                    "liuggio/statsd-php-client": "1.0.12"
                }
            }
    ```
2. run `composer update`
3. change version number to `1.0.13`
4. run `composer require monolog/monolog ~1.11`

## Expected results:
Either composer would update the lockfile and vendor dir to match the config file and in the process install Monolog, or throw a clear error message about refusing to change the config file while the lockfile is out of date.

## Actual results
```
$ composer require 'monolog/monolog' '~1.11'
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package liuggio/statsd-php-client == 1.0.12.0 could not be found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, reverting ./composer.json to its original content.
```

**Comment by alcohol** [comment] 2015-07-28 20:14
Not a big issue, but easy to solve I guess. Just reject command line modifications while the lock file is dirty.

**Comment by Seldaek** [comment] 2015-08-09 23:45
Implementing the warning when the lock file is out of date is pretty easy yes but I don't think it's a good idea to fail hard. There might be legit use cases and in general it usually works. It's only a problem if you made a change that creates invalid requirements.

The root cause by the way I guess is that it applies the lock file requirements (1.0.11) + the composer.json ones (1.0.12) and in this case they don't overlap so nothing is found. Updating silently to it would kind of break the contract that require makes a partial update of only the package you added though so I'd rather have a warning.

**Comment by beni0888** [comment] 2016-01-28 07:50
So what do you think should be solution to this issue?

**Comment by Seldaek** [comment] 2016-01-28 10:57
Ideally we would look at the composer requirements vs the versions in the lock file for non-whitelisted packages, and then if the requirement from composer.json isn't satisfied by the lock file version we warn the user that the requirement for package X seems to have changed and it should be included in the partial update whitelist. I don't really think that's an easy pick anymore though :) Not extremely hard but it touches many concepts.

**Comment by beni0888** [comment] 2016-01-28 12:06
:+1:

**Comment by Seldaek** [comment] 2016-04-18 21:13
I think we can consider this fixed by the recent error reporting enhancements as it now tells you what's wrong much more clearly:

![image](https://cloud.githubusercontent.com/assets/183678/14620090/cf7ede24-05b2-11e6-93e7-9dbe0a446d48.png)

**Comment by Seldaek** [comment] 2016-04-18 21:26
Yeah  nevermind it's not much more clear actually.. I got a repro case now, will try to fix it :)

**Comment by Seldaek** [comment] 2016-04-18 22:03
OK better for real now :)

![image](https://cloud.githubusercontent.com/assets/183678/14621319/bfd3438c-05b9-11e6-9918-a065b6f1ae41.png)

**Closed** 2016-04-18 22:03 UTC
Labels: Feature
