### ISSUE TITLE
Failed to decode response: zlib_decode(): data error

### ISSUE THREAD

**Issue by kitingChris** [composer/composer#4892] opened 2016-02-08 11:37 UTC
Don't know why but I have an issue here on updating/installing etc... 

I know there is a very long discussion on the topic #4121 and an article over [here](https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode) but none of these recommendations helped. 

The actual very weird thing is: On friday everything worked still fine.

Getting the same issue on different machines (linux/windows) and on our ci-server

local:
```
$ php composer.phar update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
zlib_decode(): data error
http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```

Jenkins:
```
vendors:
     [exec] Loading composer repositories with package information
     [exec] Updating dependencies (including require-dev)
     [exec] Failed to decode response: zlib_decode(): data error
     [exec] Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
     [exec] zlib_decode(): data error
     [exec] http://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
     [exec] Nothing to install or update
     [exec] Writing lock file
     [exec] Generating autoload files
```

I don't have any idea whats wrong :( 

EDIT:
```
$ php composer.phar diagnose
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```
Why is diagnose not testing for the zlib_decode functionality?

**Comment by curry684** [comment] 2016-02-08 21:54
These logs aren't really helpful without knowing what is causing the highly vague 'data error'. Could you execute the commands with `-vvv` flag and see if there's a hint to that in there?

**Comment by cs278** [comment] 2016-02-08 23:15
Could be the same as #4121 which seemed to be caused by ESET mangling HTTP requests.

**Comment by dirklang** [comment] 2016-02-09 07:36
Same Problem here, last Friday everything worked fine, since Monday
Loading composer repositories with package information
Updating dependencies (including require-dev)
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info

  [ErrorException]
  zlib_decode(): data error

No ESET installed. Updated Composer to latest Version, Diag runs without problems. Trying to Update Synfony 2.8 gives me following output:
F:\Documents\Projects\Web\ConReg>..\xampp\php\php.exe ..\composer.phar update -vvv
Reading ./composer.json
Loading config file ./composer.json
Checking CA file C:\Users\dilang\AppData\Local\Temp\composer-cacert-39eaf16e26c08cc90d728865f1c60406ee5d864d5963f72ede2a1cbb127f95ca.pem
Executing command (F:\Documents\Projects\Web\ConReg): git describe --exact-match --tags
Executing command (F:\Documents\Projects\Web\ConReg): git branch --no-color --no-abbrev -v
Executing command (F:\Documents\Projects\Web\ConReg): hg branch
Executing command (F:\Documents\Projects\Web\ConReg): svn info --xml
Failed to initialize global composer: Composer could not find the config file: C:/Users/dilang/AppData/Roaming/Composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading F:\Documents\Projects\Web\ConReg/vendor/composer/installed.json
Loading composer repositories with package information
Downloading https://packagist.org/packages.json
Writing C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
Reading C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/p-provider-2013.json from cache
Reading C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/p-provider-2014.json from cache
Reading C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/p-provider-2015.json from cache
Reading C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/p-provider-2015-04.json from cache
Reading C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/p-provider-2015-07.json from cache
Downloading http://packagist.org/p/provider-2015-10%24de30e2cf201d6d76340df713345334bf0470d994ae6b3ba744cc7025068e5917.json
Writing C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/p-provider-2015-10.json into cache
Downloading http://packagist.org/p/provider-2016-01%247a50d973c27fe3c528dd2e558169371b204937d2cdb4e9ecb3195151c9f6ad9e.json
Writing C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/p-provider-2016-01.json into cache
Reading C:/Users/dilang/AppData/Local/Composer/repo/https---packagist.org/p-provider-archived.json from cache
Downloading http://packagist.org/p/provider-latest%24206bdee1a09a43949aa2e7886563a0a7c88f332c0f5bbcfc1f53f87b1c4d8c06.json
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Downloading http://packagist.org/p/provider-latest%24206bdee1a09a43949aa2e7886563a0a7c88f332c0f5bbcfc1f53f87b1c4d8c06.json
Downloading http://packagist.org/p/provider-latest%24206bdee1a09a43949aa2e7886563a0a7c88f332c0f5bbcfc1f53f87b1c4d8c06.json
Downloading http://packagist.org/p/provider-latest%24206bdee1a09a43949aa2e7886563a0a7c88f332c0f5bbcfc1f53f87b1c4d8c06.json


  [ErrorException]
  zlib_decode(): data error


Exception trace:
 () at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Util/RemoteFilesystem.php:341
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 zlib_decode() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Util/RemoteFilesystem.php:341
 Composer\Util\RemoteFilesystem->get() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Util/RemoteFilesystem.php:98
 Composer\Util\RemoteFilesystem->getContents() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Repository/ComposerRepository.php:651
 Composer\Repository\ComposerRepository->fetchFile() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Repository/ComposerRepository.php:552
 Composer\Repository\ComposerRepository->loadProviderListings() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Repository/ComposerRepository.php:286
 Composer\Repository\ComposerRepository->whatProvides() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/DependencyResolver/Pool.php:199
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/DependencyResolver/Pool.php:188
 Composer\DependencyResolver\Pool->whatProvides() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:168
 Composer\DependencyResolver\RuleSetGenerator->whitelistFromPackage() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/DependencyResolver/RuleSetGenerator.php:322
 Composer\DependencyResolver\RuleSetGenerator->getRulesFor() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/DependencyResolver/Solver.php:208
 Composer\DependencyResolver\Solver->solve() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Installer.php:523
 Composer\Installer->doInstall() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Installer.php:232
 Composer\Installer->run() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Command/UpdateCommand.php:158
 Composer\Command\UpdateCommand->execute() at phar://F:/Documents/Projects/Web/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar://F:/Documents/Projects/Web/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar://F:/Documents/Projects/Web/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Console/Application.php:166
 Composer\Console\Application->doRun() at phar://F:/Documents/Projects/Web/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar://F:/Documents/Projects/Web/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar://F:/Documents/Projects/Web/composer.phar/bin/composer:43  require() at F:\Documents\Projects\Web\composer.phar:25

update [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [--with-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--] [<packages>]...

Seems that trying to download provider-latest gives a Problem. I am able to download the File using a normal webbrowser (everything seems fine then, i get the normal JSON Output).

**Comment by cs278** [comment] 2016-02-09 09:32
Have either of you updated Composer since it last worked?

**Comment by dirklang** [comment] 2016-02-09 09:36
Yes, i have updated Composer to the latest version. It seems, that it is related to a Proxy Problem in the Company Network. kitingChris has found a workaround forcing Composer to use only HTTPS.

**Comment by alcohol** [comment] 2016-02-09 11:28
While I understand that it might be frustrating, this is a duplicate of #4121. Unfortunately there is not much we can do from our end.

**Closed by alcohol** 2016-02-09 11:28 UTC

**Comment by kitingChris** [comment] 2016-02-09 16:29
Yep issue resolved due to this solution:

```
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.org"
        },
        { "packagist": false }
    ],
```

Perhaps this can find it way to the troubleshooting article as possible workaround.  https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode

Or as an additional suggestion: Add some kind of "prefer https" and/or "accept only https" option.

**Comment by machenchi0207** [comment] 2017-06-26 05:05
I have the same issue.But I try to disable the ipv6 on my vm (Centos 6.x) and it worked.

**Comment by abhishek321** [comment] 2017-09-11 12:19
Just run this command before install package using composer.
composer clear-cache

**Comment by provawebdev** [comment] 2017-11-20 09:50
composer require actuallymab/laravel-comment -dev
It's work for me

**Comment by sandun86** [comment] 2017-11-21 06:27
If you using Ubuntu..Then try to update composer as follow.
`sudo composer clear-cache`
add this line to composer.json
```
    "repositories": [
        {
            "type": "composer",
            "url": "https://packagist.org"
        },
        { "packagist": false }
    ],
```
`sudo composer update`

**Comment by petruskubito** [comment] 2017-12-01 20:19
try add composer.lock in your project

**Comment by jhoysner** [comment] 2017-12-15 03:38
composer config -g repositories.packagist composer https://packagist.jp

**Comment by marichellebisuna** [comment] 2018-01-31 13:21
i did what @abhishek321 suggested and yes it actually worked on me after i refresh my wifi router coz it could also be internet connection problem.

Just run the command:
composer clear-cache

**Comment by jonilsonanjos** [comment] 2018-05-23 21:43
Run the command: 
composer clear-cache
or
php componser.phar clear-cache (in case the composer is not installed).
