### ISSUE TITLE
Composer doesn't symlink from the path repository

### ISSUE THREAD

**Issue by emodric** [composer/composer#6110] opened 2017-01-27 17:10 UTC
When adding a path repo to `composer.json`, Composer doesn't symlink the requested package from provided path (which is a `git clone` of the repo), instead, it installs the dist version of the package from GitHub. I tried checking out various tags and branches in the repo, but nothing helps.

My `composer.json`:

```json
{
    "repositories": [
        { "type": "path", "url": "/home/eddie/repos/netgen/tagsbundle" }
    ],
    "require": {
        "netgen/tagsbundle": "^2.2"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 50 installs, 0 updates, 0 removals
// Other packages

  - Installing netgen/tagsbundle (2.2.3) Loading from cache

// Various suggestions

Writing lock file
Generating autoload files
ocramius/package-versions:  Generating version class...
ocramius/package-versions: ...done generating version class
```

And I expected this to happen:

I expected for `netgen/tagsbundle` package to be symlinked from `/home/eddie/repos/netgen/tagsbundle` path.

**Comment by dzuelke** [comment] 2017-01-28 14:26
Can you show `/home/eddie/repos/netgen/tagsbundle/composer.json`?

**Comment by dzuelke** [comment] 2017-01-28 14:27
And you're sure that `/home/eddie/repos/netgen/tagsbundle` is the correct path as well, right? There won't be an error if that path doesn't exist.

**Comment by emodric** [comment] 2017-01-28 14:34
I'm sure it's correct, yes :)

Here's the `composer.json`:

```
eddie@abyss [~] $ cat /home/eddie/repos/netgen/tagsbundle/composer.json
{
    "name": "netgen/tagsbundle",
    "description": "Netgen Tags Bundle is an eZ Platform / eZ Publish bundle for taxonomy management and easier classification of content, providing more functionality for tagging content than ezkeyword field type included in eZ Publish kernel.",
    "license": "GPL-2.0",
    "authors": [
        {
            "name": "Netgen",
            "homepage": "http://www.netgenlabs.com"
        }
    ],
    "require": {
        "ezsystems/ezpublish-kernel": "^6.0",
        "ezsystems/ezplatform-solr-search-engine": "^1.0"
    },
    "require-dev": {
        "phpunit/phpunit": "^4.8|^5.0",
        "symfony/symfony": "^2.7",
        "symfony/phpunit-bridge": "^2.7"
    },
    "suggest": {
        "ezsystems/eztags-ls": "For managing tags in legacy admin interface"
    },
    "conflict": {
        "ezsystems/eztags-ls": "<2.1"
    },
    "autoload": {
        "psr-4": {"Netgen\\TagsBundle\\": ""}
    },
    "extra": {
        "branch-alias": {
            "dev-master": "2.2.x-dev"
        }
    }
}
```

**Comment by dzuelke** [comment] 2017-01-28 17:24
You need a version in there I believe. Composer can't find one, so it never registers the package, and falls back to the online version.

**Comment by emodric** [comment] 2017-01-28 17:26
What do you mean by that? I tried checking out the `2.2.3` tag, as well as the branch the tag is on, and it didn't help.

**Comment by dzuelke** [comment] 2017-01-28 18:07
You need a `version` field in `composer.json`!

**Comment by emodric** [comment] 2017-01-28 18:17
Oh, okay... But I must admit, that doesn't make any sense, since docs specifically state that `version` field should be avoided.

**Comment by dzuelke** [comment] 2017-01-28 18:27
Not for path repos I think. For github etc it can pull the version from tags and branches, but not locally (although it could index that repo if it is one).

Anyway, does it work?

**Comment by emodric** [comment] 2017-01-28 19:14
It does, with the `version` field. However, that's not really convenient. If we shoud avoid `version` field (in VCS repos), how do I efficiently make my local clone of the same repo be used with symlink for development purposes?

**Comment by dzuelke** [comment] 2017-01-30 03:35
You put the version in there once, run "composer update", and remove the version again. It's symlinked, after all, so anything is reflected immediately, without you even having to commit changes.

**Comment by emodric** [comment] 2017-01-31 15:14
> It's symlinked, after all, so anything is reflected immediately, without you even having to commit changes.

Ofcourse, but you still need to run `composer update` from time to time. But it looks like updating the vendors doesn't remove or overwrite the symlink, so the trick with temp version number is working, although it is a bit clunky, I must admit :)

Thanks @dzuelke !

**Comment by Seldaek** [comment] 2017-02-25 18:28
If the `/home/eddie/repos/netgen/tagsbundle` is a git repo, normally it should find the current version automatically from there, without having to specify it in composer.json.. is that not working?

**Comment by emodric** [comment] 2017-02-25 18:45
Indeed, it did not. Only when I specified `version` in composer.json in the destination repo, symlink was created.

**Comment by Seldaek** [comment] 2017-02-25 19:13
Ok then I guess we would need more details to try and reproduce this.. Can
you make a repro case using a fresh clone of some open source repo?

**Comment by emodric** [comment] 2017-03-03 08:23
@Seldaek Yes, it happens with a fresh clone of https://github.com/netgen/tagsbundle and with the `composer.json` from the issue description.

As mentioned before, it happens in the master branch, `2.2-release` branch (where all `2.2.x` versions are located also) or when I checkout the `2.2.4` tag for example.

**Comment by Seldaek** [comment] 2017-03-06 16:49
With 2.2.4 of the bundle checked out, it installed from the path repo just fine, and with 2.2-release I had to change the require to `^2.2@dev` but then it installed from the path repo too. That is with the most recent composer master branch (`composer self-update --snapshot` to make sure you're on the latest dev build).

Closing as it seems fine to me really.

**Closed by Seldaek** 2017-03-06 16:49 UTC

**Comment by timothymarois** [comment] 2018-08-29 07:52
I'm having a similar issue. This was working just yesterday, and tonight its no longer linking the path, its using the online version. I know repo being linked had some version updates, but I cant see what would be off.. I updated `self-update` just to be sure I have the latest build. No luck. 

```
{
    "repositories": [
        {
            "type": "path",
            "url": "/Development/base/Framework/"
        }
    ],

    "require": {
        "base/framework": "1.2.*"
    },

    "autoload": {
        "psr-4": {
            "App\\": "app/"
        }
    },

    "optimize-autoloader": true
}
```

**Comment by sbuzonas** [comment] 2018-08-29 15:14
Unless you set `preferred-install` it will default to `auto`. Stable versions will prefer dist, and dev will prefer source. `1.2.*` may match a tag of `1.2.3` which would be satisfied and of stable stability. `1.2.x-dev` will match a branch with dev stability.

**Comment by timothymarois** [comment] 2019-03-04 23:15
Seeing this issue again with another project I'm working on. Honestly, there needs to be a failure option. **If I ask it to use a local repo, it should die if it is unsuccessful**, then tell me why it errored out. I have no idea why it is not creating the symlink. This is very frustrating. Changing branches, or paths. I even moved entire directories around to see if it's related to case-sensitivity. I seriously can't figure out why. 

1) Path exists, cd /to/path success!
2) require package : dev-master
3) minimum-stability : dev

**Comment by Seldaek** [comment] 2019-03-05 08:21
@timothymarois this is something we will most likely change/fix in 2.0..

**Comment by denitsa-cm** [comment] 2020-03-11 08:25
Having the same problem as @timothymarois right now. I can't figure out why it's not using the path and symlinking.

**Comment by inuvalogic** [comment] 2020-09-08 21:14
for those who are still has this issue, this is what I did and it's success, I'm using PHP 7.2 & Ubuntu 18.04

1. remove vendor folder & composer.lock files first, so we have a fresh folder
```sh
$ rm -rf vendor/
$ rm -rf composer.lock
```
2. remove your package from require section on your composer.json (it must be removed, I still don't understand why if my package is on composer.json file then do composer install / update not working)
```sh
"require": {
    "other/package": "*",
    "your/package: "dev-develop" --> remove this one
}
```
3. do composer install command to reinstall required package (except yours)
```sh
$ composer install
```
4. then do composer require your/package with branch dev-develop (don't understand why if I'm using different branch is not working)
```sh
$ composer require your/package dev-develop
```
5. and viola! Your symlinks are created

Hope this can help someone like me :)

**Comment by shaal** [comment] 2022-01-26 03:30
I had a similar issue. Here's the solution I found -
By adding a simple `composer.json` to `repos/my_project/`

```json
{
  "name": "my_repo/my_project",
  "description": "Description here.",
  "type": "drupal-module",
  "license": "GPL-2.0-or-later"
}
```

I was able to run `composer require my_repo/my_project`, that got symlinked to `repos/my_project/`.

**Comment by sirjeff** [comment] 2022-09-05 01:04
my 2 cents worth ...

My problem is symlinks only seem to be created when you install/require a plugin.

Neither  `composer update`  or  `composer install`  worked. It seems like once the lock file is written, composer thinks only updates to the files need to happen when issuing update r install.


This method works for me :
- `rm -rf composer.lock`
- `composer install`


BTW this is for a SilverStripe project where we include composer.lock in the repo. Works fine updating plugins, but as I mentioned, it seems the symlinks are only created on initial install of a plugin, and not an update.

Hope this helps someone :)
