### ISSUE TITLE
Fix bitbucket driver oauth token handling when updating git-installed packages

### ISSUE THREAD

**Issue by rentalhost** [composer/composer#8075] opened 2019-03-31 21:23 UTC
Following #8074

When an update fails and asks for reinstall the package, you will be ask for something like:

```
  - Updating the/package dev-master (00000000 => 11111111):  Checking out 2222222222
    Update failed (reason here)

    Would you like to try reinstalling the package instead [yes]?
```

If you wants to do this task without user interaction, there no option to "accept all". The `--no-interaction` will just skip (aka will reply "no").

Would be great if we have an option like `--yes` or `--autofix` to accept fixes like that without user interaction.

**Comment by alcohol** [comment] 2019-04-01 06:37
I am confused, in `--no-interaction` mode it should default to yes.

https://github.com/composer/composer/blob/158e1c95da02cc0b932de74f9a09a1c7b6cf654f/src/Composer/Downloader/DownloadManager.php#L279

Are you 100% certain it defaults to no for you?

**Comment by alcohol** [comment] 2019-04-02 06:28
Oh.. that's a bit of an odd flow perhaps. Maybe we should adjust that. @Seldaek how do you feel about attempting to reinstall by default in `--no-interaction` flow?

**Comment by Seldaek** [comment] 2019-04-05 14:44
I guess it might be fine to skip the whole question... The only worry I have is cases where the failure is due to uncommitted files or such.. in which case doing a reinstall will wipe everything. What errors did you see exactly @rentalhost? Because we do have https://getcomposer.org/doc/06-config.md#discard-changes to control the behavior for uncommitted files, and normally the rest shouldn't randomly fail.

**Comment by rentalhost** [comment] 2019-04-05 15:19
@Seldaek theres no changes, because it is a production instance that will only works with original files. Basically it will happen after some hours since the last successful auth.

This is the flow:

* The package is pushed to a private Bitbucket repository;
* If the auth session is outdated, then it will fail without update the package - it will treats like theres no package update:
  * ![1](https://user-images.githubusercontent.com/421851/55637501-969e1280-579b-11e9-9b8b-6b3d0d688a2a.png)
  * In this case, to make possible to update the package, I need to `composer clearcache` and `composer update` again:
    * ![image](https://user-images.githubusercontent.com/421851/55637870-6440e500-579c-11e9-8b33-4e010ad8f017.png)
    * At this point, there is some cases where it will fail and ask for reinstall package (it doesn't happen on today for some reason), but the error message is that:

```
  - Updating some-private/bitbucket-repository dev-master (4f201f5 => 046d100):  Checking out 046d100587
    Update failed (Failed to execute git remote set-url composer 'https://x-token-auth:***@bitbucket.org/some-private/bitbucket-repository.git' && git rev-parse --quiet --verify '046d100587495c81f4e6bcf9e0cd4f1e7dc2eb14^{commit}' || (git fetch composer && git fetch --tags composer)

remote: Invalid username or password
fatal: Authentication failed for 'https://x-token-auth:***@bitbucket.org/some-private/bitbucket-repository.git/'
)
    Would you like to try reinstalling the package instead [yes]?
```

So I reply `yes` to get that:

```
  - Removing some-private/bitbucket-repository (dev-master)
  - Installing some-private/bitbucket-repository (dev-master 046d100): Cloning 046d100587 from cache
Writing lock file
```

**Comment by Seldaek** [comment] 2019-04-05 15:22
Ok I see.. I guess it's fine to do this change but we'll have to make sure an update failing due to uncommitted changes does not perform a reinstall, because that might lead to data loss.

**Comment by alcohol** [comment] 2019-04-06 09:59
I think maybe someone should address the underlying cause though instead, rather than forcing the reinstall by default. Because it seems to me like if we instead refresh the oauth token being used to access the private bitbucket repository, the whole issue itself is already solved.

**Comment by alcohol** [comment] 2019-04-06 10:00
Somehow reinstalling it (after clearing the cache specifically) generates a new valid oauth token again. Not sure why we cannot just do that when it is expired. Maybe missing too many auxiliary features in our filesystem/downloader classes to support this.

**Comment by Seldaek** [comment] 2019-07-30 09:40
Yup I agree sounds like the Bitbucket token handling is the core issue here not the retry mechanism.. Marking as bug instead then, as that should be fixed.

**Comment by Xplouder** [comment] 2020-01-30 15:26
Any update?

**Comment by Seldaek** [comment] 2022-05-15 11:40
Closing as I am not sure this is still reproducible and nobody cared to fix it in these many years, if still applicable do tell.

**Closed by Seldaek** 2022-05-15 11:40 UTC
Labels: Bug
