### ISSUE TITLE
Reproducable build: deterministic APCU prefix

### ISSUE THREAD

**Issue by lstrojny** [composer/composer#7049] opened 2018-01-28 15:50 UTC
Each time when `composer install --no-dev --optimize-autoloader --apcu-autoloader` is run, a new random prefix is generated 

https://github.com/composer/composer/blob/be040f8e3111b38c1e49ae5cd6b929dbf5c39045/src/Composer/Autoload/AutoloadGenerator.php#L657

This is problematic if one tries to achieve reproducible builds where the same input leads to the same output. It would be cool if composer would offer an option to override the prefix or make it deterministic based on the `composer.lock` hash. Any other idea is welcome as well.

**Comment by Seldaek** [comment] 2018-01-31 14:02
We could use something similar to the `autoloader-suffix` config value but I find it pretty dangerous as with APCU if you don't change the prefix you might end up using a stale cache and break the application in case classes move or get removed.

I'd say maybe you should rather use --classmap-authoritative instead of --apcu-autoloader as per https://getcomposer.org/doc/articles/autoloader-optimization.md#optimization-level-2-a-authoritative-class-maps which IMO is the better approach anyway. And that won't have any random hashes.

**Comment by lstrojny** [comment] 2018-01-31 14:07
@Seldaek couldn't we just reuse the composer.lock content-hash?

**Comment by Seldaek** [comment] 2018-01-31 14:12
Well that hash doesn't include all class names. If some classes move or get removed in your project the content-hash won't change for example.

**Comment by stof** [comment] 2018-01-31 14:17
the lock file is hashing only the composer.json file (and not even all of it anymore but only the relevant parts). The APCu autoloader would require a hash of the list of classes available in your project (but if you build this reliably, storing the list itself in an authoritative classmap is indeed a better idea, as your project will now match the requirements of authoritative mode)

**Comment by lsl** [comment] 2018-02-12 13:17
I'm pretty sure this is what I ran into with laravel/lumen-framework/issues/504. Would be nice to see a solution / work around.

**Comment by nicolas-grekas** [comment] 2018-02-14 09:12
I think `--classmap-authoritative` is just the way to go. `--apcu-autoloader` cannot work with reproductible builds, because we must generate a different prefix all the time, to prune the apcu cache.

**Comment by dkarlovi** [comment] 2018-02-14 09:31
@nicolas-grekas what about a use case where there's no need to prune the cache, for example with Docker images? On production, if anything changes, a new image is rolled out anyway.

**Comment by stof** [comment] 2018-02-14 09:34
@dkarlovi In case this `if anything changes, a new image is rolled out anyway` condition holds true, you may as well be compatible with authoritative mode though.

**Comment by nicolas-grekas** [comment] 2018-02-14 09:35
`--apcu-autoloader=my_prefix`?

**Comment by dkarlovi** [comment] 2018-02-14 09:48
> --apcu-autoloader=my_prefix?

That works, IMO. Prefix specified, deterministic, up to the user to deal with pruning. Not specified, as-is.

**Comment by stof** [comment] 2018-02-14 09:58
@nicolas-grekas options with optional values are not working that well in symfony/console, especially in 2.x (which is used by Composer due to PHP version support). So using the `--apcu-autoloader` both for enabling the APCu support and forcing a prefix will not work fine IMO.

**Comment by AnrDaemon** [comment] 2018-02-20 13:25
I have a feeling that you want to turn a misfeature into requirement.
You've already got a suggestion to resolve your issue in a most unambiguous way.

**Comment by dkarlovi** [comment] 2018-03-21 13:56
@stof you were right, I've just tried auth classmap and Docker indeed uses cached layer, as expected.

**Comment by Seldaek** [comment] 2020-09-11 15:26
Closing as won't fix, I think authoritative classmap is the way to go for most projects.

**Comment by lstrojny** [comment] 2020-09-14 07:55
@Seldaek I think this should not be closed as there are cases where one cannot use authoritative classmaps, e.g. when dependencies preserve backwards compatibility via class aliases which cannot be detected when building the classmap. Basically this

`vendor/foo/bar/new_thing.php
```
class_alias(NewThing::class, BackwardsCompatibleThing::class);
class NewThing {}
```

Now `NewThing` will appear in the classmap but `BackwardsCompatibleThing` won’t but APCU based autoloading will work.

**Comment by lstrojny** [comment] 2020-09-14 07:56
P.S. happy to work on a patch for composer v2 to support passing a prefix

**Comment by Seldaek** [comment] 2020-09-14 18:56
@lstrojny ah that's an interesting limitation of the classmap scanner. Anyway ok reopening then. IMO the `--apcu-autoloader=my_prefix` approach with optional prefix would be an acceptable fix, if it works with the symfony/console 2.8. If not then it'll have to wait for Composer 2.1 when we bump dependency versions and drop old php.

**Comment by stof** [comment] 2020-09-15 09:46
> ah that's an interesting limitation of the classmap scanner.

maybe the classmap scanner could be improved to detect `class_alias` ?

**Comment by Seldaek** [comment] 2020-09-15 10:45
I'd rather not, seeing as this hasn't come up ever, and that it'd slow things down for everyone else. Especially if you have to figure out whether the class alias is within an if() block or not etc.. Just doesn't seem worth it.

**Closed** 2020-10-13 08:23 UTC
Labels: Feature
