### ISSUE TITLE
composer.lock keeps old dependencies

### ISSUE THREAD

**Issue by davidsteinsland** [composer/composer#4947] opened 2016-02-23 08:25 UTC
I just removed a package (let's call it `acme/foo`). This had several dependencies needed. However, after removing the package using `composer remove` my `composer.lock` file still contains all the other dependencies that the package needed.

Doing a `composer remove acme/baz` does not help at all. How can I keep my installation clean, if the lock file is filled with garbage? 

I would also like it if composer had an extra output of `composer info acme/baz` that said: "Was installed because dependency of acme/foo".

Here's what I see:
```
$ composer depends acme/foo
acme/bar requires acme/foo

$ composer depends acme/bar
acme/baz requires acme/bar

$ composer depends acme/baz
There is no installed package depending on "acme/baz".
```

**Comment by davidsteinsland** [comment] 2016-02-23 08:32
I was able to resolve the issue by removing the packages in reverse order:
```
composer remove acme/baz
composer remove acme/bar
composer remove acme/foo
```

Why is this? When none of the packages are installed, or required to be installed?

**Comment by curry684** [comment] 2016-02-23 08:53
Duplicate of #4895

**Closed** 2016-02-23 09:10 UTC
