### ISSUE TITLE
Deprecation Notice: Composer\Package\Version\VersionParser::parseLinks is deprecated.

### ISSUE THREAD

**Issue by Mirocow** [composer/composer#4294] opened 2015-07-24 19:07 UTC
```sh
$ composer -v
   ______
  / ____/___  ____ ___  ____  ____  ________  _____
 / /   / __ \/ __ `__ \/ __ \/ __ \/ ___/ _ \/ ___/
/ /___/ /_/ / / / / / / /_/ / /_/ (__  )  __/ /
\____/\____/_/ /_/ /_/ .___/\____/____/\___/_/
                    /_/
Composer version 1.0-dev (c6cc6dd6070871f4b198ed39f76dd8047c116b02) 2015-07-21 13:46:38

$ composer self-update
You are already using composer version c6cc6dd6070871f4b198ed39f76dd8047c116b02.

$ composer install --prefer-dist
Deprecation Notice: Composer\Package\Version\VersionParser::parseLinks is deprecated. Use \Composer\Package\Loader\ArrayLoader::parseLinks() instead in phar:///usr/local/bin/composer.phar/src/Composer/Package/Version/VersionParser.php:226
Deprecation Notice: Composer\Package\Version\VersionParser::parseLinks is deprecated. Use \Composer\Package\Loader\ArrayLoader::parseLinks() instead in phar:///usr/local/bin/composer.phar/src/Composer/Package/Version/VersionParser.php:226
```

**Comment by samdark** [comment] 2015-07-24 19:12
Duplicate of https://github.com/composer/composer/issues/4260

**Closed** 2015-07-24 19:28 UTC
