### ISSUE TITLE
Composer overrides PHP configuration and then fails because of missing extensions

### ISSUE THREAD

**Issue by renan** [composer/composer#5667] opened 2016-09-12 11:37 UTC
My `composer.json`:

```json
{
    "scripts": {
        "test-json": "php -r \"var_dump(function_exists('json_encode'));\""
    }
}
```

Having PHP with `xdebug` and `json` extensions installed, when running this script I get:

```shell
$ composer run test-json
> php -r "var_dump(function_exists('json_encode'));"
bool(false)
```

When Xdebug is enabled composer tries to restart itself and run without any extra .ini files being loaded, which causes `json` extension to not be present. So when you have scripts that depends on `json` extension the command fails.
This behavior is caused by [XdebugHandler](https://github.com/composer/composer/blob/master/src/Composer/XdebugHandler.php) and reproducible on latest master. Probably introduced on https://github.com/composer/composer/pull/5580

For example using `post-update-cmd` with `Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache`, which depends on `Monolog`, fails with:

```shell
[RuntimeException]
PHP's json extension is required to use Monolog's NormalizerFormatter
```

`XdebugHandler` re-runs the same command with the `-c` option (`-c <path>|<file> Look for php.ini file in this directory`) with the directory `/tmp/composer-php-empty/`, which is indeed empty.

**Comment by Seldaek** [comment] 2016-09-12 11:48
@renan could you show us what `php -i | grep 'Configuration|\.ini'` outputs? It shouldn't disable everything in theory it removes xdebug but reuses all other ini files that were loaded, so it seems it's not picking up whichever of your ini files loads the json extension.

cc @johnstevenson

**Comment by renan** [comment] 2016-09-12 11:56
I can see that `/tmp/composer-php.ini` is correctly created and does contain `extension=json`, but this is **never loaded**.

With `php -i` being run through `composer` script I get:
```
Configuration File (php.ini) Path => /etc/php5/cli
Loaded Configuration File => /etc/php5/cli/php.ini
Scan this dir for additional .ini files => /tmp/composer-php-empty
Additional .ini files parsed => (none)
```

`php -i` on the server:
```
Configuration File (php.ini) Path => /etc/php5/cli
Loaded Configuration File => /etc/php5/cli/php.ini
Scan this dir for additional .ini files => /etc/php5/cli/conf.d
Additional .ini files parsed => /etc/php5/cli/conf.d/05-opcache.ini,
/etc/php5/cli/conf.d/10-pdo.ini,
/etc/php5/cli/conf.d/20-apcu.ini,
/etc/php5/cli/conf.d/20-curl.ini,
/etc/php5/cli/conf.d/20-gd.ini,
/etc/php5/cli/conf.d/20-imagick.ini,
/etc/php5/cli/conf.d/20-imap.ini,
/etc/php5/cli/conf.d/20-intl.ini,
/etc/php5/cli/conf.d/20-json.ini,
/etc/php5/cli/conf.d/20-mcrypt.ini,
/etc/php5/cli/conf.d/20-memcache.ini,
/etc/php5/cli/conf.d/20-mysql.ini,
/etc/php5/cli/conf.d/20-mysqli.ini,
/etc/php5/cli/conf.d/20-pdo_mysql.ini,
/etc/php5/cli/conf.d/20-pdo_sqlite.ini,
/etc/php5/cli/conf.d/20-pinba.ini,
/etc/php5/cli/conf.d/20-readline.ini,
/etc/php5/cli/conf.d/20-sqlite3.ini,
/etc/php5/cli/conf.d/20-tidy.ini,
/etc/php5/cli/conf.d/20-xdebug.ini,
/etc/php5/cli/conf.d/xdebug.ini
```

I think you need to either copy the files to the location or tell php to run with the php.init file that is created.

**Comment by renan** [comment] 2016-09-12 12:00
On XdebugHandler, is changing the environment really needed?

**Comment by renan** [comment] 2016-09-12 12:00
Sorry, closed by mistake.

**Comment by alcohol** [comment] 2016-09-12 12:56
The problem is a bit more complicated than what you summarize.

For example, lets assume we call:
```
composer exec 'php -r "var_dump(function_exists(\"json_encode\"));"'
```

This gets interpreted by your php binary (cli) with its default php ini and ini dir settings.

Then the xdebughandler restarts the process by calling php with a custom ini file target, and sets an environment variable which specifies the new ini dir to scan.

Now we get to actually run the command you passed, e.g. `php -r "var_dump(function_exists("json_encode"));`.

The above php process uses your default php ini file, but it still inherits the custom ini dir to scan.

**Comment by Seldaek** [comment] 2016-09-12 13:02
Indeed this might be the issue, would be better if we could do it all via CLI flags avoiding environment variable changes so that it doesn't propagate to child processes. Alternatively we can also remove those env vars before calling child processes but that's uglier..

**Comment by renan** [comment] 2016-09-12 14:01
As discussed with @alcohol running the main process as it is done by XdebugHandler and sub-processes by resetting the `PHP_INI_SCAN_DIR` env var would work nicely, see: https://gist.github.com/renan/777d575a14d79f02a278800b53b3b4aa

**Comment by Seldaek** [comment] 2016-09-12 14:59
Should be fixed in latest snapshot

**Closed by Seldaek** 2016-09-12 14:59 UTC
Labels: Bug

**Comment by johnstevenson** [comment] 2016-09-12 18:03
Thanks guys. Sorry, I'm away from a computer for a few days and was unable to contribute to this bug fix. I'll reproduce and test when I can.

**Comment by Seldaek** [comment] 2016-09-12 18:06
Looks like it's fixed so no worries :)

**Comment by renan** [comment] 2016-09-12 18:12
I can no longer reproduce the issue using latest snapshot.
