### ISSUE TITLE
Get List of "Ready to Update" Packages but don't do update

### ISSUE THREAD

**Issue by mtangoo** [composer/composer#4666] opened 2015-12-03 06:39 UTC
I have checked docs and couldn't find any command (or series of commands) to accomplish this. I might be missing something so I need help.
Use Case:
I have an editor that uses composer to manage some of its projects. I want to be able to check for updates for all packages that user have installed and present option to update them if he wishes to. Something similar to Visual Studio NuGet manager.

Is there a way I can use composer to check that? If No, is it possible to write plugin that does so?
I'm ready to write one if it is not so hard (I know PHP but not internals of composer).
Thanks

For those who does not know VS NM
![nuget03](https://cloud.githubusercontent.com/assets/1502872/11553684/ccd7b130-9999-11e5-9722-ba2ac1f621df.png)

**Comment by Capenus** [comment] 2015-12-03 06:52
`composer update --dry-run` lists all updates. To update one package you can use `composer update package/name`

https://getcomposer.org/doc/03-cli.md#update

**Comment by alcohol** [comment] 2015-12-03 08:40
There is no feature that simply gives you a list of available updates. This functionality has been request a few times, but nobody has actually contributed it as of yet.

**Comment by alcohol** [comment] 2015-12-03 08:40
Duplicate of #3771

**Closed by alcohol** 2015-12-03 08:40 UTC

**Comment by simonschaufi** [comment] 2017-10-27 21:39
This tool might help: https://github.com/SpekBin/composer-package-update-checker

**Comment by alcohol** [comment] 2017-10-30 06:48
Not sure why this went into my notifications list; but anyway, the following command now exists:

```
composer oudated
```

**Comment by ytn3rd** [comment] 2018-01-09 02:50
@alcohol , I think you mean 

```
composer outdated
```

**Comment by alcohol** [comment] 2018-01-09 07:27
Correct.

**Comment by jlherren** [comment] 2020-01-14 08:25
Maybe not so important, but I'd like to point out that `composer update --dry-run` and `composer outdated` do not show the same set of updates, so they cannot be used interchangeably, but they're each useful on their own.

`composer outdated` will show updates that violate version specs in your `composer.json`. For example it will show phpunit version 8.5.2 even though `composer.json` says `"phpunit/phpunit": "~8.4.0"` which forbids any version 8.5.x. `.

**Comment by emtiazzahid** [comment] 2020-02-06 07:23
To get the list of outdated packages in **json** format

`composer outdated --format=json`
