### ISSUE TITLE
Path repository composer.lock

### ISSUE THREAD

**Issue by PapsOu** [composer/composer#7064] opened 2018-01-31 13:54 UTC
I'm using the « Path repository » technic to work with a library and a project using it (both use composer, they are symfony projects).

Every thing work great (ignoring problems with explicit release version set in the composer.json of the lib) but one problem appear. When running `composer update` the symlink is well done, but the `composer.lock` tracks the path repository configuration.

Here the example :

~/.composer/config.json
```json
{
    "repositories": [
        {
            "type": "path",
            "url": "/var/www/html/SIL",
            "options": {
                "symlink": true
            }
        }
    ]
}
```

The project composer json (that use the Platform lib)
```json
{
    "name": "libre-informatique/lisem-project",
    "license": "GPL-3.0-only",
    "require": {
        [...]
        "sil-project/platform": "dev-master",
        [...]
    },
    [...]
}
```

The Sil project is checkout on master in `/var/www/html/SIL`

The symlink is OK (`ls -l vendor/sil-project` => `platform -> ../../../SIL`)

Here the composer.lock diff :

```diff
             "dist": {
-                "type": "zip",
-                "url": "https://api.github.com/repos/sil-project/Platform/zipball/2634b25093f2fa95d06d12138bc0107ce618fae5",
+                "type": "path",
+                "url": "/var/www/html/SIL",
                 "reference": "2634b25093f2fa95d06d12138bc0107ce618fae5",
-                "shasum": ""
+                "shasum": null
             },
```

Is there something planned (or already done) to manage the composer.lock with path repositories ?

**Comment by Seldaek** [comment] 2018-01-31 14:18
Not sure what you mean by "manage the composer.lock". It works as it should IMO, you ask for a path package and you get it consistently in the lock file.. We don't support optional path packages for development. There is https://github.com/franzliedke/studio that can help.

Also closing this as duplicate of #601

**Closed by Seldaek** 2018-01-31 14:18 UTC

**Comment by PapsOu** [comment] 2018-01-31 14:30
That's not an optionnal package. it's a needed package, that I use localy with path repository (because I'm working on both projects). But, when releasing for tests (e.g. Jenkins or Travis builds), the composer.lock is used by these CI tools to speed up builds (in order to avoid using a `composer update` to fetch vendors)

My question was : Is there something to « transform » a path repository to a standard packagist repository when building the composer.lock file ? Nothing has been planned to handle this case ?

If it's No, then I would do a specific process to push a composer.lock with real packagist repository instead of path one.

**Comment by Seldaek** [comment] 2018-01-31 14:34
What I meant by optional package is what you are asking for, to optionally load a package from a path repo, but otherwise from packagist. Anyway no this is not supported.

**Comment by PapsOu** [comment] 2018-01-31 14:47
I've tried https://github.com/franzliedke/studio right now but the problem is the same, the composer.lock file tracks the path repository managed by Studio.

Thank you @Seldaek

**Comment by stof** [comment] 2018-01-31 14:53
Well, the composer.lock is meant to provide reproducible installs. So this is perfectly expected. There is absolutely no guarantee that your path repository has an equivalent repository on packagist (with exactly the same code in it and exactly the same requirements).

**Comment by PapsOu** [comment] 2018-01-31 15:09
@stof : Yes I know this « waranty » problem. But I expected that composer knows the real remote git repository of the symlinked lib in order to « translate » the path repository into a git repository. And yes, optionnaly check if the package exists on packagist (the lib I use is on packagist).

The beta version of Studio seems to use composer normaly but apply a symlink AFTER the composer.lock is generated.

I'll probably wait/help for that feature to be stabilized. Or may be I would ignore composer.lock file when developping application, generating it only for builds and deployment...

**Comment by atrauzzi** [comment] 2018-02-05 13:17
@Seldaek - I know it's been mentioned already, but I think studio isn't a *great* option for redirecting package references to a local path.  Overall it feels like a kludge to get around something only composer can do best within its own domain.

It would be super super nice if composer took on the functionality as an internal feature.

**Comment by artsafin** [comment] 2018-02-08 12:53
@stof
> Well, the composer.lock is meant to provide reproducible installs.

Here is the example of what `composer update` did to `composer.lock` after adding the path repository:
```diff
-            "version": "dev-master",
-            "source": {
-                "type": "git",
-                "url": "https://git-repository/package1.git",
-                "reference": "69a93a0b17c07fc4e984bb33da1a1794a8f0b242"

+            "version": "9999999-dev",
+            "dist": {
+                "type": "path",
+                "url": "/Users/artsafin/dev/packages/package1",
+                "reference": "69a93a0b17c07fc4e984bb33da1a1794a8f0b242",
+                "shasum": null
+             },
```
Now if I push the lock file to git repository, nobody of my colleagues will be able to work on the same project without prior running `composer update`.
I think there is ambiguity in term "reproducible" - using path repositories makes the lock file too rigid -
 though the installation is reproducable, it is only possible on dev machine because it contains local dev path to packages folder.

I agree with @PapsOu - if the path repository is defined in composer.json, contains a vcs repository and its HEAD matches the `composer.json` requirement, I think it is a good idea to assume that specified path is identical to remote git repository and skip changing `composer.lock`.

**Comment by franzliedke** [comment] 2018-02-09 15:30
@PapsOu The latest beta version of Studio tries to fix exactly that problem, the lockfile isn't touched. Please try it out and report there. :smile:

**Comment by atrauzzi** [comment] 2018-02-09 15:51
@franzliedke - That resolves ~50% of my concern with studio. Is there any way that studio can just store the list of packages that are being overridden in the platform-specific user preferences dir rather than a `json` file in the project root?

I'd probably just end up adding it to `.gitignore` as that path is going to vary between users (`/Users/bill`, `/home/sally`).

That would really lock in a similar convention to npm.

**Comment by franzliedke** [comment] 2018-02-09 15:54
@atrauzzi Feel free to discuss suggestions like that in an issue in the Studio repo. Let's not annoy people here. ;)
