### ISSUE TITLE
Travis cannot install anymore with v2

### ISSUE THREAD

**Issue by dereuromark** [composer/composer#9338] opened 2020-10-24 23:42 UTC
https://travis-ci.com/github/dereuromark/cakephp-ide-helper/jobs/406817819#L258

> if [[ $CHECKS != 1 ]]; then composer require --dev phpunit/phpunit:"^8.0"; fi
./composer.json has been updated
Running composer update phpunit/phpunit
Cannot update only a partial set of packages without a lock file present.
Installation failed, reverting ./composer.json to its original content.

The lock file is of course not present in a vendor library (plugin for a framework).
This used to work fine in v1 and seems like an unnecessary (accidental?) regression now in v2.
Which would now render a lot of travis builds impossible to run.

This should be able to do a normal install afterwards, without a lock file there is no conflict possible.

**Comment by staabm** [comment] 2020-10-25 01:14
Looks like https://github.com/composer/composer/pull/9336

**Comment by naderman** [comment] 2020-10-25 09:32
Indeed, this is a duplicate of #9336 which is fixed on master now. Would really have appreciated this kind of bug report for the RCs ;-)

**Closed by naderman** 2020-10-25 09:32 UTC
