### ISSUE TITLE
composer.json not accepted (no changes made)

### ISSUE THREAD

**Issue by webworksnbg** [composer/composer#6033] opened 2017-01-03 10:07 UTC
Hi,  by trying to update all packages of my project (without changing anything in the composer.json file), I got the following error messages:

My `composer.json`:

```
{
  "name": "symfony/framework-standard-edition",
  "license": "MIT",
  "type": "project",
  "description": "The \"Symfony Standard Edition\" distribution",
  "autoload": {
    "psr-0": {
      "": "src/"
    }
  },
  "require": {
    "php": ">=5.5",
    "symfony/symfony": "~2.7",
    "doctrine/orm": "~2.5",
    "doctrine/dbal": "~2.5",
    "doctrine/doctrine-bundle": "~1.6",
    "twig/extensions": "~1.3",
    "symfony/assetic-bundle": "~2.8",
    "symfony/swiftmailer-bundle": "~2.3",
    "symfony/monolog-bundle": "~2.11",
    "sensio/distribution-bundle": "~4.0",
    "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
    "sensio/generator-bundle": "~2.5",
    "incenteev/composer-parameter-handler": "~2.0",
    "jms/security-extra-bundle": "1.*",
    "jms/di-extra-bundle": "1.*",
    "friendsofsymfony/user-bundle": "~1.3",
    "doctrine/migrations": "1.*",
    "doctrine/doctrine-migrations-bundle": "1.*",
    "doctrine/doctrine-fixtures-bundle": "2.*",
    "oneup/uploader-bundle": "~1.5",
    "lunetics/locale-bundle": "2.*",
    "symfony/intl": "3.*",
    "symfony/locale": "2.*",
    "eluceo/ical": "~0.9",
    "kzykhys/twig-extensions": "0.1.*",
    "gregwar/captcha-bundle": "2.0.*",
    "friendsofsymfony/http-cache-bundle": "~1.0",
    "symfony/expression-language": "2.*",
    "liip/imagine-bundle": "1.*",
    "elasticsearch/elasticsearch": "2.*",
    "knplabs/knp-paginator-bundle": "2.*",
    "knplabs/knp-menu-bundle": "^2.1",
    "stfalcon/tinymce-bundle": "~1.0",
    "webworks-nuernberg/jquery-bundle": "^1.0",
    "webworks-nuernberg/select2-bundle": "1.0.*",
    "knplabs/knp-snappy-bundle": "^1.4",
    "excelwebzone/recaptcha-bundle": "^1.4",
    "jms/serializer-bundle": "^1.1",
    "suncat/mobile-detect-bundle": "1.0.*",

    "privaterepo/ApiBundle": "dev-master",
    "privaterepo/ArticleBundle": "dev-master",
    "privaterepo/BildBundle": "dev-master",
    "privaterepo/ContactBundle": "dev-master",
    "privaterepo/CsvBundle": "dev-master",
    "privaterepo/DashboardBundle": "dev-master",
    "privaterepo/MessagesBundle": "dev-master",
    "privaterepo/PageBundle": "dev-master",
    "privaterepo/PaymentBundle": "dev-master",
    "privaterepo/ProduktBundle": "dev-master",
    "privaterepo/ProfilBundle": "dev-master",
    "privaterepo/ProfilPortalBundle": "dev-master",
    "privaterepo/RatingBundle": "dev-master",
    "privaterepo/SitemapBundle": "dev-master",
    "privaterepo/StatsBundle": "dev-master",
    "privaterepo/SuperAdminBundle": "dev-master",
    "privaterepo/TagBundle": "dev-master",
    "privaterepo/TerminBundle": "dev-master",
    "privaterepo/UserBundle": "dev-master",
    "privaterepo/lib": "dev-master",
    "privaterepo/JobQueueBundle": "dev-master",
    "privaterepo/BillingBundle": "dev-master",
    "privaterepo/JobBundle": "dev-master"
  },
  "repositories": [
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/ApiBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/JobBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/JobQueueBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/BillingBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/NewsBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/CrmBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/ArticleBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/BildBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/ContactBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/CsvBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/DashboardBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/MessagesBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/PageBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/PaymentBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/ProductBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/ProfilBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/ProfilPortalBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/RatingBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/SitemapBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/StatsBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/SuperAdminBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/TagBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/TerminBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/UserBundle.git"
    },
    {
      "type": "git",
      "url": "git@git.webworks-nuernberg.de:privaterepo/lib.git"
    }
  ],
  "scripts": {
    "post-root-package-install": [
      "SymfonyStandard\\Composer::hookRootPackageInstall"
    ],
    "post-install-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
    ],
    "post-update-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles"
    ]
  },
  "config": {
    "bin-dir": "bin"
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-web-dir": "web",
    "incenteev-parameters": {
      "file": "app/config/parameters.yml"
    },
    "branch-alias": {
      "dev-master": "2.6-dev"
    }
  }
}
```

Output of `composer diagnose`:

```
  [Composer\Json\JsonValidationException]
  "./composer.json" does not match the expected JSON schema:
   - repositories[0] : Must contain no more than 1 properties
   - repositories[0].url : String value found, but a boolean is required
   - repositories[0].url : Does not have a value in the enumeration [false]
   - repositories[0].package : The property package is required
   - repositories[0].type : Does not have a value in the enumeration ["package"]
   - repositories[0].type : Does not have a value in the enumeration ["composer"]
   - repositories[0].url : Invalid URL format
   - repositories[0].type : Does not have a value in the enumeration ["path"]
   - repositories[0].type : Does not have a value in the enumeration ["artifact"]
   - repositories[0].type : Does not have a value in the enumeration ["pear"]
   - repositories[0] : Failed to match exactly one schema
   - repositories[1] : Must contain no more than 1 properties
   - repositories[1].url : String value found, but a boolean is required
   - repositories[1].url : Does not have a value in the enumeration [false]
   - repositories[1].package : The property package is required
   - repositories[1].type : Does not have a value in the enumeration ["package"]
   - repositories[1].type : Does not have a value in the enumeration ["composer"]
   - repositories[1].url : Invalid URL format
   - repositories[1].type : Does not have a value in the enumeration ["path"]
   - repositories[1].type : Does not have a value in the enumeration ["artifact"]
   - repositories[1].type : Does not have a value in the enumeration ["pear"]
   - repositories[1] : Failed to match exactly one schema
   - repositories[2] : Must contain no more than 1 properties
   - repositories[2].url : String value found, but a boolean is required
   - repositories[2].url : Does not have a value in the enumeration [false]
   - repositories[2].package : The property package is required
   - repositories[2].type : Does not have a value in the enumeration ["package"]
   - repositories[2].type : Does not have a value in the enumeration ["composer"]
   - repositories[2].url : Invalid URL format
   - repositories[2].type : Does not have a value in the enumeration ["path"]
   - repositories[2].type : Does not have a value in the enumeration ["artifact"]
   - repositories[2].type : Does not have a value in the enumeration ["pear"]
   - repositories[2] : Failed to match exactly one schema
   - repositories[3] : Must contain no more than 1 properties
   - repositories[3].url : String value found, but a boolean is required
   - repositories[3].url : Does not have a value in the enumeration [false]
   - repositories[3].package : The property package is required
   - repositories[3].type : Does not have a value in the enumeration ["package"]
   - repositories[3].type : Does not have a value in the enumeration ["composer"]
   - repositories[3].url : Invalid URL format
   - repositories[3].type : Does not have a value in the enumeration ["path"]
   - repositories[3].type : Does not have a value in the enumeration ["artifact"]
   - repositories[3].type : Does not have a value in the enumeration ["pear"]
   - repositories[3] : Failed to match exactly one schema
   - repositories[4] : Must contain no more than 1 properties
   - repositories[4].url : String value found, but a boolean is required
   - repositories[4].url : Does not have a value in the enumeration [false]
   - repositories[4].package : The property package is required
   - repositories[4].type : Does not have a value in the enumeration ["package"]
   - repositories[4].type : Does not have a value in the enumeration ["composer"]
   - repositories[4].url : Invalid URL format
   - repositories[4].type : Does not have a value in the enumeration ["path"]
   - repositories[4].type : Does not have a value in the enumeration ["artifact"]
   - repositories[4].type : Does not have a value in the enumeration ["pear"]
   - repositories[4] : Failed to match exactly one schema
   - repositories[5] : Must contain no more than 1 properties
   - repositories[5].url : String value found, but a boolean is required
   - repositories[5].url : Does not have a value in the enumeration [false]
   - repositories[5].package : The property package is required
   - repositories[5].type : Does not have a value in the enumeration ["package"]
   - repositories[5].type : Does not have a value in the enumeration ["composer"]
   - repositories[5].url : Invalid URL format
   - repositories[5].type : Does not have a value in the enumeration ["path"]
   - repositories[5].type : Does not have a value in the enumeration ["artifact"]
   - repositories[5].type : Does not have a value in the enumeration ["pear"]
   - repositories[5] : Failed to match exactly one schema
   - repositories[6] : Must contain no more than 1 properties
   - repositories[6].url : String value found, but a boolean is required
   - repositories[6].url : Does not have a value in the enumeration [false]
   - repositories[6].package : The property package is required
   - repositories[6].type : Does not have a value in the enumeration ["package"]
   - repositories[6].type : Does not have a value in the enumeration ["composer"]
   - repositories[6].url : Invalid URL format
   - repositories[6].type : Does not have a value in the enumeration ["path"]
   - repositories[6].type : Does not have a value in the enumeration ["artifact"]
   - repositories[6].type : Does not have a value in the enumeration ["pear"]
   - repositories[6] : Failed to match exactly one schema
   - repositories[7] : Must contain no more than 1 properties
   - repositories[7].url : String value found, but a boolean is required
   - repositories[7].url : Does not have a value in the enumeration [false]
   - repositories[7].package : The property package is required
   - repositories[7].type : Does not have a value in the enumeration ["package"]
   - repositories[7].type : Does not have a value in the enumeration ["composer"]
   - repositories[7].url : Invalid URL format
   - repositories[7].type : Does not have a value in the enumeration ["path"]
   - repositories[7].type : Does not have a value in the enumeration ["artifact"]
   - repositories[7].type : Does not have a value in the enumeration ["pear"]
   - repositories[7] : Failed to match exactly one schema
   - repositories[8] : Must contain no more than 1 properties
   - repositories[8].url : String value found, but a boolean is required
   - repositories[8].url : Does not have a value in the enumeration [false]
   - repositories[8].package : The property package is required
   - repositories[8].type : Does not have a value in the enumeration ["package"]
   - repositories[8].type : Does not have a value in the enumeration ["composer"]
   - repositories[8].url : Invalid URL format
   - repositories[8].type : Does not have a value in the enumeration ["path"]
   - repositories[8].type : Does not have a value in the enumeration ["artifact"]
   - repositories[8].type : Does not have a value in the enumeration ["pear"]
   - repositories[8] : Failed to match exactly one schema
   - repositories[9] : Must contain no more than 1 properties
   - repositories[9].url : String value found, but a boolean is required
   - repositories[9].url : Does not have a value in the enumeration [false]
   - repositories[9].package : The property package is required
   - repositories[9].type : Does not have a value in the enumeration ["package"]
   - repositories[9].type : Does not have a value in the enumeration ["composer"]
   - repositories[9].url : Invalid URL format
   - repositories[9].type : Does not have a value in the enumeration ["path"]
   - repositories[9].type : Does not have a value in the enumeration ["artifact"]
   - repositories[9].type : Does not have a value in the enumeration ["pear"]
   - repositories[9] : Failed to match exactly one schema
   - repositories[10] : Must contain no more than 1 properties
   - repositories[10].url : String value found, but a boolean is required
   - repositories[10].url : Does not have a value in the enumeration [false]
   - repositories[10].package : The property package is required
   - repositories[10].type : Does not have a value in the enumeration ["package"]
   - repositories[10].type : Does not have a value in the enumeration ["composer"]
   - repositories[10].url : Invalid URL format
   - repositories[10].type : Does not have a value in the enumeration ["path"]
   - repositories[10].type : Does not have a value in the enumeration ["artifact"]
   - repositories[10].type : Does not have a value in the enumeration ["pear"]
   - repositories[10] : Failed to match exactly one schema
   - repositories[11] : Must contain no more than 1 properties
   - repositories[11].url : String value found, but a boolean is required
   - repositories[11].url : Does not have a value in the enumeration [false]
   - repositories[11].package : The property package is required
   - repositories[11].type : Does not have a value in the enumeration ["package"]
   - repositories[11].type : Does not have a value in the enumeration ["composer"]
   - repositories[11].url : Invalid URL format
   - repositories[11].type : Does not have a value in the enumeration ["path"]
   - repositories[11].type : Does not have a value in the enumeration ["artifact"]
   - repositories[11].type : Does not have a value in the enumeration ["pear"]
   - repositories[11] : Failed to match exactly one schema
   - repositories[12] : Must contain no more than 1 properties
   - repositories[12].url : String value found, but a boolean is required
   - repositories[12].url : Does not have a value in the enumeration [false]
   - repositories[12].package : The property package is required
   - repositories[12].type : Does not have a value in the enumeration ["package"]
   - repositories[12].type : Does not have a value in the enumeration ["composer"]
   - repositories[12].url : Invalid URL format
   - repositories[12].type : Does not have a value in the enumeration ["path"]
   - repositories[12].type : Does not have a value in the enumeration ["artifact"]
   - repositories[12].type : Does not have a value in the enumeration ["pear"]
   - repositories[12] : Failed to match exactly one schema
   - repositories[13] : Must contain no more than 1 properties
   - repositories[13].url : String value found, but a boolean is required
   - repositories[13].url : Does not have a value in the enumeration [false]
   - repositories[13].package : The property package is required
   - repositories[13].type : Does not have a value in the enumeration ["package"]
   - repositories[13].type : Does not have a value in the enumeration ["composer"]
   - repositories[13].url : Invalid URL format
   - repositories[13].type : Does not have a value in the enumeration ["path"]
   - repositories[13].type : Does not have a value in the enumeration ["artifact"]
   - repositories[13].type : Does not have a value in the enumeration ["pear"]
   - repositories[13] : Failed to match exactly one schema
   - repositories[14] : Must contain no more than 1 properties
   - repositories[14].url : String value found, but a boolean is required
   - repositories[14].url : Does not have a value in the enumeration [false]
   - repositories[14].package : The property package is required
   - repositories[14].type : Does not have a value in the enumeration ["package"]
   - repositories[14].type : Does not have a value in the enumeration ["composer"]
   - repositories[14].url : Invalid URL format
   - repositories[14].type : Does not have a value in the enumeration ["path"]
   - repositories[14].type : Does not have a value in the enumeration ["artifact"]
   - repositories[14].type : Does not have a value in the enumeration ["pear"]
   - repositories[14] : Failed to match exactly one schema
   - repositories[15] : Must contain no more than 1 properties
   - repositories[15].url : String value found, but a boolean is required
   - repositories[15].url : Does not have a value in the enumeration [false]
   - repositories[15].package : The property package is required
   - repositories[15].type : Does not have a value in the enumeration ["package"]
   - repositories[15].type : Does not have a value in the enumeration ["composer"]
   - repositories[15].url : Invalid URL format
   - repositories[15].type : Does not have a value in the enumeration ["path"]
   - repositories[15].type : Does not have a value in the enumeration ["artifact"]
   - repositories[15].type : Does not have a value in the enumeration ["pear"]
   - repositories[15] : Failed to match exactly one schema
   - repositories[16] : Must contain no more than 1 properties
   - repositories[16].url : String value found, but a boolean is required
   - repositories[16].url : Does not have a value in the enumeration [false]
   - repositories[16].package : The property package is required
   - repositories[16].type : Does not have a value in the enumeration ["package"]
   - repositories[16].type : Does not have a value in the enumeration ["composer"]
   - repositories[16].url : Invalid URL format
   - repositories[16].type : Does not have a value in the enumeration ["path"]
   - repositories[16].type : Does not have a value in the enumeration ["artifact"]
   - repositories[16].type : Does not have a value in the enumeration ["pear"]
   - repositories[16] : Failed to match exactly one schema
   - repositories[17] : Must contain no more than 1 properties
   - repositories[17].url : String value found, but a boolean is required
   - repositories[17].url : Does not have a value in the enumeration [false]
   - repositories[17].package : The property package is required
   - repositories[17].type : Does not have a value in the enumeration ["package"]
   - repositories[17].type : Does not have a value in the enumeration ["composer"]
   - repositories[17].url : Invalid URL format
   - repositories[17].type : Does not have a value in the enumeration ["path"]
   - repositories[17].type : Does not have a value in the enumeration ["artifact"]
   - repositories[17].type : Does not have a value in the enumeration ["pear"]
   - repositories[17] : Failed to match exactly one schema
   - repositories[18] : Must contain no more than 1 properties
   - repositories[18].url : String value found, but a boolean is required
   - repositories[18].url : Does not have a value in the enumeration [false]
   - repositories[18].package : The property package is required
   - repositories[18].type : Does not have a value in the enumeration ["package"]
   - repositories[18].type : Does not have a value in the enumeration ["composer"]
   - repositories[18].url : Invalid URL format
   - repositories[18].type : Does not have a value in the enumeration ["path"]
   - repositories[18].type : Does not have a value in the enumeration ["artifact"]
   - repositories[18].type : Does not have a value in the enumeration ["pear"]
   - repositories[18] : Failed to match exactly one schema
   - repositories[19] : Must contain no more than 1 properties
   - repositories[19].url : String value found, but a boolean is required
   - repositories[19].url : Does not have a value in the enumeration [false]
   - repositories[19].package : The property package is required
   - repositories[19].type : Does not have a value in the enumeration ["package"]
   - repositories[19].type : Does not have a value in the enumeration ["composer"]
   - repositories[19].url : Invalid URL format
   - repositories[19].type : Does not have a value in the enumeration ["path"]
   - repositories[19].type : Does not have a value in the enumeration ["artifact"]
   - repositories[19].type : Does not have a value in the enumeration ["pear"]
   - repositories[19] : Failed to match exactly one schema
   - repositories[20] : Must contain no more than 1 properties
   - repositories[20].url : String value found, but a boolean is required
   - repositories[20].url : Does not have a value in the enumeration [false]
   - repositories[20].package : The property package is required
   - repositories[20].type : Does not have a value in the enumeration ["package"]
   - repositories[20].type : Does not have a value in the enumeration ["composer"]
   - repositories[20].url : Invalid URL format
   - repositories[20].type : Does not have a value in the enumeration ["path"]
   - repositories[20].type : Does not have a value in the enumeration ["artifact"]
   - repositories[20].type : Does not have a value in the enumeration ["pear"]
   - repositories[20] : Failed to match exactly one schema
   - repositories[21] : Must contain no more than 1 properties
   - repositories[21].url : String value found, but a boolean is required
   - repositories[21].url : Does not have a value in the enumeration [false]
   - repositories[21].package : The property package is required
   - repositories[21].type : Does not have a value in the enumeration ["package"]
   - repositories[21].type : Does not have a value in the enumeration ["composer"]
   - repositories[21].url : Invalid URL format
   - repositories[21].type : Does not have a value in the enumeration ["path"]
   - repositories[21].type : Does not have a value in the enumeration ["artifact"]
   - repositories[21].type : Does not have a value in the enumeration ["pear"]
   - repositories[21] : Failed to match exactly one schema
   - repositories[22] : Must contain no more than 1 properties
   - repositories[22].url : String value found, but a boolean is required
   - repositories[22].url : Does not have a value in the enumeration [false]
   - repositories[22].package : The property package is required
   - repositories[22].type : Does not have a value in the enumeration ["package"]
   - repositories[22].type : Does not have a value in the enumeration ["composer"]
   - repositories[22].url : Invalid URL format
   - repositories[22].type : Does not have a value in the enumeration ["path"]
   - repositories[22].type : Does not have a value in the enumeration ["artifact"]
   - repositories[22].type : Does not have a value in the enumeration ["pear"]
   - repositories[22] : Failed to match exactly one schema
   - repositories[23] : Must contain no more than 1 properties
   - repositories[23].url : String value found, but a boolean is required
   - repositories[23].url : Does not have a value in the enumeration [false]
   - repositories[23].package : The property package is required
   - repositories[23].type : Does not have a value in the enumeration ["package"]
   - repositories[23].type : Does not have a value in the enumeration ["composer"]
   - repositories[23].url : Invalid URL format
   - repositories[23].type : Does not have a value in the enumeration ["path"]
   - repositories[23].type : Does not have a value in the enumeration ["artifact"]
   - repositories[23].type : Does not have a value in the enumeration ["pear"]
   - repositories[23] : Failed to match exactly one schema
   - repositories[24] : Must contain no more than 1 properties
   - repositories[24].url : String value found, but a boolean is required
   - repositories[24].url : Does not have a value in the enumeration [false]
   - repositories[24].package : The property package is required
   - repositories[24].type : Does not have a value in the enumeration ["package"]
   - repositories[24].type : Does not have a value in the enumeration ["composer"]
   - repositories[24].url : Invalid URL format
   - repositories[24].type : Does not have a value in the enumeration ["path"]
   - repositories[24].type : Does not have a value in the enumeration ["artifact"]
   - repositories[24].type : Does not have a value in the enumeration ["pear"]
   - repositories[24] : Failed to match exactly one schema
```

When I run this command:

`composer update`

I get the following output:

see above

And I expected this to happen:

updating vendors packages

**Comment by alcohol** [comment] 2017-01-03 10:29
Related #6028 /cc @stof

**Comment by webworksnbg** [comment] 2017-01-03 10:33
Thanks, I updated composer, now it works. (Composer version 1.3.0 2016-12-24 00:47:03)

**Comment by stof** [comment] 2017-01-03 10:33
yeah, this is a duplicate of #6028. Please try #6034 for the fix

**Comment by stof** [comment] 2017-01-03 10:33
hmm no, this was a duplicate of #6021 actually, which is already fixed

**Comment by alcohol** [comment] 2017-01-03 10:37
@webworksnbg you "updated" from dev to the latest stable which does not contain the new validation yet, so yes that will work :-). The latest dev version should also work in your scenario though, according to @stof. Can you confirm?

**Comment by webworksnbg** [comment] 2017-01-03 11:16
@alcohol where do you see that I had the dev-version?

I didn't updated before, so I'm wondering, how I got the dev version that didn't worked befor the last update to 1.3

**Comment by Seldaek** [comment] 2017-01-03 12:14
Fixed by https://github.com/composer/composer/pull/6034 - please try again with latest after `composer self-update --snapshot`

**Closed by Seldaek** 2017-01-03 12:14 UTC
Labels: Bug

**Comment by alcohol** [comment] 2017-01-03 21:57
> @alcohol where do you see that I had the dev-version?

Because only the dev version contained the code related to this issue :-)
