### ISSUE TITLE
Global require does not check PHP platform

### ISSUE THREAD

**Issue by theofidry** [composer/composer#4477] opened 2015-10-04 20:25 UTC
For a Travis build, I'm installing PHPUnit globally and so for multiple PHP versions. Recently, PHPUnit 5 has been released, so logically PHPUnit 5 will be installed when possible (requires PHP >=5.6). However on builds with PHP5.4 or 5.5, it is still PHPUnit 5 that is installed, causing an update to fail later.

Build Job on PHP 5.4: https://travis-ci.org/hautelook/AliceBundle/jobs/83580436
Complete list of build jobs: https://travis-ci.org/hautelook/AliceBundle?branch=master

**Comment by alcohol** [comment] 2015-10-04 23:05
Duplicate of the issue right below this one; #4474

**Closed by alcohol** 2015-10-04 23:05 UTC

**Comment by alcohol** [comment] 2015-10-04 23:10
See also my second comment on that issue for a rather obvious solution.
