### ISSUE TITLE
Updating passed 2014-11-05_06-04-18-ffffab3 causes timeout issue with powershell as a post-update-cmd

### ISSUE THREAD

**Issue by u01jmg3** [composer/composer#3573] opened 2014-12-19 11:36 UTC
- I am finding that running `composer update` using the most recent version of composer (`a422d67e2701860a44a4634f62f88b58b8636468`) causes a timeout error for powershell commands. Has there been a significant change to composer which may be causing this?
  - `2014-11-05_06-04-18-ffffab3` is the last version that doesn't suffer from this timeout

``` json
"post-update-cmd": [
    "php artisan clear-compiled",
    "php artisan debugbar:publish",
    "php artisan optimize",
    "powershell -Command \"(gc vendor/laravel/framework/src/Illuminate/View/Environment.php) -replace '\\$mergeData, \\$this', '(array)$mergeData, (array)$this' | Out-File -encoding ASCII vendor/laravel/framework/src/Illuminate/View/Environment.php\""
]
```

**Comment by u01jmg3** [comment] 2015-04-08 20:19
I see there are 478 open issues so doubtful this will be looked at any time soon

**Comment by u01jmg3** [comment] 2015-05-12 12:33
`2014-11-05_06-04-18-ffffab3` is now too old to use so there is no working copy of composer I can use with the `post-update-cmd` above :(

**Comment by Seldaek** [comment] 2015-11-19 17:46
@u01jmg3 could you resolve this somehow? Sorry for the delay getting to this issue but I don't quite see why it should've started to fail. Unfortunately I can hardly try and reproduce it, so it'd be nice if you can update this.

**Comment by u01jmg3** [comment] 2016-01-07 15:08
Tested with `64b0d721838cdceef679761c5cf69a0d070d14c9` and still getting a timeout trying to run the following as a `post-update-cmd` command:

- ```
powershell -Command "(gc vendor/laravel/framework/src/Illuminate/View/Environment.php) -replace '\$mergeData, \$this', '(array)$mergeData, (array)$this' | Out-File -encoding ASCII vendor/laravel/framework/src/Illuminate/View/Environment.php"
```

**Comment by Seldaek** [comment] 2016-04-15 19:35
That's unfortunate but due to the limited use case here I doubt anyone will look at this. If you'd like to get it fixed it'd be good to dig in yourself a bit, or provide a simpler reproduce case if it really is any powershell command timing out.

**Comment by Seldaek** [comment] 2017-03-07 15:59
Closing for now.. seems nobody cares enough to fix sorry.

**Closed by Seldaek** 2017-03-07 15:59 UTC
Labels: Bug

**Comment by u01jmg3** [comment] 2017-03-07 16:24
Shall try and find some time to look at this again and provide more clarity - understand why you have to close it though.

**Comment by Seldaek** [comment] 2017-03-07 16:38
Yeah I'm not against a fix but I rather avoid issues cluttering the tracker if nobody is interested in fixing them :/
