### ISSUE TITLE
Updating a package provided by a path repository can delete the source

### ISSUE THREAD

**Issue by greg-1-anderson** [composer/composer#8389] opened 2019-10-25 19:42 UTC
## Problem Statement:

When a package is provided by a path repository, and the Composer Installers plugin is used to install the same package to its source location, then the source directory can be deleted by Composer.

Usually, Composer will detect that the path repository is being installed to its source location and do the right thing (new feature in Composer 1.9.0). The behavior is problematic, though, if the path repository no longer matches the version constraints stipulated in the composer.json file.

In the case of Drupal, drupal/core is provided as a path repository to the "core" directory. It is also subtree-split out to Packagist, so that sites that are *running* Drupal install drupal/core in a conventional way (i.e. from Packagist) -- the path repository is only used when doing core development. This is an interim situation (lasting years prbly) moving us towards actual native Composer use (e.g. perhaps restructuring like Symfony, with all "replace" directives in the root -- but we can't do that yet).

The problem arises if a core developer decides to update a dependency in the core/composer.json file, and then makes a mistake updating the composer.lock file and vendor directory.

## Steps to reproduce (n.b. output truncated for readability):

```
$ git clone https://git.drupalcode.org/project/drupal.git --branch=8.8.x
$ cd drupal
$ composer install
$ composer --working-dir=core require twig/twig:^2 --no-update
$ composer update drupal/core
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Removing drupal/core (8.8.x-dev), source is still present in core
  - Installing drupal/core (8.8.x-dev 8117454): Loading from cache
```

In the example above, `composer update drupal/core` could not be upgraded, because twig/twig is still locked to ^1. If the user had instead run `composer update drupal/core twig/twig` or `composer update drupal/core --with-dependencies`, it would have worked.

## Expected behavior:

Composer should give an error, "your project could not be updated".

## Actual behavior:

Composer notices that drupal/core can not be updated, but it finds an older version of drupal/core in Packagist that is still installable. It therefore "uninstalls" the current path repository and overwrites the source location with the older copy installed from Packagist.

**Comment by greg-1-anderson** [comment] 2019-10-27 12:35
I tried changing the warning to an error in `PathDownloader::remove` (throw an exception instead of printing a message); however, this was not effective, as Composer will innocuously remove and re-add path repositories during normal operation of `composer update` where this problem is not evidenced.

I have also [tried some workarounds in Drupal to detect and prevent this error](https://www.drupal.org/project/drupal/issues/3088935); however, it seems difficult to detect all of the scenarios where this error might occur, and Composer scripts do not have ready access to the whitelist in any event.

It seems that the best fix would be in Composer somewhere in the 'install' step.

**Comment by alcohol** [comment] 2019-10-29 08:19
Can you confirm this happens with `--no-plugins` ?

**Comment by alcohol** [comment] 2019-10-29 08:29
I'm confused about what the issue is here though. Composer does not actually delete the source. So I find the issue title quite misleading. Then there is a wall of text describing a workflow, which from what I can gather, mostly just works.

**Comment by alcohol** [comment] 2019-10-29 08:30
> It therefore "uninstalls" the current path repository and overwrites the source location with the older copy installed from Packagist.

No, it simply removes the symlink in `vendor/` (pointing to `./core`), and installs the older version inside your `vendor/` directory.

**Comment by greg-1-anderson** [comment] 2019-10-31 00:49
@alcohol You are correct that the source directory will not be deleted if `--no-plugins` is used. The source is only deleted if Composer Installers is used to install a path repository to its source location.

Even in instances when the source is not deleted, this behavior is undesirable, because the information in the composer.lock file changes when a project is converted from being installed from its path repository to being installed from Packagist. For projects that commit the composer.lock file, this is something for users to get wrong if their pull request accidentally downgrades a path repository.

I will build a minimal reproducible case that demonstrates the downgrading behavior with `--no-plugins` / without the Composer Installers plugin, and will rewrite the issue summary to match.

**Comment by fadaile** [comment] 2019-10-31 06:36
![menu](https://user-images.githubusercontent.com/25277561/67924414-7eaf3580-fba8-11e9-8403-01b158b84219.png)

**Comment by alcohol** [comment] 2019-10-31 08:09
> I will build a minimal reproducible case that demonstrates the downgrading behavior with --no-plugins / without the Composer Installers plugin, and will rewrite the issue summary to match.

That would greatly help in explaining the exact use-case or problem, and whether or not this is a snowflake or an issue that hits our entire userbase.

**Comment by cs278** [comment] 2019-12-17 17:18
I've just been bitten by this (or something similar) in a Symfony project using `1.9.0`. Unfortunately I have not been able to reproduce the problem after a bunch of experimenting, with and without `--no-plugins`.

In my case the symlink was maintained but the directory referenced was cleaned out.

I'll have another go at recreating this once I've recovered my lost work. :cry: 

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "~4.4.0"
Package operations: 0 installs, 1 update, 0 removals
  - Removing some/package (0.11.x-dev), source is still present in /.../vendor/some/package
  - Installing some/package (0.11.x-dev): Source already present
Package phpstan/phpstan-shim is abandoned, you should avoid using it. Use phpstan/phpstan instead.
Writing lock file
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class

What about running composer global require symfony/thanks && composer thanks now?
This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.

Executing script cache:clear [OK]
Executing script assets:install public [OK]
```

**Comment by doekenorg** [comment] 2020-05-23 18:42
> I've just been bitten by this (or something similar) in a Symfony project using `1.9.0`. Unfortunately I have not been able to reproduce the problem after a bunch of experimenting, with and without `--no-plugins`.
> 
> In my case the symlink was maintained but the directory referenced was cleaned out.
> 
> I'll have another go at recreating this once I've recovered my lost work. 😢
> 
> ```
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Restricting packages listed in "symfony/symfony" to "~4.4.0"
> Package operations: 0 installs, 1 update, 0 removals
>   - Removing some/package (0.11.x-dev), source is still present in /.../vendor/some/package
>   - Installing some/package (0.11.x-dev): Source already present
> Package phpstan/phpstan-shim is abandoned, you should avoid using it. Use phpstan/phpstan instead.
> Writing lock file
> Generating autoload files
> ocramius/package-versions: Generating version class...
> ocramius/package-versions: ...done generating version class
> 
> What about running composer global require symfony/thanks && composer thanks now?
> This will spread some 💖  by sending a ★  to the GitHub repositories of your fellow package maintainers.
> 
> Executing script cache:clear [OK]
> Executing script assets:install public [OK]
> ```

Had the same thing happen to me today. Fortunately I used PHPStorm and was able to retrieve everything from `Local History`. But otherwise I would have lost weeks of work, because the branch I was working on was not on my remote. 

Seems like when you have a local repository setup, composer will "remove" the folder, but the symlink stays intact. It will then download whatever version it can find, and install it in that (symlinked) folder. Removing EVERYTHING inside, including the original `.git`.

I've learned my lesson, but I was baffled by this behavior.

**Comment by Seldaek** [comment] 2022-05-23 13:44
Not sure what to do here. If this is still an issue it'd be great to get an updated idiot proof repro script.

**Comment by doekenorg** [comment] 2022-05-23 16:25
I haven't had this happen in two years now. Probably a fluke in the filesystem or something. For my sake you can close this issue.

**Closed** 2022-05-23 17:07 UTC
Labels: Bug
