### ISSUE TITLE
Composer does not select git branches named like `1.0.x` while installation.

### ISSUE THREAD

**Issue by oprokidnev** [composer/composer#6162] opened 2017-02-16 08:04 UTC
Noticed that composer does not map remote branch named `2.1.x` with my local project reposiotory properly. 
`composer.json`:

```json
{
 "require":{
  "some-vendor/some-local-repo":"^2.1"
 }
}
```

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer update|install|require
```

I get the following output:

```
Executing command (CWD): git clone --no-checkout 'https://some-repo.com/some-vendor/some-local-repo.git' '/project/vendor/some-vendor/some-local-repo' --dissociate --reference '/user/.composer/cache/vcs/https---some-repo.com-zf2-wm-widget.git/' && cd '/project/vendor/some-vendor/some-local-repo' && git remote add composer 'https://some-repo.com/some-vendor/some-local-repo.git' && git fetch composer
Executing command (/project/vendor/some-vendor/some-local-repo): git branch -r
Executing command (/project/vendor/some-vendor/some-local-repo): git checkout '2.1' --
Executing command (/project/vendor/some-vendor/some-local-repo): git checkout -B '2.1' 'composer/2.1' --
Executing command (/project/vendor/some-vendor/some-local-repo): git checkout '9497797e59828bf1a45577a3a8d2241875e544c5' -- && git reset --hard '9497797e59828bf1a45577a3a8d2241875e544c5' --
```

**Comment by stof** [comment] 2017-02-16 09:20
please give the full output. You remove the line where composer says which version it selected

**Comment by oprokidnev** [comment] 2017-02-16 11:46
@stof I think you this issue can be reproduced by the following composer json: 

```json
{
    "name": "test/branch",
    "authors": [
        {
            "name": "Andrey Oprokidnev",
            "email": "aa@oprokidnev.ru"
        }
    ],
    "require": {
        "doctrine/doctrine-module": "1.0.x-dev"
    }
}

``` 

``` 

- Installing doctrine/doctrine-module (1.0.x-dev 2214a69)Executing command (CWD): git --version

    Cloning to cache at '/home/oprokidnev/.composer/cache/vcs/https---github.com-doctrine-DoctrineModule.git/'
Executing command (/home/oprokidnev/.composer/cache/vcs/https---github.com-doctrine-DoctrineModule.git/): git rev-parse --git-dir
Executing command (/home/oprokidnev/.composer/cache/vcs/https---github.com-doctrine-DoctrineModule.git/): git remote -v
Executing command (/home/oprokidnev/.composer/cache/vcs/https---github.com-doctrine-DoctrineModule.git/): git remote set-url origin 'https://github.com/doctrine/DoctrineModule.git' && git remote update --prune origin
 Cloning 2214a69c5c829c3d0eb15b78a8b543e0f5f4fd6c from cache
Executing command (CWD): git clone --no-checkout 'https://github.com/doctrine/DoctrineModule.git' '/branch-test/vendor/doctrine/doctrine-module' --dissociate --reference '/home/oprokidnev/.composer/cache/vcs/https---github.com-doctrine-DoctrineModule.git/' && cd '/branch-test/vendor/doctrine/doctrine-module' && git remote add composer 'https://github.com/doctrine/DoctrineModule.git' && git fetch composer
Executing command (/branch-test/vendor/doctrine/doctrine-module): git remote set-url --push origin 'git@github.com:doctrine/DoctrineModule.git'
Executing command (/branch-test/vendor/doctrine/doctrine-module): git branch -r
Executing command (/branch-test/vendor/doctrine/doctrine-module): git checkout '1.0' --
Executing command (/branch-test/vendor/doctrine/doctrine-module): git checkout -B '1.0' 'composer/1.0' --
Executing command (/branch-test/vendor/doctrine/doctrine-module): git checkout '2214a69c5c829c3d0eb15b78a8b543e0f5f4fd6c' -- && git reset --hard '2214a69c5c829c3d0eb15b78a8b543e0f5f4fd6c' --
    REASON: Required by the root package: Install command rule (install doctrine/doctrine-module 1.0.x-dev)
```

As you see composer matched with a proper branch name and it's latest commit. But a branch name has an error.

```
oprokidnev@oprokidnev-webmotor:~/branch-test/vendor/doctrine/doctrine-module((2214a69...))$ git status 
HEAD detached at 2214a69
oprokidnev@oprokidnev-webmotor:~/branch-test/doctrine/doctrine-module((2214a69...))$ git branch -a
* (HEAD отделён на 2214a69)
  master
  remotes/composer/...
  remotes/origin/...
```

**Comment by Dreimus** [comment] 2017-04-25 08:40
Can you try to set in your composer.json config section :

"preferred-install": { 
    "flole/project":"source"
},
It has checked out the right version if source is specified for me.
I think that the problem is coming from gitlab archive download from commit. Composer might not use the right commit revision number.

**Comment by Seldaek** [comment] 2017-12-19 10:33
Auto-closing this as it's marked as support request and has not received any update in a long time.

**Closed by Seldaek** 2017-12-19 10:33 UTC
Labels: Support
