### ISSUE TITLE
[RFC] New link command

### ISSUE THREAD

**Issue by ro0NL** [composer/composer#6940] opened 2017-12-26 10:38 UTC
Hi,

Inspired by a new contributing tool from Symfony, called  [`link`](https://github.com/symfony/symfony/blob/master/link)  (https://github.com/symfony/symfony/pull/24746), i created a generic composer plugin from that.

https://github.com/ro0NL/composer-link

So given `/src` + `/project` and we run `composer link ../project` from **`/src`**, it will link dependencies in `/project` to `/src` for mathing packages (i.e. found in /src and used in /project).

Could this make it as a core command?

cc @dunglas

**Comment by dunglas** [comment] 2017-12-26 10:49
Btw, NPM and Yarn have a similar command.

**Comment by ostrolucky** [comment] 2017-12-28 22:57
Maybe such thing could be used to solve reverse problem too. https://github.com/composer/composer/issues/601 is second most upvoted issue

**Comment by ro0NL** [comment] 2017-12-29 10:22
@ostrolucky you mean running `composer link /path/to/global/src` on the project side right?

I guess both ways work out.. perhaps even prefer that direction?

**Comment by nicolas-grekas** [comment] 2017-12-31 10:28
I think this can be made to work both ways automatically, isn't it? Would be he best if confirmed!

**Comment by Seldaek** [comment] 2020-09-11 15:17
Closing as duplicate of #601

**Closed by Seldaek** 2020-09-11 15:17 UTC
