### ISSUE TITLE
Implement --allow-insecure-registry option for create-project and install commands

### ISSUE THREAD

**Issue by prometheas** [composer/composer#5121] opened 2016-03-27 21:16 UTC
I know it's possible to use `composer config -g secure-http false`, but that's too easy to set and forget. I believe it's worth supporting a `--allow-insecure-registry` option for `create-project` and `install` so that the permissive setting can be directed at very specific commands.

Example:

```sh
$ composer install my/project --allow-insecure-registry http://packagist.example.com
```

Note: this idea is borrowed from the `docker-machine` command.

**Comment by Seldaek** [comment] 2016-04-02 13:50
Closing as duplicate of #5008

**Comment by prometheas** [comment] 2016-04-02 16:07
The other ticket is a conversation about obstacles, this is a specific recommendation (which may be rejected for any number of reasons, obviously), which seeks to solve for the problem discussed there.

Trouble is, setting `secure-http` to `false` in the `config` key of a `composer.json` file aids in dependency installation, but composer declines to even hit an insecure registry URL to begin with on a `create-project` run.

**Comment by Seldaek** [comment] 2016-04-02 16:10
OK, for `create-project` we might need a --no-secure-http flag or something. 

The other issue mentioned a whitelist approach which if implemented could also be reflected in a `--allow-insecure <url>` flag, but it remains to be seen if that's a good idea. I still haven't seen a convincing implementation from a security standpoint that can give your more guarantees than simply turning the flag off globally (which btw does not *remove* https, most of our URLs are still going to be https as most people run with the flag enabled, it just allows http URLs on top of it).

**Comment by prometheas** [comment] 2016-04-02 16:22
What I'm averse to about a general flag is that it's a bit too "mask it all"… having to explicitly identify which registry is insecure each time you craft your composer command keeps user focus on specific insecure registries.

I might also therefore be inclined to suggest that this is actually a replacement for `--repository-url`, so perhaps it'd better be named `--insecure-repository-url`.

Supplying an http URL to `--repository-url` gets a non-zero exit status, whilst warnings become redundant when the user is forced to use the `--insecure-registry-url` option.

It's a little passive-aggressive, I'll admit, but seems to send all the important signals :)

**Comment by Seldaek** [comment] 2016-04-21 20:11
Fixed by https://github.com/composer/composer/commit/f13e0f975f3b513b5bbe5f04f5eef05923b39843

**Closed by Seldaek** 2016-04-21 20:11 UTC
Labels: Feature
