### ISSUE TITLE
Link to binary broken, when using "path" repository (Windows)

### ISSUE THREAD

**Issue by a-r-m-i-n** [composer/composer#7256] opened 2018-04-12 09:40 UTC
This is my global composer.json (in home dir):

```
{
    "repositories": [
        {
            "type": "path",
            "url": "C:/Dev/vendor/project/"
        }
    ],
    "require": {
        "vendor/project": "dev-master"
    }
}
```

The project contains a binary file with the following content:

```
#!/usr/bin/env php
<?php

if (file_exists(__DIR__ . '/vendor/autoload.php')) {
    require_once(__DIR__ . '/vendor/autoload.php');
} else if (file_exists(__DIR__ . '/../autoload.php')) {
    require_once(__DIR__ . '/../autoload.php');
} else if (file_exists(__DIR__ . '/../../autoload.php')) {
    require_once(__DIR__ . '/../../autoload.php');
} else {
    throw new \RuntimeException('Composer autoloading information not found!');
}

$application = new \Vendor\Project\Application();
$application->run();
```

When require this package globally, it creates the binary in vendor/bin folder. But when I call it (I've added the folder to PATH), I get this error:

> Could not open input file: C:\Users\me\scoop\apps\composer\current\home\vendor\bin\/../../../../../../../../Dev/vendor/project/mybinary

Actually the path is almost correct, when I add another `../` segment manually in `vendor/bin/mybinary.bat`, the binary works. 

So is it a bug in composer or a misconfiguration?

When I change type **path** in repository type to **vcs** it also works.

Thanks

**Comment by Seldaek** [comment] 2018-04-12 16:52
Seems like could be a bug due to the symlink, one would have to investigate this further.

**Comment by lonesoft** [comment] 2018-05-21 18:17
Hello,
Seems like the issues #7025 and related #4955 are re-emerging.
On my windows 10 (v 1803 x64) with PHP 7.2.5 and composer 1.6.5.
Reading on the previous posts, it seems to me that any attempt to "guess" if a folder is as junction is bound to fail sooner or later (version of O/S and/or php)
I have two suggestion to offer:
* use realpath()
* set somewhere else (composer.lock ?) if a junction has been created

Thank you for your work!

**Comment by lonesoft** [comment] 2018-05-22 11:19
Hello,
sure enough, I clone composer on my machine and run the tests. here are my results:

> There were 2 failures:
> 1) Composer\Test\AllFunctionalTest::testBuildPhar
> D:\Projects\First4Figures\002\local\composer\tests\Composer\Test\AllFunctionalTest.php:93
> 2) Composer\Test\Util\FilesystemTest::testJunctions
> Failed asserting that false is true.
> D:\Projects\First4Figures\002\local\composer\tests\Composer\Test\Util\FilesystemTest.php:303

Hope this helps.
Thank you

**Comment by Seldaek** [comment] 2022-05-15 11:46
Closing as Composer 2.2 overhauled the binary handling quite a bit. If you can still reproduce it with Composer 2.2 or above please let me know.

**Closed by Seldaek** 2022-05-15 11:46 UTC
Labels: Bug
