### ISSUE TITLE
ComposerRepository: Undefined $data

### ISSUE THREAD

**Issue by starcevpro** [composer/composer#9002] opened 2020-06-21 22:05 UTC
```
Loading composer repositories with package information
Updating dependencies


  [LogicException]
  ComposerRepository: Undefined $data. Please report at https://github.com/composer/composer/issues/new.  
```

Host Reg.ru
Panel Plesk

**Comment by dbrumann** [comment] 2020-06-22 06:29
More info would be helpful. Could you show your `composer.json`? What composer command did you run? What changes have you made to your `composer.json` or what (successful) commands did you run before the error occcured?

**Comment by Seldaek** [comment] 2020-06-29 11:21
Any more info here? Otherwise will have to close as we can not reproduce this as such..

**Comment by GrahamCampbell** [comment] 2020-07-03 18:35
I'm guessing this error is coming from `ComposerRepository::fetchFile`

**Comment by GrahamCampbell** [comment] 2020-07-03 18:35
@starcevpro Please follow the issue template, otherwise nobody can help you.

**Comment by klaaskox** [comment] 2020-10-28 19:17
I ran into the same problem when running composer update
Any idea what might cause this?
my package.json:
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "axios": "^0.19",
        "cross-env": "^7.0",
        "laravel-mix": "^5.0.1",
        "lodash": "^4.17.19",
        "resolve-url-loader": "^3.1.0",
        "vue-template-compiler": "^2.6.12"
    },
    "dependencies": {
        "vue": "^2.6.12",
        "vue-router": "^3.4.7"
    }
}
```

**Comment by Seldaek** [comment] 2020-10-28 21:04
@klaaskox I can't reproduce this.. so you'll need to give more details. If you can reproduce at least please  run it again with `-vvv` and post the full output.

**Comment by klaaskox** [comment] 2020-10-28 21:19
@Seldaek, thanks for your reply. I ran into the same problem. The problem came from `ComposerRepository::fetchFile`.
I think I fixed it by using another php version (7.3). Problem solved

**Comment by Seldaek** [comment] 2020-10-28 21:35
I know where the exception is thrown, but if you give me what I asked for maybe it'll hint at how it failed, which is what I do not understand.

Switching PHP version should not fix anything here.

**Comment by klaaskox** [comment] 2020-10-28 22:21
This is my composer.json:

```
{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.3",
        "fideloper/proxy": "^4.2",
        "fruitcake/laravel-cors": "^2.0",
        "guzzlehttp/guzzle": "^7.0.1",
        "laravel/framework": "^8.0",
        "laravel/tinker": "^2.0"
    },
    "require-dev": {
        "facade/ignition": "^2.3.6",
        "fzaninotto/faker": "^1.9.1",
        "mockery/mockery": "^1.3.1",
        "nunomaduro/collision": "^5.0",
        "phpunit/phpunit": "^9.3"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
```

I checked again, and the error shows up when I run `php composer.phar update`

This is the result when using `-vvv`:

```
-sh-4.1$ php composer.phar update -vvv
Reading ./composer.json
Loading config file ./composer.json
Checked CA file /etc/pki/tls/certs/ca-bundle.crt: valid
Executing command (/var/www/vhosts/mydomain.nl/testcomposer): git branch -a --no-color --no-abbrev -v
Executing command (/var/www/vhosts/mydomain.nl/testcomposer): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/var/www/vhosts/mydomain.nl/testcomposer): git log --pretty="%H" -n1 HEAD
Executing command (/var/www/vhosts/mydomain.nl/testcomposer): hg branch
Executing command (/var/www/vhosts/mydomain.nl/testcomposer): fossil branch list
Executing command (/var/www/vhosts/mydomain.nl/testcomposer): fossil tag list
Executing command (/var/www/vhosts/mydomain.nl/testcomposer): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /var/www/vhosts/mydomain.nl/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Running 2.0.3 (2020-10-28 15:50:55) with PHP 5.3.3 on Linux / 2.6.32-042stab133.2
Loading composer repositories with package information
Updating dependencies
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /var/www/vhosts/mydomain.nl/.composer/cache/repo/https---repo.packagist.org/packages.json into cache


  [LogicException]
  ComposerRepository: Undefined $data. Please report at https://github.com/composer/composer/issues/new.


Exception trace:
 () at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Repository/ComposerRepository.php:1150
 Composer\Repository\ComposerRepository->fetchFile() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Repository/ComposerRepository.php:833
 Composer\Repository\ComposerRepository->loadRootServerFile() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Repository/ComposerRepository.php:524
 Composer\Repository\ComposerRepository->hasProviders() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Repository/ComposerRepository.php:346
 Composer\Repository\ComposerRepository->loadPackages() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/DependencyResolver/PoolBuilder.php:319
 Composer\DependencyResolver\PoolBuilder->loadPackagesMarkedForLoading() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/DependencyResolver/PoolBuilder.php:185
 Composer\DependencyResolver\PoolBuilder->buildPool() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Repository/RepositorySet.php:233
 Composer\Repository\RepositorySet->createPool() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Installer.php:412
 Composer\Installer->doUpdate() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Installer.php:251
 Composer\Installer->run() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Command/UpdateCommand.php:230
 Composer\Command\UpdateCommand->execute() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/vendor/symfony/console/Command/Command.php:245
 Symfony\Component\Console\Command\Command->run() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/vendor/symfony/console/Application.php:835
 Symfony\Component\Console\Application->doRunCommand() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/vendor/symfony/console/Application.php:185
 Symfony\Component\Console\Application->doRun() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Console/Application.php:309
 Composer\Console\Application->doRun() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/vendor/symfony/console/Application.php:117
 Symfony\Component\Console\Application->run() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/src/Composer/Console/Application.php:121
 Composer\Console\Application->run() at phar:///var/www/vhosts/mydomain.nl/testcomposer/composer.phar/bin/composer:63
 require() at /var/www/vhosts/mydomain.nl/testcomposer/composer.phar:24
```



When I run `/opt/plesk/php/7.3/bin/php composer.phar update` everything works fine.

**Comment by Seldaek** [comment] 2020-10-29 08:59
Ah that's interesting, so it fails with php 5.3.3.. I unfortunately can't repro this locally, but maybe you can tell me a few more things:

if you run it again with the php which fails, can you then check what is in `/var/www/vhosts/mydomain.nl/.composer/cache/repo/https---repo.packagist.org/packages.json`? Is it empty? 

Can you also show the output of `php composer.phar diagnose`?

**Comment by klaaskox** [comment] 2020-10-29 19:23
`/var/www/vhosts/mydomain.nl/.composer/cache/repo/https---repo.packagist.org/packages.json` is empty indeed.

`php composer.phar diagnose` output:

```
-sh-4.1$ php composer.phar diagnose
Checking composer.json: OK
Checking platform settings: Your PHP (5.3.3) is quite old, upgrading to PHP 5.3.4 or higher is recommended.
 Composer works with 5.3.2+ for most people, but there might be edge case issues.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: FAIL
[ErrorException] Invalid argument supplied for foreach()
Composer version: 2.0.3
PHP version: 5.3.3
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
cURL version: 7.19.7 libz 1.2.3 ssl NSS/3.44
zip extension: OK
```

**Comment by Seldaek** [comment] 2020-10-29 19:30
Ok so it seems like something is deeply broken with the http handling, as it seems to return an empty 200 response.

If possible, can you run your php 5.3 *without* the curl extension to force it to use the php streams fallback? I'm hoping this would work.. if so maybe we can use that as fallback in case curl fails on older PHP versions.

**Comment by klaaskox** [comment] 2020-10-29 20:25
I disabled curl:

```
-sh-4.1$ php composer.phar diagnose
Checking composer.json: OK
Checking platform settings: Your PHP (5.3.3) is quite old, upgrading to PHP 5.3.4 or higher is recommended.
 Composer works with 5.3.2+ for most people, but there might be edge case issues.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 2.0.3
PHP version: 5.3.3
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
cURL version: missing, using php streams fallback, which reduces performance
zip extension: OK
```

And then run `php composer.phar update`:

```
-sh-4.1$ php composer.phar update
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires php ^7.3 but your php version (5.3.3) does not satisfy that requirement.
  Problem 2
    - fideloper/proxy[4.2.0, ..., 4.4.1] require php >=5.4.0 -> your php version (5.3.3) does not satisfy that requirement.
    - Root composer.json requires fideloper/proxy ^4.2 -> satisfiable by fideloper/proxy[4.2.0, ..., 4.4.1].
```

**Comment by Seldaek** [comment] 2020-10-29 20:47
Ok great, thanks for your help here. Looks like a streams fallback if we detect this error state would work, but the question is how to detect it safely. I'm gonna have a go tomorrow checking content-length + status code + empty response perhaps, and disabling curl if something looks off.

**Comment by Seldaek** [comment] 2020-10-29 21:41
@klaaskox ok had time to do this now actually so can you please try again both composer diagnose and update *with* curl this time, but with latest snapshot (`composer self-update --snapshot`)? It should hopefully print a warning and then continue correctly.

**Comment by klaaskox** [comment] 2020-10-29 22:48
@Seldaek unfortunately I can't get the latest snapshot:

```
-sh-4.1$ composer self-update --snapshot


  [ErrorException]
  Invalid argument supplied for foreach()


self-update [-r|--rollback] [--clean-backups] [--no-progress] [--update-keys] [--stable] [--preview] [--snapshot] [--1] [--2] [--set-channel-only] [--] [<version>]

```

**Comment by Seldaek** [comment] 2020-10-29 22:50
Ah you'll need to run the self-update with php 7.3 I guess

**Comment by Seldaek** [comment] 2020-10-30 22:05
2.0.4 is out now with this fix so closing, would still be glad if someone can confirm it works for them :)

**Closed by Seldaek** 2020-10-30 22:05 UTC
Labels: Bug

**Comment by seasoftjapan** [comment] 2020-12-25 09:04
```
$ php -v
PHP 5.3.3 (cli) (built: Nov  1 2019 12:28:08)
Copyright (c) 1997-2010 The PHP Group
Zend Engine v2.3.0, Copyright (c) 1998-2010 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
$ wget https://getcomposer.org/composer.phar
$ php composer.phar diagnose
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: Your PHP (5.3.3) is quite old, upgrading to PHP 5.3.4 or higher is recommended.
 Composer works with 5.3.2+ for most people, but there might be edge case issues.

Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
[ErrorException] Invalid argument supplied for foreach()
Composer version: 2.0-dev+bc31351b5bbbc5d33e916c1e54df3a291c0909b5
PHP version: 5.3.3
OpenSSL version: OpenSSL 1.0.1e-fips 11 Feb 2013
cURL version: 7.19.7 libz 1.2.3 ssl NSS/3.44
zip: extension present, unzip present
$ php composer.phar update
Loading composer repositories with package information


  [LogicException]
  ComposerRepository: Undefined $data. Please report at https://github.com/composer/composer/issues/new.


update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```

**Comment by mitchellmorris** [comment] 2021-01-03 20:42
```
[root@596ceba5f5bb html]# composer update
Loading composer repositories with package information

                                                                                                          
  [LogicException]                                                                                        
  ComposerRepository: Undefined $data. Please report at https://github.com/composer/composer/issues/new.  
                                                                                                          

update [--with WITH] [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--lock] [--no-install] [--no-autoloader] [--no-scripts] [--no-suggest] [--no-progress] [-w|--with-dependencies] [-W|--with-all-dependencies] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [-i|--interactive] [--root-reqs] [--] [<packages>]...
```
