### ISSUE TITLE
Leftover dependency after upgrading package

### ISSUE THREAD

**Issue by carlosvini** [composer/composer#8633] opened 2020-02-20 15:23 UTC
I noticed that after upgrading Codeception from 2.3 to 4.1, the facebook/webdriver package was still listed in composer.lock. I expected that since Codeception 4.1 doesn't require it, it would be removed from the lock.

```
Composer version 1.9.2 2020-01-14 16:30:31
```

My `composer.json`:

```json
{
    "name": "test/composer",
    "description": "test composer",
    "require": {
        "laravel/framework": "5.7.*"
    },
    "require-dev": {
        "codeception/codeception": "^2.3"
    }
}
```

When I run this command:

```
composer install  # to create the first lock containing facebook/webdriver
composer require --dev codeception/codeception:^4.1
```

When I type "composer why facebook/webdriver", it says:

```
There is no installed package depending on "facebook/webdriver"
```

When I type "composer show facebook/webdriver", it says:

```
name     : facebook/webdriver
descrip. : A PHP client for Selenium WebDriver. Previously facebook/webdriver.
...
```

When I type "composer remove facebook/webdriver", it says:

```
facebook/webdriver is not required in your composer.json and has not been removed
```

But it proceeds and removes it, which is good, but I had to explicitly ask for it and the message is confusing.

**Comment by stof** [comment] 2020-02-20 17:25
well, that's probably because when you updated `codeception`, you did not allow composer to modify existing packages being dependencies of this package, and so it kept it requested at its locked version.

@naderman maybe that's something that could be solved more easily in v2 (ensuring that a `remove` command does not keep unused dependencies around).

**Comment by carlosvini** [comment] 2020-02-20 17:34
So I just had to run it with some flags and it would work? 
```
composer require --dev codeception/codeception:^4.1 --update-with-dependencies
```

**Comment by stof** [comment] 2020-02-20 17:43
I think yes.

**Comment by carlosvini** [comment] 2020-02-20 17:55
Tested it and it worked.

**Comment by stof** [comment] 2020-02-20 18:35
I would keep the issue opened, because that's something that should be fixed automatically for the case of unneeded packages IMO

**Comment by ABGEO07** [comment] 2020-02-21 18:56
@stof I would start working on this issue if you said what and when we need to automate.

**Comment by Seldaek** [comment] 2020-02-28 22:03
If anyone wants to move this forward, try to reproduce it on the 2.0 branch. If you can't then it's fixed already and can be closed.

**Comment by naderman** [comment] 2020-09-17 10:23
Can someone verify if the PR https://github.com/composer/composer/pull/9223 fixes this?

**Comment by Seldaek** [comment] 2020-10-16 10:33
Fixed by https://github.com/composer/composer/pull/9223

**Closed by Seldaek** 2020-10-16 10:33 UTC
Labels: Refactoring, Solver
