### ISSUE TITLE
Composer is uninstalling my dev-master packages every 2 runs.

### ISSUE THREAD

**Issue by RubenHarms** [composer/composer#7304] opened 2018-05-03 06:48 UTC
My `composer.json`:

```json
{
  "name": "symfony/framework-standard-edition",
  "description": "The \"Symfony Standard Edition\" distribution",
  "require": {
    "php": ">=5.5.9",
    "symfony/symfony": "3.2.*",
    "doctrine/orm": "^2.5",
    "doctrine/doctrine-bundle": "^1.6",
    "doctrine/doctrine-cache-bundle": "^1.2",
    "twig/extensions": "~1.0",
    "symfony/assetic-bundle": "dev-master",
    "symfony/swiftmailer-bundle": "^2.3",
    "symfony/monolog-bundle": "^2.8",
    "sensio/distribution-bundle": "^5.0",
    "sensio/framework-extra-bundle": "^3.0.2",
    "incenteev/composer-parameter-handler": "^2.0",
    "stof/doctrine-extensions-bundle": "1.2.2",
    "hwi/oauth-bundle": "~0.5",
    "knplabs/knp-menu-bundle": "~2.0",
    "liip/imagine-bundle": "~1.2",
    "hootmarketing/affiliate-bundle": "dev-master",
    "evence/grid-bundle": "dev-master",
    "evence/rest-api-bundle": "dev-master",
    "evence/core-bundle": "dev-master",
    "evence/media-bundle": "dev-master",
    "liip/theme-bundle": "1.4.4",
    "friendsofsymfony/jsrouting-bundle": "1.6.2",
    "mopa/bootstrap-bundle": "dev-master",
    "sonata-project/seo-bundle": "2.2.0",
    "willdurand/js-translation-bundle": "2.6.4",
    "gregwar/image-bundle": "2.1.1",
    "presta/sitemap-bundle": "~1.5",
    "eko/feedbundle": "1.2.2",
    "evence/optin-bundle": "dev-master",
    "guzzlehttp/guzzle": "~5.2",
    "surfnet/messagebird-api-client-bundle": "dev-develop",
    "facebook/php-sdk-v4": "dev-4.1-dev",
    "digitick/sepa-xml": "dev-master",
    "happyr/linkedin-api-client": "^0.6.1",
    "maxmind/geoip": "dev-master",
    "wa72/htmlpagedom": "dev-master",
    "jaybizzle/crawler-detect": "1.*",
    "gibilogic/tinymce-bundle": "~1.3.2",
    "evence/site-bundle": "dev-master",
    "evence/sync-bundle": "dev-master",
    "evence/soft-deleteable-extension-bundle": "dev-master",
    "egulias/email-validator": "~1.2",
    "spipu/html2pdf": "dev-master",
    "beberlei/DoctrineExtensions": "^1.0",
    "tinymce/tinymce": "4.5.7",
    "evence/relationship-inspector-client-bundle": "dev-master"
  },
  "repositories": [
    {
      "type": "vcs",
      "url": "git@git.e-vence.nl:E-vence/EvenceCore.git"
    },
    {
      "type": "vcs",
      "url": "git@git.e-vence.nl:E-vence/EvenceSyncBundle.git"
    },
  {
      "type": "vcs",
      "url": "git@git.e-vence.nl:E-vence/EvenceMediaBundle.git"
    },
    {
      "type": "vcs",
      "url": "git@git.e-vence.nl:E-vence/EvenceRestApiBundle.git"
    },
    {
      "type": "vcs",
      "url": "git@git.e-vence.nl:E-vence/SolutionCodeMirrorBundle.git"
    },
    {
      "type": "vcs",
      "url": "git@git.e-vence.nl:E-vence/OptinBundle.git"
    },
    {
      "type": "vcs",
      "url": "https://github.com/RubenHarms/messagebird-api-client-bundle"
    },
    {
      "type": "vcs",
      "url": "git@git.e-vence.nl:E-vence/EvenceSiteBundle.git"
    },
    {
      "type": "vcs",
      "url": "git@git.e-vence.nl:HootMarketing/HootMarketingAffiliateBundle.git"
    },
    {
      "type": "vcs",
      "url": "git@git.e-vence.nl:E-vence/EvenceRelationshipClientBundle.git"
    }

  ],
  "require-dev": {
    "sensio/generator-bundle": "^3.0",
    "symfony/phpunit-bridge": "^3.0",
    "doctrine/doctrine-fixtures-bundle": "^2.3"
  },
  "scripts": {
    "post-install-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
      "Stfalcon\\Bundle\\TinymceBundle\\Composer\\ScriptHandler::createSymlink"
    ],
    "post-update-cmd": [
      "Incenteev\\ParameterHandler\\ScriptHandler::buildParameters",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::buildBootstrap",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::clearCache",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installAssets",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::installRequirementsFile",
      "Sensio\\Bundle\\DistributionBundle\\Composer\\ScriptHandler::removeSymfonyStandardFiles",
      "Stfalcon\\Bundle\\TinymceBundle\\Composer\\ScriptHandler::createSymlink"
    ]
  },
  "autoload": {
    "psr-4": {
      "": "src/"
    },
    "classmap": [
      "app/AppKernel.php",
      "app/AppCache.php"
    ]
  },
  "autoload-dev": {
    "psr-4": {
      "Tests\\": "tests/"
    }
  },
  "config": {
    "platform": {
      "php": "7.0"
    }
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-bin-dir": "bin",
    "symfony-var-dir": "var",
    "symfony-web-dir": "web",
    "symfony-tests-dir": "tests",
    "symfony-assets-install": "relative",
    "incenteev-parameters": {
      "file": "app/config/parameters.yml"
    },
    "branch-alias": {
      "dev-master": "3.0-dev"
    }
  },
  "license": "MIT",
  "type": "project"
}
```

Output of `composer diagnose`:

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
require.stof/doctrine-extensions-bundle : exact version constraints (1.2.2) should be avoided if the package follows semantic versioning
require.hootmarketing/affiliate-bundle : unbound version constraints (dev-master) should be avoided
require.evence/grid-bundle : unbound version constraints (dev-master) should be avoided
require.evence/rest-api-bundle : unbound version constraints (dev-master) should be avoided
require.evence/core-bundle : unbound version constraints (dev-master) should be avoided
require.evence/media-bundle : unbound version constraints (dev-master) should be avoided
require.liip/theme-bundle : exact version constraints (1.4.4) should be avoided if the package follows semantic versioning
require.friendsofsymfony/jsrouting-bundle : exact version constraints (1.6.2) should be avoided if the package follows semantic versioning
require.mopa/bootstrap-bundle : unbound version constraints (dev-master) should be avoided
require.sonata-project/seo-bundle : exact version constraints (2.2.0) should be avoided if the package follows semantic versioning
require.willdurand/js-translation-bundle : exact version constraints (2.6.4) should be avoided if the package follows semantic versioning
require.gregwar/image-bundle : exact version constraints (2.1.1) should be avoided if the package follows semantic versioning
require.eko/feedbundle : exact version constraints (1.2.2) should be avoided if the package follows semantic versioning
require.evence/optin-bundle : unbound version constraints (dev-master) should be avoided
require.digitick/sepa-xml : unbound version constraints (dev-master) should be avoided
require.maxmind/geoip : unbound version constraints (dev-master) should be avoided
require.wa72/htmlpagedom : unbound version constraints (dev-master) should be avoided
require.evence/site-bundle : unbound version constraints (dev-master) should be avoided
require.evence/sync-bundle : unbound version constraints (dev-master) should be avoided
require.evence/soft-deleteable-extension-bundle : unbound version constraints (dev-master) should be avoided
require.spipu/html2pdf : unbound version constraints (dev-master) should be avoided
require.tinymce/tinymce : exact version constraints (4.5.7) should be avoided if the package follows semantic versioning
require.evence/relationship-inspector-client-bundle : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: WARNING
You are not running the latest stable version, run `composer self-update` to update (1.6.3 => 1.6.4)
Composer version: 1.6.4
PHP version: 7.1.15-0ubuntu0.17.10.1
PHP binary path: /usr/bin/php7.1
```

When I run this command:

```composer update```

I get the following  important output in -vvv mode:

```
package operations: 0 installs, 0 updates, 0 removals
  - Marking mopa/bootstrap-bundle (3.x-dev d30a6d8) as uninstalled, alias of mopa/bootstrap-bundle (dev-master d30a6d8)
  - Marking evence/sync-bundle (0.1.x-dev 5d67399) as uninstalled, alias of evence/sync-bundle (dev-master 5d67399)
  - Marking evence/soft-deleteable-extension-bundle (0.1.x-dev ba66dcf) as uninstalled, alias of evence/soft-deleteable-extension-bundle (dev-master ba66dcf)
  - Marking evence/site-bundle (0.1.x-dev de367fd) as uninstalled, alias of evence/site-bundle (dev-master de367fd)
  - Marking evence/rest-api-bundle (0.1.x-dev aafd725) as uninstalled, alias of evence/rest-api-bundle (dev-master aafd725)
  - Marking evence/relationship-inspector-client-bundle (0.1.x-dev 93dc494) as uninstalled, alias of evence/relationship-inspector-client-bundle (dev-master 93dc494)
  - Marking evence/optin-bundle (0.1.x-dev 3b1656b) as uninstalled, alias of evence/optin-bundle (dev-master 3b1656b)
  - Marking evence/media-bundle (0.1.x-dev 276fa44) as uninstalled, alias of evence/media-bundle (dev-master 276fa44)
  - Marking evence/grid-bundle (0.1.x-dev d2ca118) as uninstalled, alias of evence/grid-bundle (dev-master d2ca118)
  - Marking evence/core-bundle (0.1.x-dev 63d435c) as uninstalled, alias of evence/core-bundle (dev-master 63d435c)
```

Problem is:
Most of my dev-master packages are uninstalled the first run of "composer update". After a re-run they will be installed again. The next time a run it again, the dev-packages will be uninstalled again. This loop is happening again and again. 

In the previous version of composer there are no troubles at all.

**Comment by jvasseur** [comment] 2018-05-03 06:51
This is a duplicate of #7268

**Closed** 2018-05-03 06:58 UTC
