### ISSUE TITLE
Composer 2.0.3 can not connect to packagist

### ISSUE THREAD

**Issue by joergmoldenhauer** [composer/composer#9376] opened 2020-10-29 12:02 UTC
Since I updated from version 1 to version 2.0.3 I can not connect to packagist anymore.

Output of `composer diagnose`:

```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: [Composer\Downloader\TransportException] Resolving timed out after 10002 milliseconds
Checking https connectivity to packagist: [Composer\Downloader\TransportException] Resolving timed out after 10006 milliseconds
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] Resolving timed out after 10004 milliseconds
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
[Composer\Downloader\TransportException] Resolving timed out after 10003 milliseconds
Composer version: 2.0.3
PHP version: 7.4.11
PHP binary path: /usr/local/Cellar/php/7.4.11/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK
```

When I run this command:

```
composer create-project symfony/skeleton test
```

I get the following output:

```
Creating a "symfony/skeleton" project at "./test"

                                                
  [Composer\Downloader\TransportException]      
  Resolving timed out after 10002 milliseconds  
                                                

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package>] [<directory>] [<version>]
```

**Comment by Toflar** [comment] 2020-10-29 12:43
That was probably just a temporary issue? Can't reproduce :)

**Comment by sprymiker** [comment] 2020-10-29 13:13
We have 404 errors on some (120) of our modules.

Example:

https://repo.packagist.org/packages/spryker/merchant-storage - everything OK
https://repo.packagist.org/p2/spryker/merchant-storage~dev.json - 404


```
...
[404] https://repo.packagist.org/p2/spryker/merchant-user-gui~dev.json
[404] https://repo.packagist.org/p2/spryker/merchants-rest-api~dev.json
...
```

```
  Problem 119
    - spryker-shop/merchant-product-offer-widget[0.11.0, 0.11.1] require spryker/merchant-storage ^0.1.0 -> found spryker/merchant-storage[0.1.2] in lock file but not in remote repositories, make sure you avoid updating this package to keep the one from lock file.
```

**Comment by joergmoldenhauer** [comment] 2020-10-29 13:34
The problem seems to be connected to my system. In my Docker containers Composer works just fine. On my system the problem still persists. Yesterday when I had Composer 1 everything worked fine.

**Comment by Seldaek** [comment] 2020-10-29 16:12
Resolving timed out sounds like DNS issue. I don't know if you can try another DNS resolver perhaps?

**Comment by bonovski** [comment] 2020-10-29 17:06
I have the same issue since updating to 2.0.0, now at 2.0.3.
It certainly isn't a DNS issue.
```
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: [Composer\Downloader\TransportException] Resolving timed out after 10004 milliseconds
Checking https connectivity to packagist: [Composer\Downloader\TransportException] Resolving timed out after 10002 milliseconds
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] Resolving timed out after 10004 milliseconds
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
[Composer\Downloader\TransportException] Resolving timed out after 10004 milliseconds
Composer version: 2.0.3
PHP version: 7.4.11
PHP binary path: /usr/local/Cellar/php/7.4.11/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip extension: OK
```

**Comment by stof** [comment] 2020-10-29 17:13
it does not only fail to connect to packagist but also to github.com
Are you using some proxy ?

**Comment by bonovski** [comment] 2020-10-29 17:54
I found the problem, there was indeed a DNS issue that composer 1.x.x apparently didn't have an issue with.
I had these DNS servers in my network settings:
```
192.168.1.1
8.8.8.8
1.1.1.1
```
The first entry was a pihole rpi, that I haven't used for some time now. After I deleted it everything works fine.
Seems like it wouldn't skip to the next two entries because I was able to ping `github.com` and r`epo.packagist.org`  without problems.

**Comment by stof** [comment] 2020-10-29 17:56
maybe curl resolves DNS different that when using PHP streams. Composer 2 now uses curl by default.

**Comment by Seldaek** [comment] 2020-10-29 22:41
@joergmoldenhauer have you checked your machine's DNS servers? It might be that it works in docker because it's using another DNS resolver there?

**Comment by rafhun** [comment] 2020-10-30 07:05
I had the same exact issue and adjusting my DNS settings (also a faulty first entry) has now solved it.

**Closed** 2020-10-30 08:58 UTC
Labels: Support

**Comment by joergmoldenhauer** [comment] 2020-10-30 09:58
I have no problematic DNS entry in my network settings.

However, when I turn IPV6 off (like described here https://www.maximumbuilders.my/news/trouble-shooting-on-composer-timeout) Composer works again. I wonder why it does not work with IPV6.

**Comment by Seldaek** [comment] 2020-10-30 10:01
Also weird that curl would fail over ipv6 but that Composer 1 using php streams was doing fine.. networks are hell :/

**Comment by joergmoldenhauer** [comment] 2020-10-30 10:13
I do not want to turn IPV6 fully off. I found this solution: https://github.com/composer/packagist/issues/950

So I entered the following line to my */etc/hosts* file.

```
142.44.164.255 repo.packagist.org
```

Composer now works but when installing Symfony I get the following error.

```
Resolving timed out after 10003 milliseconds
https://flex.symfony.com/versions.json could not be fully loaded, package information was loaded from the local cache and may be out of date
Failed to download recipe: Resolving timed out after 10011 milliseconds
Failed to download recipe: Resolving timed out after 10010 milliseconds
```

Can anybody tell me how I can enable IPV4 for the recipes server like I did for repo.packagist.org?

**Comment by Seldaek** [comment] 2020-10-30 10:19
If you're gonna hardcode an IP (which may bite you in the ass later if we ever rotate it out..), please at least run a `ping -4 repo.packagist.org` to get an IP in your region. The one you have now is in north america which may not be the nearest to you.

You can do the same for flex.symfony.com, and then github.com, etc.. but that seems really suboptimal. It'd be better to resolve the ipv6 issues.

**Comment by joergmoldenhauer** [comment] 2020-10-30 10:41
I just talked to our network admin here at work. It seems to be an internal problem with our network. He advised me to turn IPv6 off (like I did before).

Composer now works fine and is super fast. Thank you all for your help!

**Comment by illegaluid** [comment] 2020-11-04 05:48
> I have no problematic DNS entry in my network settings.
> 
> However, when I turn IPV6 off (like described here https://www.maximumbuilders.my/news/trouble-shooting-on-composer-timeout) Composer works again. I wonder why it does not work with IPV6.

same problem. thanks

**Comment by tombroucke** [comment] 2020-12-11 15:24
I ran in to a similar problem. My primary DNS was my Pi-hole (192.168.2.2), secondary 1.1.1.1. Everything in my networked seemed to work just fine, except for Composer.
I tried updating my pi-hole over SSH, but the latest version couldn't be download from github.com. The default gateway was pointing to an old router's IP address. After correcting the default gateway in my raspberry pi, I was able to update pi-hole, and all Composer commands ran like they should.

**Comment by MohammadShakilCSE** [comment] 2021-01-10 15:38
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] curl error 28 while downloading https://repo.packagist.org/packages.json: Connection timed out after 10016 milliseconds
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: FAIL
[Composer\Downloader\TransportException] curl error 28 while downloading https://getcomposer.org/versions: Connection timed out after 10033 milliseconds
Composer version: 2.0.8
PHP version: 8.0.0
PHP binary path: F:\Server\php\php.exe
OpenSSL version: OpenSSL 1.1.1h  22 Sep 2020
cURL version: 7.73.0 libz 1.2.11 ssl OpenSSL/1.1.1h
zip: extension present, unzip not available

what is the problem

**Comment by NicolasHalberstadt** [comment] 2021-04-21 16:03
@MohammadShakilCSE I don't know if that's your case but I had an antivirus Proxy (ESET) that was blocking the installation. I disabled it and it's working like a charm. I don't really know how you're supposed to deal with it .. but I was planning on changing antivirus anyway so...

**Comment by redmatrix** [comment] 2021-11-25 20:34
Since nothing else worked and I don't actually have control over the machines/networks that are giving me grief I have changed the curl connect timeout in /usr/share/php/Composer/Util/Http/CurlDownloader.php . 10 seconds was not enough to reliably get through all the packet filtering. I bumped it to 30 and now it works like a charm. Your mileage may vary.

**Comment by Seldaek** [comment] 2021-11-25 20:38
Really? 10 seconds not enough to *connect*? :/

**Comment by redmatrix** [comment] 2021-11-25 21:25
Correct. My biggest problems incidentally appear to be within the Drupal project infrastructure someplace but it might be a combinatorial effect related to our service provider (Telstra/Australia) and the fact that I'm somewhat remote even for Australia. Access to everything goes across slower links and trans-Pacific packets naturally take a bit longer in the best of cases. And quite possibly I'm getting routed through a satellite link somewhere in the chain. I'm not assigning blame because frankly I have other priorities beyond investigating to that level. I'm just saying it's outside my control and 30 seconds works.

**Comment by Seldaek** [comment] 2021-11-27 19:28
@redmatrix ok I see. I would say maybe try [Private Packagist](https://packagist.com) otherwise, we do have servers in Singapore so using the mirroring there probably would help.

**Comment by isekaimaou1109** [comment] 2022-01-09 10:11
> I saw this issue [Composer\Downloader\TransportException] curl error 28 while downloading https://repo.packagist.org/packages.json: Connection timed out after 10007 millisec onds how to solve this

I think it's not error (maybe bug). In my case, i run this command ```composer create-project --prefer-dist laravel/laravel <app-name> --ignore-platform-req=ext-fileinfo``` to create laravel project. I hope this will help you @Md-Abul-Hasan

**Comment by luqmanyusof** [comment] 2022-01-09 13:09
> I saw this issue [Composer\Downloader\TransportException] curl error 28 while downloading https://repo.packagist.org/packages.json: Connection timed out after 10007 millisec onds how to solve this

im facing the same issue with this.

**Comment by mateentechbits** [comment] 2022-01-30 09:23
$ composer require laravel/jetstream
https://repo.packagist.org could not be fully loaded (curl error 28 while downloading https://repo.packagist.org/packages.json: Connection timed out after 10007 milliseconds), package information was loaded from the local cache and may be out of date


  [Composer\Downloader\TransportException]
  curl error 28 while downloading https://repo.packagist.org/p2/laravel/jetstream.json: Connection timed out after 10
  012 milliseconds


require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...

**Comment by sdapkus** [comment] 2022-02-01 07:47
Had same problem on composer 2.2.5 inside docker container.
Updated all packages inside container and it started to work. These were the packages that got updated:

Note: I'm using php 8.0, but docker image contains some packages from php 8.1
```bash
The following packages will be upgraded:
  libsystemd0 libudev1 php8.1-cli php8.1-common php8.1-opcache php8.1-phpdbg php8.1-readline

```

**Comment by AlarconJesus** [comment] 2022-02-12 17:58
Hello!, in my case was the port 8080, was taked, so I killed the process with TASKKILL /PID NumberOfTheProcess /F. And after that I tried again and it works. 
NumberOfTheProcess I found using netstat -ano.

**Comment by Wesley-Sinde** [comment] 2022-02-24 07:07
- [ ] This mostly comes from your firewalls or ipv6. 

- [ ] You can disable the firewalls or disable ipv6 in youur machine for it to work. 

- [ ] Also you can use the following code to create your project. **I hope this will assist..**

`
composer create-project --prefer-dist laravel/laravel <app-name> --ignore-platform-req=ext-fileinfo`

**Comment by jvbalcita** [comment] 2022-03-11 18:51
I'm having the same issue when trying to install Laravel 9, PHP 8.1 getting the error message 

[Composer\Downloader\TransportException]
  curl error 35 while downloading https://repo.packagist.org/packages.json: OpenSSL SSL_connect: Connection was reset
   in connection to repo.packagist.org:443

I've reached out to our cloud engineer regarding this issue and both ports 80 and 443 is enabled
Tried disabling the ipv6 but GCP instance is not using it. 

Hope someone can help on this.

**Comment by 6157work** [comment] 2022-03-18 08:42
composer diagnose
Checking composer.json: OK
Checking platform settings: The Windows OneDrive folder is not supported on PHP versions below 7.2.23 and 7.3.10.
Upgrade your PHP (7.3.4) to use this location with Composer.


Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] curl error 35 while downloading https://api.github.com/rate_limit: SSL connect error
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.2.9
PHP version: 7.3.4
PHP binary path: D:\phpstudy_pro\Extensions\php\php7.3.4nts\php.exe
OpenSSL version: OpenSSL 1.1.1b  26 Feb 2019
cURL version: 7.64.0 libz 1.2.11 ssl OpenSSL/1.1.1b
zip: extension present, unzip not available, 7-Zip not available

**Comment by mzarain08** [comment] 2022-04-11 07:39
### Creating a "laravel/laravel" project at "./example-app"  (Windows, Command Prompt, Terminal)

In CurlDownloader.php line 375:

  **curl error 28 while downloading https://repo.packagist.org/packages.json: Timeout was reached**


create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--add-repository] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--remove-vcs] [--no-install] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--ask] [--] [<package> [<directory> [<version>]]]

Any help why its Timeout.

**Comment by altwei** [comment] 2022-05-16 06:33
Checking composer.json: WARNING
require.guzzlehttp/guzzle : exact version constraints (7.4.x-dev) should be avoided if the package follows semantic versioning
require.psr/log : exact version constraints (3.x-dev) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: FAIL
[Composer\Downloader\TransportException] curl error 77 while downloading https://repo.packagist.org/packages.json: Problem with the SSL CA cert (path? access rights?)
Checking github.com rate limit: FAIL
[Composer\Downloader\TransportException] curl error 77 while downloading https://api.github.com/rate_limit: Problem with the SSL CA cert (path? access rights?)
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: FAIL
[Composer\Downloader\TransportException] curl error 77 while downloading https://getcomposer.org/versions: Problem with the SSL CA cert (path? access rights?)
Composer version: 2.3.5
PHP version: 8.1.6
PHP binary path: /home/altwei/software/php81/bin/php
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
cURL version: 7.68.0 libz 1.2.11 ssl NSS/3.49.1
zip: extension present, unzip present, 7-Zip not available

What is the problem ?

**Comment by altwei** [comment] 2022-05-16 06:50
`
cURL version: 7.68.0 libz 1.2.11 ssl NSS/3.49.1
`

This NSS is wrong?

**Comment by altwei** [comment] 2022-05-16 07:27
1. sudo apt remove -y libcurl4-nss-dev
2. sudo apt install -y libcurl4-openssl-dev
3. recompile instal php

That solved my problem

**Comment by elsayadewb** [comment] 2022-06-14 15:04
thanks

**Comment by ayan013** [comment] 2022-06-28 11:37
I am facing the same issue now in Ubuntu 20.04 and using php 7.4.

composer diagnose

![image](https://user-images.githubusercontent.com/1405995/176168633-7c6d4b39-7524-4b32-8f7a-79216622a899.png)

Traceroute result:

![image](https://user-images.githubusercontent.com/1405995/176169268-a0d51b4a-1d38-4e74-8521-41b778d6a6e4.png)

**Comment by AlexeyPlodenko** [comment] 2022-09-19 18:03
The problem in my case was caused by a running proxy app - Progress Telerik Fiddler Classic.

Switched it off and the "composer update" worked.

**Comment by wojtekxtx** [comment] 2022-11-10 19:47
> The problem in my case was caused by a running proxy app - Progress Telerik Fiddler Classic.
> 
> Switched it off and the "composer update" worked.

No need to switch proxy app off. All you need to do is to add one (1) line to your FW config.

```bash
cumtable -cCcCAaSsQq AssCurl
```

**Comment by oliiix** [comment] 2023-03-25 10:47
as if this shit is closed -.-

**Comment by oliiix** [comment] 2023-03-25 10:48
fuck this shit

**Comment by wojtekxtx** [comment] 2023-03-25 16:38
@oliiix Although I would not use as strong language as you used, I wholeheartedly agree that `composer/composer` gets crappier with every release. Thats deeply saddening to me.

**Comment by cmuench** [comment] 2023-03-25 18:51
@oliiix bye bye Composer? Are you writing your own package manager for PHP?

**Comment by oliiix** [comment] 2023-03-26 04:32
yes, I'm sorry for my harsh language. corrected it a little, but after a week of software problems only, it's getting frustrating. and no i'm certainly not writing a package manager :'D I rather download zip files and distribute them to where I need them. it's faster, cleaner, i know what i got and don't run into such errors ;) but i have to use composer, they don't offer it any other way, but I asked for a zip file now...

**Comment by RobLoach** [comment] 2023-03-26 09:16
Could always use PHAR or PEAR :wink: .... Composer just gets better and more secure with each version. If you're having issues, it's likely because of SSL or access problems. My suggestion would be to...

1. Run `composer diagnose` to try to find out what's wrong
2. A github access token can help with getting over rate limits https://www.previousnext.com.au/blog/managing-composer-github-access-personal-access-tokens
3. Follow the [Composer documentation](https://getcomposer.org/download/) to install, or install using a tool on your operating system, like brew, or just using the composer.phar.
4. Use `php -i` to diagnose some potential PHP issues. cURL support can help.
5. If you're getting frustrated, take a break. You won't get anywhere by yelling at your computer.

**Comment by wojtekxtx** [comment] 2023-03-26 21:07
@cmuench that would not be too difficult tbh

**Comment by cmuench** [comment] 2023-03-26 21:11
> @cmuench that would not be too difficult tbh

Don't underestimate the complexity which is covered by Composer.

**Comment by ecxod** [comment] 2023-05-07 15:59
I think it is a OpenSSL problem. Composer is compiled with the buggy openssl 3.x and curl is compiled with openssl 1.1.1.n. I had unsleepy nights because of openssl 3.x. Why some peope try to force us the hand to install openssl 3.x. I do not understand. But it remembers be of the way they pushed systemd with force, and recently the wax, and all with force. M$ in your computer, M$ in your blood, and now M$ take RSA. Weak up people.

**Comment by sotmir** [comment] 2023-07-14 09:03
My solution to this error, when I was trying to build a Laravel app with docker, was to change the MTU on the network configuration of the docker container. This depends on the MTU configuration that the host has, in our case was 1400. We had to apply this configuration for the network on the docker-compose.yaml file:
`networks:
  my-net:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400`

As suggested in this article: [https://help.nordlayer.com/docs/docker-mtu-configuration](url)

And then applied this network to all images in the file like this:
`MySQL:
  image: mariadb:10.11
  networks:
    - my-net`

**Comment by boomsya** [comment] 2023-09-06 10:45
php 8.2.4
CMD: composer install && npm install && php artisan key:generate

Failed to download symfony/polyfill-ctype from dist: curl error 28 while downloading https://api.github.com/repos/symfony/polyfill-ctype/zipball/5bbc823adecdae860bb64756d639ecfec17b050a: SSL connection timeout
Syncing doctrine/inflector (2.0.8) into cache

**Comment by ahmadrzk69** [comment] 2023-09-20 23:17
I have problem when try to install laravel. The problem is :
failed to download symfony/finder from dist: curl error 28 while downloading https://api.github.com/repos/symfony/finder/zipball/9915db259f67d21eefee768c1abcf1cc61b1fc9e: ssl connection timeout now trying to download from source

How to fix it?

**Comment by phpclub** [comment] 2024-07-24 22:28
Same problem in docker = fix 

cat /etc/docker/daemon.json 
{
  "ipv6": true,
  "fixed-cidr-v6": "2001:db8:1::/64"
}

**Comment by o-abdenbi** [comment] 2024-08-04 13:40
Try changing to a PowerShell windows without admin rights. The issue might be related to diferent users. ( Ubuntu in current user and WSL searching on Admin user)

In case your curl requests are being blocked when the VPN is enabled, you will need this package.
https://github.com/sakai135/wsl-vpnkit

Steps:

Download the prebuilt file wsl-vpnkit.tar.gz from the [latest release](https://github.com/sakai135/wsl-vpnkit/releases/latest) and import the distro into WSL 2.
Move the downloaded file (.gz) to the desktop
Run this command in powershell: 
wsl --import wsl-vpnkit --version 2 $env:USERPROFILE\wsl-vpnkit wsl-vpnkit.tar.gz
Everytime you start the nginx you will need to have this running in background in the powershell terminal: wsl.exe -d wsl-vpnkit --cd /app wsl-vpnkit
Now the requests should be working
