### ISSUE TITLE
Composer is taking a long time to download provider

### ISSUE THREAD

**Issue by ross-chater** [composer/composer#6101] opened 2017-01-25 17:03 UTC
Downloading http://packagist.org/p/provider-2016-07%24be4ebd626ddcbcf8434576189c56cedfb8237f4191903a345f6f6d3b3b2f896e.json

This hangs on here for ~5-10 mins

Even in a fresh directory, "composer init" then "composer require cakephp/cakephp"

All of my projects using packagist are taking a long time to update / install.

I can curl these json files in seconds just to note.  

Thanks

**Comment by staabm** [comment] 2017-01-25 17:03
maybe your composer connection works thru a proxy and your curl doesnt?

**Comment by ross-chater** [comment] 2017-01-25 17:09
I fully removed all cache / config and re-installed composer. Unless that sort of time to get providers is normal, and once in cache it works as expected?

**Comment by staabm** [comment] 2017-01-25 18:30
Try checking with wireshark in between

**Comment by alcohol** [comment] 2017-01-26 08:57
Looks like a networking issue. Check firewall, proxy or virus scanner activity. Not composer related.

**Comment by Seldaek** [comment] 2017-02-25 18:25
Closing as we don't have enough info to reproduce..

**Closed by Seldaek** 2017-02-25 18:25 UTC
Labels: Question
