### ISSUE TITLE
Composer 1.2.3 wraps scripts output

### ISSUE THREAD

**Issue by mhujer** [composer/composer#5936] opened 2016-12-03 10:50 UTC
My `composer.json` (only the relevant part):
```json
    "scripts": {
        "lint": "parallel-lint -j 10 --exclude var --exclude vendor ."
    },
```

When I run this command:

```
composer run lint
```

I get the following output:

```shell
php c:\xampp\php\composer.phar run lint                            
> parallel-lint -j 10 --exclude var --exclude vendor .             
PHP 7.0.9 | 10 parallel jobs                                       
                                                                   
.............                                                      
.......                                                            
..........................                                         
...........                                                        
... 60/99 (60 %)                                                   
....................                                               
...................                      99/99 (100 %)             
                                                                   
                                                                   
Checked 99 files in 1 second                                       
No syntax error found                                              

```

And I expected this to happen:

```
> parallel-lint -j 10 --exclude var --exclude vendor .
PHP 7.0.9 | 10 parallel jobs
............................................................ 60/99 (60 %)
.......................................                      99/99 (100 %)


Checked 99 files in 1 second
No syntax error found
```
Works in 1.2.2 or when I run the command directly without Composer.

(W10 64bit, cmder shell)

Only change related to output between 1.2.2 and 1.2.3 is probably this one: https://github.com/composer/composer/compare/1.2.2...1.2.3#diff-425b09166cec48daca0a5f0dbbb634fd - in the PR https://github.com/composer/composer/pull/5852

**Comment by AdrianSkierniewski** [comment] 2016-12-03 11:15
It looks like duplicated to #5936

**Comment by driesvints** [comment] 2016-12-03 15:02
Seeing this as well in 1.2.3 when running composer scripts:

```bash
vagrant@laravelio:/vagrant$ composer test tests/Components/Users/
> phpunit 'tests/Components/Users/'
PHPUnit 5.6.4 by Sebastian Bergmann and contributors.



.
.
.
.
.
.

 6 / 6 (100%)


Time: 2.46 seconds, Memory: 18.00MB


OK (6 tests, 7 assertions)


vagrant@laravelio:/vagrant$
```

**Comment by alcohol** [comment] 2016-12-03 23:29
Yeah, duplicate of #5933 basically.

**Closed by alcohol** 2016-12-03 23:29 UTC
