### ISSUE TITLE
"Failed to decode zlib stream" when install 

### ISSUE THREAD

**Issue by PrinC** [composer/composer#4619] opened 2015-11-19 16:21 UTC
Get error when install composer with curl -sS https://getcomposer.org/installer | php
```
#!/usr/bin/env php
All settings correct for using Composer
Downloading...
PHP Fatal error:  Uncaught exception 'RuntimeException' with message 'Failed to decode zlib stream' in -:574
Stack trace:
#0 -(417): HttpClient->get('https://getcomp...')
#1 -(112): installComposer(false, false, 'composer.phar', false, false, false)
#2 -(14): process(Array)
#3 {main}
  thrown in - on line 574
```

**Comment by alcohol** [comment] 2015-11-23 11:13
Duplicate of #4121

**Closed by alcohol** 2015-11-23 11:13 UTC
Labels: Support

**Comment by hdl** [comment] 2016-12-07 08:10
This is network connection issue.

**Comment by creativeshuvo** [comment] 2017-03-22 15:52
Failed to decode zlib stream
how to solve this issue

**Comment by codebeautiful** [comment] 2017-03-29 03:30
may be you should use this command at ubuntu
sudo apt-get install zlibc

good luck

**Comment by Rbingo** [comment] 2017-06-15 09:46
how to solve the issue,in windows system?

**Comment by ekasolusi** [comment] 2017-06-20 03:06
In windows, change
zlib.output_compression=Off to on in php.ini file
good luck

**Comment by Loetfi** [comment] 2017-08-08 07:36
hi ekasolusi thanks.

**Comment by AslanLau** [comment] 2018-01-02 08:29
thanks @ekasolusi

**Comment by standibi** [comment] 2018-01-26 13:01
thanks @ekasolusi

**Comment by milyas77** [comment] 2018-04-05 04:06
on my php.ini file zlb.output_compression is by default off but still the issue remain

**Comment by SamoKaku** [comment] 2018-10-02 20:10
Thanks it work

**Comment by Riowaldy** [comment] 2018-12-07 17:00
> 
> 
> In windows, change
> zlib.output_compression=Off to on in php.ini file
> good luck

Thank you so much @ekasolusi

**Comment by mrdalem** [comment] 2018-12-14 10:56
> In windows, change
> zlib.output_compression=Off to on in php.ini file
> good luck

Thanks its work! Great

**Comment by abkisakye** [comment] 2019-12-11 11:43
https://github.com/composer/composer/issues/4619#issuecomment-309631946

thanks this works

**Comment by wahyusa** [comment] 2020-09-07 07:34
> In windows, change
> zlib.output_compression=Off to on in php.ini file
> good luck

Thankyou
It work! but first time i've just write **"On"** and still error 
the value is **must be "on"**

**Comment by muhammadabdelsalam2** [comment] 2022-04-04 14:32
thanks this works

**Comment by khalidJA** [comment] 2022-08-06 15:35
Try to enable` fileinfo` extension from` ini file `

**Comment by Arikowid31** [comment] 2022-12-29 13:35
> In windows, change zlib.output_compression=Off to on in php.ini file good luck

i was about to make this change, but i press retry previously and then it worked, is mine gonna have bug or something?
im worried lol

**Comment by yasyaindra** [comment] 2023-07-17 08:18
what if it happened in Docker?

**Comment by hhaswan** [comment] 2024-01-30 08:07
> may be you should use this command at ubuntu
> 
> ```
> sudo apt-get install zlibc
> ```
> 
> good luck

It works in some case,
I've installed  `apt-get install zlibc` on-premise server but Not Works.
it also depending on your **Internet Provider and Firewall** 😄 make sure http not blocked and your internet provider or firewall (i.e Fortigate) doesn't limit anything

**Comment by inuitviking** [comment] 2024-03-05 08:40
I know this is closed, old and from 2015, but for Debian Bookworm, this seems to solve the issue:

```bash
sudo apt install zlib1g
```

**Comment by dilhanchandrasiri** [comment] 2024-07-04 17:32
Make sure zip extension is installed too.

`sudo apt install php-zip`

**Comment by facesses** [comment] 2025-02-11 01:02
> In windows, change zlib.output_compression=Off to on in php.ini file good luck

it works! thank you.
