### ISSUE TITLE
Composer Asks for SSH Key Twice

### ISSUE THREAD

**Issue by mcordingley** [composer/composer#4257] opened 2015-07-14 19:23 UTC
Not an issue if you haven't set a passphrase on the key, but rather annoying if you have.

```
foo@hostname ~/projects/example $ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)         
  - Updating vendor/package dev-master (03bc44a => 7c65481)
    Checking out 7c65481c20766d4b84c99d04b7a75502bd9dfc71
Enter passphrase for key '/home/foo/.ssh/id_rsa': 
Enter passphrase for key '/home/foo/.ssh/id_rsa': 

Writing lock file
Generating autoload files
```

**Comment by slbmeh** [comment] 2015-07-17 22:22
Not much can be done here, it uses the key more than once, so you need to enter the passphrase more than once. Use a utility like `ssh-agent` or set up git credential caching.

Duplicate of #4004?

**Comment by frederikbosch** [comment] 2015-07-18 12:40
@slbmeh Yes. This one can be closed.

**Closed** 2015-07-21 08:23 UTC

**Comment by bezin** [comment] 2015-07-23 14:03
Any suggestions on how to fix that issue when you are on Windows and not having ssh-agent? I use Pageant with Putty, but have problems to set up Composer with SSH.

**Comment by slbmeh** [comment] 2015-07-23 18:13
@bezin I'm not very familiar with Windows. There isn't anything composer can do about it.  The ssh client is what receives the password.  AFAIK Pageant is the same concept as ssh-agent... You should be able to configure your `GIT_SSH` environment variable to use an ssh client that is aware of Pageant.

**Comment by bezin** [comment] 2015-07-24 08:39
Thanks for your hints. Took me some time to figure out my own setup with SourceTree, because it brings Pageant and Plink with itself. It was mainly because git was lookin for ssh keys at the wrong folder. But setting the plink.exe in the SourceTree folder to GIT_SSH environmental variable makes it work as expected. Thanks .
