### ISSUE TITLE
current Composer version refuses to install ezpublish saying it can not be found

### ISSUE THREAD

**Issue by gggeek** [composer/composer#4582] opened 2015-11-05 09:59 UTC
Tested on Travis, with php 5.5, and on windows, also with php 5.5.

Here is the log of a failed build: https://travis-ci.org/gggeek/ezobjectwrapper/builds/89351754
As you can see on line 105, I had added a 'composer self-update' command before composer install.

Otoh, when not doing the composer update, the composer installation works, as seen on this other build: https://travis-ci.org/gggeek/ezobjectwrapper/builds/89353721

The two builds use the same composer.json.

The error msg is:
```
Your requirements could not be resolved to an installable set of packages.
  Problem 1
    - The requested package ezsystems/ezpublish-kernel could not be found in any version, there may be a typo in the package name.
Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.
Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.
Installation failed, reverting ./composer.json to its original content.
```

**Comment by pborreli** [comment] 2015-11-05 10:03
maybe related to #4480 ?

**Comment by gggeek** [comment] 2015-11-05 10:10
Yup, seems like a dupe indeed

**Comment by alcohol** [comment] 2015-11-05 10:11
Duplicate of #4480

**Closed by alcohol** 2015-11-05 10:11 UTC
