### ISSUE TITLE
[FR] Allow updating composer.lock without downloading deps

### ISSUE THREAD

**Issue by gggeek** [composer/composer#7422] opened 2018-06-23 13:26 UTC
My use case basically boils down to running tests on Travis of a php app with a huge dependency set.
When running the tests with php 5.6, composer fails because OOM.

While I am playing around with enabling swapfiles and whatnot, I was also wondering what would be alternative sets of commands / flags that could achieve a lower memory usage from Composer.
EG: would it help to reduce the number of active php exts for running composer with `--ignore-platform-reqs` and reenable them afterwards?

One idea that I cam up with is: execute composer in multiple steps: !) resolve deps and write lock file, then 2) download deps using `composer install`.

Would it make sense / Is it possible at all?

**Comment by alexislefebvre** [comment] 2018-06-24 18:39
Did you try to commit your `composer.lock`? It will speed up `composer install`.

**Comment by gggeek** [comment] 2018-06-25 08:27
@alexislefebvre teh whole problem is that I can not commit composer.lock as:
1. this is a library, not an app. It does not come with a locked down set of versions for its dependencies, and
2. when running the test suite, I run it explicitly against many different versions of the dependencies, so there is no single composer.lock file use.

The only way that I can think of for having composer.lock committed to the repo is to
- commit many composer.lock files inside the Tests dir, and copy them to the good location before each test pass
- generate those composer.lock files on a VM which has more memory than the Travis ones do

But this only shifts the problem around, does not fix it (and it involves quite some effort on my part)

**Comment by staabm** [comment] 2018-06-25 08:30
maybe https://github.com/pborreli/composer-service is somehow usefull for you

**Comment by staabm** [comment] 2018-06-25 08:32
did you try do some kind of memory profilling (e.g. with blackfire, xdebug or similar) and see if there is some low hanging fruits to get ?

**Comment by fritzmg** [comment] 2018-06-28 17:39
Duplicate of https://github.com/composer/composer/pull/4946 ? ;)

**Comment by gggeek** [comment] 2018-06-28 23:06
Indeed a dupe, even though the reason for requiring this is a bit
difgerent. Thx for spotting it!
What I would advocate to reduce the chance of shoot-self-in-foot is in fact
a separate composer 'verb' rather than a flag for 'update'

**Comment by alcohol** [comment] 2018-07-02 13:13
On travis, it helps to add your composer home directory and project vendor directory to the travis cached directories.

Also, not downloading/installing dependencies does not reduce the complexity of the solving process. So there is barely anything to be gained there. Instead, make sure your constraints are as precise as possible.

**Comment by gggeek** [comment] 2018-07-02 13:20
> not downloading/installing dependencies does not reduce the complexity of the solving process.

True, but mi own testing shows that not all memory used in the resolving pahse gets released during the download phase. And it is the total of the 2 that in this specific case went above the server limits.

**Comment by alcohol** [comment] 2018-07-02 15:34
> True, but my own testing shows that not all memory used in the resolving phase gets released at the beginning of the download phase.

Perhaps this is something that could be looked into and improved upon? Not going to be an easy task probably... but there might be room for improvement I guess.

**Comment by alcohol** [comment] 2018-07-02 15:45
My (very limited) test shows that there is no memory freed at all after the solving stage progresses towards the installing stage. Could you generate a similar profiled output for us to look at?

https://github.com/composer/composer/issues/7437

**Comment by mwgamble** [comment] 2018-07-03 00:22
> this is a library, not an app. It does not come with a locked down set of versions for its dependencies

Any `composer.lock` file contained within a package is entirely ignored by composer when the package is installed as a dependency in another project.

**Comment by alcohol** [comment] 2018-07-03 06:21
@mwgamble it is pretty common for libraries to not commit their .lock file. Libraries are often tested against both the lowest matching set of requirements and the highest matching set of requirements. Since a lock file cannot contain both it does not really benefit you much to commit it.

**Comment by Seldaek** [comment] 2018-07-17 15:02
I don't think doing this makes a lot of sense, as you say the limit in this case was reached but if we fix the installation step then the problem remains just for projects using a little more memory.. Or maybe for your project in six months when you have more deps/versions in play. It's not exactly a fixable situation.

**Closed by Seldaek** 2018-07-17 15:02 UTC
