### ISSUE TITLE
Override preffered-install in CLI or introduce config-dev

### ISSUE THREAD

**Issue by dakujem** [composer/composer#7060] opened 2018-01-30 12:24 UTC
This is a feature request.

We are using a set of `config` settings in our `composer.json` files,
namely `preferred-install`, we have
```json
"config": {
	"preferred-install": {
		"foo/*": "source"
	}
}
```

We use this for our private packages that we keep developing within the vendor for convenience.

We would like to be able to override this setting to install from `dist` in production environment.

To do this, it would be nice to either have an appropriate CLI switch, i.e. `composer install --preferred-install foo/*:dist`, or to be able to use `config-dev` in the `composer.json` file, it would then look like
```json
"config": {
	"preferred-install": {
		"foo/*": "dist"
	}
},
"config-dev": {
	"preferred-install": {
		"foo/*": "source"
	}
},
```

Of course we tried `--prefer-dist` which has no effect for this scenario: `foo` packages still get installed from source.

The packages are avalable in "dist", if I remove the `preferred-install` clause from config, they install as expected.

**Comment by Seldaek** [comment] 2018-01-31 14:06
I guess if `--prefer-dist` is passed that should override all configs and not just the default/auto configs.

**Comment by Seldaek** [comment] 2018-01-31 14:55
Actually I can't reproduce this.. --prefer-dist overrides the preferred-install flag for me.

**Comment by dakujem** [comment] 2018-01-31 17:15
Strange. I tested this on the day of my post. It happens on different machines on different platforms.

I will test it once more and get back asap. If there is info you need to reproduce, let me know.

**Comment by Seldaek** [comment] 2018-02-01 08:50
The only reason I can see that it'd happen is if you have no dist defined at all for those packages.. Which is possible if they are private packages not configured correctly. If you can share the way you define the packages that might help, or share the package info from composer.lock (feel free to obfuscate names/URLs, but try not to remove other stuff).

**Comment by Seldaek** [comment] 2018-04-13 09:49
Closing as can not reproduce, please feel free to reopen if you have more details.

**Closed by Seldaek** 2018-04-13 09:49 UTC
Labels: Bug
