### ISSUE TITLE
Wrong behavior during a partial update for locked packages

### ISSUE THREAD

**Issue by stof** [composer/composer#1178] opened 2012-10-03 15:01 UTC
If your installed packages don't match the lock file (because you forgot to run ``composer install`` when another dev updated the vendors for instance), running a partial update will behave in a bad way for dev versions.
Here is what happens:

1. ``composer update foo/bar`` is called
2. The solver asked to update ``foo/baz dev-master`` from ``old_ref`` to ``locked_ref`` as the wrong version was installed (and this is the good behavior)
3. The installer changes this operation to an update from ``old_ref`` to ``new_ref`` as there is some commits in the master branch newer than ``locked_ref``

Result: the package ``foo/baz`` is updated in the lock file by the partial update whereas it was not whitelisted

**Comment by Seldaek** [comment] 2016-04-15 19:20
Closing as duplicate of #3468

**Closed by Seldaek** 2016-04-15 19:20 UTC
Labels: Bug
