### ISSUE TITLE
Commands should be case insensitive

### ISSUE THREAD

**Issue by greydnls** [composer/composer#6325] opened 2017-04-04 14:47 UTC
When I run this command:

`composer require namespace/package` and then `composer require Namespace/package`

I get the following output:
>2 lines are added to composer.json

And I expected this to happen:
>Composer should recognize these are the same and not show duplicate lines in composer.json

If the behavior I'm expecting is correct, I'm happy to submit a patch for this.

**Comment by alcohol** [comment] 2017-04-05 07:58
While Composer is not strictly case-insensitive (but in practical terms, it completely is), generally we lowercase everything. So lowercasing the user input before adding it would probably be a good call.

**Comment by Seldaek** [comment] 2017-04-05 15:13
Well in [RemoveCommand](https://github.com/composer/composer/blob/master/src/Composer/Command/RemoveCommand.php#L84) for example we do lowercase the input and then lowercase everything to see if it exists and where and then remove it using the proper case.

While the names are case-insensitive, I don't think it's ok to flat out lowercase stuff in `require` as case can be meaningful to some people. Only packagist.org enforces lowercase names.

So I think doing the same as in remove, just checking if it's there already with another case and then overwriting with that same case is probably the best option. More work though.

**Comment by Deamon** [comment] 2017-08-23 07:30
I tried to reproduce the case with master branch like this : 

start with an empty require field in composer.json

```
"require": {
  },
```
exec command `../contribution/composer/bin/composer require seld/jsonlint`
output : 
```
Using version ^1.6 for seld/jsonlint
./composer.json has been updated
Loading composer repositories with package information                                                            Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```
the new require field : 
```
  "require": {
    "seld/jsonlint": "^1.6"
  },
```

then execute command `../contribution/composer/bin/composer require Seld/jsonlint` (note the capital S)
output : 
```
Using version ^1.6 for Seld/jsonlint
./composer.json has been updated
Loading composer repositories with package information                                                            Updating dependencies (including require-dev)
Nothing to install or update
Generating autoload files
```
and the composer.json which hasn't change : 
```
 "require": {
    "seld/jsonlint": "^1.6"
  },

```

with tag 1.5.1 I end up with this composer.json : 
```
  "require": {
    "seld/jsonlint": "^1.6"
  },
```

if I switch to tag 1.4.3, I end up with this composer.json : 
```
  "require": {
    "Seld/jsonlint": "^1.6",
    "seld/jsonlint": "^1.6"
  },
```

so in last composer tags, there is no more than one line added but we keep the first one added when adding with an other case.

Do we need to change the behavior ?

**Comment by Seldaek** [comment] 2017-12-19 12:49
Seems like this is fixed in master, I don't remember when it was done but anyway can't reproduce anymore so closing.

**Closed by Seldaek** 2017-12-19 12:49 UTC
Labels: Easy Pick, Feature

**Comment by greydnls** [comment] 2017-12-19 13:04
Cool. Thanks!
