### ISSUE TITLE
Installing windows version of composer

### ISSUE THREAD

**Issue by paladox** [composer/composer#5123] opened 2016-03-27 22:17 UTC
Hi with the new release of composer using the windows installer it no longer upgrades prevous version ofs composer.

Also the option that allowed users to add composer to the windows options meaning when you right clicked on the folder for which you want to run composer it used to show the option to do composer install or run composer. Now it doesn't show the option.

Please fix this.

**Comment by paladox** [comment] 2016-03-27 22:31
Found out that ShellMenus has been removed. Please re add it.

**Comment by paladox** [comment] 2016-03-27 22:36
Please revert https://github.com/composer/windows-setup/commit/7edd75a0d598d621d1ab8188803df192d497daca

**Comment by Seldaek** [comment] 2016-03-28 16:21
Closing as duplicate of https://github.com/composer/windows-setup/issues/53

**Closed by Seldaek** 2016-03-28 16:21 UTC
