### ISSUE TITLE
Composer doesn't cache Toran Proxy JSON files

### ISSUE THREAD

**Issue by alexbilbie** [composer/composer#3799] opened 2015-02-27 14:37 UTC
When `packagist: false` is enabled and I proxy all public packages through my Toran Proxy instance Composer doesn't make use of cached JSON files that it downloaded previously (even if I ran `composer up` just a few seconds before).

Removing the proxying and re-enabling Packagist results in Composer using the locally cached JSON files.

Is this expected behaviour?

**Comment by Seldaek** [comment] 2015-02-27 15:19
Yup that's due to the fact the packagist proxy does not have a full list of packages it just tells composer to call for any package and it then answers yes/no. The theory was that it's ok in most cases because your toran server should be close enough to you and with a good connection, but with a large dependency list this might take its toll. I have to think about this more and see what can be done to improve the situation.

**Comment by alexbilbie** [comment] 2015-02-27 15:21
I have quite a large dependency list and it's taking on average 102 seconds to run and install or update

**Comment by Seldaek** [comment] 2015-02-27 15:45
For update fair enough, but install from lock should always be instant, 
so make sure you use that where you can :)

**Comment by scourgen** [comment] 2015-05-04 06:49
+1 for this feature, better to have.

**Comment by nevvermind** [comment] 2015-05-04 11:00
> The theory was that it's ok in most cases because your toran server should be close enough to you and with a good connection

I actually installed it _locally_ and each call to `/repo/packagist/p/` is _very_ slow (3-4 seconds each req?). It doesn't seem to be problem on Toran's side, as I can do 4 direct requests to the said URL _per second_ (according to `ab`). I guess Composer does some processing after fetching the json file.

Alas, this shouldn't be in the "Feature" milestone. It's a deal breaker when it comes to Toran. It's one of the perks of having a local (or close) Composer proxy - speed, isn't it?

Shall we wait for the reactphp PR to be merged for now?

**Comment by MauJFernandez** [comment] 2015-05-21 20:52
+1

Any update plan on this? I just had an error running an update (through Toran), and when I ran it again it downloaded everything again, it's quite annoying and time consuming.

**Comment by ibrasho** [comment] 2015-06-16 06:07
I agree, the HTTP overhead for a big list of deps is annoying. :+1:

**Comment by Vinai** [comment] 2015-06-23 14:13
I'm running toran on my local machine, but it takes 20+ minutes with packagist set to false and proxying for an `composer update` on a [Magento 2](https://github.com/magento/magento2/blob/develop/composer.json) repository.

Just posting to give this feature a bump, as the current behavior make toran unusable for me. :(

**Comment by adamlc** [comment] 2015-07-02 08:04
I also have a large deps set and for me it takes 10 minutes on average :cry:

**Comment by cgrossde** [comment] 2015-07-18 20:22
Same problem here. The initial install is faster with Toran but subsequent updates are very slow / slower compared to not using Toran.

**Comment by bryceray1121** [comment] 2015-08-19 19:31
We are experiencing the same extreme slowness.  Is this a plan to have this fixed any time soon?

**Comment by TheRatG** [comment] 2015-09-24 19:02
+1 up

**Comment by dmkuznetsov** [comment] 2015-09-25 06:35
+1 for this feature

**Comment by bojik** [comment] 2015-09-25 06:37
we have the same problem, therefore +1

**Comment by jhoff** [comment] 2015-10-21 22:21
+1 Update is always slow regardless of proximity to the toran server

**Comment by Anahkiasen** [comment] 2015-11-10 12:57
Any news on this? I'm currently disabling Toran every time I have to do a `composer update` because it takes an _eternity_ to run, which kind of negates the benefits of using Toran in the first place :/

**Comment by jippi** [comment] 2016-02-24 17:12
:+1:

**Comment by Seldaek** [comment] 2016-03-11 15:37
Toran 1.3.0 released just now fixes this (and some other issues/features). Sorry for taking so long to get to this, but hopefully it'll be worth it. 

Note that Composer will still download the files (due to what I explained in https://github.com/composer/composer/issues/3799#issuecomment-76410381) but they are now static files on disk and not hitting php every time so it is returned by the web server a lot faster, and Composer will also fetch the files it has in cache  sending an If-Modified-Since header so if your webserver is configured correctly it'll just return a Not Modified response and in cases where the cache is up to date.

Full changelog of 1.3 + 1.2 which were both released this week:

  * Added a list of other public repos to mirror on top of packagist, which lets you sync wpackagist, magento repos, etc.
  * Added detailed listing pages for private packages
  * Added support for the new style of BitBucket hooks
  * Added an easy way to update single private packages from the UI
  * Added support for updating single packages from CLI, via `bin/cron <packagename>`
  * Added a JSON API to create private packages, see `Documentation > FAQ > How to create private packages programmatically?`
  * Updated dependencies for PHP7 support and latest Composer features
  * Fixed packagist proxy to cache provider files in web dir, which makes it a lot faster to run updates
  * Fixed bug with the automatic update of packages after they are added
  * Fixed a few minor bugs

You can run "php app/console toran:update" to update. If you hit any regression please let me know by email at toran@nelm.io and I'll try to push out a fix ASAP.

**Closed by Seldaek** 2016-03-11 15:37 UTC
Labels: Feature

**Comment by TheRatG** [comment] 2016-03-11 18:40
Thanks a lot!

**Comment by jippi** [comment] 2016-03-11 20:40
@Seldaek any changes to the recommended nginx config file to mirror the 1.3 changes with cached files?

**Comment by Seldaek** [comment] 2016-03-12 13:59
@jippi no I think nginx handles this correctly by default.
