### ISSUE TITLE
composer update is showing 1 more update in package operations than actual number

### ISSUE THREAD

**Issue by leoloso** [composer/composer#9231] opened 2020-09-19 14:35 UTC
My `composer.json`:

```json
{
    "name": "graphql-api/graphql-api",
    "type": "library",
    "description": "GraphQL API for WordPress",
    "keywords": [
        "PoP",
        "WordPress",
        "GraphQL",
        "API"
    ],
    "homepage": "https://github.com/GraphQLAPI/graphql-api-for-wp",
    "license": "MIT",
    "authors": [
        {
            "name": "Leonardo Losoviz",
            "email": "leo@getpop.org",
            "homepage": "https://getpop.org"
        }
    ],
    "minimum-stability": "dev",
    "prefer-stable": true,
    "require": {
        "php": "~7.4",
        "erusev/parsedown": "^1.7",
        "pop-schema/generic-customposts": "dev-master",
        "pop-schema/commentmeta-wp": "dev-master",
        "pop-schema/comments-wp": "dev-master",
        "pop-schema/custompostmedia-wp": "dev-master",
        "pop-schema/custompostmeta-wp": "dev-master",
        "getpop/engine-wp": "dev-master",
        "graphql-by-pop/graphql-server": "dev-master",
        "graphql-by-pop/graphql-clients-for-wp": "dev-master",
        "graphql-by-pop/graphql-endpoint-for-wp": "dev-master",
        "pop-schema/media-wp": "dev-master",
        "pop-schema/pages-wp": "dev-master",
        "pop-schema/posts-wp": "dev-master",
        "pop-schema/taxonomymeta-wp": "dev-master",
        "pop-schema/taxonomyquery-wp": "dev-master",
        "pop-schema/post-tags-wp": "dev-master",
        "pop-schema/basic-directives": "dev-master",
        "pop-schema/user-roles-access-control": "dev-master",
        "pop-schema/user-roles-wp": "dev-master",
        "pop-schema/user-state-wp": "dev-master",
        "pop-schema/usermeta-wp": "dev-master",
        "pop-schema/users-wp": "dev-master",
        "symfony/expression-language": "^5.1",
        "wikimedia/composer-merge-plugin": "^1.4"
    },
    "require-dev": {
        "phpstan/phpstan": "^0.12",
        "phpunit/phpunit": ">=9.3",
        "rector/rector": "dev-master#59547a5cbe7845c2ca493ede481e1141e53df079",
        "squizlabs/php_codesniffer": "^3.0",
        "szepeviktor/phpstan-wordpress": "^0.6.2",
        "johnpbloch/wordpress": ">=5.5"
    },
    "repositories": [
        {
            "type": "composer",
            "url": "https://wpackagist.org"
        }
    ],
    "autoload": {
        "psr-4": {
            "GraphQLAPI\\GraphQLAPI\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "GraphQLAPI\\GraphQLAPI\\": "tests"
        }
    },
    "scripts": {
        "test": "phpunit",
        "check-style": "phpcs src tests",
        "fix-style": "phpcbf src tests",
        "analyse": "phpstan analyse -c phpstan.neon.dist",
        "downgrade-code": "rector process --dry-run"
    },
    "extra": {
        "wordpress-install-dir": "vendor/wordpress/wordpress",
        "branch-alias": {
            "dev-master": "1.0-dev"
        },
        "merge-plugin": {
            "include": [
                "composer.local.json"
            ],
            "recurse": true,
            "replace": false,
            "ignore-duplicates": false,
            "merge-dev": true,
            "merge-extra": false,
            "merge-extra-deep": false,
            "merge-scripts": false
        }
    },
    "config": {
        "sort-packages": true
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
The package "rector/rector" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues.
require.pop-schema/generic-customposts : unbound version constraints (dev-master) should be avoided
require.pop-schema/commentmeta-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/comments-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/custompostmedia-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/custompostmeta-wp : unbound version constraints (dev-master) should be avoided
require.getpop/engine-wp : unbound version constraints (dev-master) should be avoided
require.graphql-by-pop/graphql-server : unbound version constraints (dev-master) should be avoided
require.graphql-by-pop/graphql-clients-for-wp : unbound version constraints (dev-master) should be avoided
require.graphql-by-pop/graphql-endpoint-for-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/media-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/pages-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/posts-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/taxonomymeta-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/taxonomyquery-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/post-tags-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/basic-directives : unbound version constraints (dev-master) should be avoided
require.pop-schema/user-roles-access-control : unbound version constraints (dev-master) should be avoided
require.pop-schema/user-roles-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/user-state-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/usermeta-wp : unbound version constraints (dev-master) should be avoided
require.pop-schema/users-wp : unbound version constraints (dev-master) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.10.13
PHP version: 7.4.10
PHP binary path: /usr/local/Cellar/php/7.4.10/bin/php
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

When I run this command:

```
composer update
```

I get the following output:

```
➜  graphql-api-for-wp git:(master) ✗ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
74 packages you are using are looking for funding.
Use the `composer fund` command to find out more!

➜  graphql-api-for-wp git:(master) ✗ composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 2 updates, 0 removals
  - Updating graphql-by-pop/graphql-clients-for-wp dev-master (87db363 => 11735ad):  Checking out 11735ad410
Writing lock file
Generating autoload files
composer/package-versions-deprecated: Generating version class...
composer/package-versions-deprecated: ...done generating version class
74 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

And I expected this to happen:

Notice how

- when there were no updated packages, it said Package operations: 1 update
- when there was 1 updated package, it said: Package operations: 2 updates

So it seems it's always adding 1.

**Comment by sumpygump** [comment] 2020-09-19 23:07
This is caused by the rector dependency.

When you run `composer update` with `-v`, notice how that is the one update it is referring to.

```
$ composer update -v
Loading composer repositories with package information
Updating dependencies (including require-dev)   
Dependency resolution completed in 0.694 seconds
Analyzed 17606 packages to resolve dependencies
Analyzed 102267 rules to resolve dependencies   
Dependency resolution completed in 0.001 seconds     
Package operations: 0 installs, 1 update, 0 removals
Updates: rector/rector:dev-master 52ccfc0
Generating autoload files
ocramius/package-versions: Generating version class...
ocramius/package-versions: ...done generating version class
74 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
```

It does warn about this in the `diagnose` results.

```
The package "rector/rector" is pointing to a commit-ref, this is bad practice and can cause unforeseen issues.
```

Out of curiosity why are you pointing to a specific commit-ref for rector?

**Comment by leoloso** [comment] 2020-09-19 23:50
Ah, that explains it, thanks.

Then, shouldn't rector be shown in the list of updated packages? Oherwise it's confusing

> Out of curiosity why are you pointing to a specific commit-ref for rector?

As a temporary thing, because I'm already using a new feature of rector (to downgrade code from PHP 7.4 to 7.1) which has not been tagged yet (actually, I just checked again, and now it's tagged, so I'll point to the tag now)

**Comment by leoloso** [comment] 2020-09-20 07:52
So the bug is that dependencies using the `commit-ref` are always counted as updated, even though they are not

**Comment by Seldaek** [comment] 2020-09-21 11:25
Can you check if it is already fixed in 2.0-RC1 (`composer self-update --preview`)? I suspect it is, and it's definitely something we will not fix in 1.x.

**Comment by stof** [comment] 2020-09-21 15:39
I would say that this is related to the commit-ref pinning, which is an installer-level hack:
- the solver sees that the installed version of `rector/rector` is not the latest `dev-master` and so plans an upgrade of the package
- the installer overrides the target version due to the commit-ref pinning, and then does nothing for that update as it sees that the installed version is already the pinned one.

> As a temporary thing, because I'm already using a new feature of rector (to downgrade code from PHP 7.4 to 7.1) which has not been tagged yet

using the latest `dev-master` would still give you that feature. A (bad) use case for commit-ref pinning is when you need to force using an older version because the latest dev version is broken.

Note that the solver will still always use the metadata (dependencies, etc...) from the latest `dev-master` (as they are the metadata available in Packagist) so installed a pinned commit is actually more fragile, not less.

**Comment by leoloso** [comment] 2020-09-21 22:55
> Can you check if it is already fixed in 2.0-RC1 (composer self-update --preview)?

I just checked, there's no problem there :)

Then, I guess nothing to fix, be welcome to close the issue

**Comment by leoloso** [comment] 2020-09-21 22:56
> using the latest `dev-master` would still give you that feature

That's right, but things may break in `dev-master` every now and then, so I just pointed to a specific commit that I was sure worked fine

**Closed** 2020-09-22 07:05 UTC

**Comment by stof** [comment] 2020-09-22 09:27
@leoloso a commit-ref can also break at any time, because the resolved dependencies (and the autoload rules) are still from the latest `dev-master`, not from the installed version.

**Comment by leoloso** [comment] 2020-09-22 09:30
Good to know, thanks for the info!

**Comment by stof** [comment] 2020-09-22 09:32
note that's exactly why composer warns when using the feature. This is a hack from early days of composer when partial updates were not possible and most packages had no releases.
