### ISSUE TITLE
Increase performance of the remote file system

### ISSUE THREAD

**Issue by francoispluchino** [composer/composer#3282] opened 2014-09-18 22:11 UTC
It would be interesting to improve the performance of the remote file system. Currently only the method `file_get_contents` is used, but using `CURL`, we could significantly improve the speed of Composer, especially for VCS Repository that uses a lot the remote file system.

I know that `CURL` is not present by default, but we could do a test to detect its presence, and use `file_get_contents` when it is not active.

Of course, I've seen pass the issues about using `CURL`, but I would like to make a comparative test, showing that it would be really cool to add support when it is available.

Indeed, I did performance tests with `file_get_contents` and `CURL`, by enabling and disabling URL redirection, while performing 10 tests for each of the 4 types (representing 40 tests per attempt).

**Types:**
- `file_get_contents` with follow redirect
- `curl` with follow redirect
- `file_get_contents` without follow redirect
- `curl` without follow redirect

**Results of 10 attempts with PHP 5.5 on Windows 8:**

min increase | med increase | max increase | **report** (number of time faster)
-------------|--------------|--------------|-----------------
-20%         | -310%        | -513%        | 6.1x
-22%         | -270%        | -469%        | 5.7x
-21%         | -278%        | -460%        | 5.6x
-23%         | -273%        | -475%        | 5.7x
-24%         | -287%        | -486%        | 5.9x
-20%         | -272%        | -463%        | 5.6x
-21%         | -272%        | -470%        | 5.7x
-22%         | -270%        | -465%        | 5.7x
-22%         | -279%        | -469%        | 5.7x
-22%         | -280%        | -459%        | 5.6x
**avg**      | **avg**      | **avg**      | **avg**
-22%         | -279%        | -473%        | **5.7x**

Legend:
- `min increase`: if using CURL with follow redirect
- `med increase`: if using file_get_contens without follow redirect
- `max increase`: if using CURL without follow redirect
- `report`: number of time faster

Given that the vast difference in performance is when the redirection is not enabled, maybe, it would be interesting to perform redirection manually.

Furthermore, the redirects are rarely used for API, therefore, we could significantly improve the performance of Composer using `CURL` when it is available and managing the redirects manually.

**To conclude:**

In the worst case we increase the performance of 22% and at best 473% (that is to say up to 5.7 times faster), and that is no small thing, I think.

**The script to do the tests:**

```php
<?php

class TestPerf
{
    private $followUrl;
    private $useCurl;
    private $url = 'http://www.google.com';
    private $max = 10;
    private $values = array();

    public function __construct($followUrl = true, $useCurl = false)
    {
        $this->followUrl = $followUrl;
        $this->useCurl = $useCurl;
    }

    public function run()
    {
        $type = $this->useCurl ? 'curl' : 'file_get_contents';
        $follow = $this->followUrl ? 'with' : 'without';
        echo PHP_EOL . 'Performance test for "' . $type . '" ' . $follow . ' follow redirect:' . PHP_EOL . PHP_EOL;

        for ($i = 0; $i < $this->max; $i++) {
            if ($this->useCurl) {
                $time = $this->testCurl();
            } else {
                $time = $this->testFileGetContents();
            }
            $this->values[] = $time;

            echo sprintf('  Test %s: %s s', $i + 1, $time) . PHP_EOL;
        }

        echo PHP_EOL;

        return array_sum($this->values) / $this->max;
    }

    private function testFileGetContents()
    {
        $start = microtime(true);
        $context = stream_context_create(array(
                'http' => array(
                    'follow_location' => $this->followUrl,
                )
            ));
        file_get_contents($this->url, false, $context);

        return microtime(true) - $start;
    }

    private function testCurl()
    {
        $start = microtime(true);
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $this->url);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, $this->followUrl);
        curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 10);
        curl_exec($curl);
        curl_close($curl);

        return microtime(true) - $start;
    }
}

$test1 = new TestPerf(true, false);
$test2 = new TestPerf(true, true);
$test3 = new TestPerf(false, false);
$test4 = new TestPerf(false, true);
$avg1 = $test1->run();
$avg2 = $test2->run();
$avg3 = $test3->run();
$avg4 = $test4->run();
echo PHP_EOL . PHP_EOL . 'Average: ' . PHP_EOL . PHP_EOL;
echo PHP_EOL . '  "file_get_contents" with follow   : ' . $avg1 . ' s';
echo PHP_EOL . '  "curl" with follow                : ' . $avg2 . ' s'. PHP_EOL;
echo PHP_EOL . '  "file_get_contents" without follow: ' . $avg3 . ' s';
echo PHP_EOL . '  "curl" without follow             : ' . $avg4 . ' s' . PHP_EOL;
echo PHP_EOL . PHP_EOL . PHP_EOL . 'Variation: ' . PHP_EOL . PHP_EOL;
echo '  With follow redirect   :  ' . (($avg2 < $avg1) ? '-' : '+') . round($avg1 / $avg2 * 100 - 100) . '% (between file_get_contents and CURL)' . PHP_EOL;
echo '  Without follow redirect:  ' . (($avg2 < $avg1) ? '-' : '+') . round($avg3 / $avg4 * 100 - 100) . '% (between file_get_contents and CURL)' . PHP_EOL;
echo PHP_EOL . PHP_EOL . PHP_EOL . 'Performance increase: ' . PHP_EOL . PHP_EOL;
echo '  Minimal increase       :  ' . (($avg2 < $avg1) ? '-' : '+') . round($avg1 / $avg2 * 100 - 100) . '% (with CURL with follow redirect)' . PHP_EOL;
echo '  Medium increase        :  ' . (($avg2 < $avg1) ? '-' : '+') . round($avg1 / $avg3 * 100 - 100) . '% (with file_get_contents without follow redirect)' . PHP_EOL;
echo '  Maximal increase       :  ' . (($avg4 < $avg1) ? '-' : '+') . round($avg1 / $avg4 * 100 - 100) . '% (with CURL without follow redirect)' . PHP_EOL . PHP_EOL;
echo PHP_EOL . sprintf('RemoteFileSystem can be up to %sx faster', round($avg1 / $avg4 * 10) / 10) . PHP_EOL;
```

**Comment by francoispluchino** [comment] 2015-01-10 21:25
**Tests between file_get_contents auto follow redirect VS CURL auto and manual follow redirect:**

I did performance tests with `file_get_contents` and `CURL`, by enabling and disabling URL redirection, for an URL with 301 redirection and an URL without redirection, while performing 10 tests.

**AVG Results:**

With redirection / Auto | With redirection / Manual | Direct / Auto | Direct / Manual
----|-----|-----|----
x8.9 faster | x9.2 faster | x8.0 faster | x8.1 faster

Manually manage redirection is slightly faster. The results are much more glaring with the HTTPS protocol.

**The script to do the tests:**

```php
<?php

class TestPerf
{
    private $followUrl;
    private $useCurl;
    private $url;
    private $max = 10;
    private $values = array();

    public function __construct($followUrl, $useCurl, $url)
    {
        $this->followUrl = $followUrl;
        $this->useCurl = $useCurl;
        $this->url = $url;
    }

    public function run()
    {
        $type = $this->useCurl ? 'curl' : 'file_get_contents';
        $follow = $this->followUrl ? 'auto' : 'manual';

        echo $this->url.':'.PHP_EOL;
        for ($i = 0; $i <= strlen($this->url); $i++) {
            echo '-';
        }
        echo PHP_EOL;
        echo PHP_EOL.'    TYPE:       '.$type;
        echo PHP_EOL.'    FOLLOW URL: '.$follow.PHP_EOL.PHP_EOL;

        for ($i = 0; $i < $this->max; $i++) {
            if ($this->useCurl) {
                $time = $this->testCurl();
            } else {
                $time = $this->testFileGetContents();
            }
            $this->values[] = $time;

            echo sprintf('    Test %s: %s s', $i + 1, $time).PHP_EOL;
        }

        $avg = array_sum($this->values) / $this->max;
        echo PHP_EOL.PHP_EOL.sprintf('    AVG:    %s s', $avg).PHP_EOL.PHP_EOL.PHP_EOL;

        return $avg;
    }

    private function testFileGetContents()
    {
        $start = microtime(true);
        $this->getFileGetContentsContent($this->url, $this->followUrl);

        return microtime(true) - $start;
    }

    private function getFileGetContentsContent($url, $followUrl)
    {
        $context = stream_context_create(array(
            'http' => array(
                'follow_location' => $followUrl,
            )
        ));
        $content = file_get_contents($url, false, $context);

        if (!$followUrl && null !== $redirect = $this->getRedirect($http_response_header)) {
            return $this->getFileGetContentsContent($redirect, $followUrl);
        }

        return $content;
    }

    private function getRedirect(array $info)
    {
        if (preg_match('/^HTTP\/[0-9.]+ (301|302)/', $info[0])) {
            foreach ($info as $header) {
                if (0 === strpos($header, 'Location: ')) {
                    return str_replace('Location: ', '', $header);
                }
            }
        }

        return null;
    }

    private function testCurl()
    {
        $start = microtime(true);
        $this->getCurlContent($this->url, $this->followUrl);

        return microtime(true) - $start;
    }

    private function getCurlContent($url, $followUrl)
    {
        $curl = curl_init();
        curl_setopt($curl, CURLOPT_URL, $url);
        curl_setopt($curl, CURLOPT_BINARYTRANSFER, 1);
        curl_setopt($curl, CURLOPT_RETURNTRANSFER, true);
        curl_setopt($curl, CURLOPT_FOLLOWLOCATION, $followUrl);
        curl_setopt($curl, CURLOPT_CONNECTTIMEOUT, 10);
        $content = curl_exec($curl);
        $cInfo = curl_getinfo($curl);
        curl_close($curl);

        if (!$followUrl && '' !== $cInfo['redirect_url']) {
            return $this->getCurlContent($cInfo['redirect_url'], $followUrl);
        }

        return $content;
    }
}

// google.com redirect to google.fr

$test1 = new TestPerf(true,  false, 'https://www.google.com');
$test2 = new TestPerf(false, false, 'https://www.google.com');
$test3 = new TestPerf(true,  true,  'https://www.google.com');
$test4 = new TestPerf(false, true,  'https://www.google.com');

$test5 = new TestPerf(true,  false, 'https://www.google.fr');
$test6 = new TestPerf(false, false, 'https://www.google.fr');
$test7 = new TestPerf(true,  true,  'https://www.google.fr');
$test8 = new TestPerf(false, true,  'https://www.google.fr');


echo PHP_EOL.PHP_EOL;
echo '***************************'.PHP_EOL;
echo '*                         *'.PHP_EOL;
echo '*   URL with redirection  *'.PHP_EOL;
echo '*                         *'.PHP_EOL;
echo '***************************'.PHP_EOL;
echo PHP_EOL.PHP_EOL;

$avg1 = $test1->run();
$avg2 = $test2->run();
$avg3 = $test3->run();
$avg4 = $test4->run();

echo PHP_EOL.PHP_EOL;
echo '***************************'.PHP_EOL;
echo '*                         *'.PHP_EOL;
echo '* URL without redirection *'.PHP_EOL;
echo '*                         *'.PHP_EOL;
echo '***************************'.PHP_EOL;
echo PHP_EOL.PHP_EOL;

$avg5 = $test5->run();
$avg6 = $test6->run();
$avg7 = $test7->run();
$avg8 = $test8->run();

echo PHP_EOL.PHP_EOL;
echo '****************************************'.PHP_EOL;
echo '*                                      *'.PHP_EOL;
echo '*                RESULTS               *'.PHP_EOL;
echo '*                                      *'.PHP_EOL;
echo '* (against the current implementation) *'.PHP_EOL;
echo '*                                      *'.PHP_EOL;
echo '****************************************'.PHP_EOL;
echo PHP_EOL.PHP_EOL;

echo 'RemoteFileSystem can be up to:'.PHP_EOL;

echo PHP_EOL.sprintf('  URL with redirection | CURL auto redirect:   %sx faster', round($avg1 / $avg3 * 10) / 10).PHP_EOL;
echo PHP_EOL.sprintf('  URL with redirection | CURL manual redirect: %sx faster', round($avg1 / $avg4 * 10) / 10).PHP_EOL;
echo PHP_EOL.sprintf('  Direct URL           | CURL auto redirect:   %sx faster', round($avg1 / $avg7 * 10) / 10).PHP_EOL;
echo PHP_EOL.sprintf('  Direct URL           | CURL manual redirect: %sx faster', round($avg1 / $avg8 * 10) / 10).PHP_EOL;
```

**Comment by Seldaek** [comment] 2016-04-15 17:33
Closing as duplicate of a bunch of others about parallel downloads and such.

**Closed by Seldaek** 2016-04-15 17:33 UTC
Labels: Feature
