### ISSUE TITLE
Syntax errors in `autoload_static.php` (PHP < 5.6)

### ISSUE THREAD

**Issue by mgburns** [composer/composer#5407] opened 2016-06-05 13:36 UTC
I'm using Composer to manage dependencies for a WordPress project for a client hosted on WP Engine.

After upgrading to Composer 1.1.0 our deployments started failing due to PHP syntax errors. We're deploying code using their [Git Push](https://wpengine.com/git/) method, which has a `post-receive` hook that runs all changed files through `php -l` to check for syntax errors. We have a custom deploy script that runs `composer install` locally (with `config.platform.php` set to `5.3.29` as WP Engine is very behind) and then commits and pushes the build to their remotes.

The file that is causing the failure is `autoload_static.php` (introduced in [1.1.0-RC](https://github.com/composer/composer/releases/tag/1.1.0-RC)). It looks like that file assumes PHP 5.6 (regardless of which version of PHP you're running `composer install` with) as it uses scalar expressions in all of the static property initializers:

```php
// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit55ee1fe9ded343dc8de3a805d154a4ba
{
    public static $files = array (
        'cb78221880aa21d756cc44a8539bb425' => __DIR__ . '/..' . '/timber/timber/init.php',
    );
```

I rolled Composer back to 1.0.3 as a workaround, but feel that Composer shouldn't be generating files with syntax errors for the platform it's installing on.

**Comment by Taluu** [comment] 2016-06-05 14:05
The autoload_static file is loaded only if the optimize option has been activated and if it is php >= 5.6. You shouldn't run `php -l` on vendors file (And thus autoload files generated by composer), as it is not used...

**Comment by mgburns** [comment] 2016-06-05 14:13
The `php -l` checks are out of my control (they're run by WP Engine), but I'm not sure why you say they shouldn't be run against vendor files -- I'd want to know if they have syntax errors just like any other file included in my application.

I do concede that a static syntax check may catch false-positives due to runtime conditionals but regardless I still believe a better approach here is to not generate a file that can't be loaded for the target platform. I'm open to suggestions for things that I could do on my end to more cleanly work around this, but sticking with an older version of Composer does not seem like a good solution.

**Comment by staabm** [comment] 2016-06-05 16:25
Duplicate of https://github.com/composer/composer/issues/5316 https://github.com/composer/composer/issues/5255

**Closed** 2016-06-05 18:52 UTC

**Comment by jb510** [comment] 2016-08-19 13:32
@mgburns same issue, but the tree to bark up _is_ WP Engine's.  Their syntax checker on git push should have a way to be over ridden and doesn't.  Either when it scans with comments (this is for Squizlabs PHP Code Sniffer) like:
// @codingStandardsIgnoreStart
stuff goes here
// @codingStandardsIgnoreEnd

or file/folder ignores in something like a .wpe-config file.

Personally when this happens I .gitignore and untrack the plugin in question and then install it directly (dashboard, ftp or wp cli all of which bypasses the syntax check).

While we too normally include plugins in repos, there isn't really a ton of benefit to having code you didn't author in your repo...  more and more I just ignore everything that isn't custom code.
