### ISSUE TITLE
Project rollback after Composer\Downloader\TransportException not done

### ISSUE THREAD

**Issue by gisoconnectholland** [composer/composer#4335] opened 2015-08-06 09:18 UTC
After a failure (Composer\Downloader\TransportException) while downloading a new version of a package the previous version is not restored. This is due to the fact a package is removed before installing the new version. In my opinion it should be moved aside and be removed after successful installation of the new version.

This is what happens now:
  - Removing vendorname/package (1.0.0)
  - Installing vendorname/package (1.0.1)

When a Composer\Downloader\TransportException occurs while installing 1.0.1 is_dir('vendor/vendorname/package') becomes false

**Comment by alcohol** [comment] 2015-08-06 13:58
Not sure how easy or complicated it would be to make the update flow transactional.

**Comment by stof** [comment] 2015-08-06 14:19
@alcohol almost impossible IMO, as we would have to make the whole installation in a separate location and then replace packages atomically. but only files can be moved atomically on a filesystem, not several folders AFAICT.

**Comment by gisoconnectholland** [comment] 2015-08-06 14:21
I understand.
It might be a solution to inform about this when an exception occurs. Best solutions seems to use version control to revert composer.lock and perform a composer install. At this moment it is unclear the project might be in an unstable state.

The message could be something like:
"The exception that occurred might have left your project in an unstable state. If so and when possible revert to the previous lock-file and run composer install"

**Comment by alcohol** [comment] 2015-08-06 14:21
Maybe it could be done for each individual step. But then you would just end up with a semi-updated application, which would be just as pointless.

**Comment by gisoconnectholland** [comment] 2015-08-06 14:23
Ok, an exception is a kind of unstable state :)

But it is unclear that a whole package might be missing and what can be done about it.

**Comment by Seldaek** [comment] 2015-08-09 23:04
I guess we could wrap the whole operation execution loop in the Installer class in a try/catch to output a bit more user-friendly stuff in case it fails somewhere.

**Comment by Seldaek** [comment] 2016-04-18 21:28
Closing as duplicate of #2880

**Closed by Seldaek** 2016-04-18 21:28 UTC
Labels: Easy Pick, Feature
