### ISSUE TITLE
[Regression] class loading does not work since 2.1.0-RC1

### ISSUE THREAD

**Issue by williamdes** [composer/composer#9946] opened 2021-06-05 16:42 UTC
Using composer 2.0.12 it works fine and starting with 2.1.0-RC1 and all the next ones it does not work anymore

Example fail: https://github.com/phpmyadmin/phpmyadmin/runs/2753645987?check_suite_focus=true#step:13:672

See pass/fails: https://github.com/phpmyadmin/phpmyadmin/actions/workflows/other-tools.yml?query=branch%3AQA_5_1

On the phpMyAdmin release script we create a sandbox folder for phpunit: https://github.com/phpmyadmin/phpmyadmin/blob/QA_5_1/scripts/create-release.sh#L234

And then we run phpunit using it's path in the actual bundled release: https://github.com/phpmyadmin/phpmyadmin/blob/QA_5_1/scripts/create-release.sh#L440

Now it throws a strange error `Uncaught Error: Class 'PhpMyAdmin\Tests\Stubs\DbiDummy' not found in /home/runner/work/phpmyadmin/phpmyadmin/release/phpMyAdmin-ci/test/bootstrap-dist.php:54`:
https://github.com/phpmyadmin/phpmyadmin/runs/2745731618?check_suite_focus=true#step:13:628

As you can see we require the autoloader file before calling the actual code: https://github.com/phpmyadmin/phpmyadmin/blob/QA_5_1/test/bootstrap-dist.php#L46

It never failed before, and now that all composer binaries are updated, it fails everywhere we test it

**Comment by mauriciofauth** [comment] 2021-06-05 18:20
Related to #9714.

**Comment by GrahamCampbell** [comment] 2021-06-05 18:34
I think this was fixed in 2.1.1?

**Comment by williamdes** [comment] 2021-06-05 19:58
> I think this was fixed in 2.1.1?

Hi
It is not fixed unfortunately

**Comment by Seldaek** [comment] 2021-06-06 19:29
I have a feeling the issue is because of a weird interaction between:

https://github.com/phpmyadmin/phpmyadmin/blob/master/scripts/create-release.sh#L410

Which does --update-no-dev, so that skips dumping the dev autoloads which means `PhpMyAdmin\\Tests\\` is not autoloadable..

Then this line https://github.com/phpmyadmin/phpmyadmin/blob/master/scripts/create-release.sh#L435 calls into https://github.com/phpmyadmin/phpmyadmin/blob/master/scripts/create-release.sh#L238 which ultimately does a require of phpunit, which I assume was previously dumping the autoloader again including dev autoload rules, and this should too but perhaps it doesn't anymore.

**Comment by Seldaek** [comment] 2021-06-06 19:36
I can't reproduce it like that though, the last `require` without `--update-no-dev` dumps autoload-dev rules correctly.. So I am not entirely sure what is going on, but you do so many installs in a row I believe it's related to that somehow.

**Comment by Seldaek** [comment] 2021-06-06 19:43
Oh sorry, the phpunit require happens in a different directory.. So https://github.com/phpmyadmin/phpmyadmin/blob/master/scripts/create-release.sh#L410 using `--update-no-dev` definitely seems to be the culprit.

This broke due to https://github.com/composer/composer/pull/9714 because you then do a `dump-autoload` at https://github.com/phpmyadmin/phpmyadmin/blob/master/scripts/create-release.sh#L439 and it now does not include your autoload-dev rules anymore because the dev dependencies are not installed.

We do not have a way to force autoload-dev  rules to be dumped though in dump-autoload.. So for now the workaround would be to use `composer install` instead of `composer dump-autoload`, which will install your dev dependencies and redump the autoloader including dev dependencies and your autoload-dev rules.

If you do see a real use case for having a vendor dir without require-dev dependencies, but with your autoload-dev rules, I'd be interested in the details of that.. IMO if you run dev stuff you should have the dev dependencies installed. In this instance you install phpunit in another dir so it kinda skews this by bypassing require-dev. But if there's a valid case I guess we could add a `--dev` flag to `dump-autoload`.

**Comment by williamdes** [comment] 2021-06-06 20:38
Hi !
I am not sure the use case has been understood, let me explain it.
The problem: how can I test my bundled release without altering it ?
Solution: `create_phpunit_sandbox` create a phpunit sandbox to only install phpunit in a folder outside of the built release, and then use it to run the tests. (BUT: copy the requirement text from require-dev to be sure the installed phpunit is compatible)

It's simple but this needs to work, and phpunit can not be installed in the release bundle dir.

Is it more clear explained this way ?

**Comment by Seldaek** [comment] 2021-06-07 12:07
Yes, that explains why you do this, thanks :)

Perhaps one misunderstanding on your end though is that installing your dev requirements again does not alter your `require`, but it does make more packages available, which may mean that your tests pass even though they would not without require-dev in case some of your code inadvertently depends on some code from a dev dependency. That may still be the case if you implicitly depend on something that phpunit also depends on though, so the safe way to check for this IMO is to use https://packagist.org/packages/maglnet/composer-require-checker - not to require phpunit in a separate directory.

Makes sense?

**Comment by williamdes** [comment] 2021-06-07 13:01
Hi

> not to require phpunit in a separate directory.

We need to do this, any composer command would screw up the vendor folder we ship to our users

To clarify, lets say version X supports phpunit 7 and 8, we just pick the string that contains the composer expression to only allow 7 and 8 and then in a separate folder we install phpunit. This is just to be sure we do not run the testsuite using a non compatible with the release phpunit.

> in case some of your code inadvertently depends on some code from a dev dependency

We build checks to skip if missing dev-deps are not available, just like when the tests are run by Debian packaging teams.
They do not care if the console works, only core phpMyAdmin devs use it, so it is not usefull to have the tests run for it. So we have some tests that are skipped.

The installed code in the vendor dir is production ready, then we need a working and compatible phpunit to run the tests on the ready to be uploaded release containing the vendor folder.

Maybe this helps understand why we just and only need to have a working phpunit in a folder somewhere :)

**Closed** 2021-06-07 13:48 UTC

**Comment by Seldaek** [comment] 2021-06-07 13:50
> We need to do this, any composer command would screw up the vendor folder we ship to our users

I would say you could archive *before* you run `composer install` to restore dev dependencies, so as to avoid screwing up the archive.. Or you could install fully, run tests, then `composer install --no-dev` to remove dev dependencies before archiving if the tests passed. Then you would still not need the phpunit in a separate directory.

Anyway I can see why someone may under weird circumstances want autoload-dev active even though dev requirements are not installed, so I added a flag and you can now call `composer dump-autoload --dev` to ensure you get autoload-dev included. This will however "screw up" your  vendor dir too in a sense as it makes things autoloadable which IMO shouldn't be in a prod context, so I would still advise you to take a good look at my first paragraph here :) This'll be in 2.1.2 which I'll go and release now.

**Comment by williamdes** [comment] 2021-06-07 15:02
Thank you @Seldaek !

> I would say you could archive before you run composer install to restore dev dependencies, so as to avoid screwing up the archive.. Or you could install fully, run tests, then composer install --no-dev to remove dev dependencies before archiving if the tests passed. Then you would still not need the phpunit in a separate directory.

Well we could indeed to that, but I have to look if it is possible because we first install the vendor folder and the do some requires  using the constraints from the require-dev to require some optional things like tcpdf.
Making the installed vendor bundle not the exact same as if you just had installed it from composer.json


> This will however "screw up" your vendor dir 

Got it, that will probably be easier than installing basic and then installing back the additional packages a second time to have the vendor folder clean once more


Thank you for your patience, I will let you know how it goes in the end :)

**Comment by Seldaek** [comment] 2021-06-07 15:09
Just as a hint in case you didn't see it, when using composer require you can also pass --dev to add it to require-dev, making sure whatever req you add it'll be removed when doing an install --no-dev.

**Comment by williamdes** [comment] 2021-06-07 15:38
Just tested and the fix is quite slim thanks to you: https://github.com/phpmyadmin/phpmyadmin/commit/1397588a17da297fea8cfd001db76fdecb4f07e3

I just changed `composer dump-autoload` into `composer dump-autoload --dev` and after tests ran `composer dump-autoload`.

To detail our process for the record (a bit simplified):
- require the minimal php version extracted from the php require restriction `composer config platform.php "$PHP_REQ"`
- install without dev modules `composer update --no-interaction --no-dev --optimize-autoloader`
- install optional packages in the vendor folder `composer require --no-interaction --optimize-autoloader --update-no-dev $PACKAGES_VERSIONS`
- restore original composer.json because previous commands have affected it
- do things
- clean up vendor folders and files nobody cares about in production (`.github`, `tests` folders, and so much more crap)
- create the phpunit test sandbox
- backup vendor folder (not usefull but more security is good)
- dump autoload in dev mode to make test classes load nicely (thanks !!)
- run tests
- dump it back
- restore vendor folder
- do things

Finished !!

**Comment by Seldaek** [comment] 2021-06-07 15:51
Ok, I'd perhaps recommend using --no-dev explicitly on the last dump-autoload just for making it more self documenting but otherwise looks good I guess :)

**Comment by mauriciofauth** [comment] 2021-06-07 16:34
Thank you very much, @Seldaek.

**Comment by williamdes** [comment] 2021-06-07 16:45
`array_shift(https://seld.be/wishlist)`
