### ISSUE TITLE
packagist.org resetting connection which more than 23 seconds

### ISSUE THREAD

**Issue by astasoft** [composer/composer#5207] opened 2016-04-17 03:48 UTC
When I run this command:

```
composer require "laravel/installer" -vvv
```

I get this output:

```
Reading ./composer.json
Loading config file /home/astadev/.config/composer/config.json
Loading config file /home/astadev/.config/composer/auth.json
Loading config file ./composer.json
Checking CA file /etc/ssl/certs/ca-certificates.crt
Executing command (/home/astadev/htdocs/php-apps/laravel-installer): git branch --no-color --no-abbrev -v
Executing command (/home/astadev/htdocs/php-apps/laravel-installer): git describe --exact-match --tags
Reading /home/astadev/.config/composer/composer.json
Loading config file /home/astadev/.config/composer/config.json
Loading config file /home/astadev/.config/composer/auth.json
Loading config file /home/astadev/.config/composer/composer.json
Loading config file /home/astadev/.config/composer/auth.json
Downloading https://packagist.org/packages.json
Writing /home/astadev/.cache/composer/repo/https---packagist.org/packages.json into cache
Downloading https://packagist.org/p/provider-2013%247a4fde96465d7ca86bb80f6012233148192e7ada15222e242afd7bdabd68f073.json
Writing /home/astadev/.cache/composer/repo/https---packagist.org/p-provider-2013.json into cache
Downloading https://packagist.org/p/provider-2014%24e5a076f036bbca3ad2d7d1d7c2f1694876852d22ee4b64a39648014e2b1534da.json
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
Downloading https://packagist.org/p/provider-2014%24e5a076f036bbca3ad2d7d1d7c2f1694876852d22ee4b64a39648014e2b1534da.json
Downloading https://packagist.org/p/provider-2014%24e5a076f036bbca3ad2d7d1d7c2f1694876852d22ee4b64a39648014e2b1534da.json
Downloading https://packagist.org/p/provider-2014%24e5a076f036bbca3ad2d7d1d7c2f1694876852d22ee4b64a39648014e2b1534da.json


  [ErrorException]           
  zlib_decode(): data error  


Exception trace:
 () at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Util/RemoteFilesystem.php:358
 Composer\Util\ErrorHandler::handle() at n/a:n/a
 zlib_decode() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Util/RemoteFilesystem.php:358
 Composer\Util\RemoteFilesystem->get() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Util/RemoteFilesystem.php:99
 Composer\Util\RemoteFilesystem->getContents() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Repository/ComposerRepository.php:644
 Composer\Repository\ComposerRepository->fetchFile() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Repository/ComposerRepository.php:557
 Composer\Repository\ComposerRepository->loadProviderListings() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Repository/ComposerRepository.php:288
 Composer\Repository\ComposerRepository->whatProvides() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/DependencyResolver/Pool.php:204
 Composer\DependencyResolver\Pool->computeWhatProvides() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/DependencyResolver/Pool.php:193
 Composer\DependencyResolver\Pool->whatProvides() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Package/Version/VersionSelector.php:52
 Composer\Package\Version\VersionSelector->findBestCandidate() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Command/InitCommand.php:633
 Composer\Command\InitCommand->findBestVersionForPackage() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Command/InitCommand.php:365
 Composer\Command\InitCommand->determineRequirements() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Command/RequireCommand.php:108
 Composer\Command\RequireCommand->execute() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Console/Application.php:181
 Composer\Console\Application->doRun() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///home/astadev/htdocs/php-apps/composer/composer.phar/bin/composer:43
 require() at /home/astadev/htdocs/php-apps/composer/composer.phar:24

require [--dev] [--prefer-source] [--prefer-dist] [--no-plugins] [--no-progress] [--no-update] [--update-no-dev] [--update-with-dependencies] [--ignore-platform-reqs] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--] [<packages>]...
```

And I expected this to happen:
Laravel installer are correctly installed even on slow network.

**Debugging:**

To make sure I will not have the same issue with #4121 and #4892 I hit the IPv4 packagist directly.

This is the output in my computer.

```
$ for (( i=0; i<3; i++ )); 
do     
    curl -H 'Host: packagist.org' http://87.98.253.214/p/provider-2014%24e5a076f036bbca3ad2d7d1d7c2f1694876852d22ee4b64a39648014e2b1534da.json > /dev/null ; echo "";
done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 10 1717k   10  185k    0     0   7962      0  0:03:40  0:00:23  0:03:17  7161
curl: (56) Recv failure: Connection reset by peer

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 10 1717k   10  176k    0     0   7584      0  0:03:51  0:00:23  0:03:28  9011
curl: (56) Recv failure: Connection reset by peer

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 10 1717k   10  173k    0     0   7485      0  0:03:54  0:00:23  0:03:31  8912
```

It always fails at seconds 23rd **Recv failure: Connection reset by peer**. I also try the https version and put the IP of packagist.org to /etc/hosts. The result was same, because the server terminate the client connection.

```
$ for (( i=0; i<3; i++ )); do     curl -H 'Host: packagist.org' https://packagist.org/p/provider-2014%24e5a076f036bbca3ad2d7d1d7c2f1694876852d22ee4b64a39648014e2b1534da.json > /dev/null ; echo ""; done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 10 1717k   10  175k    0     0   7321      0  0:04:00  0:00:24  0:03:36  7469
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  9 1717k    9  159k    0     0   6797      0  0:04:18  0:00:24  0:03:54  7190
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  9 1717k    9  159k    0     0   6814      0  0:04:18  0:00:24  0:03:54  7206
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
```

@Seldaek Do you have explanation for this one? 

I don't have this problem for other files outside packagist.org even the download time takes hours.

For curiosity I try to run the command my VPS hosted on Linode.

```
# for (( i=0; i<3; i++ )); do     curl -H 'Host: packagist.org' http://87.98.253.214/p/provider-2014%24e5a076f036bbca3ad2d7d1d7c2f1694876852d22ee4b64a39648014e2b1534da.json > /dev/null ; echo ""; done
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1717k  100 1717k    0     0   237k      0  0:00:07  0:00:07 --:--:--  294k

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1717k  100 1717k    0     0   239k      0  0:00:07  0:00:07 --:--:--  295k

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1717k  100 1717k    0     0   268k      0  0:00:06  0:00:06 --:--:--  351k
```

It's run fine on my linode because it took under 23 seconds (but I think 7secs for 1,7MB of file which I considered slow in fast network).

```
$ composer --version
Composer version 1.0.0 2016-04-05 13:27:25

$ uname -a
Linux vaio 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by Seldaek** [comment] 2016-04-18 10:30
This seems to be network related.. Best is to check a traceroute to our IP and see where it gets slow.

**Comment by astasoft** [comment] 2016-04-18 15:31
I don't think this is the routing issue, because I can reach the packagist.org (87.98.253.214) without any problem. I can always connect to either port 80 or 443 to the server.

```
 $ traceroute -n packagist.org
traceroute to packagist.org (87.98.253.214), 30 hops max, 60 byte packets
 1  192.168.0.1  16.775 ms  16.729 ms  17.031 ms
 2  * * *
 3  * * *
 4  * * *
 5  180.240.193.109  210.073 ms 118.98.84.209  136.551 ms  136.604 ms
 6  180.240.192.74  307.918 ms  307.203 ms  295.269 ms
 7  180.240.193.157  131.988 ms 206.72.210.214  243.078 ms 180.240.193.157  65.020 ms
 8  198.27.73.191  304.704 ms  297.645 ms 180.240.192.74  223.587 ms
 9  206.72.210.214  215.635 ms  220.523 ms 192.99.146.132  391.193 ms
10  91.121.128.92  378.535 ms  378.692 ms  386.751 ms
11  37.187.36.197  372.760 ms  369.827 ms 178.32.135.231  383.766 ms
12  37.187.231.88  372.431 ms 91.121.128.92  374.934 ms 37.187.231.88  386.814 ms
13  37.187.36.197  400.732 ms  371.919 ms  385.735 ms
14  87.98.253.214  391.717 ms  392.086 ms 37.187.231.88  367.734 ms
```

If you see on the curl example on my initial post, it successfully establish the connection to packagist.org and starting to download. After 23 seconds the download always interrupted because it get reset by the peer (packagist.org). That's why the data is corrupted and it raise the zlib decoding error.

I try to download different URL (https://phar.phpunit.de/phpunit-4.8.24.phar) using curl to make sure it is not my network problem. And it was successful even it takes more than 10 minutes to download the file and it's not reset after 23 seconds.

**Comment by curry684** [comment] 2016-04-18 23:59
I've tried to reproduce this from a Gbit server in the Netherlands using `trickle` to shape the traffic down to 10KBps:
```sh
$ time trickle -d 10 wget https://packagist.org/packages/symfony/symfony.json
--2016-04-19 01:53:30--  https://packagist.org/packages/symfony/symfony.json
Resolving packagist.org (packagist.org)... 87.98.253.214, 2001:41d0:a:7b19::3
Connecting to packagist.org (packagist.org)|87.98.253.214|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [application/json]
Saving to: `symfony.json'

    [                  <=>               ] 489,763     10.8K/s   in 45s

2016-04-19 01:54:16 (10.7 KB/s) - `symfony.json' saved [489763]

real    0m46.100s
user    0m0.256s
sys     0m0.060s
```
Successful after 46 seconds, so I'm afraid the 23 second limit isn't imposed anywhere near the Packagist endpoint on the network.

You have multiple network issues though, even inside your own LAN judging from your trace:
```sh
 1  192.168.0.1  16.775 ms  16.729 ms  17.031 ms
```
17ms to get to your local router is an awful lot - that should be 0.5ms max for wired or 4ms max for wireless.

**Comment by astasoft** [comment] 2016-04-19 06:39
CMIIW but I think for download shaping the user space tool like `trickle` is not doing the job since all the packets actually already arrive on our network if your real connection is more than the size of the file. The user space tools may come into the play for upload shaping.

To prove my assumption, I ask my network admin to shape my computer traffic to 56kbps and this is the result after twice trying download from packagist.org. We are having up-to 20Mps bandwidth.

**Result of Shaping on Network Layer**
```
$ curl https://packagist.org/p/provider-2015%242c34bc95710925389fe4c85768c2a1c5e1703ca178d3a49b769385cdfcd491a3.json > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 27 1495k   27  415k    0     0   4246      0  0:06:00  0:01:40  0:04:20 21213
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104

$ curl https://packagist.org/p/provider-2015%242c34bc95710925389fe4c85768c2a1c5e1703ca178d3a49b769385cdfcd491a3.json > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
 23 1495k   23  351k    0     0   3706      0  0:06:53  0:01:37  0:05:16     0
curl: (56) SSL read: error:00000000:lib(0):func(0):reason(0), errno 104
```

It fails.

And then I ask the network admin to release the shaping on my computer and I use trickle to shape the packagist.org network. I use 8KB/s (56kbps).

**Result of Shaping on Application Layer (trickle)**
```
$ trickle -d 8 curl -o /dev/null "https://packagist.org/p/provider-2015%242c34bc95710925389fe4c85768c2a1c5e1703ca178d3a49b769385cdfcd491a3.json" 
trickle: Could not reach trickled, working independently: No such file or directory
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1495k  100 1495k    0     0   8790      0  0:02:54  0:02:54 --:--:-- 14331
```

It succeed. So same end point but different results because of User space tool vs Network layer shape. Since packagist.org using Toran Proxy, does Toran causing the cut of the connection?

**Comment by curry684** [comment] 2016-04-19 07:02
Toran doesn't do anything of the kind to my knowledge, but that's for @Seldaek to answer - I've never used or seen Toran hehe. The network/application difference is possible but your test is still not really conclusive to that end. Having a hard time to think of a test that is though.

**Comment by Seldaek** [comment] 2016-04-19 09:21
Toran doesn't run in front of packagist, it's just supporting it in a way of financial means :) At the nginx level the only thing I see that might impact slow connections is this:

```
    send_timeout 20; // Sets a timeout for transmitting a response to the client. The timeout is set only between two successive write operations, not for the transmission of the whole response. If the client does not receive anything within this time, the connection is closed.
```

So if you don't receive *anything* for 20 seconds it will drop you, but that's it. I think that's a reasonable setting tbh.

**Comment by astasoft** [comment] 2016-04-23 10:11
@Seldaek But on my test on using network layer shaping, the packets always sents every seconds even at rate 8KB/s. So, in theory the server should not cut the connection right?

**Comment by Seldaek** [comment] 2016-04-26 12:38
That's right yes. I have no idea what's going on tbh but I also don't see what we can do about it right now.

**Comment by Seldaek** [comment] 2017-01-22 19:07
Auto-closing as this hasn't been updated in over 6months and is marked as a support request. If there is a real bug to consider please let us know.

**Closed by Seldaek** 2017-01-22 19:07 UTC
Labels: Support
