### ISSUE TITLE
exclude-from-classmap: ['pa/'] excludes 'path/'

### ISSUE THREAD

**Issue by drjayvee** [composer/composer#8563] opened 2020-01-30 14:15 UTC
I have a little [test repo](https://github.com/drjayvee/composer-autoload/) to demonstrate a problem with `exclude-from-classmap`

The project's files are:
```
src/
  li/OtherClass.php
  lib/MyClass.php
```

My `composer.json`:
```json
{
    "name": "drjayvee/composer-autoload",
    "autoload": {
        "classmap": ["src"],
        "exclude-from-classmap": [
            "src/li"
        ]
    },
    "require": {}
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: FAIL
Missing pubkey for tags verification
Missing pubkey for dev verification
Run composer self-update --update-keys to set them up
Checking composer version: OK
Composer version: 1.9.2
PHP version: 7.3.14
PHP binary path: /usr/bin/php7.3
```

When I run this command:

```
composer dumpautoload
```

I get the following output:

```
Generated autoload files containing 0 classes
```

And I expected this to happen:
```
Generated autoload files containing 1 classes
```

**Comment by stof** [comment] 2020-01-30 14:59
well, can you try with `src/li/` ? Your issue title says that using `pa/` exclude `path/`, but that's precisely *not* what your composer.json does.

**Comment by drjayvee** [comment] 2020-01-30 15:02
I have tried that (should have mentioned that). `lib` still is excluded. I've updated my repo with that change.

Also, I would actually expect `src/li*` to exclude `src/lib`, but not `src/li`.

**Comment by alcohol** [comment] 2020-02-04 08:36
Could you maybe expand the test found here with a reproducible case so we can fix it?

https://github.com/composer/composer/blob/502b68967ac7998f2479a7d0b51fc25548cb6a8e/tests/Composer/Test/Autoload/AutoloadGeneratorTest.php#L1509

**Comment by alcohol** [comment] 2020-02-04 08:39
It is probably a real bug though;  looking at https://github.com/composer/composer/blob/e9c7e253f456190afe67e9ab88a51b3509c5cb97/src/Composer/Autoload/AutoloadGenerator.php#L234 it seems we generate a grouping of all exclude values, with no fixed start or end, so any "in-string" match will succeed.

**Comment by drjayvee** [comment] 2020-02-04 08:46
You can check out [this repo](git@github.com:drjayvee/composer-autoload.git) and run
```
$ composer dumpautoload
Generated autoload files containing 0 classes
```

**Comment by alcohol** [comment] 2020-02-04 09:13
It seems https://github.com/composer/composer/blob/master/src/Composer/Autoload/AutoloadGenerator.php#L877-L906 strips the trailing `/`, hence you end up with a regex that looks for `src/li`. @Seldaek does this qualify as a bug?

**Comment by drjayvee** [comment] 2020-02-04 09:28
Which trailing slash do you mean exactly?

Both `li` and `li/` cause `lib` to be excluded.

@stof also asked me to try including the trailing slash in the path name.

Just to be clear, I would very much expect the trailing slash to be irrelevant.
```
{"exclude-from-classmap": ['li']}
```

Actually, the [documentation](https://getcomposer.org/doc/04-schema.md#exclude-files-from-classmaps) might need some clarification:
> The classmap generator will ignore '''all files in the paths''' configured here.
(emphasis mine)

Apparently, `exclude-from-classmap` is a list of folders? Is it therefore not possible to exclude individual files? If it is folders only, then trailing slash should be irrelevant, right?

**Comment by alcohol** [comment] 2020-02-04 09:34
> Which trailing slash do you mean exactly?

This one
```
"exclude-from-class": ["src/li/"]
```
gets dropped in the process of parsing it.


> I would very much expect the trailing slash to be irrelevant.

Except for the `preg_match` call we make, it is **very** relevant. Since without the trailing `/`, `src/li` will match `src/li<ANYTHINGELSEHERE>`.

**Comment by alcohol** [comment] 2020-02-04 09:36
```
<?php

var_dump(
    (bool) preg_match('{src/li}', 'src/lib/Class.php'),
    (bool) preg_match('{src/li/}', 'src/lib/Class.php')
);
```
```
bool(true)
bool(false)
```

**Comment by drjayvee** [comment] 2020-02-04 09:38
I meant that from _user's_ point of view
```
"exclude-from-classmap": ["src/li"]
```
and
```
"exclude-from-classmap": ["src/li/"]
```
should be identical. (But that's my opinion)

**Comment by alcohol** [comment] 2020-02-04 09:40
That is debatable, and while I would personally agree, it does not change anything about the fact that the behaviour/implementation currently seems to be broken.

**Comment by drjayvee** [comment] 2020-02-04 09:40
Maybe the quickest fix is to implicitly add the missing trailing slash to all paths during evaluation.

However, you observation doesn't explain why even `li/` excludes `lib/`, right?

**Comment by alcohol** [comment] 2020-02-04 09:41
My observation explains it perfectly. The `/` gets discarded so basically `src/li/` always gets interpreted as `src/li`.

**Comment by drjayvee** [comment] 2020-02-04 09:45
Sorry, I misunderstood. Trailing slashes always get discarded, got it.

So what would be the desired functionality? You're saying that it's debatable whether `li` and `li/` should be identical. But if they should not be, then what is the difference? Are you saying `li` should _only_ matches files, while `li/` _only_ matches directories (i.e. matches (`li/**`)?

That's not at all the impression I get from the documentation.

**Comment by alcohol** [comment] 2020-02-04 09:48
I'm saying it is broken and it should be fixed. Implementation details such as whether `src/li` and `src/li/` should be treated identical are irrelevant to me and a matter for discussion in another separate issue.

**Comment by drjayvee** [comment] 2020-02-04 09:56
Ok, fair enough!

Seems like changing `trim` to `ltrim` would solve the problem. That would still remove leading slashes, while leaving trailing ones intact.

**Comment by alcohol** [comment] 2020-02-04 11:25
That seems like the most likely solution to me, yeah. But if you want to wait for @Seldaek to weigh in that is fine too. Otherwise you can go ahead and submit a PR.

**Comment by drjayvee** [comment] 2020-02-04 11:35
Since I don't know the code at all, I'm hesitant to make that change.

I'd be happy to try and write a test, though! I'll see if I can find my way around the repo.

**Comment by drjayvee** [comment] 2020-02-04 11:59
There you go! My PR targets master, which is probably not where this should land.

**Comment by Seldaek** [comment] 2020-02-04 12:20
master is fine in this case, and yes it seems like a bug.

**Closed** 2020-02-12 09:24 UTC
Labels: Bug
