### ISSUE TITLE
Composer can't resolve constraint with `~`

### ISSUE THREAD

**Issue by IchHabRecht** [composer/composer#7063] opened 2018-01-30 22:29 UTC
My `composer.json`:

```json
{
    "require": {
        "typo3/cms-extbase": "*",
        "typo3/cms-fluid": "*",
        "typo3/cms-frontend": "*",
        "typo3/cms-install": "*",
        "nimut/typo3-complete": "~9.0.0"
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
require.typo3/cms-extbase : unbound version constraints (*) should be avoided
require.typo3/cms-fluid : unbound version constraints (*) should be avoided
require.typo3/cms-frontend : unbound version constraints (*) should be avoided
require.typo3/cms-install : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 1.6.2
PHP version: 7.2.0
PHP binary path: C:\Unix\PHP-7.2.0-x64\php.exe
```

When I run this command:

```
composer install
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - nimut/typo3-complete v9.0.0 requires typo3/cms-context-help ~9.0.0 -> no matching package found.
    - nimut/typo3-complete v9.0.1 requires typo3/cms-extbase ~9.0.0 -> satisfiable by typo3/cms-extbase[v9.0.0].
    - nimut/typo3-complete v9.0.2 requires typo3/cms-extbase ~9.0.0 -> satisfiable by typo3/cms-extbase[v9.0.0].
    - Conclusion: don't install typo3/cms-extbase v9.0.0
    - Installation request for nimut/typo3-complete ~9.0.0 -> satisfiable by nimut/typo3-complete[v9.0.0, v9.0.1, v9.0.2].
```

And I expected this to happen:

As all three available tags were found, I expect Composer to install nimut/typo3-complete 9.0.2. It is installed if I change `"nimut/typo3-complete": "~9.0.0"` explicitly to `"nimut/typo3-complete": "~9.0.2"`

**Comment by Seldaek** [comment] 2018-01-31 14:40
The problem it seems is that `nimut/typo3-complete 9.0.0` requires typo3/cms-context-help and typo3/version in version `~9.0.0` and those versions don't exist. It seems like due to that the solver somehow trips up and ends up failing even though it should have installed 9.0.2 as it sees it as a valid option. Not related to `~` operator IMO but rather inner workings of the solver, and that's pretty hard to debug.

**Comment by IchHabRecht** [comment] 2018-01-31 14:45
Hi @Seldaek,

Thanks for your confirmation. Until the tag 9.1.0 was released yesterday, we required ^9.0 which didn't hat any problem and installed 9.0.1 (latest before yesterday) without any problem.

**Comment by Seldaek** [comment] 2018-01-31 14:46
Yeah the problem is any new release can change the way the solver goes about solving this entirely so I doubt it's really related to the ^ => ~ change which really are very similar internally.

**Comment by IchHabRecht** [comment] 2018-02-01 12:23
Just another information: even requre "nimut/typo3-complete": "9.0.1" fails to be installed though the failing package version should not be fetched anymore. The only constraint that is currently working is "nimut/typo3-complete": "~9.0.2"

**Comment by Seldaek** [comment] 2020-01-31 15:38
Can not repro anymore with 2.0 so closing.

**Closed by Seldaek** 2020-01-31 15:38 UTC
Labels: Bug, Solver
