### ISSUE TITLE
Can't install Composer on Windows 7

### ISSUE THREAD

**Issue by Mugane** [composer/composer#6029] opened 2017-01-03 02:03 UTC
Can't install Composer on Windows 7, getting this install error:

Warning: openssl_verify(): Don't know how to get public key from this private key in C:\Users\mywindowsusername\AppData\Local\Temp\is-3TJF5.tmp\installer.php on line 918

Warning: openssl_verify(): supplied key param cannot be coerced into a public key in C:\Users\mywindowsusername\AppData\Local\Temp\is-3TJF5.tmp\installer.php on line 918
Signature mismatch, could not verify the phar file integrity

**Comment by Mugane** [comment] 2017-01-03 02:24
C:\Users\Ag\Downloads\UniServer\usr\local\php>php -r "copy('https://getcomposer.
org/installer', 'composer-setup.php');"

C:\Users\Ag\Downloads\UniServer\usr\local\php>php -r "if (hash_file('SHA384', 'c
omposer-setup.php') === '61069fe8c6436a4468d0371454cf38a812e451a14ab1691543f25a9
627b97ff96d8753d92a00654c21e2212a5ae1ff36') { echo 'Installer verified'; } else
{ echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
Installer verified
C:\pathto\php>php composer-setup.php
Downloading...

Warning: openssl_verify(): Don't know how to get public key from this private ke
y in C:\pathto\php\composer-setup.php on line 96
4

Warning: openssl_verify(): supplied key param cannot be coerced into a public ke
y in C:\pathto\php\composer-setup.php on line 96
4
Signature mismatch, could not verify the phar file integrity
Retrying...

Warning: openssl_verify(): Don't know how to get public key from this private ke
y in C:\pathto\php\composer-setup.php on line 96
4

Warning: openssl_verify(): supplied key param cannot be coerced into a public ke
y in C:\pathto\php\composer-setup.php on line 96
4
Signature mismatch, could not verify the phar file integrity
Retrying...

Warning: openssl_verify(): Don't know how to get public key from this private ke
y in C:\pathto\php\composer-setup.php on line 96
4

Warning: openssl_verify(): supplied key param cannot be coerced into a public ke
y in C:\pathto\php\composer-setup.php on line 96
4
Signature mismatch, could not verify the phar file integrity
The download failed repeatedly, aborting.

C:\pathto\php>

**Comment by Seldaek** [comment] 2017-01-03 08:58
You can try to run the script by downloading the installer over http instead (basically just put http in the first line instead of https):

```
php -r "copy('http://getcomposer.org/installer', 'composer-setup.php');"
php -r "if (hash_file('SHA384', 'composer-setup.php') === '61069fe8c6436a4468d0371454cf38a812e451a14ab1691543f25a9627b97ff96d8753d92a00654c21e2212a5ae1ff36') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
php composer-setup.php
php -r "unlink('composer-setup.php');"
```

This should at least let you run the installer, and then it might tell you what's wrong with your setup, but it looks like you have an outdated openssl library or the openssl extension is missing completely from your php setup. I'm not sure as openssl errors tend to be pretty cryptic.

**Comment by Mugane** [comment] 2017-01-03 20:39
If it helps, here's the command line output:

C:\Users\Ag\Downloads\UniServer\usr\local\php>php composer-setup.php
Downloading...

Warning: openssl_verify(): Don't know how to get public key from this
private ke
y in C:\Users\Ag\Downloads\UniServer\usr\local\php\composer-setup.php on
line 96
4

Warning: openssl_verify(): supplied key param cannot be coerced into a
public ke
y in C:\Users\Ag\Downloads\UniServer\usr\local\php\composer-setup.php on
line 96
4
Signature mismatch, could not verify the phar file integrity
Retrying...

Warning: openssl_verify(): Don't know how to get public key from this
private ke
y in C:\Users\Ag\Downloads\UniServer\usr\local\php\composer-setup.php on
line 96
4

Warning: openssl_verify(): supplied key param cannot be coerced into a
public ke
y in C:\Users\Ag\Downloads\UniServer\usr\local\php\composer-setup.php on
line 96
4
Signature mismatch, could not verify the phar file integrity
Retrying...

Warning: openssl_verify(): Don't know how to get public key from this
private ke
y in C:\Users\Ag\Downloads\UniServer\usr\local\php\composer-setup.php on
line 96
4

Warning: openssl_verify(): supplied key param cannot be coerced into a
public ke
y in C:\Users\Ag\Downloads\UniServer\usr\local\php\composer-setup.php on
line 96
4
Signature mismatch, could not verify the phar file integrity
The download failed repeatedly, aborting.

C:\Users\Ag\Downloads\UniServer\usr\local\php>

**Comment by Seldaek** [comment] 2017-01-04 08:48
Not sure what to say, you can just download a composer.phar file by hand on https://getcomposer.org/download/ or try to use the .exe installer. Seems like a PHP setup issue.

**Comment by staabm** [comment] 2017-01-04 08:53
sounds like you are having issues with your openssl version, see e.g.
http://stackoverflow.com/questions/11399613/issues-with-openssl-on-php-different-behaviour-for-different-versions

**Comment by vlakoff** [comment] 2017-01-08 00:22
Googling the error message quickly gave a possible explanation.

The issue may be caused by different versions of `libeay32.dll` and `ssleay32.dll` in your `apache\bin\` and `php\` directories.

**Comment by vlakoff** [comment] 2017-01-08 00:32
And just in case, check in `C:\Users\Username\AppData\Roaming\Composer` if you have `keys.dev.pub` and `keys.tags.pub` files that might somehow be corrupted.

**Comment by pgalang** [comment] 2017-02-20 03:37
Guys please assist me im facing this error when installing composer using the composer-setup.exe


The "https://getcomposer.org/versions" file could not be downloaded: failed to open stream: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by vlakoff** [comment] 2017-04-23 08:04
I suppose pgalang's error above is just a network problem.

@Mugane Have you managed to fix your error? If so, this issue may be closed.

**Comment by Seldaek** [comment] 2017-12-19 10:32
Auto-closing this as it's marked as support request and has not received any update in a long time.

**Closed by Seldaek** 2017-12-19 10:32 UTC
Labels: Support
