### ISSUE TITLE
Composer should not throw if "/etc/xdg" is not in open_basedir

### ISSUE THREAD

**Issue by mvorisek** [composer/composer#9644] opened 2021-01-25 00:05 UTC
Version: 2.0.8

Current output:
```
  [ErrorException]                                                                                                                                       
  is_dir(): open_basedir restriction in effect. File(/etc/xdg) is not within the allowed path(s): ...
```

**Comment by Seldaek** [comment] 2021-01-26 09:07
Duplicate of https://github.com/composer/composer/issues/9541 - should be in a release some time this week.

**Closed by Seldaek** 2021-01-26 09:07 UTC
