### ISSUE TITLE
composer.json is not readable.

### ISSUE THREAD

**Issue by moxuanyuan** [composer/composer#8231] opened 2019-07-17 05:01 UTC
When I run this command:

```
composer require erusev/parsedown
```

I get the following output:

```
./composer.json is not readable.
```

And I expected this to happen:
Windows 10 adds DSM web folder as net drive through SMB. Login accounts have  read and write permissions to web folder, and then use composer require installation package through Windows CMD, and then prompt `./composer.json is not readable.`

Oddly, composer. Json is composer command automatically created, content is `{} `

using Google to check and found that someone had the same problem mentioned, <https://serverfault.com/questions/867669/composer-json-is-not-readable-when-running-on-synology-nas>

 someone replied to a solution, add the everyone read-write Permission to composer. json.

I tried, and it worked.But what I don't understand is that json is already created by the composer command, and it has content in it, so why can't we just add everyone read and write permissions?Also, only composer. json file is required, folder does not

**Comment by alcohol** [comment] 2019-07-17 06:07
I do not do any development on windows machine, so am unable to reproduce this myself. We'll need to find a developer familiar with the source code and access to a windows system to debug this further.

**Comment by alcohol** [comment] 2019-07-17 11:56
Looks related https://bugs.php.net/bug.php?id=68926

**Comment by alcohol** [comment] 2019-07-17 11:59
Looks like `is_readable` and `is_writable` might always return `false` when dealing with network drives/shares. Work around as suggested on the issue would be to check for this condition (networked drive/share) and determine through other means if a file is readable or writable.

**Comment by Seldaek** [comment] 2019-07-29 15:43
@moxuanyuan it'd be good if you can check if the fix work (you can try pre-release builds using `composer self-update --snapshot` and then try the composer require again)

**Comment by 0ddlyoko** [comment] 2019-07-31 21:21
This error has been reported [here](https://bugs.php.net/bug.php?id=75384).

**Comment by alcohol** [comment] 2019-08-05 07:41
@Seldaek not sure if this fixes it because the `is_readable` call would still fail. You only moved/resolved the `is_writable` call.

**Comment by Seldaek** [comment] 2019-08-05 10:50
That php bug you linked says is_readable seems to work fine so I assumed it was ok..

**Comment by alcohol** [comment] 2019-08-05 11:00
No it applies to both. His original issue also shows that it already failed on the `is_readable` step, not the one after that (`is_writable`).

**Comment by Seldaek** [comment] 2019-08-05 11:08
I see, then I guess the is_readable should be fixed too..

**Comment by alcohol** [comment] 2019-08-05 11:18
Yeah it's a bit of a PITA. Especially since it is such an edge case scenario.

**Comment by moxuanyuan** [comment] 2019-08-13 10:03
> @moxuanyuan it'd be good if you can check if the fix work (you can try pre-release builds using `composer self-update --snapshot` and then try the composer require again)
I've tried. The problem remains

**Comment by Seldaek** [comment] 2019-10-25 12:18
@moxuanyuan if you can try again with latest snapshot let me know if it helps.

**Closed** 2019-10-25 12:17 UTC
Labels: Bug, Good First Issue

**Comment by ferdiusa** [comment] 2022-10-25 12:45
This issue returns with 2.4.3 due to https://github.com/composer/composer/commit/80907cd75d039509c5edfbe8ef6a05f4de7a3d98 

Until then, downgrading to composer 2.4.2 is a workaround:
`composer self-update 2.4.2`

**Comment by begueradj** [comment] 2025-05-23 03:36
@ferdiusa I am facing this issue with 2.4.2 version.
