### ISSUE TITLE
error-control-operator in installer potentially hides an issue

### ISSUE THREAD

**Issue by hazini** [composer/composer#4683] opened 2015-12-09 15:08 UTC
curl -s https://getcomposer.org/installer | php -- --check
Shows that everything is ok.

There is suppressed error with @ in file composer/src/Composer/Console/Application.php
line: 67

if (function_exists('date_default_timezone_set') && function_exists('date_default_timezone_get')) {
date_default_timezone_set(@date_default_timezone_get());
}

And error is not displayed if there are corrupted or unreadable timezone files.

So if you run composer.phar and there is no output at all reinstalling tzdata can help.

$ -> yum reinstall tzdata # switch 'yum' for Ubuntu package manager
$ -> rm -f /etc/localtime
$ -> ln -sf /usr/share/zoneinfo/UTC /etc/localtime # 'UTC' can be replaced with what you prefer
$ -> date # check to see that it stuck

**Comment by alcohol** [comment] 2015-12-09 17:06
@seldaek is there any particular reason to use the `@` operator here? I would much rather fail with a message than hide whatever it is currently hiding.

**Comment by alcohol** [comment] 2015-12-09 17:09
@hazini this belongs in [composer/getcomposer.org](/composer/getcomposer.org) to be honest though, since that is where the installer can be found.

**Comment by Seldaek** [comment] 2015-12-09 17:17
We use the `@` because `date_default_timezone_get()` errors out in case you don't have a timezone set at all. I guess maybe we could check with `ini_get('date.timezone')` instead and force to UTC in that case and otherwise just call `date_default_timezone_get()`.

**Comment by alcohol** [comment] 2015-12-09 17:19
@seldaek errors out?

> If none of the above succeed, date_default_timezone_get() will return a default timezone of UTC.

**Comment by alcohol** [comment] 2015-12-09 17:21
I guess you mean the warning that it can produce prior to PHP 5.4.0 when querying the OS?

**Comment by Seldaek** [comment] 2015-12-09 17:24
Yes I mean it produces an error output, and we convert any error to an exception so that is a problem. AFAIK that warning is present even in 5.4+ (I think that note only applies to the OS guessing that was dropped in 5.4) but was removed in 7.

**Comment by alcohol** [comment] 2015-12-09 17:41
I'd still prefer to fail though. Not setting `date.timezone` in your `php.ini` is something that should be shoved in your face :d

**Comment by Seldaek** [comment] 2015-12-09 18:03
And those people will come here complaining that composer is breaking. 
That's why we added this setting the default in the first place. I don't 
enjoy repeating myself in support issues too much :)

**Comment by staabm** [comment] 2015-12-09 18:05
A lot of people getting this warning, therefore I also opt for a try to workaround it

**Comment by hazini** [comment] 2015-12-09 18:06
Yes it's very annoying and confusing behavior of the script. You just can't understand what's happening and why executing it does nothing.

**Comment by alcohol** [comment] 2015-12-09 20:18
I concede. But there must be a better alternative than `@` :<

**Comment by Seldaek** [comment] 2015-12-09 20:28
Well yes as I said above I think ini_set can be used to solve this more 
elegantly.

**Comment by cs278** [comment] 2015-12-09 23:25
This code is also present in Composer: https://github.com/composer/composer/blob/1c525b76f81123af180743d31c208c29351cf931/src/Composer/Console/Application.php#L66-L68

**Comment by curry684** [comment] 2016-01-23 22:26
Duplicate of #4203, should be fixed in #4820 as it now uses at-ease to suppress the common 'Not set' warning, but still shows (fatal) errors.

**Comment by Seldaek** [comment] 2016-01-25 23:32
@curry684 note that this issue is about the installer, that file is hosted in composer/getcomposer.org repo - that one should be fixed in a more concise way ideally though to keep that file from growing too insanely.

**Comment by curry684** [comment] 2016-01-25 23:49
Is it? The installer file in that repo does not reference the timezone functions at all as far as I can see. It references `composer/composer` itself, and uses this code from there.

**Comment by Seldaek** [comment] 2016-01-25 23:53
Oh you're right, never mind me, I misread OP, time for bed ;)

**Comment by cs278** [comment] 2016-01-26 00:25
> Oh you're right, never mind me, I misread OP, time for bed ;)

My bad I completely misread the issue, I thought it was saying the installer threw the error.

**Comment by curry684** [comment] 2016-01-26 20:09
@Seldaek this issue can be closed now right?

**Comment by Seldaek** [comment] 2016-01-26 21:46
Definitely! Thanks

**Closed by Seldaek** 2016-01-26 21:46 UTC
Labels: Bug, Easy Pick
