### ISSUE TITLE
Plugins that has dependencies does not sort properly (uninstall)

### ISSUE THREAD

**Issue by vancoz** [composer/composer#3791] opened 2015-02-26 22:28 UTC
The workaround introduced here (https://github.com/composer/composer/commit/62b506214640ae66ad88a07240a0bbb0201bd1e3) does not cover two use-cases:
*  composer plugin has dependency (other then compose-plugin-api)
*  composer plugin is dependency for module and we are trying to uninstall module (composer plugin subscribed for post-package-uninstall and cleanups module related code, folders, etc...) and uninstall plugin too.

For example:

1. Clone Magento2 (https://github.com/magento/magento2), run _composer install_
2. Add _"texanhogman/m2-minimal": "dev-master"_ to "require" in composer.json 
3. Run _composer update_  (*result:* new module added to _../app/code/_ (/))
4. Remove _"texanhogman/m2-minimal": "dev-master"_  from composer.json 
5. Run _composer update_ 

This happens due to wrong operations sorting, as for me would be good to implement the next behavior:

1. uninstall operations - move all packages uninstalls to the top, then plugin's dependencies and plugins uninsntall operations.

2. install and update operations - move all plugin's dependencies to the top (but after uninstall stuff) then plugins install operations, then install of all other packages.

**Comment by slbmeh** [comment] 2015-02-26 22:40
I'm not sure I understand your issue fully. For updating and uninstalling plugins it is advised in the [plugin documentation](https://getcomposer.org/doc/articles/plugins.md) to run composer with `--no-plugins`.  There is no way to reverse actions done by a plugin activation so it's a bit more complicated than moving it's install order to the end.

**Comment by vancoz** [comment] 2015-02-26 22:48
We are not going to install plugins independently. 

Plugin is the part (dependency) of our package and plugin should deploy package properly on post install or update and it should cleanup package  on post-package-uninstall.

We do not want to have installer plugin as part of our application composer requirements, it should be requirement of package.

So it should be available before install and should be uninstalled after the package.

**Comment by Seldaek** [comment] 2016-04-19 19:35
Closing as duplicate of #4520

**Closed by Seldaek** 2016-04-19 19:35 UTC
Labels: Bug
