### ISSUE TITLE
Versions aren't properly resolved when a replaced package is used

### ISSUE THREAD

**Issue by WouterJ** [composer/composer#4735] opened 2015-12-27 16:04 UTC
There is a strange bug in Composer causing unexpected behaviour when at least 2 packages are required and one replaces the other package (e.g. `symfony/symfony` and `symfony/framework-bundle`).

When using the tidle operator or the OR operator, the package isn't replaced and both packages are resolved as if they were 2 standalone packages (using OR with `x.y.*` results in unexplainable version resolving).

Reproducable Examples
---
```
+============================+====================================+===============================+
| `symfony/framework-bundle` |                                    |                               |
|     version constraint     |             Installed              |            Expected           |
+============================+====================================+===============================+
| `2.6.*`                    |  `symfony/symfony` v2.6.12         | As expected                   |
+----------------------------+------------------------------------+-------------------------------+
| `2.3.*|2.8.*`              | `symfony/framework-bundle` v2.3.36 | No `symfony/framework-bundle` |
|                            | `symfony/symfony` v2.7.8           | `symfony/symfony` v2.8.1      |
+----------------------------+------------------------------------+-------------------------------+
| `~2.3.3`                   | `symfony/framework-bundle` v2.3.36 | No `symfony/framework-bundle` |
|                            | `symfony/symfony` v2.8.1           | `symfony/symfony` v2.3.36     |
+----------------------------+------------------------------------+-------------------------------+
| `~2.3.3|~2.6.6`            | `symfony/framework-bundle` v2.6.12 | No `symfony/framework-bundle` |
|                            | `symfony/symfony` v2.8.1           | `symfony/symfony` v2.6.12     |
+----------------------------+------------------------------------+-------------------------------+
| `^2.6.6`                   |  `symfony/symfony` v2.8.1          | As expected                   |
+----------------------------+------------------------------------+-------------------------------+
| `~2.3.3|^2.6.6`            | `symfony/framework-bundle` v2.6.12 | No `symfony/framework-bundle` |
|                            | `symfony/symfony` v2.6.5           | `symfony/symfony` v2.6.12     |
+============================+====================================+===============================+
```

```bash
$ composer require --no-update symfony/framework-bundle "<CONSTRAINT FROM TABLE>"
$ composer require --no-update symfony/symfony "*"
$ composer update
$ composer show -i | grep symfony
```

**Comment by xabbuh** [comment] 2015-12-27 20:47
I guess this is probably related to #3754.

**Comment by alcohol** [comment] 2015-12-28 08:54
Yes, replace has not been working "properly" for quite some time already. This is known.

**Comment by Seldaek** [comment] 2016-02-21 15:18
Closing as duplicate of #3754

**Closed by Seldaek** 2016-02-21 15:18 UTC
Labels: Support
