### ISSUE TITLE
bitbucket oauth not working

### ISSUE THREAD

**Issue by mmoll** [composer/composer#5166] opened 2016-04-07 16:49 UTC
When I run this command:
```
composer command -vvv:
```

I get this output:
```
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Reading ./composer.json
Loading config file /home/mmoll/.composer/config.json
Loading config file /home/mmoll/.composer/auth.json
Loading config file ./composer.json
Checking CA file /etc/ssl/certs/ca-certificates.crt
Executing command (/tmp/things): git branch --no-color --no-abbrev -v
Failed to initialize global composer: Composer could not find the config file: /home/mmoll/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /tmp/things/vendor/composer/installed.json
Reading ./composer.lock
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Reading ./composer.lock
Resolving dependencies through SAT
Dependency resolution completed in 0.008 seconds
Analyzed 180 packages to resolve dependencies
Analyzed 481 rules to resolve dependencies
  - Installing zzz/yyy (1.3.1)
    Cloning 86ee5af60d7c8718fdfaaa07d53e44c2d4adea6c
Executing command (CWD): git clone --no-checkout 'https://bitbucket.org/xxx/yyy.git' '/tmp/things/vendor/zzz/yyy' && cd '/tmp/things/vendor/zzz/yyy' && git remote add composer 'https://bitbucket.org/xxx/yyy.git' && git fetch composer
Executing command (CWD): git config bitbucket.accesstoken
Enter your Bitbucket credentials to access private repos
Follow the instructions on https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html
to create a consumer. It will be stored in "/home/mmoll/.composer/auth.json" for future use by Composer.
Consumer Key (hidden): 
Consumer Secret (hidden): 
Downloading https://bitbucket.org/site/oauth2/access_token
Failed: [Composer\Downloader\TransportException] The 'https://bitbucket.org/site/oauth2/access_token' URL could not be accessed: HTTP/1.1 400 BAD REQUEST


                                                                                                            
  [Composer\Downloader\TransportException]                                                                  
  The 'https://bitbucket.org/site/oauth2/access_token' URL could not be accessed: HTTP/1.1 400 BAD REQUEST  
                                                                                                            

Exception trace:
 () at phar:///home/mmoll/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:495
 Composer\Util\RemoteFilesystem->callbackGet() at n/a:n/a
 file_get_contents() at phar:///home/mmoll/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:278
 Composer\Util\RemoteFilesystem->get() at phar:///home/mmoll/bin/composer.phar/src/Composer/Util/RemoteFilesystem.php:99
 Composer\Util\RemoteFilesystem->getContents() at phar:///home/mmoll/bin/composer.phar/src/Composer/Util/Bitbucket.php:87
 Composer\Util\Bitbucket->requestAccessToken() at phar:///home/mmoll/bin/composer.phar/src/Composer/Util/Bitbucket.php:146
 Composer\Util\Bitbucket->authorizeOAuthInteractively() at phar:///home/mmoll/bin/composer.phar/src/Composer/Util/Git.php:123
 Composer\Util\Git->runCommand() at phar:///home/mmoll/bin/composer.phar/src/Composer/Downloader/GitDownloader.php:55
 Composer\Downloader\GitDownloader->doDownload() at phar:///home/mmoll/bin/composer.phar/src/Composer/Downloader/VcsDownloader.php:69
 Composer\Downloader\VcsDownloader->download() at phar:///home/mmoll/bin/composer.phar/src/Composer/Downloader/DownloadManager.php:213
 Composer\Downloader\DownloadManager->download() at phar:///home/mmoll/bin/composer.phar/src/Composer/Installer/LibraryInstaller.php:176
 Composer\Installer\LibraryInstaller->installCode() at phar:///home/mmoll/bin/composer.phar/src/Composer/Installer/LibraryInstaller.php:90
 Composer\Installer\LibraryInstaller->install() at phar:///home/mmoll/bin/composer.phar/src/Composer/Installer/InstallationManager.php:152
 Composer\Installer\InstallationManager->install() at phar:///home/mmoll/bin/composer.phar/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///home/mmoll/bin/composer.phar/src/Composer/Installer.php:569
 Composer\Installer->doInstall() at phar:///home/mmoll/bin/composer.phar/src/Composer/Installer.php:228
 Composer\Installer->run() at phar:///home/mmoll/bin/composer.phar/src/Composer/Command/InstallCommand.php:134
 Composer\Command\InstallCommand->execute() at phar:///home/mmoll/bin/composer.phar/vendor/symfony/console/Command/Command.php:259
 Symfony\Component\Console\Command\Command->run() at phar:///home/mmoll/bin/composer.phar/vendor/symfony/console/Application.php:844
 Symfony\Component\Console\Application->doRunCommand() at phar:///home/mmoll/bin/composer.phar/vendor/symfony/console/Application.php:192
 Symfony\Component\Console\Application->doRun() at phar:///home/mmoll/bin/composer.phar/src/Composer/Console/Application.php:181
 Composer\Console\Application->doRun() at phar:///home/mmoll/bin/composer.phar/vendor/symfony/console/Application.php:123
 Symfony\Component\Console\Application->run() at phar:///home/mmoll/bin/composer.phar/src/Composer/Console/Application.php:99
 Composer\Console\Application->run() at phar:///home/mmoll/bin/composer.phar/bin/composer:43
 require() at /home/mmoll/bin/composer.phar:25

install [--prefer-source] [--prefer-dist] [--dry-run] [--dev] [--no-dev] [--no-plugins] [--no-custom-installers] [--no-autoloader] [--no-scripts] [--no-progress] [-v|vv|vvv|--verbose] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--ignore-platform-reqs] [--] [<packages>]...
```

And I expected this to happen:
OAuth is working and saving the credentials to auth.json

**Comment by alcohol** [comment] 2016-04-08 07:32
Unfortunately very few users use Bitbucket, and even fewer contribute to the code that is used to support it. I will see if I can have a look when I have some time myself (I also have a Bitbucket account though I rarely use it) as to what the issue might be.

**Comment by alcohol** [comment] 2016-04-08 11:53
Hrm.. I just created a quick test repo and tried to add it to a dummy project as a dependency;

```
{
    "repositories": [{
        "type": "vcs",
        "url": "https://bitbucket.org/rbast/composer-bitbucket"
    }],
    "require": {
        "alcohol/composer-bitbucket": "dev-master"
    }
}
```

However, when running `composer install` I get the following;

```
Loading composer repositories with package information
    Authentication required (bitbucket.org):
      Username:
```

So clearly my flow is quite different.

Can you give me some more information about what steps to take to reproduce your scenario?

**Comment by frankenpfalzer** [comment] 2016-04-08 12:24
I actually got the same problem as @mmoll described. I hope during the weekend I can collect some Information from my environment.

**Comment by alcohol** [comment] 2016-04-08 12:25
From diving into the code a bit, it looks to me like the oauth flow is not properly implemented at all. We ask the user to provide a their key and secret, but I don't see any following API calls to actually turn this into an oauth token (none that follow the Bitbucket documented flows at least).

/cc @Seldaek @stof please correct me if I am wrong; to me it looks broken/incomplete.

As an intermediate solution I suggest you use a valid ssh key instead and specify your repo url in the format of:

```
git@bitbucket.org:user/repo.git
```

**Comment by thallisphp** [comment] 2016-04-08 21:20
I'm having the same problem as @mmoll. But it's only happens on codeship.com
In my local environment it's runs fine.

**Comment by CZechBoY** [comment] 2016-04-10 14:53
After I upgraded to composer v1.0.0 then this happens to me too. If I rollback to  2016-03-29_07-53-57-e8b1a5f it's ok.

**Comment by Michal-sk** [comment] 2016-04-11 05:40
Same here, happens after upgrading to 1.0.0

**Comment by manioc2015** [comment] 2016-04-11 09:09
This worked for me. Instead of relying on auth.json for the credentials, do this instead:

`"repositories": [
        {
            "type" : "git",
            "url"  : "https://username:password@bitbucket.org/xxx/yyy.git"
        }
    ]`

**Comment by Michal-sk** [comment] 2016-04-11 11:11
well, thats not something i feel comfertable with, because we commit the composer.json files. Maybe we could try with only the username? Thanks at least for the suggestion

**Comment by vaclavvanik** [comment] 2016-04-11 12:13
@manioc2015 using credentials in repo url is just workaround :-/

**Comment by holtkamp** [comment] 2016-04-12 10:24
Same problem here when trying to have Heroku fetch dependencies from BitBucket using the default Composer version ```1.0.0``` which was [installed on 12-04-2016](https://devcenter.heroku.com/changelog-items/866). By providing our own ```composer.phar``` version 1.0-dev (37a1e12672a57813d34251c640be1e3dc0fe4537) 2016-03-27 16:14:51 got deploys working again.

@dzuelke, heads up, multiple Heroku users might experience broken deploys...

**Comment by Michal-sk** [comment] 2016-04-12 15:06
On one machine (pohp70) using the 1.0-dev (37a1e12) 2016-03-27 16:14:51 version indeed dit the trick. Another machine (php5.6) not.

**Comment by AntonStoeckl** [comment] 2016-04-15 12:20
For us the solution is to only use tagged release versions from BitBucket.
Then remove composer.lock (we check this in), remove everything from vendor, do a composer update.
All BitBucket repos now will have dist urls, so not trying to git clone repos.
On Jenkins a cleanup of workspace is necessary, because if some repo is a git clone, composer will git clone it again, instead of downloading the dist.
Hope that helps other people!

**Comment by Gorynych** [comment] 2016-04-15 13:30
If you specify type of repository as
"type" : "git"
in your composer.json file, change it to
"type": "vcs"
and problem will gone.

**Comment by Michal-sk** [comment] 2016-04-18 05:15
@Gorynych great work around, thanks!

**Comment by holtkamp** [comment] 2016-04-18 09:10
It seems the workaround as mentioned by @Gorynych https://github.com/composer/composer/issues/5166#issuecomment-210464706 enables/forces Composer to download a zip archive instead of cloning the repository, which is in line with the suggestion by @AntonStoeckl https://github.com/composer/composer/issues/5166#issuecomment-210444054 to only use the dist urls... This approach re-allows the use of ```1.0.0``` on Heroku deploys.

**Comment by carlcraig** [comment] 2016-05-14 13:15
I had a similar issue, it started working after I added *Callback URL* setting to bitbucket oauth configuration.

**Comment by Michal-sk** [comment] 2016-05-25 10:18
@carlcraig could you be more specific as to where you added the Callback URL / butbucket oauth configuration. I am unable to find the configuration you are referring to.

**Comment by carlcraig** [comment] 2016-05-25 10:55
@Michal-sk have screenshot here showing location

You will need to go to **Bitbucket Settings** then on the sidebar **ACCESS MANAGEMENT > OAuth**

When you add or edit an oauth consumer, you will get the screen below (where you can see callback url highlighted)

![bitbucket-oauth](https://cloud.githubusercontent.com/assets/919781/15537066/5de2ba20-226c-11e6-846a-2ab5b5cd46a0.png)

**Comment by dzuelke** [comment] 2016-05-25 15:00
and you entered... what?

**Comment by stof** [comment] 2016-05-25 15:06
@dzuelke anything, as the callback URL is not used for the grant flow used by Composer. but bitbucket seems to have changed their behavior to make the callback URL required, and so forbidding to authenticate if it is empty

**Comment by peec** [comment] 2016-06-15 07:35
If anyone have problems here is details how i fixed this:


## /home/USER/.composer/auth.json
```
{
    "bitbucket-oauth": {
        "bitbucket.org": {
            "consumer-key": "xxxxx",
            "consumer-secret": "yyyyyy"
        }
    }
}
```


## composer.json
```
{
"repositories": [
      {
        "type": "git",
        "url": "https://bitbucket.org/user/repo.git"
      }
]
}
```

## Bitbucket oauth consumer settings: ( in bitbucket control panel web interface )
- Callback URL needs to be set as explianed in this issue!
- Repo needs to be set to "This is a private consumer". Else you get 400 error..



Now you should be able to 

```
composer update user/repo
```

**Comment by Michal-sk** [comment] 2016-06-17 09:13
Looks like bitbucket again changed there policy. I now **DO** need to add an url / callback, otherwise i get 400 error.

**Comment by stof** [comment] 2016-06-17 09:38
@Michal-sk why again ? All previous comments are saying it is necessary

**Comment by Michal-sk** [comment] 2016-06-17 10:23
Sure, try it than. For me it does not work without a url

**Comment by astroanu** [comment] 2016-06-17 18:40
yes put something there. and it'll work

**Comment by Seldaek** [comment] 2016-06-21 10:16
Closing this as #5363 fixed a ton of bitbucket related problems, please try again after a `composer self-update --snapshot` and see if that fixes it.

**Closed by Seldaek** 2016-06-21 10:16 UTC
Labels: Bug

**Comment by dominik-ba** [comment] 2018-08-10 07:48
Had a similar problem when requiring multiple private repositories from bitbucket.
@Gorynych [#5166 comment](https://github.com/composer/composer/issues/5166#issuecomment-210464706) did the trick for me.

Configurations that worked are:
```json
"repositories": [
    {
        "type": "git-bitbucket",
        "url": "https://bitbucket.org/some/private-repo.git"
    },
    {
        "type": "vcs",
        "url": "https://bitbucket.org/some/other-repo.git"
    }
]
```

**Comment by neoacevedo** [comment] 2018-08-31 22:09
@dominik-ba what I see new in your composer.json is the repository type for private bitbucket: **git-bitbucket**

Unfortunately... https://github.com/composer/composer/issues/5389 says you have to clear cache every hour.

But what is surprised to me is: the access token and the expiration time are refreshed in auth.json on each composer update command calling but seems composer doesn't send this new values but else the old values.
