### ISSUE TITLE
--no-dev should not resolve platform dependency.

### ISSUE THREAD

**Issue by Soullivaneuh** [composer/composer#5227] opened 2016-04-21 13:31 UTC
Since #5016 was closed by https://github.com/composer/composer/commit/4de17cef6b7ea3922594d36fef495221d5df6b6c, I have an issue with the following `composer.json`:

```json
{
    "require": {
        "php": "^5.3 || ^7.0"
    },
    "require-dev": {
        "php": "^5.6 || ^7.0",
        "styleci/sdk": "^1.0",
        "symfony/console": "^3.0",
        "twig/twig": "^1.23"
    },
}
```

You can found the complete file here: https://github.com/Soullivaneuh/styleci-fixers/blob/9f5dbeae0a3492a6fa853d0b4818cb7c5de6e710/composer.json

The error on PHP <=5.5 with `composer update --no-dev`:

```
  Problem 1
    - This package requires php ^5.6 || ^7.0 but your PHP version (5.5.21) does not satisfy that requirement.
```

This package generate a class that must be compatible with php 5.3+ and 7.0.

But the generator needs PHP 5.6.

In order to test the generated class, I separated php constraint between dev and not dev section.

I didn't fully understand the goal of #5016 but IMO it should be reverted or at least has an exception for platform req.

Or maybe an option for that?

Success build: https://travis-ci.org/Soullivaneuh/styleci-fixers/jobs/124452790#L136
Failing build: https://travis-ci.org/Soullivaneuh/styleci-fixers/jobs/124733254#L136

Regards.

**Comment by Soullivaneuh** [comment] 2016-04-21 13:38
Have the same issue with a sub-dependencies if I try removing php constraint from `require-dev`:

https://travis-ci.org/Soullivaneuh/styleci-fixers/jobs/124753241#L238

**Comment by Soullivaneuh** [comment] 2016-04-21 13:45
I fixed my case with `--ignore-platform-reqs` option. But I still thing it's an issue.

Imagine you develop a library that support php 5.3+ and support as an option another library.

You will put this library on `suggest` key and `require-dev` for integration test.

If the partially supported library support only php 5.6+, this will brake your package too.

**Comment by Seldaek** [comment] 2016-04-21 13:50
This only breaks when running *update* on your library, when your library is installed as a dependency it's fine, and if your require-dev requires php5.6+ and you run update there it must be that you're developing the lib and therefore require 5.6, no? I don't really see this as a big problem except for your test suite perhaps.

**Comment by Soullivaneuh** [comment] 2016-04-21 13:53
> This only breaks when running update on your library, when your library is installed as a dependency it's fine, and if your require-dev requires php5.6+ and you run update there it must be that you're developing the lib and therefore require 5.6, no?

I think you're quite right.

> I don't really see this as a big problem except for your test suite perhaps.

Except my special case, I don't know.

IMHO this change not really nothing. If we require a different php version between dev and not dev, this should be respected isn't it?

But if you think not, then you can close this issue. I solve mine actually.

**Comment by Seldaek** [comment] 2016-04-21 19:58
I don't think it makes much sense if you install the package directly to require only the non-dev requirements.. But maybe we'll get more feedback from others as more people try the new behavior. I would rather not add more hacks for this if we can avoid it I have to say so closing for now.

**Closed by Seldaek** 2016-04-21 19:58 UTC

**Comment by patrickkusebauch** [comment] 2016-06-21 10:56
Like to reopen this issue for the following reason:
Our application runs at php 5.4. All of its "require" packages are fine with the version, however we use test frameworks in out "require-dev" section, that require php 5.5.

This is OK on our test server, where php5.5 is running and i can just call `composer install` (from JSON, not lock file, the lock file is not part of our VC, instead we specify the version in JSON file explicitly).

However on our pre-production build server (that is running php 5.4 - same as production), when I try to run `composer install --no-dev`, I will get error that the build needs php5.5 because of item in the "require-dev" section. This makes no sense as I:
1) Don't use the dev section - running `composer install --no-dev` should have the same effect as if the "require-dev" section was empty
2) If I run it with `--ignore-platform-reqs` it will build just fine at will work correctly as it should.

**Comment by stof** [comment] 2016-06-21 11:00
@patrickkusebauch the question is why your test server is running a different version than the prod. This means that all tests could pass but things would break in prod because of using a PHP 5.5 feature. It looks like a broken CI setup to me.

**Comment by Seldaek** [comment] 2016-06-21 11:19
What @stof is saying here is the composer.lock file should be committed otherwise pre-prod might end up installing some different version than what was installed in CI. If you commit it then `install --no-dev` will do what you want. The reason you have the problem is that without lock file it's doing an implicit update and tries to resolves all dependencies first then installs only the require'd ones.

**Comment by patrickkusebauch** [comment] 2016-06-22 05:27
@stof The answer is because I need a testing tool that will not run under the production version  production. Version incompatibilities are in code are easily discovered by static analysis. So it is not broken set-up. It is certainly not ideal, but it is not broken. I make due with the circumstances.

@Seldaek Thank you for explanation. The implicit resolve is the one thing I have not thought about. This explains everything. I will fix the set up to include this feature.

**Comment by XedinUnknown** [comment] 2017-03-19 19:24
No matter what PHP versions the testing/staging/production/CI servers are running, and no matter what solution for their particular cases the participants of this thread have found, I would like to point out that this behaviour is completely unexpected. Development dependencies should not impose any restriction when they are not required. This is most definitely a bug.

**Comment by curry684** [comment] 2017-03-20 01:19
It cannot be a bug as the behaviour is intentional, documented and explained thoroughly. To quote Wikipedia:
> A software bug is an error, flaw, failure or fault in a computer program or system that causes it to produce an incorrect or unexpected result, or to behave in unintended ways.

Which would for example be the case if production and development environments were, despite explicitly attempting to keep parity, included different versions of an identical package. As [environment parity](https://12factor.net/dev-prod-parity) is the intent, this behavior is the logical and to be expected consequence.
