### ISSUE TITLE
Deprecation Notice after update composer

### ISSUE THREAD

**Issue by johnitvn** [composer/composer#4265] opened 2015-07-16 23:56 UTC
I have get error after update composer

````
Deprecation Notice: Composer\Package\Version\VersionParser::parseLinks is deprecated. Use \Composer\Package\Loader\ArrayLoader::parseLinks() instead in phar://C:/xampp/php/composer.phar/src/Composer/Package/Version/VersionParser.php:226
````

**Comment by alcohol** [comment] 2015-07-21 06:22
Duplicate of #4260

**Closed by alcohol** 2015-07-21 06:22 UTC
