### ISSUE TITLE
does not install because of requirements could not be resolved.

### ISSUE THREAD

**Issue by svycka** [composer/composer#5620] opened 2016-08-24 12:10 UTC
please look at this PR https://github.com/svycka/sv-settings/pull/15
I had `"zendframework/zend-servicemanager": "^2.7.6 || ^3.1.1",` in composer.json and it failed.
error log: https://travis-ci.org/svycka/sv-settings/jobs/154721628#L157-L169
then I changed to `"zendframework/zend-servicemanager": "^2.7.5 || ^3.1.1",` and everything installed but one strange thing it installed `"zendframework/zend-servicemanager": 2.7.6` (https://travis-ci.org/svycka/sv-settings/jobs/154725439#L179) so whats wrong with previous one?

**Comment by alcohol** [comment] 2016-08-24 13:16
Please provided a reproducible use-case with as few requirements as possible. We cannot help you purely based on a few Travis builds.

**Comment by svycka** [comment] 2016-08-24 13:23
@alcohol sorry don't have time just thought will ask if this is a bug because it looked strange that ^2.7.6 does not worked and changing version to ^2.7.5 worked but installed 2.7.6

but if you wanna test just clone chat PR https://github.com/svycka/sv-settings/pull/15 and try installing I was able to reproduce this way.

You can close this issue if you like as I don't have time to figure out what's wrong at the moment.

**Comment by alcohol** [comment] 2016-08-24 13:58
It seems to be caused by `zf-commons/zfc-user`. I don't have time to debug this nightmare though and it seems like an edge-case.

```
 % cat composer.json
{
    "require": {
        "php": "^5.5 || ^7.0",
        "zendframework/zend-modulemanager": "^2.6.1",
        "zendframework/zend-servicemanager": "^2.7.6 || ^3.1.1",
        "zendframework/zend-stdlib": "^2.5.2 || ^3.0.1",
        "zendframework/zend-i18n": "^2.6",
        "zendframework/zend-validator": "^2.5.2"
    }
}
 % composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing zendframework/zend-stdlib (3.0.1)
    Loading from cache

  - Installing zendframework/zend-eventmanager (3.0.1)
    Downloading: 100%         

  - Installing zendframework/zend-config (2.6.0)
    Loading from cache

  - Installing zendframework/zend-modulemanager (2.7.2)
    Loading from cache

  - Installing container-interop/container-interop (1.1.0)
    Loading from cache

  - Installing zendframework/zend-servicemanager (3.1.1)
    Downloading: 100%         

  - Installing zendframework/zend-i18n (2.7.3)
    Downloading: 100%         

  - Installing zendframework/zend-validator (2.8.1)
    Loading from cache

zendframework/zend-config suggests installing zendframework/zend-filter (Zend\Filter component)
zendframework/zend-config suggests installing zendframework/zend-json (Zend\Json to use the Json reader or writer classes)
zendframework/zend-modulemanager suggests installing zendframework/zend-console (Zend\Console component)
zendframework/zend-modulemanager suggests installing zendframework/zend-loader (Zend\Loader component)
zendframework/zend-modulemanager suggests installing zendframework/zend-mvc (Zend\Mvc component)
zendframework/zend-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 1.* to handle lazy initialization of services)
zendframework/zend-i18n suggests installing ext-intl (Required for most features of Zend\I18n; included in default builds of PHP)
zendframework/zend-i18n suggests installing zendframework/zend-cache (Zend\Cache component)
zendframework/zend-i18n suggests installing zendframework/zend-filter (You should install this package to use the provided filters)
zendframework/zend-i18n suggests installing zendframework/zend-i18n-resources (Translation resources)
zendframework/zend-i18n suggests installing zendframework/zend-view (You should install this package to use the provided view helpers)
zendframework/zend-validator suggests installing zendframework/zend-db (Zend\Db component)
zendframework/zend-validator suggests installing zendframework/zend-filter (Zend\Filter component, required by the Digits validator)
zendframework/zend-validator suggests installing zendframework/zend-i18n-resources (Translations of validator messages)
zendframework/zend-validator suggests installing zendframework/zend-math (Zend\Math component)
zendframework/zend-validator suggests installing zendframework/zend-session (Zend\Session component)
zendframework/zend-validator suggests installing zendframework/zend-uri (Zend\Uri component, required by the Uri and Sitemap\Loc validators)
Writing lock file
Generating autoload files
```

```
 % cat composer.json
{
    "require": {
        "php": "^5.5 || ^7.0",
        "zendframework/zend-modulemanager": "^2.6.1",
        "zendframework/zend-servicemanager": "^2.7.6 || ^3.1.1",
        "zendframework/zend-stdlib": "^2.5.2 || ^3.0.1",
        "zendframework/zend-i18n": "^2.6",
        "zendframework/zend-validator": "^2.5.2",
        "zf-commons/zfc-user": "~1.3"
    }
}
 % composer install
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - zf-commons/zfc-user 1.3.3 requires zendframework/zend-servicemanager ~2.1 -> satisfiable by zendframework/zend-servicemanager[2.7.6].
    - zf-commons/zfc-user 1.4.0 requires zendframework/zend-servicemanager ~2.1 -> satisfiable by zendframework/zend-servicemanager[2.7.6].
    - zf-commons/zfc-user 1.4.1 requires zendframework/zend-servicemanager ~2.1 -> satisfiable by zendframework/zend-servicemanager[2.7.6].
    - zf-commons/zfc-user 1.4.2 requires zendframework/zend-servicemanager ~2.1 -> satisfiable by zendframework/zend-servicemanager[2.7.6].
    - zf-commons/zfc-user 1.4.3 requires zendframework/zend-servicemanager ~2.1 -> satisfiable by zendframework/zend-servicemanager[2.7.6].
    - zf-commons/zfc-user 1.4.4 requires zendframework/zend-servicemanager ~2.1 -> satisfiable by zendframework/zend-servicemanager[2.7.6].
    - Conclusion: don't install zendframework/zend-servicemanager 2.7.6
    - Installation request for zf-commons/zfc-user ~1.3 -> satisfiable by zf-commons/zfc-user[1.3.3, 1.4.0, 1.4.1, 1.4.2, 1.4.3, 1.4.4].
```

**Comment by alcohol** [comment] 2016-08-24 13:58
@naderman if you can find some time, would appreciate it if you could have a look at this :-)

**Comment by svycka** [comment] 2016-08-24 14:28
@alcohol this also works if we specify any zfc-user version like this:
```
    "require": {
        "zendframework/zend-servicemanager": "^2.7.6 || ^3.1.1",
        "zf-commons/zfc-user": "1.3.3" // or 1.4.0, 1.4.1..., also works with ^1.4.4 maybe because it is latest version?
    },
```
also removing  `|| ^3.1.1` allows installing. not sure how that's related, but maybe will help with debugging.

**Note:** zfc-user at the moment does not support zend-servicemanager 3.0

**Comment by naderman** [comment] 2019-02-03 01:51
Should be fixed with https://github.com/composer/composer/pull/7946 - please verify if you can.

**Comment by svycka** [comment] 2019-02-04 07:05
@naderman tried to reproduce but it works even with the old version I guess because those dependencies have new versions.
Don't know how to test it anymore. I guess can be closed unless you know how to test this.

**Closed** 2019-02-04 10:51 UTC
Labels: Bug, Solver
