### ISSUE TITLE
Using marketing tags for building and create-project

### ISSUE THREAD

**Issue by lisachenko** [composer/composer#3306] opened 2014-09-26 13:55 UTC
Currently, composer strictly restricts names of a tags and branches in the order to be able to normalize them and to compare. I can agree that this is useful for requiring/installing dependencies.

However, I want to discuss a possible way to use non-standard tag names for projects. I have an example, where semantic versioning is used in the project by technical specialists together with marketing versioning that defines custom marketing tag names for releases, like 'aldebaran', 'deneb', etc

What we want is to create project from marketing tag names: `composer create-project some/application:deneb`

To enable this functionality without violation of normalization rules, composer can try to resolve any given name into a git hash for this project and use it internally for installation.

Thoughts?

**Comment by mwgamble** [comment] 2015-11-09 22:48
I'd like to give a +1 to allowing any tag, instead of restricting it to semver tags. In the past I have had tags of the form "1.0.0-wip4-patch6", and the only way to ensure something is locked to that specific commit is to instead do this: "dev-1.0.0-wip4#sha1hashhere". It's quite frustrating that I can't just use git the way it was intended.

**Comment by Seldaek** [comment] 2016-04-15 17:35
Don't think this is realistically going to happen so closing.

**Closed** 2016-04-15 17:35 UTC
Labels: Feature

**Comment by lisachenko** [comment] 2016-04-15 20:15
Sigh...

**Comment by Seldaek** [comment] 2016-04-15 20:19
Yeah sorry but it's been two years, nothing happened, we have no clear plan, and a ton of other more clear and more pressing issues. I am trying to clean up the issue tracker so we can actually see what matters and focus on that. If we ever have zero open issue we can start digging up old ones.
