### ISSUE TITLE
OAuth https ignored but git clone used since 1.3.0

### ISSUE THREAD

**Issue by philicious** [composer/composer#6040] opened 2017-01-04 13:31 UTC
I do `composer config repositories.foobar vcs https://bitbucket.org/foobar/baz.git` + `composer require foobar/services:~0.1`to pull in a private repo and have an `/root/.composer/auth.json` like
```
{
    "bitbucket-oauth": {
        "bitbucket.org": {
            "consumer-key": "12344567",
            "consumer-secret": "blablawhatever"
        }
    }
}
```
up to composer 1.2.4 this is working just fine as I found out. However since 1.3.0 it doesnt use the Bitbucket API + OAuth anymore but tries to git clone the repo and fails because it doesnt have any SSH key to use.

Is this expected? Do I miss something? Was there some important change I need to adapt to ?

**Comment by ttermeer-ouat** [comment] 2017-01-04 13:56
It seems that current release of composer is broken for BitBucket. 
I was able to fix the issue by using the latest snapshot - however I hope the fix is released soon because it breaks automatics deployments of our servers instances.

**Comment by stof** [comment] 2017-01-04 13:58
duplicate of https://github.com/composer/composer/issues/5996

@Seldaek do you have an ETA for 1.3.1 ?

**Comment by Seldaek** [comment] 2017-01-04 14:01
Yeah today when I have a second :)

**Closed** 2017-01-04 14:01 UTC

**Comment by Seldaek** [comment] 2017-01-07 17:35
1.3.1 finally out, sorry busy week..

**Comment by philicious** [comment] 2017-01-07 21:30
@Seldaek awesome. thanks !
