### ISSUE TITLE
VersionGuesser not playing well with monorepositories

### ISSUE THREAD

**Issue by Toflar** [composer/composer#8477] opened 2019-12-10 17:06 UTC
I was really ripping my hair out on this one so I had to debug the reason why it's not working and found out some interesting stuff :-)

So what I'm trying to do is using a `path` repository so it's symlinked into my project which allows me to easily develop my stuff within a running application:

```
    "repositories": [
        {
            "type": "path",
            "url": "/......./project"
        }
    ]
```

Now what I noticed is that even though I made sure I checked out the my `feature1` branch on my `project`, composer did not update to my `dev-feature1` branch but instead downloaded `dev-master` from packagist.

I went down the rabbit hole and found the reason to reside in this check: https://github.com/composer/composer/blob/master/src/Composer/Package/Version/VersionGuesser.php#L210

So my `composer.json` contains a few `self.version` and that's why my `dev-feature1` branch is skipped because it's treated as "cannot work".
However, I'm using a monorepository and my `self.version` hints actually come from this:

```
    "replace": {
        "bundle1": "self.version",
        "bundle2": "self.version",
        "bundle3": "self.version"
    },
```

All of those bundles, however, are part of my repository. That means I cannot checkout a feature branch and pull that into my project when I'm using a typical monorepository setup.

So I wonder:

1. Are the replacements even relevant there? 
2. If they are, would you accept something like `monorepository-dependencies` or something (similar to `non-feature-branches`) so that `self.version` is only a problem if it's not one of those?
3. Or any other idea?

**Comment by aschempp** [comment] 2019-12-11 08:03
maybe the `self.version` check should only be on the requirements and not on everything like the provides?

**Comment by Seldaek** [comment] 2019-12-22 10:38
@aschempp I don't understand what you are suggesting. If we see self.version we have to replace it by something to make it usable, so if not the actual version what would you suggest?

@Toflar I'm not sure about your suggestion, seems overly complex and something nobody will ever use aside from you :) Defining `"version":"dev-master"` in the `project` composer.json should help to avoid version guessing going for dev-feature1.. But that may not be practical if you have to change this all the time.  Have you tried https://github.com/franzliedke/studio ? Maybe it'd be working out better than path repo for your use case?

**Comment by Toflar** [comment] 2019-12-23 09:23
> But that may not be practical if you have to change this all the time. Have you tried https://github.com/franzliedke/studio ? Maybe it'd be working out better than path repo for your use case?

I haven't, thanks for the hint. But I don't really feel like I should need any extra plugin.
Why exactly are feature branches skipped if there's `self.version` in the `composer.json`? I mean, it just falls back to `dev-master` in that case which is still a branch that also contains `self.version` in its `composer.json` so I don't get the difference 😄

**Comment by aschempp** [comment] 2020-01-04 16:16
> I don't understand what you are suggesting. If we see self.version we have to replace it by something to make it usable, so if not the actual version what would you suggest?

Its just a quick guess, but I found it confusing that Composer is doing a string match, and not an exact lookup. The `self.version` could be anywhere in `extra` or `require-dev`, and not actually affect the current resolving process…

**Comment by vtsykun** [comment] 2020-01-04 16:43
I had a similar problem, I tried to add a new option for the `path` repository to disable the `VersionGuesser` and specify the package versions manually, here https://github.com/composer/composer/pull/6578 created PR for this

**Comment by Seldaek** [comment] 2020-01-13 16:18
Just so I can try and repro this.. What are you requiring? dev-feature1 of your package in the path repo? Can I get a repro case with public repos if possible?

**Comment by Toflar** [comment] 2020-01-14 11:44
1. `mkdir test`
2. `cd test`
3. `mkdir mono-repo`
4. `cd mono-repo`
5. `git clone git@github.com:contao/contao.git .`
6. `git checkout -b my-feature`
7. `cd ..`
8. Create a `composer.json` with the following contents:

```json
{
    "require": {
        "contao/contao": "dev-my-feature"
    },
    "repositories": [
        {
            "type": "path",
            "url": "./mono-repo"
        }
    ]
}
```

9. `composer update`.

You'll notice that Composer will tell you it could not find `dev-my-feature` although we created that branch in our mono repository before.
This is because of [`VersionGuesser::guessFeatureVersion()`](https://github.com/composer/composer/blob/9041622b862baef250beffccf52f0c13f2845376/src/Composer/Package/Version/VersionGuesser.php#L210-L214). In fact for our monorepo, both conditions (the branch-alias and the self.version test) would evaluate to `true`. So I'd need some way to tell composer that I really want that `dev-my-feature` branch because I know it's all good for that monorepo 😄

**Comment by Seldaek** [comment] 2020-01-14 11:49
Yup ok so now I am fairly sure this is related/duplicate of #8498 - for which a fix is incoming soon. Will ping you when it's pushed so you can try and confirm.

**Closed** 2020-01-14 11:52 UTC
Labels: Support

**Comment by Seldaek** [comment] 2020-01-14 11:54
Ok please try with latest snapshot, should be creating two versions now for dev-my-feature and dev-master or whichever the my-feature branch came from. No need for extra config field.

**Comment by bytehead** [comment] 2020-01-14 11:55
Thank you for fixing! ❤️

**Comment by Toflar** [comment] 2020-01-14 11:58
Yeah, that indeed solves the issue! Thank you!! ❤️
