### ISSUE TITLE
2.0: Let us use multiple slashes in the package name.

### ISSUE THREAD

**Issue by 626Pilot** [composer/composer#7975] opened 2019-02-12 06:43 UTC
https://github.com/composer/composer/blob/287419f6a0ddda7824888af7bc33d65932b39743/src/Composer/Package/Loader/ValidatingArrayLoader.php#L345

Drop the requirement that package names follow the form vendor/package-name. Let us use as many slashes as we want. It's like this now in version 1, and it's better that way.

Consider these examples:

Namespace: VName\Library\MatrixMath
- Repo: gitlab.something.com/vname/library/matrix_math
- Install: composer install vname/library/matrix_math

Namespace: VName\Service\Subscription
- Repo: gitlab.something.com/vname/service/subscription
- Install: composer install vname/service/subscription

Namespace: VName\Service\Payment\PayPal
- Repo: gitlab.something.com/vname/service/payment/paypal
- Install: composer install vname/service/payment/paypal

This is very clean. Libraries (mechanisms with no awareness of business logic) are separated from Services (business logic serving endpoints), and related Service types are in their own namespaces. The namespace looks like the package name, which looks like the repo URL. The only difference is that StudlyCaps turns into snake_case. See how nice that is?

We can already do this in Composer 1, and it's extremely good! Don't impose this limitation on Composer 2.

N.b.: I understand that Packagist will not support this, which is fine with me. I also understand that some third-party tools may not support this, which is also fine with me. I don't see the point in hobbling Composer's behavior over external software. I am not uploading to Packagist, and my toolchain works just fine with multiple slashes.

**Comment by Seldaek** [comment] 2019-02-12 07:56
There is no requirement that the package name matches the gitlab path really.. What's wrong with vname-library/matrix-math or vname/lib-matrix-math or similar?

It'd mean you have standard package names that will work everywhere no matter if you decide to change your toolchain in the future.

**Comment by 626Pilot** [comment] 2019-02-13 05:10
The thing is, this change breaks something that already works fine the way it is, and it makes lots of busy work for every developer who is using more than one slash, in return for nothing.

It doesn't work with Packagist, but that's fine. Composer is not Packagist, and Packagist is not the only valid use case for Composer. If Packagist has some limiting assumption that means you can only have one slash, I am fine to change the package name _if and only if I am going to upload to Packagist,_ which I am not.

If it doesn't work with some other 3rd-party tool, the reasoning is the same.

Consider the scenario of going forward with this change:
- I have to fix this in DOZENS of repos, do the branch management and code review, etc.
- This makes my repos compatible with tools that are not a part of my use case and will never be.
- Multiply this by however many developers have been happily using multiple slashes for the last seven years. How many hours is it? Thousands? Tens of thousands? Why do we need to stop delivering code, and in many cases spend billable hours, doing this?
- The payoff is supposedly compatibility with other software, but we would already have gone to a single slash if that software was relevant to our use cases. The fact that we have not should tell you everything you need to know about whether we need to be forced into this "for our own good," at our expense, and in return for nothing we value.

Now, consider the scenario of leaving this alone, and someone runs into a problem trying to upload to Packagist:
- That developer has to fix all their repos, but all the developers who are not uploading to Packagist do not. *Huge amount of time saved for hundreds/thousands of developers.*

Which of these two scenarios causes more harm, and wastes hundreds of thousands of dollars of dev hours? Which of these two scenarios impacts only those who are using Packagist or whichever 3rd-party tool?

If we are frightened that someone will develop some stuff and it won't work with Packagist, fine. _Print a warning. Do not throw an error, and do **not** stop execution._ Also, let me put something in composer.json that suppresses that warning, because it is not relevant to my work.

**Comment by Seldaek** [comment] 2019-02-13 10:31
You talk like this problem applies to thousands of developers, yet so far nothing seems to indicate that. We will keep the warning for a while longer to see how things evolve. 

My assumption is most people follow the foo/bar naming convention because that's what they've seen used in the wild as it's enforced on packagist.org.

**Comment by 626Pilot** [comment] 2019-02-16 06:58
With respect, neither of us knows whether it's thousands. It seems likely to me that it is; we use multiple slashes at my company, and we're not from Mars or anything. Most professional developers are not at liberty to upload their work to Packagist, so unless we have the energy to contribute to open source after 40-60 hours in the office, we wouldn't find out that way.

You have two choices. One of these choices will _definitely_ cause problems for a number of people that neither of us can predict ahead of time. Maybe it's 50. Maybe it's 5,000. (PHP runs most dynamic websites, and Packagist is supplying half a billion installs per month, so even 5,000 is a vanishingly tiny fraction.)

The other choice merely warns people who use multiple slashes, and doesn't break anything. No one has to take time away from other projects to fix anything, and no one is going to file a support request on this tracker because their build process broke.

**Comment by alcohol** [comment] 2019-02-22 19:54
People getting creative is a constant source of issues and discussion. The documentation has always been rather clear on this issue however: https://getcomposer.org/doc/01-basic-usage.md#package-names

**Comment by 626Pilot** [comment] 2019-02-24 20:53
I know it's in the doc, but I don't see why that alone necessitates destroying this highly useful functionality. Allowing nested package names (and the nested directories they are transformed into) is very useful. Remember when Class_Names_Looked_Like_This? Well, that wasn't any fun, and neither is looking at dozens of 30-character-long directory names in an IDE.

If you do back-end development, and you're interested in microservices, try doing it this way for a couple of weeks. You'll see how much cleaner and more organized it is.

If you print a warning instead of stopping execution, you address every issue that has been raised by everyone in this thread. Everyone gets what they want, and everyone can weigh the issues and decide for themselves. There's no risk.

**Comment by alcohol** [comment] 2019-02-25 07:26
There barely is a relationship between package name and directory structures. But if anything, that would be another reason to enforce not allowing `/` inside the package name. We typically store packages under `vendor/<vendorname>/<packagename>`. By allowing users to put `/` in the package name, the outcome becomes less predictable.

**Comment by JanSlabon** [comment] 2019-02-28 17:27
We also use several slashes in packages to create dependecies to packages, which have an ioncube license file in the upper path. For example:

    setasign/eval/setapdf-extractor/ioncube/php7.1

requires:

    setasign/eval/setapdf-extractor/ioncube

The later one will have a license file placed in the folder. The main package in `setasign/eval/setapdf-extractor/ioncube/php7.1` will load this file (through the internal process of ioncube). We ship them through our own repository.

In the past this worked very well but since some months an update of `setasign/eval/setapdf-extractor/ioncube` will remove the folder below without noticing it. So you were forced to call `composer update` again so that the missing folder will get repaired.

That writing I would say that the several slashes-thing is currently broken anyway and you should/can not rely on it at all. It had worked but currently it doesn't. We plan to solve this by using a "script" hock, that will copy the license file to the correct folder but I guess that's another issue.

Well, just some thoughts from a several-slashes user... :-)

**Comment by stof** [comment] 2019-02-28 18:25
Another issue with allowing a variable number of slashes: installing `foo/bar` and `foo/bar/baz` will **not** work consistently (already in 1.x), as composer empties the folder before putting the new code in it.
So if `foo/bar` gets downloaded after `foo/bar/baz` (which might happen whatever priority rules we create, as an update might be downloading *only `foo/bar`), the other one gets removed.

Having to make any package conflicting with packages patching one of their "parent" name would become a mess.

**Comment by VincentSurelle** [comment] 2019-03-06 09:47
Hi,

We are also using multiple slashes on Gitlab.
We have like 200+ projects using it.
Making such a breaking changes would make us lose so much time.

As the only package manager for php, you have great responsibilities. And, in my opinion you just can't do that.

Thanks.

**Comment by stof** [comment] 2019-03-06 10:21
@VincentSurelle to have things working without WTF bugs at the composer level, that would still require having composer forbidding to install a package with a name being a subfolder of another installed package (and I'm not even considering the work needed to support such names on Packagist). I'm not sure this is worth the effort.

**Comment by 626Pilot** [comment] 2019-03-25 01:24
> We are also using multiple slashes on Gitlab.
> We have like 200+ projects using it.
> Making such a breaking changes would make us lose so much time.
> As the only package manager for php, you have great responsibilities. And, in my opinion you just can't do that.

@VincentSurelle, how many hours do you think it would take to fix this on your side? For me, it will easily take weeks (depending on the fix and what I have to do to my internal tooling), and I have less than 50 repos.

> Another issue with allowing a variable number of slashes: installing `foo/bar` and `foo/bar/baz` will **not** work consistently (already in 1.x), as composer empties the folder before putting the new code in it.

@stof, I have dozens of repos in the form vendorname/component-type/component. Each component-type directory has many subdirectories. Nothing has been overwritten so far. I am not using parent-child topology, however. Once you find a composer.json under any of my repos, you will not find another in any of the subdirectories.

> I'm not sure this is worth the effort.

It is to anyone who's interested in writing true microservices. Organizing your vendor directories so that you can have vendorname/component-type/[component-subtype/...]component-name makes sense for the same reason that _namespaces_ make sense. It provides an incredibly obvious, straightforward way to organize the modules.

**Comment by bmerigan** [comment] 2019-05-20 06:51
I support making this a warning which can be turned off.  
I personally have over 50 packages which will need to be updated should this be made mandatory in version 2.

> 
> 
> People getting creative is a constant source of issues and discussion. The documentation has always been rather clear on this issue however: https://getcomposer.org/doc/01-basic-usage.md#package-names

This documentation DOES NOT forbid the use of additional slashes.
Our packages conform to the vendor/packagename syntax as per the documentation AND our packagename contains slashes.

**Comment by alcohol** [comment] 2019-05-20 06:55
Well we might have failed to document that packagename should not contain slashes because it seemed obvious (the example implies a slash is used to separate vendor from packagename). But it shouldn't. So there you have it.

**Comment by bmerigan** [comment] 2019-05-20 07:03
Our package name syntax currently is along the lines of:
<vendor>/<applicationname>/service/<servicename>
<vendor>/<applicationname>/module/<modulename>

I can definitely change this to <vendor>/<applicationname>-service-<servicename>
but the amount of effort to do this across our entire repo is... huge.

**Comment by VincentSurelle** [comment] 2019-05-24 13:47
Will composer V1 continue to work ? Will it be degraded ?

**Comment by alcohol** [comment] 2019-05-27 06:44
I suspect v1 will continue to work, but considered deprecated, no longer supported nor maintained, and eventually will not work anymore once v3 is released most likely.

**Comment by VincentSurelle** [comment] 2019-06-03 09:38
Thanks, so it means that we could continue to work with it for a moment but not in good conditions.

Do you have any idea when 2.0 will be released ?

But to fix the problem we need : 

*To change all the way we work with Gitlab and sacrifice all the readability sub-groups provide (Huge)* OR *push our dependencies to paid private packagist https://packagist.com/*

That's all we can do isn't it ?

**Comment by stof** [comment] 2019-06-03 10:51
@VincentSurelle you can keep your gitlab subgroups. This is talking about the composer package name, not about the repository name.

**Comment by 626Pilot** [comment] 2019-06-10 02:15
> Well we might have failed to document that packagename should not contain slashes because it seemed obvious (the example implies a slash is used to separate vendor from packagename). But it shouldn't. So there you have it.

I think perhaps we are not explaining ourselves well enough.

You seem to be assuming that there is no particular use for having more than one level of subdirectories beneath the vendor name. Perhaps your use case is writing low-level libraries in vendor/something/something, and putting all your business logic in some directory like app/ or application/ (supplied by some web framework.) I think this is a very familiar use case for a lot of devs.

However, this assumption has a fatal flaw. It implies, intentionally or otherwise, that there is only one type of module that needs to be installable via Composer. If there is only one type of module (low-level library code), then that type is implied by the fact that only one level of subdirectory is allowed.

When you are working with a large amount of code - dozens to hundreds of repos, and hundreds of thousands to millions of lines - that assumption breaks down. It simply stops working.

When you are developing microservices, the practice of putting code into app/ (or any directory supplied by the framework) is the death of maintainability. It encourages inappropriately tight coupling. Dozens of controllers depend on dozens of models in a dense rat's nest that is very hard to untangle. If you want to deploy some service independently, you may have to spend weeks refactoring code because there is far too much parasitic coupling. Copy-pasted code starts to pile up. It's no good.

So, if you're not going to put your business logic in app/ or whatever, then you need to put it somewhere else. It needs to be in its own repo. Composer is the logical choice. However, you don't want to mix your business logic with your library code. Those repos are not the same kind of thing. It's bad organization to force them to coexist in the same directory, for the same reason that you would not put models and controllers in the same directory. For the same reason that using namespaces is better than not using namespaces.

Frameworks like Laravel and Zend practically beg us to write monoliths by assuming we want to bake our code into the framework, rather than using vendor. We have to work hard not to succumb to that, but it is the only sane option when working with huge amounts of code.

**This is why many of us have been running away from monolithic development for the last twenty years. This is why SOA was invented; and why, in the late 2000s, when devs got sick of classic SOA, they invented microservices instead of going back to monolithic development.**

Don't confuse the fact that you've never found a reason to have multiple nested subdirectories for evidence that they don't need to be supported.

On average, tens of millions of packages are installed with Composer every day. Out of all the devs who do this, only a vanishingly tiny fraction will ever come to this issue tracker, let alone see this particular issue. Even so, more than one of us has come here to say, "Please don't do this thing. We have good reasons for having multiple levels of nested subdirectories. If you take this feature away, we will have to do a large amount of work to compensate, and it will harm the quality of our code organization."

As maintainers, you have a responsibility to **millions** of devs, and you **really** need to think carefully before breaking backward compatibility.

**Comment by dbrumann** [comment] 2019-06-10 14:25
From what it looks like to me, you are working with a lot of false assumptions and conflate package names with the directory structure in your project/library quite often.

> However, this assumption has a fatal flaw. It implies, intentionally or otherwise, that there is only one type of module that needs to be installable via Composer.

There are many libraries providing multiple options to choose from using only vendor/package-name. For example:
* php-http/httplug (The library itself)
* php-http/httplug-bundle (Symfony integration, which has a dependency on php-http/httplug)
* php-http/curl-client (One of the possible HttpClients, that can be used with php-http/httplug)
* php-http/cache-plugin (Plugin that can be used by any http-client as part of httplug)

You could also look at the Doctrine project which also splits up both their common library as well as their dbal and orm into multiple packages using only a single slash in the package names.

> However, you don't want to mix your business logic with your library code. Those repos are not the same kind of thing. It's bad organization to force them to coexist in the same directory, for the same reason that you would not put models and controllers in the same directory.

I am not sure how this relates to the naming of packages. You can organize your application code and library code any way you want, no matter how you name your packages. I fail to see how these two issues (naming of packages vs. directory structure in your project/library) relate to each other.

> Frameworks like Laravel and Zend practically beg us to write monoliths by assuming we want to bake our code into the framework, rather than using vendor.

This point is debatable. Symfony - and from my understanding most modern frameworks - promote a clear separation of business logic and framework with only a thin layer of integration into the framework. Besides that, it has nothing to do with the naming of composer-packages. If you want just a single component from Symfony, you can install it as a separate package in composer, using e.g. symfony/<component-name> (as opposed to symfony/<bundle-name> which provides the integration into a Symfony Full Stack-application, which again is created from a different package called symfony/symfony-skeleton). Each component describes it's dependencies allowing you to use it standalone in any application without any impact on how you structure your application. Composer's autoloading will make sure that the corresponding library code is loaded when you want to use it in your application/library.

If some of the most popular frameworks, being used for a wide range of different projects from monolith to microservices, are able to organize themselves using only vendor/package-name, it stands to reason that most other projects can do so as well. If you disagree, you might want to give a concrete example when and how this limitation is an impediment.

Suggesting many - even thousands of developers - encounter an issue, but not say a single word about it (here or on any other channel) seems very unlikely given that things like outages or critical bugs are usually quickly pointed out (and fixed).

The naming of packages has no impact on whether you have a simple CLI-tool, monolithic web application, a set of microservices or any other kind of architectural pattern. How you structure them in different libraries, (VCS-)repositories or directories is also not affected by the package name. If you encounter a case, where this is not true, maybe a concrete description of how to reproduce that issue will help us understand your point.

**Comment by dbrumann** [comment] 2019-06-10 15:41
> Our package name syntax currently is along the lines of:
> _vendor_/_applicationname_/service/_servicename_
> _vendor_/_applicationname_/module/_modulename_
> 
> I can definitely change this to _vendor_/_applicationname_-service-_servicename_
> but the amount of effort to do this across our entire repo is... huge.

There may be ways to ease the migration process. For example, you could create a new version of your library with the updated name, keeping the old name in the replace-section of the `composer.json`. Existing projects should still be able to install the old version of the library using the legacy name, but you can update them to the new name easily and also create projects already requiring the new name.

I quickly tested this locally (using a path-repository):

```json
{
    "name": "acme/lib-a",
    "description": "Example library formerly using a legacy name",
    "version": "2.0.0",
    "replace": {
        "acme/library/lib-a": "1.0.1"
    }
}
```

* Re-installing the lib with the old name after renaming the package (deleted vendor folder in my project and then ran composer install, so it would install the library again):
```
dbr:project/ $ rm -rf vendor

dbr:project/ $ composer cache-clear
...

dbr:project/ $ composer install
Deprecation warning: ...
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing acme/library/lib-a (1.0.1): Mirroring from ../lib-a
```
* Updating the project to the new name & deleting the old package name:
```
dbr:project/ $ composer require acme/lib-a
Deprecation warning: ...
Using version ^2.0 for acme/lib-a
./composer.json has been updated
Deprecation warning: ...
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 1 update, 0 removals
  - Updating acme/lib-a (1.0.1 => 2.0.0): Mirroring from ../lib-a

dbr:project/ $ composer remove acme/library/lib-a
Deprecation warning: ...
Loading composer repositories with package information
Updating dependencies (including require-dev)
Nothing to install or update
Writing lock file
Generating autoload files

dbr:project/ $ rm -rf vendor
dbr:project/ $ composer install
Loading composer repositories with package information
Installing dependencies (including require-dev) from lock file
Package operations: 1 install, 0 updates, 0 removals
  - Installing acme/lib-a (2.0.0): Mirroring from ../lib-a
Generating autoload files
```

Obviously, with a larger project this might be more work and I haven't tried this with transitive dependencies, but it seems like a good start. If you (or anyone else running into this) need any help/further advice feel free to post questions on StackOverflow. I answer questions there quite regularly and will gladly help.

**Comment by 626Pilot** [comment] 2019-06-13 04:28
> From what it looks like to me, you are working with a lot of false assumptions and conflate package names with the directory structure in your project/library quite often.
I am working with Composer in a way that is perfectly logical.

vendorname/packagename: Both of those tokens are directories
vendorname/packagetype/packagename: All three of those tokens are directories

You try it now, and it works, and why wouldn't it? It makes perfect sense.

> > However, this assumption has a fatal flaw. It implies, intentionally or otherwise, that there is only one type of module that needs to be installable via Composer.
> 
> There are many libraries providing multiple options to choose from using only vendor/package-name. For example:
> 
> * php-http/httplug (The library itself)
> * php-http/httplug-bundle (Symfony integration, which has a dependency on php-http/httplug)
> * php-http/curl-client (One of the possible HttpClients, that can be used with php-http/httplug)
> * php-http/cache-plugin (Plugin that can be used by any http-client as part of httplug)
> 
> You could also look at the Doctrine project which also splits up both their common library as well as their dbal and orm into multiple packages using only a single slash in the package names.

Imagine this instead:
- php-http/library/httplug
- php-http/integration/symfony
- php-http/integration/laravel
- php-http/integration/zend
- php-http/client/curl
- php-http/client/streaming-sockets
- php-http/plugin/cache
- php-http/plugin/circuit-breaker
- php-http/plugin/failover

I challenge any of you to explain how shoehorning all of that stuff under one directory is a better solution than allowing it to be divided into logical groups, just like you would files in an application or classes in namespaces.

"Well, you don't NEED to..."

You don't need to have namespaces, you can call your class App_Http_Controller_Login instead.
You don't need more than two levels of subdirectories in the framework, you can just have app/Model-Eloquent-Authentication.php.
You don't need to write code in PHP, it's perfectly possible to use assembly language.
You don't need a hard drive, Hollerith cards and mag tape are perfectly fine.
You don't need to write a program, you can correspond with your customers by telephone.

> > Frameworks like Laravel and Zend practically beg us to write monoliths by assuming we want to bake our code into the framework, rather than using vendor.
> 
> This point is debatable.
Laravel wants you to put all your business logic in app/, and Zend wants you to put all your business logic in application/. Separability and independent deployability are terrible with this because you cannot add and remove components with a dependency manager if they are baked into those directories. Over time, you get a gigantic rat's nest with dozens of controllers accessing dozens of models. If you want to put ten endpoints in ten copies of the framework, there will be enormous copying and pasting, ten copies of the same code. It's a terrible way to write back-end services. This is why large codebase developers such as myself and the others in this thread are not doing it that way. Over time, it leads to huge maintenance problems.

> Suggesting many - even thousands of developers - encounter an issue, but not say a single word about it (here or on any other channel) seems very unlikely given that things like outages or critical bugs are usually quickly pointed out (and fixed).
Oh, but other developers have already found their way here. Some of them are replying directly, others are giving me thumbs up on my posts. It seems that I am not alone.

Here is what Mr. Surelle said above:
> Hi,
> 
> We are also using multiple slashes on Gitlab.
> We have like 200+ projects using it.
> Making such a breaking changes would make us lose so much time.
> 
> As the only package manager for php, you have great responsibilities. And, in my opinion you just can't do that.
> 
> Thanks.

What more do you need to know?

**Closed** 2019-06-13 07:59 UTC
Labels: Question

**Comment by Seldaek** [comment] 2019-06-13 08:06
Sorry for the reopen noise.

Anyway.. @626Pilot the problem with sub-directories is you can have clashes, i.e. php-http/client/curl and php-http/client, how do you install both?

That's the main technical reason behind enforcing a single slash, but there are other things that get easier to handle for all integrators when things are consistent.

The main problem I see is that a few users (not thousands, not hundreds of thousands) decided that they wanted to do this, and we never checked against it (except on packagist.org). Most everyone just followed the convention set by packagist.. I suspect mostly the reason people get confused is that they map their repo name (on GitLab IIRC you can have multiple slashes in the repo url..) to the package name, but there is no need to do that. The package name is completely independent from the repository name. And the package name is unrelated to the location of the source files as well. 

The way your vendor directory is organized shouldn't matter IMO.. It's ok if it's a flat structure where everything has two foo/bar components. 

For example if you look at Symfony, https://github.com/symfony/symfony/tree/4.4/src/Symfony/Component/Cache is released as symfony/cache. The short package name doesn't prevent the use of namespaces, subdirectories etc.

I feel like this is a misunderstanding issue first and foremost. Now that it annoys you because we nudge you to cleanup I understand, but given the amount of time wasted here discussing I'm starting to wonder if maybe you wouldn't be done renaming your packages instead.. Sounds like something that can be reasonably automated.

**Comment by dbrumann** [comment] 2019-06-13 08:39
That's my chance to get in my final comments as well 😉 

@626Pilot if you want to map your different repositories to the directory structure you like inside the (meta) project using them. You could use a mono repo for the whole project and then split it up using something like subtree split similar to how Symfony does it. My offer still stands to help with finding a solution inside your project bounds around your constraints. Feel free to contact me on a different channel.

**Comment by segrax** [comment] 2019-06-19 04:20
> Suggesting many - even thousands of developers - encounter an issue, but not say a single word about it (here or on any other channel) seems very unlikely given that things like outages or critical bugs are usually quickly pointed out (and fixed).

Perhaps its because this change isn't live yet and affecting people, this 'issue' was just brought to my attention by a few developers in a meeting regarding the "upper case characters" deprecation warning they're now getting.
I'm not sure how most devs/orgs handle composer, but its my understanding devs don't update Composer very often (it seems common to find 2 year old versions of it in use around here)

it would seem the 2.0 release is going to require even more work than just fixing a few upper case characters (i can already see 39 of our internal packages which are going to need a rename)
