### ISSUE TITLE
Inexplainable dependency conflict

### ISSUE THREAD

**Issue by Berdir** [composer/composer#6131] opened 2017-02-04 14:33 UTC
Steps to reproduce:

https://github.com/Berdir/strict-dependency-bug

Output:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - berdir/strict-dependency-bug 1.0.0 requires webflo/drupal-core-strict 8.2.6 -> satisfiable by webflo/drupal-core-strict[8.2.6].
    - berdir/strict-dependency-bug 1.0.1 requires webflo/drupal-core-strict 8.2.6 -> satisfiable by webflo/drupal-core-strict[8.2.6].
    - Conclusion: don't install webflo/drupal-core-strict 8.2.6
    - Installation request for berdir/strict-dependency-bug ^1.0 -> satisfiable by berdir/strict-dependency-bug[1.0.0, 1.0.1].


Installation failed, reverting ./composer.json to its original content.
```

The problem is related to having more than one valid version in strict-dependency-bug, if you do "composer require berdir/strict-dependency-bug:1.0.1" instead, it installs fine.

The error doesn't really make sense, how can there be a conflict because of two identical versions?

drupal-core-strict is a package that aims to enforce the same dependencies as defined in Drupal's composer.lock. We've noticed that sometimes there are unexpected changes in untested dependencies versions, this is an idea to prevent that.

(That might or might not really be a good idea. I mostly sharing this in case there's a deeper depencency resolving problem here)

Any idea what's going on?

**Comment by Seldaek** [comment] 2017-02-05 11:27
Might be interesting for @naderman  to look at as it seems to happen with a minimal subset of packages, but can you please share the smallest possible composer.json you use to reproduce this?

**Comment by Berdir** [comment] 2017-02-05 13:15
Thanks for checking.

I can't try, but I suspect it only happens in combination with starting off with a drupal-project. I just tried the last two commands (adding the repo and requiring it) after initializing a new and empty composer.json and then it works fine.

I guess it is the combination of depending on drupal/core which has the same dependencies as drupal-core-strict, just not as strict. But testing that alone also doesn't really give the same. Whe I just run composer require drupal/core and then try to add mine then I do get conflicts, but they go away after a rm -rf composer.lock vendor/.

So as far as I see, it only happens when you actually start of with drupal-project.

**Comment by webflo** [comment] 2017-02-05 13:23
Thanks for helping. I did some testing a while ago over in https://gist.github.com/webflo/5d8a2310734a9089eb67ab5ec85ce1cd

It looks like that is works if i add it to the composer.json and run composer update on all packages. ``composer update --with-dependencies`` or ``composer require  --update-with-dependencies`` does not work.

**Comment by osopolar** [comment] 2018-03-15 21:58
I had [a similar problem](https://github.com/webflo/drupal-core-strict/issues/5), maybe it is related to this.

**Comment by naderman** [comment] 2019-02-03 01:36
Should be fixed with https://github.com/composer/composer/pull/7946 - please verify if you can.

**Comment by naderman** [comment] 2019-02-05 14:39
You can use a current composer snapshot to test this `composer self-update --snapshot`.

I'll close this because I think it was fixed. Please comment/reopen if this is still a problem.

**Closed by naderman** 2019-02-05 14:39 UTC
Labels: Solver, Support
