### ISSUE TITLE
Composer 1.4+ fails to resolve dependencies on private repositories

### ISSUE THREAD

**Issue by halles** [composer/composer#6383] opened 2017-04-27 00:50 UTC
We are having issues with composer 1.4+, as it is not being able to resolve our private packages stream. We stand behind a toran proxy install that holds two streams, a public one which basically proxies public packagist packages and a private one for our private stuff.

When composer 1.4+ is resolving the dependencies, it will try to look for the private packages on the public stream thus failing after three retrials, and falling back to the cached versions. Version 1.3.3 is working as expected. I'm documenting the behaviour as detailed as I can, although I have redacted out of the configuration files several domain and project names that we'd like to remain private. Regardless of these modifications, the behaviour from running the same composer update command under composer 1.3.3 renders the expected results by resolving correctly to the private packages. Sadly I cannot provide access to these private packages.

The output from running `composer update --no-dev --no-interaction -vvv --profile` is a fairly regular output other than getting a bunch of lines like this:

```
[7.8MB/10.39s] Warning from https://packages.redacted.domain/repo/packagist: The original providers could not be fetched
```

The output is fairly long so I put it in a gist file `https://gist.github.com/halles/d1b626e4fb29003db6b50744ccef9d41`

Other debug information:

`composer.json`:

```json
{
  "name": "project1/vertical-project2",
  "description": "------------------------------",
  "license": "proprietary",
  "type": "project",
  "authors": [
    {
      "name": "Company Ltd",
      "email": "hello@company.domain"
    }
  ],
  "minimum-stability": "stable",
  "config": {
    "preferred-install": "dist"
  },
  "repositories": [
    {
      "type": "composer",
      "url": "https://packages.redacted.domain/repo/private/"
    },
    {
      "type": "composer",
      "url": "https://packages.redacted.domain/repo/packagist/"
    },
    {
      "packagist": false
    }
  ],
  "require": {
    "nfriends/vertical-project2-bundle": "*"
  },
  "extra": {
    "installer-paths": {
      "public/app/skins/{$name}/": [
        "type:project3-skin"
      ],
      "public/app/mu-plugins/{$name}/": [
        "type:wordpress-muplugin",
        "type:wordpress-plugin"
      ],
      "public/app/plugins/{$name}/": [
      ],
      "public/app/themes/{$name}/": [
        "type:wordpress-theme"
      ]
    },
    "wordpress-install-dir": "public/wp"
  }
}



```

Output of `composer diagnose`:

```
3edgy5life:derp xtc$ composer diagnose
Checking composer.json: WARNING
require.nfriends/vertical-project2-bundle : unbound version constraints (*) should be avoided
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

**Comment by halles** [comment] 2017-05-02 22:22
@Seldaek let me know if you would like to have more output and tests on this.

**Comment by maarten00** [comment] 2017-05-08 15:15
Confirming I'm also having this issue, running Composer 1.4.1 and Toran 1.5.3.

**Comment by amansilla** [comment] 2017-06-22 10:49
I've same issue running composer 1.4.2 and Toran 1.5.3

**Comment by bjoern-flagbit** [comment] 2017-06-23 08:04
I've same issue running composer 1.4.2 and Toran 1.5.3

**Comment by jumale** [comment] 2017-07-05 12:06
Same problem here
Composer v1.4.2
Toran v1.5.3

**Comment by jmglsn** [comment] 2017-07-25 11:30
same here, same versions as @jumale

@alcohol  @Seldaek Is there something that we can provide to help tracing the cause?

**Comment by ramsaybell** [comment] 2017-07-26 15:07
We have the same issue with Composer 1.5-dev and Toran Proxy v1.5.3

**Comment by Seldaek** [comment] 2017-08-07 07:56
Sorry for the delay on this everyone. Please upgrade to Toran Proxy v1.5.4 which removes the warning, because as far as I can tell in Composer nothing changed except for the fact that the warning is now shown, but it was still functional.

Unfortunately we can not fully fix that in Composer, it's kind of a design flaw in Toran, which is fixed in Private Packagist by having a single repository. You can upgrade to Toran 1.5.4 but as it is not maintained much anymore I would really advice everyone to please migrate to Private Packagist (https://packagist.com/).

**Closed by Seldaek** 2017-08-07 07:56 UTC
Labels: Support

**Comment by cedvan** [comment] 2017-10-05 12:17
@Seldaek,

I understand your financial need, but there is no longer a solution of proxy for personal use ?

**Comment by Seldaek** [comment] 2017-10-05 13:06
@cedvan nope because what we see is that many companies abuse the personal use version instead of getting a license, making the whole thing unsustainable. Plus for personal use there is anyway little benefit to using such a solution IMO.

**Comment by cedvan** [comment] 2017-10-05 14:00
I understand, but personally I use it so personal...

I find it a pity to block the honest people. They will be forced to develop their own solution, and will not be to your advantage.

**Comment by alcohol** [comment] 2017-10-05 14:09
For personal use, there is [composer/satis](/composer/satis). Which we also offer as a Docker container. Not nearly as fancy as Toran Proxy though, and definitely not as full-featured as packagist.org though.

**Comment by mrgrain** [comment] 2017-10-06 00:28
@cedvan I can actually understand the move. I just find the pricing very steep from Toran, especially since we basically loose some functionality (and also getting a bunch of new things).
