### ISSUE TITLE
"composer update" with path option "symlink=true" deletes files in local repository

### ISSUE THREAD

**Issue by rosasurfer** [composer/composer#5676] opened 2016-09-14 12:12 UTC
Composer: v1.2.1
PHP: v5.6.12
OS: Windows 7 Pro and admin rights (means ability to create both junctions and real symlinks)

My `composer.json`:
```json
...  
    "repositories": [
        {
            "type": "path",
            "url":  "../../local-packages/my-package",
            "options": {
                "symlink": true
            }               
        }
    ],       
...
```

Without option "symlink=true":
```
$ composer update
Loading composer repositories with package information                                       
Updating dependencies (including require-dev)    
- Installing my/package (dev-master)
    Junctioned from ../../local-packages/my-package
Writing lock file
Generating autoload files
```

With option "symlink=true":
```
$ composer update
Updating dependencies (including require-dev)           
- Installing my/package (dev-master 3683433)
    Cloning 36834331bc9df184f41122710e43d85682f43cd0 from cache
Writing lock file
Generating autoload files
```

Expected result:
- a symlinked "vendor/my/package"

Actual result:
- a cloned "vendor/my/package"
- all files in ../../local-packages/my-package and subdirectories deleted
- empty directory structure in ../../local-packages/my-package left

Additional info:
When Composer links the local repo to "vendor" it creates a Windows junction (as can be seen from the output), not a symlink. If you later replace this junction with a real symlink and run ```composer update``` again, the error appears, too, and the result is again an empty local repo with deleted files.

Wild guess: It seems Composer can't handle correctly Windows symlinks. If an update is required (SHA1 hash of the repo changed) it first deletes the repo in "vendor" and then re-creates it by linking to the local one. Because it doesn't recognize the real symlink "deleting everything in vendor" deletes the original repo.

**Comment by Seldaek** [comment] 2016-09-15 13:53
We can't reliably symlink on windows so we create junctions which are kinda equivalent.. What are you trying to achieve exactly?

Regardless, it shouldn't wipe stuff outside of the vendor dir ever so that bit looks like a bug for sure. /cc @curry684

**Comment by curry684** [comment] 2016-09-15 14:10
Oopsie was already looking into this this morning but got interrupted.

What you are describing is really weird. I didn't build the `symlink` option itself, but by its very nature enabling/disabling it should only ever switch between copying or symlinking. On Windows platforms junctioning is used instead of symlinks. Omitting the `symlink` option implies try symlink, otherwise copy, ref https://github.com/composer/composer/pull/4933#issuecomment-186209850

I don't think however the symptom points to the right cause here, as it's blatantly impossible for a path repository to be cloned from the cache. What appears to be happening:

- The junction is applied correctly as it should with `symlink:null`
- During update some *other* mechanism thinks the package was sourced from a git repo, and declares it a real package, wiping the old version before installing a new one

I have no idea how this could happen as the git clone indicates it's bypassing all native path repository mechanisms. I suspect some changes in the caching code could cause this, but I'd have to investigate. One way or another I also suspect this is completely unrelated to the `symlink` flag and you can reproduce it without.

**Comment by rosasurfer** [comment] 2016-09-15 14:38
The fact it is cloning comes from the other repository settings. "symlink=true" fails, for whatever reason. so it tries the next repo location which in my case is cloning from github. 
snippet:
```!json
    "repositories": [
        {
            "type": "path",
            "url":  "../../local-packages/my-package"
        },
        {
            "type": "vcs", 
            "url":  "https://github.com/my/package" 
        }
    ],       
    "require": {
        "php":                   ">=5.6",
        "my/package": "dev-master"
    },
```

What I'm trying to achieve is the following: 
- Setup a Composer configuration enabling our team to develop locally with shared repos in the developer machine's file system (repo type=path) both under Linux and Windows.
- Make the same configuration clone/update the packages from Github on the deployment server and skip the local part (as it doesn't exist on the production server).
- If possible achieve all this with one single composer.json that can be pushed to the repo (instead of mangling with a local composer-local.json)

This is proprietary code so the packages can't reside at Packagist.

In playing with the available options (especially with "path" since last month) I just tried the effect of "symlink=true" on the machines, which wiped the repos there.
The message "cloning from cache" shouldn't matter, it just says it already cloned that repo from Github before and had it in the cache.

The wiping is reproducable. Finally I realize I can skip "symlink=true" all together, however the fact it wiped at all on Windows was worth to be mentioned here, imho.

**Comment by curry684** [comment] 2016-09-15 14:56
Yikes, so the exact same package called `my/package` is in both the path repo and the VCS repo? That could potentially cause a very nasty situation where the package is installed according to the first rules (junction) and then deleted according to the second rule, a VCS repo can always be plain deleted, and this only causes the havoc on Windows because a junction isn't reliably detected by Symfony FileSystem's recursive delete functions - they stop at symlinks, not at junctions.

What could also be happening is that the package is deleted by *both* downloaders able to provide the package, with the same result as the VCS driver would recurse through the symlink.

@Seldaek should it even be an allowed scenario that the same package can be sourced from multiple conflicting custom repositories?

**Comment by rosasurfer** [comment] 2016-09-15 15:01
I think Composer should stop at the first location it finds the package, otherwise repo "type=path" doesn't make much sense for packages that reside on Packagist or elsewhere.

But another situation comes to my mind: What is the expected behaviour if the local repo is "behind" a remote version (somebody else might have pushed). In this case the remote version would be newer than the local one. However, I think Composer should always prefer the local one as merging is in the responsibility of the developer. Otherwise the setup "linked local repo" would again be get messed up. 

What are your thoughts in regard to this?

**Comment by curry684** [comment] 2016-09-15 15:03
Semi offtopic btw:

> OS: Windows 7 Pro and admin rights (means ability to create both junctions and real symlinks)

This is not entirely true regrettably. Junctions are a userland feature, and every user can make them. An administrator can make real symlinks as well but still requires elevation, ie. a "Run as Administrator" command prompt, most specifically accepting the UAC alert that causes. This is the reason we could only implement junctions as symlinking would require all users to always run Composer with elevation. Despite the practical issues this would in practice mean you'd be executing plugins and installers with full root rights, something we try like hell to avoid on *nix.

**Comment by curry684** [comment] 2016-09-15 15:06
@rosasurfer I'm pretty confident I feel that Composer should always prefer the first valid candidate, but a lot less that that's actually what's happening. Hence my question to Seldaek, he may know from the top of his head what (intended) behaviour is there. It's a messy (and exotic) scenario though.

**Comment by rosasurfer** [comment] 2016-09-15 15:08
I understand but creation is not required (UAC implications). What is required is reading/detection that we are working on a symlink. A symlink can be resolved and detected without UAC, if I'm correct. Would be enough to protect from any damage.

**Comment by rosasurfer** [comment] 2016-09-15 15:10
I don't agree with your "messy thoughts". It's the most typical scenario for a team working with closed code and on a shared code base. Many projects, custom libraries, repo-server in-house. I can't imagine something more typical.

**Comment by curry684** [comment] 2016-09-15 15:16
The symlinks are a chicken-egg issue - we don't need to detect them if we don't create them because we can't create them   :)  

As for the exoticness: I have a 10 man team with a private Satis install sourced from closed shared code in private GitLab. None of us have ever used the VCS drivers, and we only rarely use path repositories during initial package development. We have also never experienced this specific issue hehe.

**Comment by rosasurfer** [comment] 2016-09-15 15:17
He-he, obviously you have no problem to delete them :-)

**Comment by curry684** [comment] 2016-09-15 15:32
Is the situation in https://github.com/composer/composer/issues/5676#issuecomment-247347204 the full [SSCCE](http://sscce.org/) that reproduces the situation reliably and reproducably? I'll really need to be able to consistently reproduce it to find the underlying issue, so if you could check that - yes please.

**Comment by rosasurfer** [comment] 2016-09-15 17:48
I have to step back a bit. You were right, to reproduce it the cache indeed needs to be in a specific state which I can't exactly describe. To re-check I setup everything up brandnew in a VM and the bug disappeared. Deleting a repo should never happen whatever state the cache is in. However, this doesn't help at the moment. I will watch it. Thank you.

**Comment by curry684** [comment] 2016-09-16 07:40
Yeah I figured as much. There simply is no connection whatsoever between the path repository code and any kind of Git connectivity, so *something* is at some point or another causing your environment to get corrupted. It really seems like 2 completely unrelated mechanisms clashing somewhere, hence why I have no idea where to start debugging without a reproducable sample.

We can keep this issue open for the time being and close it as a fluke later if it never occurs again.

**Comment by Seldaek** [comment] 2016-09-18 15:23
Yeah I tend to agree here, if you can't figure out how to reproduce, it is kinda hard to fix.

That said, if you have the same repo defined both as path and as vcs, it might indeed be that it switches from the path to the git one if the git one has a newer commit than your local path repo. It shouldn't I think, but maybe I'm wrong. Anyway this shouldn't be very hard to try and verify if someone wants to dig in. But according to the code AFAICT it should always pick the package from the first repo it finds it in, as long as it is matching the requirements that is.

**Closed** 2016-10-01 11:07 UTC
Labels: Bug

**Comment by greg-1-anderson** [comment] 2019-10-25 12:50
> it should always pick the package from the first repo it finds it in, as long as it is matching the requirements that is.

We're having this situation. We have a path repo `drupal/core` whose source location is `/core`, and whose installation location is equal to its source location (from the composer installers plugin). If someone changes the version constraints of dependencies in the `require` section inside drupal/core's composer.json, and then runs `composer update drupal/core`, then Composer thinks that `drupal/core` is not installable, because its dependency constraints do not match what is currently installed. This failure to match requirements causes Composer to re-install from Packagist, which erases the `/core` directory. (n.b. `drupal/core` exists as a path repo because that is how we do development, and it exists in Packagist because we run a subtree split to put it there.)

The update works correctly if the packages being changed are whitelisted on the commandline, or if `--with-dependencies` is used. It is rather inconvenient to have a minor mistake in an update command invocation remove a source directory, though.

**Comment by Seldaek** [comment] 2019-10-25 13:01
@greg-1-anderson please report a new issue for this, with clear step-by-step reproduction steps.

**Comment by greg-1-anderson** [comment] 2019-10-25 14:41
Yeah will do.

**Comment by greg-1-anderson** [comment] 2019-10-25 19:43
Created #8389
