### ISSUE TITLE
[2.4.0RC1] How to enable auto completion?

### ISSUE THREAD

**Issue by mitelg** [composer/composer#10961] opened 2022-07-22 07:28 UTC
Hello there :wave: 

I just installed the latest RC of 2.4.0 and wanted to try the new autocompletion feature. But I have troubles to get it working :slightly_smiling_face: 

I am on Ubuntu 22.04 and normally I am using zsh, but to try the feature I switched to bash. 

I tried to execute the commands stated in the docs, and I would expect that `composer update symfony <tab>` will now show me some Symfony packages to update, but nothing happens. 

I then had a look for using bash autocompletion with zsh and found this on SO https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh
This works like a charm. :+1: 

Thanks in advance for your help and thanks for your work on Composer! :heart: 

PS: Everything else seems to work fine so far, I really like the `audit` command

**Comment by GuySartorelli** [comment] 2022-07-22 07:54
For anyone who sees this but doesn't notice the PR: https://github.com/composer/composer/pull/10962

**Comment by mitelg** [comment] 2022-07-22 07:58
My PR still does not solve the problem of the autocompletion not working for me with bash :wink:

**Comment by GuySartorelli** [comment] 2022-07-22 08:17
Ahh, okay. The wording of the PR description seemed to imply you had resolved whatever the problem was. My mistake.

**Comment by Seldaek** [comment] 2022-07-22 08:24
Maybe try to patch the completion file with https://github.com/symfony/symfony/pull/47022 see if it helps you?

**Comment by Seldaek** [comment] 2022-07-22 08:27
Right, confirmed that it needs that patch - otherwise it only seems to work if you call composer via an alias.

**Comment by dkarlovi** [comment] 2022-07-22 09:15
@Seldaek I'm using the PM provided by Remi (which patches in the patch already) and can confirm it works for me as expected.

**Comment by mitelg** [comment] 2022-07-22 09:55
> Maybe try to patch the completion file with [symfony/symfony#47022](https://github.com/symfony/symfony/pull/47022) see if it helps you?

hey @Seldaek 
I can also confirm, that this patch is fixing my problem :+1:

**Comment by Seldaek** [comment] 2022-07-22 10:47
01a7bb8e5 fixes it for now in snapshot builds.. I'll probably delay 2.4.0 until a symfony patch release happens.

**Comment by dkarlovi** [comment] 2022-07-22 11:06
Maybe RC2 to allow Remi to remove the inclined patch?

**Comment by GuySartorelli** [comment] 2022-07-30 01:48
Symfony 5.4.11 has released with the fix included
https://github.com/symfony/symfony/releases/tag/v5.4.11

**Comment by Seldaek** [comment] 2022-07-30 11:09
Yup.. I'm on vacation now tho so will see if I find time to do a release or probably I'd rather wait until I'm back for the 2.4 stable to avoid any urgent issues due to regressions.

**Comment by GuySartorelli** [comment] 2022-07-30 11:41
That's fair. Enjoy the vacation!

**Comment by Seldaek** [comment] 2022-08-16 14:19
2.4.0 is out https://github.com/composer/composer/releases/tag/2.4.0

**Closed by Seldaek** 2022-08-16 14:19 UTC
Labels: Bug
