### ISSUE TITLE
Feature suggestion: composer outdated advanced

### ISSUE THREAD

**Issue by icanhazstring** [composer/composer#8104] opened 2019-04-18 08:10 UTC
**Feature description:**
`composer outdated` currently shows a list of packages where an update for your used constraint is available. But I got no information about what might have changed. Some packages don't even follow SemVer which is a huge problem for larger projects.

To avoid problems with that, you would have to manually find the *changelog* or compare tags by using the GitHub compare url. But even that you have to write yourself.

What I suggest are two things:
1. Output a link to the changelog/compareUrl for the package when running `composer outdated`
2. Maybe add a new key in the `support` section of `composer.json` for providing a value for the `CHANGELOG.md` of a package. See [Docs](https://getcomposer.org/doc/04-schema.md#support)
 
    ```
    {
        "support": {
            "changelog": "https://github.com/repo/package/blob/master/CHANGELOG.md"
        }
    }
    ```

    With the provided link it would be possible (if the changelog is in certain format) to directly anchor the new version tag like: https://github.com/repo/package/blob/master/CHANGELOG.md#1.1.0

   If there is no config value provided. A link to github compare or even the tag itself could be displayed (see below)

**What are you trying to solve?**
Current problem I have with some major projects, mostly proprietary ones, is that you can't just run `composer update` and push it to production. There were some major issues (like SemVer problem) which caused a lot of trouble. To integrate some kind of "weekly report" about new updates. A change in `composer outdated` would help with that.

**How could this look like?**
For this to look nicely we could change the output into a table format and add some more information. Maybe something like this:
![image](https://user-images.githubusercontent.com/883543/56345836-f98ea100-61c0-11e9-9a47-3c420d0957ff.png)

**Are there similar libraries?**
Yes, as of yesterday there is one. But this is currently working with `composer update`.
But as I wrote above, in the process this is kind of late. I don't want to run `composer update` over all packages to see what has changed, just to revert the changes and run `composer update repo/package` on single targets.

https://github.com/pyrech/composer-changelogs

I don't want to badmouth the repo from @pyrech here. This package works like charm.
Maybe we can even get him on board to integrate this into composer itself.

---
As the specs are not set in stone. I would love to iterate some other ideas on how we could achieve this with composer directly instead of the need for people to require another library.

**Comment by localheinz** [comment] 2019-04-18 08:32
Would be awesome if at least the link to the diff could be displayed, similar to https://github.com/pyrech/composer-changelogs!

**Comment by alcohol** [comment] 2019-04-18 09:11
I think this is a problem that plugins can solve perfectly. This does not belong in Composer core IMHO. Way too complex and completely out of scope.

**Comment by alcohol** [comment] 2019-04-18 09:16
Have you tried running the mentioned plugin with an update in dry-run mode btw? I do not know if that process still provides sufficient information for the plugin to determine the changes etc, but if it does, that would reduce the need to revert any changes.

**Comment by icanhazstring** [comment] 2019-04-21 13:26
As @localheinz pointed out. At least a link to the diff with the version tags is not quite "out of scope".
Since this is the point of `composer outdated` to see what packages are outdated and what might have changed. Also the complexity is not really high with that one.

And no. Unfortunately `--dry-run` does not work.

**Comment by ThomasLandauer** [comment] 2022-01-09 13:41
This is the same as https://github.com/composer/composer/issues/5673, isn't it?

**Comment by Seldaek** [comment] 2022-06-07 07:16
Yes, closing as duplicate of https://github.com/composer/composer/issues/5673

**Closed by Seldaek** 2022-06-07 07:16 UTC
Labels: Feature
