### ISSUE TITLE
Load classes from phar

### ISSUE THREAD

**Issue by flip111** [composer/composer#5036] opened 2016-03-10 23:39 UTC
It would convenient if the composer autoloader can be used to load files from phars. There is a package which can be put inside a phar, the phar will retain the directory structure (PSR-0 or PSR-4). Can i somehow point to the phar and tell it to look there for files with a certain namespace and try to load them with PSR-0/4 but then inside the phar?

Second question: can i copy the composer autoloader to another place throw away the vendor folder and the composer.json so i only keep the autoloading part?

**Comment by curry684** [comment] 2016-03-11 08:47
I'm not sure it's possible to mount any autoloader at all to point from outside a phar inside a phar, I suspect it isn't. Also I don't really see the point as phars are intended to be standalone distributables, kind of exactly the opposite of what Composer is doing (interdependent distributables). What  are you trying to achieve?

> can i copy the composer autoloader to another place throw away the vendor folder and the composer.json so i only keep the autoloading part

I don't really see the point of this but sure.

**Comment by flip111** [comment] 2016-03-11 09:05
I would like to use libraries without being dependent on composer, but leaving composer as an option. If i have just 1 php script file and i can add libraries by just including a phar file it would be pretty convenient in some situations. However since some libraries need their own vendors i would get quite a bit of code duplication, for that i would like to bring in (bring back) composer to the project. But i only need composer to check dependencies and create the autoloader, not to download the packages.

**Comment by curry684** [comment] 2016-03-11 09:09
You can use `composer dump-autoload` to [do only that](https://getcomposer.org/doc/03-cli.md#dump-autoload). I'm just not really seeing how you would make this work as the autoloaders we generate depend on the `vendor` structure generated by our installer. So without that the autoloader is pretty pointless.

**Comment by Seldaek** [comment] 2016-03-15 10:47
Closing as I don't think we can really do anything here but feel free to keep discussing as needed.

**Closed by Seldaek** 2016-03-15 10:47 UTC
Labels: Question

**Comment by mindplay-dk** [comment] 2019-02-27 07:57
> I'm not sure it's possible to mount any autoloader at all to point from outside a phar inside a phar

It ships with a stream-wrapper, so presumably (untested) this is possible:

```php
Phar::loadPhar('/path/to/phar.phar', 'some-name.phar');

require_once 'phar://some-name.phar/src/SomeClass.php';
```

Note that `Phar::loadPhar()` only loads the manifest, so it should perform just fine.

In an autoloader, you wouldn't even have to do that up front though - the autoloader could just keep track of which archives it has already loaded, and mount them only when needed.

For bloated shit like `aws/aws-sdk-php` and `google/apiclient-services`, this would be a freaking life-saver - if we could download and install a single archive instead of unpacking thousands of files every time they change one of these two-hundred-in-one crap-bundles, that would probably be about a gazillion times faster... and also, code in Phar archives actually loads (from bytecode cache) faster than flat files.

If you can envision the mainstream web-frameworks shipping phar binaries as well, that would probably be a better experience for many of the Joe Average PHP developers who deploy their code via FTP to a live web-server as well - e.g. being able to upload just one file to install a security upgrade.

I think there's a huge, untapped potential to vastly improve the ergonomics of big packages here.

**Comment by curry684** [comment] 2019-02-27 10:19
> if we could download and install a single archive instead of unpacking thousands of files every time they change one of these two-hundred-in-one crap-bundles, that would probably be about a gazillion times faster...

I just benchmarked unzipping the 2.0MB `aws.zip`, downloaded from https://docs.aws.amazon.com/aws-sdk-php/v3/download/aws.zip:
```
real	0m0,165s
user	0m0,035s
sys	0m0,104s
```
By contrast, the phar at https://docs.aws.amazon.com/aws-sdk-php/v3/download/aws.phar is 13MB, and as such takes 6.5 times longer to download. On an average 50Mbit high speed connection with 20% protocol overhead the install times would therefore be:

1. Download zip in 0.4s, unzip in 0.165s, total 0.565 seconds, or
2. Download phar in 2.6 seconds

As the zip approach is actually 5 times faster instead of a "gazillion times" slower I don't really see high potential for life-changing optimizations there.

> and also, code in Phar archives actually loads (from bytecode cache) faster than flat files.

I highly doubt that actually. Do you have reproducible evidence of this?

**Comment by flip111** [comment] 2019-02-27 13:09
The thing with unzip is that if you pass it to someone else you have to pass instructions along to unzip it. Making it already "complicated". You could says if they knew how to run a php script surely they know how to unzip, if only that were true.. One of the biggest confusions about zip files is unpacking them into the current folder vs unpacking them in their own sub folder. Then when you want to move the script what do you copy? The zip file, the vendor folder? If you copy the vendor folder it can be slow because there are tons of really small files. If you copy the zip file only and delete the folder you will have to pass this again as additional instructions to someone. There are plenty of people that work with computers and are good at what they do, but still have trouble doing things they have never done before. Then they call you "it doesn't work, your php script makes errors" and see they extract the zip to the wrong place.

What happened to php (in my humble opinion) is that before it was "just a scripting language" .. but you could actually pass scripts around and they would just work. Now php is more a "programming language" with mature package management. And so it becomes more complicated for the "just being a scripting language"-part of it. The load from phar idea was there just to be able to place another file together with your script and it would just work regardless.

Anyway i understand when someone is doing professional php development on a daily basis they no longer need or see the use of doing things like this. Especially if you program for web it's all much more structured now. The use case was for scripting where php competes with bash and likes. All though @mindplay-dk use case of simple FTP upload is also a good one, because when you have only FTP you don't get to unzip on the server.

I guess what i'm trying to say is that with new technology old technology is getting more complicated.

**Comment by mindplay-dk** [comment] 2019-03-01 12:01
> By contrast, the phar at https://docs.aws.amazon.com/aws-sdk-php/v3/download/aws.phar is 13MB, and as such takes 6.5 times longer to download

This comparison isn't relevant to what I'm suggesting.

I'm suggesting the actual package could ship as a phar, from which Composer could autoload - this is something entirely different from shipping a runnable phar *with* dependencies.

> As the zip approach is actually 5 times faster instead of a "gazillion times" slower I don't really see high potential for life-changing optimizations there.

The difference could be substantial for Windows users at least, and/or people with slower harddrives.

Updating either of the two mentioned packages on Windows literally takes several minutes on a fast PC.

> > code in Phar archives actually loads (from bytecode cache) faster than flat files.
>
> I highly doubt that actually. Do you have reproducible evidence of this?

There are benchmarks out there, here's the first one I found with a quick search:

https://www.programering.com/a/MzN2ADNwATY.html

It is naturally faster with a bytecode cache, because it only needs to check the timestamp of a single file for modification to see if the cache is still valid - as opposed to checking every individual file.

PHP is well optimized to load phar archives fast - there are natural bottlenecks to accessing hundreds of tiny files, compared with accessing a few larger files.

So yes, it's faster. There's no reason it wouldn't be. And I think there is definite potential to improve the experience here: downloading, autoloading, caching, etc. could all be much faster - for one, Composer could skip unpacking anything at all when a phar binary is available.
