### ISSUE TITLE
Root alias not considered properly

### ISSUE THREAD

**Issue by Toflar** [composer/composer#10747] opened 2022-04-21 08:07 UTC
My `composer.json`:

```json
{
    "name": "contao/managed-edition",
    "license": "proprietary",
    "type": "project",
    "require": {
        "contao/manager-bundle": "4.13.*",
        "contao/manager-plugin": "dev-main as 2.12.0"
    },
    "config": {
        "allow-plugins": {
            "contao/manager-plugin": true,
            "contao-components/installer": true
        }
    }
}
```

Output of `composer diagnose`:

```
Checking composer.json: OK
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.3.5
PHP version: 8.1.4
PHP binary path: /usr/local/Cellar/php/8.1.4.reinstall/bin/php
OpenSSL version: OpenSSL 1.1.1m  14 Dec 2021
cURL version: 7.82.0 libz 1.2.11 ssl (SecureTransport) OpenSSL/1.1.1n
zip: extension present, unzip present, 7-Zip not available
```

When I run this command:

```
composer update
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - contao/manager-bundle 4.13.2 requires contao/installation-bundle 4.13.2 -> satisfiable by contao/installation-bundle[4.13.2].
    - contao/manager-bundle 4.13.1 requires contao/installation-bundle 4.13.1 -> satisfiable by contao/installation-bundle[4.13.1].
    - contao/manager-bundle 4.13.0 requires contao/installation-bundle 4.13.0 -> satisfiable by contao/installation-bundle[4.13.0].
    - contao/installation-bundle[4.13.0, ..., 4.13.2] conflict with contao/manager-plugin <2.0 || >=3.0.
    - Root composer.json requires contao/manager-plugin dev-main as 2.12.0 -> satisfiable by contao/manager-plugin[dev-main].
    - Root composer.json requires contao/manager-bundle 4.13.* -> satisfiable by contao/manager-bundle[4.13.0, 4.13.1, 4.13.2].

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.
```

And I expected this to happen:

The problem is that it seems like my root alias `dev-main as 2.12.0` is not being considered properly.

This is confirmed by the fact that when I use `"contao/manager-plugin": "2.11.1"` (latest bugfix release), it resolves correctly and `"contao/manager-plugin": "dev-main as 2.11.1"` fails again. I also checked if the pool optimizer is the reason but `COMPOSER_POOL_OPTIMIZER=0 composer update` does not result in any changes other than it taking way longer :)

**Comment by Seldaek** [comment] 2022-04-28 07:01
This is partly by design, because when an alias is installed technically the aliased package is installed, and the alias is marked as installed too. If the aliased package has a conflict against it, it is uninstallable, and going around that if it is aliased would have been quite a mess so we decided to keep it that way.

That said here what happens is a bit different so I am not sure.. the conflict matches not against the contao/manager-plugin `dev-main` version but against its `9999999-dev` alias which we add because it is the default branch.

What you have in the pool is:

- contao/manager-plugin-9999999-dev (alias of dev-main)
- contao/manager-plugin-dev-main
- contao/manager-plugin-2.12.0.0 (root alias of dev-main)

And indeed 9999999-dev matches the `>=3.0` part of the conflict.

This is fixable at update time by wrapping `if ($package->isRootPackageAlias()) {}` around https://github.com/composer/composer/blob/e918b6001b4b2bdb6b5f8bfb53c62c11a87eb6de/src/Composer/DependencyResolver/RuleSetGenerator.php#L190 for example. This lets the update go through as it now can install the dev-main & 2.12.0 alias but leave out the 9999999-dev alias.

But if you then run an install against the project, you get a new failure:
```
  Problem 1
    - contao/core-bundle is locked to version 4.13.2 and an update of this package was not requested.
    - contao/core-bundle 4.13.2 conflicts with contao/manager-plugin dev-main.
    - contao/manager-plugin is locked to version dev-main and an update of this package was not requested.
```

This occurs because the 9999999-dev gets recreated when loading the lock file, and it is then seen as installed and locked, but it is conflicting with something else which is installed and locked, and it then looks like a corrupt lock file which cannot be resolved. Fixing this in turn is possible perhaps by not loading the alias if it is not needed but it's not so easy to determine and may lead to other unpredictable issues. The current way is perhaps a little annoying but at least it's deterministic.

The real solution here IMO is that you add a branch-alias to contao/manager-plugin so it does not have the default `9999999-dev` alias anymore but instead a 2.9999999-dev one or something equivalent.

**Comment by Toflar** [comment] 2022-05-03 15:13
Indeed, now it works but it's really confusing :) Imho what should happen is it should "just" not add `contao/manager-plugin-9999999-dev (alias of dev-main)` if there already is an alias for `dev-main`.
Or if that doesn't work then maybe at least try to detect the situation of multiple packages having the same alias and give more info on what one could do. 🤔

**Comment by Toflar** [comment] 2022-05-03 15:13
Thanks for the help ❤️

**Comment by Seldaek** [comment] 2022-05-11 08:29
Or don't use unbound conflicts.. But yeah anyway closing here, I don't think this is a common enough issue to warrant risking causing more issues by changing how aliases behave.

**Closed by Seldaek** 2022-05-11 08:29 UTC
