### ISSUE TITLE
`config.json` platform overrides are ignored

### ISSUE THREAD

**Issue by ThibaudDauce** [composer/composer#9493] opened 2020-11-18 11:21 UTC
My `C:\Users\thibaud\AppData\Roaming\Composer\config.json`:

```json
{
    "config": {
        "platform": {
            "ext-pcntl": "7.4",
            "ext-posix": "7.4"
        }
    }
}
```

Output of `composer diagnose`:

```
❯ composer diagnose
Checking composer.json: WARNING
require.jakoch/phantomjs-installer : exact version constraints (2.1.1-p09) should be avoided if the package follows semantic versioning
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com oauth access: OK
Checking disk free space: OK
Checking pubkeys:
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
Composer version: 2.0.7
PHP version: 7.2.13 - Package overridden via config.platform, actual: 7.4.11
PHP binary path: C:\PHP\php.exe
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
cURL version: 7.70.0 libz 1.2.11 ssl OpenSSL/1.1.1g
zip extension: OK
```

When I run this command:

```
 composer require laravel/horizon
```

I get the following output:

```
Using version ^4.3 for laravel/horizon
./composer.json has been updated
Running composer update laravel/horizon
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/horizon[v4.3.0, ..., 4.x-dev] require ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
    - Root composer.json requires laravel/horizon ^4.3 -> satisfiable by laravel/horizon[v4.3.0, ..., 4.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\PHP\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

And I expected this to happen:

Installation succeed because I set the platform extension inside my global `config.json`.

---

If I set the platform inside the project `composer.json`, `composer require laravel/horizon` is working as expected:

```
    "config": {
        "preferred-install": "dist",
        "platform": {
            "php": "7.2.13",
            "ext-pcntl": "7.4",
            "ext-posix": "7.4"
        },
        "sort-packages": true,
        "optimize-autoloader": true
    },
```

**Comment by naderman** [comment] 2020-11-18 13:16
@ThibaudDauce can you rerun your composer require command with `-vvv` added for debug output and post the full output?

**Comment by ThibaudDauce** [comment] 2020-11-18 13:52
```
❯ composer require laravel/horizon -vvv
PHP Warning:  Version warning: Imagick was compiled against ImageMagick version 1799 but version 1802 is loaded. Imagick will run but may behave surprisingly in Unknown on line 0
Reading ./composer.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/config.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json
Checked CA file C:\Users\thiba\AppData\Local\Temp\ope6715.tmp: valid
Executing command (C:\Users\thiba\Code\quantic-telecom.net): git branch -a --no-color --no-abbrev -v
Reading C:/Users/thiba/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/config.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\thiba\AppData\Roaming\Composer/auth.json
Reading C:\Users\thiba\AppData\Roaming\Composer/auth.json
Reading C:\Users\thiba\Code\quantic-telecom.net/vendor/composer/installed.json
Running 2.0.7 (2020-11-13 17:31:06) with PHP 7.4.11 on Windows NT / 10.0
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing C:/Users/thiba/AppData/Local/Composer/repo/https---repo.packagist.org/packages.json into cache
Reading C:/Users/thiba/AppData/Local/Composer/repo/https---repo.packagist.org/provider-laravel~horizon.json from cache
Downloading https://repo.packagist.org/p2/laravel/horizon.json if modified
Reading C:/Users/thiba/AppData/Local/Composer/repo/https---repo.packagist.org/provider-laravel~horizon~dev.json from cache
Downloading https://repo.packagist.org/p2/laravel/horizon~dev.json if modified
[304] https://repo.packagist.org/p2/laravel/horizon.json
[304] https://repo.packagist.org/p2/laravel/horizon~dev.json
Using version ^4.3 for laravel/horizon
./composer.json has been updated
Reading ./composer.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/config.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/auth.json
Loading config file ./composer.json
Executing command (C:\Users\thiba\Code\quantic-telecom.net): git branch -a --no-color --no-abbrev -v
Reading C:/Users/thiba/AppData/Roaming/Composer/composer.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/config.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/auth.json
Loading config file C:/Users/thiba/AppData/Roaming/Composer/composer.json
Loading config file C:\Users\thiba\AppData\Roaming\Composer/auth.json
Reading C:\Users\thiba\AppData\Roaming\Composer/auth.json
Reading C:\Users\thiba\Code\quantic-telecom.net/vendor/composer/installed.json
Running composer update laravel/horizon
Reading ./composer.lock
Loading composer repositories with package information
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing C:/Users/thiba/AppData/Local/Composer/repo/https---repo.packagist.org/packages.json into cache
Downloading https://repo.packagist.org/p2/php-http/client-implementation.json
Downloading https://repo.packagist.org/p2/psr/http-message-implementation.json
Reading C:/Users/thiba/AppData/Local/Composer/repo/https---repo.packagist.org/provider-laravel~horizon.json from cache
Downloading https://repo.packagist.org/p2/laravel/horizon.json if modified
Downloading https://repo.packagist.org/p2/php-http/client-implementation~dev.json
Downloading https://repo.packagist.org/p2/psr/http-message-implementation~dev.json
Reading C:/Users/thiba/AppData/Local/Composer/repo/https---repo.packagist.org/provider-laravel~horizon~dev.json from cache
Downloading https://repo.packagist.org/p2/laravel/horizon~dev.json if modified
[304] https://repo.packagist.org/p2/laravel/horizon.json
[304] https://repo.packagist.org/p2/laravel/horizon~dev.json
[404] https://repo.packagist.org/p2/php-http/client-implementation.json
[404] https://repo.packagist.org/p2/psr/http-message-implementation.json
[404] https://repo.packagist.org/p2/php-http/client-implementation~dev.json
[404] https://repo.packagist.org/p2/psr/http-message-implementation~dev.json
Updating dependencies
Generating rules
Resolving dependencies through SAT

Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - laravel/horizon[v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, 4.x-dev] require ext-pcntl * -> it is missing from your system. Install or enable PHP's pcntl extension.
    - Root composer.json requires laravel/horizon ^4.3 -> satisfiable by laravel/horizon[v4.3.0, v4.3.1, v4.3.2, v4.3.3, v4.3.4, v4.3.5, 4.x-dev].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\PHP\php.ini
You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by ThibaudDauce** [comment] 2020-11-18 13:53
```
❯ cat  C:/Users/thiba/AppData/Roaming/Composer/config.json
{
    "config": {
        "platform": {
            "ext-pcntl": "7.4",
            "ext-posix": "7.4"
        }
    }
}
```

**Comment by naderman** [comment] 2020-11-18 15:04
@ThibaudDauce And what does your composer.json look like?

**Comment by ThibaudDauce** [comment] 2020-11-18 15:17
I've done more tests. I have in my `composer.json`:
```
    "config": {
        "preferred-install": "dist",
        "platform": {
            "php": "7.2.13"
        },
        "sort-packages": true,
        "optimize-autoloader": true
    },
```

And it's not working.

It's also not working with:

```
    "config": {
        "preferred-install": "dist",
        "platform": {
        },
        "sort-packages": true,
        "optimize-autoloader": true
    },
```

But it's working with:
```
    "config": {
        "preferred-install": "dist",
        "sort-packages": true,
        "optimize-autoloader": true
    },
```

It seems that the `platform` key is not merged if present on the local `composer.json` and in the `config.json`.

**Comment by naderman** [comment] 2020-11-18 15:21
Yes that's what I was about to suggest. Platform is not merged, it is overwritten, this is by design. So going to close this as it's not a bug.

**Comment by ThibaudDauce** [comment] 2020-11-18 15:23
Ok. Do you have an explanation about this design?

I need to keep the `platform.php` on the local `composer.json` because I don't want to install new dependencies requiring new PHP version (my production is PHP 7.2). And every developer on the project need that (so it must be in the local `composer.json`). But the `platform.ext-posix` and `plaftorm.ext-pnctl` are only for my Windows computer (other developers do not care about these overrides)

**Comment by naderman** [comment] 2020-11-18 15:41
@ThibaudDauce We currently have no way to unset individual platform packages or reset the state in a local project, so this is usually less confusing than having to work out what the platform is after a merge. Would have to find a solution https://github.com/composer/composer/issues/7884 before we can reconsider this here.

**Comment by naderman** [comment] 2020-11-18 15:41
@ThibaudDauce for your particular case: It shouldn't hurt your colleagues if you add the extensions to the config for everyone?

**Closed by naderman** 2020-11-18 15:41 UTC
