### ISSUE TITLE
Bitbucket x-token-auth not updating after one hour

### ISSUE THREAD

**Issue by wts-dev** [composer/composer#5389] opened 2016-05-31 16:48 UTC
I often need to clear my cache due to bitbucket expiring the current x-token-auth after one hour. 

With the following composer.json:

```json
{
    "name": "westminster/wts-jobs",
    "version": "1.1",
    "repositories": [
        {
            "type": "git",
            "url": "https://bitbucket.org/westminster/wts-db"
        }
    ],
    "require": {
        "westminster/db": "*"
    },
    "require-dev": {
        "codeception/codeception":"*"
    },
    "config": {
        "bitbucket-oauth": {
            "bitbucket.org" : {
                "consumer-key": "*****",
                "consumer-secret": "*****"
            }
        }
    }
}
```

The first time I run install, it works. But the x-token-auth which is generated gets saved to the composer cache such that after enough time has elapsed, I get the following:

```
$ composer update -vvv
Reading ./composer.json
Loading config file /home/mikr/.composer/config.json
Loading config file /home/mikr/.composer/auth.json
Loading config file ./composer.json
Checked CA file /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem: valid
Failed to initialize global composer: Composer could not find the config file: /home/mikr/.composer/composer.json
To initialize a project, please create a composer.json file as described in the https://getcomposer.org/ "Getting Started" section
Reading /home/mikr/Domains/WTS/Projects/wts-jobs/vendor/composer/installed.json
Running 1.1.1 (2016-05-17 12:25:44) with PHP 5.6.15 on Linux / 4.1.13-100.fc21.x86_64
Loading composer repositories with package information
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git rev-parse --git-dir
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git remote -v
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git remote set-url origin 'https://bitbucket.org/westminster/wts-db' && git remote update --prune origin
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git remote set-url origin 'https://://:***@bitbucket.org/westminster/wts-db.git' && git remote update --prune origin
Executing command (CWD): git --version
Failed to update https://bitbucket.org/westminster/wts-db, package information from this repository may be outdated (Failed to execute git remote set-url origin 'https://x-token-auth:***@bitbucket.org/westminster/wts-db.git' && git remote update --prune origin

remote: Invalid username or password. If you log in via a third party service you must ensure you have an account password set in your account profile.
fatal: Authentication failed for 'https://x-token-auth:***@bitbucket.org/westminster/wts-db.git/'
error: Could not fetch origin
)
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git show-ref --tags
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git branch --no-color --no-abbrev -v
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git branch --no-color
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git show 'master':composer.json
Executing command (/home/mikr/.composer/cache/vcs/https---bitbucket.org-westminster-wts-db/): git log -1 --format=%at 'master'
Reading composer.json of westminster/db (v0.1)
Reading /home/mikr/.composer/cache/repo/https---bitbucket.org-westminster-wts-db/27d0e1e4c5ba78b3ba50401cb77c867640c1c72a from cache
Importing tag v0.1 (0.1.0.0)
Reading composer.json of westminster/db (master)
Reading /home/mikr/.composer/cache/repo/https---bitbucket.org-westminster-wts-db/0f0b9040c4733fbe03f666b0d14922e3a155ee52 from cache
Importing branch master (dev-master)
Downloading https://packagist.org/packages.json
Writing /home/mikr/.composer/cache/repo/https---packagist.org/packages.json into cache
Updating dependencies (including require-dev)
```

My work around is to run:
```
$ composer clearcache
```
But it should be taking into account that the generated x-token-auth needs to be refreshed after 1 hour according to bitbucket.

**Comment by alcohol** [comment] 2016-06-01 13:27
Bitbucket's API is quite painful to use in comparison to Github's. Unfortunately (for you), not a lot of people use it, so there is very little development focus towards it (from our end). Mostly community contributions only. So, fingers crossed :-)

**Comment by wts-dev** [comment] 2016-06-03 18:58
If I were to work on fixing this myself (that is, put in a timeout when composer would rebuild the token), where would be the best place for me to look in the code be? Any suggestions? I notice that the the associated configuration in ~/.composer/cache/vcs/{repository name}/config, does not contain a datetime stamp of any sort. It seems to me that the steps to fix would be something like:
1) save a timestamp to the config file (or would it be enough to keep an eye on the datetimestamp of the config file?)
2) when more than an hour has past, regenerate the x-token-auth token.
3) save that new token to the config file, updating the datetimestamp.

**Comment by alcohol** [comment] 2016-06-03 19:31
Honestly that sounds weird. I would have to invest some time into reading their documentation however. But if it can be easily regenerated, just do that when you detect that it is expired?

**Comment by wts-dev** [comment] 2016-06-03 19:44
What if Composer just always blocks the code from loading the url from the cache when the url contains x-token-auth in the username field? 

I've attached a patch which does just this to /composer/src/Composer/Util/Git.php. 
[patch.txt](https://github.com/composer/composer/files/298295/patch.txt)

**Comment by wts-dev** [comment] 2016-06-03 20:34
I recognize my one liner isn't the best solution under the face of the sun. It certainly leaves the developer in a place where rather than using a perfectly fine x-token-auth, they are always regenerating the token. 

The alternative would be around line 140 of Git.php, to attempt to regenerate the x-token-auth on failure and then resubmit the command. This would involve replicating some of the code found in BaseIO::loadConfiguration() and  around 128 - 140 of Git.php.

Currently, I'm looking to see if Bitbucket gives a reasonable method for testing whether the token is still usable or has expired, since its only response when expired is that the access is unauthorized.

**Comment by peec** [comment] 2016-06-09 13:19
Having the same issue here. Current workaround is to clear composer cache before. Worked then started erroring when token expired.

**Comment by wts-dev** [comment] 2016-06-09 14:45
Yup. Clearing the cache has worked as my workaround as well. Sometimes I
have to go a step further and delete the vendor directory and the lock
file.

**Comment by peec** [comment] 2016-06-13 07:51
Where is these authentication details stored in cache? Deleting the whole cache makes deployments really slow because now we must get all vendors from remote repository. Maybe its possible as a workaround to only delete the cache file where authentication /  oauth is stored.

**Comment by peec** [comment] 2016-06-16 12:17
Hm, any updates on this. The workaround is a very slow one, clearing the whole composer cache takes a lot of time when you want to reinstall dependencies ( note: which happens mostly on deploys ). 

Maybe bitbucket should not store the Oauth 2 token in cache and must get a new one for every time, since it needs to be refresh every hour? I think this is the easiest approach since then you don't have to implement workflow for refreshing new tokens based on the refresh_token.

**Comment by wts-dev** [comment] 2016-06-20 12:41
@peec My patch above essentially does what you suggest. It forces composer, in bitbucket situations not to overwrite the passwords with the cached token. Consequently, it has to retrieve a new token every time. 
I couldn't quite figure out how to set up a test environment and test cases to make sure it works and doesn't break anything else. So unfortunately, it hasn't been tested beyond my own usage.

**Comment by Seldaek** [comment] 2016-06-21 10:16
Closing this as #5363 fixed a ton of bitbucket related problems, please try again after a `composer self-update --snapshot` and see if that fixes it.

**Closed by Seldaek** 2016-06-21 10:16 UTC
Labels: Bug

**Comment by peec** [comment] 2016-07-25 07:59
This seems to be a problem still using snapshot. Token is cached and only available for 1 hour.



How to reproduce:

1. Add a dependency using oauth from bitbucket.
1. Use composer to download the dependency.
1. Wait for 1 hour.
1. Try to use `composer update`. This will now fail since the token (x-token-auth) only lasts for 1 hour.


```
cd vendor/username/myrepo
git remote -v 

composer	https://x-token-auth:xxxxxxxx@bitbucket.org/username/myrepo.git (fetch)
composer	https://x-token-auth:xxxxxxxx@bitbucket.org/username/myrepo.git (push)
origin	https://x-token-auth:xxxxxxxx@bitbucket.org/username/myrepo.git (fetch)
origin	https://x-token-auth:xxxxxxxx@bitbucket.org/username/myrepo.git (push
```

I think one must always generate this token on every composer command or keep a timer on the cached token so that after 1 hour composer will reauthenticate to get a new token.

**Comment by ricardokenji** [comment] 2016-09-14 12:37
Instead of deleting all composer cache you can use composer scripts to delete specifc bitbucket caches:


       "pre-install-cmd": [
          "rm -R /home/user/.composer/cache/vcs/https---bitbucket.org-repository.git/",
          "rm -R /home/user/.composer/cache/vcs/https---bitbucket.org-repository2.git/"
      ],
      "pre-update-cmd": [
          "rm -R /home/user/.composer/cache/vcs/https---bitbucket.org-repository.git/",
          "rm -R /home/user/.composer/cache/vcs/https---bitbucket.org-repository2.git/"
      ]

**Comment by ericlaflamme** [comment] 2016-10-06 16:54
This thread is interesting and helped me diagnose my token expiring problem. Here is how I fix my problem since clear composer cache wasn't enough.

I found that the token was writing in the git config of the project composer was installing. So I have to replace the line 'https://x-token-auth.' with the url without the token in .git/config file in each project that is expose to the problem.

I'm not sure why the token is writing there. Maybe isn't related to composer afterall. But it's in '[remote "composer"]' section.

Hope I helped.

**Comment by dan-andreoli** [comment] 2017-03-07 14:58
Any news on this bug? I've to go through a continuous integration based on bitbucket repository

**Comment by Seldaek** [comment] 2017-03-07 15:04
@dan-andreoli I just merged #6094 which fixes a lot of bitbucket issues.. So make sure you try it again with the latest Composer snapshot (`composer self-update --snapshot`).. Or another way is to use [Private Packagist](https://packagist.com) which now supports bitbucket sync, so you only have to set up bitbucket auth there once and then you have an easy way to auth to us with basic auth and no bitbucket oauth nonsense.

**Comment by bscheshirwork** [comment] 2017-12-12 14:05
Same issue on fresh composer.
```
docker-compose run --rm --entrypoint composer php-client -V
Composer version 1.5.5 2017-12-01 14:42:57
docker-compose run --rm --entrypoint composer php-client global show
Changed current directory to /root/.composer
hirak/prestissimo 0.3.7 composer parallel install plugin
```
I try to access to bitbucket from docker container without ssh-access use https and OAuth.

Also I can share composer files.
```yml
version: '2'
services:
  php-client:
    image: bscheshir/php:7.2.0-fpm-alpine-4yii2-xdebug
    restart: always
    volumes:
      - ./php-code:/var/www/html #php-code
      - ~/.composer/cache:/root/.composer/cache
      - ~/.composer/auth.json:/root/.composer/auth.json
```

I can get error 
```
Package operations: 1 install, 0 updates, 0 removals
  - Installing org/repo (dev-master 00hash00): Cloning 111hash111 from cache
    Failed to download org/repo from source: Failed to execute git clone --no-checkout 'https://x-token-auth:***@bitbucket.org/team/repo.git' '/var/www/html/vendor/org/repo' --dissociate --reference '/root/.composer/cache/vcs/https---bitbucket.org-team-repo.git/' && cd '/var/www/html/vendor/org/repo' && git remote add composer 'https://x-token-auth:***@bitbucket.org/team/repo.git' && git fetch composer

Cloning into '/var/www/html/vendor/org/repo'...
remote: Invalid username or password. If you log in via a third party service you must ensure you have an account password set in your account profile.
fatal: Authentication failed for 'https://x-token-auth:***@bitbucket.org/team/repo.git/'

    Now trying to download from dist
  - Installing org/repo (dev-master 00hash00): Downloading (connecting...)
                                                
  [Composer\Downloader\TransportException]      
  Could not authenticate against bitbucket.org  
```
Worked with https://github.com/composer/composer/issues/5389#issuecomment-246999350
```sh
docker-compose run --rm --entrypoint composer php-client show
org/repo dev-master 00hash00 Description
```

**Comment by Seldaek** [comment] 2018-01-19 08:53
Yes that would might be good to add @tolbon if you wanna send a PR. Definitely seems like the bitbucket types are missing there.

**Comment by neoacevedo** [comment] 2018-08-31 22:14
Good, what I have seen: auth.json is updated with new access token and time expiration each _composer update_ callings, but after a while (maybe 1 hour) the new value is never sent and it causes the error.

**Comment by tolbon** [comment] 2018-09-01 12:04
Hi @neoacevedo 
Which version of composer do you have ?
And how you configure your repo in your composer.json ?

**Comment by neoacevedo** [comment] 2018-09-01 14:40
@tolbon I use the latest version: 1.7.2

In my composer.json I have configured my private repos as:

```json
    "repositories": [
        {
            "type": "vcs",
            "url": "https://bitbucket.org/myuser/myrepo.git
        }
    ],

```
And for instance, if I run just now `composer update my-package` I will receive the error. 

But additional curious, composer is able to read the latest commit version or latest tag, but is unable to download. 

I will change from vcs to git-bitbucket and I will try again.

**Comment by neoacevedo** [comment] 2018-09-05 17:52
Good, the same issue. It doesn't matter if I change from VCS to git-bitbucket. I have to clear cache and sometimes to delete the access token and the access token expiration from auth.json to update from my private repositories.

**Comment by tolbon** [comment] 2018-09-06 09:09
You use an auth.json file in repo or globally ?
What the look like of auth.json please.

**Comment by neoacevedo** [comment] 2018-09-07 17:28
@tolbon in repo, but same result as global.
```javascript
{
    "bitbucket-oauth": {
        "bitbucket.org": {
            "consumer-key": "CONSUMER",
            "consumer-secret": "SECRET",
            "access-token": "ACCESS TOKEN",
            "access-token-expiration": 1536091069
        }
    }
}
```

**Comment by tolbon** [comment] 2018-09-11 09:39
I have this in my auth.json I don't know if it's help
```
{
  "config": {
    "bitbucket-oauth": {
      "bitbucket.org": {
        "consumer-key": "CONSUMER_KEY",
        "consumer-secret": "CONSUMER_SECRET"
      }
    }
  },
  "bitbucket-oauth": {
    "bitbucket.org": {
      "consumer-key": "CONSUMER_KEY",
      "consumer-secret": "CONSUMER_SECRET",
      "access-token": "ACCESS_TOKEN",
      "access-token-expiration": 1516355009
    }
  }
}
```

**Comment by neoacevedo** [comment] 2018-09-12 21:14
@tolbon at the moment, your auth.json configuration works. It isn't in the official documentation.

**Comment by neoacevedo** [comment] 2018-09-15 01:56
Update: not works at all. Just today I got again the same error.
