### ISSUE TITLE
Packagist does not contain valid JSON / Down

### ISSUE THREAD

**Issue by mmjjb** [composer/composer#7013] opened 2018-01-16 13:32 UTC
When I run this command:

```
composer update
```

I get the following output:

```
"https://packagist.org/packages.json" does not contain valid JSON
Parse error on line 1:

^
Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['
https://packagist.org could not be fully loaded, package information was loaded from the local cache and may be out of date
```

I have tried this on 2 complete different servers, and both result in the same problem.

When I go to https://packagist.org/packages.json is is actually empty!
```

```

What happened? is packagist down?

**Comment by narwy** [comment] 2018-01-16 13:32
Packagist is down.

**Comment by narwy** [comment] 2018-01-16 13:33
https://twitter.com/packagist/status/953257504565334016

**Comment by SystemZ** [comment] 2018-01-16 13:34
I can confirm this problem too, can't update one of deps.

**Comment by mstaack** [comment] 2018-01-16 13:40
working again...@Seldaek  can we have some kind of info within composer like
"Maintenance, Please wait" ...

 i flushed all my composer cache and also tried different version trying to fix that issue ;)

**Comment by mstaack** [comment] 2018-01-16 13:42
getting this now:
```
 [Composer\Repository\RepositorySecurityException]                                                                                                                                                  
  The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This could indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.
```

**Comment by mmjjb** [comment] 2018-01-16 13:45
@mstaack me too, I guess we will have to wait a while longer

**Comment by andrewmclagan** [comment] 2018-01-16 13:51
confirming with 👍 

`[Composer\Repository\RepositorySecurityException]
  The contents of https://packagist.org/p/provider-latest%240cbfb40ab72a881d21b70f78286d39cd72e3b0eb8704c13e79dc49624e549973.json do not match its signature. This should indicate a man-in-
  the-middle attack. Try running composer again and report this if you think it is a mistake.`

**Comment by narwy** [comment] 2018-01-16 14:00
Composer should check status of packagist and if error returned then return false with a message.

**Comment by pixiuPL** [comment] 2018-01-16 14:09
`Bad gateway. Nginx`.

**Comment by mwreppa** [comment] 2018-01-16 14:10
@narwy yeah, when this issue with the packagist service down started, composer first stated that i should take a look at my config because composer requested **http**://packagist.org/packages.json which is http and secure-http is true by default.

**Comment by BondITSolutions** [comment] 2018-01-16 14:16
Been pulling my hair over this for an hour, glad it's not me.

**Comment by stephenmudere** [comment] 2018-01-16 14:18
A valid reason to tell the project manager .... composer was down! oops I am the project manager by the way.

**Comment by mmjjb** [comment] 2018-01-16 14:23
**update: Brief update: As service is being fully restored, refreshing DNS will make sure you reach a working server for your composer operations.**
src: https://twitter.com/packagist/status/953257504565334016

**Comment by mmjjb** [comment] 2018-01-16 14:27
Still get an empty signature though...  how about you guys?

**Comment by mstaack** [comment] 2018-01-16 14:28
@mmjjb same here.. guess we have to wait / refresh dns

**Comment by stefan-korn** [comment] 2018-01-16 14:28
For me it's up again. After flushing dns caches, composer update worked and composer require drupal/paragraphs worked.

**Comment by mwreppa** [comment] 2018-01-16 14:29
@mmjjb @mstaack working again for me

**Comment by pixiuPL** [comment] 2018-01-16 14:30
Still down in afraid

**Comment by pixiuPL** [comment] 2018-01-16 14:31
On its up now. Thanks

**Comment by narwy** [comment] 2018-01-16 14:32
"Brief update: As service is being fully restored, refreshing DNS will make sure you reach a working server for your composer operations."

https://twitter.com/packagist/status/953268853890482176

**Comment by mmjjb** [comment] 2018-01-16 14:33
@narwy My dns provider is not that fast...

**Comment by mstaack** [comment] 2018-01-16 14:33
quickfix via hosts:
```
144.217.203.53 packagist.org
```

**Comment by saysa** [comment] 2018-01-16 14:37
Refresh DNS for mac users : 

```
sudo dscacheutil -flushcache; sudo killall -HUP mDNSResponder; say DNS cache flushed
```

**Comment by pixiuPL** [comment] 2018-01-16 14:46
@saysa shouldnt be `dnscacheutil`?

**Comment by saysa** [comment] 2018-01-16 14:52
@pixiuPL No it is really `dscacheutil`

More here : https://help.dreamhost.com/hc/en-us/articles/214981288-Flushing-your-DNS-cache-in-Mac-OS-X-and-Linux

**Comment by narwy** [comment] 2018-01-16 15:08
Wait for the DNS propagation period.

The issue should now be resolved and marked as closed.

**Comment by pixiuPL** [comment] 2018-01-16 15:14
@narwy only if it was true.
DNS propagated;

**Comment by SystemZ** [comment] 2018-01-16 15:21
There is big TTL set on packagist.org so it can take hour or more.
IMHO admin should consider lower TTL like 10 minutes.

Manual enforced IP in /etc/hosts fixed it for me.

**Comment by mauriciogior** [comment] 2018-01-16 16:08
Suggestion: modify error message based on http code returned by packagist.

**Comment by narwy** [comment] 2018-01-16 16:35
@SystemZ Be mindful that the IP could change in the future, so I would suggest removing that from the hosts file after 48 hours.

**Comment by narwy** [comment] 2018-01-16 16:36
I will create a pull request to check for a status code of the site to return false with an error message.

**Comment by Seldaek** [comment] 2018-01-16 16:37
All systems have been restored and our DNS is updated with a 2min TTL so hopefully any future event we can react quicker. Sorry for the inconvenience and have a good day everyone.

Please don't forget to remove any /etc/hosts entries you made as they are not needed anymore.

**Closed by Seldaek** 2018-01-16 16:37 UTC

**Comment by pixiuPL** [comment] 2018-01-16 16:42
@Seldaek thanks.
Little suggestion out of my experience :: 2mins for TTL is - frankly - too few. Standard here is 5mins.

**Comment by joenmarz** [comment] 2018-03-24 22:58
For Windows users, refresh DNS using:

> ipconfig /flushdns

https://joen-marz.blogspot.co.id/2018/03/cara-melakukan-clear-dns-cache-pada-os.html
