### ISSUE TITLE
Cache PSR0 classmaps and enable PSR0 scanning by default

### ISSUE THREAD

**Issue by Seldaek** [composer/composer#998] opened 2012-08-14 18:35 UTC
This would be a good improvement and would allow PSR0 classmap scans to be always enabled. Since that yields faster autoloaders it would be great.

**Comment by benbor** [comment] 2015-12-22 10:18
@alcohol. As i understand, this issue can be closed, because of duplicate of #811

**Closed** 2015-12-23 08:34 UTC
Labels: Feature
