### ISSUE TITLE
`composer.json` does not allow comments

### ISSUE THREAD

**Issue by cweagans** [composer/composer#5364] opened 2016-05-21 20:07 UTC
**I know lack of commenting is a limitation of the JSON format. I'm not attempting to convince anyone that YAML > JSON or that Composer should switch. Simply trying to get to a solution here.**

As developers, we all generally accept that commenting your code is a good thing. As developers, we would also not be too pleased if we had to write all of the code at the top of the file, and then have a specific section at the end of the file where all of the comments needed to live. That would significantly decrease the usefulness of the comments, and the comments would be much more likely to be outdated because they don't exist in the same context as the code that they're talking about.

The unfortunate reality is that by using JSON for the Composer file format, we're locked into that very situation. We have to create arbitrary keys in the `extra` section to document anything that's in `composer.json`.

This should not be the case.

Given that switching to YAML (or other formats) has been ruled out [over](https://github.com/composer/composer/issues/159) and [over](https://github.com/composer/composer/issues/440) and [over](https://github.com/composer/composer/issues/1778) and [over](https://github.com/composer/composer/issues/3228) again, and that I'm not really interested in opening that can of worms, we should try to find some other solution that allows Composer users to properly document things in their `composer.json`. Comments are not an uncommon need, especially for large projects with lots of dependencies.

There are a couple of solutions that I'd like to suggest (in order of my preference):

1. Swap out the JSON parser for an [HJSON](http://hjson.org/) parser (PHP parser already written here: https://github.com/laktak/hjson-php, and it's backward compatible with plain JSON). This seems like a somewhat worthwhile compromise, as it doesn't require anyone to change anything with their projects, but allows people to start using a relaxed syntax + comments in their `composer.json`. Alternatively, upgrade to [JSON5](http://json5.org/) which supports comments, among other things. Looks like there's an existing package for this too: https://packagist.org/packages/hiroto-k/json5-php. Also backward compatible.

2. Change `JsonFile.php` (and anywhere else that package data is read from `composer.json` -- ideally, this would all be consolidated appropriately) such that it strips any lines that begin with `//` (I think we could skip block comments for the sake of simplicity) before doing anything with the contents of the file. Note that Douglas Crockford suggested something similar: https://plus.google.com/+DouglasCrockfordEsq/posts/RK8qyGVaGSr. I'm not sure this is actually against the JSON spec, either, according to https://groups.yahoo.com/neo/groups/json/conversations/messages/152. I think this would require updates for Satis and Packagist as well, but they should be pretty similar changes to what would be required in Composer.

3. Add a `_comment` property to the `composer.json` schema, ideally in a way that it can appear multiple times in a file without breaking validation. This has the benefit of `composer.json` still being valid JSON, and while it's a bit verbose, comments would be easier to deal with. Bonus points if `_comment` can appear as a subproperty of any other existing property. Also consider just using `_` or `#` or `//` as the key to cut down on extra typing to add a comment.

4. If `composer.json` is not found but there's a `composer.yml` present, convert `composer.yml` -> `composer.json`, and then run composer as normal. Yes, this could be easily implemented as a wrapper around Composer, but I'd argue that sane commenting is a widely useful thing to have, and that it shouldn't be relegated to third party tooling. It should be a feature built directly into composer. Note that it's entirely reasonable (IMO) for Packagist and the like to not change their behaviors -- that is, the generated `composer.json` would still need to be committed to the repository (probably in addition to the `composer.yml`). This obviously satisfies the requirement of being able to add comments, but adding an additional translation step is not ideal. Note that this doesn't necessarily need to be YAML - this could be something as simple as `composer.cjson` (commented JSON) -> `composer.json` (normal `composer.json` that we have today).

At the end of the day, I don't really care how this gets solved as long as I can put comments in my `composer.json`. If we come to an agreement on the direction to take, I'm willing and able to implement it. I didn't want to spend a bunch of time on something that would be rejected though, so I thought I'd open this issue first to discuss whether or not any of the ideas above would be accepted.

Thoughts?

**Comment by kamilsk** [comment] 2016-05-22 07:20
How about create a simple converter from yaml to json? Team works with `composer.yml` and dump it with validation to `composer.json`.

**Comment by kamilsk** [comment] 2016-05-22 18:55
add to .bash_profile
```bash
# requires PyYAML
alias yaml2json='python -c "import sys,yaml,json;sys.tracebacklimit=0;print(json.dumps(yaml.load(open(sys.argv[1]).read()), indent=2))"'
```

work with composer.yml, convert it to composer.json: `yaml2json composer.yml > composer.json`

**Comment by kamilsk** [comment] 2016-05-22 19:08
works fine for me https://github.com/kamilsk/Common/blob/3.x/composer.yml

**Comment by cweagans** [comment] 2016-05-22 21:47
@kamilsk That's option 4 above. I do not think this should be 3rd party tooling, nor do I think it's ideal to have an additional translation step between changing your `composer.yml` and actually being able to use Composer to install/update dependencies. This should be something solved in Composer itself, I think.

**Comment by kamilsk** [comment] 2016-05-22 22:11
@cweagans, I really disagree with you. Do you know about `requirements.yml` in `pip`-world or `package.yml` in `npm`-world, or maybe you know about `yamled` gem files? Why not xml, ini, etc? All of them increase complexity for dependency resolving tool. I shown how simple you can resolve your problem without increasing Composer complexity.

https://github.com/npm/npm/issues/3336

**Comment by kamilsk** [comment] 2016-05-22 22:25
In any case, better to introduce YAML than to expand JSON.

**Comment by cweagans** [comment] 2016-05-23 01:01
Please argue your point beyond "I like YAML better" so that we can actually accomplish something here. There are some considerable downsides to your solution (or even adding a YAML to JSON converter directly in Composer), and not a lot of upsides *especially* when compared to the other three solutions.

**Comment by kamilsk** [comment] 2016-05-23 07:31
1. JSON5 is not an official successor to JSON, @Seldaek and @alcohol will get error messages about third-party parser when the composer.json will not be correctly processed

2. \Composer\Json\JsonFile based on ext-json, and
```json
{
   // this json is invalid for json_decode
   "invalid": true
}
```
json_last_error_msg() -> Syntax error

3. _comment block is terrible, how to comment different parts of composer.json

4. if ... else ... is increase complexity. composer.cjson, composer.yml, composer.ini, composer.xml -> composer.json and composer.lock. the packagist does not need comments on your composer.*. So, if you add converter, then it is must be transparency for other developers. Adding this step to workflow should be a conscious decision. And that's why it has to be a third-party solution, not part of the Composer.
- PhpStorm > Preferences > Tools > File watchers > Add new for composer.<your choice> and run <your choice> converter

And why comments in JSON is a problem of Composer? Why not authors of ext-json?

**Comment by alcohol** [comment] 2016-05-23 07:46
Duplicate of #1988, #1778, #440, #159.

**Closed by alcohol** 2016-05-23 07:46 UTC

**Comment by alcohol** [comment] 2016-05-23 07:53
``` json
# file.json
{
  "key": "some comment here about key (this value gets overwritten)",
  "key": "some value"
}
```

``` shell
$ php -r 'print_r(json_decode(file_get_contents("file.json"), true));'
Array
(
    [key] => some value
)
```

**Comment by kamilsk** [comment] 2016-05-23 13:40
@cweagans I create some instructions for your target. I hope that it will be useful for you. http://www.slideshare.net/ssuserb6ada9/octolab-cookbook-how-to-use-composeryml-and-stop-creating-issues-about

Now I start using composer.yml without any pain for composer maintainers.

**Comment by cweagans** [comment] 2016-05-23 15:34
@alcohol I'm not sure how this is a duplicate, especially because I specifically stated that this issue is not about switching to YAML. The unwillingness to discuss any of the solutions presented above is pretty frustrating, especially since I proposed a number of things which, to my knowledge, have not been proposed for Composer before.

@kamilsk Thanks, but depending on third party tooling for something as simple as comments is an inadequate solution. I'm not sure why this issue constitutes "pain" for the Composer maintainers, especially since I offered to implement whatever solution was agreeable.

**Comment by cweagans** [comment] 2016-05-23 15:49
@kamilsk Thanks, but depending on third party tooling for this is not an acceptable solution for my needs. To respond to your specific points from before:

> JSON5 is not an official successor to JSON

Nobody said it was, but it *is* a standard that we can point at to say "This is what is allowed in `composer.json`." There are parsers for JSON5 already. We can just use one.

> \Composer\Json\JsonFile based on ext-json

I'm aware. I don't think you read the suggestion thoroughly enough, but to reiterate, we would strip the comments before passing the JSON along to ext-json. There wouldn't be any parse errors in this case.

> _comment block is terrible, how to comment different parts of composer.json?

As @alcohol pointed out, you can repeat keys in a JSON file (although the spec says that keys SHOULD be unique).

> And why comments in JSON is a problem of Composer? Why not authors of ext-json?

You can bang this drum all you like, but at the end of the day, you still can't comment your `composer.json`. I'm not sure why ext-json would need to be involved. The JSON spec doesn't allow for comments, so it would be a bit of extra niceness that Composer would add on top of JSON to make life a little better for Composer users. Changing the JSON spec is not realistic. Changing ext-json to tolerate non-standard JSON is not realistic. Adding some *very* simple logic to Composer **is** realistic.

@alcohol There's already a lot of support for the ability to add comments in https://github.com/composer/composer/issues/1988. The other three issues you linked to are specifically about switching to YAML and are therefore not relevant to this issue. The unwillingness to at least discuss solutions (some of which have not been proposed before for Composer, to my knowledge) is very frustrating :/

**Comment by Seldaek** [comment] 2016-05-23 16:08
@cweagans to reply to your original post:

- 1/2 have been suggested before, and they are not practical IMO because third party tooling needs to be updated and that kinda sucks.
- 3 is feasible already, much like what @alcohol suggested. Validate will complain maybe but we could perhaps fix that. I use `_` keys myself in some projects when I really need to explain why some dep is locked to some version. Sure `composer validate` sees it as invalid but it's otherwise not an issue at all.
- 4 is technically feasible, but tbh if it's done as a third party tool that transparently does that + calls composer it has no overhead for users and it means it's something we don't need to maintain. I also don't see the benefit of comments as justifying such a mess of having two files.

**Comment by cweagans** [comment] 2016-05-23 16:29
Proposed solutions and JSON spec aside, @Seldaek and @alcohol: Do you agree that comments in a `composer.json` would be helpful? If yes, what can I/we do to resolve this difficulty for Composer users? If no, why not?

@Seldaek:

> 1/2 have been suggested before, and they are not practical IMO because third party tooling needs to be updated and that kinda sucks.

"Third party tooling" meaning Packagist and Satis? I already volunteered to do the work for those projects. Also, note that both of the supersets of JSON suggested in option 2 are 100% backward compatible with regular JSON. That is, only people that opt-in to actually using comments in their root package's composer.json will need to change their tooling to cope with comments in JSON. My guess is that most of the time, this functionality won't be used in a package that actually gets pushed to Packagist anyway, though. It would be more useful for private, internal projects that are just pulling in dependencies from Packagist or whatever other repositories.

> 3 is feasible already, much like what @alcohol suggested. Validate will complain maybe but we could perhaps fix that. I use _ keys myself in some projects when I really need to explain why some dep is locked to some version. Sure composer validate sees it as invalid but it's otherwise not an issue at all.

Well, `composer validate` actually runs as part of my build process. If `composer validate` says it's bad, the build stops. That's easily fixed, sure, but it's also a pretty verbose way of writing comments.

> 4 is technically feasible, but tbh if it's done as a third party tool that transparently does that + calls composer it has no overhead for users and it means it's something we don't need to maintain. I also don't see the benefit of comments as justifying such a mess of having two files.

Yeah, this is definitely not an ideal solution. I only suggested it for the sake of completeness. Personally, I'd prefer to completely replace JSON with YAML, but since that hasn't been received well for whatever reason, I'm trying to come up with other paths forward here.


@Seldaek As an aside, In response to https://twitter.com/seldaek/status/734778522087067648, I don't mean to come across as overly combative here, but if people keep beating that horse, they must have a reason, no? We all acknowledge that comments are good, but every time something has been suggested that attempts to move Composer in that direction, the issue has been closed and conversation stops. That's where my frustration is coming from, so apologies if that came across poorly.

**Comment by stof** [comment] 2016-05-23 16:49
> "Third party tooling" meaning Packagist and Satis?

Third-party tooling meaning **any** tool out there reading a composer.json file. there are many tools reading the composer.json file out there, not only Composer. For instance, your IDE is probably reading it (and it does not use the Composer codebase for that, unlike Packagist and Satis), but they are not the only ones.

**Comment by stof** [comment] 2016-05-23 16:49
the main drawback of your proposal is that you suggest to have a composer.json file which would not be a JSON file

**Comment by cweagans** [comment] 2016-05-23 19:02
@stof The comment handling behavior for JSON is not strongly defined. Some parsers simply ignore them as they should.

What about simply adding support for JSON5 or HJSON with a different file extension? (i.e. `composer.hjson` or `composer.json5` ?)

**Comment by curry684** [comment] 2016-05-23 23:23
Would `composer require foo/bar` insert it in `composer.hjson`, convert it to `composer.json5`, create a new `composer.json`? What if all 3 exist? What if 2 of them exist and have different dependencies? Would we also have a `composer.json5.lock` to ensure the lockfiles are in sync with their sources? Would we need to have similar logic in `installed.json`? Assuming we stick with a sane single lockfile, what happens if both `composer.hjson` and `composer.json5` are updated?

**Comment by cweagans** [comment] 2016-05-24 01:11
@curry684 No, not quite so complicated I think. Pick one of HJSON or JSON5 and add support for that. If `composer.$chosenFormat` exists, use that over `composer.json`. Every time. Or even better, throw a `MakeUpYourMindException` and just complain loudly at the user until they either delete `composer.json` or `composer.$chosenFormat`. `composer.lock` would be unaffected - it should stay the same, contain the same information, etc.

**Comment by curry684** [comment] 2016-05-24 06:57
The problem is quite that complicated though, likely even worse. The `MakeUpYourMindException` would break thousands of existing CI/CD systems out there not cleaning up their folders and suddenly seeing both files end up simultaneously. Keeping both around would cause tons of discrepancies. The Composer 'executable' would grow because of shipping an extra parser.

My main point being - you're talking about changing extremely fundamental and formerly dependable behaviour here in an application running on millions of computers and servers. The only viable route for that is changing format consistently, for everyone, in a single go, and it would still cause a lot of issues. Are you going to handle the hundreds of tickets here in the first 2 days?

**Comment by alcohol** [comment] 2016-05-24 07:00
What is wrong with my solution? Or the one @Seldaek suggested (using `_` as a key). It's backwards compatible, doesn't require any changes, and makes all parties involved in this discussion happy.

**Comment by kamilsk** [comment] 2016-05-24 09:33
> but depending on third party tooling for this is not an acceptable solution for my needs

But you want it to be the Composer team decision, seriously?

> What about simply adding support for JSON5 or HJSON with a different file extension? (i.e. composer.hjson or composer.json5)

You try to open Pandora's box. It is simple for you, because you have done this many times (`composer require once, composer require twice...` - not difficult action). But it hard work for the composer maintainers. Why:

_ 1. support two format forever (yes, "frozen" releases contain composer.json)

_ 2. support tickets like this https://github.com/phalcon/cphalcon/issues/11820 (I am talking about the problem of parsing, and not support there JSON5), because something happen with json5/hjson parser

_ 3. add external dependency and support for it

> Hi! `json5/parser` updated their major version, has BC broken, but now support new cool features. I really want them! Could you update Composer? It is important. Really. I'm not kidding. True.

I run test coverage for:
https://github.com/laktak/hjson-php - "php": ">=5.6", _86%_ lines covered! http://screencast.com/t/yhTOJpqz0NI
https://github.com/hiroto-k/json5-php - "php": ">=5.5.0", _88%_ lines covered! http://screencast.com/t/EuhSOJP781

But actual support version for Composer is "php": "^5.3.2 || ^7.0". Why didn't you check it out before offering?!

All this projects created on this year and don't have sustainable community. Who will support their solutions?

About Pandora's box:

> Why composer.json does not support multiline? I want to write detailed description for my super-duper awesome package.

> Why composer.json does not support inheritance/reference? I want to reuse some code and adhere to DRY principle.

```
"require-dev": &basic { ... }
"suggest": { <<: *basic, "another": "suggest" }
```

> Why composer.json does not support importing?

```
@inlude: "thephpleague/skeleton:composer.json"
"name": "name of my package"
```

_Don't do Package Management Driven Development!_ It is not important in most cases! If you really need it you get it by yourself (start using https://github.com/composer/composer/issues/5364#issuecomment-221183060). I'm done and out from this discussion.

**Comment by Seldaek** [comment] 2016-05-24 09:51
Fixed the `_comment` validation in https://github.com/composer/composer/commit/98b0af1386f7ff730c3330e2525c1d66998c7f90 which makes official that "workaround".

**Comment by cweagans** [comment] 2016-05-24 15:02
> The MakeUpYourMindException would break thousands of existing CI/CD systems out there not cleaning up their folders and suddenly seeing both files end up simultaneously.

What? That's not true at all. If I have a project with `composer.json` in it and I upgrade to a version of Composer that has this new functionality, nothing changes. If I then *add* a `composer.hjson` (or whatever) without removing `composer.json`, then I get the exception. It takes two separate conscious actions to get to that point. It should not be a "suddenly everything is broken" kind of thing at all.

> What is wrong with my solution? Or the one @Seldaek suggested (using _ as a key)? It's backwards compatible, doesn't require any changes, and makes all parties involved in this discussion happy.

I guess it works, but it's very verbose and pretty suboptimal, but if that's the only thing we're going to be able to do, it's better than nothing, I suppose.

> But you want it to be the Composer team decision, seriously?

You know what I mean. It shouldn't live outside of Composer.

> But actual supported version by Composer is "php": "^5.3.2 || ^7.0". Why didn't you check it out before offering?! [...]
> Why composer.json does not support multiline? I want to write detailed description for my super-duper awesome package.
> Why composer.json does not support inheritance/reference? I want to reuse some code and adhere to DRY principle.

So? "You have to upgrade PHP to use the HJSON format in Composer." Done. Or we could consider a different tool that's arguably better for the job, but I've been purposely trying to not steer the discussion there (hint: it rhymes with BLAML).

In general, a lot of your arguments come down to "What if ____ happens or user wants _____?". Taking a feature request to it's most ridiculous extreme to disprove the need for the original feature request is kind of disingenuous, if you ask me. To the users that want imports or multiline or whatever, a "no, do it elsewhere" is acceptable. But the fact that there have been so many issues opened about wanting simple comments in a file that *can get really damn complicated for large projects* is telling. There is a need for this functionality.

> Don't do Package Management Driven Development! It is not important in most cases! If you really need it you get it by yourself (start using #5364 (comment)). I'm done and out from this discussion.

What? We're not talking about an entire new development methodology here, man. We're talking about adding *comments*. This should not be rocket surgery.

> Fixed the _comment validation in 98b0af1 which makes official that "workaround".

Thanks, @Seldaek. I appreciate that. Taking this a step further, If I were to implement something that satisfies the following criteria, would you be willing to consider it? And are there any criteria I'm missing?

* Adds support for a JSON superset or YAML
* 100% backward compatible and opt-in only
* Supported by Composer, Satis, and Packagist
* Doesn't unacceptably bloat Composer
* Doesn't change Composer's version constraints to anything more restrictive

**Comment by stof** [comment] 2016-05-24 15:12
@cweagans but if you suggest that any repositories containing a .hjson metadata file instead of a .json file becomes unusable for any user running PHP 5.3, as composer would not be able to read the metadata file from this repository.
The alternative would be to make the .hjson root-only, i.e. reading only the composer.json for any package meant to be used as a dependency, but this would mean that any shared package wanting to use .hjson to have more advanced features would then have to convert it to .json to (and having some way to ensure that they stay in sync), which is also forbidden by your idea of allowing only one of them.

Btw, allowing multiple metadata files for composer has a major drawback: the repository must then check the existence of both file. This means that the GithubDriver will then have to perform 2 API calls for each branch of the repo (one for each file, and it cannot even skip the second one in most cases if it must forbid having both files). This would slow down repositories (and increase the Github API usage of Packagist a lot btw)

**Comment by alcohol** [comment] 2016-05-24 15:38
@cweagans I would not count on it. What you are proposing violates KISS principles.

We simply do not wish to end up having to support something like this:

![pleasegodno](http://cdn.thisiswhyimbroke.com/images/ultimate-swiss-army-knife1-640x533.jpg)

**Comment by Seldaek** [comment] 2016-05-24 22:02
@alcohol please refrain from using such imagery as it's just not helpful and tends to devolve the discussion into a trollfest.

@cweagans no I'd still rather not have actual comments even if it's BC because even if it's opt in and everything it can still break third party tooling in potentially unpredictable ways, and the added value of comments isn't worth it IMO vs the makeshift comments you can already use in the current state.

**Comment by curry684** [comment] 2016-05-25 07:12
> What? That's not true at all. If I have a project with composer.json in it and I upgrade to a version of Composer that has this new functionality, nothing changes. If I then add a composer.hjson (or whatever) without removing composer.json, then I get the exception. It takes two separate conscious actions to get to that point. It should not be a "suddenly everything is broken" kind of thing at all.

1. Random self-built CD system gets webhook trigger from SCM
2. Downloads dist archive and runs `tar -x`
3. Developer forgot to clean up intermediate folders
4. `MakeUpYourMindException` breaks production environment

You are skipping extremely lightly over the issue that Composer is a vital production tool in integration/delivery processes in tens of thousands of companies. We cannot afford in any way to skip lightly over a change that might break the delivery chain for *any single one of them* without issuing a proper major version. A change like this is so fundamentally breaking it could only go in v2.0.0, and would need compatibility modes and fallbacks.

Doing that to be able to fix something that simply **is not broken right now** is just bad software engineering from every angle.

**Comment by lsloan** [comment] 2016-06-02 22:23
What I've been doing for comments is using a key name that Composer doesn't use for anything else.  The suggestion to use `"_"` is pretty good, too, as long as only one is used within that scope.  If more than one is used, then Composer will give the error, "`Key _ is a duplicate in ./composer.json at line N`".

The [comment above](#issuecomment-220910577) from @alcohol is interesting.  I never thought of using that, however, I don't think it will always work.  I just told a colleague today not to use this in their composer.json:

```json
{"repositories":[{
  "type":"vcs",
  "url":"https://github.com/hoopy-dude/thing-one",
  "url":"https://github.com/hoopy-dude/thing-two"
}],"require":{
  "hoopy-dude/thing-one":"1.0.1",
  "hoopy-dude/thing-two":"dev-master"
}}
```

Because Composer gave the error (seems like it was just a warning), "`Key url is a duplicate in ./composer.json at line 4`".  However, after the `composer install` command completed, `composer show` indicated that both `thing-one` and `thing-two` had been installed.  As it turns out, `thing-one` was available from Packagist, so it was being installed from there.

I noticed this issue because I was researching whether other issues had been opened about the "`Key ... is a duplicate`" messages.  They appear to be warnings, but I would like (I will) suggest that they be treated as fatal errors and Composer should stop processing the JSON file when a duplicate is encountered.  I also found that adding `"packagist": false` to other repository structures, like the one in my example, it's ignored.  That should cause an error, too.

**Comment by alcohol** [comment] 2016-06-03 07:15
> I also found that adding "packagist": false to other repository structures, like the one in my example, it's ignored.

You should open a new ticket regarding this with a minimalistic reproducible scenario. Cause that sounds like a bug to me if that is true :-)

**Comment by dsshafer** [comment] 2016-09-04 14:24
Please, provide some simple mechanism for comments. I just ran into a production issue that could've been avoided with proper comments.

**Comment by sloanlance** [comment] 2016-09-04 15:52
@dsshafer: As the conversation has shown, comments aren't allowed in JSON, but there are workarounds described here.

**Comment by dsshafer** [comment] 2016-09-04 16:38
@sloanlance: As the conversation(s) have shown, developers want a simple commenting mechanism, and the workarounds described here (what I can understand of them) aren't encouraging. :) Try a quick Google search for "composer comments" or "comments in composer.json"-- you'll find closed issues, feature requests, and questions, but nothing resembling a solid resolution or documented workaround. I don't have a solution, but I'm adding my voice to the chorus of developers asking to make this a priority.

**Comment by sloanlance** [comment] 2016-09-04 22:48
Another user added their name to the list of people wanting comments in composer.json by writing:

> Please, provide some simple mechanism for comments. I just ran into a production issue that could've been avoided with proper comments.

I replied as above and he replied to me:

> As the conversation(s) have shown, developers want a simple commenting mechanism, and the workarounds described here (what I can understand of them) aren't encouraging. :) Try a quick Google search for "composer comments" or "comments in composer.json"-- you'll find closed issues, feature requests, and questions, but nothing resembling a solid resolution or documented workaround. I don't have a solution, but I'm adding my voice to the chorus of developers asking to make this a priority.

He's since deleted his remarks for some reason.  I didn't mean to make him feel unwelcome, so I hope that's not it.  Anyway, he might not want to be part of the conversation any longer, so I won't disturb him by @-mentioning his name again.

I don't disagree with him and others' remarks that we need comments in composer.json.  However, I agree with @alcohol and @Seldaek that Composer shouldn't add any features that would make it incompatible with standard JSON.

💡 **_Therefore, it seems that the correct long-term goal is to petition the keepers of the JSON standard to make allowances for comments._**

In the meantime, we should use the workarounds mentioned in this issue to add comments.  Personally, I like the strategy of using an attribute named "_**`attribute_name`**_`-comment`" to add a comment about an attribute named "_**`attribute_name`**_".

**Comment by iandunn** [comment] 2019-07-19 18:35
>  Therefore, it seems that the correct long-term goal is to petition the keepers of the JSON standard to make allowances for comments.

They already have:

> A JSON encoder MUST NOT output comments. A JSON decoder MAY accept and ignore comments.
- [Douglas Crockford](https://web.archive.org/web/20100629021329/http://blog.getify.com/2010/06/json-comments/) (creator of JSON)

Comments are not invalid in JSON _per-se_, they're just supposed to be ignored. [The JSON linters should support an option to do that](https://github.com/Seldaek/jsonlint/issues/58).

**Comment by vtsykun** [comment] 2023-02-09 01:37
I found a simple way how to add comments support by patching `composer.phar`. 
Initially I tried to make a plugin, but the Composer `Factory` is called before the plugin is loaded, so the Composer will throw an error before the plugin is loaded.

The idea is that I can declare a custom `json_decode` function under `Composer\Json` namespace that will override `json_decode` function from the global namespace only for `JsonFile` class. This is hack, but very easy for implementation
 
```php
namespace Composer\Json;

if (!\function_exists('Composer\Json\json_decode')) {
    function json_decode($json, $associative = null, $depth = 512, $flags = 0)
    {
        if (null === ($result = \json_decode($json, $associative, $depth, $flags))) {
            $minify = \preg_replace('#(([},{\[\]]|false\b|true\b|null\b|\d\b|\w")//.*)|(\s//.*)|(^//.*)#', '$2', $json);
            $minify = \preg_replace('#\s*(?!<\")/\*[^*]+\*/(?!\")\s*#', '', $minify);

            return \json_decode($minify, $associative, $depth, $flags);
        }

        return $result;
    }
}
```

I created composer phar patcher tools for this https://github.com/packeton-org/composer-comments

**Comment by red8888** [comment] 2023-08-14 13:29
Hello, this is still an issue. Regression maybe???

I have an SO post as well: https://stackoverflow.com/questions/76860410/does-composer-not-support-comments-in-requriements-txt/76886280#76886280


This is my requirements.txt:
```
# This is a comment
python-json-logger==2.0.4
# Here's a private package
my_private_pypi_package==1.2.3
```

I get an error:
```
> gcloud composer environments update myenv  --format=json --project myproj --location=us-central1 --update-pypi-packages-from-file='requirements.txt'

ERROR: (gcloud.composer.environments.update) INVALID_ARGUMENT: Found 2 problems:

    1) Error validating key # Here's a private package. PyPI dependency name is not formatted properly. It must follow the format of 'identifier' specified in PEP-508.
    2) Error validating key # This is a comment. PyPI dependency name is not formatted properly. It must follow the format of 'identifier' specified in PEP-508.
```

**Comment by xabbuh** [comment] 2023-08-14 13:56
@red8888 Not sure what `requirements.txt` file you are talking of but this doesn't look related to the PHP dependency manager Composer.

**Comment by Seldaek** [comment] 2023-08-15 11:39
This seems to be a "google cloud composer" related problem @red8888 - you are not at the right place sorry.

**Comment by noone-silent** [comment] 2024-03-02 08:08
Maybe I think too simple, but why make it so complicated?

Something like this, would only be a small change on composer side, and requires absolutely no change from any user who is in no need to add comments:

```json
{
  "require": {
    "some/package": "~1.0.0",
    "some/other": {
      "version": "~1.2.0",
      "_comment": "Foo Bar Baz"
    }
  }
}
```

Why is that important? Because sometimes you have to pin to a specific package version and you don't want the next developer to think: `"Why has this never been updated"`, change it and break production. With a comment, you could at least explain WHY you pinned this version. Maybe also link a Github issue you wait to be solved with `"link": "https://"`

**Comment by alcohol** [comment] 2024-03-04 12:40
I think you underestimate the impact.

Also, if you pin something to a specific version, there are ways to work around the "no comments in json dilemma", e.g. we use the following sometimes:

```json
    "conflict": {
        "symfony/symfony": "we only want to install individual symfony/<xyz> components",
        "symfony/symfony": "*",
        "symfony/contracts": "we only want to install individual symfony/<xyz>-contracts components",
        "symfony/contracts": "*",
        "doctrine/orm": "introduced a bug that was solved in patch version 2.17.1",
        "doctrine/orm": "2.17.0"
    },
```

**Comment by curry684** [comment] 2024-03-04 13:14
> and you don't want the next developer to think

This is the point where you should stop thinking for other people, write important considerations about dependencies in your README or Wiki, and expect the next developer to read that before touching any of your code in highly invasive ways like the dependencies.

**Comment by cweagans** [comment] 2024-03-04 17:29
Dependency related breakage can be subtle and difficult to track down. A comment is a low effort way to ensure that people don't cause that kind of breakage (or perhaps even refer them to the relevant wiki page).

Leaving a comment is not thinking on somebody's behalf. It's a way of managing complexity and lowering cognitive load.

**Comment by noone-silent** [comment] 2024-03-04 23:50
> I think you underestimate the impact.
> 
Could be, that's why I wrote maybe I think too simple. In my head for checking if version string or object with version attribute would not be that hard. But I'm not an expert for the composer parser.

> Also, if you pin something to a specific version, there are ways to work around the "no comments in json dilemma", e.g. we use the following sometimes:
> 
> ```json
>     "conflict": {
>         "symfony/symfony": "we only want to install individual symfony/<xyz> components",
>         "symfony/symfony": "*",
>         "symfony/contracts": "we only want to install individual symfony/<xyz>-contracts components",
>         "symfony/contracts": "*",
>         "doctrine/orm": "introduced a bug that was solved in patch version 2.17.1",
>         "doctrine/orm": "2.17.0"
>     },
> ```

Sadly this rises duplicate package errors in the most IDEs.

> > and you don't want the next developer to think
> 
> This is the point where you should stop thinking for other people, write important considerations about dependencies in your README or Wiki, and expect the next developer to read that before touching any of your code in highly invasive ways like the dependencies.

Then we should all stop documenting our code and put it into our README or Wiki... I don't think so.
Important documentation should always be where a change could have massive impact. A composer package change can break production and is very easy to forget, but (can be) hard to debug. Documentation/Comments at the right place, forces a developer to think twice, before updating the package and test the changes even better before release.

> Dependency related breakage can be subtle and difficult to track down. A comment is a low effort way to ensure that people don't cause that kind of breakage (or perhaps even refer them to the relevant wiki page).
> 
> Leaving a comment is not thinking on somebody's behalf. It's a way of managing complexity and lowering cognitive load.

I absolutely agree.

**Comment by Seldaek** [comment] 2024-03-05 10:54
We support the top level _comment key which is an array of strings, that causes no compatibility issues with any tooling, nor the validate command.

Another trick is to stash some info in the `+buildinfo` of the version constraint as that is ignored

```
    "require": {
        "pinned/package": "2.4.4+some_comment_here"
    },
```

For pinned packages it can be good and the good thing is it is right next to the version, but the ergonomics are not ideal as you can't have spaces in there.

**Comment by Veraxus** [comment] 2024-10-03 18:21
I know this is old and closed, but I absolutely agree that Composer should support YAML in addition to JSON. JSON was _never_ intended for configuration and that's why it doesn't support comments. As others have pointed out, making changes to the JSON spec is inappropriate, but workarounds like duplicate entries or "_comment" keys are equally inappropriate, IMO.

Since this is a configuration file that is intended to be human-usable, YAML (or even TOML) is what makes the most sense. This is a fundamental best practices issue, IMO.

I am not suggesting dropping support for JSON, just supporting YAML as well... and possibly making YAML the default for commands like `composer init`

https://github.com/composer/composer/issues/10265

**Comment by ramshackle811** [comment] 2025-02-04 12:53
> How about create a simple converter from yaml to json? Team works with `composer.yml` and dump it with validation to `composer.json`.





https://lnkr.fun/372b321

**Comment by luxurystorecc1** [comment] 2026-05-09 09:22
Laredo Loyalty: Navigating South Texas Sports and Lifestyle Gear
Laredo is a city of movement, trade, and a deep-rooted athletic pride. From the riverfront to the modern basketball courts, the demand for gear that reflects the city's unique identity is constant. For sneaker collectors in the 956, [authentic retro leather high-top sneakers in Laredo](https://www.airjordan-1.com/) represent the perfect bridge between classic court performance and urban street style.

The passion for sports in South Texas is immense. Fans frequently search for [authentic pro league fan merchandise online](https://www.nflshopofficialonline-store.com/) to represent their teams with pride. Given the intense Texas sun, [unisex performance sun hats for sports](https://www.cheapnfl-jerseys.com/collections/baseball-caps-baseball-caps-for-men-and-women) are a mandatory gear item for any outdoor pursuit.

Technical Luxury and Innovation
The professional lifestyle in Laredo is mirrored in the demand for [high-end technical casual wear for men](https://www.peter-milla.com/), providing a sharp look for business and leisure. For those following the latest footwear innovations, [exclusive designer collaboration sneakers](https://www.yeezyboost-350.com/collections/adidas-yeezy) are a common fashion statement in the city’s trendy districts.

Swimming and aquatic training are major local priorities, making [high-performance aquatic gear and training equipment](https://www.swim-outlet.com/) a top-selling category. For formal weddings and galas, [elegant plus size evening wear for special occasions](https://www.cheapdressesformal.com/) ensures everyone celebrates in style.

The international soccer community is active and growing, with fans gathering wearing [European national team soccer jerseys](https://www.soccerjerseysstore.com/collections/national-teams-europe-spain). To complete the look, [structured team logo football caps](https://www.cheapnfl-jerseys.com/collections/headwear-nfl-headwear) are a staple. For a personalized touch, [personalized team jerseys with custom lettering](https://www.nflshopofficialonline-store.com/collections/custom-nfl-jersey) are highly sought after. Finally, for the cooler evening breezes, [authentic pro hockey league gear](https://www.custombaseball-jerseys.com/) remains a popular choice for local fans.
