### ISSUE TITLE
Composer chokes when `path` type repositories are converted to vcs repos

### ISSUE THREAD

**Issue by kael-shipman** [composer/composer#6708] opened 2017-09-26 22:49 UTC
### My initial `composer.json`:

```json
{
    "require": {
        "me/my-lib": "~1.0"
    },
    "repositories": [
        {
            "type": "path",
            "url": "../me/my-lib"
        }
    ]
}
```

### My `composer.json` after breaking `me/my-lib` out into a separate repo:

```json
{
    "require": {
        "me/my-lib": "~1.0"
    },
    "repositories": [
        {
            "type": "git",
            "url": "https://github.com/me/my-lib.git"
        }
    ]
}
```

### Output of `composer diagnose`:

```
(Todo)
```

### When I run this command:

```
composer update
```

### I get the following output:

```
  [RuntimeException]                                                                         
  /path/to/me/my-lib does not exist and could not be created. 
```

### And I expected this to happen:

(successful update)

### More details

This happens because composer creates a symlink for path repositories and expects them to be directories, but when the source directory is removed and the dependency is replaced with a git repo, the symlinks become dangling and composer chokes on it. We probably just need to do a check for whether the package under the `vendor` folder is a directory or a symlink and then just delete it if it's a dangling symlink.

**Comment by alcohol** [comment] 2017-09-27 22:38
Most user-generated errors like these can be fixed by simply telling the user to `rm -rf vendor` and running `composer install` again.

**Comment by kael-shipman** [comment] 2017-09-28 03:04
Hm... This is a bug that's presumably fairly easy to solve. It seems like telling the user to just fix it him/herself by using the comcast "reboot" trick is a sure-fire way to create less than ideal software.

Would you consider re-opening the issue and just assigning it to me? It won't cost you anything....

**Comment by alcohol** [comment] 2017-09-28 08:57
The problem is that we then have to come up with lots of "what if the user did ..." checks in our code, which makes things more complicated to maintain. 

This is definitely going to run into conflicting scenarios at some point in the future. 

Considering the issue described almost never occurs, it really is not worth the hassle.

**Comment by kael-shipman** [comment] 2017-09-28 14:38
With all due respect, this is not a "what if the user did this"
scenario, nor would it require "lots of checks".

Composer allows you to use "path" type repositories. According to any
reasonable specification, a package installed via a "path" type repo
should act the same way that a package installed via a regular repo
acts, and you don't have to blow your vendor folder away every time you
change the location of a repo (nor should you). If you decide the best
solution is to blow your vendor folder away (something I vehemently
disagree with because I often develop libraries within my vendor folder
for lack of a better way to do it), then you should have Composer do it
transparently so the user doesn't have to interact with what is
obviously an unresolved code bug.

I insist, however: The answer to a bug is not "let's let it keep existing".

**Comment by alcohol** [comment] 2017-09-28 16:03
It is honestly not a bug. Switching the repository type of a package almost never happens. If it happens frequently in your case, you are doing something wrong.

Normally, if you need to switch the type, simply uninstall the package, redefine or modify the repository configuration, and install the new package.

You are, of course, entitled to your own opinion.

**Comment by Seldaek** [comment] 2017-10-01 16:52
Sounds like a bug to me that if you remove the symlink target Composer doesn't detect the package as being gone. We already do this check in case you delete something in vendor/*, so deleting the symlink target should probably mark the package as uninstalled all the same (and probably clean up the symlink too).

**Comment by alcohol** [comment] 2017-10-02 06:27
I disagree. If the user manually removed the target of the symlink, then he should have uninstalled the package first. The symlink could be dangling because it's on a volume mount that is not mounted currently. There are other edge cases as well. We should not consider the package uninstalled or removed until the user explicitly uninstalls or removes it.

**Comment by Seldaek** [comment] 2017-10-02 11:57
Ok you make a good point about volume mounts and co, I guess symlinks can indeed be temporarily broken, the question is whether running composer updates while a symlink is in a broken state can result in anything good, or whether we should error out or something if we detect that. I don't think the current way of ignoring it is ideal.

**Comment by jpmschuler** [comment] 2018-08-09 14:41
I don't get the point in the argumentation here. The state described is "current install of the package is broken" and "repository offers working, newer, compatible version". The only solution would be: delete broken and reinstall.

The contrary arguments of alcohol are about "well we can't decide how broken it really is". Actually, "not available" is plain broken IMHO and the valid scenario alcohol came up with, doesn't include that composer up would be able to get a better version. I get that a composer up shouldn't remove packages which aren't fixable, but just report an error. But for the case it is fixable, it should fix. So it is not about "every symlink should be deleted", but just about "if a symlink path repo is currently used and composer finds a better™ version, replace the symlink with the newer version (which might then be plain files)". 

I get that this is not high on the agenda, but if one uses this quite specific case of the OP at hand, instead of generally talking about symlinks: are there really any edge cases here? The case with the mount point is exactly when I'd like a `composer up` to fix the package in the scenario.

If there are still edge cases, would it be possible to mark this as WONT FIX to have a definitive answer; or if not perhaps just say "PULL REQUESTS ARE WELCOME".

**Comment by alcohol** [comment] 2018-08-09 19:47
> "PULL REQUESTS ARE WELCOME".

**Comment by kael-shipman** [comment] 2018-08-11 00:36
Haha, I get that. I've just been in too many situations where I spent a weekend fixing something only to discover that the maintainers didn't agree with my solution. I'm trying avoid that this time by having the conversation first to see if we can come up with a solution people are happy with.

So far it looks like we're converging on the idea that a dangling symlink should be treated the same as the _absence_ of a package, i.e., given the file `vendor/me/my-pkg`, if `my-pkg` is a dangling symlink, then it should be silently removed and composer should view `my-pkg` as not being installed (and subsequently locate and install it).

The one possible exception appears to be that the original package may have been on a removable medium that was temporarily removed. In this case, though, I would say if that removable medium is still listed as a repository, we should throw some sort of a `NonexistentPathRepositoryException` if the medium is not present. If it's not, then we can safely assume that the package really is gone and there are no inconsistencies.

### PR Proposal

I propose the following changes:

1. Whenever composer checks for the presence of a given package, it should check to see if the directory it's looking at is symlink, and if that symlink is broken, it should remove it and consider the package "not installed".
2. Whenever composer aggregates repositories, it should throw an exception when a listed repository is unreachable, either because it's a path-type repository and no longer exists, or because it's a remote HTTP repository for which there is no connection.

If this proposal is approved (or modified and approved), I'll dig in and submit a PR for it.

**Comment by Seldaek** [comment] 2018-08-11 07:59
That sounds good to me yes. 1 should be relatively easy and would mostly fix the problem already. 2 for path repository sounds easy if it isn't the case yet, the network ones I would say rather not change the way they behave.

**Comment by jpmschuler** [comment] 2018-08-12 07:33
+1 for PR1

I think PR2 is a different topic actually but would suggest that all Repo types should react the same as much as possible. 

Additionally, with a path repo of `./localpkgs/*` (all folders below this custom folder) this check is basically impossible, because it might be that 3 subfolders like `./localpkgs/mypackage17`vanished, still that path would resolve. So this would create inconsistent behaviour, even for different kind of path repos, as the non-star-path-repos would throw the exception and the star-path-repos would die silently.

Perhaps instead of throwing an exception by default, a configuration option "required" might be interesting, as throwing an exception as default would be a breaking change. No matter how the default is, an option to stick to the old behaviour might be helpful.

**Closed** 2022-06-06 14:50 UTC
Labels: Bug
