### ISSUE TITLE
HTTP Basic Auth collides with Gitlab OAuth Token authentication

### ISSUE THREAD

**Issue by shochdoerfer** [composer/composer#4936] opened 2016-02-20 11:46 UTC
This might not be a problem a lot of people will hit but should be fixed to avoid confusion. Background: We recently migrated from a pure git+https setup to Gitlab. During that migration I wanted to let Satis use the GitlabDriver to improve the overall performance.

In my auth.json file I had the old HTTP Basic Auth credentials for the gitlab host (because we did not change the hostname during the migration) which after the migration did not work any more. on the first run Composer was able to ask me for the Gitlab OAuth Token and add it to the global auth.json file without a problem. But when running Composer a second time the Gitlab OAuth Token was not recognized and Composer asked me again for the Gitlab credentials.

When removing the HTTP Basic Auth credentials Composer is running fine. I was not yet able to debug the issue in the code, so I am not sure if this is a general problem or *just* an issue with the GitlabDriver.

**Comment by shochdoerfer** [comment] 2016-02-20 11:47
The issue might be related to #3765.

**Comment by Seldaek** [comment] 2016-02-20 16:09
This should be fixed in BaseIO::loadConfiguration it probably needs to check if this->hasAuthentication and before doing setAuthentication and if so warn that it's overwriting something.

**Comment by shochdoerfer** [comment] 2016-02-20 17:35
@Seldaek Currently we are not able to "prioritize" which auth method wins, right? Would that make sense? Somehow in this case the HTTP Basic Auth gets triggered (need to investigate where) even though the Gitlab OAuth Token would be the one that should be used. Or am I thinking way too complicated?

**Comment by Seldaek** [comment] 2016-02-20 17:57
Well the problem is they are all stored in the same place, so if you have both defined one will overwrite the other when loaded in the IO instance.

IMO solution is just to warn users so they notice it and remove the one that's wrong. I don't really think there is a case for using different auth methods on the same domain?

**Comment by shochdoerfer** [comment] 2016-02-21 09:36
True.

**Closed** 2016-02-29 13:57 UTC
Labels: Bug, Easy Pick

**Comment by shochdoerfer** [comment] 2016-02-29 13:59
@Seldaek thanks for taking care. Could not yet find the time to fix it myself.

**Comment by Seldaek** [comment] 2016-02-29 13:59
No problem but it was @e-moe not me ;)
