### ISSUE TITLE
Composer downloading outdated package

### ISSUE THREAD

**Issue by mozgbrasil** [composer/composer#5259] opened 2016-04-27 22:56 UTC
Good evening

Hello my friends

---

## 1)

With the following composer.json:

```
{
   "minimum-stability": "dev",
    "license": [
        "proprietary"
    ],
   "require": {
      "mozgbrasil/framework-php56": ">=1.0.0-rc.1"
   },
   "extra": {
      "magento-root-dir": "./"
   }
}
```

When I run this command:

```
composer install -vvv

```

I get this output:

```

Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mozgbrasil/framework-php56 dev-master requires ext-zend-guard-loader * -> the requested PHP extension zend-guard-loader is missing from your system.
    - mozgbrasil/framework-php56 1.0.0-rc.2 requires ext-zend-guard-loader * -> the requested PHP extension zend-guard-loader is missing from your system.
    - mozgbrasil/framework-php56 1.0.0-rc.1 requires ext-zend-guard-loader * -> the requested PHP extension zend-guard-loader is missing from your system.
    - Installation request for mozgbrasil/framework-php56 >=1.0.0-rc.1 -> satisfiable by mozgbrasil/framework-php56[1.0.0-rc.1, 1.0.0-rc.2, dev-master].


```

And I expected this to happen:

```
Ok, this is a result that I hope

```

https://packagist.org/packages/mozgbrasil/framework-php56

---

## 2)

With the following composer.json:

```
{
   "minimum-stability": "dev",
    "license": [
        "proprietary"
    ],
   "require": {
      "mozgbrasil/test": "*"
   },
   "extra": {
      "magento-root-dir": "./"
   }
}
```

https://packagist.org/packages/mozgbrasil/test

We have seen that for this repository has

    requires
        "mozgbrasil/framework-php56": "*"

or if I change to

    requires
        "mozgbrasil/framework-php56": ">=1.0.0-rc.1"

When I run this command:

```
composer install -vvv

```

I get this output:

```
mozgbrasil/framework-php56 (0.1.0-beta9)

```

And I expected this to happen:

```

Dependency resolution completed in 0.001 seconds
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - mozgbrasil/framework-php56 dev-master requires ext-zend-guard-loader * -> the requested PHP extension zend-guard-loader is missing from your system.
    - mozgbrasil/framework-php56 1.0.0-rc.2 requires ext-zend-guard-loader * -> the requested PHP extension zend-guard-loader is missing from your system.
    - mozgbrasil/framework-php56 1.0.0-rc.1 requires ext-zend-guard-loader * -> the requested PHP extension zend-guard-loader is missing from your system.
    - Installation request for mozgbrasil/framework-php56 >=1.0.0-rc.1 -> satisfiable by mozgbrasil/framework-php56[1.0.0-rc.1, 1.0.0-rc.2, dev-master].


```

https://packagist.org/packages/mozgbrasil/framework-php56

---

**Comment by stof** [comment] 2016-04-28 09:53
composer does it job properly, as it finds the latest version compatible with your setup when resolving dependencies, which is exactly its job.

If you want to understand why a specific version cannot be installed, composer has a command for that:
```bash
composer why-not mozgbrasil/framework-php56 1.0.0-rc.1
```

**Comment by mozgbrasil** [comment] 2016-04-28 19:56
Hello good afternoon

I ran the command and was shown the following return, I see no explanation of the reason for not installing the latest version of the module

-

There is no installed package depending on "mozgbrasil/framework-php56" in versions not matching 1.0.0-rc.1

**Comment by Seldaek** [comment] 2016-04-28 20:26
0.1-beta9  is the last version that did not have all the ext-something requires, so it's probably not installing 1.0 because you are missing one of these extensions. I don't think `why-not` checks for this yet. If you require the package in the version you want then run update it should tell you exactly why.

**Comment by mozgbrasil** [comment] 2016-04-28 20:52
Hello Good afternoon my friends

I edited my first interaction that I believe it should now be easier to understand

We see that in the case of parent package call the child package is not being triggered the error alert in this case

But if I come direct call the child package, we see that is triggered the error of lack of server extension

I believe that the composer must analyze the requirements of both hierarchy, or should I refer in both packages the same requirements?

**Comment by Seldaek** [comment] 2016-04-28 21:08
In all cases it tells you that the zend-guard requirement is missing. I am not entirely sure what the problem is that you have.

I fixed the `why-not` command to also show required platform packages if they are missing, so now I see:

```
$ composer why-not mozgbrasil/framework-php56:1.0.0-rc.1
mozgbrasil/framework-php56  1.0.0-rc.1  requires  ext-zend-guard-loader (* but it is missing)
mozgbrasil/framework-php56  1.0.0-rc.1  requires  ext-soap (* but it is missing)
mozgbrasil/framework-php56  1.0.0-rc.1  requires  ext-gd (* but it is missing)
mozgbrasil/framework-php56  1.0.0-rc.1  requires  ext-xsl (* but it is missing)
```

**Closed by Seldaek** 2016-04-28 21:08 UTC
