### ISSUE TITLE
composer.phar was changed after the publication

### ISSUE THREAD

**Issue by linux0uid** [composer/composer#4325] opened 2015-08-03 20:36 UTC
I was downloaded the composer.phar file from getcomposer.org a 15.04.2015 using the link https://getcomposer.org/download/1.0.0-alpha10/composer.phar
And now it's not the same file. Checksums doesn't match.

If I clearly understand the version file should NOT be changed after the publication.

15.04.2015 composer-1.0.0_alpha10.phar
SHA256 ef292a13b696ea2e6b427138f432f7db40668ece4b0970785c28aa59eb11b1c3
SHA512 ecc5fe4b56fd731161c25e463f941c1ff318f16e54530bdf26b416a73a6043cb1f1414fdd44b1d611a10d18f60d41962fa91e7f198e86060084eab54443b1ce5

03.08.2015 composer-1.0.0_alpha10.phar
SHA256 9f2c7d0364bc743bcde9cfe1fe84749e5ac38c46d47cf42966ce499135fd4628
SHA512 a3cd8f017dd102eecab2ee68d24dbdadd3c4442495ddbb957c623b266b999edb3c174713df5424f2db3e8d33ebd86364420955fcdf50a4de79c0d53f9a36eee0

**Comment by alcohol** [comment] 2015-08-03 21:39
Well, as you can see here, the file has not changed in the past 3 months.
https://github.com/composer/getcomposer.org/tree/master/web/download/1.0.0-alpha10

Could it be possible you modified your composer.phar yourself?

**Comment by cs278** [comment] 2015-08-03 22:56
https://github.com/composer/getcomposer.org/commit/4116ca58e397bbcb36461cae246b157fefaafbed But alpha 9 and 10 were committed at the same time, suggests to me they originally weren't in git.

**Comment by linux0uid** [comment] 2015-08-04 04:33
I couldn't modified my composer.phar, because It wasn't download manually, I was wrote ebuild for gentoo. And original file /usr/portage/distfiles/composer-1.0.0_alpha10.phar was modified at 15.04.2015. Checksum was made a few days later.
And I was installed the composer in my system from this ebuild https://github.com/linux0uid/gentoo-overlay/tree/master/dev-php/composer
And it worked, and works now.

Maybe this file was modified after releasing, maybe for the next day. But if you published the release why you modify it? Make a next release.

**Comment by alcohol** [comment] 2015-08-04 07:12
I am sorry but unless you can give me any actual proof of your claims, I cannot help you.

**Comment by stof** [comment] 2015-08-04 08:20
@linux0uid Before May 1, building the phar was not a reproducible process because there were some random hashes generated at build time (as well as a few other changing parts).

and given that the alpha9 and alpha10 releases were originally not added in the git repository of the website (this was forgotten when releasing them), each deployment until April 28 was recreating them, and with a different hash because of the reproducible build issue

**Comment by Seldaek** [comment] 2015-08-09 14:11
7

**Comment by Seldaek** [comment] 2015-08-09 14:12
Yup, this is unfortunate but the good news is that it was fixed and should not happen again in the future. The contents of the phar didn't really change though it was just metadata in the phar that was different every time we built it.

**Closed by Seldaek** 2015-08-09 14:12 UTC
Labels: Support
