### ISSUE TITLE
certificate verify

### ISSUE THREAD

**Issue by bpgh** [composer/composer#5439] opened 2016-06-15 13:43 UTC
When I run this command:
```
$ composer install
```

I get this output:
```
Loading composer repositories with package information
                                                                                                                                  [Composer\Downloader\TransportException]                                                                                           
  The "https://packagist.org/packages.json" file could not be downloaded: SSL operation failed with code 1. OpenSSL Error messages:  
  error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed                                                  
  failed to open stream: Cannot connect to HTTPS server through proxy                                                                
```                                                                                                                                 

I behind security Gateway (not Proxy! -> security Gateway it works as man in the middle)  it is necessary disable the certificate validation on the Exhibitor's name.

disable-tls  
git config http.sslVerify false
export GIT_SSL_NO_VERIFY=true
not working

Thank you for the quick reply in the first.

**Comment by alcohol** [comment] 2016-06-15 14:10
Duplicate of #5436, please continue the discussion there.

**Closed by alcohol** 2016-06-15 14:10 UTC
