### ISSUE TITLE
`composer show --outdated` is recommending old version of specific package

### ISSUE THREAD

**Issue by dsutphin** [composer/composer#9688] opened 2021-02-10 15:28 UTC
`composer show --outdated` is showing an update to v7.0.2 from v11.1.1 for [vladimir-yuldashev/laravel-queue-rabbitmq](https://packagist.org/packages/vladimir-yuldashev/laravel-queue-rabbitmq).
This is unexpected as the installed version is newer than the version displayed.
```
$ docker run --rm -it composer ash
/app # composer require vladimir-yuldashev/laravel-queue-rabbitmq --ignore-platform-reqs
...
/app # composer show -vvv --outdated --direct
Reading ./composer.json (/app/composer.json)
Loading config file ./composer.json (/app/composer.json)
Checked CA file /etc/ssl/certs/ca-certificates.crt: valid
Executing command (/app): git branch -a --no-color --no-abbrev -v
Executing command (/app): git describe --exact-match --tags
Executing command (CWD): git --version
Executing command (/app): git log --pretty="%H" -n1 HEAD --no-show-signature
Executing command (/app): hg branch
Executing command (/app): fossil branch list
Executing command (/app): fossil tag list
Executing command (/app): svn info --xml
Failed to initialize global composer: Composer could not find the config file: /tmp/composer.json

Reading /app/vendor/composer/installed.json
Running 2.0.9 (2021-01-27 16:09:27) with PHP 8.0.1 on Linux / 5.4.0-65-generic
Downloading https://repo.packagist.org/packages.json
[200] https://repo.packagist.org/packages.json
Writing /tmp/cache/repo/https---repo.packagist.org/packages.json into cache
Reading /tmp/cache/repo/https---repo.packagist.org/provider-vladimir-yuldashev~laravel-queue-rabbitmq.json from cache
Downloading https://repo.packagist.org/p2/vladimir-yuldashev/laravel-queue-rabbitmq.json if modified
[304] https://repo.packagist.org/p2/vladimir-yuldashev/laravel-queue-rabbitmq.json
vladimir-yuldashev/laravel-queue-rabbitmq v11.1.1 v7.0.2 RabbitMQ driver for Laravel Queue. Supports Laravel Horizon.
```

**Comment by Seldaek** [comment] 2021-02-10 16:39
This happens because you're running on PHP 8 and `vladimir-yuldashev/laravel-queue-rabbitmq` versions newer than 7.0.2 do not support it as they require php using `^7.x`. What is very weird though is that the initial require works at all. I don't understand that and will need to investigate more tomorrow.

If you run a `composer update` you will indeed see this:

```
  Problem 1
    - vladimir-yuldashev/laravel-queue-rabbitmq[v11.1.0, ..., v11.1.1] require php ^7.3 -> your php version (8.0.0) does not satisfy that requirement.
    - Root composer.json requires vladimir-yuldashev/laravel-queue-rabbitmq ^11.1 -> satisfiable by vladimir-yuldashev/laravel-queue-rabbitmq[v11.1.0, v11.1.1].
```

**Comment by stof** [comment] 2021-02-11 09:43
@Seldaek the initial require is done with `--ignore-platform-reqs` in this example. That's why it worked.

**Comment by Seldaek** [comment] 2021-02-11 09:46
Oh I missed that was kinda in a rush :) But yes that does explain it.. Then closing as duplicate of https://github.com/composer/composer/issues/9631

**Closed by Seldaek** 2021-02-11 09:46 UTC
