### ISSUE TITLE
symfony3 conflict

### ISSUE THREAD

**Issue by mmucklo** [composer/composer#4774] opened 2016-01-15 18:55 UTC
When I import this into a project using symfony 3 components, I get an exception:

```
Strict standards: Declaration of Composer\Console\Application::renderException() should be compatible with Symfony\Component\Console\Application::renderException(Exception $e, Symfony\Component\Console\Output\OutputInterface $output) in /Users/mmucklo/src/license-grab-lib/vendor/composer/composer/src/Composer/Console/Application.php on line 38
```

**Comment by xabbuh** [comment] 2016-01-15 19:02
What is "this" that you import in a project? Please provide some more detailed information about what you are trying to do.

**Comment by cs278** [comment] 2016-01-15 19:59
Reproduce:

```
composer require composer/composer:@dev
vendor/bin/composer about
```

```
[tmpdir]:/tmp/chris/tmp.QXSLCiPRBv $ composer require composer/composer:@dev
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Installing justinrainbow/json-schema (v1.6.0)
    Loading from cache

  - Installing seld/jsonlint (1.4.0)
    Loading from cache

  - Installing seld/cli-prompt (1.0.1)
    Downloading: 100%         

  - Installing seld/phar-utils (1.0.1)
    Loading from cache

  - Installing symfony/filesystem (v3.0.1)
    Loading from cache

  - Installing symfony/process (v3.0.1)
    Loading from cache

  - Installing symfony/finder (v3.0.1)
    Loading from cache

  - Installing symfony/polyfill-mbstring (v1.0.1)
    Loading from cache

  - Installing symfony/console (v3.0.1)
    Loading from cache

  - Installing composer/semver (1.2.0)
    Loading from cache

  - Installing composer/spdx-licenses (1.1.2)
    Loading from cache

  - Installing composer/composer (dev-master 03299ff)
    Cloning 03299ff075236be27be356498d6c64def973fe41

Writing lock file
Generating autoload files

[tmpdir]:/tmp/chris/tmp.QXSLCiPRBv $ vendor/bin/composer about
PHP Strict Standards:  Declaration of Composer\Console\Application::renderException() should be compatible with Symfony\Component\Console\Application::renderException(Exception $e, Symfony\Component\Console\Output\OutputInterface $output) in /tmp/chris/tmp.QXSLCiPRBv/vendor/composer/composer/src/Composer/Console/Application.php on line 38

Strict Standards: Declaration of Composer\Console\Application::renderException() should be compatible with Symfony\Component\Console\Application::renderException(Exception $e, Symfony\Component\Console\Output\OutputInterface $output) in /tmp/chris/tmp.QXSLCiPRBv/vendor/composer/composer/src/Composer/Console/Application.php on line 38
Composer - Package Management for PHP
Composer is a dependency manager tracking local dependencies of your projects and libraries.
See https://getcomposer.org/ for more information.
```

**Comment by cs278** [comment] 2016-01-15 20:06
I don't think there is much that can be done other than live with it, because changing the signature to match then breaks Symfony < 3.

**Comment by Seldaek** [comment] 2016-01-16 11:43
Fixed by removing that method, should work fine now with sf3

**Closed by Seldaek** 2016-01-16 11:43 UTC
