### ISSUE TITLE
Symlink local development libraries 

### ISSUE THREAD

**Issue by Petah** [composer/composer#1299] opened 2012-11-07 22:36 UTC
Is there any way to simply symlink a vendor library from another directory rather than keeping a local copy for each project?

This is primarily for speed of development. 

We have many in house modules (20-30) and are running a Satis server. 

When we require a change to a module for a project, you must follow this process at present.

 - Make change in module
 - Commit and push change to Git server
 - Update Satis server (currently on a 5 min cron schedule) 
 - Update the project using `composer update --dev`

The turn around on this is quite lengthy, and doing it multiple time for multiple modules/projects is impractical. 

If we could just symlink each of our in house libraries into the vendor directory, turn around time would be nil.

**Comment by Jeremlicious** [comment] 2015-01-21 16:23
+1

**Comment by gilbitron** [comment] 2015-03-05 12:03
+1

**Comment by piwi** [comment] 2015-03-15 10:50
Hello all,
I made a plugin for that (not so amazing but it works fine) : <https://github.com/piwi/composer-symlinker>.
If it helps ...

**Comment by jreinke** [comment] 2015-04-02 10:30
Hi there,

@piwi solution did not work for me because my local packages are not under VCS.

So I had to modify Composer itself to allow local packages installation, modification is quite simple https://github.com/jreinke/composer/commit/92ad4e4c631d5c611634aa64b4f44ce66cf26491. You have to modify your `composer.phar` like that:
```shell
$ git clone https://github.com/jreinke/composer.git && cd composer/
$ curl -sS https://getcomposer.org/installer | php && php composer.phar install
$ ./bin/compile
```
Now you can use custom `composer.phar` for local packages installation like below:
```json
"require": {
     "<vendor>/<local-package>": "*"
},
"repositories": [
    {
        "type": "folder",
        "url": "../path/to/package/"
    }
]
```
Local packages are installed with symlinks so that any modification made is automatically applied to projects depending on them.

**Comment by Vittel** [comment] 2015-04-03 08:28
Hey,

just a complain: having symlinks in anything related to source control is not a good idea. Why dont you just read the packages from where they are and not link them in?

**Comment by jreinke** [comment] 2015-04-03 08:40
I agree, but symlinks are also a good way for developers productivity. Hard copying packages would involve frequent `composer update` commands on all depending packages.
Maybe a good option would be having the choice between hard copy and symlink...

**Comment by Vittel** [comment] 2015-04-03 16:56
No, i mean do not copy or link them at all. just take the position of the sourcecode as is, and do include the files in their original position in the autoloader

**Comment by Divi** [comment] 2015-04-06 16:50
If someone can't wait for this feature, I made a plugin to automatically symlink only dev packages : https://github.com/Letudiant/composer-shared-package-plugin

Hope it can help.

Btw :+1: for the native implementation.

**Comment by jreinke** [comment] 2015-04-06 19:41
Nice alternative @Divi, thanks for sharing.

**Comment by iwiznia** [comment] 2015-04-08 20:56
@jreinke that would be a great addition. Will try it and let you know if it works. Why not make that a pull request? Lots of people are asking for something like that.

**Comment by gossi** [comment] 2015-04-09 15:28
I wrote a blog post about my discovery with local composer development. I also summarized some of the requirements and ideas I came across while dealing with local development.

Please take a look: http://gos.si/blog/composer-development-with-local-dependencies

**Comment by Divi** [comment] 2015-04-09 15:42
Nice post @gossi, pros & cons are nicely resumed.  
Just one comment about the first pro for symlink workaround (fetching each repository `composer.json` file) : you can handle it by installing Satis, see : https://github.com/Letudiant/composer-shared-package-plugin/blob/master/docs/how-to-use/work-with-satis.md

You can even disable packagist to use only your Satis host.

**Comment by ahuszko** [comment] 2015-11-27 07:10
This may help you to improve local package development: http://ahuszko.ghost.io/compact/

**Comment by staabm** [comment] 2015-11-27 08:08
@Seldaek I think we can close this one, because we have `PathRepository` now?
https://getcomposer.org/doc/05-repositories.md#path

**Comment by Seldaek** [comment] 2015-11-27 09:16
Closing as duplicate of #601 anyway, but yes path repo helps.

**Closed by Seldaek** 2015-11-27 09:16 UTC
Labels: Feature
