### ISSUE TITLE
Getting a lot of "file could not be downloaded" last night and this morning

### ISSUE THREAD

**Issue by phil-davis** [composer/composer#9112] opened 2020-08-10 05:10 UTC
e.g. https://drone.owncloud.com/owncloud/core/26287/41/5
```
  [Composer\Downloader\TransportException]                                                                                                                                      
  The "https://packagist.org/p/provider-2019-10%2432a026927646b99f9893365e837d3ee433d98aeea10876817629b88510db53c4.json" file could not be downloaded (HTTP/1.1 404 Not Found)
```

Is there currently some issue with packagist having inconsistent content somewhere???

**Comment by phil-davis** [comment] 2020-08-10 05:21
I restarted my CI and am getting more: https://drone.owncloud.com/owncloud/core/26288/10/6
````
  The "https://packagist.org/p/symfony/polyfill-php70%2404e8fe5bcfdf3fcf8d62ab881ed2f60b3a0c49632a95b40387d9c702ba7dbd07.json" file could not be downloaded (HTTP/1.1 404 Not Found)
```

About a dozen pipelines failed with similar packagist "not found" errors.

https://drone.owncloud.com/owncloud/core/26288/148/7
```
The "https://packagist.org/p/provider-2020-04%24ff87dee5698f6ea339e5a1ef20437417a599a28e97508aa1a9a6a4a58a6c34d7.json" file could not be downloaded (HTTP/1.1 404 Not Found)
```

I don't know where else to report these "packagist support" issues.

**Comment by phil-davis** [comment] 2020-08-10 09:06
I forgot about this issue https://github.com/composer/packagist/issues/940

It has a report just now that his problem is happening.

**Comment by Sidlegionair** [comment] 2020-08-10 09:15
@phil-davis Can confirm, this is still happening.

**Comment by Seldaek** [comment] 2020-08-10 10:55
Closing as duplicate of https://github.com/composer/packagist/issues/940 then

**Closed by Seldaek** 2020-08-10 10:55 UTC
