### ISSUE TITLE
package provide extension not used in resolve dependencies

### ISSUE THREAD

**Issue by gimler** [composer/composer#6177] opened 2017-02-17 14:20 UTC
Output of `composer diagnose`:

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Checking composer.json: WARNING
No license specified, it is recommended to do so. For closed-source software you may use "proprietary" as license.
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking HTTP proxy: OK
Checking HTTP proxy support for request_fulluri: OK
Checking HTTPS proxy support for request_fulluri: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

When I run this command:

```
composer require "alcaeus/mongo-php-adapter:^1.0" "doctrine/mongodb-odm:^1.1"   
```

I get the following output:

```
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/mongodb-odm 1.1.0 requires doctrine/mongodb ~1.3 -> satisfiable by doctrine/mongodb[1.3.0, 1.4.0].
    - doctrine/mongodb-odm 1.1.1 requires doctrine/mongodb ~1.3 -> satisfiable by doctrine/mongodb[1.3.0, 1.4.0].
    - doctrine/mongodb-odm 1.1.2 requires doctrine/mongodb ~1.3 -> satisfiable by doctrine/mongodb[1.3.0, 1.4.0].
    - doctrine/mongodb-odm 1.1.3 requires doctrine/mongodb ~1.3 -> satisfiable by doctrine/mongodb[1.3.0, 1.4.0].
    - doctrine/mongodb 1.4.0 requires ext-mongo ^1.5 -> the requested PHP extension mongo is missing from your system.
    - doctrine/mongodb 1.3.0 requires ext-mongo ^1.5 -> the requested PHP extension mongo is missing from your system.
    - Installation request for doctrine/mongodb-odm ^1.1 -> satisfiable by doctrine/mongodb-odm[1.1.0, 1.1.1, 1.1.2, 1.1.3].

  To enable extensions, verify that they are enabled in your .ini files:
    - /usr/local/etc/php/php.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-apcu.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gd.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-gettext.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-intl.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-libsodium.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-mongodb.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-msgpack.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-opcache.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-phalcon.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    - /usr/local/etc/php/conf.d/docker-php-ext-zip.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.

Installation failed, deleting ./composer.json.
```

But when i run the commands seperatly
```
composer require "alcaeus/mongo-php-adapter:^1.0"
composer require "doctrine/mongodb-odm:^1.1"
```

Then it works I get the following output:
```
root@7cb8f797caae:/composer-temp# composer require "alcaeus/mongo-php-adapter:^1.0"                            
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing mongodb/mongodb (1.0.5) Loading from cache
  - Installing alcaeus/mongo-php-adapter (1.0.9) Loading from cache
Writing lock file
Generating autoload files
root@7cb8f797caae:/composer-temp# composer require "doctrine/mongodb-odm:^1.1"                                 
Do not run Composer as root/super user! See https://getcomposer.org/root for details
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 13 installs, 0 updates, 0 removals
  - Installing doctrine/lexer (v1.0.1) Loading from cache
  - Installing doctrine/inflector (v1.1.0) Loading from cache
  - Installing doctrine/collections (v1.4.0) Loading from cache
  - Installing doctrine/cache (v1.6.1) Loading from cache
  - Installing doctrine/annotations (v1.3.1) Loading from cache
  - Installing doctrine/common (v2.7.2) Loading from cache
  - Installing doctrine/mongodb (1.4.0) Loading from cache
  - Installing doctrine/instantiator (1.0.5) Loading from cache
  - Installing psr/log (1.0.2) Loading from cache
  - Installing symfony/debug (v3.2.4) Loading from cache
  - Installing symfony/polyfill-mbstring (v1.3.0) Loading from cache
  - Installing symfony/console (v3.2.4) Loading from cache
  - Installing doctrine/mongodb-odm (1.1.3) Loading from cache
doctrine/mongodb suggests installing jmikola/geojson (Support GeoJSON geometry objects in 2dsphere queries)
symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/filesystem ()
symfony/console suggests installing symfony/process ()
doctrine/mongodb-odm suggests installing symfony/yaml (Enables the YAML metadata mapping driver)
Writing lock file
Generating autoload files
```

**Comment by stof** [comment] 2017-02-17 14:36
This is because Packagist does not create metadata files for ext packages provided by other packages, and so the packages coming from Packagist are not found when asking for packages providing an extension.
When the package is in the local repository or in a VCS repository, it will be found properly by the pool.

**Comment by Seldaek** [comment] 2017-03-07 15:49
Duplicate of #5030

**Closed by Seldaek** 2017-03-07 15:49 UTC
