### ISSUE TITLE
Consider silencing Git permission issues from VersionGuesser

### ISSUE THREAD

**Issue by proton-ab** [composer/composer#12192] opened 2024-11-09 21:04 UTC
https://github.com/composer/composer/pull/12178 introduced a change to be verbose and pass full error from Git to user whenever it fails, however this does not account for how often composer actually calls `git` even when completely unnecessary. Ever since v2.8.2, many commands (such as user-defined scripts) will print unnecessary message:

```
+ composer phpcs
The repository at "/drone/src" does not have the correct ownership and git refuses to use it:
fatal: detected dubious ownership in repository at '/drone/src'
To add an exception for this directory, call:

	git config --global --add safe.directory /drone/src

> phpcs -n --cache=.phpcs-cache
........................................................ 56 / 56 (100%)

Time: 963ms; Memory: 10MB
```

Please note - this is expected by me and I do not wish to add exception for this particular case nor I want composer to try to guess root project version when executing user-defined script.

I do not believe being this verbose is of any relevance here and provides nothing of value. I am fine with composer doing this for `install` or `update` commands (and I do handle exception there appropriately) though.

**Comment by Seldaek** [comment] 2024-11-15 13:17
So unfortunately suppressing the warning just in some places is pretty difficult given the root package is always loaded in the same way and that code has no notion of which command is running.. Maybe we could switch the version guesser warning to be only output in verbose output. That's kinda best I can do.

Why is it such a big deal to resolve the issue and configure git correctly tho?

**Comment by rfay** [comment] 2024-11-15 14:03
> Why is it such a big deal to resolve the issue and configure git correctly tho?

An example: Some [DDEV](https://github.com/dddev/ddev) users use a docker provider which bind-mounts the repository into the Docker container, leaving the bind mount owned by the root user. This isn't a great situation, but it's hard for the user to resolve it. 

The problem comes when a composer.json uses git. Normally the user is doing git operations with their repo on the host, but `ddev composer` runs composer inside the container, where the php version and composer version are predictable. Then, if composer uses git, the warnings come, which confuse the user.  For example, https://github.com/ddev/ddev/issues/4829#issuecomment-2450349802

**Comment by proton-ab** [comment] 2024-11-16 12:31
> Why is it such a big deal to resolve the issue and configure git correctly tho?

My issue is with CI where each step runs in ephemeral container only sharing working directory via bind mount. I would hate to have a step that explicitly adds working directory as trusted by Git just to silence dubious warning, especially when given step is not supposed to modify installed packages in any way. As I said, I already add trusted directory in installation step, however this is only place I am realistically willing to add it because I expect possible git checkouts happening there - anywhere else, I don't really want or need working directory to be touched (for all it cares it could be mounted `ro`)

> Then, if composer uses git, the warnings come, which confuse the user.

The warning is valid for `install` and `update` scope because composer might be required to perform git checkout in working directory depending on dependencies specified. Though, maybe the warning should instead be an error and be emitted only when composer actually has real need to do checkout?

**Comment by nickpoulos** [comment] 2024-11-19 06:38
`My issue is with CI where each step runs in ephemeral container only sharing working directory via bind mount.`

This ^. Now using composer within a docker container spits out these errors all the time, as it detects the internal folder name, which will never have the correct ownership it would seem? 

The only fix is to run the `git config --global --add safe.directory` command from within the container. Kinda annoying for local development, super annoying for CI/CD.  You end up having to do `git config --global --add safe.directory '*'`.

**Comment by Seldaek** [comment] 2024-11-19 08:28
And pardon my ignorance here but I only do CI with GH actions where I haven't seen these issues, so I wonder what is the cause? Is it because you run the containers/steps without the correct user? Or why isn't GH actions affected by this?

**Comment by proton-ab** [comment] 2024-11-19 10:15
> And pardon my ignorance here but I only do CI with GH actions where I haven't seen these issues

Most likely GH actions are pre-configured to set working directory as safe (which isn't surprising given that they fully control their very fat images). My CI setup involves running docker-in-docker containers that I don't control (usually stuff like official images from PHP) and can't guarantee that such steps were taken unless I add it in every step.

**Comment by stof** [comment] 2024-11-19 11:42
@proton-ab `safe.directory` is not only needed when you want to do a `checkout`. *reading* the state of the git repository is also affected (which is why the VersionGuesser fails at guessing the version if the directory is considered unsafe in git)

**Comment by proton-ab** [comment] 2024-11-20 04:50
> which is why the VersionGuesser fails at guessing the version if the directory is considered unsafe in git

I don't need composer to guess version of root package based on git tags when all I need it to do is execute user defined script. In fact, it shouldn't even need to resolve the version when doing installation or update of packages as the root version is of zero consequences here as far as I am aware. The warning is moot because I am not expecting nor want composer to execute `git` in this environment.

**Comment by stof** [comment] 2024-11-20 11:22
@proton-ab the root package version is of zero consequence only if you don't have a circular dependency graph involving the root package (which cannot be known upfront). And this also requires that nothing uses the composer runtime API to get the root package version (as they would expect to get it properly instead of getting a `1.0` fallback).
Also, plugins might be reading the version of the root package.
However, note that Composer already provides a way to avoid the need for git for that: setting the `COMPOSER_ROOT_VERSION` env variable to provide that root version instead of relying on git-based guessing.

**Comment by proton-ab** [comment] 2024-11-20 16:06
> However, note that Composer already provides a way to avoid the need for git for that: setting the COMPOSER_ROOT_VERSION env variable to provide that root version instead of relying on git-based guessing.

That is a very interesting thing that I seem to have missed reading docs. I might be able to use this actually.

**Comment by Seldaek** [comment] 2024-12-11 10:34
Closing as I don't see a clear action we can take here.

**Closed by Seldaek** 2024-12-11 10:34 UTC
Labels: Bug
