### ISSUE TITLE
Can you set the root directory of your app's files in composer.json, especially for autoloading?

### ISSUE THREAD

**Issue by floriandammeyer** [composer/composer#5198] opened 2016-04-15 12:44 UTC
To clean up my project's folder structure, I have put all files that actually belong to the app into a subfolder called `app`. Everything else that is not required for deployment resides outside of this directory, like Vagrant configuration or composer files (composer.json, composer.lock). 

This keeps my app's files clean and separate from all the other stuff that is required for development. This way, I can just take all files inside the `app` directory and upload them to the server or whatever, without anything else getting in the way. 

    /
    ├── app/
    │   ├── config/
    │   ├── public/
    │   ├── src/
    │   ├── template/
    │   └── vendor/
    ├── vagrant-scripts/
    │   └── ...
    ├── xdebug-output/
    │   └── ...
    ├── composer.json
    ├── composer.lock
    └── Vagrantfile

However, this folder structure breaks composer's autoloader, because apparently I can't set a project root folder for the autoloader in my `composer.json` file. This is an excerpt of my composer.json, showing my path mappings:

```javascript
{
  // ...
  "config": {
    "vendor-dir": "app/vendor"
  },
  "autoload": {
    "psr-4": {
      "MyApp\\": "app/src/"
    }
  },
  // ...
}
```

Which results in the following `vendor/composer/autoload_psr4.php` file:

```php
<?php
$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname(dirname($vendorDir));
    
return array(
    // ...
        'MyApp\\' => array($baseDir . '/app/src'),
    // ...
);
```

As you can see, the name of the app's root folder (`app`) is hardcoded into the mapped path. This is no problem in the development environment, but on a production server, the app's root directory is most of the time not called `app`. I. e. it might be `/sharedHostingProvider/CustomerData/c1234/Website`, so the autoloader does not find my app's files anymore.

I would need something like this, which also simplified the vendor-dir path mapping:

```javascript
{
  // ...
  "project-root": "app",
  "config": {
    "vendor-dir": "vendor"
  },
  "autoload": {
    "psr-4": {
      "MyApp\\": "src"
    }
  }
  // ...
}
```

If I understand the documentation correctly, there is no such configuration as of now. So I wonder, is it deliberately not implemented or has just nobody ever had a use-case for it? Is my only solution for using such folder structure to move the `composer.json` into the `app/` directory?

**Comment by stof** [comment] 2016-04-15 14:09
putting the composer.json inside the app folder is probably the easiest, yes (which is possible for projects, not for package meant to be shared in a repository to be installed as dependency, as the composer.json must be at the root in such case)

**Comment by curry684** [comment] 2016-04-15 15:26
Your proposed solution still would not work as it would still imply having different `composer.json` files per environment.

I think we may easily be able to implement something like this when #5184 is merged. We could use that same functionality on autoloaders to enable using env variables based on deployment, so you could for example use:
```json
  "psr-4": {
      "MyApp\\": "$WEBROOT/src/"
  }
```
By tweaking the env variables on every deployment platform you could then achieve the desired effect.

This is just quick brainfarting though, didn't quite think anything through yet whether it's really a good idea to have 'dynamic autoloaders' like this.

**Comment by floriandammeyer** [comment] 2016-04-15 21:50
> Your proposed solution still would not work as it would still imply having different composer.json files per environment.

Why that? At the moment, composer creates autoload files with relative paths, and that behavior should stay the same because it makes the autoloader agnostic of its environment. The problem is just that composer creates those paths relative to the directory that contains the project's `composer.json` file. Setting a root directory would make composer aware of the directory which contains the actual application code and would therefore enable composer to create according relative paths in its autoload files. Setting the root path as in my example should change the generated autoload file as follows:

```php
<?php
// the $vendorDir stays the way it is
$vendorDir = dirname(dirname(__FILE__));
// but because of my given 'project-root' path, composer is aware 
// of the fact that -- in my case -- the $baseDir is just one directory 
// above the $vendorDir, so
//     $baseDir = dirname(dirname($vendorDir));
// from my original post becomes
$baseDir = dirname($vendorDir));
 
return array(
    // ...
        // note that the 'app' folder is omitted in this relative path,
        // because composer no longer uses the directory containing
        // the composer.json file as the root for the relative paths,
        // but instead the given root directory (which is 'app' in my example)
        'MyApp\\' => array($baseDir . '/src'),
    // ...
);
```

Those paths are all relative, so it doesn't matter if my project root directory is called `app`, or `webdata`, or `customer_1234_webdata`. This should keep it environment independent or have I missed your point?

**Comment by curry684** [comment] 2016-04-15 22:28
@floriandammeyer he said:

> This is no problem in the development environment, but on a production server, the app's root directory is most of the time not called app. I. e. it might be `/sharedHostingProvider/CustomerData/c1234/Website`

From this I gather that in his use case the deployment path is environment specific, not application specific. May be a misunderstanding though.

Just changing the vendor folder itself to a nested folder is trivial, as you could just put `app/vendor` in `COMPOSER_VENDOR_DIR` - internally we use `mkdir($path, ..., true);` to recursively ensure it exists so it should be agnostic to more paths being in there. Undocumented but should work.

**Comment by floriandammeyer** [comment] 2016-04-15 23:55
> From this I gather that in his use case the deployment path is environment specific

Yes, this is true. However the actual path is irrelevant to the problem because the autoloader uses relative paths anyway. The problem is just that composer is generating the **wrong** relative paths because it is using the wrong base for the paths.

Right now, composer creates the autoload path mappings relative to the folder of the `composer.json` file and there is no way of changing this. This is fine for projects that keep their application's code on the same directory level as the `composer.json` file. 

However, my project has so many other files which are only required for development, that I want to move my application's code into a subdirectory (called `app` in this case). Now everything that has to be deployed somewhere is in its own separate space, far away from any Vagrant clutter and also away from any composer configuration, which I obviously also don't want to deploy.

Just to make sure, I want to emphasize now that only the files **inside** this subdirectory are deployed to other servers, this subdirectory is therefore the actual root of my application! 

And this is where it gets messy: I can't tell composer that my application is not on the same level as the `composer.json` file. Composer still assumes it had to construct the autoloading paths relative to the composer.json file. And in doing so, it hardcodes the name of my subdirectory into the relative path.

```php
<?php
$vendorDir = dirname(dirname(__FILE__));
// Composer moves two directories up from the 
// $vendorDir, so that the $baseDir is the 
// same directory that contains the composer.json
// file. That is however not the actual base directory
// of my application. The base directory would only be
// one level up from the $vendorDir.
$baseDir = dirname(dirname($vendorDir));

return array(
    // ...
        // 'app' is now hardcoded into the autoloader, because
        // the path is being constructed relative to the directory
        // containing the composer.json file.
        'MyApp\\' => array($baseDir . '/app/src'), 
    // ...
);
```

This now makes the autoloader environment specific, because it assumes that the parent folder of my application's code is always called `app`. As I said, I only deploy the code **inside** the folder `app` to other servers! If I deploy the code to a shared host for example, the parent directory of `src` might be something like `customer_data_1234` (because the full path to my application might be `/sharedHostingProvider/CustomerData/customer_data_1234`). Now the autoloader can't find my files anymore, because it is looking in `/sharedHostingProvider/CustomerData/app` which does not exist.

So to solve this problem, I would need some way of telling composer that the autoload paths should be created relative to the `app` subdirectory, not the directory containing the composer.json.

While writing this I realize that this feature only makes sense for projects, not for packages, as @stof already said. I guess I have been trying to use composer for something that it isn't meant to be used for. I was trying to solve a deployment issue, but this autoloader-setup would not make any sense at all for for composer packages. And after all, composer is a package managing tool, not a deployment tool. I guess I will go with @stof solution and move the composer.json file to my `app` subdirectory.

**Closed** 2016-04-16 08:46 UTC

**Comment by robozb** [comment] 2016-04-27 19:25
I think it might be a good idea if you can define a "root/base" dir in the composer.json what the composer can use to determine the relative paths to it, so the composer.json can be anywhere in the filesystem during the developing.

**Comment by Milania1** [comment] 2017-02-19 17:12
Are the plans for a "root/base" discarded or already implemented and I just can't find it?

Personally, I would love to see this option, since I have exactly the same problem as the issue initiator. Currently, I adjust the generated paths manually with the hope to never need to re-run the autoloader again^^

**Comment by sogetimaitral** [comment] 2017-03-01 09:35
I second the need for variables in composer.json.
I disagree that composer is only a dev tool. This is also a deployment tool used in php-buildpack for example. This buildpack look for a composer.json at the root directory, so putting it in the app folder is not an option :(

I have to go with 2 composer.json files, one for local environment, and one for "prod" environment, which is even worse than the possibility to use environemnt variables in the composer.json file...

**Comment by ccfelix** [comment] 2018-01-05 13:05
It would be of great use to be able to create a structure like the one below in my projects:
/
├── frmwrk/
│   ├── config/
│   ├── src/
│   ├── template/
│   └── vendor/
├── assets/
├── composer.json
├── composer.lock
└── Vagrantfile

**Comment by ChrisTucker2000** [comment] 2018-03-21 14:47
Has this been fixed yet?

**Comment by ramsey** [comment] 2018-05-15 22:54
I've run into a use case where this would be very helpful for a project I'm working on, too.

**Comment by curry684** [comment] 2018-05-15 23:08
Please refer to my previous answer: https://github.com/composer/composer/issues/5198#issuecomment-210669377

`COMPOSER_VENDOR_DIR=app/vendor composer install` should work for the requested usecase.

> I have to go with 2 composer.json files, one for local environment, and one for "prod" environment, which is even worse than the possibility to use environemnt variables in the composer.json file...

[There is a good reason this is not easily possible](https://12factor.net/dev-prod-parity).

**Comment by KarelWintersky** [comment] 2018-08-28 10:51
> composer creates the autoload path mappings relative to the folder of the composer.json file and there is no way of changing this. 

no way? Really? (sarcasm)
What about declare option in `composer.json` file like `basedir: ...` ?

**Comment by curry684** [comment] 2018-08-28 10:54
That option does not make a lot of sense as static configuration, hence why it's not in the `composer.json`. It could sometimes make sense in a specific environment, hence [why it's an environment variable](https://github.com/composer/composer/issues/5198#issuecomment-389342591).

**Comment by KarelWintersky** [comment] 2018-11-22 04:49
Hardcode binding packages source directory to one fixed name is a **bad** design. And bad solution. 

I want place composed packages to `/libs/packages`... and... can't do it. 

> composer creates the autoload path mappings relative to the folder of the composer.json file and there is no way of changing this.

Statements about the impossibility of doing this are like religious prejudices! 
No religion in the code, please!

**Comment by marekdedic** [comment] 2019-08-30 10:46
Is there any update on this issue please?

So far I see only people saying that there is no way of changing this and that it would be bad design (@curry684 ) - I am sorry but I still don't get **why** it would be bad design... I am really missing this feature and would like to know the rationale behind why this has been rejected...

Thanks

**Comment by max-carroll** [comment] 2019-09-13 08:19
I dont get how implementing this feature would prevent the deployment from being environment agnostic, it would simply enable you to have you source code in a different folder to the package manager file.

This is a achievable with create-react-app by having your source in a src folder and then doing an npm build which then build it to public, then this public folder can be deployed anywhere.

I suppose a lot of people have used another technology such as create react app and want the felxibility that comes with it in their php apps too

**Comment by curry684** [comment] 2019-09-19 12:18
@marekdedic `composer.json` is supposed to be a universal file describing the dependencies of your *application*, not your *deployment*. Once deployments become different as an integral part of your application you are violating a lot of basic software engineering principles. Differences between deployments should be semantically declared and not committed to the application's source control, most commonly in `.env` files, environment variables or configuration stores.

**Comment by marekdedic** [comment] 2019-09-20 08:33
@curry684 I'm sorry, but it seems to me that the link to *deployment* is only marginal, at least for me.

Why I would like to see this feature (and I'd be willing to take a shot at it if there's support) may not be the same reason as the original author, but it seems to me that it is:

Basically what I would want is to keep my source files separate from all the other "clutter" in a repository - the `composer.json` file, maybe some config files for tools like phan, `.gitignore` etc. So I imagined I would create a folder inside my repo, called for example `app` (as suggested by the original author of this issue) and all of the source code would live there.

Yes, now comes the link to the deployment - when I deploy the application (e. g.), I probably don't want all the config files and the dotfiles, so I only deploy the `app` directory. But alas, now all my autoloading is broken, because composer always does autoloading relative to the `composer.json` file. So I need to somehow hack around this. (either on the deployment side or by e. g. putting `composer.json` in the `app` folder)

I see no way how to get around this using some `.env` files or environment variables - the autoloader path is just hard-coded.

**Comment by max-carroll** [comment] 2019-09-20 09:01
yes the composer file assumes the folder where it exists will be the root of the deployment, so in this respect can we say that it is composer itself isnt fundamentaly deployment agnostic?

**Comment by curry684** [comment] 2019-09-20 09:02
Well let's agree to disagree   :wink:   I'm not a Composer team member or anything, so all I do is share my views and opinions. In this I believe it's pretty pointless to complicate Composer with easily abused features causing tons of potential new problems for people abusing them without truly understanding consequences, just for the sake of having some kind of custom deployment procedure that nobody else uses.

**Comment by djibarian** [comment] 2019-09-20 09:16
Where do you see there are 3 people supporting this feature?

**Comment by max-carroll** [comment] 2019-09-20 09:58
I support this feature

**Comment by marekdedic** [comment] 2019-09-20 10:34
@curry684 I was hoping more to be convinced or see some solution that I don't, but you do... :)

> ```json
>   "psr-4": {
>       "MyApp\\": "$WEBROOT/src/"
>   }
> ```

I really like this idea, but unfortunately, for me, most of the time I have just FTP access to the deployment, so setting environment variables is not an option. :(

I agree this feature could be abused if set improperly, the way I envisioned it, it would be limited to subfolders of the repo - making it work just like *as if* `composer.json` was in the subfolder.

If anything, I think this would make the application **less** environment-specific - for many usecases, as reading through the comments above says.

Anyway, is there a way a Composer team member could opine on this? Or to re-open this issue, as it definitely doesn't look settled (although I am the one stirring the debate...).

**Comment by KarelWintersky** [comment] 2019-09-20 10:52
I support this feature

**Comment by Milania1** [comment] 2019-09-21 15:15
My current workaround for this issue is to wrap composer calls with the following `run_composer.sh` script:
```Bash
#!/bin/bash

mv composer.json deployment/composer.json
cd deployment
composer $@
cd ..
mv deployment/composer.json composer.json
```
assuming the following directory structure:
```
my_app
   - composer.json
   - run_composer.sh
   deployment
      - files supposed to be uploaded to the webserver
```

It basically works around the issue by temporarily moving the `composer.json` file to the deployment folder.

I guess the problem is that I use composer *only* for the autoloader and this is not the main use case.

**Comment by smileBeda** [comment] 2024-06-30 13:23
For some reason composer gets the paths of required packages (which become part of `vendor`) correctly.
So, this shouldn't really be too hard to fix:
provide a setting that allows us to determine the path to the autoload classes _relative to vendor folder_, since it gets that part right... and the problem is fixed, without actually breaking anything else.

What Composer produces in OPs example when you have a requirement in composer.json:
```
public static $prefixDirsPsr4 = array (
        'Your\\Namespace\\' => 
        array (
            0 => __DIR__ . '/../../..' . '/app/src',
        ),
        'Psr\\Container\\' => 
        array (
            0 => __DIR__ . '/..' . '/psr/container/src',
        ),
    );
```

It makes zero sense that this should not be fixable for source files, if it is perfectly working for requirements.
Clearly, it knows the _correct_ path to the vendor - so why not build on that and if then its needed, provide a setting to allow custom path relative to vendor path, if nothing else?

**Comment by smileBeda** [comment] 2024-07-01 07:37
I have implemented this on https://github.com/TukuToi/composer, if anyone is interested in testing this out.

There are absolutely no problems arising from it, as long you know what you do, which pre supposedly anyone using composer should do.

With the new config option you can keep your composer.json in the root, and dump the files into a sub-root and it will adjust the paths accordingly.

Note, for now, this only works with `classmap`, it _might_ just work with psr4 but I did not test this as I do not use it.

**Comment by AndreasDolphin** [comment] 2025-01-29 15:06
I just bumped into this issue almost a decade later! I have a source folder where everything that should be deployed resides, just like in this issue, but the auto-loader does not output valid paths due to the `composer.json` file being outside the source folder.

I'll just drop the `composer.json` inside the source folder for now, and exclude it in the deployment script, but I'm honestly surprised that it wasn't possible to fix this in the config out of the box.

**Comment by smileBeda** [comment] 2025-01-29 15:52
@AndreasDolphin my fork did the trick for me.
However, instead of navigating against the so called mainstream what I do now is I have a workflow setup on git that does the src/replace for me on publish. 
_Cumbersome_, thinking that it really needs _nothing_ but a small edit on the core code side to fix this issue _while keeping all other things working_!

I hope dev's will consider what I did on the branch.
