### ISSUE TITLE
"as" bug with --prefer-lowest --prefer-stable

### ISSUE THREAD

**Issue by GrahamCampbell** [composer/composer#9025] opened 2020-06-29 09:48 UTC
My `composer.json`:

```json
{
    "name": "guzzlehttp/guzzle",
    "type": "library",
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/GrahamCampbell/promises"
        },
        {
            "type": "vcs",
            "url": "https://github.com/GrahamCampbell/psr7"
        }
    ],
    "require": {
        "php": "^7.2.5",
        "ext-json": "*",
        "guzzlehttp/promises": "dev-no-functions as 1.4.0",
        "guzzlehttp/psr7": "dev-no-functions as 1.7.0",
        "psr/http-client": "^1.0"
    },
    "provide": {
        "psr/http-client-implementation": "1.0"
    },
    "require-dev": {
        "ext-curl": "*",
        "ergebnis/composer-normalize": "^2.0",
        "php-http/client-integration-tests": "dev-phpunit8",
        "phpunit/phpunit": "^8.5.5",
        "psr/log": "^1.1"
    }
}

```

When I run this command (version 1824637dab08405989503764dd5e3a129a4f00c3):

```
composer update --no-interaction --prefer-stable --prefer-lowest --prefer-dist
```

I get the following output:

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires guzzlehttp/psr7 dev-no-functions as 1.7.0, found guzzlehttp/psr7[1.3.1, ..., 1.6.1] but it does not match the constraint.
  Problem 2
    - Root composer.json requires php-http/client-integration-tests dev-phpunit8 -> satisfiable by php-http/client-integration-tests[dev-phpunit8].
    - php-http/client-integration-tests dev-phpunit8 requires guzzlehttp/psr7 ^1.0 -> found guzzlehttp/psr7[1.3.1, ..., 1.6.1] but it conflicts with your root composer.json require (dev-no-functions as 1.7.0).

You are using a snapshot build of Composer 2, which may be the cause of the problem. Run `composer self-update --stable` and then try again. In case it solves the problem, please report an issue mentioning Composer 2.
```

**Comment by naderman** [comment] 2020-06-29 15:51
Looks a bit like pool builder filtering is going wrong with aliases

**Comment by Seldaek** [comment] 2020-07-01 08:15
With latest master (45f228a375703c34a3a086573ee57ec4d49d6a67) it seems to work fine for me. Can you still reproduce this?

```
$ composer update --no-interaction --prefer-stable --prefer-lowest --prefer-dist
Loading composer repositories with package information
Updating dependencies
Lock file operations: 42 installs, 0 updates, 0 removals
  - Locking clue/stream-filter (v1.3.0)
  - Locking dflydev/markdown (v1.0.0)
  - Locking doctrine/instantiator (1.2.0)
  - Locking ergebnis/composer-normalize (2.4.0)
  - Locking ergebnis/json-normalizer (0.12.0)
  - Locking ergebnis/json-printer (3.0.2)
  - Locking guzzlehttp/promises (dev-no-functions 3836256)
  - Locking guzzlehttp/psr7 (dev-no-functions 2a7fe37)
  - Locking justinrainbow/json-schema (4.0.0)
  - Locking localheinz/diff (1.0.1)
  - Locking myclabs/deep-copy (1.9.1)
  - Locking phar-io/manifest (1.0.3)
  - Locking phar-io/version (2.0.1)
  - Locking php-http/client-integration-tests (dev-phpunit8 6d527ff)
  - Locking php-http/message (v1.0.0)
  - Locking php-http/message-factory (v1.0.2)
  - Locking phpdocumentor/reflection-docblock (2.0.0)
  - Locking phpspec/prophecy (1.8.1)
  - Locking phpunit/php-code-coverage (7.0.7)
  - Locking phpunit/php-file-iterator (2.0.2)
  - Locking phpunit/php-text-template (1.2.1)
  - Locking phpunit/php-timer (2.1.2)
  - Locking phpunit/php-token-stream (3.1.0)
  - Locking phpunit/phpunit (8.5.5)
  - Locking psr/http-client (1.0.0)
  - Locking psr/http-message (1.0)
  - Locking psr/log (1.1.0)
  - Locking ralouphie/getallheaders (2.0.5)
  - Locking sebastian/code-unit-reverse-lookup (1.0.1)
  - Locking sebastian/comparator (3.0.2)
  - Locking sebastian/diff (3.0.2)
  - Locking sebastian/environment (4.2.2)
  - Locking sebastian/exporter (3.1.1)
  - Locking sebastian/global-state (3.0.0)
  - Locking sebastian/object-enumerator (3.0.3)
  - Locking sebastian/object-reflector (1.1.1)
  - Locking sebastian/recursion-context (3.0.0)
  - Locking sebastian/resource-operations (2.0.1)
  - Locking sebastian/type (1.1.3)
  - Locking sebastian/version (2.0.1)
  - Locking th3n3rd/cartesian-product (v0.3.0)
  - Locking theseer/tokenizer (1.1.3)
```

**Comment by GrahamCampbell** [comment] 2020-07-01 09:41
It worked correctly on my laptop, but not on CI. I think there may have also been a root package version set for guzzle/http. Maybe that breaks things?

**Comment by Seldaek** [comment] 2020-07-01 09:46
Maybe. What was it set to?

**Comment by GrahamCampbell** [comment] 2020-07-01 09:50
Not sure. It was from within a PR: https://github.com/guzzle/guzzle/runs/816707652?check_suite_focus=true. The composer.json (at the time of that build run) was as in the OP.

**Comment by Seldaek** [comment] 2020-07-01 09:56
Doesn't seem like it has an env set in the CI. So it'd use `dev-no-functions` or `dev-master`, both of which resolve fine for me.. Not sure what the composer version used was there in CI, so if this can't be reproduced for sure I'd say we close this..

**Comment by GrahamCampbell** [comment] 2020-07-01 10:08
Not sure what the composer version used was there in CI

it was the snapshot build from 2 days ago

**Comment by Seldaek** [comment] 2020-07-02 06:15
Also can not repro using 1824637dab08405989503764dd5e3a129a4f00c3, so not sure what to say here.. If you can repro somehow let me know, in the meantime let's close this as a glitch of some sort. Maybe it failed because it couldn't find the dev-no-functions version at all in the vcs repo due to some lag in github API or something? They had a few issues lately..

**Closed by Seldaek** 2020-07-02 06:15 UTC
