### ISSUE TITLE
Link in /bin is not updated

### ISSUE THREAD

**Issue by alecpl** [composer/composer#6522] opened 2017-07-02 11:24 UTC
My original `composer.json`:
```json
    "repositories": [
        {
            "type": "pear",
            "url": "https://pear.php.net/"
        }
    ],
    "require": {
        "pear-pear.php.net/crypt_gpg": "~1.4.3"
    }
```
Note that with that I have 
```
$ ls -l bin 
lrwxrwxrwx 1 alec alec  53 Apr 28 10:12 crypt-gpg-pinentry -> ../pear-pear.php.net/Crypt_GPG/bin/crypt-gpg-pinentry
```

Next I modify the composer.json file to use packagist (removed repository and changed require):
```json
    "repositories": [],
    "require": {
        "pear/crypt_gpg": "~1.6.0"
    }
```
And on composer update now I get the following output:
```
$ php composer.phar update --no-dev
Loading composer repositories with package information
Initializing PEAR repository https://pear.php.net
Updating dependencies                                          
Package operations: 8 installs, 1 update, 8 removals
   ...
  - Removing pear-pear.php.net/crypt_gpg (1.4.3)
  - Installing pear/crypt_gpg (v1.6.0): Loading from cache
                                                                                                                                          
  [ErrorException]                                                                                                                         
  file_put_contents(/home/alec/roundcubemail-1.2.5/vendor/bin/crypt-gpg-pinentry): failed to open stream: No such file or directory  
```

**Comment by alcohol** [comment] 2017-07-04 09:00
It seems to want to install the binary symlink into `vendor/bin`, whereas from your issue I can infer that you actually have your bin dir default changed and set to `./bin`. So the `vendor/bin` directory does not exist. Not sure why Composer is trying to install it there though. Can you show us your actual complete `composer.json`?

**Comment by alecpl** [comment] 2017-07-04 09:13
Before update: https://github.com/roundcube/roundcubemail/blob/release-1.2/composer.json-dist
After update: https://github.com/roundcube/roundcubemail/blob/release-1.3/composer.json-dist

**Comment by Seldaek** [comment] 2017-08-07 12:48
I think this is just a bug in the PEAR handling of binaries.. But this stuff is very old and not well supported. Gonna close as duplicate of #6514 which seems likely related, and my comment there stands: if nobody with an interest in PEAR compat fixes it, I doubt it will get fixed..

**Closed by Seldaek** 2017-08-07 12:48 UTC
Labels: Support

**Comment by alecpl** [comment] 2017-08-07 13:11
Fair enough, but you noticed that here I did an update from pear to packagist?

**Comment by Seldaek** [comment] 2017-08-07 13:24
I did notice, but the question is is it failing when only using stuff from packagist? If not then I'd say it's a bug in PEAR-land in which case I won't waste my time on it sorry :)
