### ISSUE TITLE
Repository priority is ignored when dependent package added.

### ISSUE THREAD

**Issue by simesy** [composer/composer#4710] opened 2015-12-15 22:28 UTC
Composer ignores the higher priority repository of PackageA (`drupal/migrate_plus`) when I add a PackageB (`drupal/migrate_tools`) that depends on PackageA (where PackageA is also listed in the  repository that PackageB is listed in).

This is my composer.json. With this setup, `drupal/migrate_plus` is cloned from `github.com:simesy/migrate_plus.git`.

    {
        "name": "somethin/somethin",
        "type": "project",
        "license": "GPL-2.0+",
        "repositories": [
            {
                "type": "vcs",
                "url": "git@github.com:simesy/migrate_plus.git"
            },
            {
                "type": "composer",
                "url": "https://packagist.drupal-composer.org"
            }        
        ],
        "require": {
            "drupal/migrate_plus": "dev-8.x-1.x",
        },
        "minimum-stability": "dev",
        "prefer-stable": true
    }

When I add `drupal/migrate_tools": "dev-8.x-1.x"` (see below), which has a dependency on migrate_plus, and run `composer update`, the migrate_plus package is replaced by the source defined by `packagist.drupal-composer.org` - my custom repo is ignored, even though it has a higher priority.

    {
        "name": "somethin/somethin",
        "type": "project",
        "license": "GPL-2.0+",
        "repositories": [
            {
                "type": "vcs",
                "url": "git@github.com:simesy/migrate_plus.git"
            },
            {
                "type": "composer",
                "url": "https://packagist.drupal-composer.org"
            }        
        ],
        "require": {
            "drupal/migrate_plus": "dev-8.x-1.x",
            "drupal/migrate_tools": "dev-8.x-1.x"
        },
        "minimum-stability": "dev",
        "prefer-stable": true
    }

**Comment by alcohol** [comment] 2015-12-16 12:51
Please create a reproducible scenario.

**Comment by simesy** [comment] 2015-12-16 21:51
Hmm, I thought that's what I posted. Is the problem that you can't reproduce? Or do you need me to be more specific?

**Comment by cs278** [comment] 2015-12-16 22:22
I think this is because the default branch of your repository has no `composer.json`, if you switch the default branch to `8.x-1.x` it should pick up that repository.

**Comment by simesy** [comment] 2015-12-16 22:54
Changed the default branch. Things just got a bit weirder. Now doing an update with the 2nd composer.json now results in the correct origin, and the tracking branch is correct, but it shows that the local branch is out of date and a merge with origin/8.x-1.x results in conflicts. It's almost like composer first cloned the wrong one, and then simply swapped out the origins. I'm running the test again with a cleared cache, and will get verbose output.

    * remote origin
      Fetch URL: git://github.com/simesy/migrate_plus.git
      Push  URL: git@github.com:simesy/migrate_plus.git
      HEAD branch: 8.x-1.x
      Remote branches:
        8.x-1.x                 tracked
        april_poc               tracked
        master                  tracked
        refactor_source_plugins tracked
        split                   tracked
      Local branch configured for 'git pull':
        8.x-1.x merges with remote 8.x-1.x
      Local ref configured for 'git push':
        8.x-1.x pushes to 8.x-1.x (local out of date)

**Comment by simesy** [comment] 2015-12-16 23:18
So yes, composer points to the right origin, but then `git reset --hard HASH`, where that HASH is the latest commit from the wrong origin.

      - Updating drupal/migrate_plus dev-8.x-1.x (2caf641 => 2f33339)
    Executing command (modules/migrate_plus/): git status --porcelain --untracked-files=no
        Checking out 2f33339ff7b19a9eb75c3d3f67880c340a624bd5
    Executing command (modules/migrate_plus/): git remote -v
    Executing command (modules/migrate_plus/): git remote set-url composer 'http://git.drupal.org/project/migrate_plus.git' && git fetch composer && git fetch --tags composer
    Executing command (modules/migrate_plus/): git branch -r
    Executing command (modules/migrate_plus/): git checkout '8.x-1.x' --
    Executing command (modules/migrate_plus/): git reset --hard '2f33339ff7b19a9eb75c3d3f67880c340a624bd5' --
    Executing command (modules/migrate_plus/): git log 2caf641d44406154743aa5cdc11f8afaa61a850c..2f33339ff7b19a9eb75c3d3f67880c340a624bd5 --pretty=format:"%h - %an: %s"
        Pulling in changes:
          2f33339 - stborchert: Issue #2613336 by stBorchert, webflo: Convert migration_group to a third party setting

      - Marking drupal/migrate_plus (8.1.x-dev 2f33339) as installed, alias of drupal/migrate_plus (dev-8.x-1.x 2f33339)

**Comment by simesy** [comment] 2016-01-03 01:06
I'm wondering if anyone has managed to reproduce this using the instructions?

**Comment by jaimz22** [comment] 2016-01-14 23:22
I don't think I've reproduced the same thing, but it seems similar to your issue.

Just a bit of backstory: So I've forked a couple repos to use PHP_FFMpeg with Symfony 3...
PHP_FFMpeg requires; (among other libraries) alchemy/binary-driver and neutron/temporary-filesystem. Both of these libraries are using Symfony 2 components, I simply forked them and changed the requirement to the Symfony 3 version of the component. Then I forked PHP_FFMpeg and added my repositories and changed the libraries in question to just simply use dev-master.

When I run ```composer install``` or ```composer update vendor/package``` it fails every time in the manner being described in this issue.

running with verbose mode I see:

```
Executing command (/root/.composer/cache/vcs/https---github.com-jaimz22-BinaryDriver.git/): git rev-parse --git-dir
Executing command (/root/.composer/cache/vcs/https---github.com-jaimz22-BinaryDriver.git/): git remote -v
Executing command (/root/.composer/cache/vcs/https---github.com-jaimz22-BinaryDriver.git/): git remote set-url origin 'git://github.com/jaimz22/BinaryDriver.git' && git remote update --prune origin
Executing command (/root/.composer/cache/vcs/https---github.com-jaimz22-BinaryDriver.git/): git show-ref --tags
Executing command (/root/.composer/cache/vcs/https---github.com-jaimz22-BinaryDriver.git/): git branch --no-color --no-abbrev -v
Executing command (/root/.composer/cache/vcs/https---github.com-jaimz22-BinaryDriver.git/): git branch --no-color
Executing command (/root/.composer/cache/vcs/https---github.com-jaimz22-BinaryDriver.git/): git show 'master':composer.json
Executing command (/root/.composer/cache/vcs/https---github.com-jaimz22-BinaryDriver.git/): git log -1 --format=%at 'master'
Reading composer.json of alchemy/binary-driver (1.0.0)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/ec284bcfb3ce058fb61b2d851296d6d39412655c from cache
Importing tag 1.0.0 (1.0.0.0)
Reading composer.json of alchemy/binary-driver (1.1.0)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/0c9cd7ae85c2f46655bacfa8e70d254e7f6096d3 from cache
Importing tag 1.1.0 (1.1.0.0)
Reading composer.json of alchemy/binary-driver (1.2.0)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/9cb49140f9ca1e3d7f1c9f1da0e66c513ef1ca78 from cache
Importing tag 1.2.0 (1.2.0.0)
Reading composer.json of alchemy/binary-driver (1.2.1)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/2bc09928dcc5b13748ebed260d75b8a87eeab11f from cache
Importing tag 1.2.1 (1.2.1.0)
Reading composer.json of alchemy/binary-driver (1.3.0)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/ffd53eaeff6b5dec1b876c502382360a0e78fc25 from cache
Importing tag 1.3.0 (1.3.0.0)
Reading composer.json of alchemy/binary-driver (1.3.1)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/0cfa50b4b3f2a16245ea72017633039c811e31e4 from cache
Importing tag 1.3.1 (1.3.1.0)
Reading composer.json of alchemy/binary-driver (1.3.2)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/5a8d6bb0a3baf82697a22e338172afb23741cfa3 from cache
Importing tag 1.3.2 (1.3.2.0)
Reading composer.json of alchemy/binary-driver (1.3.3)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/3a80a05fbca09664b521fd4af715cfecdb07a650 from cache
Importing tag 1.3.3 (1.3.3.0)
Reading composer.json of alchemy/binary-driver (1.3.4)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/7f90ec80f679d6161f9facc9e32a9988ed2c03d1 from cache
Importing tag 1.3.4 (1.3.4.0)
Reading composer.json of alchemy/binary-driver (1.4.0)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/aec550d9656b6cf291be4ceaa77c908385ba9b52 from cache
Importing tag 1.4.0 (1.4.0.0)
Reading composer.json of alchemy/binary-driver (1.4.1)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/c3baaeff6bdde8b62aa05008518c271327aadaf1 from cache
Importing tag 1.4.1 (1.4.1.0)
Reading composer.json of alchemy/binary-driver (1.5.0)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/b32c03d4b56ce29f783051eac55887adae654b41 from cache
Importing tag 1.5.0 (1.5.0.0)
Reading composer.json of alchemy/binary-driver (master)
Reading /root/.composer/cache/repo/https---github.com-jaimz22-BinaryDriver.git/4bb3460f3922bddbc56f321217a04a397741fb60 from cache

```

So you can clearly see it's reading from my repository but then

```
  - Updating alchemy/binary-driver dev-master (b32c03d => 4bb3460)
Executing command (/var/www/PHP-FFMpeg/vendor/alchemy/binary-driver): git status --porcelain --untracked-files=no
    Checking out 4bb3460f3922bddbc56f321217a04a397741fb60
Executing command (/var/www/PHP-FFMpeg/vendor/alchemy/binary-driver): git remote -v
Executing command (/var/www/PHP-FFMpeg/vendor/alchemy/binary-driver): git remote set-url composer 'git://github.com/alchemy-fr/BinaryDriver.git' && git fetch composer && git fetch --tags composer
Executing command (/var/www/PHP-FFMpeg/vendor/alchemy/binary-driver): git branch -r
Executing command (/var/www/PHP-FFMpeg/vendor/alchemy/binary-driver): git checkout 'master' --
Executing command (/var/www/PHP-FFMpeg/vendor/alchemy/binary-driver): git reset --hard '4bb3460f3922bddbc56f321217a04a397741fb60' --
Executing command (/var/www/PHP-FFMpeg/vendor/alchemy/binary-driver): git checkout '4bb3460f3922bddbc56f321217a04a397741fb60' -- && git reset --hard '4bb3460f3922bddbc56f321217a04a397741fb60' --
    4bb3460f3922bddbc56f321217a04a397741fb60 is gone (history was rewritten?)
Failed: [RuntimeException] Failed to execute git checkout '4bb3460f3922bddbc56f321217a04a397741fb60' -- && git reset --hard '4bb3460f3922bddbc56f321217a04a397741fb60' --

fatal: reference is not a tree: 4bb3460f3922bddbc56f321217a04a397741fb60

Executing command (/var/www/PHP-FFMpeg/vendor/alchemy/binary-driver): git log b32c03d4b56ce29f783051eac55887adae654b41..4bb3460f3922bddbc56f321217a04a397741fb60 --pretty=format:"%h - %an: %s"



  [RuntimeException]
  Failed to execute git log b32c03d4b56ce29f783051eac55887adae654b41..4bb3460f3922bddbc56f321217a04a397741fb60 --pretty=format:"%h - %an: %s"
  fatal: Invalid revision range b32c03d4b56ce29f783051eac55887adae654b41..4bb3460f3922bddbc56f321217a04a397741fb60
```


```
Exception trace:
 () at phar:///usr/local/bin/composer/src/Composer/Downloader/GitDownloader.php:301
 Composer\Downloader\GitDownloader->getCommitLogs() at phar:///usr/local/bin/composer/src/Composer/Downloader/VcsDownloader.php:136
 Composer\Downloader\VcsDownloader->update() at phar:///usr/local/bin/composer/src/Composer/Downloader/DownloadManager.php:253
 Composer\Downloader\DownloadManager->update() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:180
 Composer\Installer\LibraryInstaller->updateCode() at phar:///usr/local/bin/composer/src/Composer/Installer/LibraryInstaller.php:109
 Composer\Installer\LibraryInstaller->update() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:172
 Composer\Installer\InstallationManager->update() at phar:///usr/local/bin/composer/src/Composer/Installer/InstallationManager.php:139
 Composer\Installer\InstallationManager->execute() at phar:///usr/local/bin/composer/src/Composer/Installer.php:603
 Composer\Installer->doInstall() at phar:///usr/local/bin/composer/src/Composer/Installer.php:232
 Composer\Installer->run() at phar:///usr/local/bin/composer/src/Composer/Command/UpdateCommand.php:143
 Composer\Command\UpdateCommand->execute() at phar:///usr/local/bin/composer/vendor/symfony/console/Command/Command.php:256
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:838
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:189
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:147
 Composer\Console\Application->doRun() at phar:///usr/local/bin/composer/vendor/symfony/console/Application.php:120
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/composer/src/Composer/Console/Application.php:82
 Composer\Console\Application->run() at phar:///usr/local/bin/composer/bin/composer:43
 require() at /usr/local/bin/composer:25
```

**Comment by Seldaek** [comment] 2016-01-29 14:09
I can reproduce it, but I have no clue what is going on, it acts up really weird, as subsequent updates do stranger things and eventually I could not update anymore.. I'll try and keep digging.

**Comment by naderman** [comment] 2016-02-24 15:11
One thing I'm a little surprised by is that dev-8.x-1.x is even listed on https://packagist.drupal-composer.org/packages/drupal/migrate_plus since it doesn't contain a composer.json on that repo.

**Comment by naderman** [comment] 2016-02-24 17:47
Alright here's what happens:

- Available packages:
  - drupal/migration_plus dev-8.x-1.x on github
  - drupal/migration_plus dev-8.x-1.x on packagist.drupal-composer.org
  - drupal/migration_plus 8.1.x-dev (alias) on packagist.drupal-composer.org
  - drupal/migration_tools dev-8.x-1.x on packagist.drupal-composer.org
    - requires drupal/migration_plus 8.*
- You require `"drupal/migration_plus": "dev-8.x-1.x" which correctly picks your github repository
- Available packages now:
  - drupal/migration_plus dev-8.x-1.x on github
  - drupal/migration_plus dev-8.x-1.x on packagist.drupal-composer.org
  - drupal/migration_plus 8.1.x-dev (alias) on packagist.drupal-composer.org
  - drupal/migration_plus dev-8.x-1.x on your disk
  - drupal/migration_tools dev-8.x-1.x on packagist.drupal-composer.org
    - requires drupal/migration_plus 8.*
- You additionally require `"drupal/migration_tools": "dev-8.x-1.x" which correctly picks the the package from packagist.drupal-composer.org
  - The only package matching the 8.* constraint is the 8.1.x-dev package on packagist.drupal-composer.org, dev-* are branch names and do not match version constraints
  - The drupal/migration_plus 8.1.x-dev package is considered an alias of drupal/migration_plus dev-8.x-1.x so your composer.json's requirement is still fulfilled
- Composer decides to "update" drupal/migration_plus on your disk to drupal/migration_plus dev-8.x-1.x on packagist.drupal-composer.org which has the 8.1.x-dev alias and thus fulfills all dependencies

So Composer is acting correctly here. The fundamental problem is that packagist.drupal-composer.org is advertising package aliases, that are lost when duplicating a git repository (due to lack of branch-alias info in a composer.json) and even worse, are lost on disk because there is no actual composer.json. So after installation the dependencies are actually unmet, because the local drupal/migration_plus dev-8.x-1.x package does not have a branch alias, unlike its source on packagit.drupal-composer.org.

So as a workaround for your solution, you can include a branch-alias in your drupal/migration_plus repository's composer.json, but in general packagist.drupal-composer.org needs to stop advertising aliases that don't exist in the packages themselves. I really don't think it's a good idea to be distributing composer packages without a composer.json allowing local reconstruction of the metadata.

**Comment by naderman** [comment] 2016-02-24 17:47
And I'll close this, as there's no bug in Composer itself.

**Closed by naderman** 2016-02-24 17:47 UTC
Labels: Bug, Solver

**Comment by alcohol** [comment] 2016-02-24 17:52
@Seldaek Maybe bring this up at your next chat with the Drupal folks? :)

**Comment by naderman** [comment] 2016-02-24 18:14
@alcohol they are notified already

**Comment by alcohol** [comment] 2016-02-24 18:41
Yeah Jordi told me a little after I posted that, didn't know.

**Comment by simesy** [comment] 2016-02-25 01:04
Super grateful, thank you.
