### ISSUE TITLE
Escaping of angle brackets

### ISSUE THREAD

**Issue by staabm** [composer/composer#4560] opened 2015-10-29 11:36 UTC
As reported in #4559 there were some problems in case of user-supplied input strings which contain angle brackets. This was fixed in this ticket as far as the VcsDownloader is concerned.

As discussed further[1] on this problem might be present in other parts of composer as well and a proper solution to it would require to indroduce some kind of escaping which could be provided by one of the IO* classes.

[1] https://github.com/composer/composer/pull/4559/files#r43361511

Open questions are:
- Are all classes which IOInterface supossed to handle or strip the markup patterns like `<info>` etc. or is it just implementation detail of `IOConsole` and its subclasses?
- Should we introduce escaping in the IO* layer instead of fixing it in the callsite as the fix in #4559 did?

**Comment by alcohol** [comment] 2015-10-29 11:50
Too much effort for an issue that is virtually non-existant. :-1:

**Comment by Seldaek** [comment] 2015-10-29 18:40
I agree, it never came up as an issue so it's probably not worth the trouble. If anything I think it should be fixed in symfony so that it doesn't blow up if you output a tag for an unknown style. That would fix the root cause.

**Closed by Seldaek** 2015-10-29 18:40 UTC
Labels: Question
