### ISSUE TITLE
remove command corrupts composer.json when custom packages are defined

### ISSUE THREAD

**Issue by derhasi** [composer/composer#3716] opened 2015-02-06 17:14 UTC
## Problem 

When a custom package ist defined, composer remove seems to have a problem with removing the right part of the composer.json. It seems like the failure is located in `Composer\Json\JsonManipulator::removeSubNode`.

```json
{
  "description": "Composer template for Drupal projects",
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "custom/package",
        "type": "metapackage",
        "version": "1.0.0",
        "require": {
          "derhasi/tempdirectory": "0.1.4"
        }
      }
    }
  ],
  "require": {
    "custom/package": "1.0.0",
    "derhasi/tempdirectory": "0.1.4",
    "rkr/wildcards": "~1.0"
  },
  "require-dev": {
    "composer/composer": "dev-master"
  }
}
```

## How to reproduce:

1. Use composer.json from above (or clone gist https://gist.github.com/derhasi/24f46ec9f74af9a6a83f)
2. `composer install`
3. `./vendor/bin/composer remove rkr/wildcards`

## Result 

After that the composer.json's require was replaced by the one from the custom package:

![Corrupt composer.json diff](http://share.undpaul.de/bilder/jh/24f46ec9f74af9a6a83f__Working_Copy_master__4_Changed_Files_2015-02-06_18-07-22-xp3j3.png)

The full result composer.json is

```json
{
  "description": "Composer template for Drupal projects",
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "custom/package",
        "type": "metapackage",
        "version": "1.0.0",
        "require": {
          "derhasi/tempdirectory": "0.1.4"
        }
      }
    }
  ],
  "require": {
          "derhasi/tempdirectory": "0.1.4"
        },
  "require-dev": {
    "composer/composer": "dev-master"
  }
}
```

**Comment by alcohol** [comment] 2015-02-09 14:30
Cannot reproduce.
```
  [InvalidArgumentException]
  Package custom/package-1.0.0.0 must have a source or dist specified
```

**Comment by derhasi** [comment] 2015-02-09 14:33
Ah, sorry, forgot to update the package information to contain type metapackage, like it is in the gist. Update the example in the original post.

Package should look like
```json
    {
      "type": "package",
      "package": {
        "name": "custom/package",
        "type": "metapackage",
        "version": "1.0.0",
        "require": {
          "derhasi/tempdirectory": "0.1.4"
        }
      }
    }
```

**Comment by alcohol** [comment] 2015-02-09 14:41
Weir. 

I thought it might be related to the metapackage requiring the same package as your root `composer.json`, so I modified it:

```
{
  "description": "Composer template for Drupal projects",
  "repositories": [
    {
      "type": "package",
      "package": {
        "name": "custom/package",
        "type": "metapackage",
        "version": "1.0.0",
        "require": {
          "alcohol/iso3166": "~2.0"
        }
      }
    }
  ],
  "require": {
    "custom/package": "1.0.0",
    "derhasi/tempdirectory": "0.1.4",
    "rkr/wildcards": "~1.0"
  },
  "require-dev": {
    "composer/composer": "dev-master"
  }
}
```

However, a subsequent `composer install` and `composer remove rkr/wildcards` resulted in:
```
{
  description: Composer template for Drupal projects,
  repositories: [
    {
      type: package,
      package: {
        name: custom/package,
        type: metapackage,
        version: 1.0.0,
        require: {
          alcohol/iso3166: ~2.0
        }
      }
    }
  ],
  require: {
          alcohol/iso3166: ~2.0
        },
  require-dev: {
    composer/composer: dev-master
  }
}
```

This seems completely off indeed.
I'll see if I can determine the why and how and attempt to fix it.

**Comment by Seldaek** [comment] 2015-02-09 19:12
Should be fixed if you self-update, thanks @alcohol for the test case.

**Closed** 2015-02-09 19:11 UTC
Labels: Bug

**Comment by derhasi** [comment] 2015-02-10 08:06
Yeah, works now. Thanks for the fix :+1:
