### ISSUE TITLE
Failed to decode response: zlib_decode()

### ISSUE THREAD

**Issue by tarach** [composer/composer#4395] opened 2015-09-03 00:29 UTC
Hello,

I think this is an issue with one of the packagist repositories / branches packs... sorry I'm not that familiar with terminology. Either way when I fired `composer -vvv update` on my project a moment ago I got this:

```
( ... )
Downloading http://packagist.org/p/provider-2015-04$10e65066fc0e50a1f2f2fa14bcd1e0068c3cbffbd20d2ae7806be6d38ef9a066.json
Failed to decode response: zlib_decode(): data error
Retrying with degraded mode, check https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode for more info
( ... )
```
Previously the command just hung up after displaying that so I clear composer cache by using `rm -rf /home/vagrant/.composer/cache` and also used `composer self-update` from root account and `composer -vvv update` command completed:

```
( ... )
Reading ./composer.lock
Writing lock file
Generating autoload files
> post-update-cmd: php artisan optimize
Executing command (CWD): php artisan optimize
Generating optimized class loader
```

Is this error anything to worry about? Could it be my fault it occurred? 

~Cheers

**Comment by alcohol** [comment] 2015-09-05 14:57
We've had a range of issues with zlib_decode(), the degraded mode retries the download with some modifications to the process which in some cases seem to resolve the zlib_decode() issues. If you see this repeatedly, it means there is something funky going on, but as long as it finished the install/update process there is nothing serious to worry about.

**Comment by LukeNZ** [comment] 2015-09-19 09:03
Also getting this issue. Very frustrating, and composer is now unusable. Have tried clearing the cache with no success.

**Comment by mahdi-younesi** [comment] 2015-11-07 19:35
I have the same error and it's really A PAIN IN THE NECK.

**Comment by alcohol** [comment] 2015-11-09 09:27
Duplicate of #4121

**Closed by alcohol** 2015-11-09 09:27 UTC
Labels: Support

**Comment by MicroDreamIT** [comment] 2015-12-24 15:57
@alcohol brother now i am having same problem. Its really painful when setup gives a lot of pain.... :(

**Comment by samarulrajt** [comment] 2016-01-25 11:31
i found this link in the command line. It is related to bad internet connection as well as some firewall settings thta blocks to fetch data from outside. Cheers!

https://getcomposer.org/doc/articles/troubleshooting.md#degraded-mode

**Comment by tanveerahmaddar** [comment] 2016-02-01 17:06
i think its because of poor internet connection. try using high speed internet
